### ISSUE TITLE
是否考虑增加在IP变动时的webhook

### ISSUE THREAD

**Issue by tgly307** [jeessy2/ddns-go#10]
在IP变更后，希望能收到IP更新的通知，是否考虑增加相应的webhook？感谢

**Comment by jeessy2** [comment]
有什么应用场景呢

**Comment by tgly307** [comment]
一般IP变更出现在断线重连的时候，有些服务需要重新启动，如果有webhook之类的东西会比较方便。

**Comment by jeessy2** [comment]
可以支持。啥啥服务要断线重连？

**Comment by jeessy2** [comment]
1.3.0后支持。https://github.com/jeessy2/ddns-go/releases/tag/v1.3.0
支持变量方式，说明参考：https://github.com/jeessy2/ddns-go#webhook

**Comment by tgly307** [comment]
感谢支持！目前的实现形式是webhook和DNS服务商多选一，我期待的是修改DNS服务商的同时能够触发webhook，不过倒是也问题不大，可以通过启动2个来实现

**Comment by jeessy2** [comment]
域名更新成功后才触发？

**Comment by tgly307** [comment]
期待的场景是IP变更后更新域名的同时能够触发webhook，域名更新和触发webhook并行就可以，无所谓顺序。

**Comment by jeessy2** [comment]
就不依赖更新成功与否了嘛

**Comment by tgly307** [comment]
嗯，可以不依赖更新结果。不过我刚才想到，会不会有需要依赖更新结果的场景，在更新操作有结果后再触发webhook是不是也可以，在可选参数中增加更新结果，比如用在通知中什么的。

**Comment by tgly307** [comment]
比如通知内容可以是“IP地址以由xxx变更为xxx，域名更新成功”

**Comment by jeessy2** [comment]
简单点。更新成功后才触发webhook

**Comment by jeessy2** [comment]
成功与否都触发，在加一个是否成功的变量

**Comment by jeessy2** [comment]
试下这个版本：https://github.com/jeessy2/ddns-go/releases/tag/v1.4.0

**Comment by tgly307** [comment]
感谢，非常完美

**Comment by raining1123** [comment]
能否提供“域名更新未成功”不触发的选项呢？

**Comment by jeessy2** [comment]
> 能否提供“域名更新未成功”不触发的选项呢？

不支持，可以把webhook配置删除临时解决
