### ISSUE TITLE
解析到带端口号的二级域名 传参参数不详

### ISSUE THREAD

**Issue by zzzbaba** [jeessy2/ddns-go#1002]
### 功能描述

例如，需要把pipc.xxx.com通过传递自定义参数到xxx.com:7777
实际命令参数为？
pipc.xxx.com?RecordId=REDIRECT_URL&xxx.com:777 是这样吗
看官方文档没看太明白，感谢解答！

### 解决的问题

二级域名解析内网服务

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
自定义参数不是这么用的，实现的是地域解析或多IP

**Comment by zzzbaba** [comment]
> 自定义参数不是这么用的，实现的是地域解析或多IP

我只更新一条域名记录，比如picc.xxx.com，我看xxx.com也会更新，怎么保证只解析picc.xxx.com呢？

**Comment by jeessy2** [comment]
把xxx.com删除？

**Comment by zzzbaba** [comment]
学会了，是冒号，ipc:xxx.com

jeessy2 ***@***.***> 于2024年2月1日周四 20:15写道：
