### ISSUE TITLE
解析老是godaddy报错

### ISSUE THREAD

**Issue by PTCRY233** [jeessy2/ddns-go#1003]
### 问题描述

 报错的问题有：
2024/02/01 14:14:42 更新域名解析 ptcry.xyz 失败! 异常信息: Put "https://api.godaddy.com/v1/domains/ptcry.xyz/records/AAAA/@": read tcp 192.168.2.69:53258->2.18.153.85:443: wsarecv: An existing connection was forcibly closed by the remote host.
2024/02/01 16:16:28 更新域名解析 ptcry.xyz 失败! 异常信息: Put "https://api.godaddy.com/v1/domains/ptcry.xyz/records/AAAA/@": dial tcp [2a03:2880:f130:83:face:b00c:0:25de]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2024/02/01 15:58:14 更新域名解析 ptcry.xyz 失败! 异常信息: Put "https://api.godaddy.com/v1/domains/ptcry.xyz/records/AAAA/@": read tcp 192.168.2.83:44594->96.7.186.93:443: read: connection reset by peer
2024/02/01 15:47:43 更新域名解析 ptcry.xyz 失败! 异常信息: Put "https://api.godaddy.com/v1/domains/ptcry.xyz/records/AAAA/@": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
![IMG_20240201_142546](https://github.com/jeessy2/ddns-go/assets/55911222/b7c4615e-dbf9-4d70-858d-2163e680a563)
![IMG_20240201_142629](https://github.com/jeessy2/ddns-go/assets/55911222/2954f22d-8378-42e6-9d1d-e2dee074164a)

### DNS服务商

GoDaddy

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v6.1.0

### 安装方式

其它

**Comment by jeessy2** [comment]
检查你”网络“

**Comment by PTCRY233** [comment]
揪不出问题来了，累了，买了个其他服务商的域名就正常了，可能是godaddy的api过期了吧
