### ISSUE TITLE
无法获取IP地址

### ISSUE THREAD

**Issue by luyurun** [jeessy2/ddns-go#1004]
### 问题描述

已测试外网访问正常，已测试DNS解析正常，已测试正常访问域名服务器(AliDNS)

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

6.1.0

### 安装方式

其它

### 额外信息

`2024/02/01 23:27:29 You can use 'sudo .\ddns-go -s install' to install service`
`2024/02/01 23:27:29 监听 :9876`
`2024/02/01 23:27:29 通过接口获取IPv4失败! 接口地址: https://myip4.ipip.net`
`2024/02/01 23:27:29 异常信息: Get "https://myip4.ipip.net": dial tcp4: lookup myip4.ipip.net: no such host`

**Comment by jeessy2** [comment]
指定dns

**Comment by luyurun** [comment]
感谢回复与协助。

电脑已手动指定DNS地址：
主要DNS：`8.8.8.8`
次要DNS：`208.67.222.222`

已使用`ipconfig /flushdns`刷新，尝试过重启，问题依旧。

**Comment by jeessy2** [comment]
myip4.ipip.net 这个应该用不了了
