### ISSUE TITLE
无法更新域名解析

### ISSUE THREAD

**Issue by zhaoxuyan** [jeessy2/ddns-go#1007]
### 问题描述

无法更新域名解析

### DNS服务商

GoDaddy

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v6.1.1

### 安装方式

其它

### 额外信息

更新域名解析 zxyjelly.xyz 失败! 异常信息: Put "https://api.godaddy.com/v1/domains/zxyjelly.xyz/records/AAAA/@": dial tcp [2a03:2880:f10e:83:face:b00c:0:25de]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by jeessy2** [comment]
#1003
