### ISSUE TITLE
密码忘记了怎么办

### ISSUE THREAD

**Issue by 1359450511** [jeessy2/ddns-go#1008]
### 功能描述

设置了安全密码，现在密码忘记了，进不到webUI里面了怎么办，有方法么

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
https://github.com/jeessy2/ddns-go/wiki/FAQ

**Comment by 1359450511** [comment]
openwrt 路由器配置文件再哪个路径下

**Comment by 1359450511** [comment]
密码忘记了，openwrt 路由器

**Comment by jeessy2** [comment]
`find / -name ddns`

**Comment by 1359450511** [comment]
我还是不明白怎么弄，我尝试在openwrt的终端窗口中输入 find -name ddns 但是什么也没有发生，我的密码要怎么找回

**Comment by jeessy2** [comment]
自行网上搜索怎么查找文件

**Comment by cgwxq** [comment]
docker的配置文件在哪呢

> 手机网上搜索怎么查找文件
