### ISSUE TITLE
请求添加对dnspod国际版的支持

### ISSUE THREAD

**Issue by houpi** [jeessy2/ddns-go#101]
如题！！！

**Comment by jeessy2** [comment]
dnspod国际版比cloudflare有啥优势?

**Comment by houpi** [comment]
dnspod的api可以支援freenom的免费域名.tk  .ml  .ga
而后者很多人都在用的。而国际版不用实名让人稍放心。

**Comment by jeessy2** [comment]
后面有空在考虑实施，如果会点golang欢迎提PR

**Comment by houpi** [comment]
对比acme文件后得出以下进展：

在dnspod官方文档中https://docs.dnspod.com/api/5fe1b40a6e336701a2111f5b/
使用的是user_token参数

acme文件中https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_dpi.sh#L116
使用的是login_token参数

后使用官方文档中的curl -X POST 方法测试后发现，acme可以取得正确返回值，官方的验证失败
希望以上发现能够给完善代码节省时间

**Comment by jeessy2** [comment]
ok

**Comment by jeessy2** [comment]
嗯

**Comment by houpi** [comment]
> login_token中的星星替换实际的没有

那肯定替换了，包括我打开/opt/ddns-go/.ddns_go_config.yaml文件核对了，token信息没有错，我copy下来用curl命令在同一台机更新IP成功。

**Comment by arho14** [comment]
国际版用这个接口 https://api.dnspod.com/Record.Ddns 可以免费ttl 10
