### ISSUE TITLE
新增域名解析 xxx.xxx.in 失败! 异常信息: 当前域名未添加解析，请返回域名列表。

### ISSUE THREAD

**Issue by Chinakentgao** [jeessy2/ddns-go#1014]
### 问题描述

外面测试域名解析什么都正常，工具一直提示解析失败。根本不知道问题在哪里，删了内置几个ipV4的网站地址逐个测试也是一样问题。

### DNS服务商

腾讯云

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v6.1.1

### 安装方式

其它

### 额外信息

2024/02/13 00:50:35 监听 :9876
2024/02/13 00:51:39 配置文件已保存在: C:\Users\Administrator\.ddns_go_config.yaml
2024/02/13 00:51:39 通过接口获取IPv4失败! 接口地址: https://myip4.ipip.net
2024/02/13 00:51:39 异常信息: Get "https://myip4.ipip.net": dial tcp4: lookup myip4.ipip.net: no such host
2024/02/13 00:51:40 新增域名解析 x.x.in 失败! 异常信息: 当前域名未添加解析，请返回域名列表。
2024/02/13 00:52:15 配置文件已保存在: C:\Users\Administrator\.ddns_go_config.yaml
2024/02/13 00:52:15 通过接口获取IPv4失败! 接口地址: https://myip4.ipip.net
2024/02/13 00:52:15 异常信息: Get "https://myip4.ipip.net": dial tcp4: lookup myip4.ipip.net: no such host
2024/02/13 00:52:15 新增域名解析 x.x.in 失败! 异常信息: 当前域名未添加解析，请返回域名列表。
2024/02/13 00:55:36 通过接口获取IPv4失败! 接口地址: https://myip4.ipip.net
2024/02/13 00:55:36 异常信息: Get "https://myip4.ipip.net": dial tcp4: lookup myip4.ipip.net: no such host
2024/02/13 00:55:36 新增域名解析 x.x.in 失败! 异常信息: 当前域名未添加解析，请返回域名列表。

**Comment by jeessy2** [comment]
域名填写正确没有

**Comment by Chinakentgao** [comment]
正确测试几个域名都这样不知道什么情况



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月13日(周二) 上午9:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeessy2/ddns-go] 新增域名解析 xxx.xxx.in 失败! 异常信息: 当前域名未添加解析，请返回域名列表。 (Issue #1014)




 
域名填写正确没有

**Comment by Chinakentgao** [comment]
刚才又测试一轮改了DNS参数还是一样不知道什么问题了。

**Comment by jeessy2** [comment]
账号下有这个域名？

**Comment by Chinakentgao** [comment]
主域名是别人的，但是子域名授权给我了。我可以控制子域名的解析。我现在在等服务器更新完试试直接用公网ip看看是不是解析内网ip的问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月13日(周二) 中午11:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeessy2/ddns-go] 新增域名解析 xxx.xxx.in 失败! 异常信息: 当前域名未添加解析，请返回域名列表。 (Issue #1014)




 
账号下有这个域名？

**Comment by jeessy2** [comment]
用冒号分割，下方有说明

**Comment by Chinakentgao** [comment]
找到问题了。。@:linxueren.moonnight.in得这样写


凬清沄淡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeessy2/ddns-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月13日(星期二) 中午11:06
***@***.***&gt;;
抄送:&nbsp;"Kent ***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeessy2/ddns-go] 新增域名解析 xxx.xxx.in 失败! 异常信息: 当前域名未添加解析，请返回域名列表。 (Issue #1014)





 
用冒号分割，下方有说明
