### ISSUE TITLE
porkbun 查询域名信息发生异常

### ISSUE THREAD

**Issue by Childish-Ghost** [jeessy2/ddns-go#1015]
### 问题描述

查询域名信息发生异常! 返回内容: {"status":"ERROR","message":"Domain is not opted in to API access."} ,返回状态码: 400 

### DNS服务商

Porkbun

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

FreeBSD

### 架构

x86_64

### 版本

v6.1.1

### 安装方式

服务

**Comment by jeessy2** [comment]
porkbun需要勾选api访问
