### ISSUE TITLE
无法获取cloudflare纯数字域名？

### ISSUE THREAD

**Issue by jas0nxu** [jeessy2/ddns-go#1016]
### 问题描述

购买了spaceship六位纯数字的xyz域名，并且转移到cloudflare进行dns解析

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v6.1.1

### 安装方式

Docker

### 额外信息

2024/02/15 22:55:22 在DNS服务商中未找到域名: remote.123456.xyz

**Comment by jas0nxu** [comment]
以前那些cf、tk域名cf不再支持的域名api会返回一长串调用失败信息，没有api失败的报错信息，感觉不是api失败

**Comment by jeessy2** [comment]
Cloudflare中有那个域名？

**Comment by jas0nxu** [comment]
> Cloudflare中有那个域名？

cloudflare里有那个域名的，电脑ping对应域名也能得到cloudflare里边设置的IP地址。我等会更新一下api token试试有没有变化

**Comment by jas0nxu** [comment]
更新token后可以了，不好意思叨扰了，感谢你分享这个超好用工具

**Comment by metaforget** [comment]
请问一下spaceship有官方的api能修改域名解析吗，我也想买一个
