### ISSUE TITLE
请问能否同时使用多种方式通知？

### ISSUE THREAD

**Issue by caliban511** [jeessy2/ddns-go#1017]
### 功能描述

如题。
习惯了同时在微信和tg上接受通知，
主要是平时用tg比较多，微信不常开且后台锁死，
不过因为众所周知的问题tg偶尔可能会上不去，需要去微信上查看消息，，，
目前的webhook只能选填其中一种，
能否让用户同时配置多个通知方式？有通知时多平台同时发送？

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
不支持，暂无计划支持

**Comment by caliban511** [comment]
> 不支持，暂无计划支持

好的，谢谢大佬回复。
