### ISSUE TITLE
好东西，mark了，但是有两个问题

### ISSUE THREAD

**Issue by Li-Lian1069** [jeessy2/ddns-go#102]
1. 能否在设置页面添加一个控制重新绑定时间的功能
2. 在默认情况下，是多久同步一次呢？

这个项目解决我燃眉之急，谢谢你！！

**Comment by jeessy2** [comment]
默认5分钟同步一次。时间在页面修改和目前方式不同了，目前这个方式也还是可以的，后面有机会在考虑了

**Comment by Li-Lian1069** [comment]
ok，感谢蛤~
