### ISSUE TITLE
请问内网虚拟机怎么获取拨号主路由的IPv6地址？

### ISSUE THREAD

**Issue by caliban511** [jeessy2/ddns-go#1020]
### 功能描述

如题。
ddns-go 是布置在局域网内的一台虚拟机上，用docker跑的。
实测获得的IPv6地址是该docker宿主机的地址，而不是拨号主路由的公网地址。
请教一下，要怎么才能获得拨号主路由的IPv6地址？

找了半天，找到大佬你发的这个命令：
ip -6 route | awk '{print $1}' | awk '/2409:?/' | awk -F::/ '{print $1 "any other suffix of other mac"}'
但，拨号主路由的公网IP地址是：
240e:958:1c06:947:****:****:****:****/64
网内其他机器的IPv6地址是：
240e:95b:1d40::*/60
240e:95b:1d40::*/128
连前缀都不一样，，，

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
不用虚拟机，获取的前缀多少

**Comment by caliban511** [comment]
> 不用虚拟机，获取的前缀多少
没看明白，，上面列出的IPv6地址是在主路由里查看到的，不是用 ddns-go 获取的

**Comment by jeessy2** [comment]
找台安装在物理机，看IPv6

**Comment by caliban511** [comment]
> 找台安装在物理机，看IPv6

啊，那算了，麻烦大佬了，，，小白只会玩下docker，，，😂😂😂
