### ISSUE TITLE
忘记远程登陆账户密码了如何查询或重置密码？

### ISSUE THREAD

**Issue by uki4ray** [jeessy2/ddns-go#1022]
### 问题描述

环境：威联通nas，通过portainer创建的ddns-go，模板如下：
version: "3.8"
services:
ddns-go:
image: jeessy/ddns-go
container_name: ddns-go-1
volumes:
- /share/Container/ddnsgo:/root
restart: always
network_mode: host
挂载的ddnsgo文件夹中无.ddns_go_config.yaml文件。同样看了下黑裙下面挂载的ddnsgo文件夹中是存在该文件的…
现在该如何查询或重置密码？

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

latest

### 安装方式

Docker

**Comment by jeessy2** [comment]
是个隐藏文件。未使用过威联通，自行搜索怎么看

**Comment by FrozenGEE** [comment]
.ddns_go_config.yaml是一个隐藏文件，正常是无法直接查看的，你需要在ssh里面用vi命令去编辑才可以看到

**Comment by minhongqi** [comment]
> ssh里面用vi命令去编辑

win下没找到.ddns_go_config.yaml这个文件怎么办？

**Comment by WaterLemons2k** [comment]
> win下没找到.ddns_go_config.yaml这个文件怎么办？打开文件夹隐藏项目也没有

用 [Everything](https://www.voidtools.com/zh-cn/#everything)

**Comment by minhongqi** [comment]
> > win下没找到.ddns_go_config.yaml这个文件怎么办？打开文件夹隐藏项目也没有
> 
> 用 [Everything](https://www.voidtools.com/zh-cn/#everything)

牛，感谢哥

**Comment by xiaobaidadada** [comment]
在docker中运行的。docker exec -it ddns-go sh 然后 find / -name *.ddns-go*" 就可以找到了密码所在的文件了。

**Comment by swjtuhyq** [comment]
Centos命令行运行的，也无法找到配置文件，我要怎么才找到它呢？
