### ISSUE TITLE
更新6.1.2以后ipv4通过接口解析依然报错

### ISSUE THREAD

**Issue by kingsleygithub001** [jeessy2/ddns-go#1026]
### 问题描述

异常信息: Get "https://myip4.ipip.net": dial tcp4: lookup myip4.ipip.net on 192.168.31.1:53: no such host

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v6.1.2

### 安装方式

Docker

**Comment by jeessy2** [comment]
更新没有用。因为是之前的配置，需要要手动改。全新的配置才会默认最新的

**Comment by kingsleygithub001** [comment]
> 更新没有用。因为是之前的配置，需要要手动改。全新的配置才会默认最新的

确实，已解决
