### ISSUE TITLE
cloudflare返回400

### ISSUE THREAD

**Issue by tingxi1** [jeessy2/ddns-go#1027]
### 问题描述

配置第一次能正常解析，后面就突然返回400了

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

6.1.2

### 安装方式

Docker

### 额外信息

2024/02/23 09:51:08 新增域名解析 泥儿.com 失败! 异常信息: 返回内容: {"result":null,"success":false,"errors":[{"code":81057,"message":"Record already exists."}],"messages":[]} ,返回状态码: 400

**Comment by jeessy2** [comment]
是不是有自定义参数

**Comment by tingxi1** [comment]
> 是不是有自定义参数

没有啊，第一次按照这个走他都正常解析好了的

**Comment by tingxi1** [comment]
> 是不是有自定义参数
哎呀找到问题了，我是中文域名
