### ISSUE TITLE
建议添加对IPV6地址的选择选项

### ISSUE THREAD

**Issue by Li-Lian1069** [jeessy2/ddns-go#103]
![微信截图_20210912121015](https://user-images.githubusercontent.com/42291113/132971852-e0d481ed-fb7a-488b-bf15-8ae4c0e7c4b1.png)

如图，我获取到两个公网的IPV6，但是第一个地址是临时的地址，是无法使用的，ping不通

![image](https://user-images.githubusercontent.com/42291113/132971868-6366d36b-ac90-45aa-8f2f-4aa6878865ed.png)

建议可以根据ip地址的特征（比如前缀长度、 scopeid 等）提供多个选项，给用户选择的余地

**Comment by jeessy2** [comment]
第一个公网ipv6应该不是临时的吧，可以正常使用，检查一下你那边网络环境呢。
也可以试下通过接口获取，接口获取的一般都是临时地址
通过前缀长度匹配地址也可以考虑

**Comment by Li-Lian1069** [comment]
我这边移动第一个获取的就是临时地址，试过n多遍只有第二个前缀64的好使

**Comment by jeessy2** [comment]
未遇到这种情况。那你试下通过接口获取v6

**Comment by Li-Lian1069** [comment]
接口获取的也是临时ipv6

**Comment by jeessy2** [comment]
临时的v6也可以通的吧，检查一下配置这些呢

**Comment by jeessy2** [comment]
程序应该直接过滤前缀128的
前缀128这种情况外网是不能访问的
不知道你的怎么配置的, 有一个前缀128的IPv6地址

**Comment by Li-Lian1069** [comment]
没有任何配置，这是移动自己给的。临时可以通，但是tcp连接在大约三分钟之后就会被强制断开，而且非常不稳定

**Comment by jeessy2** [comment]
换台电脑看获取的IPv6 prefix还是不是128位

**Comment by jeessy2** [comment]
3.0.0已过滤128位的前缀。下载后试下

**Comment by Li-Lian1069** [comment]
感谢大佬，问题解决了。
不过这个128位的ip我还是没有搞懂哪来的，可能是因为centos自动禁用使用临时ip的功能，所以移动看我不爽强行给我分配了个128的地址。另外windows看不到前缀长度，所以我也不知道怎么判断了。手头两台centos的机器都是这样。

另外，关于禁止使用临时地址的，大佬可以看下这篇文章：https://blog.csdn.net/weixin_30462049/article/details/98268751
