### ISSUE TITLE
当在阿里云账号中的域名是子域名时会运行出错

### ISSUE THREAD

**Issue by BA7JCM** [jeessy2/ddns-go#1030]
### 问题描述

比如说现有一个域名test.com，我分出去一个temp.test.com给我朋友，让他添加到他账号下的阿里云dns里去解析（阿里云是可以免费添加子域名去解析的），然后在程序里的域名的时候填的"temp.test.com"，程序去请求阿里云的api会报400错误，返回
```json
{"RequestId":"（省略requestID）","HostId":"alidns.aliyuncs.com","Code":"IncorrectDomainUser","Message":"The domain name belongs to other users. Transfer the domain name to the current user and then try the binding and setting actions.","Recommend":"https://api.aliyun.com/troubleshoot?q=IncorrectDomainUser&product=Alidns&requestId=（省略requestID）"}
```
推测可能是直接拿主域名test.com去拼凑payload了，而这个账号只拿到其中一个子域名和它的再下一级域名的解析，进而导致的报错“IncorrectDomainUser”

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v6.1.2

### 安装方式

服务

**Comment by WaterLemons2k** [comment]
用冒号分割

**Comment by BA7JCM** [comment]
> 用冒号分割

感谢，尝试后已解决
