### ISSUE TITLE
重启OP路由器之后， 一定要重启ddns-go 才正常

### ISSUE THREAD

**Issue by owen-gu** [jeessy2/ddns-go#1032]
### 问题描述

重启OP路由器之后， 一定要重启ddns-go 才正常

等待网络连接：Get "https://porkbun.com/api/json/v3/dns": context deadline exceeded (Client.Timeout exceeded while awaiting headers)。5s 后重试...

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

5.6.1

### 安装方式

其它

**Comment by owen-gu** [comment]
还是没有生效， 必须重启DDNS-go 才能正常工作

**Comment by jeessy2** [comment]
try v6.2.0

**Comment by jeessy2** [comment]
v6.3.0之后修复
