### ISSUE TITLE
我在外网服务器使用, 网页打开，里面没有任何服务商选项

### ISSUE THREAD

**Issue by maya413** [jeessy2/ddns-go#1036]
### 问题描述

我在外网服务器使用, 网页打开，里面没有任何服务商选项
![微信截图_20240310165800](https://github.com/jeessy2/ddns-go/assets/41216622/e7088a8e-77f6-491e-849f-b077391a9ec7)

### DNS服务商

腾讯云

### 是否已搜索同类问题

未搜索

### 操作系统

Windows

### 架构

x86_64

### 版本

最新版本ddns-go 6.2

### 安装方式

其它

**Comment by jeessy2** [comment]
换一个新的浏览器

**Comment by maya413** [comment]
![微信截图_20240310171201](https://github.com/jeessy2/ddns-go/assets/41216622/dba0f55d-d230-4425-9d4d-8a064256393f)
x现在有选项，但是命令行一直不动，不执行解析操作

**Comment by jeessy2** [comment]
域名填了？

**Comment by maya413** [comment]
噢，哈哈忘记填了
