### ISSUE TITLE
ddns-go_6.2.0_windows_x86_64.zip 下载报毒，被Windows11自动删除

### ISSUE THREAD

**Issue by CarlosLucky** [jeessy2/ddns-go#1037]
### 问题描述

想下载最新版本，Windows11 系统下载完后立即报毒查杀
![屏幕截图 2024-03-10 183810](https://github.com/jeessy2/ddns-go/assets/105660964/74cb8095-1285-465c-9cc9-c86c8fe3387d)
![屏幕截图 2024-03-10 183914](https://github.com/jeessy2/ddns-go/assets/105660964/c947d182-c492-4044-939c-29d9d3bd655d)

### DNS服务商

其它

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v6.2.0

### 安装方式

其它

### 额外信息

之前版本都没有这个情况。

**Comment by jeessy2** [comment]
下之前版本，可能是升级了一个包，不知道是不是误报
