### ISSUE TITLE
今天运行了个代理，ddnsgo是用的1panel带的docker

### ISSUE THREAD

**Issue by XBWAP** [jeessy2/ddns-go#1039]
### 问题描述

不知道为啥出现这个
2024/03/15 18:31:28 监听 :9876
2024/03/15 18:31:34 查询域名信息发生异常! Post "https://dnspod.tencentcloudapi.com": http: server gave HTTP response to HTTPS client
2024/03/15 18:36:34 查询域名信息发生异常! Post "https://dnspod.tencentcloudapi.com": http: server gave HTTP response to HTTPS client

### 是否已搜索同类问题

未搜索

### 操作系统

Linux

### 架构

x86_64

### 版本

realest

### 安装方式

Docker

**Comment by WaterLemons2k** [comment]
可能是代理导致的证书问题，请尝试禁用代理。

参考：https://stackoverflow.com/questions/56488377/http-server-gave-http-response-to-https-client
