### ISSUE TITLE
可不可以同时设置局域网里的多个域名的ddns

### ISSUE THREAD

**Issue by Ryker97** [jeessy2/ddns-go#104]
是不是只能设置本设备的DDNS，无法设置局域网内的其他设备的DDNS。例如我把这个装在旁路由上，然后设置局域网内其他暂时不能安装这个插件的设备的DDNS。

**Comment by jeessy2** [comment]
目前不支持. 同#31

**Comment by Ryker97** [comment]
大佬有计划更新版本支持这个功能吗？

**Comment by jeessy2** [comment]
获取局域网其它电脑的IPv6, 主流方案是根据MAC地址获取的IPv6(如爱快系统)
但是有以下问题:
- mac/windows几代前已不支持通过MAC地址生成IPv6(为了保护隐私, 防止网站追踪)
- linux可以通过配置来使用MAC地址获取IPv6

总结如下:
- 支持的系统较少, 不完整
- 隐私问题严重
- 如果有新的方案, 及时讨论

建议:
- 目前建议独立安装DDNS-GO

**Comment by Ryker97** [comment]
可不可以通过终端DUID来获取其他设备的ipv6？

**Comment by jeessy2** [comment]
> 可不可以通过终端DUID来获取其他设备的ipv6？

duid怎么来获取？网上没看到有人这么操作过

**Comment by Ryker97** [comment]
https://blog.csdn.net/qq_38265137/article/details/80466734
这个估计得要深入研究一下DHCPV6的工作原理。我查了一圈也没找到类似的解决途径。我猜想看客户端能不能够通过发送组播的方式获取到这个组播网络中其他设备的duid，因为这个duid是唯一的，而且设备需要不断发送这个duid来延长自己的v6地址

**Comment by laok133** [comment]
> 

家里都没软路由,假设有了软路由,这个项目没存在的价值,软路由内置 ipv4&ipv6 ddns解析,
我已知在爱快&ros.ipv4的环境下,一个域名 无限二域 ddns
