### ISSUE TITLE
用的1Panel安装的ddns-go ,刚开始解析还好好的，不知道哪里变动了开始报错，权限都给了

### ISSUE THREAD

**Issue by Syz87** [jeessy2/ddns-go#1044]
### 问题描述

更新域名解析  失败! 异常信息: 返回内容: {"RequestId":"1922FA25-0F1D-51D2-BBAE-8EC5C3A26E64","HostId":"alidns.aliyuncs.com","Code":"DomainRecordDuplicate","Message":"The DNS record already exists.","Recommend":"https://api.aliyun.com/troubleshoot?q=DomainRecordDuplicate&product=Alidns&requestId=1922FA25-0F1D-51D2-BBAE-8EC5C3A26E64"} ,返回状态码: 400

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v6.2.1

### 安装方式

Docker

**Comment by Syz87** [comment]
> The DNS record already exists. 域名存在了。用了自定义参数？

没有啊，我只启用了ipv6，添加了www. 域名 @.域名  还有一个ruskery.域名，然后启用了企业微信的推送

**Comment by jeessy2** [comment]
那你自行检查，提示有相同的记录了
