### ISSUE TITLE
webhook如何设置多个headers ?

### ISSUE THREAD

**Issue by XF2886** [jeessy2/ddns-go#1045]
### 问题描述

设置单个headers是没有问题的 , 设置多个headers时按照文本域下方的提示 , 一行一个 , 会提示如下内容
~~~
2024/03/18 11:57:16 Webhook Header不正确: Authorization:Bearer tk_xxx
Content-Type: application/json
~~~

我也尝试了其他分隔方式 , 均不生效

~~~
2024/03/18 11:57:21 Webhook Header不正确: Authorization:Bearer tk_xxx,
Content-Type: application/json
~~~

~~~
2024/03/18 11:57:29 Webhook Header不正确: Authorization:Bearer tk_xxx;
Content-Type: application/json
~~~

~~~
2024/03/18 11:57:34 Webhook Header不正确: Authorization:Bearer tk_xxx|
Content-Type: application/json
~~~

![QQ截图20240318130708](https://github.com/jeessy2/ddns-go/assets/77381998/cf64e521-53d7-44b4-8564-e3697668e33e)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

 v6.2.0

### 安装方式

服务

**Comment by WaterLemons2k** [comment]
不用设置 `Content-Type` Header，会自动添加。

https://github.com/jeessy2/ddns-go/blob/23f39fb06542b49e8078de5676bb5cd10f9a0ce0/config/webhook.go#L87

**Comment by XF2886** [comment]
> 不用设置 `Content-Type` Header，会自动添加。
> 
> https://github.com/jeessy2/ddns-go/blob/23f39fb06542b49e8078de5676bb5cd10f9a0ce0/config/webhook.go#L87

感谢 ! 看了一下源码 , contentType默认是`application/x-www-form-urlencoded` , 当RequestBody是JSON的时候会替换成`application/json` , 但是我不能自定义Content-Type吗 ? 例如`Content-Type: text/markdown`

另外我需要设置其他的也是不生效的 ? 例如 :
~~~
title:123
~~~

~~~
2024/03/18 13:47:48 Webhook Header不正确: Authorization:Bearer tk_xxx
title:123
~~~

**Comment by WaterLemons2k** [comment]
> 但是我不能自定义Content-Type吗 ? 例如`Content-Type: text/markdown`

暂时不支持。

> 另外我需要设置其他的也是不生效的 ? 例如 :
> 
> ~~~
> 
> title:123
> 
> ~~~
> 
> 
> 
> ~~~
> 
> 2024/03/18 13:47:48 Webhook Header不正确: Authorization:Bearer tk_xxx
> 
> title:123
> 
> ~~~

https://github.com/jeessy2/ddns-go/blob/23f39fb06542b49e8078de5676bb5cd10f9a0ce0/config/webhook.go#L147

输入没问题，应该是检查 Headers 的函数 `checkParseHeaders` 有问题，一会看一下。
