### ISSUE TITLE
【BUG】Webhook 发送钉钉消息

### ISSUE THREAD

**Issue by zy0311** [jeessy2/ddns-go#1048]
### 问题描述

Webhook 发送钉钉测试消息时，总是提示返回数据：{"errcode":500100,"errmsg":"description:系统异常，请稍后再试;"}

经过测试，手动调用钉钉URL是没有问题的。

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v6.2.1

### 安装方式

Docker

**Comment by jeessy2** [comment]
咨询钉钉，或网上自行搜索

**Comment by zy0311** [comment]
> 咨询钉钉，或网上自行搜索

钉钉没问题的，通过Fiddler测试请求，包括在其它项目里使用都没有问题。所以，我想了解此项目如何能知道请求的header与body。排查一下问题。

**Comment by jeessy2** [comment]
header和body是你填写的，变量会自动替换真实值。
