### ISSUE TITLE
多个IPv6地址支持

### ISSUE THREAD

**Issue by Aimeast** [jeessy2/ddns-go#1053]
### 功能描述

每个终端都会有主IPv6地址和临时IPv6地址，希望支持将多个地址更新到DDNS的功能。
因为我遇到的网络环境下，有的IPv6地址只能内网访问，有的IPv6地址只能外网访问。希望多个地址都更新到DDNS，增加连通概率。

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
参考传递自定义参数

**Comment by Aimeast** [comment]
是否有示例？找了文档、找了issues、找了google，没找到多ip的示例。

**Comment by jeessy2** [comment]
https://github.com/jeessy2/ddns-go/wiki/%E4%BC%A0%E9%80%92%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%82%E6%95%B0

**Comment by Aimeast** [comment]
这个页面看过很多遍愣是没看懂。这个参数怎么填，怎么传递多个ipv6地址。

**Comment by jeessy2** [comment]
都写了，自己想折腾就自行研究

**Comment by caliban511** [comment]
我也想知道这个参数该怎么填？去翻阿里云的文档也是云里雾里的，自己填一串数字好像也没什么作用，，等一位不打机锋的大佬，，，😂😂😂

![Screenshot_2024-03-29-02-08-40-512_org mozilla firefox](https://github.com/jeessy2/ddns-go/assets/13557387/c518db6c-9dc3-4043-912b-6b75bbbdde35)

**Comment by jeessy2** [comment]
阿里云 RecordId 可通过 阿里云 -> 解析设置 -> F12 调试 -> 网络 -> list.json -> 预览 -> data 获取。

**Comment by caliban511** [comment]
> 阿里云 RecordId 可通过 阿里云 -> 解析设置 -> F12 调试 -> 网络 -> list.json -> 预览 -> data 获取。

谢谢大佬。我看看去。👍

**Comment by Aimeast** [comment]
作者的文档确实很难猜，回复也非常高傲。

思考了很久灵机一动，实现一个子域名更新多IP的方式是这样的：
1. 新建两个相同的子域名，随便填个IP。这时你就有了这两个子域名的RecordID。PS：获取RecordID方式上面已有。
2. ddns-go上新建两个任务（当然可用相同的token），一个用`@1`获取第一个IP，一个用`@2`获取第二个IP。推送自定义参数在域名后加上`?RecordId=xx`。
3. 如果有3个IP也是类似的。
4. 只有 阿里云 和 DnsPod 的API支持RecordID参数。注，虽然腾讯云就是dnspod，但是RecordID参数不支持腾讯云的API。

但这有个bug，日志一直没完没了的刷新提醒。

**Comment by jeessy2** [comment]
你的思路是对的。就是步骤有点多，难得写文档

**Comment by Jenpo** [comment]
匹配DUID吧，iKuai的ddns服务是这个逻辑
