### ISSUE TITLE
希望支持西部数码

### ISSUE THREAD

**Issue by 1049731887** [jeessy2/ddns-go#1054]
### 功能描述

https://console-docs.apipost.cn/preview/bf57a993975b67e0/7b363d9b8808faa2?target_id=3884598e-7ad3-4582-8617-c287ea7ee337

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
太多服务商，建议转
