### ISSUE TITLE
openwrt 重启路由器，提示等待网络连接

### ISSUE THREAD

**Issue by kern111** [jeessy2/ddns-go#1056]
### 问题描述

用这个命令也没有用./ddns-go -dns 114.114.114.114
路由器重启之后，ddns go总是默认使用1.1.1.1的dns更新ip。但是我们这1.1.1.1这个不能用。
每次都要到路由器里面关闭，再重新启动ddnsgo，才能使用页面指定的dns更新ip。
如何把默认的1.1.1.1这个dns改了呢？
![1711351390](https://github.com/jeessy2/ddns-go/assets/105206657/ed568df6-5310-4f36-958d-3a664c5275b7)

### DNS服务商

Callback

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

9aee04b5-46

### 安装方式

服务

**Comment by jeessy2** [comment]
日志及版本发一下

**Comment by kern111** [comment]
2024/03/25 16:12:44 等待网络连接: lookup bcd.baidubce.com on [::1]:53: dial udp 1.1.1.1:53: connect: network is unreachable
2024/03/25 16:12:44 5s 后重试...
2024/03/25 16:13:29 等待网络连接: lookup api.cloudflare.com on [::1]:53: read udp 192.168.1.2:41477->1.1.1.1:53: i/o timeout
2024/03/25 16:13:29 5s 后重试...
2024/03/25 16:14:14 等待网络连接: lookup dnsapi.cn on [::1]:53: read udp 192.168.1.2:51930->1.1.1.1:53: i/o timeout
2024/03/25 16:14:14 5s 后重试...
不显示具体的版本
![1711354584](https://github.com/jeessy2/ddns-go/assets/105206657/60ebecf5-9f6b-4920-97aa-664fc121c7bc)

**Comment by jeessy2** [comment]
界面右上角看版本

**Comment by jeessy2** [comment]
还有出现`本机DNS异常! 将默认使用1.1.1.1...`的日志也有, 顺便发一下？

**Comment by kern111** [comment]
确实没有版本信息
![Uploading 1711355722.png…]()

**Comment by kern111** [comment]
![1711355722](https://github.com/jeessy2/ddns-go/assets/105206657/09da7dbb-d231-4791-94dd-21c545429ff1)

**Comment by kern111** [comment]
https://dl.openwrt.ai/packages-23.05/x86_64/kiddin9/ddns-go_9aee04b5-46_x86_64.ipk
就是用的这个

**Comment by jeessy2** [comment]
v6.3.0修复，不过用的openwrt，得等插件那方升级

**Comment by AmiroKD** [comment]
> 2024/03/25 16:12:44 等待网络连接: lookup bcd.baidubce.com on [::1]:53: dial udp 1.1.1.1:53: connect: network is unreachable 2024/03/25 16:12:44 5s 后重试... 2024/03/25 16:13:29 等待网络连接: lookup api.cloudflare.com on [::1]:53: read udp 192.168.1.2:41477->1.1.1.1:53: i/o timeout 2024/03/25 16:13:29 5s 后重试... 2024/03/25 16:14:14 等待网络连接: lookup dnsapi.cn on [::1]:53: read udp 192.168.1.2:51930->1.1.1.1:53: i/o timeout 2024/03/25 16:14:14 5s 后重试... 不显示具体的版本 ![1711354584](https://private-user-images.githubusercontent.com/105206657/316431422-60ebecf5-9f6b-4920-97aa-664fc121c7bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDczNjksIm5iZiI6MTczMjUwNzA2OSwicGF0aCI6Ii8xMDUyMDY2NTcvMzE2NDMxNDIyLTYwZWJlY2Y1LTlmNmItNDkyMC05N2FhLTY2NGZjMTIxYzdiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwMzU3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2M0ZGIyNGIwMTNkMmM1YjBmMGMwYTZjN2NlZjQwMGVkYmRkZjA3NDA2MjUwYTgzNmUzNWRkZjM1MDUyZTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fXxM8sPhH9cRxQuz7-JhOULwFy8Wl86c7HQvUMObNP0)

我也是这个问题，请问该怎么解决
