### ISSUE TITLE
希望能够支持Qmsg

### ISSUE THREAD

**Issue by yyxida** [jeessy2/ddns-go#106]
现在用[Qmsg](https://qmsg.zendee.cn/index.html)有点问题 ,直接用以下方法时会出现400错误
```
https://qmsg.zendee.cn/send/<key>?msg=家中宽带IP发生变更,当前IPV4:#{ipv4Addr},变更状态:#{ipv4Result}；当前IPV6:#{ipv6Addr},变更状态:#{ipv6Result}
msg=#{ipv4Addr},:#{ipv4Result};#{ipv6Addr},:#{ipv6Result}
msg=家中宽带IP发生变更
```
`2021/09/15 17:14:11 监听 :9876 ...
2021/09/15 17:14:30 请求接口 https://qmsg.zendee.cn/send/<key>?msg=家中宽带IP发生变更,当前IPV4:127.0.0.1,变更状态:成功；当前IPV6:::1,变更状态:成功 失败! 返回内容:
HTTP Status 400 – Bad Request
,返回状态码: 400
2021/09/15 17:14:30 Webhook调用失败，Err：请求接口 https://qmsg.zendee.cn/send/<key>?msg=家中宽带IP发生变更,当前IPV4:127.0.0.1,变更状态:成功；当前IPV6:::1,变更状态:成功 失败! 返回内容:
HTTP Status 400 – Bad Request
,返回状态码: 400`
但是在ddns-go中只推送但数字和英文字母是可以用的
```
msg=123123
msg=aaabbbccc

```
`2021/09/15 17:15:31 Webhook调用成功, 返回数据: {"success":true,"reason":"操作成功","code":0,"info":{}}`

**Comment by jeessy2** [comment]
已处理. 等待发布3.0

**Comment by yyxida** [comment]
> 已发布3.0.0版本。下载试试

完美解决，感谢
