### ISSUE TITLE
[Bug] 貌似华为云的自动ddns有异常，我一直都没办法给上

### ISSUE THREAD

**Issue by liannai569** [jeessy2/ddns-go#1061]
### 问题描述

![image](https://github.com/jeessy2/ddns-go/assets/89626087/35330307-40c0-4014-9a71-729583320d98)
总是错误提示

### DNS服务商

华为云

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v6.3.0

### 安装方式

服务

### 额外信息

我今天已更新了最新的key这些的，但是就是无法正常使用

**Comment by jeessy2** [comment]
你时间不对吧，都4月1号。现在才3月

**Comment by liannai569** [comment]
> 你时间不对吧，都4月1号。现在才3月

抱歉哈，我上次测试东西调时间了，忘记改回去了，真的很抱歉，请关闭这个请求
