### ISSUE TITLE
windows通过网卡获取ipv6，几个小时会出现一次ip变化然后马上变回来

### ISSUE THREAD

**Issue by lssdo12** [jeessy2/ddns-go#1062]
### 问题描述

windows下使用`./ddns-go -s install -f 10 -cacheTimes 180`命令安装服务
ipv6地址原本是f308（最后四位），偶尔会变成8f11，然后马上变回f308
![v6连续变动](https://github.com/jeessy2/ddns-go/assets/59727014/e616df22-7920-46f1-a181-2b2b71a98650)

钉钉每隔几个小时就会收到通知
![ipv6变化_钉钉](https://github.com/jeessy2/ddns-go/assets/59727014/d8442e00-591d-4f69-9845-b82043188cde)

附上ipconfig
![image](https://github.com/jeessy2/ddns-go/assets/59727014/7cca5d91-fc7c-42b6-a51b-61b2927d5798)

### DNS服务商

DnsPod

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v6.2.2

### 安装方式

服务

**Comment by lssdo12** [comment]
> 这个应该是正常的。参考AI回答
> 
> ```
> 如果你的IPv6地址在短时间内变化，然后又恢复到之前的地址，这种情况可能是由于网络连接的短暂中断或者网络配置更新引起的。以下是一些可能导致这种情况发生的原因：
> 
> 网络适配器重置或禁用/启用:
> 如果你的网络适配器被禁用然后重新启用，或者遇到某些问题导致自动重置，它可能会重新获取原先的IPv6地址。
> 
> 网络连接闪断:
> 网络连接可能因为路由器、交换机或其他网络设备的问题而短暂中断，导致你的电脑重新与网络建立连接，并可能获取到一个新的IPv6地址，随后又恢复到之前的地址。
> 
> 操作系统或网络栈问题:
> Windows操作系统在处理网络配置时可能出现临时错误，导致IPv6地址发生变化，然后又自动修正了该错误。
> 
> IP地址冲突解决:
> 如果系统检测到IP地址冲突（例如两个设备被分配了相同的IPv6地址），它可能会尝试解决这个问题，并在解决后恢复使用原来的IPv6地址。
> 
> 路由器或DHCPv6服务器行为:
> 路由器或DHCPv6服务器可能因为配置更新、软件错误或其他原因暂时分配了一个不同的IPv6地址，然后再次分配回正确的地址。
> 
> 要进一步诊断这个问题，你可以查看Windows事件查看器（Event Viewer）以确定是否有与网络相关的日志条目。此外，检查你的路由器和其他网络设备上是否有任何相关日志或设置也是一个好主意。如果问题持续存在，考虑与你的ISP联系以寻求帮助。
> ```

好像找到原因了，系统是win10的，事务日志里看每隔一段时间会出现日志`系统正在进入睡眠状态。睡眠原因: System ldle`，来源是Kernel-Power。大概一两秒后出现日志`系统已从睡眠状态恢复。`。在这中间会出现日志`Media disconnected on NIC /DEVICE/13A03481B-A8CB-4251-AB4F-93C82B60F788} (frendly Name: Realtek pcle 2.5GbE Family Controller).`，来源是Hyper-V-VmSwitch。
应该win10尝试进入睡眠状态导致我的Hyper-V外部虚拟交换机网卡中断了
![image](https://github.com/jeessy2/ddns-go/assets/59727014/268d47b1-50c7-447c-b7c9-f61888490f6a)

**Comment by WaterLemons2k** [comment]
> 好像找到原因了，系统是win10的，事务日志里看每隔一段时间会出现日志`系统正在进入睡眠状态。睡眠原因: System ldle`，来源是Kernel-Power。大概一两秒后出现日志`系统已从睡眠状态恢复。`。在这中间会出现日志`Media disconnected on NIC /DEVICE/13A03481B-A8CB-4251-AB4F-93C82B60F788} (frendly Name: Realtek pcle 2.5GbE Family Controller).`，来源是Hyper-V-VmSwitch。 应该win10尝试进入睡眠状态导致我的Hyper-V外部虚拟交换机网卡中断了

试下取消勾选 Hyper-V 宿主机网卡上的 `允许计算机关闭此设备以节约电源`

![允许计算机关闭此设备以节约电源未勾选](https://filestore.community.support.microsoft.com/api/images/f019d9eb-8e0f-4a3d-bb7d-af03a9fb52ad)

**Comment by lssdo12** [comment]
已经解决了，就是电源计划里关闭“使计算机进入睡眠状态”
