### ISSUE TITLE
Dynadot的DDNS请求报错【This account is not testing account】？

### ISSUE THREAD

**Issue by SeamusWong** [jeessy2/ddns-go#1065]
### 问题描述

我今天才开的Dynadot上面的域名
申请了一个API-KEY然后填到了password里面去
设置好之后访问链接Dynadot返回{"error_code":-1,"content":["This account is not testing account."],"status":"error"}
但是我在账户设置里也没看到任何和“testing account”有关系的东西
软件界面里有一个[开启Dynadot动态域名解析](https://www.dynadot.com/community/help/question/enable-DDNS)但是点进去也啥都没有
所以我不清楚是Dynadot的问题还是软件的问题还是我的账号的问题？

### DNS服务商

其它

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

6.3.0

### 安装方式

服务

### 额外信息

![image](https://github.com/jeessy2/ddns-go/assets/46064981/c36db9ff-3516-49ef-8db1-18b0e20168e4)

**Comment by jeessy2** [comment]
参考 #1050
可以问下dynadot开发，好像没上线

**Comment by SeamusWong** [comment]
> 参考 #1050 可以问下dynadot开发，好像没上线

我刚才聊了一下客服，然后她直接给我一句【At this time Dynadot does not support DDNS, however we are working to add this feature.】我就挺纳闷这东西怎么可能你没有呢还等待开发，所以大佬您在弄的时候这账号是可以的对码？

**Comment by jeessy2** [comment]
@YangerStars 啥时候上线呢

**Comment by jeessy2** [comment]
> > 参考 #1050 可以问下dynadot开发，好像没上线
> 
> 
> 
> 我刚才聊了一下客服，然后她直接给我一句【At this time Dynadot does not support DDNS, however we are working to add this feature.】我就挺纳闷这东西怎么可能你没有呢还等待开发，所以大佬您在弄的时候这账号是可以的对码？

不是我弄的。 是他 @YangerStars

**Comment by YangerStars** [comment]
明天上线

**Comment by nicet** [comment]
@jeessy2 @YangerStars @SeamusWong 已测试，可以使用

**Comment by SeamusWong** [comment]
可以了谢谢
