### ISSUE TITLE
增加一個"保存"按鈕在標題欄的"日誌"按鈕前面

### ISSUE THREAD

**Issue by Nebulosa-Cat** [jeessy2/ddns-go#1068]
### 功能描述

如題所述，目前要保存配置必須一路往下到最底部才能保存
然而實際上很多時候只是在 ipv4 or v6 的地方加一條網址而已，並不需要一路拉到最下面 webhook 通知區後
保存按鈕放在那邊實際上不是很方便，希望能多一個在標題欄方便使用

### 解决的问题

保存操作的流暢度

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
最上面不是有一个？

**Comment by Nebulosa-Cat** [comment]
> 最上面不是有一个？

那一個往下拉到中段的時候就看不到了 xD
實際上在所有操作過程中唯一相對位置完全不會變化的只有標題列

![image](https://github.com/jeessy2/ddns-go/assets/30948446/9c308345-f613-4dd5-9b69-14abc63309b3)

**Comment by jeessy2** [comment]
这个不影响吧，毕竟不是天天在保存。
不过也欢迎PR，滚动到中间的时候，保存按钮浮动出来
