### ISSUE TITLE
是否考虑新增SMTP邮件提醒功能?

### ISSUE THREAD

**Issue by 6411692** [jeessy2/ddns-go#1070]
### 功能描述

是否考虑新增SMTP邮件提醒功能?虽然可以变相实现邮件功能化,但是还是会增加流程,占用更多资源!

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
不考虑
