### ISSUE TITLE
DNSPod国际站（dnspod.com）不支持

### ISSUE THREAD

**Issue by choson88** [jeessy2/ddns-go#1079]
### 功能描述

dnspod中国站（dnspod.cn）可以正常ddns，dnspod国际站（dnspod.com）暂时无法ddns。可否增加dnspod.com的支持？

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
太多服务商，建议转DNS服务到支持的。在加dnspod国际版，都快三口之家了
