### ISSUE TITLE
DDNSGO获取网卡IPV6后，提示等待网络连接

### ISSUE THREAD

**Issue by iamtwvl** [jeessy2/ddns-go#1084]
### 问题描述

DDNSGO获取网卡IPV6后，提示等待网络连接，链接超时，感觉是dns问题但是dns没问题，可以正常解析，并且也是host模式
日志：
2024/04/22 11:35:25 等待网络连接: lookup dnsapi.cn on 10.0.3.1:53: read udp 192.168.50.100:58432->10.0.3.1:53: i/o timeout
2024/04/22 11:35:25 5s 后重试...
2024/04/22 11:35:40 等待网络连接: lookup domains.google.com on 10.0.3.1:53: read udp 192.168.50.100:55647->10.0.3.1:53: i/o timeout
2024/04/22 11:35:40 5s 后重试...

### DNS服务商

DnsPod

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

amd64

### 版本

6.3.2

### 安装方式

Docker

**Comment by jeessy2** [comment]
后面出现提示没有，没提示的话就说明正常了
