### ISSUE TITLE
哪里可以配置日志，或者日志记录变化的Ip及时刻

### ISSUE THREAD

**Issue by huanghe-1** [jeessy2/ddns-go#1085]
### 功能描述

我想通过日志，统计分析，ip变化的频繁不频繁。

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
你的需求，配置webhook就可以了，会收到变化通知的
