### ISSUE TITLE
ddns-go_6.3.3_windows_x86_64 启动后样式缺失

### ISSUE THREAD

**Issue by hxp20645** [jeessy2/ddns-go#1088]
### 问题描述

刷新看到样式闪没，控制台显示：Fallback font will be used while loading

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v6.3.3

### 安装方式

服务

**Comment by hxp20645** [comment]
![Snipaste_2024-04-22_22-13-38](https://github.com/jeessy2/ddns-go/assets/25942188/497131b6-3e59-4466-8f67-c8b5949169ff)

**Comment by jeessy2** [comment]
换个浏览器看看
