### ISSUE TITLE
二级域名调用阿里报错查询域名异常？

### ISSUE THREAD

**Issue by biutv** [jeessy2/ddns-go#1089]
### 问题描述

二级域名直接在阿里云解析更改IP地址能正常解析，在ddns-go里填了AccessKey ID和密匙，域名   运行报错
查询域名信息发生异常! 返回内容: {"RequestId":"1A2C45DC-CC73-57B3-92B6-FBCA7FBE35F2","HostId":"alidns.aliyuncs.com","Code":"InvalidDomainName.NoExist","Message":"The specified domain name does not exist. Refresh the page and try again.","Recommend":"https://api.aliyun.com/troubleshoot?q=InvalidDomainName.NoExist&product=Alidns&requestId=1A2C45DC-CC73-57B3-92B6-FBCA7FBE35F2"} ,返回状态码: 400
不知是啥问题

### 是否已搜索同类问题

未搜索

### 操作系统

Linux

### 架构

x86_64

### 版本

v6.3.1

### 安装方式

Docker

### 额外信息

查询域名信息发生异常! 返回内容: {"RequestId":"1A2C45DC-CC73-57B3-92B6-FBCA7FBE35F2","HostId":"alidns.aliyuncs.com","Code":"InvalidDomainName.NoExist","Message":"The specified domain name does not exist. Refresh the page and try again.","Recommend":"https://api.aliyun.com/troubleshoot?q=InvalidDomainName.NoExist&product=Alidns&requestId=1A2C45DC-CC73-57B3-92B6-FBCA7FBE35F2"} ,返回状态码: 400

**Comment by jeessy2** [comment]
`www.domain.example.com` -> `www:domain.example.com`

**Comment by xiaohuihuitop** [comment]
我遇到了同样的问题.
我设置的域名是  www.xxx.top  和  xxx.top 
阿里云 同样报错  
查询域名信息发生异常! 返回内容: {"RequestId":"974DD9FC-C359-524  ... 6"} ,返回状态码: 400

**Comment by jeessy2** [comment]
> 我遇到了同样的问题. 我设置的域名是 [www.xxx.top](http://www.xxx.top) 和 xxx.top 阿里云 同样报错 查询域名信息发生异常! 返回内容: {"RequestId":"974DD9FC-C359-524 ... 6"} ,返回状态码: 400

换个key试试

**Comment by biutv** [comment]
换过几次key，也升级了新版本，然后发现我这二级域名xx.or.td在阿里 和腾讯。都是报错，大概意思就是没有该域名。 但是我这二级域名手动在他里面改ip，已经在他服务商解析成功并能正常访问了。













在 2024-06-09 08:34:22，"jeessy2" ***@***.***> 写道：

我遇到了同样的问题. 我设置的域名是 www.xxx.top 和 xxx.top 阿里云 同样报错 查询域名信息发生异常! 返回内容: {"RequestId":"974DD9FC-C359-524 ... 6"} ,返回状态码: 400

换个key试试

**Comment by HC-Dex** [comment]
还是同样的问题，我用的是飞牛自带的ddns-go，v6.13.3版本应该。冒号也没用
