### ISSUE TITLE
如何加入端口号

### ISSUE THREAD

**Issue by lemontree1433223** [jeessy2/ddns-go#1093]
### 功能描述

请问怎么在解析的时候加上端口号呢

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
什么？

**Comment by lemontree1433223** [comment]
> 什么？



> 什么？

就比如我想nas.xxxx.com对应80端口，b.xxxx.com对应8080端口，应该如何填写呢

**Comment by jeessy2** [comment]
加端口和域名解析有什么关系？

**Comment by SeamusWong** [comment]
解析端口跟ddns没有关系，是在域名服务商DNS里设置的，如果用http访问域名默认就是80端口https是8080，如果是非标端口需要添加Forward记录，比如你有主域名xxx.com通过A解析到一个ip，a.xxx.com需要做Forward记录http://a.xxx.com:端口号这样去弄，ddns只更新xxx.com的ip地址而已

**Comment by jeessy2** [comment]
https默认443

**Comment by lemontree1433223** [comment]
> 解析端口跟ddns没有关系，是在域名服务商DNS里设置的，如果用http访问域名默认就是80端口https是443（上次脑子瓦特了打错了😂），如果是非标端口需要添加Forward记录，比如你有主域名xxx.com通过A解析到一个ip，a.xxx.com需要做Forward记录[http://a.xxx.com:端口号这样去弄，ddns只更新xxx.com的ip地址而已](http://a.xxx.com:%E7%AB%AF%E5%8F%A3%E5%8F%B7%E8%BF%99%E6%A0%B7%E5%8E%BB%E5%BC%84%EF%BC%8Cddns%E5%8F%AA%E6%9B%B4%E6%96%B0xxx.com%E7%9A%84ip%E5%9C%B0%E5%9D%80%E8%80%8C%E5%B7%B2)

非常感谢
