### ISSUE TITLE
阿里云解析api返回400

### ISSUE THREAD

**Issue by rabbit-deer-you** [jeessy2/ddns-go#1095]
### 问题描述

阿里云解析api返回400，
错误code：Identity.Uncertified
error message：Identity of the account is uncertified.
access Key重新更新测试过，依然不行

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

未搜索

### 操作系统

Linux

### 架构

i386

### 版本

16.5

### 安装方式

服务

### 额外信息

群晖内安装

**Comment by jeessy2** [comment]
发工单问阿里云

**Comment by WaterLemons2k** [comment]
实名认证了吗？

参考：[关于使用云解析DNS需完成账号实名认证的通知](https://help.aliyun.com/zh/dns/notice-on-the-need-to-complete-account-real-name-authentication-when)

**Comment by rabbit-deer-you** [comment]
> 实名认证了吗？
> 
> 参考：[关于使用云解析DNS需完成账号实名认证的通知](https://help.aliyun.com/zh/dns/notice-on-the-need-to-complete-account-real-name-authentication-when)

这个没认证，估计是这个原因吧，确实是用着用着就不好使了，我再试下

**Comment by rabbit-deer-you** [comment]
认证后已恢复，感谢
