### ISSUE TITLE
Dynadot更新子域名的AAAA导致所有CNAME、Forward等全部消失是Bug还是就这样设计的？

### ISSUE THREAD

**Issue by SeamusWong** [jeessy2/ddns-go#1096]
### 问题描述

@YangerStars 
手动艾特下代佬
在最开始的时候，我的dns记录是这样的，有一个v6做AAAA解析，剩下的都是301转发
![image](https://github.com/jeessy2/ddns-go/assets/46064981/e388e2d1-c33a-48a0-8408-500289e8f290)
但是当我在ddns-go里针对这个v6对应的domains更新之后，整个记录里所有的Forward全部都消失了，只剩AAAA记录
![image](https://github.com/jeessy2/ddns-go/assets/46064981/6144c6c1-4000-4394-a672-c646f4190756)
我尝试了几次，不仅是转发到这个v6的Forward，而是所有的Forward全都被删掉了，百分百复现
这个是专门这样设计的吗？

### DNS服务商

其它

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v6.5.3

### 安装方式

服务

**Comment by YangerStars** [comment]
是bug，我们会尽快修复

**Comment by YangerStars** [comment]
我们已经修复了这个bug，您可以验证一下，如果有其它问题，可以通过dynadot网站内的官方客服来反馈，我们会及时跟进处理。

**Comment by SeamusWong** [comment]
> 我们已经修复了这个bug，您可以验证一下，如果有其它问题，可以通过dynadot网站内的官方客服来反馈，我们会及时跟进处理。

经测试已经没问题了，感谢您！
