### ISSUE TITLE
解析华为云域名，控制台显示成功且ipv6地址与本地相同，但网址ping不通，外网无法解析出ipv6

### ISSUE THREAD

**Issue by Jayj1997** [jeessy2/ddns-go#1097]
### 问题描述

之前的配置：aksk都配了，华为云控制台显示状态成功，且值与本地ipv6地址相同，ddnsgo日志显示成功

**问题**：局域网ping域名可以通，互联网ping域名不通，ping (-6 都试过) fakeurl.com 显示Ping 请求找不到主机 fakeurl.com。请检查该名称，然后重试。
**当前状态**：ping fakeurl.com Ping 请求找不到主机 fakeurl.com。请检查该名称，然后重试。
**期望实现**：ping fakeurl.com 回复 正在 Ping fakeurl.com [ip] 具有 32 字节的数据

这个真的支持吗，我提了华为云的工单，他说不支持动态ddns(我理解我这个不是动态的吧？这块网络知识不太好，他还给出了链接https://support.huaweicloud.com/dns_faq/dns_faq_160511.html，无用的话请忽略)

### DNS服务商

华为云

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

newest

### 安装方式

服务

### 额外信息

装在openwrt里

**Comment by jeessy2** [comment]
那说明成功了的。解析不通的话，建议在网上搜索一下，每个人的网络环境不同，无法给建议

**Comment by Jayj1997** [comment]
> 那说明成功了的。解析不通的话，建议在网上搜索一下，每个人的网络环境不同，无法给建议

欧克，等假期结束我再问问运营商，只有可能是他的问题了
