### ISSUE TITLE
在无图形linux中安装服务后局域网内其他设备无法访问ip:9876

### ISSUE THREAD

**Issue by shangcanyang** [jeessy2/ddns-go#1099]
### 问题描述

Linux纯命令版本安装服务后在局域网内输入ip:9876无法访问配置网页

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v6.5.0

### 安装方式

服务

**Comment by jeessy2** [comment]
检查是不是防火墙

**Comment by shangcanyang** [comment]
谢谢，把防火墙端口放行后能正常使用了
