### ISSUE TITLE
不要明文存储密码在配置文件内

### ISSUE THREAD

**Issue by RogerProSelf** [jeessy2/ddns-go#1100]
### 功能描述

希望能在配置密码之后将密码以哈希值等方式存储，而不是明文写入配置文件，增加安全性，谢谢！

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
欢迎PR, 有些hash也不安全。如果都能看见你配置文件了，那电脑也不安全了啊

**Comment by KirinRyuuri** [comment]
如果使用 Windows ，可以用 NTFS 的权限限制掉配置文件的查看
如果使用 Linux ，可以用 ACL 单独限制配置文件查看

**Comment by happyelements01** [comment]
自己收紧AKSK权限

**Comment by jeessy2** [comment]
https://github.com/jeessy2/ddns-go/actions/runs/9140525236
下载试下，用bcrypt加密
