### ISSUE TITLE
日志清除

### ISSUE THREAD

**Issue by cyzimo** [jeessy2/ddns-go#111]
web界面的清空日志是不是只清除显示出来的50条日志？我在web界面清空日志后，docker日志里面还是看到全部日志。
docker本身的日志能否清理？
或者加个环境变量来限制log文件的大小？

**Comment by jeessy2** [comment]
web界面的清空日志就是清除50条缓存在内存中的日志.
清空docker日志, 这个没有必要. 如果要清除, 看下网上的教程吧

**Comment by cyzimo** [comment]
google了下清除容器日志，发现不太懂。实在不行我删除容器重新安装应该也可以清掉日志吧
-_-!!!

**Comment by jeessy2** [comment]
也可以。日志占用又不大，没必要清除

**Comment by cyzimo** [comment]
主要是逼死强迫症了~-~
