### ISSUE TITLE
docker 容器时区错误

### ISSUE THREAD

**Issue by turingking** [jeessy2/ddns-go#1110]
### 问题描述

解析域名失败，报错： Signature expired. Please use local time and enable NTP service for time synchronization to avoid a deviation between `Timestamp` and the server time 1715570716.
docker 容器已经增加    -e TZ="Asia/Shanghai"
``` java
 docker run
  -d
  --name='ddns-go'
  --net='host'
  -e TZ="Asia/Shanghai"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="ddns-go"
  -l net.unraid.docker.managed=dockerman
  -v '/mnt/user/appdata/ddns-go/':'/root':'rw' 'jeessy/ddns-go'
04655d4730f60e6b6244f931158c2c4e8b38e1297469ccc3736b703cee1110ab

The command finished successfully!```

### DNS服务商

腾讯云

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v6.5.0

### 安装方式

Docker

### 额外信息

_No response_

**Comment by jeessy2** [comment]
检查时间，而不是传时区

**Comment by turingking** [comment]
> 检查时间，而不是传时区

/app # date
Mon May 13 19:32:48 CST 2024

时间是错误的，怎么更新呢

**Comment by WaterLemons2k** [comment]
> /app # date
> 
> Mon May 13 19:32:48 CST 2024
> 
> 
> 
> 时间是错误的，怎么更新呢

检查宿主机的时间和时区
