### ISSUE TITLE
Ipv6获取bug

### ISSUE THREAD

**Issue by H357753** [jeessy2/ddns-go#1111]
### 问题描述

2024/05/13 20:51:52 You can use 'sudo ./ddns-go -s install' to install service
2024/05/13 20:51:52 监听 :9876
2024/05/13 20:51:52 通过接口获取IPv6失败! 接口地址: https://speed.neu6.edu.cn/getIP.php
2024/05/13 20:51:52 异常信息: Get "https://speed.neu6.edu.cn/getIP.php": dial tcp6 **************: connect: network is unreachable
2024/05/13 20:51:52 未能获取IPv6地址, 将不会更新
2024/05/13 21:01:31 "Remote: 192.168.1.100:6456" 登陆成功

### DNS服务商

DnsPod

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

6.5

### 安装方式

其它

### 额外信息

你好，使用的是spk的群晖源，群晖是黑群晖，每次启动都获取不到ipv6不论是http还是接口或者命令行，请问一下大佬这个是因为黑群晖还是什么别的？

**Comment by jeessy2** [comment]
其他机器启动呢？

**Comment by H357753** [comment]
你好，目前只有这个群晖的电脑在用ddns-go

**Comment by jeessy2** [comment]
找个其他电脑测一下

**Comment by jeessy2** [comment]
这些自己测下吧。本次失败下次会重新获取的

**Comment by H357753** [comment]
你好就是失败过多（未获取不再更新）

**Comment by H357753** [comment]
嗯，确定有，一直都是开机未获取，重新进入控制台保存一下就获取到了

**Comment by jeessy2** [comment]
你设置的多久更新一次

**Comment by H357753** [comment]
ttl是自动

**Comment by jeessy2** [comment]
更新频率，不是ttl
考虑用docker

**Comment by H357753** [comment]
好的我去下个docker版本

**Comment by H357753** [comment]
![QQ截图20240516214351](https://github.com/jeessy2/ddns-go/assets/81468266/eebcc99a-19cd-4790-ac8d-738ebc133578)
![QQ截图20240516214410](https://github.com/jeessy2/ddns-go/assets/81468266/fdae35e6-777f-446a-a6f9-f1d078a30abb)

**Comment by H357753** [comment]
用的是群晖docker，启动命令自带-f 300

**Comment by H357753** [comment]
但还是会出错QWQ

**Comment by jeessy2** [comment]
21:28后自动关闭了？

**Comment by H357753** [comment]
我停止了

**Comment by H357753** [comment]
它不会再获取

**Comment by H357753** [comment]
原来在外面1h，它都没获取新的v6

**Comment by jeessy2** [comment]
换台机器测一下
