### ISSUE TITLE
IPV6获取错误

### ISSUE THREAD

**Issue by realzolo** [jeessy2/ddns-go#1112]
### 问题描述

1. 使用接口获取ipv6, 有时候也是得到的这个包含“::”的不可用的地址
2. 通过网卡+正则，还是获取错误。
3. 也不能按照顺序获取，因为这两个地址顺序会自动改变。。。
![image](https://github.com/jeessy2/ddns-go/assets/63219216/dafce58f-831f-4557-a087-1286a0faa43a)

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v6.5.0

### 安装方式

Docker

**Comment by karteous** [comment]
> 换个正则ff:ee

遇到同样问题，请问可否提供一个正则表达式呢

**Comment by realzolo** [comment]
> > 换个正则ff:ee
> 
> 遇到同样问题，请问可否提供一个正则表达式呢

用这个试试：
ip -6 addr | grep inet6 | awk -F '[ \t]+|/' '$3 == "::1" { next;} $3 ~ /^fe80::/ { next;} /inet6/ {print $3}' | awk '{ln=length}ln>max{delete result; max=ln}ln==max{result[NR]=$0}END{for(i in result) print result[i] }'

**Comment by karteous** [comment]
匹配正确ipv6地址^([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$

**Comment by kinding** [comment]
https://github.com/jeessy2/ddns-go/discussions/1153
接口和正则都不稳定的话，可以试试我的脚本，我也查了这个问题，最后还是自己写了个脚本，在通信中解析自己的v6地址，个人觉得这样靠谱些。
