### ISSUE TITLE
希望增加SSL访问的支持

### ISSUE THREAD

**Issue by shuning0128** [jeessy2/ddns-go#1114]
### 功能描述

现在只能通过http://ip:9876访问，无法通过https访问，希望增加相关功能。如果已经支持了相关功能，请告知设置方法，谢谢。

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
暴露在外网强烈建议使用https。如果只在内网使用可以不用https。
推荐如下反带：nginx/traefik/nginx proxy manager

**Comment by acocchat** [comment]
群晖怎么配置呢

**Comment by jeessy2** [comment]
推荐tailscale, wireguard 等vpn。不用https/http，暴露外网也不安全
