### ISSUE TITLE
在DNS服务商中未找到域名

### ISSUE THREAD

**Issue by HMwancheng** [jeessy2/ddns-go#1116]
### 问题描述

![image](https://github.com/jeessy2/ddns-go/assets/91036325/ca3c412a-35d8-4c49-b621-7be0b74fb6a6)
如图，已经尝试过更新token仍然无法使用
该域名已经能正确解析，但DDNS-GO内一直报错

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

6.5.0

### 安装方式

服务

**Comment by HMwancheng** [comment]
加了之后显示这个

2024/05/17 18:45:10 新增域名解析 @.hmwancheng.cloudns.ch 失败! 异常信息: 返回内容: {"result":null,"success":false,"errors":[{"code":1004,"message":"DNS Validation Error","error_chain":[{"code":9000,"message":"DNS name is invalid."}]}],"messages":[]} ,返回状态码: 400

**Comment by jeessy2** [comment]
是冒号...

**Comment by HMwancheng** [comment]
![image](https://github.com/jeessy2/ddns-go/assets/91036325/0dcaa862-1b5a-4737-bc3d-3a58e2bbd12b)
是的，冒号

**Comment by HMwancheng** [comment]
![image](https://github.com/jeessy2/ddns-go/assets/91036325/23e89cd9-6acd-4028-84af-357faf8e6468)

**Comment by jeessy2** [comment]
把@去掉，保留冒号试下

**Comment by HMwancheng** [comment]
![image](https://github.com/jeessy2/ddns-go/assets/91036325/42b67bcd-f1e5-4270-ab6b-091274e14749)
大佬NB!!!!!!!!!!!!!!!!

**Comment by HMwancheng** [comment]
小白膜拜.jpg

**Comment by jeessy2** [comment]
还是买个正常点的域名吧

**Comment by HMwancheng** [comment]
awa
正常点的域名还没批下来嘿嘿嘿   /挠头

**Comment by zhtut** [comment]
![微信截图_20240517222910](https://github.com/jeessy2/ddns-go/assets/7497402/cc274dbb-1107-49eb-bd65-1ba990ec637c)
我这域名怎么也不行？之前用dnspod可以，今天想切到cloudflare就报错了，请大佬帮我看看

**Comment by jeessy2** [comment]
> ![微信截图_20240517222910](https://github.com/jeessy2/ddns-go/assets/7497402/cc274dbb-1107-49eb-bd65-1ba990ec637c)
> 
> 我这域名怎么也不行？之前用dnspod可以，今天想切到cloudflare就报错了，请大佬帮我看看

不要@.

**Comment by leungyiuhoi** [comment]
我也是clouddns的域名:cf里面的dns用“@”，ddns-go里面用“www:+域名”

**Comment by jyzok** [comment]
今天我同意遇到这个问题，我发现问题在cf的 用户API令牌，权限 和区域资源的设置不对。改成下图就没问题了

**Comment by Gary-404notfound** [comment]
> 把@去掉，保留冒号试下

感谢！！！

**Comment by TPAXcc** [comment]
> 今天我同样遇到这个问题，我发现问题在cf的 用户API令牌，权限 和区域资源的设置不对。改成下图这样就没问题了。
> 
> ![Image](https://github.com/user-attachments/assets/6bf03ce8-7a31-417e-b96c-444c68a9db70)

Same, 感谢
