### ISSUE TITLE
提示 “在DNS服务商中未找到域名”，但服务商中有域名

### ISSUE THREAD

**Issue by ItzMiracleOwO** [jeessy2/ddns-go#1117]
### 问题描述

ipv6下，提示 “在DNS服务商中未找到域名”，但服务商中有域名

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

6.5.0

### 安装方式

服务

**Comment by jeessy2** [comment]
截图看下，啥都没有，怎么分析

**Comment by ItzMiracleOwO** [comment]
![image](https://github.com/jeessy2/ddns-go/assets/76854136/53425ae4-6336-4970-8df1-e39d498cb7d6)
![image](https://github.com/jeessy2/ddns-go/assets/76854136/02dee23a-3f86-440c-a4d2-530a5e571535)

**Comment by ItzMiracleOwO** [comment]
可以看到cloudfalre下确实有这个域名，但是ddns-go提示没有

**Comment by jeessy2** [comment]
重新创建key呢

**Comment by jeessy2** [comment]
你怎么创建的key

**Comment by jeessy2** [comment]
实在不行你问下cf,毕竟另外一个成功了

**Comment by ItzMiracleOwO** [comment]
API Token更正为"All Zones"后成功了
