### ISSUE TITLE
当设置禁止公网访问时同内网的机器使用域名访问面板会404

### ISSUE THREAD

**Issue by L245T** [jeessy2/ddns-go#112]
# bug描述
当设置禁止公网访问时，处于同内网的机器使用域名访问面板会404

# bug复现示例
1. 面板的宿主机的ip是172.27.1.2，面板端口为9876
2. 打开其它配置-禁止公网访问
3. 设置ddns解析abc.ddns.com，解析到本地网络接口ip为172.27.1.2
4. 宿主机通过172.27.1.2:9876可以访问面板
4. 同内网的主机ip为172.27.100.2，访问172.27.1.2:9876，可以正常访问
5. 宿主机通过abc.ddns.com:9876访问面板，HTTP状态码404
6. 同内网的主机ip为172.27.100.2，通过abc.ddns.com:9876访问面板，HTTP状态码404

**Comment by jeessy2** [comment]
也判断了域名了的.
主要解决通过nat映射内网后, 静止公网访问不起作用..
也可以取消这个限制, 看有没有这个需求

**Comment by L245T** [comment]
emm，可以加个开关不，由用户决定
nat映射用户的可以拒绝域名访问
非映射的可以允许域名同内网访问

**Comment by jeessy2** [comment]
加个开关感觉没这个必要了, 绝大部分人估计不关心这个功能
