### ISSUE TITLE
2024/05/20 02:56:36 查询域名信息发生异常! Get "https://alidns.aliyuncs.com/?AccessKeyId=.......": EOF

### ISSUE THREAD

**Issue by specialdyy** [jeessy2/ddns-go#1120]
### 问题描述

作者你好，我使用的是 eSir  OpenWrt 高大全版本中的 ddns-go，版本为 v6.3.1，OpenWRT 做旁路由（10.0.0.2），主路由是小米的硬路由（10.0.0.1），设置只使用 ipv4，选择 “通过接口获取” 一直报错 【通过接口获取IPv4失败! 接口地址: https://myip.ipip.net】、【异常信息: Get "https://myip.ipip.net": EOF】，于是选择 “通过网卡获取”，但又出现如提所述报错（具体内容在额外信息栏），请问我的问题可能出在哪里？怎么解决？另外想问一下 “通过接口获取” 和 “通过网卡获取” 有什么区别？旁路由该选哪个？感谢感谢！

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v6.3.1

### 安装方式

其它

### 额外信息

日志中的报错信息（有几个隐私信息用 * 和假内容代替掉了）：
2024/05/20 03:16:36 查询域名信息发生异常! Get "https://alidns.aliyuncs.com/?AccessKeyId=*****&Action=DescribeSubDomainRecords&DomainName=abcde.cc&Format=JSON&Signature=*********************&SignatureMethod=HMAC-SHA1&SignatureNonce=*****************&SignatureVersion=1.0&SubDomain=subDomain.abcde.cc&Timestamp=2024-05-19T19%3A16%3A36Z&Type=A&Version=2015-01-09": EOF

**Comment by jeessy2** [comment]
当您在进行 HTTP 请求时遇到 "EOF" 错误，这通常表示意外的连接终止或远程服务器突然关闭连接。 "EOF" 代表 "End of File"，这表明在尝试读取响应时意外达到了流的末尾。

用curl测下

**Comment by specialdyy** [comment]
感谢作者这么及时的回复！我在开始提交问题之前就已经试过直接打开获取 IP 的域名地址了（但没有用 curl），用内网电脑的 Edge 浏览器打开都是能正常获取 IP 地址的，但是 OP 旁路由中却报上面的错误。我今天白天无意中尝试关闭科学代理，却发现 DDNS 又可以了，但究竟是科学上网的设置导致还是说只要是科学上网就不能使用 DDNS 这个我还搞不懂，请问作者有没有哪些解决的线索或方向可以指导一下？

**Comment by jeessy2** [comment]
这个自行搜索，每个人环境不同，不好给建议
