### ISSUE TITLE
阿里云解析失败

### ISSUE THREAD

**Issue by acientdragon** [jeessy2/ddns-go#1121]
### 问题描述

近期阿里云解析失败，返回内容:https://alidns.aliyuncs.com/失败! ERROR: Get "https://alidns.aliyuncs.com/?AccessKeyId=打码&Action=DescribeSubDomainRecords&DomainName=打码&Format=JSON&Signature=2AbQLRw2e0dyYMNdaqE0eJUEAd4%3D&SignatureMethod=HMAC-SHA1&SignatureNonce=打码&SignatureVersion=1.0&SubDomain=打码&Timestamp=2024-05-20T04%3A32%3A11Z&Type=A&Version=2015-01-09": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
请教应该如何解决

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v5.6.3

### 安装方式

其它

**Comment by jeessy2** [comment]
检查你网，用curl测

**Comment by ZYWNB666** [comment]
我也遇到了同样的问题，curl https://alidns.aliyuncs.com 没问题，是通的，不知道什么问题，可有大佬帮忙解答？

**Comment by 1049731887** [comment]
我也
ping curl通的

**Comment by YipSzeho** [comment]
遇到同样问题

**Comment by lonely-nightmare** [comment]
我也是，重新生成key，也检测了权限了，和上面报错一样

**Comment by jeessy2** [comment]
> 我也是，重新生成key，也检测了权限了，和上面报错一样

超时了，和key无关。经常出现还是偶尔出现

**Comment by lonely-nightmare** [comment]
> > 我也是，重新生成key，也检测了权限了，和上面报错一样
> 
> 超时了，和key无关。经常出现还是偶尔出现

之前一直好好的，突然就出现了，然后就一直不行

**Comment by jeessy2** [comment]
检查你的网络

**Comment by lonely-nightmare** [comment]
> 检查你的网络
好的，谢谢
