### ISSUE TITLE
密码加密应该去除

### ISSUE THREAD

**Issue by fu9809** [jeessy2/ddns-go#1122]
### 功能描述

6.6.0 版本更新了一个新的功能，存储的密码加密了，导致我不能在电脑上查到我设置的密码。
我认为这个功能是完全多余！！！
网页端设置的密码很复杂，肯定记不住。我连接到我的服务器，但是我看不到密码，只能重置密码或者把密码明文存储在另一个地方。
这个功能的意义何在？如果别人能登录自己的服务器，那这个明文密文存储有什么意义？

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
还是几个人提了issues把密码加密，加密还是有好处的。以下是参考：

密码加密是一种保护用户安全和隐私的重要手段，主要有以下几个原因：

- 防止未经授权的访问：加密密码可以防止攻击者轻易获取用户的密码，进而防止其访问用户的账户和数据。

- 保护数据隐私：用户的密码往往是访问敏感信息的关键，加密密码可以有效保护这些敏感信息不被泄露。

- 减轻数据泄露的风险：即便是系统被攻破，存储的加密密码也不易被破解，从而减轻数据泄露的风险。

- 提高用户信任：安全措施完善的系统更容易获得用户的信任，用户会更愿意使用和依赖这样的系统。

- 遵守法规和标准：许多行业和地区都有数据保护法规和标准，要求对用户密码进行加密存储。遵守这些规定可以避免法律风险。

- 防止密码重用攻击：很多用户会在多个网站使用相同的密码。如果一个网站的数据被泄露，但密码是加密的，攻击者就无法轻易利用这些密码在其他网站进行攻击。

总的来说，密码加密是网络安全的一道基本防线，能够在多个层面上提升系统的安全性和用户的隐私保护。

**Comment by jeessy2** [comment]
密码很复杂，可以用密码管理器记住，不可能每次都去看配置文件吧。

**Comment by fu9809** [comment]
总觉得这个功能在这个项目上就是属于“鸡肋”
我已经回退了，使用的是6.5.0版本



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月22日 11:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jeessy2/ddns-go] 密码加密应该去除 (Issue #1122) |

密码很复杂，可以用密码管理器记住，不可能每次都去看配置文件吧。

**Comment by jeessy2** [comment]
可以，自行选择。不过多点安全总是好的

**Comment by Goooooooooood** [comment]
我从6.6.5升级到6.6.7后，居然强制要求我设置密码，还对密码强度有要求，而且还对密码进行了不可逆转的加密。

直接来了个版本回退，完全不需要密码这个功能。

强制要求设密码真是多此一举，就是用一把巨锁来锁住家里卫生间的感觉。😂

**Comment by jeessy2** [comment]
> 我从6.6.5升级到6.6.7后，居然强制要求我设置密码，还对密码强度有要求，而且还对密码进行了不可逆转的加密。
> 
> 
> 
> 直接来了个版本回退，完全不需要密码这个功能。
> 
> 
> 
> 强制要求设密码真是多此一举，就是用一把巨锁来锁住家里卫生间的感觉。😂

可以通过命令获取IP，不设置密码等于肉鸡

**Comment by Goooooooooood** [comment]
> 可以通过命令获取IP，不设置密码等于肉鸡

理解担忧。但是web-ui根本无法从公网访问，密码只会增加“忘记密码后还得重置密码”的焦虑。

想要从公网访问我这个web-ui，除了启用ddns-go的wan访问功能，我还得配置路由器防火墙放行对应端口…

**Comment by Goooooooooood** [comment]
没有抬杠的意思，只是表达对密码的看法，感谢作者的付出。因为强制密码的问题，暂时不会升级软件了。❤️

**Comment by jeessy2** [comment]
还是有很多人暴露在公网的，即使不暴露公网，内网也并不是很安全的。
做为一个使用量比较大的ddns，安全是需要考虑的重要需求。
可以自行选择升级与否。

**Comment by tbc0309** [comment]
赞同密码+加密……大把人搞dmz
