### ISSUE TITLE
自定义域名服务商

### ISSUE THREAD

**Issue by grant580** [jeessy2/ddns-go#1123]
### 功能描述

可以自定义域名服务商

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
Callback

**Comment by grant580** [comment]
> Callback 
这是什么原因呢
2024/05/23 10.32:20 Callback调用失败，异常信息：返回内容：<IDOCTYPE HTML PUBLIC '-MIETF/DTD HTML2.0//EN'S

**Comment by jeessy2** [comment]
找到对方的文档写。这个感觉直接是请求到网页上了

**Comment by grant580** [comment]
> 找到对方的文档写。这个感觉直接是请求到网页上了
> 
> 

我重新配置了callback，查看日志显示调用成功，但是ip依然是之前错误的IP，没有更新成最新的。

**Comment by jeessy2** [comment]
检查你配置

**Comment by grant580** [comment]
> 检查你配置

老大能帮忙看看吗？我参考的是https://dnsexit.com/apps/dynamic-dns-update-clients/ 
配置的callback

URL： https://api.dnsexit.com/dns/
RequestBody：act=dnsrec.update&domain=#{domain}&hostname=#{domain}&record_value=#{ip}&apidomainkey= myapi

**Comment by jeessy2** [comment]
RequestBody的内容应该放在url中

**Comment by grant580** [comment]
> RequestBody的内容应该放在url中

![image](https://github.com/jeessy2/ddns-go/assets/42966265/e272bd3d-e20b-4eee-9b84-a4c9cbdd40a1)

获取到了新的IP，但是dns服务商那边没变，这是为什么
