### ISSUE TITLE
隐藏任务栏图标

### ISSUE THREAD

**Issue by lee4862** [jeessy2/ddns-go#1124]
### 功能描述

作者你好，请问是否能着增加一项功能：隐藏任务栏应用图标至任务栏托盘。Windows系统一直运行ddns go，容易误触应用图标导致程序框弹出，或者意外关闭
<img width="986" alt="示例" src="https://github.com/jeessy2/ddns-go/assets/113847408/dd179151-82dc-4306-a2cc-a5c3dbf26f80">

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by WaterLemons2k** [comment]
安装为服务
