### ISSUE TITLE
配置名称可以有备注吗？

### ISSUE THREAD

**Issue by charley008** [jeessy2/ddns-go#1131]
### 功能描述

有多个二级域名需要ddns，但是配置名称有点单调，无法区分哪个配置是哪个域名，需要一个一个点进去看。

![屏幕截图 2024-05-28 130214](https://github.com/jeessy2/ddns-go/assets/24822683/971f5c84-479e-4346-9c7b-06998bce4265)
能否切换配置那里标注一下哪个一个配置对应哪个域名。

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
无这个功能，可以PR

**Comment by WaterLemons2k** [comment]
> 改完名一会又恢复成原来的样子。没有写到配置文件里面？ 我用的是群晖+docker

保存了吗？

**Comment by charley008** [comment]
没有保存，只是在当前页面改了而已。刷新网页后又和以前一样了
改完后截图：
![屏幕截图 2024-05-30 094425](https://github.com/jeessy2/ddns-go/assets/24822683/d49fd275-f6c6-4480-b3e7-06b0cbc8b705)
刷新后截图：
![屏幕截图 2024-05-30 094447](https://github.com/jeessy2/ddns-go/assets/24822683/9976f003-360e-4002-b846-d3743b277aeb)

**Comment by WaterLemons2k** [comment]
> 没有保存，只是在当前页面改了而已。刷新网页后又和以前一样了 改完后截图： ![屏幕截图 2024-05-30 094425](https://private-user-images.githubusercontent.com/24822683/335012387-d49fd275-f6c6-4480-b3e7-06b0cbc8b705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzM5MjQsIm5iZiI6MTcxNzAzMzYyNCwicGF0aCI6Ii8yNDgyMjY4My8zMzUwMTIzODctZDQ5ZmQyNzUtZjZjNi00NDgwLWIzZTctMDZiMGNiYzhiNzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDAxNDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMWY2NjI4OTYwZDUyNWQzNjEyMDlhM2ViM2U1Y2ZiZWQ1Nzg3NzdkMGQ1OWY3NjRlYmFjOWE5NTNlMjI4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PWbj78j9h6jeZ3EBs09tIBbLzWNRYiXdDoP5YRK8mjc) 刷新后截图： ![屏幕截图 2024-05-30 094447](https://private-user-images.githubusercontent.com/24822683/335012424-9976f003-360e-4002-b846-d3743b277aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzM5MjQsIm5iZiI6MTcxNzAzMzYyNCwicGF0aCI6Ii8yNDgyMjY4My8zMzUwMTI0MjQtOTk3NmYwMDMtMzYwZS00MDAyLWI4NDYtZDM3NDNiMjc3YWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDAxNDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MWMxNzFiZThhN2EyZmRjNTNhYmZkOTgwM2IxOGJmYTBlMzJjMGQ4MWVkMzdhMGE1MTE1ZjM3YWNiN2FkM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w2sA_T-CKJFaEgXO0s9XspML-PkJF6J69ZdAdJSyrtg)

改完得保存才能写入到配置文件，不保存没用的

**Comment by jeessy2** [comment]
😓就和你添加了一个配置一样，你不保存，刷新当然没有了

**Comment by charley008** [comment]
的确如此。。没保存。
