### ISSUE TITLE
请求支持home assistant

### ISSUE THREAD

**Issue by chencl0214** [jeessy2/ddns-go#1133]
### 功能描述

请求支持home assistant

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
具体是什么

**Comment by chencl0214** [comment]
> 具体是什么

大佬大佬，是这样的，最近在使用home assistant想要用ddns工具来给dynv6持续更新ipv6地址（windows上有操作过非常顺利且实用），看到home assistant官方和社区的插件只有duckdns的插件，本人比较盲目自信使用ssh工具连上去把ddns-go的文件导进去依葫芦画瓢ddns-go -s install来像windows那也安装服务，但是报错了。网上查了下没找到结果，报错如图不是很懂，以为是不支持请大佬看下
![LJC A _VI)$LR1IES38{N}C](https://github.com/jeessy2/ddns-go/assets/24311314/9ec2ee35-4278-4b62-a1bd-611ce26429f3)

**Comment by jeessy2** [comment]
直接运行呢？ 对home assistant 插件不了解，只有看社区有没有哪位有熟悉+兴趣的来写

**Comment by chencl0214** [comment]
> 直接运行呢？ 对home assistant 插件不了解，只有看社区有没有哪位有熟悉+兴趣的来写

![image](https://github.com/jeessy2/ddns-go/assets/24311314/7b1cbf2e-7204-4d06-a06d-91dcf2157550)
直接运行是这个结果，不过我ip+9876端口去访问打不开东西，应该是失败了
![image](https://github.com/jeessy2/ddns-go/assets/24311314/5aafe2df-c873-4dc9-b120-a889cdccbd41)

**Comment by jeessy2** [comment]
防火墙这些关了嘛？

**Comment by chencl0214** [comment]
> 防火墙这些关了嘛？

![image](https://github.com/jeessy2/ddns-go/assets/24311314/484d1db5-400a-4b71-b746-e4316cbbd9b7)
没找到看防火墙状态和关的方法，似乎和平时玩的那些linux发行版不太一样...

**Comment by jeessy2** [comment]
那你自己研究一下了，搜索/gpt都可以问下

**Comment by WaterLemons2k** [comment]
> ![image](https://private-user-images.githubusercontent.com/24311314/335035975-7b1cbf2e-7204-4d06-a06d-91dcf2157550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNDMxMjgsIm5iZiI6MTcxNzA0MjgyOCwicGF0aCI6Ii8yNDMxMTMxNC8zMzUwMzU5NzUtN2IxY2JmMmUtNzIwNC00ZDA2LWEwNmQtOTFkY2YyMTU3NTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA0MjAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYTNiNDM0Zjk1NjdkMzYxNTRmODNlMTM5N2EyZDM2OWNkZjQwMDA3ZmU3NDZlZjk1ODEwN2QyNzMwNjk1OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P4tBr-CWntW0H7ZbW4fCMoqXk88WsBlJLYMhm3FDtpw) 

我看这里有 `Docker中运行`，是用 Docker 安装的 Home Assistant 吗？

**Comment by chencl0214** [comment]
> > ![image](https://private-user-images.githubusercontent.com/24311314/335035975-7b1cbf2e-7204-4d06-a06d-91dcf2157550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNDMxMjgsIm5iZiI6MTcxNzA0MjgyOCwicGF0aCI6Ii8yNDMxMTMxNC8zMzUwMzU5NzUtN2IxY2JmMmUtNzIwNC00ZDA2LWEwNmQtOTFkY2YyMTU3NTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA0MjAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYTNiNDM0Zjk1NjdkMzYxNTRmODNlMTM5N2EyZDM2OWNkZjQwMDA3ZmU3NDZlZjk1ODEwN2QyNzMwNjk1OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P4tBr-CWntW0H7ZbW4fCMoqXk88WsBlJLYMhm3FDtpw)
> 
> 我看这里有 `Docker中运行`，是用 Docker 安装的 Home Assistant 吗？

不是，用的虚拟机直接安装原生的

**Comment by WaterLemons2k** [comment]
> 不是，用的虚拟机直接安装原生的

那应该只是 SSH 用了 Docker。安装个管理面板（比如 [Portainer](https://community.home-assistant.io/t/home-assistant-community-add-on-portainer/68836)试一下？

参考：https://community.home-assistant.io/t/run-extra-docker-container/321362/12

**Comment by WaterLemons2k** [comment]
找到了一个包含 ddns-go 的 add-ons 仓库（未测试）：https://github.com/dscao/hassio-addons

来源：https://bbs.hassbian.com/thread-23029-1-1.html

**Comment by chencl0214** [comment]
> 找到了一个包含 ddns-go 的 add-ons 仓库（未测试）：https://github.com/dscao/hassio-addons
> 
> 来源：https://bbs.hassbian.com/thread-23029-1-1.html

多谢大佬，我看了下，可以用，就是版本停留在5.6几。之前那个问题的原因也找到了，确实跟你说的一样，我之前的命令行操作全都是home assistant自带容器里的ssh里操作的，人傻了，我准备直接用虚拟机的命令去重新试试看

**Comment by chencl0214** [comment]
![image](https://github.com/jeessy2/ddns-go/assets/24311314/c7bd5eaf-a111-4e87-8fea-93b79a36b56b)
感谢大佬们的解答，搞定了
