### ISSUE TITLE
能否支持多 Webhook

### ISSUE THREAD

**Issue by u1s3-fu** [jeessy2/ddns-go#1136]
### 功能描述

ddns-go 的webhook通知能否同时启用多种通知方式？最近找到一个可以发短信的通知接口就是不太稳定所以问一下看看能不能同时使用两种方式。

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
不支持。暂无计划支持
