### ISSUE TITLE
建议启动时先进行一次IP比对再决定后续操作

### ISSUE THREAD

**Issue by ChenyangS** [jeessy2/ddns-go#1138]
### 功能描述

现在在用Callback注册动态IP域名，看日志貌似重启之后无论IP是否改变，总是进行注册，所以建议启动时先进行一次IP比对再决定后续操作，IP不变就不需要更新了。

### 解决的问题

现在用的DDNS，好像越来越严格，害怕一不小心调试系统的时候重启多了把帐号砍了。

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
callback无法做到比对，其它稍微大点的服务商是可以的。

**Comment by ChenyangS** [comment]
其实之前接触过一个简单的脚本，它是把IP存在本地文件定时更新，比对改变之后再进行更新，所以也希望DDNS-Go也能前置类似的判断条件

**Comment by jeessy2** [comment]
暂不支持，感觉没必要
