### ISSUE TITLE
可以使用相对路径设置配置文件路径并在程序启动时自动读取

### ISSUE THREAD

**Issue by lsdxfs** [jeessy2/ddns-go#1139]
### 功能描述

参考 [请问windows下能不能设置配置文件在当前目录（exe所在目录）](https://github.com/jeessy2/ddns-go/issues/268)
这里说明可以指定路径 但是据我测试无法使用相对路径 

我的想法是可以安装后将整个文件夹从D盘挪到其他硬盘中正常使用 或者迁移文件夹所在的电脑仍然可以正常使用 实现文件夹内便携 这样在切换多台windows电脑时不用反复配置

### 附加信息

经我测试无法使用相对路径 使用.\ddns-go.exe -s install -c ..\Config 配置文件会写入到C:\Windows\Config 这个文件里
是否可以读取文件夹内是否有配置文件暂未测试awa

辛苦开发者大大了

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
不建议。安装服务运行时不同系统运行目录不同，除非你知道运行时的目录是多少，就可以使用相当路径。

**Comment by lsdxfs** [comment]
> 不建议。安装服务运行时不同系统运行目录不同，除非你知道运行时的目录是多少，就可以使用相当路径。

我的想法是 主程序双击运行时读取当前目录是否有配置文件 如果没有再新建 这样就不会导致目录不同无法同步设置

**Comment by jeessy2** [comment]
啥？

**Comment by jeessy2** [comment]
双击/安装服务都是默认当前用户目录

**Comment by lsdxfs** [comment]
所以大佬在 ? 啥 没看懂 (

**Comment by jeessy2** [comment]
我也没看懂你说的什么意思

**Comment by jeessy2** [comment]
你自己测一下吧
