### ISSUE TITLE
callback 能否支持 header配置

### ISSUE THREAD

**Issue by DrugChen** [jeessy2/ddns-go#1145]
### 功能描述

火山引擎，确实字节的dns，刚起步，贼便宜，质量又好
但是坑的鉴权只能使用header，不支持url传参，唉
callback能否支持自定义header
看webhook都支持

### 解决的问题

基本全部运营商都能通过callback支持了吧

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
可以转dns服务器到支持的服务商吧
