### ISSUE TITLE
不同服务商自由选择是否进行推送

### ISSUE THREAD

**Issue by Emtier** [jeessy2/ddns-go#1146]
### 功能描述

现在ddns-go可以添加多个api，但是下面的推送通知只有一个，希望第一个api 推送通知，第二个API不推送通知，独立处理。

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
复杂了。为啥要一个推送一个不推送

**Comment by jeessy2** [comment]
啊，要不你fork一个吧。感觉大部分人暂时用不上
