### ISSUE TITLE
Cloudflare API只能创建不能修改

### ISSUE THREAD

**Issue by Separatee** [jeessy2/ddns-go#1149]
### 问题描述

如题，是否有解决方案?我看到有Overwrite和Update两个api选项，能否改用Update呢？
并且我的终端显示三天以来只成功更新两次
错误内容:
````
新增域名解析 example.com 失败! 异常信息: 返回内容: {"result":null,"success":false,"errors":[{"code":81057,"message":"Record already exists."}],"messages":[]} ,返回状态码: 400
````
然后cloudflare出现了三个同域名不同记录的解析。导致访问不到地址。或许换个api方法能够解决…?

复现方法:
在webui创建一个api,给予最小权限
在webui创建域名解析之前，创建一个正确的域名
等待新ip更新，出现多个相同域名解析

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### 版本

v6.6.1

### 安装方式

服务

**Comment by jeessy2** [comment]
你自己试。需要要查询权限，根据有无进行新增或更新

**Comment by jeessy2** [comment]
try: v6.3.3
参考 https://github.com/jeessy2/ddns-go/discussions/1159

**Comment by Separatee** [comment]
了解，的确如此，谢谢回复
