### ISSUE TITLE
用户名是啥

### ISSUE THREAD

**Issue by ata666** [jeessy2/ddns-go#1154]
### 问题描述

我参考README在ubuntu上安装了ddns-go，已经重置了密码。但是这默认的用户名是啥，我搜了一圈也没找到。。。
![image](https://github.com/jeessy2/ddns-go/assets/90944267/fb1dc36b-98cd-4413-9961-3808ba4ff9ea)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

6.6.2

### 安装方式

服务

**Comment by jeessy2** [comment]
> 可以增加一个参数去除认证吗，自己一个人用没必要，也没找到不要认证的方式

不启用web -noweb

**Comment by Y7ianxi** [comment]
> 没有任何默认账号密码。使用重置密码，账号会显示出来，注意看下

我在群辉安装的套件， 
![2e65b392324f380bdbe49a0a0efde7f](https://github.com/jeessy2/ddns-go/assets/174860340/57bdf31d-5173-4061-b4a0-c1888254263a)
现实的只有这个，怎么重置密码

**Comment by jeessy2** [comment]
> > 没有任何默认账号密码。使用重置密码，账号会显示出来，注意看下
> 
> 
> 
> 我在群辉安装的套件， 
> 
> ![2e65b392324f380bdbe49a0a0efde7f](https://github.com/jeessy2/ddns-go/assets/174860340/57bdf31d-5173-4061-b4a0-c1888254263a)
> 
> 现实的只有这个，怎么重置密码

找到配置文件，把账号密码删除后重启一下

**Comment by haoranxu1989** [comment]
> > 可以增加一个参数去除认证吗，自己一个人用没必要，也没找到不要认证的方式
> 
> 不启用web -noweb

在docker中不能使用这个命令吧

 -noweb 'jeessy/ddns-go:latest'
unknown shorthand flag: 'n' in -noweb
See 'docker run --help'.

**Comment by jeessy2** [comment]
> > > 可以增加一个参数去除认证吗，自己一个人用没必要，也没找到不要认证的方式
> 
> > 
> 
> > 不启用web -noweb
> 
> 
> 
> 在docker中不能使用这个命令吧
> 
> 
> 
>  -noweb 'jeessy/ddns-go:latest'
> 
> unknown shorthand flag: 'n' in -noweb
> 
> See 'docker run --help'.

加到最后，参考下文档
