### ISSUE TITLE
查询域名信息发生异常!

### ISSUE THREAD

**Issue by MoIei** [jeessy2/ddns-go#1155]
### 问题描述

保存后提示“查询域名信息发生异常! 返回内容: {"RequestId":"FE1FD5FA-BBC7-54D7-8F4C-4B68465D27EE","HostId":"alidns.aliyuncs.com","Code":"Forbidden.RAM","Message":"User not authorized to operate on the specified resource, or this API doesn't support RAM.","Recommend":"https://api.aliyun.com/troubleshoot?q=Forbidden.RAM&product=Alidns&requestId=FE1FD5FA-BBC7-54D7-8F4C-4B68465D27EE","AccessDeniedDetail":{"AuthPrincipalOwnerId":"1909118372392793","EncodedDiagnosticMessage":"AQEAAAAAZmxhsUZFMUZENUZBLUJCQzctNTRENy04RjRDLTRCNjg0NjVEMjdFRQ==","AuthPrincipalType":"SubUser","AuthPrincipalDisplayName":"209811618375036959"}} ,返回状态码: 400”

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

6.6.2

### 安装方式

Docker

### 额外信息

查询域名信息发生异常! 返回内容: {"RequestId":"FE1FD5FA-BBC7-54D7-8F4C-4B68465D27EE","HostId":"alidns.aliyuncs.com","Code":"Forbidden.RAM","Message":"User not authorized to operate on the specified resource, or this API doesn't support RAM.","Recommend":"https://api.aliyun.com/troubleshoot?q=Forbidden.RAM&product=Alidns&requestId=FE1FD5FA-BBC7-54D7-8F4C-4B68465D27EE","AccessDeniedDetail":{"AuthPrincipalOwnerId":"1909118372392793","EncodedDiagnosticMessage":"AQEAAAAAZmxhsUZFMUZENUZBLUJCQzctNTRENy04RjRDLTRCNjg0NjVEMjdFRQ==","AuthPrincipalType":"SubUser","AuthPrincipalDisplayName":"209811618375036959"}} ,返回状态码: 400

**Comment by jeessy2** [comment]
User not authorized to operate on the specified resource, or this API doesn't support RAM.

**Comment by MoIei** [comment]
在RAM控制里面把所有权限授权后可以成功解析了，谢谢
