### ISSUE TITLE
设置页面增加一个退出登陆的功能

### ISSUE THREAD

**Issue by fcurrk** [jeessy2/ddns-go#1156]
### 功能描述

既然都有登陆了，还是加一个退出登陆的功能吧，这样才是完整的安全体系。

### 解决的问题

根据是否登陆在设置页面增加一个退出，退出后重定向到登陆页面，以保证在其它设备上临时登陆的密码安全。

_No response_

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
可以PR
