### ISSUE TITLE
openclash与之冲突

### ISSUE THREAD

**Issue by socpio** [jeessy2/ddns-go#1158]
### 问题描述

主机名 | iStoreOS
型号 | FriendlyElec NanoPi R4S
架构 | ARMv8 Processor rev 4
目标平台 | rockchip/armv8
固件版本 | iStoreOS 22.03.6 2024052410 / LuCI istoreos-22.03 branch git-24.057.30647-6659faa
内核版本 | 5.10.201

IPv6地址，在打开openclash时候，三种方式不论何种方式获取ipv6地址。
日志：
2024/06/15 17:50:39 配置文件已保存在: /etc/ddns-go/ddns-go-config.yaml
2024/06/15 17:50:39 查询域名信息发生异常! Get "https://api.cloudflare.com/client/v4/zones?name=【隐藏我的域名】&status=active&per_page=50": EOF
2024/06/15 17:51:32 查询域名信息发生异常! Get "https://api.cloudflare.com/client/v4/zones?name=【隐藏我的域名】&status=active&per_page=50": EOF

在关闭openclash时候，或者使用SSRP+时候，日志正常

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### 版本

6.6.2

### 安装方式

其它

**Comment by jeessy2** [comment]
不是程序问题，这个自行解决

**Comment by socpio** [comment]
> 不是程序问题，这个自行解决

解决了，把api.cloudflare.com设置为 Fake-IP 模式下将返回真实IP地址就行了。
是我大意了
