### ISSUE TITLE
建议添加更新功能

### ISSUE THREAD

**Issue by MNWZ211** [jeessy2/ddns-go#1162]
### 功能描述

更新步骤繁琐，需要卸载重装

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
去年就有了， 参考#834

**Comment by MNWZ211** [comment]
> 去年就有了， 参考#834
谢谢，没找到
