### ISSUE TITLE
ipv6成功配置但是无法外网访问

### ISSUE THREAD

**Issue by RikkaLzw** [jeessy2/ddns-go#1165]
### 问题描述

![QQ截图20240619162055](https://github.com/jeessy2/ddns-go/assets/128763841/640eff40-2686-4af8-9cfd-84085358af1d)
![QQ截图20240619161908](https://github.com/jeessy2/ddns-go/assets/128763841/d2728a3c-d6fa-4d72-8590-c394d69bc721)
配置没有问题，光猫超级终端也关闭了防火墙.
可以内网访问，外网不行，也ping不通

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v5.6.4

### 安装方式

Docker

**Comment by WaterLemons2k** [comment]
再检查一下路由器的防火墙

**Comment by RikkaLzw** [comment]
> 再检查一下路由器的防火墙

没有用路由器。光猫牵的网线

**Comment by WaterLemons2k** [comment]
> ![QQ截图20240619161908](https://private-user-images.githubusercontent.com/128763841/340988316-d2728a3c-d6fa-4d72-8590-c394d69bc721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODg1NDEsIm5iZiI6MTcxODc4ODI0MSwicGF0aCI6Ii8xMjg3NjM4NDEvMzQwOTg4MzE2LWQyNzI4YTNjLWQ2ZmEtNGQ3Mi04NTkwLWMzOTRkNjliYzcyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwOTEwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTczYzhlYTVhYzUwZGE1ZjA3YjBiNTcxMzY3NGFkZjM4MDhlZmJmN2FmODE1ZjBiNTQyZTczNTgxNWFiMjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-ZvupeL-OR_gdoLcu7ei3LdCqm5ZXNgrHxFtFuCTqLU)

没从图片中看到任何有关 IPv6 相关的防火墙设置，所以有理由怀疑这个选项只管 IPv4 防火墙。

可能还需要关闭类似 IPV6 SESSION 的选项：

![image](https://img-blog.csdnimg.cn/img_convert/86f9ebdc302af029a65c84bfef476146.png)

**Comment by RikkaLzw** [comment]
> > ![QQ截图20240619161908](https://private-user-images.githubusercontent.com/128763841/340988316-d2728a3c-d6fa-4d72-8590-c394d69bc721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODg1NDEsIm5iZiI6MTcxODc4ODI0MSwicGF0aCI6Ii8xMjg3NjM4NDEvMzQwOTg4MzE2LWQyNzI4YTNjLWQ2ZmEtNGQ3Mi04NTkwLWMzOTRkNjliYzcyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwOTEwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTczYzhlYTVhYzUwZGE1ZjA3YjBiNTcxMzY3NGFkZjM4MDhlZmJmN2FmODE1ZjBiNTQyZTczNTgxNWFiMjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-ZvupeL-OR_gdoLcu7ei3LdCqm5ZXNgrHxFtFuCTqLU)
> 
> 没从图片中看到任何与 IPv6 相关的防火墙设置，所以有理由怀疑这个选项只管 IPv4 防火墙。
> 
> 可能还需要**关闭** IPV6 SESSION 之类的选项，如下图所示：
> 
> ![image](https://camo.githubusercontent.com/cde9acc0e8ba7d55fdbc6aed9a47070b3cd49683b6700a43bc41669f5c74e815/68747470733a2f2f696d672d626c6f672e6373646e696d672e636e2f696d675f636f6e766572742f38366639656264633330326166303239613635633834626665663437363134362e706e67)
![QQ截图20240619200056](https://github.com/jeessy2/ddns-go/assets/128763841/eff5f256-12e3-4fb2-b90d-e769658bc9ee)

我将光猫改为桥接 用路由器拨号，但是发生同样的情况。

**Comment by RikkaLzw** [comment]
路由器防火墙也关了。
![QQ截图20240619200231](https://github.com/jeessy2/ddns-go/assets/128763841/92dd9eef-57a2-489e-9584-616d40dff76b)

**Comment by straint** [comment]
能不能访问和ddns没啥关系吧,正常情况直接用ipv6地址加端口就能访问

**Comment by lldacing** [comment]
我是ipv6+端口能访问，域名+端口不行，不知道为什么，防火墙都关了也不行

**Comment by Emtier** [comment]
linux的防火墙关了吗 有时候会获取到多个IPv6 你获取的是第几个IPv6

**Comment by RikkaLzw** [comment]
> linux的防火墙关了吗 有时候会获取到多个IPv6 你获取的是第几个IPv6

linux关了，获取了两个ip，解析的是第一个，获取的公网ip在itdog上部分ping得通，网站是绝对打不开的。

**Comment by RikkaLzw** [comment]
目前算是解决了，80端口没法用，本来想重定向的，用其他端口就能行。
