### ISSUE TITLE
callback到底怎么用啊？能举个例子吗

### ISSUE THREAD

**Issue by poppy7921** [jeessy2/ddns-go#117]
举个简单的例子，每步的解析应该是最简单的，只需要域名和密码
http://main.meibu.com/ip/login.asp?name=xxx.noip.cn&pwd=PASSWORD
只需要用域名和密码访问这个URL就行了，如果用callback该怎么弄？

**Comment by jeessy2** [comment]
`http://main.meibu.com/ip/login.asp?name=#{domain}&pwd=PASSWORD`
在ipv4或ipv6输入你的域名即可

**Comment by poppy7921** [comment]
测试OK，谢谢
