### ISSUE TITLE
希望能添加gnudip服务器功能，有很多光猫设备内置支持这个协议

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [jeessy2/ddns-go#1170]
### 功能描述

![image](https://github.com/jeessy2/ddns-go/assets/67987607/5f6e6878-8fef-4925-ac4c-b0cc5ab0f65a)

### 解决的问题

可以防止部分光猫的自带nat阻扰ddns

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
不支持
