### ISSUE TITLE
win版拒绝外网登录后IPV6就ping不通了

### ISSUE THREAD

**Issue by qyourk** [jeessy2/ddns-go#1174]
### 问题描述

用IPV6开了个MC服务器，打开了禁止外网访问后游戏服务器也连不上了

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v6.6.3

### 安装方式

服务

**Comment by jeessy2** [comment]
应该和禁止外网访问无关

**Comment by jeessy2** [comment]
你自己测下

**Comment by jainnieh** [comment]
我Windows上安装的ddns-go,. Windows有公网ipv6. 不知道和你的情况一样不. 
我确实出现ping不通, 是因为Windows防火墙, 关闭防火墙就能ping通.
当然一直关闭防火i墙不安全. 如果需要通过特定端口访问Windows主机就自己开放一些端口.
另外我知道如何解决Windows无法被ping的正确方案. 如果以上和你的问题一样,可以再给我留言, 我告诉你解决方案

**Comment by Emtier** [comment]
防火墙对应端口打开了吗
<img width="1127" alt="截屏2024-06-28 12 53 41" src="https://github.com/jeessy2/ddns-go/assets/166900875/41085618-1cc9-4d82-8d3f-707bfec51c09">
