### ISSUE TITLE
请求取消密码加密

### ISSUE THREAD

**Issue by Herissmon** [jeessy2/ddns-go#1178]
### 功能描述

我现在忘记了用户名密码，但当我打开ddns-go-config文件时，发现密码是加密的，希望取消！另外希望告知密码是用什么加密的？

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by Herissmon** [comment]
这实在是太麻烦了，也希望能出个找回密码的功能（docker构建）

**Comment by jeessy2** [comment]
只能重置，或者编辑配置文件，把账号密码去除。也可以进入容器执行./ddns-go --resetPassword

**Comment by Herissmon** [comment]
> 只能重置，或者编辑配置文件，把账号密码去除。也可以进入容器执行./ddns-go -resetPassword

那咋解码 用什么加密方式

**Comment by Herissmon** [comment]
因为我已经找到配置文件里的密码存储段 但是加密

**Comment by jeessy2** [comment]
只能重置，解密不出来的

**Comment by Herissmon** [comment]
> 只能重置，解密不出来的

哦哦

**Comment by lalasou** [comment]
不取消密码加密也行
但是这个 

密码不安全  请换更安全的密码 



我也是无语了


asdfghjkll.123   这么复杂都不行

大哥   差不多就行了🤣好不好啊


别太复杂   随意 想安全就复杂点  想简单就简单点 
纯内网

**Comment by jeessy2** [comment]
> 不取消密码加密也行
> 但是这个 
> 
> 密码不安全  请换更安全的密码 
> 
> 
> 
> 我也是无语了
> 
> 
> asdfghjkll.123   这么复杂都不行
> 
> 大哥   差不多就行了🤣好不好啊
> 
> 
> 别太复杂   随意 想安全就复杂点  想简单就简单点 
> 纯内网

打开外网访问就要求复杂密码

**Comment by Herissmon** [comment]
也够人无语的了

**Comment by jeessy2** [comment]
> 还是建议作者把加密取消，真的特麻烦

取消不了了。可以用老版本

**Comment by Herissmon** [comment]
😅是不愿意开发吗

**Comment by jeessy2** [comment]
> 😅是不愿意开发吗

不可反向解密，会影响密码已加密的用户。建议你了解一下bcrypt

你实在嫌麻烦的话，你换个软件吧，或则fork自行开发未加密的
