### ISSUE TITLE
这个https://myip4.ipip.net获取的地址是错误的！！！建议对比其余的后面几个地址。再选出多数的正确地址。

### ISSUE THREAD

**Issue by iesv** [jeessy2/ddns-go#1179]
### 问题描述

这个https://myip4.ipip.net获取的地址是错误的！！！建议对比其余的后面几个地址。再选出多数的正确地址。

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

6.6.3

### 安装方式

服务

**Comment by jeessy2** [comment]
myip4用不了了，把4去了。参考#1047

**Comment by iesv** [comment]
我搞晕了三天，怎么也想不通，最后发现原来是这个地址获取错误导致的！！！好晕啊
