### ISSUE TITLE
状态卡滞不动

### ISSUE THREAD

**Issue by otaku1213** [jeessy2/ddns-go#1183]
### 问题描述

长时间开着不动 程序会失去响应 命令行显示更新到某个时刻    偶尔按空格会向下更新 类似CMD命令跑着跑着不动了 要回车继续走

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v6.6.1

### 安装方式

服务

### 额外信息

无任何报错

**Comment by jeessy2** [comment]
日志+截图

**Comment by otaku1213** [comment]
发现卡滞了 ，没有滚动信息，登录WEB端登录了两次发现它已自行恢复
2024/07/19 10:09:39 IPv6未改变, 将等待 5 次后与DNS服务商进行比对
2024/07/23 16:28:38 "Remote: 192.168.1.47:58807" 帐号密码不正确


![微信截图_20240723163106](https://github.com/user-attachments/assets/afb7098d-9de8-41f5-9e09-2f52fbc3a5f5)
日志：
2024/07/19 09:04:25 你的IP 240e:3bb:64e:d1d1:41e6:36cb:eae9:59b2 没有变化, 域名 *****.net
2024/07/19 09:04:27 你的IP 14.145.15.131 没有变化, 域名 *****.xyz
2024/07/19 09:04:28 你的IP 240e:3bb:64e:d1d1:41e6:36cb:eae9:59b2 没有变化, 域名 *****.xyz
2024/07/19 09:09:28 IPv6未改变, 将等待 5 次后与DNS服务商进行比对
2024/07/19 09:09:28 IPv4未改变, 将等待 5 次后与DNS服务商进行比对
2024/07/19 09:09:28 IPv6未改变, 将等待 5 次后与DNS服务商进行比对
2024/07/19 09:14:29 IPv6未改变, 将等待 4 次后与DNS服务商进行比对
2024/07/19 09:14:29 IPv4未改变, 将等待 4 次后与DNS服务商进行比对
2024/07/19 09:14:29 IPv6未改变, 将等待 4 次后与DNS服务商进行比对
2024/07/19 09:19:29 IPv6未改变, 将等待 3 次后与DNS服务商进行比对
2024/07/19 09:19:30 IPv4未改变, 将等待 3 次后与DNS服务商进行比对
2024/07/19 09:19:30 IPv6未改变, 将等待 3 次后与DNS服务商进行比对
2024/07/19 09:24:30 IPv6未改变, 将等待 2 次后与DNS服务商进行比对
2024/07/19 09:24:30 IPv4未改变, 将等待 2 次后与DNS服务商进行比对
2024/07/19 09:24:30 IPv6未改变, 将等待 2 次后与DNS服务商进行比对
2024/07/19 09:29:30 IPv6未改变, 将等待 1 次后与DNS服务商进行比对
2024/07/19 09:29:31 IPv4未改变, 将等待 1 次后与DNS服务商进行比对
2024/07/19 09:29:31 IPv6未改变, 将等待 1 次后与DNS服务商进行比对
2024/07/19 09:34:31 你的IP 240e:3bb:64e:d1d1:41e6:36cb:eae9:59b2 没有变化, 域名 ****.net
2024/07/19 09:34:33 你的IP 14.145.15.131 没有变化, 域名 *****.xyz
2024/07/19 09:34:33 你的IP 240e:3bb:64e:d1d1:41e6:36cb:eae9:59b2 没有变化, 域名 ****.xyz
2024/07/19 09:39:34 IPv6未改变, 将等待 5 次后与DNS服务商进行比对
2024/07/19 09:39:34 IPv4未改变, 将等待 5 次后与DNS服务商进行比对
2024/07/19 09:39:34 IPv6未改变, 将等待 5 次后与DNS服务商进行比对
2024/07/19 09:44:34 IPv6未改变, 将等待 4 次后与DNS服务商进行比对
2024/07/19 09:44:35 IPv4未改变, 将等待 4 次后与DNS服务商进行比对
2024/07/19 09:44:35 IPv6未改变, 将等待 4 次后与DNS服务商进行比对
2024/07/19 09:49:35 IPv6未改变, 将等待 3 次后与DNS服务商进行比对
2024/07/19 09:49:35 IPv4未改变, 将等待 3 次后与DNS服务商进行比对
2024/07/19 09:49:35 IPv6未改变, 将等待 3 次后与DNS服务商进行比对
2024/07/19 09:54:35 IPv6未改变, 将等待 2 次后与DNS服务商进行比对
2024/07/19 09:54:36 IPv4未改变, 将等待 2 次后与DNS服务商进行比对
2024/07/19 09:54:36 IPv6未改变, 将等待 2 次后与DNS服务商进行比对
2024/07/19 09:59:36 IPv6未改变, 将等待 1 次后与DNS服务商进行比对
2024/07/19 09:59:36 IPv4未改变, 将等待 1 次后与DNS服务商进行比对
2024/07/19 09:59:36 IPv6未改变, 将等待 1 次后与DNS服务商进行比对
2024/07/19 10:04:37 你的IP 240e:3bb:64e:d1d1:41e6:36cb:eae9:59b2 没有变化, 域名 ****.net
2024/07/19 10:04:38 你的IP 14.145.15.131 没有变化, 域名 ai1.066006.xyz
2024/07/19 10:04:39 你的IP 240e:3bb:64e:d1d1:41e6:36cb:eae9:59b2 没有变化, 域名 ***.xyz
2024/07/19 10:09:39 IPv6未改变, 将等待 5 次后与DNS服务商进行比对
2024/07/23 16:28:38 "Remote: 192.168.1.47:58807" 帐号密码不正确
2024/07/23 16:28:42 "Remote: 192.168.1.47:58807" 帐号密码不正确
2024/07/23 16:28:47 通过接口获取IPv4失败! 接口地址: https://myip.ipip.net
2024/07/23 16:28:47 异常信息: Get "https://myip.ipip.net": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024/07/23 16:28:49 更新域名解析 ***.xyz 成功! IP: ***
2024/07/23 16:28:50 更新域名解析 ****.xyz 成功! IP: ***
2024/07/23 16:28:50 Webhook调用成功! 返回数据：{"errcode":0,"errmsg":"ok"}
2024/07/23 16:31:48 "Remote: 192.168.1.47:60097" 帐号密码不正确
2024/07/23 16:31:51 "Remote: 192.168.1.47:60097" 帐号密码不正确
2024/07/23 16:31:55 "Remote: 192.168.1.47:60114" 登陆成功

**Comment by jeessy2** [comment]
你电脑是不是待机了

**Comment by otaku1213** [comment]
只有锁屏，没有休眠和睡眠，每天都在着可以随时远程的

**Comment by jeessy2** [comment]
安装服务吧。能后台运行

**Comment by jeessy2** [comment]
19日到23日之间就没日志

**Comment by otaku1213** [comment]
好的 我试试看，感谢。

**Comment by otaku1213** [comment]
安装服务一切正常，感谢
