### ISSUE TITLE
容器安装，忘记密码怎么办

### ISSUE THREAD

**Issue by dayoocn11** [jeessy2/ddns-go#1187]
### 功能描述

容器安装，忘记密码怎么办

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
直接运行如下，并把123456改成复杂的密码
`docker exec ddns-go ./ddns-go -resetPassword 123456`

**Comment by dayoocn11** [comment]
首先谢谢你，输入命令回复如下：
root@iStoreOS:~# docker exec ddns-go ./ddns-go -resetPassword 123456
flag provided but not defined: -resetPassword
Usage of ./ddns-go:
  -c string
        自定义配置文件路径 (default "/root/.ddns_go_config.yaml")
  -cacheTimes int
        间隔N次与服务商比对 (default 5)
  -dns string
        自定义 DNS 服务器（例如 1.1.1.1）
  -f int
        同步间隔时间(秒) (default 300)
  -l string
        监听地址 (default ":9876")
  -noweb
        不启动 web 服务
  -s string
        服务管理, 支持install, uninstall, restart
  -skipVerify
        跳过验证证书, 适合不能升级的老系统
  -u    更新 ddns-go
  -v    ddns-go 版本

**Comment by jeessy2** [comment]
升级到最新版本

**Comment by dayoocn11** [comment]
用chaigpt帮忙解决了：
忘记密码：进入容器内部：docker exec -it ddns-go /bin/sh    
查看配置文件：cat /root/.ddns_go_config.yaml
是因为不知道什么原因被动被修改成一个很长的密码

**Comment by dayoocn11** [comment]
查看配置文件里面有密码

**Comment by dayoocn11** [comment]
user:
    username: root
    password: $2a$10$4hSbp1hwsoDIXrd6iBT/T.VfCjwpZ7JZarZDpvRvDneUq8LHPQpE.
这么长。。。。

**Comment by jeessy2** [comment]
最新版本密码加密了的

**Comment by PeichenXie2012** [comment]
+1，搞得我每次重启后密码就没用了，怕不是要用加密了的密码才行
