### ISSUE TITLE
建议增加QMSG酱推送

### ISSUE THREAD

**Issue by skoy03** [jeessy2/ddns-go#1189]
### 功能描述

建议增加QMSG酱推送方式,qmsg酱支持私有云也就是可以使用qmsg酱官方地址和自定义地址
官方地址：https://qmsg.zendee.cn/send/4dfglkslkfiuoernglalksajkljlhdgh
私有云地址：http://私有云IP:私有云WEB端口/send/4dfglkslkfiuoernglalksajkljlhdgh

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
只它支持webhook方式就可以的

**Comment by skoy03** [comment]
话说，centos7的系统应该下载哪个安装包?
