### ISSUE TITLE
3.1.1window 64下载的版本还是3.1.0

### ISSUE THREAD

**Issue by mkfd** [jeessy2/ddns-go#119]
3.1.1mac和window 64下载的版本还是3.1.0，至少是页面显示的还是3.1.0
![截屏2021-10-11 下午5 29 24](https://user-images.githubusercontent.com/32868578/136767224-cfb1f276-cdaa-4aa6-b003-90dde5acc622.png)

**Comment by jeessy2** [comment]
3.1.1. 只是这里没改到

**Comment by jeessy2** [comment]
重新发包。稍等

**Comment by mkfd** [comment]
> 重新发包。稍等

好了。感谢开发者
