### ISSUE TITLE
找不到用户名和密码

### ISSUE THREAD

**Issue by lingxingsever** [jeessy2/ddns-go#1190]
### 问题描述

我在使用您开发的ddns时，打开后提示无需属于账号密码，但我登录进去后想要保存ddns配置上提示必须输入账号密码，找了一圈也没发现账号和密码

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

6.6.4

### 安装方式

其它

### 额外信息

![2EAFE28D3DC716F0C3408A8411E58A42](https://github.com/user-attachments/assets/dc7200c6-44e2-4acb-b85b-55b40c361ec1)

**Comment by lingxingsever** [comment]
搜索什么呢

**Comment by jeessy2** [comment]
密码

**Comment by lingxingsever** [comment]
![QQ截图20240718170507](https://github.com/user-attachments/assets/fa12bff0-2bd8-44ff-abf4-a42664892f4c)
没有诶

**Comment by jeessy2** [comment]
直接点登陆

**Comment by lingxingsever** [comment]
![QQ截图20240718170705](https://github.com/user-attachments/assets/3fa61783-72cb-4e7f-8862-3e22158c188d)
没法保存

**Comment by jeessy2** [comment]
> ![QQ截图20240718170705](https://github.com/user-attachments/assets/3fa61783-72cb-4e7f-8862-3e22158c188d)
> 
> 没法保存

要在下方填写密码

**Comment by lingxingsever** [comment]
还是这样

**Comment by jeessy2** [comment]
你超时了，都提示你5分钟内配置。重启ddns-go

**Comment by lingxingsever** [comment]
我软件都关闭了，为啥端口又被占用了

**Comment by jeessy2** [comment]
重启电脑

**Comment by lingxingsever** [comment]
可算保存成功了，谢谢

**Comment by jeessy2** [comment]
5分钟够填写了不，不够设置长点

**Comment by yangbao93** [comment]
我也遇到相同的问题，不用密码登录 ，但是保存的时候就需要了
<img width="1106" alt="Snipaste_2024-07-18_23-46-02" src="https://github.com/user-attachments/assets/67c160cd-59e3-41ae-a370-1294b61f0a58">
<img width="1195" alt="Snipaste_2024-07-18_23-46-59" src="https://github.com/user-attachments/assets/8a23f792-7a7d-4334-8eb4-0db43f81277f">

**Comment by jeessy2** [comment]
> 我也遇到相同的问题，不用密码登录 ，但是保存的时候就需要了
> 
> <img width="1106" alt="Snipaste_2024-07-18_23-46-02" src="https://github.com/user-attachments/assets/67c160cd-59e3-41ae-a370-1294b61f0a58">
> 
> <img width="1195" alt="Snipaste_2024-07-18_23-46-59" src="https://github.com/user-attachments/assets/8a23f792-7a7d-4334-8eb4-0db43f81277f">
> 
> 
> 
> 

第一个是登陆页面，你没设置所以不需要。第二个是设置页面，都提示你必须输入密码了，你怎么不输入。这个有这么复杂么😓？

**Comment by yangbao93** [comment]
> > 我也遇到相同的问题，不用密码登录 ，但是保存的时候就需要了
> > <img alt="Snipaste_2024-07-18_23-46-02" width="1106" src="https://private-user-images.githubusercontent.com/8946052/350034987-67c160cd-59e3-41ae-a370-1294b61f0a58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTMwNTIsIm5iZiI6MTcyMTM1Mjc1MiwicGF0aCI6Ii84OTQ2MDUyLzM1MDAzNDk4Ny02N2MxNjBjZC01OWUzLTQxYWUtYTM3MC0xMjk0YjYxZjBhNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTlUMDEzMjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWEyYTc4OTVhYmNhZmFjM2Y3OWQyNTM5ZTlhY2IyMjY5ZjJlZDhlZDM2MjIwMmNmMjc0ZTg5M2FiZjU4NDkyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VVYQeNqWT0x-BmM0TQYNbWRKL4UMow9deP2knf6GpYU">
> > <img alt="Snipaste_2024-07-18_23-46-59" width="1195" src="https://private-user-images.githubusercontent.com/8946052/350035008-8a23f792-7a7d-4334-8eb4-0db43f81277f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTMwNTIsIm5iZiI6MTcyMTM1Mjc1MiwicGF0aCI6Ii84OTQ2MDUyLzM1MDAzNTAwOC04YTIzZjc5Mi03YTdkLTQzMzQtOGViNC0wZGI0M2Y4MTI3N2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTlUMDEzMjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmM2YmYxMjU0ZjdjYWZjMGQ3MjM2NTBmNzE0YWUwZTVhNDBmYmQ1NDhkMTk5ZDI2MGQwZWQwNTdjODMzNmY3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZBEWq1wRj220-bd7RT7-c87H31UZ_dAB67yn3eLHrkM">
> 
> 第一个是登陆页面，你没设置所以不需要。第二个是设置页面，都提示你必须输入密码了，你怎么不输入。这个有这么复杂么😓？

感谢回复，填写不对这是我理解的问题，我对这个功能的设计逻辑没弄清楚。

不知道是否可以优化一下第二个页面的提示信息。目前提示必须输入登录用户名/密码，很容易联想到的是第一个页面要填的，我也纠结我没有第一个页面的用户名密码，怎么填写第二个页面的用户名密码？ 

这些仅是我个人的一个疑问，再次感谢大佬，respect🫡

**Comment by jeessy2** [comment]
第一个长得不像登陆页面么
现在在第一个页面提示登陆后设置账号密码了

**Comment by yangbao93** [comment]
> 第一个长得不像登陆页面么 现在在第一个页面提示登陆后设置账号密码了

第一个页面是登录页面，但是第一个页面到第二个页面没有填写任何登录信息。 就好比第一个页面没有要我任何信息，第二个页面转头要我第一个页面的信息，会让人有些疑惑。

用户的理解是：要么第一个页面我就有初始化好了的用户名密码，要么第一个页面就可以设置用户名密码。（和大多数的软件、游戏的逻辑是一致的）

**Comment by jeessy2** [comment]
没有默认的账号密码，也不会自动生成账号密码。要手动填写。也有这种系统，类似windows/Linux

**Comment by yangbao93** [comment]
> 没有默认的账号密码，也不会自动生成账号密码。要手动填写。也有这种系统，类似windows/Linux

他们初始化了administer/root ，且可以不用设置密码。这确实哈。我们只是讨论了这样的一个疑惑点，并不是说咱们的设计就是有问题。

**Comment by jeessy2** [comment]
前几个版本，未设置会自动跳转的，有些人说闪现一个页面，才改成的提示点击登录

**Comment by 911061873** [comment]
这一块的用户交互我觉得应该设计成这样：
在登录页面判断是否初始化了用户，如果没有，则提示跳转或直接跳转到用户初始化的网页。
初始化完成后返回登录页面，正常登录。
登录进系统后可修改账号密码。

**Comment by jeessy2** [comment]
> 这一块的用户交互我觉得应该设计成这样：
> 
> 在登录页面判断是否初始化了用户，如果没有，则提示跳转或直接跳转到用户初始化的网页。
> 
> 初始化完成后返回登录页面，正常登录。
> 
> 登录进系统后可修改账号密码。

多了一个页面，不如随机账号密码算了

**Comment by Emtier** [comment]
> > 这一块的用户交互我觉得应该设计成这样：
> > 在登录页面判断是否初始化了用户，如果没有，则提示跳转或直接跳转到用户初始化的网页。
> > 初始化完成后返回登录页面，正常登录。
> > 登录进系统后可修改账号密码。
> 
> 多了一个页面，不如随机账号密码算了

建议首次登陆生成一个默认用户名和密码显示在日志/首页 用户修不修改自己决定

**Comment by jeessy2** [comment]
> > > 这一块的用户交互我觉得应该设计成这样：
> > > 在登录页面判断是否初始化了用户，如果没有，则提示跳转或直接跳转到用户初始化的网页。
> > > 初始化完成后返回登录页面，正常登录。
> > > 登录进系统后可修改账号密码。
> > 
> > 
> > 多了一个页面，不如随机账号密码算了
> 
> 建议首次登陆生成一个默认用户名和密码显示在日志/首页 用户修不修改自己决定

那位感兴趣来PR

**Comment by SillyShalong** [comment]
需要去配置文件目录，打开ddns-go-config.yaml
user:
  username: ""
  password: ""
  
 找到这两个配置项，配置一下。 重启服务，就可以了

**Comment by jeessy2** [comment]
> To be honest, these 5 minutes were really shit

It has been changed to 10 minutes. u can fork, and u can modify it yourself

**Comment by jeessy2** [comment]
> > > 这一块的用户交互我觉得应该设计成这样：
> > > 在登录页面判断是否初始化了用户，如果没有，则提示跳转或直接跳转到用户初始化的网页。
> > > 初始化完成后返回登录页面，正常登录。
> > > 登录进系统后可修改账号密码。
> > 
> > 
> > 多了一个页面，不如随机账号密码算了
> 
> 建议首次登陆生成一个默认用户名和密码显示在日志/首页 用户修不修改自己决定

不生成默认的用户名或密码，显示在首页不安全，显示在日志中，有些人可能找不到日志在哪里，考虑到一些非标准的系统。
方案：
- 加长初始化时间为30分钟。
- 优化提示

**Comment by hylnb** [comment]
建议增加一个命令，一键回归初始设置

**Comment by jeessy2** [comment]
> 建议增加一个命令，一键回归初始设置
> 
>

**Comment by Zerorigin** [comment]
虽然这个 issue 关闭了，但是我觉得这个建议在这里提还是比较好的
改个初次配置登录账号和密码的逻辑，可以很方便的杜绝此问题

初次配置时，打开登录页面，不允许空账号和空密码登录
强制要求填写账号及密码（可以顺便在代码里把账号和密码复杂度要求校验一并做了）
初次配置时，在账号密码填写框的下一行给个提示或者复选框来提示其它注意事项，比如提示“登录并配置为管理员账户”
后端记得校验是否是初次配置账号密码，防止已配置过的利用调接口二次配置覆盖原有密码，杜绝安全隐患

这个逻辑不难写，稍微修改下登录接口的校验逻辑的流程就行了，当然页面也是有些代码变动的

**Comment by jeessy2** [comment]
> 虽然这个 issue 关闭了，但是我觉得这个建议在这里提还是比较好的
> 
> 改个初次配置登录账号和密码的逻辑，可以很方便的杜绝此问题
> 
> 
> 
> 初次配置时，打开登录页面，不允许空账号和空密码登录
> 
> 强制要求填写账号及密码（可以顺便在代码里把账号和密码复杂度要求校验一并做了）
> 
> 初次配置时，在账号密码填写框的下一行给个提示或者复选框来提示其它注意事项，比如提示“登录并配置为管理员账户”
> 
> 后端记得校验是否是初次配置账号密码，防止已配置过的利用调接口二次配置覆盖原有密码，杜绝安全隐患
> 
> 
> 
> 这个逻辑不难写，稍微修改下登录接口的校验逻辑的流程就行了，当然页面也是有些代码变动的

第一个是登陆页面做检验，又做设置账号密码的页面，感觉不是更加复杂了？

这些都可以探讨一下，感谢提出

**Comment by jeessy2** [comment]
根据建议，优化为？
未填写账号密码，登陆页不显示账号密码输入框，登陆按钮改为: 进入初期设置

**Comment by Zerorigin** [comment]
> 根据建议，优化为？ 未填写账号密码，登陆页不显示账号密码输入框，登陆按钮改为: 进入初始设置

登录按钮的文字改为“登录并配置为管理员账号”，这样应该就够了，不需要另外弄个界面了

是否初次配置，在登录接口做很简单的，只要检查下从配置里读到密码键值对是否为空或空值即可
然后根据这个响应前段的登录按钮提示词
并且在密码为空的时候，将加盐哈希过的密码回写存储到配置里即可

我一些个人的小项目，因为自用，懒得将注册和登录页面分开，都是这么取巧做的，忘记密码就去配置里删掉密码的键值对，重启下服务，这样也很方便

**Comment by jeessy2** [comment]
> > 根据建议，优化为？ 未填写账号密码，登陆页不显示账号密码输入框，登陆按钮改为: 进入初始设置
> 
> 登录按钮的文字改为“登录并配置为管理员账号”，这样应该就够了，不需要另外弄个界面了。
> 
> 是否初次配置，在登录接口做很简单的，只要检查下从配置里读到密码键值对是否为空或空值即可。 然后根据这个响应 Web 前端的登录按钮提示词。 并且在密码为空的时候，将加盐哈希过的密码回写存储到配置里即可。
> 
> 我一些个人的小项目，因为自用，懒得将注册和登录页面分开，都是这么取巧做的，忘记密码就去配置里删掉密码的键值对，重启下服务，这样也很方便。
> 
> 这样原本配置页面里的账号密码设置逻辑应该不需要修改？因为那里大概率是要校验 token 的？（没具体看过这个项目的代码，不太清楚，是按照自己已有经验做的简单推断）

在登录页设置帐号密码也可以，时间限制30分钟就放在登录逻辑里，只有在启动30分钟内才可以初始化用户名和密码

**Comment by jeessy2** [comment]
v6.6.7 改为：如果不存在帐号密码，直接在登录页设置账号密码

**Comment by tbc0309** [comment]
> v6.6.7 改为：如果不存在帐号密码，直接在登录页设置账号密码

赞成！配置界面里面的删除掉，碰到用户反馈被浏览器自动填充给改了……

**Comment by jeessy2** [comment]
> > v6.6.7 改为：如果不存在帐号密码，直接在登录页设置账号密码
> 
> 赞成！配置界面里面的删除掉，碰到用户反馈被浏览器自动填充给改了……或者改密码改成弹窗？

应该不会自动填充吧。参考代码`autocomplete="new-password"`
