### ISSUE TITLE
新增子域名解析失败

### ISSUE THREAD

**Issue by Blubiubiu** [jeessy2/ddns-go#1195]
### Description

主域名解析www添加正常，子域名解析时使用@报错
![image](https://github.com/user-attachments/assets/6e596598-6645-4ead-9bf8-f52bee68378e)
已使用方法：
1，使用 @:xxx.xxx.xxx
2,  使用:xxx.xxx.xxx
以上两种方式设置后均不可

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Linux

### Architecture

i386

### Version

v6.6.4

### How are you running ddns-go?

Docker

**Comment by Blubiubiu** [comment]
![image](https://github.com/user-attachments/assets/638fbc5f-ed55-4998-8fb5-9fa058749fa4)
![image](https://github.com/user-attachments/assets/7b2117c0-ada4-4e3c-a266-9a87d6552f5d)

**Comment by jeessy2** [comment]
正常填写，不要加`:` 或 `@`

**Comment by Blubiubiu** [comment]
正常填写也不行
![image](https://github.com/user-attachments/assets/37179509-a774-47af-a5b5-9ee6196e60fa)
![image](https://github.com/user-attachments/assets/3a23aa05-af8a-4f4a-adaf-e72a3f03cd84)

**Comment by Blubiubiu** [comment]
自己的问题，domain错了

**Comment by jeessy2** [comment]
你不是第一个填错的
