### ISSUE TITLE
卡巴斯基安全软件报毒

### ISSUE THREAD

**Issue by xinjiajuan** [jeessy2/ddns-go#1201]
### Description

卡巴斯基报毒内容如下：
```
事件: 检测到恶意对象
用户: DESKTOP-EG69OHQ\xinjiajuan
用户类型: 活动用户
应用程序名称: SurSvc.exe
应用程序路径: C:\Program Files\Intel\SUR\QUEENCREEK
组件: 文件反病毒
结果说明: 检测到
名称: UDS:DangerousObject.Multi.Generic
精确度: 确切
威胁级别: 高
对象类型: 文件
对象名称: ddns-go.exe
对象路径: C:\Users\xinjiajuan\app\ddns-go
MD5: 4C1BA688E39BA5587997EE6313B3AD9E
原因: 云保护
```

### DNS Provider

DnsPod

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Windows

### Architecture

x86_64

### Version

v6.6.5

### How are you running ddns-go?

Service

**Comment by jeessy2** [comment]
https://go.dev/doc/faq#virus

**Comment by jeessy2** [comment]
换个杀毒软件，或者用docker，或则换个软件
