### ISSUE TITLE
解析延迟及泛解析ttl被自动改成10min的问题

### ISSUE THREAD

**Issue by baiyefeiyu** [jeessy2/ddns-go#1206]
### Description

环境：群晖7.2   ddns版本：6.6.7(群晖套件)
1.自动更改泛解析ttl问题：我现在阿里云可以设置ttl为一分钟，但是ddns go会自动将泛解析ttl改成十分钟。
2.二级域名更新很慢：泛解析基本是ip变化后十几秒内就更新了，但是二级域名需要十几分钟。

![b38f2b943579fdd61053002713c3e4c](https://github.com/user-attachments/assets/0f436236-6dc0-4cc8-a2fa-016359d8d4ab)
![1dc25fd7b1761d35da3b6c39280a3ae](https://github.com/user-attachments/assets/afec5b4e-363e-4de4-bf00-7579cea76476)
![71ed71474768d9709193cca862009d4](https://github.com/user-attachments/assets/8a325003-529d-4e7f-a87f-9d703c7a599f)

### DNS Provider

阿里云

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Linux

### Architecture

x86_64

### Version

v6.6.7

### How are you running ddns-go?

Docker

**Comment by jeessy2** [comment]
这个不好看日志，建议clone后debug

**Comment by baiyefeiyu** [comment]
> 这个不好看日志，建议clone后debug

![1722586593034](https://github.com/user-attachments/assets/f052c80f-1e47-4124-9be3-5eb391f464c9)
![image](https://github.com/user-attachments/assets/17777e7f-39c2-405c-902c-f2efe6e75d57)

我原先用的套件，刚才重新在docker又部署了一套。
1.看起来好像二级域名更新的时间没之前久了。
2.泛解析的TTL我手动改成60s，从日志看，ip更新后，直接给改成600s了。我感觉这个应该是ddns go给阿里同步信息的时候改的吧，应该不是只有我有问题吧。。。。。原本还打算二级域名更新慢的话，只配置泛解析，结果泛解析十分钟，我进入死胡同了。二级域名不存在这个情况。

**Comment by jeessy2** [comment]
是不是开了几个ddns同步，互相在抢。16:12的ttl为60对的吧？16:10没有同步日志

**Comment by baiyefeiyu** [comment]
> 是不是开了几个ddns同步，互相在抢。16:12的ttl为60对的吧？16:10没有同步日志

16:04  的时候我手动改了 泛解析 的ttl；
16:10  重启路由器后，泛解析第一时间更新了ip并且把ttl改成了600s;
16:12  二级域名nas.XXX更新了ip（二级域名的ttl一直都是60，并不会因为同步而改为600）

**Comment by baiyefeiyu** [comment]
> 是不是开了几个ddns同步，互相在抢。16:12的ttl为60对的吧？16:10没有同步日志

我看权重配置那儿没办法操作，都是灰的，目前看起来所有的解析都是1级权重，但是我今天实验了大概有20+次了吧，每次都是泛解析先更新，二级域名有时候得十几分钟都不变

**Comment by jeessy2** [comment]
你自己分析下了，整得太复杂。看谁有空帮你分析下

**Comment by baiyefeiyu** [comment]
> 你自己分析下了，整得太复杂。看谁有空帮你分析下

周围的其他人都是小白，哈哈哈。其实我现在就想明确一个问题：

到底ddns-go给阿里同步泛解析的时候是不是会强制更改ttl为600（我ddns-go其实没配置泛解析，我只要随便配置个二级域名，ddns同步阿里后就会生成一条泛解析的记录）

**Comment by jeessy2** [comment]
TTL根据设置来的。没配置又增加泛解析，你问下阿里云

**Comment by baiyefeiyu** [comment]
> TTL根据设置来的。没配置又增加泛解析，你问下阿里云

好吧，今天白天电联了，大概意思就是阿里这边应该没啥问题。行吧，我再问问吧

**Comment by baiyefeiyu** [comment]
> 多检查下的配置，你是第一个没有设置泛解析，而“自动”加的

唉，我也无语了，我阿里云那边解析都删了，也是这种，ddns配置也就是我给你截图那种。不理解了

**Comment by jeessy2** [comment]
把ddns-go停了，你看还有日志不？
删除阿里云的key,重新建

**Comment by baiyefeiyu** [comment]
> 把ddns-go停了，你看还有日志不？ 删除阿里云的key,重新建

经过反复测试，只有重启路由器后会产生泛解析记录。如果把泛解析记录删了，重新保存ddns配置，只会同步二级域名，不会产生泛解析记录。
也就是说，为啥重启路由器会导致生成泛解析记录呢

**Comment by jeessy2** [comment]
路由器设置了ddns？

**Comment by baiyefeiyu** [comment]
> 路由器设置了ddns？

![Screenshot_20240803_084030](https://github.com/user-attachments/assets/bec0ac2c-68e5-4dd6-bbed-04b66826b7e5)
没有啊，路由器装了crash，我看看有啥配置有关系

**Comment by baiyefeiyu** [comment]
检查了路由器，自带的ddns没开，crash的ddns也没开。

**Comment by baiyefeiyu** [comment]
搞不懂了，采用重启大法解决了。
阿里的增值服务退了，。重新在腾讯云搞了个域名，一切正常了。

**Comment by baiyefeiyu** [comment]
今天突然问题原因的根源找到了。。。。。。。。。虽然很尴尬，但是还是说一下吧。。。。。。
心血来潮，想再整一下反向代理，然后找到容器，发现lucky竟然开着，我心想这玩意儿很久前用过就关了啊。打开后。。。。赫然看见一项ddns服务开着。。。。。。。。。。。。。。。再见，不丢人了。果然越是玄幻的技术问题，必然存在着一波sb操作。

**Comment by ritaswc** [comment]
> 今天突然问题原因的根源找到了。。。。。。。。。虽然很尴尬，但是还是说一下吧。。。。。。 心血来潮，想再整一下反向代理，然后找到容器，发现lucky竟然开着，我心想这玩意儿很久前用过就关了啊。打开后。。。。赫然看见一项ddns服务开着。。。。。。。。。。。。。。。再见，不丢人了。果然越是玄幻的技术问题，必然存在着一波sb操作。

及时关闭Issue
