### ISSUE TITLE
修改解析到的时原域名DNS记录并不会被删除

### ISSUE THREAD

**Issue by alazeprt** [jeessy2/ddns-go#1212]
### Description

如题，当你修改IPv4解析到的域名（如将a.xxx.top修改为b.xxx.top）时，原解析域名（a.xxx.top）中已经被ddns-go修改的DNS记录仍然存在

### DNS Provider

Cloudflare

### Did you search for similar issues before submitting this one?

No, I didn't

### Operating System

Linux

### Architecture

x86_64

### Version

v6.6.7

### How are you running ddns-go?

Service

**Comment by jeessy2** [comment]
是这样的，只有去手动删除

**Comment by dpy013** [comment]
腾讯云也是这样的。

**Comment by Emtier** [comment]
就是这样设计的 不是bug
