### ISSUE TITLE
请问能加一个，是否选择自动更新的功能么，及配置文件导入导出,重启服务按钮

### ISSUE THREAD

**Issue by betakernel** [jeessy2/ddns-go#1213]
### Description

1自动更新选项，
 启用，
     设置自动更新时间
 禁用
2配置文件导入导出
3能加一个重启，启动。停用服务按钮么

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
自动更新 `./ddns-go -u`
配置为什么要导入导出，就在当前用户目录下
服务不是有重启

**Comment by betakernel** [comment]
我意思是比如。 几小时。或者自定义时间。检测ddns-go有没有新版本。自动更新

**Comment by jeessy2** [comment]
> 我意思是比如。 几小时。或者自定义时间。检测ddns-go有没有新版本。自动更新

欢迎PR
