### ISSUE TITLE
Support for multiple IPs in a A/AAAA DNS record.

### ISSUE THREAD

**Issue by Zerorigin** [jeessy2/ddns-go#1214]
### Description

现有的 A/AAAA DNS record 都是支持同一 record 映射到多个 IP 地址的
仅仅需要创建多个同一前缀的 A/AAAA 记录即可

当然，更新的时候需要批量删除旧记录，再批量添加新记录
（不清楚各个厂商的 update 接口能不能一次性直接传整个 IPs 列表来更新）
使用 DNS 查询判断记录变动情况的，则需要稍微修改下判断逻辑
若解析出来的记录包含获取到的待更新 IP，则不进行更新动作
若不包含，则批量删除旧记录，再批量添加新记录

这个东西并不着急，不知道是否会给实现？

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
同一个record支持多个ip，首页不是有说明？

**Comment by Zerorigin** [comment]
> 同一个record支持多个ip，首页不是有说明？

仔细看了一下，在自定义传递传参里面，不过和我想的有点不太一样
得新建两个不同 "ID" 的相同配置，略微麻烦了点

**Comment by jeessy2** [comment]
你能实现更好更简单的，欢迎PR

**Comment by Zerorigin** [comment]
> 你能实现更好更简单的，欢迎PR

请原谅我有一点点懒（哈哈），变动太多的东西不想提 PR
这个 issue 就这样关了也行，反正我也没在用同一 Record 映射多 IPs 功能
只是突然想法上的一时兴起而已

**Comment by jeessy2** [comment]
👍你可以先看下文档在提`enhancement`不

**Comment by Zerorigin** [comment]
> 👍你可以先看下文档在提`enhancement`不

下次会注意的，不好意思。

**Comment by jeessy2** [comment]
it's okay.
