### ISSUE TITLE
首次登录报错: "需在 2024-08-06 17:00:38 之前完成用户名密码设置,请重启ddns-go"

### ISSUE THREAD

**Issue by vhxnyu** [jeessy2/ddns-go#1216]
### Description

![QQ截图20240808124848](https://github.com/user-attachments/assets/8b656a1c-e751-4388-969c-043b8f87f198)

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Linux

### Architecture

x86_64

### Version

v6.6.7

### How are you running ddns-go?

Service

### Any other information

尝试过重新安装
![image](https://github.com/user-attachments/assets/93d7dd52-4c1d-45df-82b7-57d4105f69ea)

**Comment by jeessy2** [comment]
./ddns-go -s restart

**Comment by vhxnyu** [comment]
> ./ddns-go -s restart

仍然报错, 相同的错误

**Comment by vhxnyu** [comment]
啊这, 卸载后, 仍然可以访问, 似乎是docker版本的ddnsgo没有卸载干净

**Comment by jeessy2** [comment]
你发的安装的服务，不是docker

**Comment by vhxnyu** [comment]
> 你发的安装的服务，不是docker

我没搞错, 我把服务卸载了, 仍然可以访问网页

原因是在1panel里安装过docker版, 后来卸载1panel了没想到没有他同时删除容器
![image](https://github.com/user-attachments/assets/5499768a-766d-40f0-a914-31aa11785f2f)

现在他正常运行
