### ISSUE TITLE
通过接口获取IPv6失败! 接口地址: https://speed.neu6.edu.cn/getIP.php

### ISSUE THREAD

**Issue by CrazyManjuu** [jeessy2/ddns-go#1218]
### Description

异常信息: Get "https://speed.neu6.edu.cn/getIP.php": dial tcp6 [2001:da8:9000::66]:443: connect: network is unreachable

### Did you search for similar issues before submitting this one?

No, I didn't

### Operating System

Windows

### Architecture

i386

### Version

v6.6.8

### How are you running ddns-go?

Docker

**Comment by jeessy2** [comment]
IPv6正常？

**Comment by CrazyManjuu** [comment]
原来解析IPV6是不能再docker中运行，需要在系统中运行。
