### ISSUE TITLE
 查询域名信息发生异常

### ISSUE THREAD

**Issue by caioplpl** [jeessy2/ddns-go#1219]
### Description

2024/08/12 11:52:06 查询域名信息发生异常! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400
![screenshot-1723435116551](https://github.com/user-attachments/assets/a8f51449-e46a-46ab-922a-c1cc099dab88)

### DNS Provider

Cloudflare

### Did you search for similar issues before submitting this one?

No, I didn't

### Operating System

Linux

### Architecture

x86_64

### Version

V6.68

### How are you running ddns-go?

Docker

**Comment by jeessy2** [comment]
重新生成key

**Comment by nayihz** [comment]
> 重新生成key

仍然不行
