### ISSUE TITLE
期望能新增@max这样的命令，可以获取最后一个ipv6地址

### ISSUE THREAD

**Issue by kylongteng** [jeessy2/ddns-go#1220]
### Description

首先感谢作者的付出。
期望能新增@max这样的命令，可以获取最后一个ipv6地址。
拨号路由器每次重启时都会导致路由器本身和客户端多一个（或者两个）ipv6地址，旧的ipv6地址因为运营商下发的前缀变化了，原来的ipv6地址已经失效。使用@指定ipv6地址时，没办法选择最后一个(有效的)ipv6地址。期望新增类似@max这样的命令取最后一个

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
通过命令获取？

**Comment by kylongteng** [comment]
> 通过命令获取？

docker安装的，然后目前用的网卡获取，使用@2指定（第一个有效但我不用，主要是为了防火墙后缀方形。正常情况下第二个是对的），然后重启后第二个失效，第三个才是有效的。如果命令能解决，请问命令如何写呢

**Comment by jeessy2** [comment]
参考 #531 
也可PR

**Comment by kylongteng** [comment]
很早之前我看到过https://github.com/jeessy2/ddns-go/issues/531
但不能解决我的问题。期望什么时候加入这个功能吧。我先前都是手动改@后面的数字，等旧的ipv6消失后又手动改回@2  ……

**Comment by guohu7777** [comment]
![image](https://github.com/user-attachments/assets/bdd377b7-8a74-4bbc-9966-4480783a5654)
我之前的网络也是和你一样的问题,你可以试试用这种方式去获取最新的ipv6地址.  https://speed.neu6.edu.cn/getIP.php

**Comment by kylongteng** [comment]
> ![image](https://private-user-images.githubusercontent.com/75009704/357242778-bdd377b7-8a74-4bbc-9966-4480783a5654.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTI1NTUsIm5iZiI6MTcyMzUxMjI1NSwicGF0aCI6Ii83NTAwOTcwNC8zNTcyNDI3NzgtYmRkMzc3YjctOGE3NC00YmJjLTk5NjYtNDQ4MDc4M2E1NjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDAxMjQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjM2Q5Y2EyYWY5MGI1OWZlOGQzMTYwMWFjYTU3ZTJhMDRjNDEzN2MxZDZmZWM3NjA1MTI0NzY2N2I5ZGQ2YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19HWp2hQbYIDyjK9eBNmSp80oVZgbjrXlb5b2Oxt-Ws) 我之前的网络也是和你一样的问题,你可以试试用这种方式去获取最新的ipv6地址. https://speed.neu6.edu.cn/getIP.php

先前我试过，很奇怪的是这个方式拿到的128那个短公网ipv6地址.昨天后来我把ddns换到拨号路由上了，然后防火墙按ipv6后缀接受入站，再防火墙通过目标内网ipv6转发到目标上。暂时先用这个方案

**Comment by kylongteng** [comment]
我目前通过以下命令可以满足要求，直接获取最新的ipv6地址：如果本机有多个ipv6地址，通过过期时间判断拿到最新的ipv6地址。

ip addr show|grep -v deprecated|grep -A1 'inet6 [^f:]'|sed -nr ':a;N;s#^ +inet6 ([a-f0-9:]+)/.+? scope global .*? valid_lft ([0-9]+sec) .*#\2 \1#p;ta'|grep 'ff:fe'|sort -nr|head -n1|cut -d' ' -f2
