### ISSUE TITLE
重启后密码不可用

### ISSUE THREAD

**Issue by PeichenXie2012** [jeessy2/ddns-go#1222]
### Description

每一次重启设备（Pi4）后，web后台的原密码就无法使用，没法登录后台，必须每次重启设备后都-resetPassword一次，且再次重启之后又会再次无法登录

### DNS Provider

Cloudflare

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Linux

### Architecture

arm64

### Version

v6.6.8

### How are you running ddns-go?

Service

**Comment by PeichenXie2012** [comment]
我也尝试过直接更改配置文件，也没效果

**Comment by jeessy2** [comment]
重启观察密码变没有

**Comment by PeichenXie2012** [comment]
好神奇，貌似上次安装带了sudo的原因，这次重装了一次没用sudo居然就解决了？！再观察一下
