### ISSUE TITLE
[功能请求]请求添加配置名参数用于webhook推送：A/B配置名

### ISSUE THREAD

**Issue by NEANC** [jeessy2/ddns-go#1225]
# 请求添加新配置名参数在 webhook 推送时使用

添加新变量：配置名 `#{servername}`

应用范围：多个配置 / 单域名多服务商同时解析

## 期望功能：

1. 配置名：A服务商  
   - webhook 推送回报：  
     - 当前解析方：A服务商  
2. 配置名：B服务商
   - webhook 推送回报：  
     - 当前解析方：B服务商  

### 例

```diff
- name: 腾讯云
+ servername = 腾讯云
      ipv4:
        enable: true
      以下略

{
    "msgtype": "markdown",
     "markdown": {
        "title": "您的公网IP已变更：",
        "text": "当前解析方：{servername}  \n"
   }
}

回报：
您的公网IP已变更：
当前解析方：腾讯云
```

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
欢迎PR，不过通过域名也知道是什么服务商
