### ISSUE TITLE
重启容器后，web界面无法打开。

### ISSUE THREAD

**Issue by BI4KIA** [jeessy2/ddns-go#1227]
### Description

重启容器后，web界面无法打开。日志中也没有端口开启信息。

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Linux

### Architecture

arm64

### Version

v6.6.9

### How are you running ddns-go?

Docker

**Comment by BI4KIA** [comment]
可以ping通获取到的IP地址

**Comment by RoryTHWu** [comment]
我也遇到相同情况，问题似乎来自于 --net=host 无法正常配置开启端口。
可以尝试放弃--net=host 直接使用 -p 9876:9876/tcp 开启端口。

修改后的命令：
docker run -d --name ddns-go --restart=always -p 9876:9876/tcp -v /opt/ddns-go:/root jeessy/ddns-go


My system info for ref:
Arch: x86_64
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble

**Comment by BI4KIA** [comment]
> 我也遇到相同情况，问题似乎来自于 --net=host 无法正常配置开启端口。 可以尝试放弃--net=host 直接使用 -p 9876:9876/tcp 开启端口。
> 
> 修改后的命令： docker run -d --name ddns-go --restart=always -p 9876:9876/tcp -v /opt/ddns-go:/root jeessy/ddns-go
> 
> My system info for ref: Arch: x86_64 Distributor ID: Ubuntu Description: Ubuntu 24.04 LTS Release: 24.04 Codename: noble

我是安装在RouterOS系统的容器里面的，感觉像是IPv4与IPv6无法完全兼容，都获取到了IP地址但总有一个不能与外部网络稳定通讯。ping命令也是时而显示v4地址时而显示v6地址。

**Comment by BI4KIA** [comment]
> docker有问题 `/app # netstat -an | grep LISTEN | grep 9876 tcp 0 0 :::9876 :::* LISTEN ` 用--net=host 容器绑定到了ipv6的端口， 如果改为-p 9876:9876，又无法获取到ipv6的ip。

RouterOS中的docker确实不太好用，兼容性比较差，无奈使用其他程序了。

**Comment by BI4KIA** [comment]
我目前发现的问题是在系统关闭重启后，docker容器需要执行手动执行`’/app/ddns-go -c /root/.ddns_go_config.yaml`，web页面和ddns服务才会启动。

**Comment by RoryTHWu** [comment]
如果是docker的问题的话，可以直接找个脚本，设置定时运行来更新dns 记录，效果是一样的。Github上面很多写好的，非常轻量，也很好用。

**Comment by geeklihui** [comment]
我也遇到了，host 模式创建容器后拒绝访问，不使用 host 模式就正常了
