### ISSUE TITLE
请问如何不通过web页面修改配置

### ISSUE THREAD

**Issue by hjldev** [jeessy2/ddns-go#1232]
### Description

想通过命令行修改配置，直接修改文件.ddns_go_config.yaml不生效，请问有什么办法不通过web页面也能修改配置吗

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
直接修改后需要重启ddns-go
