### ISSUE TITLE
v6.6.0卡巴斯基报毒

### ISSUE THREAD

**Issue by RoyZ-iwnl** [jeessy2/ddns-go#1236]
### Description

```
事件: 检测到恶意对象
应用程序: ddns-go.exe
用户: NT AUTHORITY\SYSTEM
用户类型: 系统用户
组件: 系统监控
结果说明: 检测到
类型: 木马
名称: PDM:Trojan.Win32.Bazon.a
威胁级别: 高
对象类型: 进程
对象路径: d:\software\ddns
对象名称: ddns-go.exe
原因: 数据库
数据库发布日期: 2024/8/28 16:09:00
```
```
事件: 对象已删除
应用程序: ddns-go.exe
用户: NT AUTHORITY\SYSTEM
用户类型: 系统用户
组件: 系统监控
结果说明: 已删除
类型: 木马
名称: PDM:Trojan.Win32.Bazon.a
威胁级别: 高
对象类型: 文件
对象路径: D:\Software\ddns
对象名称: ddns-go.exe:Zone.Identifier
```

### DNS Provider

Cloudflare

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Windows

### Architecture

x86_64

### Version

v6.6.0

### How are you running ddns-go?

Service

**Comment by RoyZ-iwnl** [comment]
v6.7.0报为
Trojan-PSW.Win32.Greedy.fgw

**Comment by jeessy2** [comment]
上一个版本报不

**Comment by MAONY-QAQ** [comment]
刚测试了一下，也是报错的。
事件: 对象已删除
用户: MAONY\MAONY
用户类型: 活动用户
应用程序名称: 360zip.exe
组件: 文件反病毒
结果说明: 已删除
类型: 木马
名称: Trojan-PSW.Win32.Greedy.fgz
精确度: 确切
威胁级别: 高
对象类型: 文件
对象名称: ddns-go.exe
MD5: FE8DD59E5D256483679979002632AF9B

**Comment by jeessy2** [comment]
有可能是自动打开浏览器那段，删除自己编译一个试下
