### ISSUE TITLE
qnap 威联通 获取到的ipv4地址不正确

### ISSUE THREAD

**Issue by wang1zhen** [jeessy2/ddns-go#1237]
### Description

在威联通qnap中使用container部署ddns-go后，从记录log中可以发现获取到的ip地址并不正确（使用api获取）

![image](https://github.com/user-attachments/assets/d4e72a47-4b52-4644-8007-1be38d99ffd3)

而我的ip（上海电信，有公网ip）实际是

![image](https://github.com/user-attachments/assets/006816a3-68eb-40b8-87fb-bd3e18d29c35)

考虑到过可能是科学上网导致的，但从ip可以看出并非机场地址，故排除。

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Linux

### Architecture

x86_64

### Version

v6.7.0

### How are you running ddns-go?

Docker

### Any other information

该容器使用host网络，在容器内部还有一些奇怪的现象：

![image](https://github.com/user-attachments/assets/a3c87b85-8be3-4935-893e-e3350f317204)

**Comment by jeessy2** [comment]
这些自己看了吧，自己测一下，通过curl 接口地址测

**Comment by wang1zhen** [comment]
您看一下上面我补充的other information，容器内部curl和ping都尝试过了，trancert没有所以没测试。

**Comment by jeessy2** [comment]
每个人网络情况都不同，自行研究下。我也帮不上什么忙

**Comment by wang1zhen** [comment]
好的谢谢，那我还是先把这个issue close吧，可能是qnap specific problem，因为它自带的myqnapcloud的ddns服务也会获取到这样的ip。主要是他所获取到的这个ip，虽然我科学上网了但是有点八竿子打不着的意思，具体可能还是直接问他们的客服可能更有效。祝好。
