### ISSUE TITLE
namesilo 的使用方式是否有誤？

### ISSUE THREAD

**Issue by 2ipm1nd** [jeessy2/ddns-go#1238]
### Description

大家好，我在 namesilo 購買網域 xixi2go.link 之後，想要透過 ddns-go 更改子網域的 IP，可是怎麼弄都出現錯誤，請問我哪裡弄錯了嗎？

密碼：新創的 API

IPV4 網域填寫

```
memos:xixi2go.link
```

IPV6 網域填寫

```
memos:xixi2go.link
```

出現以下錯誤訊息

```

2024/09/03 13:41:01 配置文件已保存在: /root/.ddns_go_config.yaml
2024/09/03 13:41:02 新增域名解析 memos.xixi2go.link 失败! 异常信息: xixi2go.link could not be loaded
2024/09/03 13:41:03 新增域名解析 memos.xixi2go.link 失败! 异常信息: xixi2go.link could not be loaded
2024/09/03 13:41:03 将不会触发Webhook, 仅在第 3 次失败时触发一次Webhook, 当前失败次数：10
```

### DNS Provider

NameSilo

### Did you search for similar issues before submitting this one?

No, I didn't

### Operating System

Linux

### Architecture

x86_64

### Version

v6.7.0

### How are you running ddns-go?

Docker

**Comment by jeessy2** [comment]
问下namesilo

**Comment by 2ipm1nd** [comment]
有啦，原來子網域只要正常填入就可以了改成

```
memos.xixi2go.link
```
即可
