### ISSUE TITLE
Support for DNS provider ClouDNS

### ISSUE THREAD

**Issue by chaoqiao** [jeessy2/ddns-go#1244]
### Description

ClouDNS is not in the supported DNS provider
<img width="758" alt="ddns-go" src="https://github.com/user-attachments/assets/43902dc4-fc64-4c43-90da-174b24c4de72">

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
There are too many service providers. You can choose existing ones.
