### ISSUE TITLE
请问支持duckdns？

### ISSUE THREAD

**Issue by gzsyl** [jeessy2/ddns-go#1245]
### Description

请问支持duckdns？如果支持，需要如何设置？

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
不直接支持，参考callback写

**Comment by gzsyl** [comment]
callback如何填写？请指教

**Comment by jeessy2** [comment]
自行参考文档写吧

**Comment by nuovomondoc** [comment]
duckdns官方文档里给出了示例：https://www.duckdns.org/update?domains={YOURVALUE}&token={YOURVALUE}[&ip={YOURVALUE}][&ipv6={YOURVALUE}][&verbose=true][&clear=true], 所以callback的url写法是：https://www.duckdns.org/update?domains=#{domain}&token=xxxx&ip=#{ip}，把xxxx替换成你duckdns的token就行了。

B.T.W
#{domain}是ddns-go的域名列表，有几个就执行几次回调，#{ip}是ddns-go获取到的ip地址。
