### ISSUE TITLE
cloudflare 查询域名信息发生异常! per_page=50&status=active": EOF

### ISSUE THREAD

**Issue by dodoy6830** [jeessy2/ddns-go#1246]
### Description

2024/09/10 07:56:26 查询域名信息发生异常! Get "https://api.cloudflare.com/client/v4/zones?name=???????????.xyz&per_page=50&status=active": EOF

偶尔又是可以的，大部分时间不行，更换了不同dns也不行，在hosts文件里写上api.cloudflare.com的ip地址也不行。
ping  api.cloudflare.com 也是正确的。已更新编辑DNS区域的token  么么哒谢谢解答

### DNS Provider

Cloudflare

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Linux

### Architecture

arm64

### Version

6.7.0

### How are you running ddns-go?

Service

### Any other information

没有

**Comment by jeessy2** [comment]
你”网”的问题

**Comment by dodoy6830** [comment]
的确是“网”的问题，关掉小喵喵就好了。

**Comment by AmiroKD** [comment]
> 的确是“网”的问题，关掉小喵喵就好了。

关掉也不行啊

**Comment by luckyBricks** [comment]
> > 的确是“网”的问题，关掉小喵喵就好了。
> 
> 关掉也不行啊

如果在用OpenClash，由于会劫持DNS服务，将ddns-go指定的DNS服务器设置为OpenClash劫持的DNS即可

**Comment by godfather1103** [comment]
openwrt中，关掉OpenClash就可以，dns我也改了，但是只要开启OpenClash就不行

**Comment by godfather1103** [comment]
<img width="1005" height="141" alt="Image" src="https://github.com/user-attachments/assets/06494b1f-dee1-433d-97fb-d4b88bfe8161" />
我这边好像把这里从br-lan改为默认就正常了

**Comment by BitbeyHub** [comment]
> > 的确是“网”的问题，关掉小喵喵就好了。
> 
> 关掉也不行啊

你直接在 DDNS-GO里面 把DNS服务器 设置到 `127.0.0.1` 就好了，路由器就会自动 给你 的 DNS请求纳入链式路由了，就不会出错了，我是这样秒解的
