### ISSUE TITLE
局域网中多台电脑 通过接口获取ipv6 每个电脑获取出来的值不一样

### ISSUE THREAD

**Issue by kyo8598CC** [jeessy2/ddns-go#1247]
### Description

局域网中多台电脑 通过接口获取ipv6 每个电脑获取出来的值不一样
局域网中三台电脑
一个240e:338:4c31:ae40::xxx
一个 240e:338:4c31:ae40:211:22ff:fe33:xxxx
一个240e:338:4c31:ae40:18ec:fb62:1f62:xxxx

然后用一个解析的话就访问不了另外的机器 只有都运行ddns 然后分别解析到不同的域名 才能访问到自己

### DNS Provider

腾讯云

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Linux

### Architecture

x86_64

### Version

last

### How are you running ddns-go?

Docker

**Comment by jeessy2** [comment]
每台不一样，难道每台v6都一样？

**Comment by jeessy2** [comment]
IPv6本意就是解决v4不够分的问题，号称每粒沙子都可以分一个v6地址。
看来知识还没普及到你那里。
