### ISSUE TITLE
安装服务可否使用非系统最高权限？

### ISSUE THREAD

**Issue by charley008** [jeessy2/ddns-go#1251]
### Description

windows安装服务后看到这个dds-go程序以系统权限运行，感觉没必要用这么高的权限。可否使用windows内置用户network service 网络服务 这个内置用户来执行呢？

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
可以fork
