### ISSUE TITLE
ddnsgo页面登录密码忘记

### ISSUE THREAD

**Issue by Eros1007** [jeessy2/ddns-go#1252]
### Description

登录密码忘记，之后多次登录错误，在登录就不行，在ddns_go_config_yaml配置文件中找到的密码是乱码，怎么办

### Problem

无法登录

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
参考首页说明重置密码，或者直接改配置文件的密码，重启后会自动加密

**Comment by Zerorigin** [comment]
> 参考首页说明重置密码，或者直接改配置文件的密码，重启后会自动加密

密码连续尝试错误几次后，加个弹窗提示可以在忘记密码的情况下如何重置密码吧，不然总是偶尔会有人来问的。

**Comment by jeessy2** [comment]
可以PR
