### ISSUE TITLE
判断是否向dns服务商发起请求逻辑疑问！

### ISSUE THREAD

**Issue by Black-Gold** [jeessy2/ddns-go#1254]
### Description

当前判断逻辑是从IPcache比对IP并设置次数阈值。但此方式感觉不是很合理，是否可以简单一些，比对IPcache中IP与获取到的最新IP不匹配时再去调用dns服务商接口进行更新dns解析记录？即只有当IP真正变更时再去修改解析记录。这样每个月请求dns服务商接口10次左右，完全不会产生任何费用！

### Problem

当前逻辑在IP未实际变更时，仍然会调用dns服务商接口。go语言小白，理解如有问题，欢迎赐教！@jeessy2

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
可以设置的，参考首页说明

**Comment by Black-Gold** [comment]
> 可以设置的，参考首页说明

你说的是：-cacheTimes 间隔N次与服务商比对这个吧！但是我不理解与服务商比对有什么作用？只需要比对IPCache中是否与获取到的最新IP进行比对不就可以了吗？如果IPCache中和最新IP不一致，再去请求dns服务商接口进行更新解析即可！

**Comment by Black-Gold** [comment]
> 比如这哥们#1250

这哥们问题应该不是ddns-go的问题，我认为是他自己的问题！如果按照现有逻辑来处理，假如IP未实际变更的情况下，每隔一段时间仍会请求服务商接口。如果真的需要此功能，是否考虑增加一个类似开关功能，而不是用户自行设置cacheTimes？如果可以我愿意在大佬指导下，完成此功能！

**Comment by jeessy2** [comment]
这样就可以了，不用在实现什么功能

**Comment by Black-Gold** [comment]
但是这样的话，即使在IP未实际变更时，仍会请求dns服务商进行比对操作，对于一些厂商免费次数太少很容易就超了会导致产生费用！白嫖到底啊！哥们

**Comment by jeessy2** [comment]
默认30分钟一次，暂时没遇到有那些服务商限流。即使被限制了，可设置参数为9999

**Comment by Pointvar** [comment]
> 但是这样的话，即使在IP未实际变更时，仍会请求dns服务商进行比对操作，对于一些厂商免费次数太少很容易就超了会导致产生费用！白嫖到底啊！哥们

这个算是增强可用性，完全接管了dns解析。永远保持ddns-go和域名的关系，我也被搞晕过。不需要可以cacheTimes设置很大值。话说腾讯云api没有看到收费标准，需要收费吗？
