### ISSUE TITLE
是否可以执行多个服务商的不同callback？

### ISSUE THREAD

**Issue by guyqqcom** [jeessy2/ddns-go#1255]
### Description

单一服务商可能会有服务中断的情况，比如dynv6最近经常解释失败，是否可以同时执行多个不同服务商的callback保证多个服务商的不同域名解析服务可用？比如我在callback设置dynv6解析的同时另外设置ydns中的不同域名的解析。

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
右上角有个新增
