### ISSUE TITLE
windows版的开了允许公网访问，外网还是访问不了配置页面

### ISSUE THREAD

**Issue by z-wh** [jeessy2/ddns-go#1257]
### Description

windows版的开了允许公网访问，外网还是访问不了配置页面。反复开关了几次，开了访问、关了访问，外网都访问不了配置页面（用的默认端口9876）。用的IPV6动态域名访问，电脑上其他端口的服务都能访问并打开页面。

### DNS Provider

Callback

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Windows

### Architecture

x86_64

### Version

v6.7.0

### How are you running ddns-go?

Service

**Comment by jeessy2** [comment]
页面显示什么

**Comment by z-wh** [comment]
配置页面打不开，看不到页面

**Comment by z-wh** [comment]
> 页面显示什么

配置页面打不开，看不到页面

**Comment by jeessy2** [comment]
看一下监听端口没有，监听的v4还是v6,还是都监听了

**Comment by z-wh** [comment]
> 看一下监听端口没有，监听的v4还是v6,还是都监听了

到哪看监听端口啊？日志里没看到相关输出啊

**Comment by jeessy2** [comment]
重启ddns-go会输出
也可以用gpt搜一下怎么看监听

**Comment by z-wh** [comment]
> 重启ddns-go会输出 也可以用gpt搜一下怎么看监听

![image](https://github.com/user-attachments/assets/c3a1da6e-d16f-4ca3-a382-b7762ae652d4)
![image](https://github.com/user-attachments/assets/97032607-ca4e-48df-addd-13c2d3052ce3)
是这个吗？

**Comment by jeessy2** [comment]
看上去监听了的，windows防火墙放开了端口？

**Comment by z-wh** [comment]
> 看上去监听了的，windows防火墙放开了端口？

windows防火墙出站和入站规则 里，添加允许9876端口出站和入站，配置页面打开了。谢谢
