### ISSUE TITLE
XDG CONFIG DIR

### ISSUE THREAD

**Issue by xiagw** [jeessy2/ddns-go#1258]
### Description

https://wiki.archlinux.org/title/XDG_Base_Directory
现在一般都是在 $HOME/.config/ 目录下面放配置文件，
是否把默认配置文件放到  .config/ 下面？

### Problem

默认配置文件不太规范

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by xiagw** [comment]
这个倒是不会，
可以参考 aliyun-cli 或 kubectl 之类的，有个命令参数配置 或 环境变量 指定 配置文件路径
在程序内也可以做一个 if 判断，
优先查找 .config/
其次查找 $HOME/
就能做到兼容旧、新版

**Comment by jeessy2** [comment]
有些系统可能没有.config目录。目前正常使用，暂不考虑
