### ISSUE TITLE
webhook希望能增加多个

### ISSUE THREAD

**Issue by wuai1024** [jeessy2/ddns-go#1260]
### Description

通常当某一个特定域名的ip变动后，我需要通知多个webhook，希望能弄成可以动态添加多个的。目前我是自己写的一个中转服务，然后推送给我，再由我的中转服务，转发给多人，这个实现不是那么优雅和方便。

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
不支持。你这个需求可建一个群吧，推到群里？

**Comment by wuai1024** [comment]
目前是推送到  `bark` 里的。

因为有些有ip限制，变更了会通知相关的人。

**Comment by jeessy2** [comment]
想其它法吧。多个webhook不是很强的需求，大部分人用一个也够了，主要把项目也弄复杂了

**Comment by wuai1024** [comment]
嗯，那就还是走我的中间服务，去给多个人做转发了。
