### ISSUE TITLE
【问题请教】-请教如何让ddns-go将日志记录到一个指定的日志文件中

### ISSUE THREAD

**Issue by jiangxianxu** [jeessy2/ddns-go#1261]
### Description

请教如何让ddns-go将日志记录到一个指定的日志文件中

### Problem

1、在openwrt上使用的时候不想开web，因而用了-noweb参数，没有web后就无法通过web查看ddns-go的解析日志了，所以想通过日志文件能查看日志信息应该怎么传递参数？非常感谢！
2、在Linux发行版上使用的时候加了-noweb参数后，systemd可以接管ddns-go的打印可以看到日志，所以在linux发行版是没有这个问题。

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
不能指定，跟随系统的

**Comment by jiangxianxu** [comment]
> 不能指定，跟随系统的

好的，谢谢回复！ 后续会考虑增加这个功能吗？比如可以通过启动ddns-go的时候加上一个日志文件参数指定日志输出位置。如果有参数指定日志输出位置则按参数指定输出，如果没有参数指定则按照原来的方式不变这种。

**Comment by jeessy2** [comment]
搞复杂了，暂时不考虑
没人天天看日志，有变动可以使用webhook

**Comment by jiangxianxu** [comment]
> 搞复杂了，暂时不考虑 没人天天看日志，有变动可以使用webhook

好的，了解！
