### ISSUE TITLE
无法获取ipv6地址

### ISSUE THREAD

**Issue by zhanglilei1996** [jeessy2/ddns-go#1262]
### Description

log上显示Failed to get IPv6 address, will not update

### Problem

使用是的dns army的dns服务，callback选项，配置网页logs显示更新不了ipv6地址，导致公网访问不了

### Other Description

![123](https://github.com/user-attachments/assets/951641e3-8abf-466d-9cd7-be0e7a357389)

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
截图和你描述不一样
