### ISSUE TITLE
synology  NAS  ddnsgo页面登录密码忘记,怎么重置密码啊？ 

### ISSUE THREAD

**Issue by YUNNANZHOU** [jeessy2/ddns-go#1265]
### Description

synology  NAS  ddnsgo页面登录密码忘记,怎么重置密码啊？
![image](https://github.com/user-attachments/assets/bcf28c8b-8560-4274-b5d0-4655c901370d)
![image](https://github.com/user-attachments/assets/447fa067-2ac2-4dee-98b6-05597d30dc2f)

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
参考#1197
