### ISSUE TITLE
卸载不完全

### ISSUE THREAD

**Issue by Sheep2706** [jeessy2/ddns-go#1267]
### Description

大佬，为什么执行卸载。然后再重新安装，登陆页面的账号密码不是重新设置。我也把配置文件/.ddns_go_config.yaml删除了

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
卸载不会删除配置，手动删除

**Comment by Sheep2706** [comment]
可是我已经把/.ddns_go_config.yaml删除了，哪里还有配置文件。readme没写好像

**Comment by jeessy2** [comment]
默认当前用户目录下

**Comment by Sheep2706** [comment]
我弄好了，root用户的目录下不知道怎么也有一个配置文件。两个一起删了就好了
