### ISSUE TITLE
mac docker运行时，无法访问到web页面

### ISSUE THREAD

**Issue by mryee2023** [jeessy2/ddns-go#1268]
### Description

docker run

`docker run -d --name ddns-go --restart=always --net=host -v ${HOME}/ddns-go:/root jeessy/ddns-go -l :9877 -f 10 -cacheTimes 180`

日志输出：

![image](https://telegraph-pic.pages.dev/1728119939988.png)

但9877端口在宿主机中访问不到

~/ddns-go/ telnet localhost 9877

Trying 127.0.0.1...

telnet: connect to address 127.0.0.1: Connection refused

Trying ::1...

telnet: connect to address ::1: Connection refused

telnet: Unable to connect to remote host

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

macOS (Darwin)

### Architecture

arm64

### Version

latest

### How are you running ddns-go?

Docker

**Comment by jeessy2** [comment]
默认不改端口试下

**Comment by mryee2023** [comment]
![image](https://telegraph-pic.pages.dev/1728129898970.png)

还是有一样的问题


是不是跟我mac安装了docker的桌面版有关？

![image](https://telegraph-pic.pages.dev/1728130018907.png)

**Comment by jeessy2** [comment]
不用host模式

**Comment by mryee2023** [comment]
> 不用host模式

确实，不用host模式就OK了。

**Comment by Emtier** [comment]
mac直接部署服务不就行了 搞这么麻烦
