### ISSUE TITLE
使用webhook出现空白推送

### ISSUE THREAD

**Issue by Emtier** [jeessy2/ddns-go#1269]
### Description

我同时解析了v4和v6，但是平时通知只通知v4变动，但是通知我的时候v6也会发消息。导致有多条空白消息，希望增加开关选择推送v4/v6
![IMG_0221](https://github.com/user-attachments/assets/5ef8f20a-7d30-4482-bfd5-7e2781a82920)

### Did you search for similar issues before submitting this one?

No, I didn't

### Operating System

Linux

### Architecture

arm64

### Version

v6.7.0

### How are you running ddns-go?

Service

**Comment by jeessy2** [comment]
你没配置对吧，v4,v6分开的

**Comment by Emtier** [comment]
> 你没配置对吧，v4,v6分开的
我只写了ipv4 但是ipv6变动的时候会发送空白消息：
https://push/hCFD52/IP变动通知/IP已变动，新的IP：#{ipv4Addr}?icon=https://assets/static/img/server_icon.png

**Comment by jeessy2** [comment]
把v6也加上

**Comment by Emtier** [comment]
> 把v6也加上

v6太长了 平时也不用他啊，并且同时解析了别的设备的v6 我也看不出来v6是哪个设备的。

**Comment by jeessy2** [comment]
填写域名就知道了

**Comment by Emtier** [comment]
> 填写域名就知道了

行吧，不用这个功能了
