### ISSUE TITLE
Token没错，按模板填加，域名也对，怎么不行，老是403

### ISSUE THREAD

**Issue by xyxmos** [jeessy2/ddns-go#1273]
### Description

2024/10/09 11:51:42 查询域名信息发生异常! 返回内容: {"success":false,"errors":[{"code":9109,"message":"Cannot use the access token from location: 183.154.105.241"}],"messages":[],"result":null} ,返回状态码: 403

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
Cannot use the access token from location: 183.154.105.241

问服务商

**Comment by 35240** [comment]
我知道,如果是Cloudflare那么token要IPv6加IPv4地址
