### ISSUE TITLE
porkbun要改api地址未来能否有空更新一下

### ISSUE THREAD

**Issue by xxxsnn** [jeessy2/ddns-go#1274]
### Description

![image](https://github.com/user-attachments/assets/f3eaa248-f1f9-42a0-a609-0e24b7446d30)
今天收到porkbun要换api的邮件

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
可以来pr, 这个简单
