### ISSUE TITLE
callback里面能否增加ipv4和ipv6变量功能?

### ISSUE THREAD

**Issue by guhill1** [jeessy2/ddns-go#1276]
### Description

你好,callback里面能否增加ipv4和ipv6变量?有的网站要求同时提供ipv4和ipv6

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
什么服务商啊，没v6都不能用？

**Comment by guhill1** [comment]
大佬好,是dynu,他ipv4可以用,就是他一条语句要求把ipv4和ipv6都给上,不然光给ipv6的话他会把ipv4给刷成外网地址(被墙的结果),我看您这个有ipv6功能我很想用.

**Comment by jeessy2** [comment]
dynu支持的，右上角增加一个配置

**Comment by jeessy2** [comment]
https://github.com/jeessy2/ddns-go/wiki/Callback%E9%85%8D%E7%BD%AE%E5%8F%82%E8%80%83

**Comment by guhill1** [comment]
> https://github.com/jeessy2/ddns-go/wiki/Callback%E9%85%8D%E7%BD%AE%E5%8F%82%E8%80%83

回大佬,我照着以上步骤做了,还是不成功,ddnsgo日志显示没问题,实际ipv4解析是外网地址

服务商网站
https://www.dynu.com/
https://www.dynu.com/zh-CN/DynamicDNS/IP-Update-Protocol

日志:
![2024-10-12_135624](https://github.com/user-attachments/assets/2e7f1cb0-d2e2-4566-931e-4847aee7bc96)
实际服务商解析结果:
![2024-10-12_140144](https://github.com/user-attachments/assets/9a8175a5-7eb8-40c7-b210-2a5fb8d61d4e)
请大佬再关注一下

**Comment by jeessy2** [comment]
把你配置发来。
```
IP ADDRESS  Optional. IPv4 address to be used for update. This field is OPTIONAL. If IP addrss is not sent as part of the request, the API server will use the IP address from which the request originates. The special IP address 10.0.0.0 is replaced with the IP address from which the request originates and you may use it with routers which disallow empty IP address field. If you need to block the update of the IPv4 address, use myip=no as part of the update URL.

```

**Comment by jeessy2** [comment]
myip=no
myipv6=no

**Comment by jeessy2** [comment]
```
https://api.dynu.com/nic/update?username=jamesd&myip=no&myipv6=#{ip}&password=YOUR_TOKEN
```

**Comment by guhill1** [comment]
> IP ADDRESS  Optional

看懂了,我的错!谢谢大佬
