### ISSUE TITLE
Linux中Docker安装打开网页后，用户名和密码是什么？

### ISSUE THREAD

**Issue by dddjjjyyy222000000444** [jeessy2/ddns-go#1279]
### Description

Linux中Docker安装打开网页后，用户名和密码是什么？
![image](https://github.com/user-attachments/assets/0f60cffb-2119-4e31-9e4c-a095c5ebc4ac)

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Linux

### Architecture

i386

### Version

latest

### How are you running ddns-go?

Docker

**Comment by dddjjjyyy222000000444** [comment]
不知道哪一步做错了？也没看到文档中哪里能配置。

**Comment by jeessy2** [comment]
参考说明重置密码，首页docker栏

**Comment by dddjjjyyy222000000444** [comment]
> 参考说明重置密码，首页docker栏
这个吗？
![image](https://github.com/user-attachments/assets/45109932-9728-4167-95ee-38a6ca649531)

重置密码后，容器内的这个文件`/root/.ddns_go_config.yaml`中的用户名是空的，加上用户名可以了。

**Comment by jeessy2** [comment]
没设置账号密码？

**Comment by dddjjjyyy222000000444** [comment]
> 没设置账号密码？

不知道怎么回事儿，一打开页面就是登录，没看到哪里能配置。


重置密码生成文件后，直接修改的文件

![image](https://github.com/user-attachments/assets/df42b8b3-6140-4bbb-bd36-7a9ccc5f4a77)


![image](https://github.com/user-attachments/assets/65f16bf1-7613-4e97-9678-427a350d3b79)


![image](https://github.com/user-attachments/assets/884efca1-cba3-4739-a63c-ecde5884afdf)
