### ISSUE TITLE
正则表达式匹配错误

### ISSUE THREAD

**Issue by fengqiangs** [jeessy2/ddns-go#1281]
### Description

(?<![0-9A-Fa-f:])((?!(fe80|fc|fd|ff))[0-9A-Fa-f]{1,4}(?::[0-9A-Fa-f]{1,4}){7}|(?!(fe80|fc|fd|ff))(?:[0-9A-Fa-f]{1,4}:){1,7}:)(?![0-9A-Fa-f:])
我写了一份IPV6匹配规则， 但是从日志上看未正确匹配而默认使用第一个地址，请问是对格式有什么要求吗

### DNS Provider

阿里云

### Did you search for similar issues before submitting this one?

No, I didn't

### Operating System

Linux

### Architecture

i386

### Version

V6.7.1

### How are you running ddns-go?

Docker

**Comment by jeessy2** [comment]
用这个测 https://www.lddgo.net/string/golangregex

**Comment by TeemoZhang-ice** [comment]
> 用这个测 https://www.lddgo.net/string/golangregex

我想要排除固定ipv6，例如结尾是4466的ipv6
使用这个无法进行匹配，因为只支持[^...]，不支持负向断言^.*(?<!4466)$
