### ISSUE TITLE
可以增加 对 spaceship商家的解析吗

### ISSUE THREAD

**Issue by HDAES** [jeessy2/ddns-go#1282]
### Description

可以增加 对 spaceship商家的解析吗

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
可以把spaceship改到已有的服务商，服务商太多，支持不过来

**Comment by HDAES** [comment]
意思是 转出域名到 已有服务商吗

**Comment by jeessy2** [comment]
不是。改nameserver到已有的服务商

**Comment by HDAES** [comment]
额，有没有参考的文章之类的。小白 不太懂

**Comment by jeessy2** [comment]
网上搜下吧，很简单

**Comment by shen-lan** [comment]
@HDAES  把域名转入到其他的域名服务商
