### ISSUE TITLE
日志时间显示慢8小时怎么解决

### ISSUE THREAD

**Issue by Elysia51** [jeessy2/ddns-go#1283]
### Description

我路由器的时间是东8时区的时间，但是路由器上安装的ddng-go日志时间就是utc，导致解析失败，请问怎么结局

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Linux

### Architecture

armv7

### Version

v6.7.0

### How are you running ddns-go?

Service

**Comment by jeessy2** [comment]
设置你路由器时区？

**Comment by Elysia51** [comment]
红米路由器，时区是对的，时间也是对的，登录ssh安装ddns-go后，设置好后日志时间就是慢了8个小时，

**Comment by jeessy2** [comment]
什么系统

**Comment by pvzgh** [comment]
> 红米路由器，时区是对的，时间也是对的，登录ssh安装ddns-go后，设置好后日志时间就是慢了8个小时，

如果是openwrt系统，在软件包安装`zoneinfo-asia`可以解决

**Comment by pvzgh** [comment]
> 红米路由器，时区是对的，时间也是对的，登录ssh安装ddns-go后，设置好后日志时间就是慢了8个小时，

如果是openwrt系统，在软件包安装`zoneinfo-asia`可以解决。

也可以参照这个操作https://github.com/jeessy2/ddns-go/issues/328#issuecomment-1646517329

**Comment by pvzgh** [comment]
> 红米路由器，时区是对的，时间也是对的，登录ssh安装ddns-go后，设置好后日志时间就是慢了8个小时，

如果是openwrt系统，在软件包安装zoneinfo-asia就可以解决。

也可以参考这个操作https://github.com/jeessy2/ddns-go/issues/328#issuecomment-1646517329

**Comment by lpcheng1208** [comment]
> 什么系统

应该是 路由器 打开的SSH, 应该是基于OpenWrt 定制的，我这边开了ssh 装 ddns-go 确实也是有这个问题，路由器的资源相对比较小，可能时区包也安装不了，所以上次的pr 我觉得加入tZ 参数是可行的，就不限制是 安卓才走那个代码，不传tZ参数就用系统默认的

**Comment by jeessy2** [comment]
> > 什么系统
> 
> 
> 
> 应该是 路由器 打开的SSH, 应该是基于OpenWrt 定制的，我这边开了ssh 装 ddns-go 确实也是有这个问题，路由器的资源相对比较小，可能时区包也安装不了，所以上次的pr 我觉得加入tZ 参数是可行的，就不限制是 安卓才走那个代码，不传tZ参数就用系统默认的

能安装包解决就安装包，先不考虑传参

**Comment by Elysia51** [comment]
![Screenshot_2024-11-08-08-00-50-504_com android browser-edit](https://github.com/user-attachments/assets/8e1f4bda-d3f8-4968-968c-0c166eabf106)
![Screenshot_2024-11-08-08-02-27-091_com sonelli juicessh-edit](https://github.com/user-attachments/assets/0a06959c-ff9f-4535-85e8-8e5641a909cb)
是红米路由器自带的系统，登录ssh显示的时间是正确的，登录到ddns-go面板上时间就不正确了

**Comment by Elysia51** [comment]
> > > > 什么系统
> > > 
> > > 
> > > 应该是 路由器 打开的SSH, 应该是基于OpenWrt 定制的，我这边开了ssh 装 ddns-go 确实也是有这个问题，路由器的资源相对比较小，可能时区包也安装不了，所以上次的pr 我觉得加入tZ 参数是可行的，就不限制是 安卓才走那个代码，不传tZ参数就用系统默认的
> > 
> > 
> > 能安装包解决就安装包，先不考虑传参
> 
> 装时区包，重启路由器可以解决



> > > > 什么系统
> > > 
> > > 
> > > 应该是 路由器 打开的SSH, 应该是基于OpenWrt 定制的，我这边开了ssh 装 ddns-go 确实也是有这个问题，路由器的资源相对比较小，可能时区包也安装不了，所以上次的pr 我觉得加入tZ 参数是可行的，就不限制是 安卓才走那个代码，不传tZ参数就用系统默认的
> > 
> > 
> > 能安装包解决就安装包，先不考虑传参
> 
> 装时区包，重启路由器可以解决

![Screenshot_2024-11-08-08-00-50-504_com android browser-edit](https://github.com/user-attachments/assets/0b1514bb-8ea7-4130-988d-c94a37eb2658)
![Screenshot_2024-11-08-08-02-27-091_com sonelli juicessh-edit](https://github.com/user-attachments/assets/dc9b6747-2471-4e4a-bdac-05f235c4fc35)
系统是红米路由器自带的系统，登录ssh后时间显示是对的，登录面板后的时间就是错的
