### ISSUE TITLE
有没有办法可以禁用账号密码登录呀docker容器板的

### ISSUE THREAD

**Issue by Rui-xing** [jeessy2/ddns-go#1285]
### Description

有没有办法可以禁用账号密码登录呀docker容器板的

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
docker不暴露端口就可以了

**Comment by Rui-xing** [comment]
> docker不暴露端口就可以了

使用host模式吗？

**Comment by jeessy2** [comment]
docker命令最后加参数-noweb

**Comment by jeessy2** [comment]
必须登录，除非自己改个版本

**Comment by jeessy2** [comment]
op系统也要登录

**Comment by Rui-xing** [comment]
> op系统也要登录
啊？可是我这个没有登录的呀

**Comment by jeessy2** [comment]
这个版本太老了。最近的都必须登录

**Comment by Rui-xing** [comment]
> 这个版本太老了。最近的都必须登录

emmm，能不能给个老版本的版本号呀

**Comment by jeessy2** [comment]
自己看
