### ISSUE TITLE
2024/10/23 18:45:02 Callback调用失败, 异常信息: Get "https://dynv6.com/api/update?zone=xia.my&token=g_LrznFTeT9Y&ipv6=240e:********": proxyconnect tcp: dial tcp 127.0.0.1:10808: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by sakura-hahaha** [jeessy2/ddns-go#1287]
### Description

在使用ddns-go时它为什么要去端口10808，是不是我第一次安装ddns-go时开了v2rayng造成的？我现在win不开v2rayng就会报错2024/10/23 18:45:02 Callback调用失败, 异常信息: Get "https://dynv6.com/api/update?zone=xia.my&token=g_LrznFTeT9Y&ipv6=240e:********": proxyconnect tcp: dial tcp 127.0.0.1:10808: connectex: No connection could be made because the target machine actively refused it.

我启动v2rayng软件ddns-go就解析地址成功，即使我v2rayng并没有启动系统代理，只是v2rayng软件开始监听10808端口了。

请问我该怎么解决这个问题，我能让ddns-go不使用10808代理吗？我不想我每次使用ddns-go还要同时使用v2rayng。

我已经卸载ddns-go，然后关闭v2rayng，然后关机，然后开机，然后在未启动v2rayng的情况下安装ddns-go，结果还是报错2024/10/23 18:45:02 Callback调用失败, 异常信息: Get "https://dynv6.com/api/update?zone=xia.my&token=g_LrznFTeT9Y&ipv6=240e:********": proxyconnect tcp: dial tcp 127.0.0.1:10808: connectex: No connection could be made because the target machine actively refused it.

### DNS Provider

Callback

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Windows

### Architecture

x86_64

### Version

v6.7.2

### How are you running ddns-go?

Service

**Comment by jeessy2** [comment]
默认跟随系统环境变量
