### ISSUE TITLE
取消身份验证

### ISSUE THREAD

**Issue by l3126596029** [jeessy2/ddns-go#1288]
### Description

请问能否取消取消该应用本身的验证(账密), 我想使用nginx那边反向代理配置专门的身份验证界面来访问此应用, 避免重复输入账密的情况, 查询项目文档并未提到相关问题, 或者是否有通过URI传参直接能避免此情况的方式?

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
必须要账号密码，不是人人都用nginx，nginx 不设置验证就可以了。

**Comment by jeessy2** [comment]
URI传参就取消账号密码，这个就成漏洞了

**Comment by l3126596029** [comment]
是的, 不是所有人都使用nginx, 所以请问能否评估一下后续增加一个环境变量, 来让用户自行决定是否需要使用应用本身的身份验证, 谢谢
如-e Auth=true (default)

**Comment by jeessy2** [comment]
有通过命令获取，不可能加这个参数。要实现只有自己fork

**Comment by l3126596029** [comment]
好的，明白了，谢谢
