### ISSUE TITLE
重置密码后，用新的密码依旧无法登录；

### ISSUE THREAD

**Issue by love90618** [jeessy2/ddns-go#1289]
### Description

OpenWrt 23.05.0  
软件：sirpdboy/luci-app-ddns-go
使用ddns-go -resetPassword 重置密码后 无法登录
重置路由也无效

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
有可能是重置默认使用当前用户目录的配置， 插件的目录不在用户目录。需要指定配置文件目录一起使用

**Comment by love90618** [comment]
> 有可能是重置默认使用当前用户目录的配置， 插件的目录不在用户目录。需要指定配置文件目录一起使用

确认用命令重启了，甚至重启了路由器；
而且也在root目录下生成了新的.ddns_go_config.yaml文件

**Comment by jeessy2** [comment]
默认的不对，需要指定。实际应该在/etc/ddns-go下，你去看下

**Comment by love90618** [comment]
> 默认的不对，需要指定。实际应该在/etc/ddns-go下，你去看下

非常感谢，我删除配置文件重置了程序，好在只一个域名；
