### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by Jiale798** [jeessy2/ddns-go#1297]
### Description

![2024-10-28_173954](https://github.com/user-attachments/assets/2c7b0e0e-05b1-473e-a1bd-5c752b9ed7f0)

### Did you search for similar issues before submitting this one?

No, I didn't

### Operating System

Linux

### Architecture

i386

### Version

v6.7.3

### How are you running ddns-go?

Docker

**Comment by Jiale798** [comment]
help

**Comment by jeessy2** [comment]
用管理员打开cmd

**Comment by Jiale798** [comment]
thanks
