### ISSUE TITLE
注销登录的功能

### ISSUE THREAD

**Issue by sinkink** [jeessy2/ddns-go#1299]
### Description

登录后没有看到注销登录的选项，这有点影响安全性。希望可以加上注销的按钮

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
可以PR

**Comment by sinkink** [comment]
> 可以PR

请问PR是指？

**Comment by jeessy2** [comment]
贡献代码

**Comment by sinkink** [comment]
> 贡献代码

大佬，我不会写呀
![015AE452](https://github.com/user-attachments/assets/106264ab-171b-4bbd-bf0d-d11c15683a86)

**Comment by jeessy2** [comment]
那你就等待吧。。

**Comment by sinkink** [comment]
> 那你就等待吧。。

好的，谢谢大佬

**Comment by jeessy2** [comment]
try 6.7.4
