### ISSUE TITLE
不能打开：open /tmpstatic_pages_writing.html: no such file or directory

### ISSUE THREAD

**Issue by 378978764** [jeessy2/ddns-go#13]
运行后的日志如下：

```
$ ./ddns-go 
2020/11/28 21:34:46 没有找到配置文件！请在网页中输入
2020/11/28 21:34:46 监听 :9876 ...
自动打开浏览器失败, 请手动打开。错误信息: exec: "xdg-open": executable file not found in $PATHError happened..
# 尝试访问后，提示：
open /tmpstatic_pages_writing.html: no such file or directory
```

**Comment by 378978764** [comment]
安装上面那个命令后，问题仍然存在，日志变成：
```
]$ ./ddns-go 
2020/11/28 21:38:42 没有找到配置文件！请在网页中输入
2020/11/28 21:38:42 监听 :9876 ...
成功打开浏览器
Error happened..
open /tmpstatic_pages_writing.html: no such file or directory
```

**Comment by 378978764** [comment]
服务器上没有桌面环境，通过ssh访问的。

**Comment by jeessy2** [comment]
Docker中运行的？如果是，不用管这个错。docker中没有环境打开。直接浏览器中打开dockerIP:9876

**Comment by 378978764** [comment]
> Docker中运行的？如果是，不用管这个错。docker中没有环境打开。直接浏览器中打开dockerIP:9876

不是的，是直接在腾讯云的centos上运行的，直接访问的ip:9876，浏览器能出来图标，但是没有显示，然后命令行出现这个错误。

**Comment by 378978764** [comment]
最新更新：使用root权限运行后正常了，这个必须要使用root权限吗？网页的静态文件是否可以在当前目录下dump呢？

**Comment by 378978764** [comment]
> 最新更新：使用root权限运行后正常了，这个必须要使用root权限吗？网页的静态文件是否可以在当前目录下dump呢？

对于一些公司的服务器，个人是没有root权限的

**Comment by jeessy2** [comment]
静态文件打包在程序中，下来分析一下

**Comment by 378978764** [comment]
> 静态文件打包在程序中，下来分析一下

下来分析一下是指？

**Comment by jeessy2** [comment]
非管理员权限不能运行问题

**Comment by jeessy2** [comment]
感谢反馈。已在v1.4.2中修复。https://github.com/jeessy2/ddns-go/releases/tag/v1.4.2

**Comment by 378978764** [comment]
> 感谢反馈。已在v1.4.2中修复。https://github.com/jeessy2/ddns-go/releases/tag/v1.4.2

神速！从提出到解决不到两小时~
