### ISSUE TITLE
阿里云解析突然就不能用了，错误码400

### ISSUE THREAD

**Issue by chuyinluotian01** [jeessy2/ddns-go#1307]
### Description

昨天还好好的，重新安装了最新版也不行
![Screenshot_2024-11-02-21-53-59-870_com microsoft emmx-edit](https://github.com/user-attachments/assets/0e5e4b80-65eb-49fa-979c-a2bfc0d23cea)
![Screenshot_2024-11-02-21-55-51-721_com microsoft emmx](https://github.com/user-attachments/assets/3bcdaefe-974f-4744-bad3-d2ee8acc40ed)

### Did you search for similar issues before submitting this one?

No, I didn't

### Operating System

Linux

### Architecture

x86_64

### Version

最新docker版

### How are you running ddns-go?

Docker

**Comment by jeessy2** [comment]
重新生成一个key

**Comment by colaKot** [comment]
重新生成了一个 key 也还是不行. 大哥你解决了吗?

**Comment by chuyinluotian01** [comment]
> 重新生成了一个 key 也还是不行.大哥你解决了吗?

我解决了 😁
