### ISSUE TITLE
添加反向记录PTR的ddns功能

### ISSUE THREAD

**Issue by KelaLeaf** [jeessy2/ddns-go#1309]
### Description

自动根据当前ipv4或ipv6添加相应的PTR记录。

### Problem

目前使用个人自建邮箱，家庭网络为动态IP，我尝试过使用frp等反代软件将邮件服务器映射到我购买的公网服务器，但发件IP地址依旧为家庭自建服务器IP，并不会使用我购买的公网服务器IP发件。IP无法固定下来那么PTR记录也需要随时修改。

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
超出范畴了，fork自行开发了

**Comment by KelaLeaf** [comment]
> 超出范畴了，fork自行开发了

好吧，感谢
