### ISSUE TITLE
Win10 开机自动启动和常驻后台

### ISSUE THREAD

**Issue by GTLeoLee123** [jeessy2/ddns-go#131]
请问：Win10 开机自动启动和常驻后台 应该如何设置？

**Comment by jeessy2** [comment]
参考首页文档
- [可选] 安装服务
  - Mac/Linux: `./ddns-go -s install` 
  - Win(管理员打开cmd): `.\ddns-go.exe -s install`
  - 安装服务也支持 `-l`监听地址 `-f`同步间隔时间(秒) `-c`自定义配置文件路径
