### ISSUE TITLE
能否将DNS服务商的ID跟KEY跟账户密码一样都加密

### ISSUE THREAD

**Issue by avw95** [jeessy2/ddns-go#1310]
### Description

能否将DNS服务商的ID跟KEY跟账户密码一样都加密，不要打开配置文件直接是明文

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
密码是非对称加密，不可解密。而Key只能对称加密，可以解密，对于一个开源项目感觉没有必要再对Key加密，只要看到配置就能知道Key
