### ISSUE TITLE
[BUG]容器化部署的服务无法正常获取到IPV6

### ISSUE THREAD

**Issue by carolcoral** [jeessy2/ddns-go#1311]
### Description

使用docker compose方式部署的ddns-go，通过调用接口方式去获取ipv6地址一直提示无法获取，手动在浏览器中访问地址发现可以正常返回v6地址

<img width="851" alt="image" src="https://github.com/user-attachments/assets/791c488c-1375-4b63-b7ac-1218c248502c">
<img width="771" alt="image" src="https://github.com/user-attachments/assets/44b22251-d71e-4bc6-a324-659d08d8d4ce">

<img width="294" alt="image" src="https://github.com/user-attachments/assets/1acddc48-e376-47f2-b19c-44f626a5a1ce">

### DNS Provider

阿里云

### Did you search for similar issues before submitting this one?

Yes, I did, but I didn't find anything useful

### Operating System

Linux

### Architecture

arm64

### Version

v6.7.5

### How are you running ddns-go?

Docker

**Comment by jeessy2** [comment]
是不是host模式

**Comment by carolcoral** [comment]
> 是不是host模式

桥接模式，容器部署我都不用host的

**Comment by jeessy2** [comment]
> > 是不是host模式
> 
> 桥接模式，容器部署我都不用host的

看下文档，容器中使用ipv6需要host模式。

**Comment by carolcoral** [comment]
> > > 是不是host模式
> > 
> > 
> > 桥接模式，容器部署我都不用host的
> 
> 看下文档，容器中使用ipv6需要host模式。

ok

**Comment by carolcoral** [comment]
docker compose怎么配置可以映射本地网卡到容器里面呢，这样就不用开host了

**Comment by jeessy2** [comment]
> docker compose怎么配置可以映射本地网卡到容器里面呢，这样就不用开host了

这些不熟悉，你可以自己研究下，我都是简单化处理
