### ISSUE TITLE
关于是否将 100.64.0.0/10 用于私有地址

### ISSUE THREAD

**Issue by soxft** [jeessy2/ddns-go#1318]
### Description

100.64.0.0/10 虽不属于 ABC类私有地址，但也在部分场景被用作私网地址，如 tailscale 分配的组网设备IP
100.64.0.0/10 并未在公网上路由，在部分场景下也用于内部通信

目前在 https://github.com/jeessy2/ddns-go/blob/52f0e67a4e3391b7c02060492d07414ed62b881c/util/net.go#L25-L28
https://github.com/jeessy2/ddns-go/blob/52f0e67a4e3391b7c02060492d07414ed62b881c/util/net_test.go#L21

似乎将 100.64.0.0/10 判断为 非内网地址

### Problem

在 tailscale 下，通过 该网段无法访问，httpcode 403

### Other Description

也许是否可以考虑提供一个配置文件，供用户设置允许或禁止的ip段

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
同 #1256 
增加一个配置，感觉更加复杂了。
Tailscale 支持Subnet，这个更加方便，就可以通过你实际的内网ip访问

**Comment by soxft** [comment]
> 同 #1256 增加一个配置，感觉更加复杂了。 Tailscale 支持Subnet，这个更加方便，就可以通过你实际的内网ip访问

感谢回复，我研究一下 subnet 配置
