### ISSUE TITLE
希望增加一些功能

### ISSUE THREAD

**Issue by ElvenP** [jeessy2/ddns-go#132]
比如商品  时间这些能在web页面修改
删除了域名后在后台上自动删除记录。

**Comment by jeessy2** [comment]
商品/时间 这些是什么？

**Comment by ElvenP** [comment]
打错了。应该是端口和自动刷新ip时间
2021年11月2日 +0800 15:20 jeessy2 ***@***.***>，写道：

**Comment by jeessy2** [comment]
端口在页面不好修改
有些可以考虑，后面有空考虑。欢迎PR
