### ISSUE TITLE
能否增加可选网卡后使用接口获取IP地址？

### ISSUE THREAD

**Issue by albertnjcn** [jeessy2/ddns-go#1320]
### Description

我主机有多张网卡，分别接了2个路由器上网。希望仅获取其中一个网卡连接的路由器的外网IP地址。非常感谢！

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
不是有？
