### ISSUE TITLE
mac版本忘记密码

### ISSUE THREAD

**Issue by zymshirley** [jeessy2/ddns-go#1323]
### Description

mac版本忘记密码怎么重置呀

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by zymshirley** [comment]
输入./ddns-go -resetPassword 123456提示./ddns-go: No such file or directory。不是docker安装，不好找配置文件在哪

**Comment by jeessy2** [comment]
ddns-go下载解压目录
