### ISSUE TITLE
Forbidden Rejected request from RFC1918 IP to public server address

### ISSUE THREAD

**Issue by qichengyu3** [jeessy2/ddns-go#1326]
### Description

Forbidden
Rejected request from RFC1918 IP to public server address

配置好ddns后台，打开网站显示Forbidden
Rejected request from RFC1918 IP to public server address

### DNS Provider

腾讯云

### Did you search for similar issues before submitting this one?

No, I didn't

### Operating System

Linux

### Architecture

i386

### Version

最新

### How are you running ddns-go?

Docker

### Any other information

Forbidden
Rejected request from RFC1918 IP to public server address

**Comment by jeessy2** [comment]
用内网IP打开或开启公网访问
