### ISSUE TITLE
增加时间变量、日志自定义路径

### ISSUE THREAD

**Issue by skoy03** [jeessy2/ddns-go#1329]
### Description

可否增加时间变量用于记录IP更新时间，同时可否增加日志记录的自定义路径。有时webhook访问失败时可以从日志文件中查找

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
感觉没必要，有webhook通知后基本没人会去看日志，webhook失效我没遇到过

**Comment by shen-lan** [comment]
请问有持久化的日志吗    我看界面那里好像都是临时的 清了就没了。几天后想去排查之前解析失败的日志，都找不到原因
