### ISSUE TITLE
无法重置程序

### ISSUE THREAD

**Issue by XmLinkia** [jeessy2/ddns-go#133]
在我删除程序保存的配置文件并卸载服务后打开程序仍在获取IP地址，无法重置应用。是除了在systemprofiles文件下还有其他配置文件需要删除吗？

**Comment by XmLinkia** [comment]
是除了在system profile s文件下还有其他配置文件需要删除吗？

**Comment by jeessy2** [comment]
打开程序也要运行的，打开程序的配置文件在用户目录下

**Comment by XmLinkia** [comment]
好的！找到了，谢谢作者解答！
