### ISSUE TITLE
新增DNSLA的解析支持

### ISSUE THREAD

**Issue by xjh2009** [jeessy2/ddns-go#1330]
### Description

这个是API文档 https://www.dns.la/docs/ApiDoc

Callback用不了Basic令牌也不支持PUT

### Other Description

我算是不会写go项目 想PR也PR不了

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
服务商太多，建议转dns server到支持的
