### ISSUE TITLE
通过接口获取IPv4失败! 接口地址: https://myip.ipip.net 

### ISSUE THREAD

**Issue by MrLi1982** [jeessy2/ddns-go#1337]
### Description

好久没用，忽然发现域名不能登陆，查看日志发现，报：通过接口获取IPv4失败! 请大佬们帮助小白，感谢各位大佬！！
2024/12/11 14:15:08 通过接口获取IPv4失败! 接口地址: https://myip.ipip.net
2024/12/11 14:15:08 异常信息: Get "https://myip.ipip.net": read tcp4 *.*.*.*:49756->*.*.*.*:443: read: connection reset by peer
![1733898386846](https://github.com/user-attachments/assets/a327cb54-0207-436d-8fc1-64bb3989cca3)

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by MrLi1982** [comment]
> 解析正常的。只是my.ipip.net接口异常，还有其他接口获取了正常的v4地址

那我是把这个地址删了吗？

**Comment by jeessy2** [comment]
可以，也可以重新添加稳定的接口地址

**Comment by MrLi1982** [comment]
> 可以，也可以重新添加稳定的接口地址

我是个小白，您能给我几个稳定的接口吗？万分感谢

**Comment by MrLi1982** [comment]
> 可以，也可以重新添加稳定的接口地址

我是个小白，您能给我几个稳定的接口吗？万分感谢，这个软件以前别人给我弄的，弄好了我就没有在动过，这段时间域名用不了了，才查看的！！

**Comment by jeessy2** [comment]
就默认那几个

**Comment by MrLi1982** [comment]
> 就默认那几个

https://myip.ipip.net, https://ddns.oray.com/checkip, https://ip.3322.net, https://4.ipw.cn, https://v4.yinghualuo.cn/bejson
以上这几个
