### ISSUE TITLE
如何修改同步时间

### ISSUE THREAD

**Issue by Today-to-Lsp** [jeessy2/ddns-go#134]
如题：如何修改同步时间，同步时间默认是5分钟

**Comment by jeessy2** [comment]
文档中写了。加-f就是，单位秒
./ddns-go -l 127.0.0.1:9876 -f 600 -c /Users/name/ddns-go.yaml

**Comment by Today-to-Lsp** [comment]
不好意思，我表达的可能有点问题，是docker-compose.yml里面怎么填写同步时间
version: "3.0"
services:
  ddns:
    image: jeessy/ddns-go
    container_name: ddns-go
    restart: always
    ports:
      - "9876:9876"
    volumes:
      - ./:/root

**Comment by jeessy2** [comment]
个人觉得没必要用docker-compose，项目非常简单的，直接用docker就可以了

**Comment by Today-to-Lsp** [comment]
> 个人觉得没必要用docker-compose，项目非常简单的，直接用docker就可以了

因为这样会比较方便备份文件后，方便服务器的迁移，能教教吗

**Comment by jeessy2** [comment]
这个我也没操作过。可以参考官方文档
`command: ["./wait-for-postgres.sh", "db", "python", "app.py"]`
https://docs.docker.com/compose/startup-order/

**Comment by walkxspace** [comment]
用 [这个工具](https://www.composerize.com/) 去生成配置文件试试？
