### ISSUE TITLE
Can add HE tunnel IPv4 endpoint update?

### ISSUE THREAD

**Issue by Handsome1080P** [jeessy2/ddns-go#1342]
### Description

Can add HE tunnel IPv4 endpoint update?I am using scripts,but if add this in ddns-go,that is will be appreciated.

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
u can try `callback`
