### ISSUE TITLE
webhook中获取IPV6地址无效

### ISSUE THREAD

**Issue by btwise** [jeessy2/ddns-go#1343]
### Description

DNS-GO工作正常，DNS解析也正常，可以正确获取到IPV6地址，但是我使用webhook推送功能里获取到的IPV6地址显示为::1，换其他API推送都是如此，这是哪里不对，如何处理

### DNS Provider

Cloudflare

### Did you search for similar issues before submitting this one?

No, I didn't

### Operating System

Linux

### Architecture

x86_64

### Version

v6.x

### How are you running ddns-go?

Service

### Any other information

DNS-GO工作正常，DNS解析也正常，可以正确获取到IPV6地址，但是我使用webhook推送功能里获取到的IPV6地址显示为::1，换其他API推送都是如此，这是哪里不对，如何处理

**Comment by jeessy2** [comment]
点击按钮是模拟数据，只是测试通不通

**Comment by btwise** [comment]
> 点击按钮是模拟数据，只是测试通不通

哦，明白了，因为IP一直没有更新，所以并没有发送真正的地址
