### ISSUE TITLE
大佬请问下docker下的问题

### ISSUE THREAD

**Issue by xiaokao2008** [jeessy2/ddns-go#135]
大佬请问一个问题，在DOcker下利用ipv6 DDNS，在外面，手机的网络可以正常访问NAS，但是利用WIFI去不能链接设备！

在局域网又能利用域名访问，，，我是在群晖DOCKEr下运行的，感谢大佬！

**Comment by jeessy2** [comment]
Wi-Fi不能访问，局域网可以？检测下各个地方获取到ipv6没有
