### ISSUE TITLE
是否有办法在一个ddns-go程序中，按照规则管理多个域名?

### ISSUE THREAD

**Issue by nu1lkali** [jeessy2/ddns-go#1351]
### Description

比如a域名获取当前程序的ipv6地址
b域名根据命令获取局域网另一个设备的ipv6地址
因为我局域网另一个设备内存太小了 没法跑ddns-go

### Problem

比如a域名获取当前程序的ipv6地址
b域名根据命令获取局域网另一个设备的ipv6地址
因为我局域网另一个设备内存太小了 没法跑ddns-go

### Checklist

- [X] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [X] I have searched for similar feature requests before submitting this one

**Comment by jeessy2** [comment]
https://github.com/jeessy2/ddns-go/wiki/%E9%80%9A%E8%BF%87%E5%91%BD%E4%BB%A4%E8%8E%B7%E5%8F%96IP%E5%8F%82%E8%80%83

**Comment by jeessy2** [comment]
不用，右上角新增一个配置

**Comment by nu1lkali** [comment]
多个配置可同时生效?

**Comment by jeessy2** [comment]
问一百次不如试一次

**Comment by nu1lkali** [comment]
非常感谢。是否有办法根据mac地址获取其他设备的外网ipv6地址?
