### ISSUE TITLE
能否增加 IPv6 失效提醒

### ISSUE THREAD

**Issue by walkxspace** [jeessy2/ddns-go#136]
由于我这边运营商的 IPv6 地址的有效期只有 3 天，3 天之后 NAS 上的 IPv6 地址还在但无法从公网访问，而光猫没有定时自动重启功能，能否在 DDNS-GO 连续多次访问接口获取不到 IPv6 地址后通过 Webhook 发送 IPv6 失效通知来提醒手动重启光猫。
![](https://i.loli.net/2021/11/14/MBZJrdaQyetNLOv.png)
![](https://i.loli.net/2021/11/14/o4fKpC8NLJElsUQ.png)

**Comment by jeessy2** [comment]
应该可以

**Comment by jeessy2** [comment]
fix: https://github.com/jeessy2/ddns-go/releases/tag/v3.2.1
刚好在第三次时触发一次Webhook
