### ISSUE TITLE
啊这，两个项目如果可以合体想想就美滋滋

### ISSUE THREAD

**Issue by SoraKasvgano** [jeessy2/ddns-go#14]
https://github.com/NewFuture/DDNS
https://github.com/jeessy2/ddns-go

**Comment by jeessy2** [comment]
一个用户python写的，一个go写的。如需要啥功能，欢迎提PR

**Comment by samondlee** [comment]
> 一个用python写的，一个go写的。如需要啥功能，欢迎提PR

啊这，暂时没有，就是感觉那个项目的 IP获取方式 判断方法 多种多样 可以吸取一下。。。

**Comment by jeessy2** [comment]
v2.0.0增加通过网卡获取ip

**Comment by Cihivip** [comment]
测试下来对于.com.cn这样的域名还是不支持, 比如现在解析www.abc.com是没问题的, 但www.abc.com.cn根本无法解析

**Comment by Cihivip** [comment]
2020/12/24 09:12:47 新增域名解析 ddns.abc.com.cn 失败！Code: 8, Message: 域名不正确，请输入主域名，如 dnspod.cn
测试下来对于.com.cn这样的域名还是不支持, 比如现在解析www.abc.com是没问题的, 但www.abc.com.cn无法解析

**Comment by jeessy2** [comment]
> 2020/12/24 09:12:47 新增域名解析 ddns.abc.com.cn 失败！Code: 8, Message: 域名不正确，请输入主域名，如 dnspod.cn
> 测试下来对于.com.cn这样的域名还是不支持, 比如现在解析www.abc.com是没问题的, 但www.abc.com.cn无法解析

对，`com.cn`做为了请域名了，后续修改

**Comment by jeessy2** [comment]
> 2020/12/24 09:12:47 新增域名解析 ddns.abc.com.cn 失败！Code: 8, Message: 域名不正确，请输入主域名，如 dnspod.cn
> 测试下来对于.com.cn这样的域名还是不支持, 比如现在解析www.abc.com是没问题的, 但www.abc.com.cn无法解析

v2.0.1修复了。
