### ISSUE TITLE
大佬，请教个获取ipv6的问题

### ISSUE THREAD

**Issue by yangchris4** [jeessy2/ddns-go#142]
环境是
1.lean固件的软路由+荣耀路由做AP，并且NAS 是插在AP路由器上的
2.ddns-go 是在NAS上用的docker

情况是
1.软路由没有开启科学上网，此时NAS可以获取到ipv6地址，并且docker里的ddns-go 也能检测到ipv6地址；
2.开启科学上网后（ssr plus+插件，已取消勾选wan6接口)，此时NAS可以获取到ipv6地址(自带的ddns可以使用），但是docker 里的ddns-go 提示获取不到Ipv6地址。
![微信截图_20211126220355](https://user-images.githubusercontent.com/13220804/143592862-08204c41-5a74-4392-86b9-9256a07300b2.png)

请问这是肿么肥事啊

**Comment by jeessy2** [comment]
自行判断了吧，没有你这个环境，这个我也说不清
