### ISSUE TITLE
通过网卡获取IPV6里面只有一个临时的IPV6地址？

### ISSUE THREAD

**Issue by nczyw** [jeessy2/ddns-go#143]
通过网卡获取IPV6里面只有一个临时的IPV6地址？我看说明写的获取第一个IPV6，我自己用QT写了获取ipv6地址，发现第1个，经常是内网IPV6和临时的IPV6，不知道大佬能不能想办法不要获取到临时的IPV6呢

**Comment by jeessy2** [comment]
默认获取的第一个，每个系统第一个ipv6规则可能都不同。不好区分，欢迎提供建议

**Comment by nczyw** [comment]
> 默认获取的第一个，每个系统第一个ipv6规则可能都不同。不好区分，欢迎提供建议

我也在尝试怎么能不获取到临时的，其实还有个问题，获取同一个地方的IPV6，如果电脑没有重启网卡，路由器重启了，这时，微软IPV6里面还有一个已经过期的IPV6，就是路由上一次拨号分下来的前缀，获取到这个才是最为致命的，永远都不会再正确了。明明微软的网卡显示里面，能完全正确的显示IPV6，过期的，临时的，非临时的。为什么在我们调用微软的API后，就不再区分呢？目前我也还没有找到一种方式可以正确处理这个问题。

**Comment by jeessy2** [comment]
第二个问题通过接口获取比较合适

**Comment by nczyw** [comment]
> 第二个问题通过接口获取比较合适

不太明白，你说的通过接口，我选了通过接口，要我填一个ipv6的域名,域名会添加到127.0.0.1:9876/后面。这个方法我是不是用的不对啊。大佬

**Comment by jeessy2** [comment]
不会吧。你杂操作的

**Comment by nczyw** [comment]
> 不会吧。你杂操作的

IPV6
 获取IP方式 ：选择通过接口获取,下面是操作说明，里面我填域名或者留空
填写的URL需返回公网IPv6地址。如：https://api-ipv6.ip.sb/ip、https://v6.myip.la/json、https://speed.neu6.edu.cn/getIP.php

都报错，未能获取IPV6地址 查看接口是否返回IPV6地址，点了，是返回的当前 地址

**Comment by jeessy2** [comment]
截图看下配置，和日志呢。重要信息马赛克

**Comment by nczyw** [comment]
> 截图看下配置，和日志呢。重要信息马赛克
![捕获](https://user-images.githubusercontent.com/29042754/143685932-2bd838d8-9214-406e-8ee9-d241eb46c45a.PNG)
上面的域名我故意没填的，我填和下面的一样，也是一样错误

**Comment by nczyw** [comment]
填的时候比 Domains 多了https://

**Comment by jeessy2** [comment]
通过接口获取的地址都不填，杂获取？？

**Comment by nczyw** [comment]
> 通过接口获取的地址都不填，杂获取？？
![1](https://user-images.githubusercontent.com/29042754/143686846-689139f0-9c60-487d-931e-6bc8dc760c9e.PNG)
肯定是都填了试过的呀。

**Comment by jeessy2** [comment]
通过安装电脑那台电脑直接访问接口地址能获取不

**Comment by nczyw** [comment]
> 通过安装电脑那台电脑直接访问接口地址能获取不

能的，这是我在DNS那边填的地址。能ping通的

**Comment by jeessy2** [comment]
获取的什么地址，发来看下呢

**Comment by nczyw** [comment]
不对啊，大佬，这个方法，是获取我填的网的ip，然后更新到域名上去吧？我是要把本机的IPV6传到阿里云去呀？

**Comment by jeessy2** [comment]
通过别人的接口获取你的IP。

**Comment by nczyw** [comment]
> 通过别人的接口获取你的IP。
![2](https://user-images.githubusercontent.com/29042754/143688874-233ddc72-94e3-4faf-8aa9-3e008cff0544.PNG)
用了这个网址获取的，看了下，仍然是临时的ipv6

**Comment by kxy09** [comment]
不知道是不是获取方式改了，点开也只能看到一个长的ipv6地址，而不是ip a命令看到的第一个最短的

**Comment by jeessy2** [comment]
> 不知道是不是获取方式改了，点开也只能看到一个长的ipv6地址，而不是ip a命令看到的第一个最短的

系统默认会通过临时IP访问，为了保护你的隐私

**Comment by yuxuan0107** [comment]
> 



> > 默认获取的第一个，每个系统第一个ipv6规则可能都不同。不好区分，欢迎提供建议
> 
> 我也在尝试怎么能不获取到临时的，其实还有个问题，获取同一个地方的IPV6，如果电脑没有重启网卡，路由器重启了，这时，微软IPV6里面还有一个已经过期的IPV6，就是路由上一次拨号分下来的前缀，获取到这个才是最为致命的，永远都不会再正确了。明明微软的网卡显示里面，能完全正确的显示IPV6，过期的，临时的，非临时的。为什么在我们调用微软的API后，就不再区分呢？目前我也还没有找到一种方式可以正确处理这个问题。

这个问题我也遇到了,路由重启pc不重启就会出现这样的问题,我现在用的是网卡获取,幸亏网卡现在地址获取的不是本地链路地址,要是本地链路地址就哭了

**Comment by jeessy2** [comment]
3.6.1后支持通过匹配正则表达式获取网卡中的ipv6地址 #227

**Comment by buqiang** [comment]
关闭临时ipv6地址
`netsh interface ipv6 set privacy state=disabled`

**Comment by igophper** [comment]
可以通过命令获取
`ipconfig | Select-String "^   IPv6 地址"`
