### ISSUE TITLE
eu.org的域名挂在cf上没办法更新ip

### ISSUE THREAD

**Issue by zhumao520** [jeessy2/ddns-go#146]
点击保存 就显示配置文件已保存在: /root/.ddns_go_config.yaml

有和我一样的吗

**Comment by jeessy2** [comment]
这个和my.com一样，分不清到底是顶级还是二级域名

**Comment by zhumao520** [comment]
有办法区分一下吗？

**Comment by jeessy2** [comment]
可以。后面加起，还有没有类似这个的

**Comment by zhumao520** [comment]
目前这种域名用的比较多

**Comment by zhumao520** [comment]
docker版本同步更新吗？

**Comment by jeessy2** [comment]
同步的

**Comment by DongfeiSay** [comment]
> v3.3.1已修复。下载试下https://github.com/jeessy2/ddns-go/releases/tag/v3.3.1

好像还是不行？域名是xx.xxx.cn.eu.org

**Comment by DongfeiSay** [comment]
> > v3.3.1已修复。下载试下https://github.com/jeessy2/ddns-go/releases/tag/v3.3.1
> 
> 还是不行？域名是xx.xxx.cn.eu.org

eu.org可以，申请的更高一级的xx.eu.org域名就不行了，都得加进去就有点麻烦了

**Comment by jeessy2** [comment]
`xx.xxx.cn.eu.org` -> `xx:xxx.cn.eu.org` 冒号分割
