### ISSUE TITLE
家宽服务器，运行更换IP指令后无法正常更新DDNS。

### ISSUE THREAD

**Issue by phdwilson** [jeessy2/ddns-go#149]
2021/12/08 09:26:18 连接失败! 点击查看接口能否返回IPv4地址,
2021/12/08 09:26:18 未能获取IPv4地址, 将不会更新
2021/12/08 09:27:28 连接失败! 点击查看接口能否返回IPv4地址,
2021/12/08 09:27:28 未能获取IPv4地址, 将不会更新

重新点击”保存“按钮后可以正常工作。

Docker容器版本和普通安装版本均拥有该问题。

使用的是接口获取IP的方式，同类DDNS服务未有异常（如Changeip.com基于CRON的CURL更换IP服务）

**Comment by phdwilson** [comment]
挺喜欢这个服务的GUI服务，因为是家宽服务器经常换IP。但是不知为何基础的DDNS功能无法使用。。
系统环境为Ubuntu 20.04 LTS ，设置更新时间为60秒。

**Comment by jeessy2** [comment]
在服务器上运行 `curl https://myip.ipip.net` 看是否返回ip地址

**Comment by phdwilson** [comment]
对的，服务器网络是正常获取到IP的，我在出现这个失败提示后也有试过，是OK的。

并且我重新点击保存并更换第二个接口后，就恢复正常了。

然后我运行换IP指令，然后又失效了，然后再更换回第一个接口点保存，又恢复正常了。

**Comment by phdwilson** [comment]
具体失效过程为以下。

服务器更换IP （约30秒左右）

DDNS更新服务失效，出现连接失败循环。

打开DDNS-GO后台，更换第一个接口为其他接口，比如第二个IPIP.NET，点击保存，恢复正常。

然后又更换IP，然后又出现连接失败循环的问题，这个时候更换为刚刚换掉的第一个接口也就是ip.sb点保存，又恢复正常。

然后换IP，又是一个循环。

**Comment by phdwilson** [comment]
我设置的DDNS更新时间为60秒。

当我把时间延长后可以正常使用。

这里有一个BUG。

也就是，假如你更换IP后，在没有更换成功（无法连接公网）的这段时间内，如果DDNS-GO服务向接口请求了IP地址，将会陷入死循环LOOP的下场。

这里需要补充一下，我的服务器网卡配置是内网IP，无论如何更换我的公网IP都不会影响我内网IP的配置。

更换IP会有30-60秒的断网间隙，这段时间内假如正好碰到DDNS-GO向接口查询公网IP地址，就会死循环，感觉这个BUG还是要修一下。

**Comment by phdwilson** [comment]
所以说，如果我把更新时间设置的太短，正好DDNS-GO 查询公网IP地址的时间与更换IP地址（断开公网）的这段时间重叠了的话，就会陷入”连接失败“无限循环的LOOP。哪怕公网恢复 CURL测试正常的情况下也会一直连接失败。

刚刚测试了一下，设置时间为300秒，基本可以算是能正常使用。

然后为了复现我的理论是否正确，我又做了一个测试。

也就是等300秒剩下30秒的时候，DDNS-GO准备向公网接口查询IP地址的时候，运行了更换IP指令，结果也是一样的，无限连接失败循环。

但是如果DDNS-GO查询公网IP的时候没有与公网断开连接的时间重叠的话，就可以正常使用。

**Comment by jeessy2** [comment]
即使在断网间隙获取不了外网。下一个时间点也会重新请求的，应该不会存在无限连接失败

**Comment by phdwilson** [comment]
> 即使在断网间隙获取不了外网。下一个时间点也会重新请求的，应该不会存在无限连接失败

我也是这么认为的，但是问题确实存在，暂时不知道是什么因素引起的。

我更换公网IP并不会影响我的机器网卡配置，网卡配置的是内网IP。

其他DDNS服务运行全部正常，比如基于CURL的changeip.com 还有 NewFuture/DDNS 都是正常

**Comment by phdwilson** [comment]
> 即使在断网间隙获取不了外网。下一个时间点也会重新请求的，应该不会存在无限连接失败

DNS-GO 更新时间设置的越短，问题出现的概率就越大，设置为60秒基本就是必出这个问题了，因为更换IP断网间隙正好也就是60秒左右。

设置的时间越长，出现该问题几率越小，时间越多，时间重叠几率也会减小。但是也增加了DDNS更新的延迟。

**Comment by phdwilson** [comment]
> 即使在断网间隙获取不了外网。下一个时间点也会重新请求的，应该不会存在无限连接失败

希望有时间可以看看什么情况修复一下吧，比如在访问第一个公网接口无法正常获得IP地址的时候访问备用接口等等方式来尝试缓解这个问题，至于是什么具体因素引起的这个问题我也不太清楚，如果需要更多信息提供您随时联系我。

**Comment by jeessy2** [comment]
截图下日志看下呢

**Comment by phdwilson** [comment]
[https://s6.jpg.cm/2021/12/08/LdF4AL.png](url)

> 截图下日志看下呢

**Comment by phdwilson** [comment]
> 截图下日志看下呢

图片我上传到图床上发给您了。

**Comment by phdwilson** [comment]
目前正常使用的话就只能把更新时间尽可能的延长。

如果不频繁更换IP是感受不到这个BUG的存在，不过一旦发生时间碰撞，那就会无限循环不会自我恢复。

**Comment by phdwilson** [comment]
使用阿里云服务器，通过弹性IP的方式，也可以复现出这个BUG。

把DDNS-GO更新时间设置为60秒，然后在DDNS-GO即将访问公网接口获取IP地址的前10-20秒的时候，将阿里云弹性IP解绑（此时失去公网访问能力），解绑后过30秒左右，重新绑定上另一个公网弹性IP地址，再连回去后台，就会看到DDNS-GO在无限循环连接失败。

**Comment by jeessy2** [comment]
我简单测了下，通过修改网关，能正常获取ipv4
![截屏2021-12-08 下午5 21 13](https://user-images.githubusercontent.com/6205259/145182477-14f040f7-725d-490f-9fd7-7ac96e4bb290.png)

**Comment by phdwilson** [comment]
> 我简单测了下，通过修改网关，能正常获取ipv4 ![截屏2021-12-08 下午5 21 13](https://user-images.githubusercontent.com/6205259/145182477-14f040f7-725d-490f-9fd7-7ac96e4bb290.png)

我的公网IP是通过访问API接口
例如https://myip.ipip.net  获取的

并且我更换公网IP并不会影响到我的网卡配置（eth0配置是内网IP 一直都不会变）只会断开公网连接一段时间。
在这段时间里如果DDNS-GO访问了  例如  https://myip.ipip.net 来获取新IP 就会循环。

在阿里云上测试最相似的例子应该就是弹性IP的解绑和重新绑定了。我测了下也确实会有这个问题。

不过触发这个问题的前置条件就是更换IP断网的时间会跟DDNS-GO获取新公网地址的时间重叠才可以。把DDNS-GO更新时间设置的尽可能长会缓解这个问题。

**Comment by jeessy2** [comment]
试下v3.3.2版本，开启了DisableKeepAlives

**Comment by jeessy2** [comment]
后面考虑吧。欢迎pr

**Comment by phdwilson** [comment]
docker版似乎还没有更新。

还有就是，遇到了一个问题，IP地址可以正常获取了，但是访问API准备更新域名DNS记录的时候又出现了无限循环。。是不是也要给访问API的代码加一下DisableKeepAlives？

**Comment by jeessy2** [comment]
docker更新了,看下网页上的版本号是不是3.3.2

**Comment by jeessy2** [comment]
试试3.3.3版本。

**Comment by phdwilson** [comment]
已經在使用3.3.4版本 更換IP導致的連接失敗循環問題似乎已經解決的比較徹底 但是偶爾會出現以下問題。

該問題是在網絡完全正常的情況下出現，但并不是無限循環，出現4-5次之後就恢復，然後過一段時間又會出現，我在出現該提示的時候嘗試CURL這個http地址，是正常獲取的，網絡沒問題。

版本：3.3.4 Docker Version
更新頻率：60s

 👇  
请求接口https://api.cloudflare.com/client/v4/zones?name=*****.co&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=******.co&status=active&per_page=50": dial tcp: i/o timeout

**Comment by jeessy2** [comment]
网不好也可能超时，后面diag超时时间5秒，整个20s. 可以自行修改一下参数并编译测试一下

**Comment by jeessy2** [comment]
3.4.0后增加`IP未改变时，将等待5次后与DNS服务商进行比对`
