### ISSUE TITLE
提个web hook的bug

### ISSUE THREAD

**Issue by MkMarko** [jeessy2/ddns-go#15]
我想推送到钉钉，结果钉钉返回你传输过去的content-type类型不正确，希望能加个content-type的参数设置

**Comment by jeessy2** [comment]
试试1.4.3版本。如`RequestBody`不为空，content-type为`application/json`
https://github.com/jeessy2/ddns-go/releases/tag/v1.4.3

**Comment by MkMarko** [comment]
我是使用docker的 docker是否已经更新？

**Comment by MkMarko** [comment]
已经测试过没有问题了
