### ISSUE TITLE
更新Cloudflare的DNS的时候提示下面的错误

### ISSUE THREAD

**Issue by cdlinsen** [jeessy2/ddns-go#153]
https://api.cloudflare.com/client/v4/zones?name=xxxxxxx&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=xxxxxxx&status=active&per_page=50": dial tcp 127.0.0.1:443: connectex: No connection could be made because the target machine actively refused it.
老是提示请求地址是 127.0.0.1

**Comment by jeessy2** [comment]
解析一下api.cloudflare.com的域名呢，有可能被你当地运营商污染了。我这里正常

**Comment by cdlinsen** [comment]
![image](https://user-images.githubusercontent.com/9855816/145405464-4b069836-c0d3-44f2-a226-e7b2789e106d.png)
我换了很多个网络环境ping  api.cloudflare.com  全都是指向的本机，但是我的电脑并没有配置cloudflare相关的host,代理关了也是一样

**Comment by jeessy2** [comment]
被劫持了。参考下`https://www.boce.com/dns/api.cloudflare.com`

**Comment by cdlinsen** [comment]
被什么东西劫持了，暂时找不到原因，在hosts指向了它的ip倒是可以了

**Comment by jeessy2** [comment]
运营商劫持了域名，好像是四川这边，其他地方没有被劫持

**Comment by cdlinsen** [comment]
确实是四川这边的

**Comment by hy817120** [comment]
> 确实是四川的

好像的确是被四川电信劫持了 返回的是127.0.0.1
