### ISSUE TITLE
流量可访问,WiFi不能访问

### ISSUE THREAD

**Issue by WaterSunMount** [jeessy2/ddns-go#155]
#### 运行环境
我的ddns是架在树莓派上的,因为运营商原因,我的ipv4地址是大局域网环境,没法使用ddns的ipv4功能,我只能使用ipv6功能进行内网穿透,对接一切正常,阿里云的域名管理也加上了一条AAAA解析配置,域名使用子域名配置
![image](https://user-images.githubusercontent.com/75781948/145320911-97e67901-79f7-4017-bc58-abb956872cac.png)

#### 运行结果
1. 在家使用`WiFi`访问ddns解析的域名正常访问
2. 使用`流量`访问ddns解析的域名正常访问
3. 使用公司的`WiFi`访问ddns解析的域名不能访问
4. 朋友测试`WiFi`访问ddns解析的域名不能访问
5. 朋友测试`流量`访问ddns解析的域名正常访问

### 其他疑问的地方
想在树莓派上架设多个服务,如果使用同一域名,不同端口区分不优雅,想使用子域名+nginx来实现,但是发现nginx配置完后,不生效的(直接访问nginx是可以看到`Welcome to nginx`页面的),就很纳闷,是因为ipv6穿透的原因吗,之前使用公网ip的服务器是同样nginx配置就可以

**Comment by jeessy2** [comment]
看你公司和朋友的wifi支持ipv6不？不支持，那确实不能访问

**Comment by WaterSunMount** [comment]
> 

ipv6

**Comment by WaterSunMount** [comment]
还有个问题,ipv6接入钉钉机器人,这个ip有问题
![image](https://user-images.githubusercontent.com/75781948/145325452-30540906-ec5b-4bcb-a3ad-9dda6fb1d812.png)
![image](https://user-images.githubusercontent.com/75781948/145325463-561fcb1a-2127-47b9-9cd9-91e2b129d334.png)

**Comment by jeessy2** [comment]
模拟测试的ip是假的，主要看通不通

**Comment by WaterSunMount** [comment]
> 模拟测试的ip是假的，主要看通不通

了解了👌🏻
