### ISSUE TITLE
家里Win安装ddns-go,通过网卡获取,会两个ip来回跳

### ISSUE THREAD

**Issue by HappyQuQu** [jeessy2/ddns-go#156]
由于通过网址获取有点问题,会获取不到v6
所以改用网卡获取,
但是win下,会有两个v6地址,所以一直会来回跳,这个有办法解决吗(linux下没有这个问题)
而且9d40 是不通的
![1](https://user-images.githubusercontent.com/4098823/145500024-eb2ee34e-bd2f-4089-8b0c-1d9f5eff2664.png)
![2](https://user-images.githubusercontent.com/4098823/145500835-ee6dd291-8aae-4177-9a42-3461ad5173e5.png)

**Comment by jeessy2** [comment]
通过接口获取比较好。windows似乎会保留过期的ipv6地址

**Comment by jeessy2** [comment]
如果需要网卡。参考下配置，未实验
`netsh interface ipv6 show privacy` 通过这个可查看配置
`netsh interface ipv6 set privacy state=disabled` 可禁用临时IPv6
`netsh interface ipv6 set privacy maxvalidlifetime=3d` 临时地址最长有效生存时间。默认值是 7d (7 天)

**Comment by HappyQuQu** [comment]
好的 谢谢 我试试
