### ISSUE TITLE
ubuntu开机自启

### ISSUE THREAD

**Issue by WYejian** [jeessy2/ddns-go#157]
请问将ddns-do文件路径加到ubuntu的Startup Applications 能否实现开机启动（非登录启动）？

**Comment by jeessy2** [comment]
直接安装服务，./ddns-go -s install

**Comment by WYejian** [comment]
安装服务后还要设置开机运行的脚本吗

**Comment by jeessy2** [comment]
不用

**Comment by WYejian** [comment]
安装后什么都不用做是吧  谢谢！！

**Comment by jeessy2** [comment]
对的。服务就可以达到这个效果

**Comment by jeessy2** [comment]
使用3.3.5版本，修复了ubuntu重启不能自动启动
