### ISSUE TITLE
测试发现在ubuntu18下直接安装并不能开机自启动

### ISSUE THREAD

**Issue by houpi** [jeessy2/ddns-go#158]
经以下操作后方可:
./ddns-go -s install
cp -f /root/.config/systemd/user/multi-user.target.wants/ddns-go.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable ddns-go
systemctl restart ddns-go

**Comment by jeessy2** [comment]
3.2.0改成安装用户服务，可能还是要安装系统服务才可以

**Comment by jeessy2** [comment]
fix by https://github.com/jeessy2/ddns-go/releases/tag/v3.3.5
