### ISSUE TITLE
家里现在有两条带公网IP的宽带，如何同时把两个IP解析到同一条记录上而不是相互覆盖？

### ISSUE THREAD

**Issue by Today-to-Lsp** [jeessy2/ddns-go#161]
如标题

**Comment by Today-to-Lsp** [comment]
![image](https://user-images.githubusercontent.com/31529293/145823897-176e7256-030c-4e75-b939-30a841ccb1e7.png)

**Comment by jeessy2** [comment]
不支持多条宽带，会更新

**Comment by Today-to-Lsp** [comment]
> 不支持多条宽带，会更新

thank
