### ISSUE TITLE
反向代理的时候的目录

### ISSUE THREAD

**Issue by BA7JCM** [jeessy2/ddns-go#165]
我用nginx反向代理ddns-go的9876端口并设置路径的话页面就不行了，看浏览器的控制台里面它还是从根目录开始找，我设置替换字段之后它还是从根目录去找
而我这个网站的根目录还整了别的东西，所以说要怎么设置反代才能让它在子目录里面

**Comment by jeessy2** [comment]
改代码为相对路径，或放在根目录

**Comment by BA7JCM** [comment]
> 改代码为相对路径，或放在根目录

我试过在浏览器中访问反代目录/static/common.css，它会自动给我跳回/static/common.css然后返回404，这是什么情况。。。

**Comment by jeessy2** [comment]
代码里改相对路径试下

**Comment by BA7JCM** [comment]
> 代码里改相对路径试下

![image](https://user-images.githubusercontent.com/79561519/146670811-ca3e8cf9-4aeb-4e94-93e8-3d68065caeaf.png)
是在这里这么改吗，我改了之后直接404了，是哪里搞错了啥吗，别的地方都没动
![image](https://user-images.githubusercontent.com/79561519/146670829-85eaf6e7-3781-42f7-b6d2-d8ef7c2313f2.png)

**Comment by jeessy2** [comment]
只改html里面的

**Comment by BA7JCM** [comment]
> 只改html里面的

![image](https://user-images.githubusercontent.com/79561519/146674409-e314a8f9-55d1-420b-8979-83251a9e74eb.png)
不行，还是会301到根目录去

**Comment by jeessy2** [comment]
html把自己的前缀./ddns/static/...加进去

**Comment by BA7JCM** [comment]
> /ddns

![image](https://user-images.githubusercontent.com/79561519/146674566-573859de-07ed-4dce-a41f-ddd51f76798f.png)
这样？

**Comment by BA7JCM** [comment]
> html把自己的前缀./ddns/static/...加进去

另外现在的问题不是它请求不到这些文件，而是这些文件的链接会自己301跳转到根目录下的路径
![image](https://user-images.githubusercontent.com/79561519/146674624-a373fb29-bae4-4226-a8d7-4f2f6cda9751.png)

root@leafhomedns:/www/wwwroot/test.ba7jcm.live/pan# curl https://test.ba7jcm.live:442/ddns/static/common.css -Lv
*   Trying 240e:3b1:767e:71b0:82c6:5321:df0a:e12:442...
* Connected to test.ba7jcm.live (240e:3b1:767e:71b0:82c6:5321:df0a:e12) port 442 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=ba7jcm.live
*  start date: Nov  8 09:08:28 2021 GMT
*  expire date: Feb  6 09:08:27 2022 GMT
*  subjectAltName: host "test.ba7jcm.live" matched cert's "*.ba7jcm.live"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5584fdda9340)
> GET /ddns/static/common.css HTTP/2
> Host: test.ba7jcm.live:442
> user-agent: curl/7.74.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 301
< server: nginx
< date: Sun, 19 Dec 2021 12:20:59 GMT
< content-type: text/html; charset=utf-8
< content-length: 53
< location: /static/common.css
< expires: Mon, 20 Dec 2021 00:20:59 GMT
< cache-control: max-age=43200
< x-cache: MISS
<
* Ignoring the response-body
* Connection #0 to host test.ba7jcm.live left intact
* Issue another request to this URL: 'https://test.ba7jcm.live:442/static/common.css'
* Found bundle for host test.ba7jcm.live: 0x5584fdda5550 [can multiplex]
* Re-using existing connection! (#0) with host test.ba7jcm.live
* Connected to test.ba7jcm.live (240e:3b1:767e:71b0:82c6:5321:df0a:e12) port 442 (#0)
* Using Stream ID: 3 (easy handle 0x5584fdda9340)
> GET /static/common.css HTTP/2
> Host: test.ba7jcm.live:442
> user-agent: curl/7.74.0
> accept: */*
>
< HTTP/2 404
< server: nginx
< date: Sun, 19 Dec 2021 12:20:59 GMT
< content-type: text/html
< content-length: 146
<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host test.ba7jcm.live left intact

**Comment by BA7JCM** [comment]
> html把自己的前缀./ddns/static/...加进去

用curl带Lv选项去访问能得到以下内容：
![image](https://user-images.githubusercontent.com/79561519/146674814-9d5d18de-d232-450f-8558-1f5d06a2bcb2.png)

![image](https://user-images.githubusercontent.com/79561519/146674820-26cf6b42-e397-44d5-9696-9d8d9a846884.png)

**Comment by jeessy2** [comment]
使用nginx的rewrite功能`        rewrite ^/order/(.*)$ /$1 break;`
或则把项目加一个前缀

**Comment by BA7JCM** [comment]
> 使用nginx的rewrite功能` rewrite ^/ddns/(.*)$ /$1 break;` 或则把整个项目加一个前缀

“给整个项目加一个前缀”怎么搞，我这个网站搭建了其它的东西，是用nginx的rewrite整的，再加别的rewrite怕搞乱

**Comment by jeessy2** [comment]
整个不好加，使用rewrite吧

**Comment by BA7JCM** [comment]
> 整个不好加，使用rewrite吧

我那个站原本搭建了generate_204的检测服务器（安卓用来判断有网没网的东西），不知道加这个rewrite会不会影响

**Comment by jeessy2** [comment]
应该没问题，帮你把个人信息的删除了

**Comment by BA7JCM** [comment]
> rewrite ^/ddns/(.*)$ /$1 break;

**Comment by BA7JCM** [comment]
> 应该没问题，帮你把个人信息的删除了

感谢帮忙处理个人信息，不过我感觉加了这玩意会陷入死循环——你程序301到/static，然后我ng又重定向到/ddns/static，如此反复循环下去。。。

**Comment by jeessy2** [comment]
参考下https://www.cnblogs.com/woshimrf/p/nginx-proxy-rewrite-url.html

**Comment by BA7JCM** [comment]
> 参考下https://www.cnblogs.com/woshimrf/p/nginx-proxy-rewrite-url.html

我感觉现在最头疼的一点就是访问到那里会被你程序301到别的地方，如果反代目录是根目录那就没问题，但问题我反代的路径不是根目录。。。就很头疼，我用vscode在整个项目源码里面查找都找不到相关的重定向代码，
![image](https://user-images.githubusercontent.com/79561519/146678388-97417e32-8ecd-421f-8916-9c18c71caaf2.png)

如果没有这个301重定向，那我估计我连源码都不用改，直接在反代的设置里面设置相关的替换就行了
![image](https://user-images.githubusercontent.com/79561519/146678373-9cbc213a-0495-4cb0-88d3-3161296ad807.png)

我把这里设置成“/”的话那其它的设置就全部都没用了，但设置成“/ddns”的话那么反代之后的路径就变成了“/ddns/ddns"，然后接着就会被跳转回”/“

**Comment by jeessy2** [comment]
程序不动，你那个没有使用过，使用rewrite原理上是可以的。

**Comment by BA7JCM** [comment]
> 程序不动，你那个管理界面没有使用过，使用rewrite原理上是可以的。

在使用由源码不做任何更改的情况下编译的程序，打开之后f12发现HTML中引用文件的路径已经成功被按要求替换了，但它们接着被重定向回到了替换之前的路径了

**Comment by BA7JCM** [comment]
> 程序不动，你那个管理界面没有使用过，使用rewrite原理上是可以的。

试了一下，现在只剩通过网卡获取v6的接口解决不了，还是从根目录去请求，设置rewrite和替换都没用
![image](https://user-images.githubusercontent.com/79561519/146680419-0dadcd49-0921-4bf1-b2e4-c664ea589934.png)

![image](https://user-images.githubusercontent.com/79561519/146680422-af3b4947-13c8-4397-a5bd-478b471254d8.png)

**Comment by jeessy2** [comment]
修改代码使用相对路径

**Comment by BA7JCM** [comment]
> 修改代码使用相对路径

![image](https://user-images.githubusercontent.com/79561519/146681304-64d61d0b-d6f8-4a07-986e-4960071205f8.png)

是我改错地方了吗还是怎么的，writing那一行我改相对路径打开就404，不改的话其它几行改了没效果，改绝对路径和相对路径都不行

**Comment by jeessy2** [comment]
已提交，不修改这这个文件

**Comment by BA7JCM** [comment]
> 已提交，不修改这这个文件

那是改哪个文件，只找到这个文件里面有相关的路径

**Comment by jeessy2** [comment]
```web/writing.html ```

**Comment by BA7JCM** [comment]
> `web/writing.html `

在HTML中没找到相关的路径设置

**Comment by jeessy2** [comment]
已提交。请更新。。。。

**Comment by BA7JCM** [comment]
> 已提交。请更新。。。。

？在哪更新

**Comment by BA7JCM** [comment]
> 已提交。请更新。。。。

看到了抱歉

**Comment by BA7JCM** [comment]
> 已提交。请更新。。。。

更新之后还是会找不到那些文件，但是在f12中查看HTML已经是用相对路径的了
![image](https://user-images.githubusercontent.com/79561519/146681823-1f835ae2-e8a8-44b2-a67f-fd678a307f3d.png)
![image](https://user-images.githubusercontent.com/79561519/146681826-b4f27c44-cb1a-4905-9e71-f5c9112f15ca.png)

**Comment by BA7JCM** [comment]
> 使用nginx的rewrite功能` rewrite ^/ddns/(.*)$ /$1 break;` 或则把整个项目加一个前缀

新版本加了这个rewrite之后所有东西都变成了/ddns/下的那个HTML的内容了

**Comment by jeessy2** [comment]
👌
