### ISSUE TITLE
cloudflare 解析ipv6失败

### ISSUE THREAD

**Issue by MrTsien** [jeessy2/ddns-go#167]
请求接口 https://api.cloudflare.com/client/v4/zones?name=xxx.com&status=active&per_page=50 失败! 
返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400

**Comment by jeessy2** [comment]
查看创建的token是否正确
`创建令牌->编辑区域 DNS(使用模板)`
