### ISSUE TITLE
配置文件路径不支持空格

### ISSUE THREAD

**Issue by YuXianYuan** [jeessy2/ddns-go#168]
比如，配置文件存入C:\Program Files (x86)\ddns-go_3.3.5_Windows_x86_64
指令 -c C:\Program Files (x86)\ddns-go_3.3.5_Windows_x86_64
结果，在C盘新建了一个奇奇怪怪的Program文件

**Comment by jeessy2** [comment]
最好不放入这种特殊字符的文件夹中

**Comment by YuXianYuan** [comment]
好嘞
