### ISSUE TITLE
可不可以加一个配置代理的功能呢

### ISSUE THREAD

**Issue by cdlinsen** [jeessy2/ddns-go#169]
Cloudflare的api接口地址，老是因为各种各样的原因访问不了，导致更新DNS失败

**Comment by jeessy2** [comment]
后面在考虑。欢迎PR

**Comment by yin1999** [comment]
是否考虑使用 `ProxyFromEnvironment` 的模式（ref: [ProxyFromEnvironment](https://pkg.go.dev/net/http#ProxyFromEnvironment), [DefaultTransport](https://pkg.go.dev/net/http#DefaultTransport)），允许用户通过设置环境变量的方式使用代理。不过需要考虑排除 IP 检测 API 使用带有 `proxy` 的 `Transport`。

**Comment by jeessy2** [comment]
> 是否考虑使用 `ProxyFromEnvironment` 的模式（ref: [ProxyFromEnvironment](https://pkg.go.dev/net/http#ProxyFromEnvironment), [DefaultTransport](https://pkg.go.dev/net/http#DefaultTransport)），允许用户通过设置环境变量的方式使用代理。不过需要考虑排除 IP 检测 API 使用带有 `proxy` 的 `Transport`。

可以，检测的API统一经过代理？

**Comment by yin1999** [comment]
> 可以，检测的API统一经过代理？

感觉检测 IP 的请求不经过代理会好一些，代理主要还是用于解决API接口无法直接访问的问题。

**Comment by jeessy2** [comment]
> > 可以，检测的API统一经过代理？
> 
> 感觉检测 IP 的请求不经过代理会好一些，代理主要还是用于解决API接口无法直接访问的问题。

#346 review一下

**Comment by jeessy2** [comment]
4.0.2 使用默认的 [DefaultTransport](https://pkg.go.dev/net/http?utm_source=gopls#DefaultTransport) ，默认包含`ProxyFromEnvironment `

具体在操作系统环境变量中配置HTTP_PROXY或HTTPS_PROXY使用
