### ISSUE TITLE
dnspod解析失败获取不到接口

### ISSUE THREAD

**Issue by 1637410810** [jeessy2/ddns-go#170]
![image](https://user-images.githubusercontent.com/42006019/148002550-b9aceed2-9d4a-4228-99b7-ce9e34cf2dd3.png)

**Comment by jeessy2** [comment]
调用dnspod接口失败了，通过curl https://despond.cn/Record.List测试下本地网络环境

**Comment by 1637410810** [comment]
这个地址访问不到，curl不到

**Comment by jeessy2** [comment]
`curl -X POST https://dnsapi.cn/Record.List` 我这里访问正常，检查下本地网络

**Comment by 1637410810** [comment]
更新成功了，日志显示时好时坏

**Comment by jeessy2** [comment]
3.4.0后增加 `IP未改变时，将等待5次后与DNS服务商进行比对`
