### ISSUE TITLE
黑裙晖 显示 Failed to get ipv6, URL: https://api-ipv6.ip.sb/ip

### ISSUE THREAD

**Issue by wggglggg** [jeessy2/ddns-go#18]
我用ipv6 test 网站可以获取ipv6,  我的软路由Openwrt可以拿到openwrt的ipv6,并将ipv6传到阿里云上来域名访问,  群晖装这个ddsn-go失败,  夏天时我在网上找的aliddns.sh小插件正常实现过,将群晖上的ipv6攻取传到阿里云上,  后来电脑没开机半年时间,今天重装群晖, 用ddsn-go无法实现,  拿不到群晖的ipv6, 请问如何能解决?

**Comment by jeessy2** [comment]
1. 群晖是不是装在虚拟机下，虚拟机能获取ipv6，但不能使用ipv6
1. 如不装在虚拟机下，群晖系统中看下获取ipv6地址没有?

**Comment by wggglggg** [comment]
1  群晖是直接装在物理机上的,没有装虚拟机
2  群晖可以获取IPV6,  我用群晖里的IPV6,  在浏览器直接能访问, 目前问题就卡在ddsn go无法获取群晖的ipv6,因为我是移动宽带, 夏天也是同样的环境, 用那个小sh插件能获取ipv6,  那个小插件没备份, 也不知道以前在哪个网站下的. 
3  ddns go 是看这这位视频跟着做的, 环境跟他一样,.https://www.youtube.com/watch?v=Hm7kOsmbuyI&t=95s       .

**Comment by wggglggg** [comment]
> 1. 群晖是不是装在虚拟机下，虚拟机能获取ipv6，但不能使用ipv6
> 2. 如不装在虚拟机下，群晖系统中看下获取ipv6地址没有?

**Comment by jeessy2** [comment]
核对勾选：使用与 Docker Host 相同的网络)
参考如下：
群晖：使用docker。1、注册表中搜索ddns-go并下载。 2、映像 -> 选择jeessy/ddns-go -> 启动 -> 高级设置 -> 网络中勾选使用与 Docker Host 相同的网络)

**Comment by wggglggg** [comment]
没做任何修改,跑去重启了光猫, , 现在可以了,  谢谢

**Comment by jeessy2** [comment]
未勾选`使用与 Docker Host 相同的网络`也可以？请看下ddns-go日志还有那个错误否

**Comment by wggglggg** [comment]
呃,,,发现又不能域名访问了,  我发现可能是我手动把ipv6复制到阿里云,这样能打开, 虽然重启了猫, 但是IPV6还是保留了一段时间, 可能 半小时或许几分钟,  吃过饭再来域名访问群晖, 发现又不能访问了,  从安装到目前,, ddns-go里面日志都是显示 fail to get ipv6,,  这个查询URLhttps://api-ipv6.ip.sb/ip,  这个地址一直打不开

**Comment by jeessy2** [comment]
我看了视频，作者应该没有说对，ipv4可以那样设置，ipv6需要改成`使用与 Docker Host 相同的网络`

**Comment by wggglggg** [comment]
按你说的钩选了, 一样fail to get ipv6

**Comment by jeessy2** [comment]
应该可以的。你重启docker容器试试，或重新创建下

**Comment by wggglggg** [comment]
https://api-ipv6.ip.sb/ip               这个检测ipv6的网址移动宽带打不开,会不会是这样原因,  用移动手机卡也打不开, 发现问题就在这,  我换了联通手机卡尝试打开这个网址, 他妹的一下就能打开网页显示IPV6,  其它地区移动宽带我不清楚, 无锡的不行

**Comment by wggglggg** [comment]
可以不可以换成别的网址来检测IPV6?

**Comment by jeessy2** [comment]
我这边能正常打开,你可以换成其它的，备注里有。参考：`https://api-ipv6.ip.sb/ip` `https://v6.myip.la/json` `https://speed.neu6.edu.cn/getIP.php`

**Comment by wggglggg** [comment]
> 我这边能正常打开,你可以换成其它的，备注里有。参考：`https://api-ipv6.ip.sb/ip` `https://v6.myip.la/json` `https://speed.neu6.edu.cn/getIP.php`
这一次是真的正常工作了,  原来参考就是这个意思, 谢谢你了.

**Comment by jeessy2** [comment]
好。发布v1.4.4优化相关提示。

![image](https://user-images.githubusercontent.com/6205259/102595615-d6b14e80-4152-11eb-9ba6-6fd5b9f9f3b0.png)

**Comment by wggglggg** [comment]
> 好。发布v1.4.4优化相关提示。
> 
> ![image](https://user-images.githubusercontent.com/6205259/102595615-d6b14e80-4152-11eb-9ba6-6fd5b9f9f3b0.png)

好的，希望其它机友可以一次成功

**Comment by wggglggg** [comment]
不好意思, 忘记关贴了
