### ISSUE TITLE
支持noip吗

### ISSUE THREAD

**Issue by cero-ss** [jeessy2/ddns-go#182]
www.noip.com这个ddns支持吗，我发现他们官网的软件只能同步ipv4的地址，不知道ddnsgo能否支持，不支持的话后续能否支持呢

**Comment by jeessy2** [comment]
可使用callback更新

**Comment by cero-ss** [comment]
> 可使用callback更新

具体该怎么操作呢，虽然有看到这个功能，但完全不知道该怎么用

**Comment by jeessy2** [comment]
参考 [#177](https://github.com/jeessy2/ddns-go/issues/117)

**Comment by cero-ss** [comment]
> 参考 [#177](https://github.com/jeessy2/ddns-go/issues/117)

其实我在提问前就搜到了 #177那个提问，但是完全没看懂怎么操作

**Comment by jeessy2** [comment]
callback中输入（#{domain}就是ipv4/ipv6处的域名）
http://main.meibu.com/ip/login.asp?name=#{domain}&pwd=PASSWORD

然后在ipv4或ipv6域名处输入你的域名即可

实在不行你买个域名吧，又不贵

**Comment by cero-ss** [comment]
> callback中输入（#{domain}就是ipv4/ipv6处的域名） [http://main.meibu.com/ip/login.asp?name=#{domain}&pwd=PASSWORD](http://main.meibu.com/ip/login.asp?name=#%7Bdomain%7D&pwd=PASSWORD)
> 
> 然后在ipv4或ipv6域名处输入你的域名即可
> 
> 实在不行你买个域名吧，又不贵
注册noip后给域名了啊，也填了啊并没有用

**Comment by jeessy2** [comment]
怎么填的，截个图看下，重要信息马赛克

**Comment by cero-ss** [comment]
> 怎么填的，截个图看下，重要信息马赛克
![网页捕获_18-1-2022_225817_127 0 0 1](https://user-images.githubusercontent.com/32891402/149962099-fe5e4cb9-348e-487c-8d9e-4d30faf662a9.jpeg)

**Comment by jeessy2** [comment]
直接在浏览器输入callback的URL看成功不，你用的noip不是这个URL吧

**Comment by cero-ss** [comment]
https://www.noip.com/integrate/request

我看他们网站上给的是这样的格式
http://username:password@dynupdate.no-ip.com/nic/update?hostname=mytest.example.com&myip=192.0.2.25,2001:0db8::2e

我照着填就是
http://注册名:密码@dynupdate.no-ip.com/nic/update?hostname=域名&myip=ipv4地址,ipv6地址
改好后填在浏览器打开就能更新成功了，但是这个ipv4和ipv6得手动填，如何能用ddnsgo获取的地址帮我自动替换呢

**Comment by cero-ss** [comment]
> 用#{ip}替换

感谢终于成功了，超级感谢
