### ISSUE TITLE
多网卡 如何 获取指定网卡的IP?

### ISSUE THREAD

**Issue by tanpengsccd** [jeessy2/ddns-go#183]
群晖2个LAN 口 分别接入2个 LAN: 一个为移动1000M, 一个 为电信200M.
群晖我我默认是移动优先,因为口子更大,但是没公网. 电信有公网所以想拿来作DDNS.
但是

![image](https://user-images.githubusercontent.com/13959880/149797033-6d48081e-b0db-4ae3-9e55-291251d9216c.png)
用接口获取的IP是移动大公网的IP,不能用.
用通过网卡获取 的是内网IP. 192.168.2.X 这种 IP. 
都不能正常使用

**Comment by jeessy2** [comment]
试试群晖的静态路由功能
