### ISSUE TITLE
求助,再群晖docker下遇到了报错

### ISSUE THREAD

**Issue by hy817120** [jeessy2/ddns-go#185]
网络环境是PVE下ikuai做的播放,然后虚拟机装的群晖,群晖里又装的docker,本身有IPV6的动态公网IP,可以直接在cloudflare上直接绑定使用,已经测试成功,用此脚本做群晖docker上的ddns出现报错.
不知道是否是外网不通的原因.

2022/01/25 16:47:55 请求接口https://api.cloudflare.com/client/v4/zones?name=xxxxx.live&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=xxxx.live&status=active&per_page=50": x509: certificate is valid for synology, not api.cloudflare.com

![df647fe4-5cba-4ac1-adbf-9273af200521](https://user-images.githubusercontent.com/46050478/150944996-e811ab1d-40a6-43ef-aed2-e914acad9b55.png)

**Comment by jeessy2** [comment]
通过curl直接访问，看能访问不
参考 #153

**Comment by hy817120** [comment]
> 通过curl直接访问，看能访问不 参考#153

搞定了感谢, 原来开启IPv6后,  默认先走的是ipv6协议,但是四川电信把cloudflareipv6给劫持了,我现在的做法是,路由器开启IPV6但不分配DNS, 这样,走的还是IPV4, 就可以了. 因为我的IPV4本身是有翻墙插件,
