### ISSUE TITLE
-s install  没有效果

### ISSUE THREAD

**Issue by helieting** [jeessy2/ddns-go#186]
电脑 mac mini  m1

install 后，没有进程产生

**Comment by jeessy2** [comment]
1. 是否下载包含Darwin_arm64的文件
2. 检查是否存在`ls ~/Library/LaunchAgents/ddns-go.plist`

**Comment by helieting** [comment]
1,是的
2，没有这个文件

**Comment by jeessy2** [comment]
install后，控制台输出的什么内容

**Comment by helieting** [comment]
显示安装成功, 在执行,显示已安装

jeessy2 ***@***.***> 于2022年1月27日周四 22:12写道：

**Comment by jeessy2** [comment]
没有m1的笔记本，自行测试下，有结果在反馈一下

**Comment by avtion** [comment]
M1 Max 可以尝试使用 `sudo` 执行

**Comment by jeessy2** [comment]
mac系统版本是不是12. 如果是参考 #199 
可使用3.5.0版本，3.5.0后全部都安装为系统服务 https://github.com/jeessy2/ddns-go/releases/tag/v3.5.0
