### ISSUE TITLE
配置文件中的密钥相关字段建议加密存储

### ISSUE THREAD

**Issue by sun-weihan** [jeessy2/ddns-go#187]
如`dns.id`和`dns.secret`

**Comment by jeessy2** [comment]
密钥也要存储到配置文件中，拿到这个密钥也可以通过这个来解密，意义也不大。看有没有其他方式

**Comment by Rirmach** [comment]
[Rclone](https://github.com/rclone/rclone/blob/9e2fbe0f1a9314e1330b4adc9d69de137be12ee6/fs/config/obscure/obscure.go#L48) 用了一种比较简单的混淆方式。  
考虑到比较有威胁的自动化脚本也很难去翻源码开盒，简单的混淆至少比明文能好一些。  
如果可以我来推个PR。

**Comment by jeessy2** [comment]
> [Rclone](https://github.com/rclone/rclone/blob/9e2fbe0f1a9314e1330b4adc9d69de137be12ee6/fs/config/obscure/obscure.go#L48) 用了一种比较简单的混淆方式。 考虑到比较有威胁的自动化脚本也很难去翻源码开盒，简单的混淆至少比明文能好一些。 如果可以我来推个PR。

欢迎。需考虑以前的配置文件升级
