### ISSUE TITLE
能否增加对分区域解析的支持

### ISSUE THREAD

**Issue by walkxspace** [jeessy2/ddns-go#189]
例如利用 [DNSPod API 文档中](https://www.dnspod.cn/docs/records.html) 中的 `record_line` 参数仅对用户自己所在地区添加解析记录，其余默认返回 `127.0.0.1` 或 `::1` 的记录亦或直接不作解析记录，以进一步减少被暴力扫描破解的危害。
![Snipaste_2022-02-02_13-30-41](https://user-images.githubusercontent.com/51308700/152098308-96b6640c-6f16-4e82-89d0-91c5209aeffb.png)

**Comment by jeessy2** [comment]
有些服务商不支持，页面也弄复杂了，暂不考虑。可以自行修改运行

**Comment by walkxspace** [comment]
DDNS-GO 本身所支持的服务商仅 Cloudflare 不支持国内分区的解析，界面的话或许只用添加一个输入框，不填就使用现版本所使用的默认记录，需要使用的话 DNSPod 可以用户自行输入例如“华北”、“北京电信”的文字。
此外，阿里云相关的 API 可在[此处](https://help.aliyun.com/document_detail/29772.html)、华为云相关的 API 可在[此处](https://support.huaweicloud.com/api-dns/dns_api_65001.html)找到，均通过 `Line` 参数，用户可自行输入诸如 `cn_telecom_beijing`(阿里云)、`Dianxin_Beijing`(华为云) 以仅对北京电信进行解析。

**Comment by jeessy2** [comment]
感兴趣的话，欢迎PR

**Comment by walkxspace** [comment]
纯外行，不太会编程😅，但看[此处](https://github.com/jeessy2/ddns-go/blob/9bb457db30aa0857aa34c9b216beb587c1922369/dns/dnspod.go#L96)代码，应该可小幅更改以增加对DNSPod分区解析的支持。

**Comment by jeessy2** [comment]
4.0.0后支持，欢迎尝鲜
