### ISSUE TITLE
NAS上docker启动，日志无报错，但一直不生效

### ISSUE THREAD

**Issue by L0yy** [jeessy2/ddns-go#190]
docker 网络是host模式
提示如下，等待10多分钟后去腾讯云后台看，没生效
![image](https://user-images.githubusercontent.com/43272685/152795903-bf999924-8790-4e8c-b4be-304d85119dfa.png)
黑裙版本
![image](https://user-images.githubusercontent.com/43272685/152796188-1e00c806-a976-482c-b4d2-c01159d413a2.png)

已排查方案
重申请过token，重装过镜像（laster）

**Comment by jeessy2** [comment]
域名都没有输入，怎么更新😹
