### ISSUE TITLE
不支持Windows-XP, 32位的也不行

### ISSUE THREAD

**Issue by lqsbg26** [jeessy2/ddns-go#191]
操作系统是Windows XP，service pack 3，32位，简体中文版。下载了ddns-go_3.4.1_Windows_i386.tar.gz，运行时提示“不是有效的Win32应用程序”。另外下载了v2.0.2，v1.2.1的i386版本进行尝试，都不行，提示是同样的。

**Comment by jeessy2** [comment]
直接用源码编译试试

**Comment by bfbfcom** [comment]
windows xp， windows 2003 
x386程序
无法正常使用。 不是有效的32位程序。

**Comment by jeessy2** [comment]
> windows xp， windows 2003 
> 
> x386程序
> 
> 无法正常使用。 不是有效的32位程序。

直接用源码编译试试

**Comment by bfbfcom** [comment]
大佬，我是真的不会编译啊。
我下载啦 从0.1到最新的5.7 逐个测试，都是这个毛病。

https://blog.csdn.net/u014386971/article/details/22490277  
是不是这个页面描述的 问题呢，大佬在编译的时候。没有勾选 兼容 winxp  和windows2003呢

**Comment by jeessy2** [comment]
go语言写的...
升级系统吧，都这么老的系统了

**Comment by bfbfcom** [comment]
好的，谢谢了
测试了，好几个 ddns 都无法运行。
