### ISSUE TITLE
返回状态码: 400

### ISSUE THREAD

**Issue by faonecze** [jeessy2/ddns-go#192]
请教,正常运行后并填写好内容保存(aliyun),提示:

2022/02/12 16:06:24 配置文件已保存在: /root/.ddns_go_config.yaml
2022/02/12 16:06:24 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"586EBxxxED-EB43A497AFDD","Message":"Specified time stamp or date value is expired.","Recommend":"https://error-center.aliyun.com/status/search?Keyword=InvalidTimeStamp.Expired&source=PopGw","HostId":"alidns.aliyuncs.com","Code":"InvalidTimeStamp.Expired"} ,返回状态码: 400

查看dns那边日至也没有修改啊.

**Comment by jeessy2** [comment]
检查本地时间，时间不准确
