### ISSUE TITLE
win10配置运行后报错

### ISSUE THREAD

**Issue by yanweijum** [jeessy2/ddns-go#194]
请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"AA04D6BE-BAB2-55BF-B916-FBC104BB97FB","Message":"Specified time stamp or date value is expired.","Recommend":"https://error-center.aliyun.com/status/search?Keyword=InvalidTimeStamp.Expired&source=PopGw","HostId":"alidns.aliyuncs.com","Code":"InvalidTimeStamp.Expired"} ,返回状态码: 400

**Comment by jeessy2** [comment]
时间不对。#192
