### ISSUE TITLE
求支持dynv6！群晖7.0没有软件能使用dynv6的

### ISSUE THREAD

**Issue by 1103471751** [jeessy2/ddns-go#195]

**Comment by jeessy2** [comment]
使用callback

**Comment by 1103471751** [comment]
> 

试过了，不行

**Comment by 1103471751** [comment]
> 使用回调

试过了，不行

**Comment by 1103471751** [comment]
> 使用callback

试过了，不行

**Comment by jeessy2** [comment]
给个日志之类的。参考下#182

**Comment by hjkl950217** [comment]
同样求dynv6支持

**Comment by 1103471751** [comment]
> 同样求dynv6支持

URL里填http://ipv6.dynv6.com/api/update?zone=（域名）&token=（key）&ipv6=auto

RequestBody里填域名

**Comment by hjkl950217** [comment]
@1103471751  可以了，我之前用脚本在跑，把脚本里面的url放在这上面就可以了

**Comment by hjkl950217** [comment]
@1103471751 再问一下大佬，有没有做AAAA记录的考虑鸭？ dynv6支持aaaa,也有更新的API，但是需要先调用一个API获取id,再拿IP地址和IP去更新。 请求时还要带上认证头，而且这个更新是PATH的请求方式，不是普通的get post。。 我用postman调用成功过一次

**Comment by Duke-li** [comment]
可以考虑用其他docker镜像支持

**Comment by humSuperman** [comment]
> > 同样求dynv6支持
> 
> URL里填[http://ipv6.dynv6.com/api/update?zone=（域名）&token=（key）&ipv6=auto](http://ipv6.dynv6.com/api/update?zone=%EF%BC%88%E5%9F%9F%E5%90%8D%EF%BC%89&token=%EF%BC%88key%EF%BC%89&ipv6=auto)
> 
> RequestBody里填域名

测试成功，感谢
