### ISSUE TITLE
能否实现多终端IPV6域名解析？

### ISSUE THREAD

**Issue by ZhxChen** [jeessy2/ddns-go#205]
获取ipv6 /64前缀
内网主机1域名：host1.domain.com
内网主机1 ipv6地址：动态前缀:（后64自己固定写死）

内网主机2域名：host2.domain.com
内网主机2 ipv6地址：动态前缀:（后64自己固定写死）

内网主机3域名：host3.domain.com
内网主机3 ipv6地址：动态前缀:（后64自己固定写死）

ipv6分配不搞slaac，内网dhcpv6固定后缀。

**Comment by jeessy2** [comment]
没有计划支持。感兴趣的话，欢迎PR

**Comment by jeessy2** [comment]
#104
