### ISSUE TITLE
阿里云请求失败，返回状态码：400

### ISSUE THREAD

**Issue by mouren-zhang** [jeessy2/ddns-go#207]
新建AccessKey 好几次了 确定不是AccessKey 的问题

**Comment by jeessy2** [comment]
传一下报错的日志，才好分析

**Comment by jerry91222** [comment]
2022/03/17 23:15:30 配置文件已保存在: /root/.ddns_go_config.yaml
2022/03/17 23:15:31 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"A54D0EF9-75BA-57AD-9A44-00E0C15C9F44","HostId":"alidns.aliyuncs.com","Code":"QuotaExceeded.TTL","Message":"The specified TTL is invalid. A valid TTL must be in the range of 600 to 86400.","Recommend":"https://error-center.aliyun.com/status/search?Keyword=QuotaExceeded.TTL&source=PopGw"} ,返回状态码: 400
2022/03/17 23:15:31 更新域名解析 www.XXX.XXX 失败！

**Comment by mouren-zhang** [comment]
搞忘记了 我传一下返回

请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"34025A66-A43F-58E5-9842-5BB42964F755","Message":"Specified access key is not found or invalid.","Recommend":"https://error-center.aliyun.com/status/search?Keyword=InvalidAccessKeyId&source=PopGw","HostId":"alidns.aliyuncs.com","Code":"InvalidAccessKeyId"} ,返回状态码: 404

就这样

**Comment by mouren-zhang** [comment]
额 好像是我这边的问题 我也不清楚 以前的AccessKey就是不行  我把以前的删了 用新建的就没问题了   尝试复现 但是复现不了害~~

**Comment by mouren-zhang** [comment]
感谢老哥的回复

**Comment by panhuide** [comment]
2023/12/10 22:22:54 配置文件已保存在: /root/.ddns_go_config.yaml
2023/12/10 22:22:55 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"093026A0-7B93-5C4F-893A-BA3A6D24E958","HostId":"alidns.aliyuncs.com","Code":"InvalidDomainName.NoExist","Message":"The specified domain name does not exist. Refresh the page and try again.","Recommend":"https://api.aliyun.com/troubleshoot?q=InvalidDomainName.NoExist&product=Alidns&requestId=093026A0-7B93-5C4F-893A-BA3A6D24E958"} ,返回状态码: 400
大佬，想问下这是什么情况
