### ISSUE TITLE
允许设置多个返回公网IP网址

### ISSUE THREAD

**Issue by kksay2010** [jeessy2/ddns-go#212]
我这边经常发现这些返回公网IP网址挂掉，建议允许设置多个。
 逻辑是这样的，第一个返回了就用第一个IP值，第一个没返回，就用第二个公网网址。。。。。

**Comment by jeessy2** [comment]
比较好的建议，欢迎PR

**Comment by jeessy2** [comment]
v3.6.0后已支持
