### ISSUE TITLE
server酱的调用api可以换成新版的

### ISSUE THREAD

**Issue by SakuraLaurel** [jeessy2/ddns-go#213]
server酱旧版的api是
https://sc.ftqq.com/[SCKEY(登入后可见)].send?text=主人服务器又挂掉啦~
新版是
https://sctapi.ftqq.com/****************.send?title=messagetitle

新版功能好像更加丰富一些

**Comment by jeessy2** [comment]
可以。只用修改说明文档就可以了。可以PR

**Comment by jeessy2** [comment]
可以。只用修改说明文档就可以了。可以PR

**Comment by jeessy2** [comment]
fixed

**Comment by SakuraLaurel** [comment]
QaQ谢谢jeessy大佬

**Comment by jeessy2** [comment]
谢谢这个 #225
