### ISSUE TITLE
使用钉钉以后显示的是本地地址和测试域名。

### ISSUE THREAD

**Issue by s0ng1** [jeessy2/ddns-go#214]
![image](https://user-images.githubusercontent.com/101986150/159171104-31c0e1aa-08a4-4871-a240-d589dcba2d3e.png)
![image](https://user-images.githubusercontent.com/101986150/159171113-2397a078-ea32-4a1e-9293-99290d238ef9.png)

**Comment by jeessy2** [comment]
模拟测试是这样的。
