### ISSUE TITLE
希望支持多个dns供应商同时解析

### ISSUE THREAD

**Issue by lizheyo77** [jeessy2/ddns-go#216]
希望支持多个dns供应商同时解析域名,而不是像现在只能一个提供商解析域名

**Comment by jeessy2** [comment]
页面不好处理，多个服务商，输入域名的地方只有一个。建议转到一个服务商

**Comment by lizheyo77** [comment]
> 页面不好处理，多个服务商，输入域名的地方只有一个。建议转到一个服务商

2022/03/24 09:09:22 连接失败! [点击查看接口能否返回IPv4地址](http://whatismyip.akamai.com/),
2022/03/24 09:09:22 未能获取IPv4地址, 将不会更新

**Comment by lizheyo77** [comment]
> 页面不好处理，多个服务商，输入域名的地方只有一个。建议转到一个服务商

每次断电都不会自动更新怎么办啊

**Comment by jeessy2** [comment]
应该是网络没准备好，请求失败了。下一个循环就好了

**Comment by lizheyo77** [comment]
> 应该是网络没准备好，请求失败了。下一个循环就好了

可以就是延迟启动这个插件20s嘛 大概20s就不会出现这个问题了

**Comment by lizheyo77** [comment]
> 应该是网络没准备好，请求失败了。下一个循环就好了

一循环是多久 我看他的提示好像是将不会更新

**Comment by jeessy2** [comment]
默认5分钟。怎么重现的

**Comment by lizheyo77** [comment]
> 默认5分钟


> 默认5分钟。怎么重现的

断电开机

**Comment by lizheyo77** [comment]
> 默认5分钟。怎么重现的

还有个问题 ddns内网可以访问 外网无法访问 不知啥原因 配置文件正常

**Comment by jeessy2** [comment]
> 可以就是延迟启动这个插件20s嘛 大概20s就不会出现这个问题了

欢迎PR

**Comment by jeessy2** [comment]
> > 应该是网络没准备好，请求失败了。下一个循环就好了
> 
> 可以就是延迟启动这个插件20s嘛 大概20s就不会出现这个问题了

v3.6.1 docker中延时10s 其它延时20s #235

**Comment by FxPixels** [comment]
> 页面不好处理，多个服务商，输入域名的地方只有一个。建议转到一个服务商

我觉得可不可以把页面做tabs的形式，使用不同多页面对应多供应商

**Comment by jeessy2** [comment]
> > 页面不好处理，多个服务商，输入域名的地方只有一个。建议转到一个服务商
> 
> 
> 
> 我觉得可不可以把页面做tabs的形式，使用不同多页面对应多供应商

可以。可以考虑一下怎么设计美观，感兴趣来个PR

**Comment by jeessy2** [comment]
5.0.0已支持 https://github.com/jeessy2/ddns-go/releases/tag/v5.0.0
