### ISSUE TITLE
Win10 Docker 获取ipv4失败

### ISSUE THREAD

**Issue by tomguan** [jeessy2/ddns-go#217]
docker run -d --name ddns-go --restart=always -p 9876:9876 -v D:\Docker\server\ddns-go:/root jeessy/ddns-go

配置文件：
ipv4:
  enable: true
  gettype: url
  url: https://myip4.ipip.net
  netinterface: ""
  domains:
  - xx.xxxx.net

Win docker版本：v4.6.1（76265）
Mac docker版本：v4.5.0（74594）（mac os v11.1，安装该docker，正常使用，一周都很稳。所以觉得用这个方案，迁移到win10上用）。

日志：
2022/03/27 23:22:02 监听 :9876 ...

2022/03/27 23:22:17 连接失败! <a target='blank' href='https://api-ipv4.ip.sb/ip'>点击查看接口能否返回IPv4地址</a>,

2022/03/27 23:22:17 未能获取IPv4地址, 将不会更新

2022/03/27 23:27:27 连接失败! <a target='blank' href='https://api-ipv4.ip.sb/ip'>点击查看接口能否返回IPv4地址</a>,

2022/03/27 23:27:27 未能获取IPv4地址, 将不会更新

2022/03/27 23:32:37 连接失败! <a target='blank' href='https://api-ipv4.ip.sb/ip'>点击查看接口能否返回IPv4地址</a>,

2022/03/27 23:32:37 未能获取IPv4地址, 将不会更新

2022/03/27 23:32:37 Webhook调用成功, 返回数据: {"errcode":0,"errmsg":"ok"}

多次尝试都不行； 偶尔能成功获取一次。提示无法获取，获取apiv4的接口，贴进浏览器里看，每次都是成功的。宽带网络状况等，都很好。这个配置在Mac OS v11.1 的 docker中，正常使用。

**Comment by jeessy2** [comment]
进入容器里，通过curl请求接口看能获取IP不

**Comment by tomguan** [comment]
> 进入容器里，通过curl请求接口看能获取IP不

我是小白， 求指教：curl 怎么快速安装。这个容器里， apt也没有。curl 网上的链接都失效了。 从macos里 copy了一个过来， 用不了

**Comment by yin1999** [comment]
In alpine, please try:

```bash
# install curl
apk add curl
```

**Comment by tomguan** [comment]
> 

think you!  "apk add curl" is good for me 😄

**Comment by tomguan** [comment]
/app # curl https://www.baidu.com
<!DOCTYPE html>
<html> <head><meta http-equiv=content-type content=text/html;charset=utf-8><meta http-equiv=X-UA-Compatible content=IE=Edge><meta content=always name=referrer><link rel=stylesheet type=text/css href=https://ss1.bdstatic.com/5eN1bjq8AAUYm2zgoY3K/r/www/cache/bdorz/baidu.min.css><title>百度一下，你就知道</title></head> <body link=#0000cc> <div id=wrapper> <div id=head> <div class=head_wrapper> <div class=s_form> <div class=s_form_wrapper> <div id=lg> <img hidefocus=true src=//www.baidu.com/img/bd_logo1.png width=270 height=129> </div> <form id=form name=f action=//www.baidu.com/s class=fm> <input type=hidden name=bdorz_come value=1> <input type=hidden name=ie value=utf-8> <input type=hidden name=f value=8> <input type=hidden name=rsv_bp value=1> <input type=hidden name=rsv_idx value=1> <input type=hidden name=tn value=baidu><span class="bg s_ipt_wr"><input id=kw name=wd class=s_ipt value maxlength=255 autocomplete=off autofocus=autofocus></span><span class="bg s_btn_wr"><input type=submit id=su value=百度一下 class="bg s_btn" autofocus></span> </form> </div> </div> <div id=u1> <a href=http://news.baidu.com name=tj_trnews class=mnav>新闻</a> <a href=https://www.hao123.com name=tj_trhao123 class=mnav>hao123</a> <a href=http://map.baidu.com name=tj_trmap class=mnav>地图</a> <a href=http://v.baidu.com name=tj_trvideo class=mnav>视频</a> <a href=http://tieba.baidu.com name=tj_trtieba class=mnav>贴吧</a> <noscript> <a href=http://www.baidu.com/bdorz/login.gif?login&amp;tpl=mn&amp;u=http%3A%2F%2Fwww.baidu.com%2f%3fbdorz_come%3d1 name=tj_login class=lb>登录</a> </noscript> <script>document.write('<a href="http://www.baidu.com/bdorz/login.gif?login&tpl=mn&u='+ encodeURIComponent(window.location.href+ (window.location.search === "" ? "?" : "&")+ "bdorz_come=1")+ '" name="tj_login" class="lb">登录</a>');
                </script> <a href=//www.baidu.com/more/ name=tj_briicon class=bri style="display: block;">更多产品</a> </div> </div> </div> <div id=ftCon> <div id=ftConw> <p id=lh> <a href=http://home.baidu.com>关于百度</a> <a href=http://ir.baidu.com>About Baidu</a> </p> <p id=cp>&copy;2017&nbsp;Baidu&nbsp;<a href=http://www.baidu.com/duty/>使用百度前必读</a>&nbsp; <a href=http://jianyi.baidu.com/ class=cp-feedback>意见反馈</a>&nbsp;京ICP证030173号&nbsp; <img src=//www.baidu.com/img/gs.gif> </p> </div> </div> </div> </body> </html>
/app # curl https://api-ipv4.ip.sb/ip
curl: (6) Could not resolve host: api-ipv4.ip.sb


docker里 执行是这样的，看起来像dns问题； 宿主机能访问， 到 docker里，不这腾出

**Comment by jeessy2** [comment]
建议使用3.6.0支持多个接口

**Comment by tomguan** [comment]
添加dns  114.114.114.114 之后， ping 域名识别了。 curl：
/app # curl https://api-ipv4.ip.sb/ip
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by tomguan** [comment]
docker镜像里， 也有 3.6.0 了吗？  当前安装的版本，有什么命令可以查看吗？

**Comment by jeessy2** [comment]
嗯。接口问题，被拒绝了。不支持通过未修改的golang http请求。换个接口

**Comment by tomguan** [comment]
docker run -d --name ddns-go --restart=always -p 9876:9876 -v D:\Docker\server\ddns-go:/root --dns 114.114.114.114  jeessy/ddns-go:3.6.0
Unable to find image 'jeessy/ddns-go:3.6.0' locally
docker: Error response from daemon: manifest for jeessy/ddns-go:3.6.0 not found: manifest unknown: manifest unknown.
See 'docker run --help'.

貌似还没有最新的 docker镜像

**Comment by jeessy2** [comment]
版本在右上角。更新版本要把最后一个镜像删除，让docker重新下载。或者在docker 命令指定版本号v3.6.0

**Comment by jeessy2** [comment]
差一个v
v3.6.0

**Comment by tomguan** [comment]
> 

1、一切都正常了。docker 版本，我少打了 'v'。 
2、右上角也看到当前版本号了。
3、dns 更新也正常了。 真的太感谢了😄
