### ISSUE TITLE
阿里云通过接口获取失败

### ISSUE THREAD

**Issue by spanker008** [jeessy2/ddns-go#219]
使用的最新版本Linux 3.5.1_Linux_x86_64，返回状态码400

**Comment by jeessy2** [comment]
贴一个日志

**Comment by spanker008** [comment]
2022/04/03 21:40:39 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"9FCED3A9-D02F-5175-869F-4E700DA8D8E1","HostId":"alidns.aliyuncs.com","Code":"InvalidDomainName.Format","Message":"Invalid domain name.","Recommend":"https://troubleshoot.api.aliyun.com?q=InvalidDomainName.Format&product=Alidns"} ,返回状态码: 400

**Comment by spanker008** [comment]
2022/04/03 22:10:04 监听 :9876 ... 
2022/04/03 22:10:14 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"40B46513-9332-572F-8DDA-4C040E2758DB","HostId":"alidns.aliyuncs.com","Code":"QuotaExceeded.TTL","Message":"The specified TTL is invalid. A valid TTL must be in the range of 600 to 86400.","Recommend":"https://troubleshoot.api.aliyun.com?q=QuotaExceeded.TTL&product=Alidns"} ,返回状态码: 400

**Comment by spanker008** [comment]
不好意思，是我设置错误，现在一切正常了
