### ISSUE TITLE
默认获取 ipv6 的接口返回 403 了

### ISSUE THREAD

**Issue by equationl** [jeessy2/ddns-go#220]
我在自己电脑上访问这个接口 `https://api-ipv6.ip.sb/ip` 能够正常打开，但是挂载在群晖 dockers 上的日志一直显示无法获取地址：

![QQ截图20220403173624](https://user-images.githubusercontent.com/6501123/161421514-8f2e69d5-bf3a-486f-bea5-43d72e4e0921.png)

于是我用群晖访问了一下这个接口，发现返回的是 403：
![QQ截图20220403173648](https://user-images.githubusercontent.com/6501123/161421532-e82af134-162c-4d61-a562-4923ea58a0f7.png)

不知道是不是因为请求太频繁被这个接口拉黑了之类的？

但是之前已经稳定运行了三个月了也没出现问题啊，只是最近我在外面突然访问不了放家里面的 NAS 了，这次放假回家一看，才发现是从上周左右访问不了的。

想问一下，还有其他可用的接口吗...

**Comment by equationl** [comment]
尴尬了，刚发现可以直接通过网卡获取，我之前一直以为通过网卡获取不了

**Comment by jeessy2** [comment]
ipv6建议通过网卡获取。后面会支持从多个接口获取ip
