### ISSUE TITLE
希望能加个手动匹配网卡ipv6的功能。

### ISSUE THREAD

**Issue by yyxida** [jeessy2/ddns-go#223]
有些路由器下dhcpv6会在EUI64之外额外分配一个简单的ipv6地址，如xxxx:xxxx::700。这种地址有可能会被当作第一个优先选取，用ifconfig查出来这条不在第一个，也不知道为啥会被有优先，这种地址随机的不好加防火墙放行规则，所以希望能加一个用关键词匹配EUI64的ipv6地址功能。
凭网上找的资料和别的语言的经验改了一段，献丑了😂。
`		for _, netInterface := range ipv6 {
			if netInterface.Name == conf.Ipv6.NetInterface && len(netInterface.Address) > 0 {
				for i := 0; i < len(netInterface.Address); i++ {
					matched, err := regexp.MatchString(conf.Ipv6.macReg, netInterface.Address[i])
					if err != nil {
						log.Println("从网卡中正则匹配IPv6失败! 网卡名: ", conf.Ipv6.NetInterface)
					}
					if matched == true && err == nil {
						log.Println("正则表达式匹配成功!")
						return netInterface.Address[i]
					}
				}
				return netInterface.Address[0]
			}
		}
`

**Comment by yyxida** [comment]
> 多测下，直接PR

认证了我就继续挖坑了🤣，web就麻烦大佬了，这个真不会。

**Comment by tomguan** [comment]
😄老大们， 这里的 PR 是什么意思？

**Comment by yyxida** [comment]
> 😄老大们， 这里的 PR 是什么意思？

提交代码🤣

**Comment by yyxida** [comment]
#227

**Comment by laok133** [comment]
哈哈哈,支持大佬.我也很好奇 多个机器需要解析ipv6怎么办
