### ISSUE TITLE
在Windows下面执行安装失败

### ISSUE THREAD

**Issue by Hua-Fan-Yang** [jeessy2/ddns-go#226]
.\ddns-go.exe -s install
2022/04/05 21:44:40 安装 ddns-go 服务失败, ERR: Access is denied.

**Comment by jeessy2** [comment]
需要以管理员打开cmd

**Comment by nxuu** [comment]
mac版本的brew的 我也没安装成服务 也是提示禁止
安装 ddns-go 服务失败, ERR: open /Library/LaunchDaemons/ddns-go.plist: permission denied

**Comment by NekoYyang** [comment]
你这个貌似是没有sudo，提示没权限，sudo ./ddns_go install试试

**Comment by nxuu** [comment]
> 

我就是想用这个命令 安装成服务 结果不允许.mac好像不能安装sudo

**Comment by NekoYyang** [comment]
su 管理员名，然后在安装试试

**Comment by nxuu** [comment]
试了不行 我直接用sudo  看到是有sudo的
然后我尝试sudo ddns-go -s install 就安装成功了
我以前使用程序都是./ddns-go 
这次用brew安装 ./ddns-go就不行了 直接用ddns-go就可以了.
不知道为什么.

**Comment by WaterLemons2k** [comment]
> 试了不行 我直接用sudo 看到是有sudo的 然后我尝试sudo ddns-go -s install 就安装成功了 我以前使用程序都是./ddns-go 这次用brew安装 ./ddns-go就不行了 直接用ddns-go就可以了. 不知道为什么.

因为 brew 会将 ddns-go 安装到 `/usr/local/bin` 而非当前目录，所以需要使用 `sudo ddns-go -s install` 安装。
