### ISSUE TITLE
黑群晖的docker里部署的api方式获取不了ipv6地址

### ISSUE THREAD

**Issue by lovepaofu** [jeessy2/ddns-go#228]
版本是3.6.0，网卡获取的地址外网无法连通，之前一直使用的api的方式获取的ipv6地址，最近一直无法连通，看了看日志报无法获取ipv6地址，升级新版本ddns-go以后使用最新的api也不行，自己找了其他几个api也不管用，但是在浏览器访问时都是能正确返回v6地址的。
看别的用户用myip6.ipip.net可以，但我在群辉里curl http://myip6.ipip.net 返回的是ipv4地址，确定群晖是有v6地址的。很让人费解。

2022/04/06 10:09:01 连接失败! [点击查看接口能否返回IPv6地址](http://ip1.dynupdate6.no-ip.com/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:09:01 未能获取IPv6地址, 将不会更新
2022/04/06 10:14:01 连接失败! [点击查看接口能否返回IPv6地址](https://api6.ipify.org/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:14:01 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/04/06 10:14:01 连接失败! [点击查看接口能否返回IPv6地址](http://ip1.dynupdate6.no-ip.com/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:14:01 未能获取IPv6地址, 将不会更新
2022/04/06 10:19:01 连接失败! [点击查看接口能否返回IPv6地址](https://api6.ipify.org/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:19:01 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/04/06 10:19:01 连接失败! [点击查看接口能否返回IPv6地址](http://ip1.dynupdate6.no-ip.com/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:19:01 未能获取IPv6地址, 将不会更新
2022/04/06 10:24:01 连接失败! [点击查看接口能否返回IPv6地址](https://api6.ipify.org/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:24:02 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/04/06 10:24:02 连接失败! [点击查看接口能否返回IPv6地址](http://ip1.dynupdate6.no-ip.com/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:24:02 未能获取IPv6地址, 将不会更新
2022/04/06 10:29:02 连接失败! [点击查看接口能否返回IPv6地址](https://api6.ipify.org/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:29:02 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/04/06 10:29:02 连接失败! [点击查看接口能否返回IPv6地址](http://ip1.dynupdate6.no-ip.com/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:29:02 未能获取IPv6地址, 将不会更新
2022/04/06 10:34:02 连接失败! [点击查看接口能否返回IPv6地址](https://api6.ipify.org/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:34:02 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/04/06 10:34:02 连接失败! [点击查看接口能否返回IPv6地址](http://ip1.dynupdate6.no-ip.com/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:34:02 未能获取IPv6地址, 将不会更新
2022/04/06 10:39:02 连接失败! [点击查看接口能否返回IPv6地址](https://api6.ipify.org/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:39:02 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/04/06 10:39:02 连接失败! [点击查看接口能否返回IPv6地址](http://ip1.dynupdate6.no-ip.com/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:39:02 未能获取IPv6地址, 将不会更新
2022/04/06 10:44:02 连接失败! [点击查看接口能否返回IPv6地址](https://api6.ipify.org/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:44:02 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/04/06 10:44:02 连接失败! [点击查看接口能否返回IPv6地址](http://ip1.dynupdate6.no-ip.com/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:44:02 未能获取IPv6地址, 将不会更新
2022/04/06 10:49:02 连接失败! [点击查看接口能否返回IPv6地址](https://api6.ipify.org/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:49:02 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/04/06 10:49:02 连接失败! [点击查看接口能否返回IPv6地址](http://ip1.dynupdate6.no-ip.com/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:49:02 未能获取IPv6地址, 将不会更新
2022/04/06 10:54:02 连接失败! [点击查看接口能否返回IPv6地址](https://api6.ipify.org/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:54:03 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/04/06 10:54:03 连接失败! [点击查看接口能否返回IPv6地址](http://ip1.dynupdate6.no-ip.com/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:54:03 未能获取IPv6地址, 将不会更新
2022/04/06 10:59:03 连接失败! [点击查看接口能否返回IPv6地址](https://api6.ipify.org/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:59:03 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/04/06 10:59:03 连接失败! [点击查看接口能否返回IPv6地址](http://ip1.dynupdate6.no-ip.com/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 10:59:03 未能获取IPv6地址, 将不会更新
2022/04/06 11:04:03 连接失败! [点击查看接口能否返回IPv6地址](https://api6.ipify.org/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 11:04:03 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/04/06 11:04:03 连接失败! [点击查看接口能否返回IPv6地址](http://ip1.dynupdate6.no-ip.com/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 11:04:03 未能获取IPv6地址, 将不会更新
2022/04/06 11:09:03 连接失败! [点击查看接口能否返回IPv6地址](https://api6.ipify.org/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 11:09:03 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/04/06 11:09:03 连接失败! [点击查看接口能否返回IPv6地址](http://ip1.dynupdate6.no-ip.com/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/04/06 11:09:03 未能获取IPv6地址, 将不会更新

**Comment by jeessy2** [comment]
3.6.0支持多个接口。可以试下

**Comment by lovepaofu** [comment]
> 

我设置了多个接口，但是很奇怪，这些接口在电脑浏览器里访问都正常返回v6地址，但是配置到ddnsgo里以后就显示获取错误。
https://api6.ipify.org,https://myip6.ipip.net,http://ip1.dynupdate6.no-ip.com,https://v6.ident.me

**Comment by jeessy2** [comment]
群晖里勾选host模式没有？

**Comment by mathlife** [comment]
我是直接armbian里装docker镜像host模式，api也一样获取不到ipv6的地址，和楼主的日志一样，用网卡模式经常获取的是已经失效的IP

**Comment by jeessy2** [comment]
有些接口屏蔽了未修改的http请求.
进入容器通过curl请求看能请求莫

**Comment by mathlife** [comment]
进容器使用curl提示/bin/sh: curl: not found
不懂技术，不太明白怎么安装curl了

**Comment by mathlife** [comment]
宿主机上执行提示这样的
root@N1:~# curl https://speed.neu6.edu.cn/getIP.php
curl: (6) Could not resolve host: speed.neu6.edu.cn
root@N1:~# curl https://v6.ident.me
curl: (6) Could not resolve host: v6.ident.me
容器内按楼上的方法添加curl以后也这样报错
/app # curl https://speed.neu6.edu.cn/getIP.php
curl: (6) Could not resolve host: speed.neu6.edu.cn

直接ping可以通
root@N1:~# ping -6 2400:3200:baba::1
PING 2400:3200:baba::1(2400:3200:baba::1) 56 data bytes
64 bytes from 2400:3200:baba::1: icmp_seq=1 ttl=119 time=18.4 ms
64 bytes from 2400:3200:baba::1: icmp_seq=2 ttl=119 time=18.2 ms
64 bytes from 2400:3200:baba::1: icmp_seq=3 ttl=119 time=18.7 ms
64 bytes from 2400:3200:baba::1: icmp_seq=4 ttl=119 time=16.6 ms
64 bytes from 2400:3200:baba::1: icmp_seq=5 ttl=119 time=18.2 ms
64 bytes from 2400:3200:baba::1: icmp_seq=6 ttl=119 time=17.9 ms
64 bytes from 2400:3200:baba::1: icmp_seq=7 ttl=119 time=18.0 ms
64 bytes from 2400:3200:baba::1: icmp_seq=8 ttl=119 time=17.4 ms
64 bytes from 2400:3200:baba::1: icmp_seq=9 ttl=119 time=18.3 ms
64 bytes from 2400:3200:baba::1: icmp_seq=10 ttl=119 time=17.1 ms

**Comment by labulac** [comment]
> 宿主机上执行提示这样的
> 
> root@N1:~# curl https://speed.neu6.edu.cn/getIP.php
> 
> curl: (6) Could not resolve host: speed.neu6.edu.cn
> 
> root@N1:~# curl https://v6.ident.me
> 
> curl: (6) Could not resolve host: v6.ident.me
> 
> 容器内按楼上的方法添加curl以后也这样报错
> 
> /app # curl https://speed.neu6.edu.cn/getIP.php
> 
> curl: (6) Could not resolve host: speed.neu6.edu.cn
> 
> 
> 
> 直接ping可以通
> 
> root@N1:~# ping -6 2400:3200:baba::1
> 
> PING 2400:3200:baba::1(2400:3200:baba::1) 56 data bytes
> 
> 64 bytes from 2400:3200:baba::1: icmp_seq=1 ttl=119 time=18.4 ms
> 
> 64 bytes from 2400:3200:baba::1: icmp_seq=2 ttl=119 time=18.2 ms
> 
> 64 bytes from 2400:3200:baba::1: icmp_seq=3 ttl=119 time=18.7 ms
> 
> 64 bytes from 2400:3200:baba::1: icmp_seq=4 ttl=119 time=16.6 ms
> 
> 64 bytes from 2400:3200:baba::1: icmp_seq=5 ttl=119 time=18.2 ms
> 
> 64 bytes from 2400:3200:baba::1: icmp_seq=6 ttl=119 time=17.9 ms
> 
> 64 bytes from 2400:3200:baba::1: icmp_seq=7 ttl=119 time=18.0 ms
> 
> 64 bytes from 2400:3200:baba::1: icmp_seq=8 ttl=119 time=17.4 ms
> 
> 64 bytes from 2400:3200:baba::1: icmp_seq=9 ttl=119 time=18.3 ms
> 
> 64 bytes from 2400:3200:baba::1: icmp_seq=10 ttl=119 time=17.1 ms
> 
> 
> 
> 
> 
> 

1、宿主机上要添加dns解析 2、容器内要使用apk add curl添加curl命令

**Comment by mathlife** [comment]
> > 宿主机上执行提示这样的
> > root@N1:~# curl https://speed.neu6.edu.cn/getIP.php
> > curl: (6) Could not resolve host: speed.neu6.edu.cn
> > root@N1:~# curl https://v6.ident.me
> > curl: (6) Could not resolve host: v6.ident.me
> > 容器内按楼上的方法添加curl以后也这样报错
> > /app # curl https://speed.neu6.edu.cn/getIP.php
> > curl: (6) Could not resolve host: speed.neu6.edu.cn
> > 直接ping可以通
> > root@N1:~# ping -6 2400:3200:baba::1
> > PING 2400:3200:baba::1(2400:3200:baba::1) 56 data bytes
> > 64 bytes from 2400:3200:baba::1: icmp_seq=1 ttl=119 time=18.4 ms
> > 64 bytes from 2400:3200:baba::1: icmp_seq=2 ttl=119 time=18.2 ms
> > 64 bytes from 2400:3200:baba::1: icmp_seq=3 ttl=119 time=18.7 ms
> > 64 bytes from 2400:3200:baba::1: icmp_seq=4 ttl=119 time=16.6 ms
> > 64 bytes from 2400:3200:baba::1: icmp_seq=5 ttl=119 time=18.2 ms
> > 64 bytes from 2400:3200:baba::1: icmp_seq=6 ttl=119 time=17.9 ms
> > 64 bytes from 2400:3200:baba::1: icmp_seq=7 ttl=119 time=18.0 ms
> > 64 bytes from 2400:3200:baba::1: icmp_seq=8 ttl=119 time=17.4 ms
> > 64 bytes from 2400:3200:baba::1: icmp_seq=9 ttl=119 time=18.3 ms
> > 64 bytes from 2400:3200:baba::1: icmp_seq=10 ttl=119 time=17.1 ms
> 
> 1、宿主机上要添加dns解析 2、容器内要使用apk add curl添加curl命令

1宿主机上有配置ipv6DNS
# Generated by NetworkManager
search DHCP HOST
nameserver 192.168.123.2
nameserver 114.114.114.114
nameserver 2400:3200:baba::1
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver 2001:de4::101

2容器内已经按您提示的命令添加了curl

**Comment by labulac** [comment]
网关设置了没；网卡重启了没。   推荐N1直接上openwrt，armbian还是有不少的问题。op即刷即用，同样有docker

**Comment by mathlife** [comment]
> 网关设置了没；网卡重启了没。   推荐N1直接上openwrt，armbian还是有不少的问题。op即刷即用，同样有docker

网关设置了，网卡和设备都重启了。访问别的比如百度之类的倒是正常的，就是这些获取ip的接口网页都这报错

**Comment by lovepaofu** [comment]
> 有些接口屏蔽了未修改的http请求. 进入容器通过curl请求看能请求莫

勾选了host，在容器ssh中信息返回如下
*  subject: CN=myip6.ipip.net                                                   be'y
*  start date: Mar 10 00:00:00 2022 GMT                                         
*  expire date: Mar 10 23:59:59 2023 GMT                                        
*  subjectAltName: host "myip6.ipip.net" matched cert's "myip6.ipip.net"        
*  issuer: C=CN; O=TrustAsia Technologies, Inc.; CN=TrustAsia RSA DV TLS CA G2  
*  SSL certificate verify ok.                                                   
* Using HTTP2, server supports multiplexing                                     
* Connection state changed (HTTP/2 confirmed)                                   
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f939b57ba90)                               
> GET / HTTP/2                                                                  
> Host: myip6.ipip.net                                                          
> user-agent: curl/7.80.0                                                       
> accept: */*                                                                   
>                                                                               
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!                     
< HTTP/2 200                                                                    
< server: nginx                                                                 
< date: Thu, 07 Apr 2022 09:28:21 GMT                                           
< content-type: text/plain; charset=utf-8                                       
< content-length: 67                                                            
<                                                                               
当前 IP：112.0.151.62  来自于：中国 江苏 苏州  移动                             
* Connection #0 to host myip6.ipip.net left intact

**Comment by lovepaofu** [comment]
> > 网关设置了没；网卡重启了没。 >  >  > 推荐N1直接上openwrt，armbian还是有不少的问题。op即刷即用，同样有docker
> 
> 网关设置了，网卡和设备都重启了。访问别的比如百度之类的倒是正常的，就是这些获取ip的接口网页都这报错

我搞好了，打开群辉的网络设置里高高级设置的启用多网关只有，获取到ipv6网关地址以后就好了
<img width="825" alt="image" src="https://user-images.githubusercontent.com/18135785/162171976-3fd31da2-6202-4798-89f4-2e77e6f7e60c.png">

**Comment by jeessy2** [comment]
试试4.0.3版本
