### ISSUE TITLE
兄弟 能请教一下你个问题吗

### ISSUE THREAD

**Issue by MkMarko** [jeessy2/ddns-go#23]
为什么你的docker能这么小啊
一个Go环境应该不止这么小啊

**Comment by jeessy2** [comment]
运行环境不需要golang环境。最后打包成一个可执行包，使用alpine基础镜像。参考Dockerfile

**Comment by MkMarko** [comment]
噢噢 原来如此，因为golang已经编译完可执行了是吗？&nbsp;
因为我用PHP的，我写了一个PHP但是dockerfile编译出的镜像都特别大，最小都要100多M 有啥办法嘛？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jeessy2"<notifications@github.com&gt;; 
发送时间: 2021年1月5日(星期二) 晚上6:03
收件人: "jeessy2/ddns-go"<ddns-go@noreply.github.com&gt;; 
抄送: "M.K"<275535133@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jeessy2/ddns-go] 兄弟 能请教一下你个问题吗 (#23)





 
运行环境不需要golang环境。最后打包成一个可执行包，使用alpine基础镜像。参考Dockerfile

**Comment by jeessy2** [comment]
看下PHP有没有alpine镜像。我没用过PHP，你自己看下了

**Comment by MkMarko** [comment]
好的 谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jeessy2"<notifications@github.com&gt;; 
发送时间: 2021年1月5日(星期二) 晚上6:07
收件人: "jeessy2/ddns-go"<ddns-go@noreply.github.com&gt;; 
抄送: "M.K"<275535133@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jeessy2/ddns-go] 兄弟 能请教一下你个问题吗 (#23)





 
看下PHP有没有alpine镜像。我没用过PHP，你自己看下了
