### ISSUE TITLE
请问Webhook在返回失败后，支持多次重试？

### ISSUE THREAD

**Issue by cholinfu** [jeessy2/ddns-go#231]
我目前的使用情况是，路由器如果重启了，ddns使用内网的webhook发送消息至apple推送服务器（bark），因为路由器还没重启完成，内网webhook暂时还不具备访问互联网的条件，所以消息发送失败。请问ddns有重发的机制吗？谢谢

**Comment by jeessy2** [comment]
没有重发机制
