### ISSUE TITLE
能否指定获取某个网口的wan口IP地址？  

### ISSUE THREAD

**Issue by ErDongChen1973** [jeessy2/ddns-go#232]
如题，我的设备链接了不同的局域网，我想指定解析某个局域网wan口的IP地址，可以实现么？

**Comment by jeessy2** [comment]
路由器可以安装ddns-go可以通过网卡获取IP，如果不能安装需要指定静态路由

**Comment by ErDongChen1973** [comment]
> 路由器可以安装ddns-go可以通过网卡获取IP，如果不能安装需要指定静态路由

好的  谢谢！
