### ISSUE TITLE
Windows 重启后无法自动解析

### ISSUE THREAD

**Issue by Omoinemie** [jeessy2/ddns-go#237]
重启电脑后，工具无法获取到IPV6，但系统是有地址的，直接访问6.ipw.cn也能返回公网地址，必须进入配置网页，点一下保存，才能正常解析
![Snipaste_2022-04-14_11-39-37](https://user-images.githubusercontent.com/31991443/163309383-50a56bc2-1714-458c-b107-f588b984adbf.jpg)

**Comment by jeessy2** [comment]
用的什么系统，ddns-go的版本是多少

**Comment by Omoinemie** [comment]
系统win10 ltsc 2022 ，软件版本是最新版，我不晓得系统不登录软件是否在运行

**Comment by jeessy2** [comment]
是不是没登录系统，操作系统不用许请求？

**Comment by jeessy2** [comment]
刚测了windows server 2019重启能正常获取ip。 不知道是不是win10的什么原因造成的，可以多测下反馈（身边没有win10）
