### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by giodano0718** [jeessy2/ddns-go#238]
![image](https://user-images.githubusercontent.com/88591600/163333658-07acb49d-3c2c-45ce-8734-4176a0328624.png)
帮忙看一下这个问题怎么解决？从3.5.1到3.6.1都有这个问题，我是在软路由里运行DDNS-GO

另外DDNS-GO的开机自启工程要怎么开启？谢谢

**Comment by jeessy2** [comment]
下载对应CPU的版本，有可能是版本不对

**Comment by giodano0718** [comment]
确认了版本没问题，我下载的是ddns-go_3.6.1_Linux_x86_64.tar，然后我的软路由是J1900四LAN口的小主机,能在帮忙看看是什么问题吗？有时候ddns-go换个文件夹，比如从root下转移到根目录下面，又不会报错了。

**Comment by jeessy2** [comment]
直接在根目录运行的？一般没这么操作，我一般都放在一个子目录下面的

**Comment by jeessy2** [comment]
或者下一个386安装包试试

**Comment by giodano0718** [comment]
这个ISSUE可以关闭了，我这里找到解决该问题的办法了：我用的软路由固件安装完，需要给Overlay扩容，默认的软件包安装空间不足10M！
