### ISSUE TITLE
无法工作, 日志只会显示这些, 进程还在

### ISSUE THREAD

**Issue by pylist** [jeessy2/ddns-go#239]
![image](https://user-images.githubusercontent.com/52667561/163556957-56a78576-348f-4efa-a0c5-7cf42e62ef32.png)

**Comment by jeessy2** [comment]
你这样发，怎么分析啊。打开浏览器访问下页面，看什么错

**Comment by pylist** [comment]
> 你这样发，怎么分析啊。打开浏览器访问下页面，看什么错

是我配置文件名字写错了, 程序不报错, 我以为因为语言卡bug了
