### ISSUE TITLE
在host网络端口问题

### ISSUE THREAD

**Issue by satrom** [jeessy2/ddns-go#24]
阿里云和腾讯云的DDNS,因一个镜像只能设置一家的，我要用ipv6,选了host网络，这样要同时用两家的，我就要开二个镜像，但端口冲突只能运行一个，能否一个镜像同时设置多家（id和token分开保存），或开多个镜像（端口可以自定义）？

**Comment by jeessy2** [comment]
方案1. 你可以把域名转到同一个云下面，不用多开docker
方案2. docker中暂时不支持传参，马上增加

**Comment by satrom** [comment]
方案2的意思是什么? 多家参数共存，同时生效？

**Comment by jeessy2** [comment]
不是，多家共存改动大。方案二指的是多个容器。建议你用方案一

**Comment by satrom** [comment]
嗯，好的，如不用方案一，多个容器在host网络下，端口不冲突（共存），期待早日支持

**Comment by jeessy2** [comment]
2.3.0后支持, 使用前需要重新拉镜像
`docker run -d --name ddns-go --restart=always --net=host -v /opt/ddns-go:/root jeessy/ddns-go -l :9877 -f 600
`
