### ISSUE TITLE
cloudflare400错误

### ISSUE THREAD

**Issue by anglesccs** [jeessy2/ddns-go#240]
https://api.cloudflare.com/client/v4/zones?name=域名&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400

**Comment by jeessy2** [comment]
看说明是你生成的token不对

**Comment by anglesccs** [comment]
![捕获](https://user-images.githubusercontent.com/49857157/163819171-a89f5055-4b4e-4fa3-9cf8-f417668420c7.JPG)
这样了

**Comment by anglesccs** [comment]
![捕获](https://user-images.githubusercontent.com/49857157/163819429-a348944f-1d63-4eed-be95-90e2a9492039.JPG)
所有权限全开了

**Comment by jeessy2** [comment]
重新生成一个吧。这个看不出来

**Comment by anglesccs** [comment]
找到原因了，域名的问题，免费域名不让用API
