### ISSUE TITLE
Unraid中Docker安装Host模式取到的IPv6地址不是实际地址。

### ISSUE THREAD

**Issue by dengniweiyi** [jeessy2/ddns-go#243]
我的ifconfig后显示如下

> br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.31.17  netmask 255.255.255.0  broadcast 192.168.31.255
        inet6 2408:8256:10d1:4242:d435:79ff:fe3f:94e5  prefixlen 64  scopeid 0x0<global>
        inet6 2408:8256:10d1:4242::2f2  prefixlen 128  scopeid 0x0<global>
        inet6 fe80::d435:79ff:fe3f:94e5  prefixlen 64  scopeid 0x20<link>
        ether 00:f0:d2:d0:54:ad  txqueuelen 1000  (Ethernet)
        RX packets 1421026  bytes 1917281459 (1.7 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 412443  bytes 344088152 (328.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

以上，其中[2408:8256:10d1:4242::2f2]为公网可以访问到的地址，但是服务只取到[2408:8256:10d1:4242:d435:79ff:fe3f:94e5]，未取到2f2地址。这个该怎么处理？

另还想问一下，IPv6的正则表达式是怎样的规则？有例子可以学习吗？
谢谢大神了。

**Comment by dengniweiyi** [comment]
又测试了一下，64位前缀也是可以访问的，另还是想请教一下关于正则，有样例吗？

**Comment by jeessy2** [comment]
直接输入一个固定的值，重新获取IP不变的值。比如：ff

**Comment by dengniweiyi** [comment]
没明白，例如
2408:8256:10d1:4242:d435:79ff:fe3f:94e5
这组IP
2408:8256 是固定的
10d1:4242:d435:79ff:fe3f 是变化的
94e5 是固定的
那我该输入什么样的正则呢？

**Comment by jeessy2** [comment]
ff:fe就是固定的

**Comment by yyxida** [comment]
带有ff:fe的ip地址是客户端（Unraid）根据自身ip地址向路由器要来的地址（详细见EUI64）。
::2f2结尾的应该是路由器DHCPV6分配给设备的地址。因为隐私问题，设备常使用此ip连接互联网。
两者均为公网地址，请检查防火墙配置。
