### ISSUE TITLE
近期持续失败，提示“未能获取IPv6地址, 将不会更新”

### ISSUE THREAD

**Issue by qlin6gb** [jeessy2/ddns-go#244]
可能是4月16日开始，也可能是更早的日子开始，DDNS-go 开始无法更新 IPv6 记录。查看日志为持续提示“未能获取IPv6地址, 将不会更新”。

两家住户，位置北京市海淀区，分别是中国电信和中国移动的家庭光纤宽带，每家下面各有一台Windows 10  和一台 Windows Server 2019，用IPCONFIG  查看，都获取到了正常的 IPv6地址。Win10 的域名用阿里（万网）的，Server 2019 的域名用腾讯（DNSpod）的。

DDNS-go 版本 v3.4.1，仅启用 IPv6 的 DNS 更新，获取 IP  方式为通过接口获取，URL使用默认的https://api-ipv6.ip.sb/ip。DDNS-go 的日志连续显示“未能获取 IPv6 地址, 将不会更新”。但用浏览器访问 https://api-ipv6.ip.sb/ip ，则每次都可以看到返回的IPv6地址信息。4台Windows的情况相同。

然后在中国移动宽带上 Windows server 2019 做测试，将获取 IPv6 地址的URL更换为 https://v6.myip.la/json 并 save 后，看到日志立即显示成功更新了一次，但紧接着的30分钟里，6次检查，失败3次，日志为“未能获取IPv6地址, 将不会更新”，另外3次成功。再将 URL更换为 https://speed.neu6.edu.cn/getIP.php，连续6次检查全部成功。最后将 URL 换回 https://api-ipv6.ip.sb/ip ，6次检查，成功1次，失败5次。看来目前https://speed.neu6.edu.cn/getIP.php是最可靠的。

上述对比，貌似是默认 URL https://api-ipv6.ip.sb/ip 可靠性不佳，但是在浏览器上查看，每次都是成功的，所以有可能是 DDNS-go v3.4.1太娇气了，或timeout太短之类的情况。

目前我的解决办法是把获取IPv6的方式改为通过网卡获取，这样肯定保证每次都成功。Windows server 还好说，Windows 10 会启用临时 IPv6 地址，还需要用 netsh 禁止掉临时 IPv6 地址才行。

不知 v3.4.1 以后的版本是否已经改善了这个问题。

**Comment by jeessy2** [comment]
http.Client默认的User-Agent是“Go-http-client/1.1”

ip.sb应该是通过这个拒绝访问了。其他接口没发现

**Comment by jeessy2** [comment]
3.6.0后支持多个接口地址。可以升级到这个版本之后的。一个不可用，另外一个还可以接替

**Comment by lidawei97688** [comment]
之前的那个python语言写的ddns（现已被github封禁），在获取ipv6那里填写default的话是默认从网卡获取本机上网临时ipv6地址，而ddns-go选择从网卡获取ipv6地址则是获取那个固定ipv6地址
