### ISSUE TITLE
阿里云DNS更新失败

### ISSUE THREAD

**Issue by st7yws** [jeessy2/ddns-go#245]
> 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"16E2F7D1-B96B-5985-83D5-CB4C0B3DA108","HostId":"alidns.aliyuncs.com","Code":"InvalidDomainName.Format","Message":"Invalid domain name.","Recommend":"https://troubleshoot.api.aliyun.com?q=InvalidDomainName.Format&product=Alidns"} ,返回状态码: 400

**Comment by magickio** [comment]
请问这个问题你是怎么解决的，这两天突然这样，我查了好久没找到
