### ISSUE TITLE
似乎有个BUG，提示IP没有变化还调接口更新解析

### ISSUE THREAD

**Issue by li-xunhuan** [jeessy2/ddns-go#25]
日志如图所示
![1611610287341_ pic_hd](https://user-images.githubusercontent.com/10476982/104125106-99c22b80-538f-11eb-81fb-5f21ce2bfbe6.jpg)

**Comment by jeessy2** [comment]
是一个域名还是多个域名。

**Comment by li-xunhuan** [comment]
> 是一个域名还是多个域名。

单个域名，IPv6

**Comment by jeessy2** [comment]
你登陆下阿里云账号看下，一个域名下有二个IPv6地址？

**Comment by li-xunhuan** [comment]
卧槽，还真有，怎么做到的？？

**Comment by jeessy2** [comment]
是不是使用ddns-go后新增后，然后手动又加一条？

**Comment by li-xunhuan** [comment]
> 是不是使用ddns-go后新增后，然后手动又加一条？

又没动过这个，好久没动过它了！

**Comment by jeessy2** [comment]
那你在看下有没有可能的
本程序不会出现新增多条的。

**Comment by li-xunhuan** [comment]
> 那你在看下有没有可能的
> 本程序不会出现新增多条的。

再观察观察，再出现再说！

**Comment by jeessy2** [comment]
ok
