### ISSUE TITLE
通过接口获取的ipv6不通

### ISSUE THREAD

**Issue by Omoinemie** [jeessy2/ddns-go#261]
网卡上有两个IPv6地址，只有临时地址是通的，但脚本获取的地址的上面那个地
![Snipaste_2022-05-09_17-03-35](https://user-images.githubusercontent.com/31991443/167377962-d4a8279f-28f4-47f0-8e26-96e17fe7dadc.jpg)
址

**Comment by jeessy2** [comment]
建议通过接口获取，一般就是临时的地址

网卡获取可以使用正则表达式匹配

**Comment by StefanLuo** [comment]
大佬，ipv6正则表达式可以给个示例吗？
