### ISSUE TITLE
通过 https://myip.ipip.net  获取ipv4 异常

### ISSUE THREAD

**Issue by calibura** [jeessy2/ddns-go#266]
网址正常访问，ddns却不行

**Comment by HughRyu** [comment]
一样,三个默认解析DDNS地址都不行.
手动在威联通ssh后curl 
https://myip4.ipip.net
https://ddns.oray.com/checkip
是可以解析的,3322那个因为https证书问题无法解析.

**Comment by jeessy2** [comment]
> 一样,三个默认解析DDNS地址都不行. 手动在威联通ssh后curl https://myip4.ipip.net https://ddns.oray.com/checkip 是可以解析的,3322那个因为https证书问题无法解析.

ddns-go版本是多少，更新频率是多少
