### ISSUE TITLE
请问windows下能不能设置配置文件在当前目录（exe所在目录）

### ISSUE THREAD

**Issue by Curious-r** [jeessy2/ddns-go#268]
这样重装系统就不会丢失配置了

**Comment by jeessy2** [comment]
首页有相关说明的。

[可选] 安装服务
Mac/Linux: sudo ./ddns-go -s install
Win(以管理员打开cmd): .\ddns-go.exe -s install
安装服务也支持 -l监听地址 -f同步间隔时间(秒) -c自定义配置文件路径

**Comment by Curious-r** [comment]
> 

好的，感谢回复。不好意思没看清文档里这部分。
