### ISSUE TITLE
IP获取的问题

### ISSUE THREAD

**Issue by CanonKQ** [jeessy2/ddns-go#27]
openwrt开了ssrp，获取到的IP成了代理的了，怎么解决啊大佬

**Comment by CanonKQ** [comment]
也不是代理的是个119开头的IP，咋搞的

**Comment by jeessy2** [comment]
ssrp是啥不清楚了。参考原理来：提供了几个接口地址，浏览器访问下那个对的就用那个

**Comment by jeessy2** [comment]
还要看下你拨号的路由器获取的公网是不是100开头的ip。是的话，你只有用IPv6了

**Comment by CanonKQ** [comment]
ssr代理

**Comment by CanonKQ** [comment]
公网ip是27开头，代理节点是119开头，ddns获取的IP是openwrt代理的IP不是主路由的

**Comment by jeessy2** [comment]
https://api-ipv4.ip.sb/ip
https://myip.ipip.net
https://ddns.oray.com/checkip

**Comment by CanonKQ** [comment]
解决了大佬，让解析域名直连了
