### ISSUE TITLE
ddns-go和宝塔冲突

### ISSUE THREAD

**Issue by gzxief** [jeessy2/ddns-go#270]
在arm盒子里，armbian22.05 bullseye安装宝塔，无法打开ddns-go,不管是docker还是直接部署

**Comment by jeessy2** [comment]
贴日志

**Comment by gzxief** [comment]
我无法登录IP:9876，docker logs ddns-go 就提示等待10秒进入

**Comment by jeessy2** [comment]
说明启动了。检查端口打开没有

**Comment by gzxief** [comment]
如何修改端口，我指向 -p 1234：9876，也无法打开

**Comment by jeessy2** [comment]
是不是防火墙开了

**Comment by gzxief** [comment]
感谢
