### ISSUE TITLE
win无法更改同步间隔时间

### ISSUE THREAD

**Issue by jun1111233** [jeessy2/ddns-go#271]
再使用.\ddns-go.exe -s install安装完服务后 我尝试.\ddns-go.exe -f 3600 来更改同步间隔时间，但并没有效果 还是原来的300秒 是使用的命令错误了吗？纯小白求指导

**Comment by jeessy2** [comment]
卸载后重新安装服务

**Comment by jun1111233** [comment]
> 卸载后重新安装服务
没有安装服务的话是有效果的 但安装服务后再输入.\ddns-go.exe -f 3600就显示
2022/05/14 22:20:52 监听 :9876 ...
2022/05/14 22:20:52 第一次运行将等待 20 秒后运行 (等待网络)
2022/05/14 22:20:52 启动端口发生异常, 请检查端口是否被占用 listen tcp :9876: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by jeessy2** [comment]
服务运行了，终端又运行了。难道不是运行二个程序了[抹汗]

**Comment by jun1111233** [comment]
> 服务运行了，终端又运行了。难道不是运行二个程序了[抹汗]

是的所以想问下服务的更新间隔时间应该用什么命令

**Comment by jeessy2** [comment]
首页有说明自己看下
