### ISSUE TITLE
IPv6地址已获取，但是使用域名无法访问

### ISSUE THREAD

**Issue by AlexQlynn** [jeessy2/ddns-go#272]
各位大佬，
我只有IPv6公网地址，使用阿里云解析，已经获取地址，如下
![屏幕截图 2022-05-14 230041](https://user-images.githubusercontent.com/73543630/168432466-cd308837-1a55-4633-b2cd-612b5fc882bb.jpg)
我的环境是威联通5.0版本，docker安装。
但是浏览器域名就是无法访问，不知道从何排查起，还请各位大佬赐教。

**Comment by AlexQlynn** [comment]
![屏幕截图 2022-05-14 230930](https://user-images.githubusercontent.com/73543630/168433399-dd347c2f-a389-4262-b633-28f636b7407e.jpg)

**Comment by jeessy2** [comment]
检查防火墙之类的，利用ping6等工具自行检查一下

**Comment by AlexQlynn** [comment]
解决了，我的梯子路由没白名单....
