### ISSUE TITLE
centos无法获取ipv6

### ISSUE THREAD

**Issue by zwsn** [jeessy2/ddns-go#277]
centos系统物理机,ipv6已开启,但是通过接口获取不到ipv6,使用网卡显示没有找到可用的网卡.希望解答.同网络下的windows使用ddns-go正常.
使用ifconfig可以查看到已获取的ipv6地址:
<img width="745" alt="image" src="https://user-images.githubusercontent.com/42889307/168851969-06a8f783-5b72-40e5-90f7-8a21edac1d09.png">
ping6 localhost也通
<img width="626" alt="image" src="https://user-images.githubusercontent.com/42889307/168852512-f42593b3-5cd3-4b20-943d-9f66efd9813f.png">
网页端显示结果:
<img width="1883" alt="image" src="https://user-images.githubusercontent.com/42889307/168852918-2b18e80b-8230-44e8-ab64-81362639baba.png">

**Comment by jeessy2** [comment]
应该是你系统问题。自己检查一下，帮不上什么忙

**Comment by zwsn** [comment]
好的,感谢回复

**Comment by TheJan-Jan** [comment]
你的路由器的问题，系统优先识别ipv4
