### ISSUE TITLE
请问能否添加一个环境变量用来挂载配置文件

### ISSUE THREAD

**Issue by tecsar9000** [jeessy2/ddns-go#278]
用非root用户启动发现无法读取配置文件来着

**Comment by jeessy2** [comment]
首页有说明，你们都不看的么

**Comment by tecsar9000** [comment]
不好意思，因为用的docker compose，所以看到没提environment第一反应就以为没有..... 现在在compose里加了一句command: -c /usr/local/ddns-go.yaml就好了
