### ISSUE TITLE
提个建议吧

### ISSUE THREAD

**Issue by hopana** [jeessy2/ddns-go#279]
群晖套件配置页可以设置是否开启外网访问，我没有开启。
但是，没有开启的情况下，每次点击套件图标，仍然是用群晖默认域名去访问的，比如我的：xxx.fun:9876
但是，这是访问不通的（禁用了外网访问），所以每次我得手动把 xxx.fun.9876 改成内网访问地址 192.168.x.x:9876

因此，能不能提供一个配置，设置默认访问地址（也就是群晖套件图标点击后打开的页面地址）
这样就方便多了，使用起来体验就好多了！

最后，作者辛苦了，感谢~

**Comment by jeessy2** [comment]
把快捷方式的链接地址改成内网地址，不使用域名

**Comment by hopana** [comment]
> 

你的意思是现在就可以改吗？群晖是不支持直接改快捷方式链接的吧？

**Comment by jeessy2** [comment]
创建的时候就修改
![截屏2022-05-23 下午6 37 44](https://user-images.githubusercontent.com/6205259/169801677-277e7ac3-c3f8-4982-ac65-e45ed4828767.png)

**Comment by hopana** [comment]
> 创建的时候就修改 ![截屏2022-05-23 下午6 38 41](https://user-images.githubusercontent.com/6205259/169801844-82a6de1b-5c66-4841-a252-a400e6cc98b1.png)

哈哈哈，我是用别人打包好的套件安装的。。。。那我换成docker方式吧

**Comment by jeessy2** [comment]
ok
