### ISSUE TITLE
华为云解析失败

### ISSUE THREAD

**Issue by ycb2516** [jeessy2/ddns-go#282]
华为云解析ipv4和ipv6均出错，2022/05/23 21:13:19 连接失败! [点击查看接口能否返回IPv4地址](https://myip4.ipip.net/),
2022/05/23 21:13:19 未能获取IPv4地址, 将不会更新
2022/05/23 21:13:29 请求接口https://dns.myhuaweicloud.com/v2/recordsets?type=AAAA&name=www.xxxxxxxxxxxxxx.top失败! ERROR: Get "https://dns.myhuaweicloud.com/v2/recordsets?name=www.xxxxxxxxx.top&type=AAAA": dial tcp: i/o timeout，通过给定接口查询是APIGW.0301错误值，华为云给出解决方案https://support.huaweicloud.com/devg-apisign/api-sign-0001.html，奈何自己小白，只能请大大解决了

**Comment by jeessy2** [comment]
看上去是你网络问题

**Comment by ycb2516** [comment]
> 看上去是你网络问题

刚才重新换了一个路由器就没问题了，不知道是路由器 哪里设置的原因……
