### ISSUE TITLE
能否增加google domain的接口支持

### ISSUE THREAD

**Issue by WangJiyuanYo** [jeessy2/ddns-go#283]
从阿里云换到Google Domain，大佬可以增加下Google Domain的支持嘛

**Comment by jeessy2** [comment]
没有计划。服务商太多了，有几个常用的就可以了。
ps: 可以把域名的dns转到支持的服务商进行解析

**Comment by swzsweet** [comment]
求个Google Domain支持

**Comment by yin1999** [comment]
我按Google Domain的文档写了一下，但我没有在Google Domain上购买域名，可以测试一下是否可用：https://github.com/yin1999/ddns-go/tree/support-google-domain

动态域名解析说明文档：https://support.google.com/domains/answer/6147083?hl=zh-Hans#zippy=%2C%E4%BD%BF%E7%94%A8-api-%E6%9B%B4%E6%96%B0%E6%82%A8%E7%9A%84%E5%8A%A8%E6%80%81-dns-%E8%AE%B0%E5%BD%95

**Comment by swzsweet** [comment]
> 

你的这个分支要怎么安装

**Comment by swzsweet** [comment]
> 我按Google Domain的文档写了一下，但我没有在Google Domain上购买域名，可以测试一下是否可用：https://github.com/yin1999/ddns-go/tree/support-google-domain
> 
> 动态域名解析说明文档：https://support.google.com/domains/answer/6147083?hl=zh-Hans#zippy=%2C%E4%BD%BF%E7%94%A8-api-%E6%9B%B4%E6%96%B0%E6%82%A8%E7%9A%84%E5%8A%A8%E6%80%81-dns-%E8%AE%B0%E5%BD%95

请问 您的这个分支要怎么安装

**Comment by yin1999** [comment]
> 请问 您的这个分支要怎么安装

请问你是什么操作系统，我单独编译一个二进制文件，你测试一下
