### ISSUE TITLE
IPV6 ::20格式的不会更新

### ISSUE THREAD

**Issue by Aitain** [jeessy2/ddns-go#285]
你好，请问  当IPV6 ::20格式  使用网卡获取  显示没有找到可用的网卡 ；  而使用接口获取   在ddns里面并不会有::20格式的ipv6更新  ，仍然是之前过时的v6地址 这应该怎么解决。

**Comment by jeessy2** [comment]
能描述清楚一点么？实在看不明白

**Comment by Aitain** [comment]
> 能清楚吗？ 实际看描述不明白一点

就是 比如说我的ipv6地址之前都是CDCD:910A:2222:5498:8475:1111:3900:2020 如今因为某些原因 ipv6的地址变成了CDCD:910A:2222::22 。。 在ddns-go中 ipv6的设置是通过网卡获得 而CDCD:910A:2222::22 这个地址就是显示没有可用的网卡 使用接口获得 ， 就比如https://api-ipv6.ip.sb/ip 这个 在浏览器打开可以显示 这个::22的地址 但是 在域名那没有更新 ::22 的这个地址

**Comment by jeessy2** [comment]
如果网卡获取，显示无网卡，说明IP不正常或没有IPv6地址

**Comment by jeessy2** [comment]
ip.sb拦截了一些请求。#244

把安装文件替换就可以

**Comment by jeessy2** [comment]
ip.sb拦截了一些请求。#244

把安装文件替换就可以

**Comment by Aitain** [comment]
> ip.sb拦截了一些请求。#244
> 
> 把安装文件替换就可以
  万分感谢！

**Comment by Aitain** [comment]
> ip.sb拦截了一些请求。#244
> 
> 把安装文件替换就可以


好的  ，万分感谢！
