### ISSUE TITLE
百度域名ipv6接口报错

### ISSUE THREAD

**Issue by ymrzs** [jeessy2/ddns-go#287]
百度云的域名，用ipv6的话接口会报错
![ddns-go百度云ipv6](https://user-images.githubusercontent.com/105834464/170721559-c5b9c8c7-61f6-4ee8-8656-160867958e65.jpg)

**Comment by jeessy2** [comment]
请@WinterBokeh看下

**Comment by WinterBokeh** [comment]
@ymrzs 请再测试一下？是百度云的api出问题了，已提交工单解决。我这边来看已经恢复了。
<img width="695" alt="image" src="https://user-images.githubusercontent.com/39732766/170939789-87772e9b-3209-4dcb-a474-3cb89aef7432.png">

**Comment by ymrzs** [comment]
@WinterBokeh 嗯，是百度api问题，之前必须大写

**Comment by ymrzs** [comment]
已经ok了
