### ISSUE TITLE
阿里云无法正常解析ip

### ISSUE THREAD

**Issue by huangwb8** [jeessy2/ddns-go#288]
## 问题描述
- 2022-5-28早上8点之后出现ip无法正常解析至阿里云后台

## 是否已搜索同类问题
- [ ] 已搜索未能解决

## 环境
- 操作系统: Linux openmediavault 5.4.174-2-pve #1 SMP PVE 5.4.174-2 (Thu, 10 Mar 2022 15:58:44 +0100) x86_64 GNU/Linux
- ddns-go版本: latest
- 安装方式: docker

## 报错

类似于：

```
2022/05/28 10:50:33 请求接口https://alidns.aliyuncs.com/失败! ERROR: Get "https://alidns.aliyuncs.com/?AccessKeyId=*******&Action=DescribeSubDomainRecords&Format=JSON&Signature=***&SignatureMethod=HMAC-SHA1&SignatureNonce=***&SignatureVersion=1.0&SubDomain=***&Timestamp=2022-05-28T02%3A50%3A33Z&Type=A&Version=2015-01-09": EOF
```

我并未更新token。今天早上7点多的时候还是正常的。

**Comment by jeessy2** [comment]
观察下还报错不。有可能是网络问题或阿里云的问题

**Comment by huangwb8** [comment]
@jeessy2 
谢谢您的指示。
经查，与clash的proxy节点不可用有关，已经更换新节点。目前正常。与DDNS-GO没有关系。
