### ISSUE TITLE
求助:群晖docker下ddns-go,无法获取IPV6的地址,用的是cloudflare

### ISSUE THREAD

**Issue by hy817120** [jeessy2/ddns-go#290]
## 问题描述
我是用的pvE下装的黑群晖然后装docker,docker下装的ddns-go,    ipv6通过接口获取出现下面的报错
但是打开https://myip6.ipip.net, https://speed.neu6.edu.cn/getIP.php, https://v6.ident.me,是可以获取IPV6的地址,
昨天刚装上的时候一直可以用, 就一直没有没用改动, 突然就开始报错,
我cloudflare以及Token一切都是正确的不知道到底是什么原因,
单独打开https://myip6.ipip.net, https://speed.neu6.edu.cn/getIP.php, https://v6.ident.me,是可以获取ipv6的公网地址,
而且昨天一直都正常,突然就不正常了,并没有改过文件.
2022/05/29 08:27:48 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/05/29 08:27:48 连接失败! [点击查看接口能否返回IPv6地址](https://speed.neu6.edu.cn/getIP.php), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/05/29 08:27:48 连接失败! [点击查看接口能否返回IPv6地址](https://v6.ident.me/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/05/29 08:27:48 未能获取IPv6地址, 将不会更新

**Comment by jeessy2** [comment]
检查下群晖网络。
进入docker中通过curl https://myip6.ipip.net 能返回结果吗

**Comment by hy817120** [comment]
> 检查下群晖网络。通过curl [https://myip6.ip.net](https://myip6.ipip.net) 进入docker中能返回结果吗？[](https://myip6.ipip.net)

可以的,一切设置都是正常的,就是不知道什么原因我怀疑是我没有绑定顶级域名,因为我是直接绑定的二级域名,在另外一款脚本上开始也是只绑定了二级域名,出现报错,最后把顶级域名绑定上,就恢复正常了, 现在已经达到了我想要的结果, 等我再测试一下ddns-go是不是也是这种情况,到时候再反馈, 感谢作者的回复.

**Comment by QASDJKL5** [comment]
群晖的套件中心里有ddns-go的套件，搞个矿神套件源下载直接用，没必要用docker

**Comment by hy817120** [comment]
群晖套件版测了几天,发现没有问题, docker不知道是什么原因, 感谢作者的回复.
