### ISSUE TITLE
能不能配置一下快捷方式打开地址呢？

### ISSUE THREAD

**Issue by hopana** [jeessy2/ddns-go#291]
如果已经设置了禁止外网访问，但是桌面快捷方式默认依然是用域名访问的。
这导致禁用外网访问会导致桌面快捷方式失效，每次要手动更改成内网地址才能访问！

能不能增加一个配置默认打开地址的配置项呢，Docker版是有这个配置的。
这样会方便很多，不会每次都要手动输入内网地址访问！

**Comment by jeessy2** [comment]
你说的群晖套件吧。这个第三方爱好者搞得，可以和他沟通下
