### ISSUE TITLE
如果同一个域名设置了国内国外两条线路不同解析，更新时会替换两条线路配置为默认线路，更新完后两条配置记录会一模一样

### ISSUE THREAD

**Issue by qysaber** [jeessy2/ddns-go#293]
## 问题描述
- 如果同一个域名设置了国内国外两条线路不同解析，更新时会替换两条线路配置为默认线路，更新完后两条配置记录会一模一样，是否可以后续更新版本然后支持参数设置来实现修改特定记录

## 是否已搜索同类问题
- [ ] 已搜索未能解决

## 环境
- 操作系统: windows
- ddns-go版本: 3.7.1
- 安装方式: 服务

## 截图
![image](https://user-images.githubusercontent.com/29822089/171540737-11774626-80cc-4b18-8a8e-a69e5938e4c9.png)

**Comment by jeessy2** [comment]
没有计划支持

**Comment by walkxspace** [comment]
和我提的 #189 感觉是一个需求😂

**Comment by whx1024** [comment]
试试这个https://github.com/jeessy2/ddns-go/pull/319

**Comment by jeessy2** [comment]
4.0.0后支持，欢迎尝鲜
