### ISSUE TITLE
建议:通过接口获取IP增加多个来源

### ISSUE THREAD

**Issue by hjkl950217** [jeessy2/ddns-go#295]
建议IP获取方式-接口这种,可以配置多个。

虽然目前既支持json又支持普通文本，但是不同的网站有时会有一些限制或是国内某些原因失效，建议可以配置多个获取IP的API。

形式： 文本框，一行代表一个API。

同时建议可以增加一个备选： https://ipv6.renfei.net/

**Comment by jeessy2** [comment]
v3.6.0以后已经支持了

**Comment by hjkl950217** [comment]
看到了 感谢。。。`支持多个接口, 使用半角逗号分隔`
