### ISSUE TITLE
Please complete the project description with support for Baidu

### ISSUE THREAD

**Issue by WinterBokeh** [jeessy2/ddns-go#296]
<img width="732" alt="image" src="https://user-images.githubusercontent.com/39732766/172104192-09075c99-48cd-4fd4-a7c8-5a40341dea83.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/39732766/172104283-9e6843d4-9191-4a23-a6ac-0b87ac9ce836.png">

**Comment by jeessy2** [comment]
fixed
