### ISSUE TITLE
解析的，主机记录可否有@改成www,因为@好多人只能局域网，外网用不了，WWW就行

### ISSUE THREAD

**Issue by lhg0318** [jeessy2/ddns-go#297]
解析的，主机记录可否有@改成www,因为@好多人只能局域网，外网用不了，WWW就行

![Uploading 微信图片_20220609103718.jpg…]()

**Comment by lhg0318** [comment]
![未标题-1](https://user-images.githubusercontent.com/33344183/172752750-24f85843-4168-43af-98fd-39b536e9b5bd.jpg)

**Comment by lhg0318** [comment]
![微信图片_20220609103718](https://user-images.githubusercontent.com/33344183/172752783-87a6d9da-a98f-4be6-9797-4e60266ca2d9.jpg)

**Comment by jeessy2** [comment]
你有www开头的，所以能访问。@的意思指example.com这个域名。

**Comment by lhg0318** [comment]
后面2个是我手动添加的

**Comment by jeessy2** [comment]
那看不明白你是什么意思了
