### ISSUE TITLE
win10 无法通过网卡获取ipv6

### ISSUE THREAD

**Issue by diaoseo** [jeessy2/ddns-go#298]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
win10 无法通过网卡获取到ipv6地址
选取网卡获取下方提示没有找到可用网卡
## 是否已搜索同类问题
- [x ] 已搜索未能解决
- [ ] 未搜索

## 环境
- 操作系统: windows 10
- ddns-go版本: 3.7.1
- 安装方式: win任务计划启动

## 截图
![image](https://user-images.githubusercontent.com/36965008/173179605-09a5e2b3-da12-493a-8455-a0dfebc92364.png)

**Comment by jeessy2** [comment]
检查网络，没有匹配到合适的IPv6地址

**Comment by diaoseo** [comment]
> 检查网络，没有匹配到合适的IPv6地址

使用接口获取能获取到，可是每次接口都要请求出去。有时候api并不一定能获取。刚刚重启了一次路由器，其他设备几分钟内就上线了，接口获取的过去了一小时才获取成功

**Comment by diaoseo** [comment]
> 检查网络，没有匹配到合适的IPv6地址

![image](https://user-images.githubusercontent.com/36965008/173182364-d3697782-6367-4071-bdd9-d5657069cc4d.png)

**Comment by jeessy2** [comment]
应该是网络问题。自行检查一下吧

**Comment by diaoseo** [comment]
> 应该是网络问题。自行检查一下吧

网络问题根本不是重点啊，网是很稳定的。且当网络问题。我的网卡都没有是什么情况呢。没有可用的网卡，下面的解释成功不是侧面证明我有v6吗，可是网卡都识别不出来和我的网络应该没关系吧。

**Comment by diaoseo** [comment]
![image](https://user-images.githubusercontent.com/36965008/173186185-767f97e3-05cb-49fa-983e-80ea39046fff.png)

**Comment by jeessy2** [comment]
试下3.7.2，不知道你的这个问题是不是同#300

**Comment by diaoseo** [comment]
> 试下3.7.2，不知道你的这个问题是不是同#300

已解决
