### ISSUE TITLE
ubuntu18.06无法获取ipv6网卡

### ISSUE THREAD

**Issue by liuhrme** [jeessy2/ddns-go#300]
![image](https://user-images.githubusercontent.com/102905159/173477872-c9726dcf-47c6-4a95-a017-5242136acb87.png)
![image](https://user-images.githubusercontent.com/102905159/173477986-c8212a06-01c2-4f56-b0d3-bd954d6e0036.png)

**Comment by jeessy2** [comment]
prefixlen为128。所以没找到

**Comment by liuhrme** [comment]
那请问这个不支持吗？虽然他是128位地址，但也属于公网地址，后续会升级支持吗？

**Comment by jeessy2** [comment]
外网能访问这个地址？

**Comment by liuhrme** [comment]
没有任何问题的啊，我通过这个地址使用的！
![image](https://user-images.githubusercontent.com/102905159/173480383-87eb4bfe-b183-4ca3-abab-0b637ab1821e.png)

**Comment by jeessy2** [comment]
通过接口能获取这个v6地址否

**Comment by liuhrme** [comment]
dns-go日志显示无法获取，我如何通过其他方式测试。v6地址没有问题，下图为ping公共dns测试图片。
![image](https://user-images.githubusercontent.com/102905159/173482788-b8c074b0-4423-4ba5-9092-e8df568de546.png)
![image](https://user-images.githubusercontent.com/102905159/173482840-24f718ef-af11-4a67-9706-2472595085a1.png)

**Comment by liuhrme** [comment]
我确认可以正常访问IPV6地址，请问是否与DNS相关，因为我v6地址没有配置IPV6的DNS。

**Comment by jeessy2** [comment]
v4的dns也可以返回v6的地址

**Comment by loryncien** [comment]
docker 使用，群晖升级到7.1-up1，发现也不能通过**网卡**获得 IPv6，同样显示「没有找到可用网卡」，能通过**接口**获得，并外网正常使用，之前群晖 6.2.3 两种方式都可以获得。

将虚拟机卸了把网卡`ovs_eth0` 还原为`eth0` 也不行；搜索关闭问题，打开群晖网络「启用多网关」的方案也不行。
试了下之前的版本，如v3.5.1 v3.4.1 也不行。

![iShot_2022-06-14_14 17 36-tuya](https://user-images.githubusercontent.com/9330590/173506916-25a6e86d-5f88-416e-a372-af2f3ddfcf36.png)

**Comment by jeessy2** [comment]
通过网卡获取是过滤了128位的，如果能通过4G/5G信号能访问，就放开

**Comment by liuhrme** [comment]
确认可以访问，且4G/5G下发的v6地址也是128位，期待下个版本放开。

**Comment by loryncien** [comment]
> 你会编译go代码不? 如果会的话，克隆 https://github.com/jeessy2/ddns-go/tree/prefixlen128 这个分支试下，我这里没有前缀128位的

搜了下编译教程，按着编译了一下 docker文件，好像能行了
![iShot_2022-06-14_17 47 19-tuya](https://user-images.githubusercontent.com/9330590/173548348-a96cf1b6-b54b-4278-b588-1e644724b53e.png)

**Comment by liuhrme** [comment]
不会，楼上的大哥可以出个简单的教程吗？或者将来有计划更新放开128位地址吗？
