### ISSUE TITLE
请问是否会考虑增加解析数量

### ISSUE THREAD

**Issue by liuhrme** [jeessy2/ddns-go#302]
首先感谢更新至3.72，现在能正常使用了。

当系统存在多个网卡需要解析时，当前应用没办法做到，只能单网卡解析至多域名，或开启多个docker桥接至不同网卡来做到这样的需求，管理起来也不太方便。

**Comment by jeessy2** [comment]
ddns-go只考虑简单、实用的功能需求。类似这种暂不考虑
