### ISSUE TITLE
cloudflare 解析问题

### ISSUE THREAD

**Issue by qingmuhy** [jeessy2/ddns-go#303]
## 问题描述
- 之前是正常使用的，我怀疑可能是网络出问题了。有啥排错思路不。

## 是否已搜索同类问题
- [x ] 已搜索未能解决
- [ ] 未搜索

## 环境
- 操作系统: 威联通QTS
- ddns-go版本: 3.72
- 安装方式: docker

报错信息：
`2022/06/15 09:35:56 监听 :9876 ...
2022/06/15 09:35:57 第一次运行将等待 10 秒后运行 (等待网络)
2022/06/15 09:36:07 请求接口https://api.cloudflare.com/client/v4/zones?name=*****.com&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=*****.com&status=active&per_page=50": dial tcp: lookup api.cloudflare.com on 10.0.3.1:53: read udp 10.0.3.1:58292->10.0.3.1:53: read: connection refused`

**Comment by jeessy2** [comment]
这个自行看下报错信息就知道了，DNS 10.0.3.1有问题。

**Comment by HughRyu** [comment]
楼主解决了嘛？
我也是突然前两天就报错了,更新最新版也白扯.我的的是阿里云,报错是一样的.
docker部署...
我也是威联通,本地resolve.conf也更换dns了白扯.
