### ISSUE TITLE
请求接口https://dnsapi.cn/Record.List失败

### ISSUE THREAD

**Issue by Fragskyline** [jeessy2/ddns-go#304]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
利用synology内置的docker安装了最新的ddns-go，用腾讯云的域名和IPV6设置了DDNS，但是看日志上一直在滚动
2022/06/16 17:29:30 请求接口https://dnsapi.cn/Record.List失败! ERROR: Post "https://dnsapi.cn/Record.List": dial tcp: i/o timeout
搜了一圈每一个人碰到类似问题，只好麻烦jeessy大佬了。

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [ ] 未搜索

## 环境
- 操作系统: synology7.0.1，win7
- ddns-go版本: 3.7.2
- 安装方式: docker/服务

## 截图
![image](https://user-images.githubusercontent.com/107615867/174043636-48855b38-1512-46d9-833c-60161113f78c.png)

**Comment by jeessy2** [comment]
网络问题，请求接口失败了。自行检查一下了

**Comment by Fragskyline** [comment]
> 网络问题，请求接口失败了。自行检查一下了

确实是synology网络设置的问题，主要是网络防火墙的设置导致的，多谢~~

**Comment by qq169802031** [comment]
> > 网络问题，请求接口失败了。自己检查一下了
> 
> 确实是synology网络设置的问题，主要是网络防火墙的设置导致的，多谢~~

老兄，是防火墙的哪里的设置问题啊？我也遇到了，该怎么设置

**Comment by qq169802031** [comment]
> > > 自己的网络问题，请求接口失败了。检查一下了
> > 
> > 
> > 确实是synology网络设置的问题，主要是网络防火墙的设置导致的，多谢~~
> 
> 老哥，是防火墙的哪里设置的问题啊？我也遇到了，该怎么设置

我发现5分钟后 软件自动第二次更新ipv6就正常了 怀疑是请求接口时软路由还没准备好，等5分钟就正常了
