### ISSUE TITLE
bug: win11下载Releases中已编译好的文件运行会报错

### ISSUE THREAD

**Issue by D1rtyDann** [jeessy2/ddns-go#305]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
win11下载Releases中已编译好的文件运行会报错:
        程序“ddns-go.exe”无法运行: 指定的可执行文件不是此操作系统平台的有效应用程序。
## 是否已搜索同类问题
- [ ] 已搜索未能解决
- [x] 未搜索
已解决
clone源码自行编译即可

## 环境
- 操作系统: 
- Windows 11 专业工作站版 21H2 22000.739
- ddns-go版本: 3.7.1
- 安装方式: docker/服务
下载预编译的可执行文件运行
## 截图
![image](https://user-images.githubusercontent.com/44843555/174642925-a5dd37d0-c263-42c5-b9ed-3987242c3307.png)

**Comment by jeessy2** [comment]
这个问题不好查找。clone源码自行编译比较好
