### ISSUE TITLE
怎么cloudflare的域名无法解析呢

### ISSUE THREAD

**Issue by zzfree2021** [jeessy2/ddns-go#308]
2022/06/28 09:09:19 请求接口 https://api.cloudflare.com/client/v4/zones?name=xxx.com&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400 

域名记录不更新呢

**Comment by jeessy2** [comment]
检查一下token

**Comment by zzfree2021** [comment]
token我直接填写的Global API Key，不行？

**Comment by jeessy2** [comment]
按说明来：创建令牌->编辑区域 DNS (使用模板)

**Comment by RealKiro** [comment]
报错无法更新DDNS，请问如何处理？
```
2022/07/20 12:43:11 请求接口https://api.cloudflare.com/client/v4/zones?name=best520.fun&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=best520.fun&status=active&per_page=50": EOF
```

**Comment by jeessy2** [comment]
> 

网络问题。下次就好了

**Comment by sslzhou948** [comment]
我也相同的问题，本来没问题升级了DDNS-GO的版本就不行了，我也观察观察会不会自动恢复

**Comment by sslzhou948** [comment]
我发现日志还是会报错，但是可以解析了，这是不是5.6.0的bug啊

**Comment by TwT-L** [comment]
![image](https://github.com/jeessy2/ddns-go/assets/93702913/36a6cb90-9999-4277-901b-651a1fc4f65f)

@jeessy2 请问它直接停止了是为什么？

**Comment by jeessy2** [comment]
> ![image](https://github.com/jeessy2/ddns-go/assets/93702913/36a6cb90-9999-4277-901b-651a1fc4f65f)
> 
> 
> 
> @jeessy2 请问它直接停止了是为什么？

换个接口，或通过curl测试

**Comment by ddlanlan** [comment]
> 我发现日志还是会报错，但是可以解析了，这是不是5.6.0的bug啊

我也有这个问题了，请问这个怎么解决呢？谢谢。
