### ISSUE TITLE
IPV6 内网的IPv6 地址获取

### ISSUE THREAD

**Issue by ccdos** [jeessy2/ddns-go#31]
这个程序非常好用，看了说明已经在 群晖部署成功。
另外提个建议，就是我发现 爱快的DDNS 有个很好的功能，就是能通过mac 地址获取内网机器的 IPV6 地址。
因为ipv6情况下，内网机器也都能获得公网地址，虽然可以在每台机器安装这个客户端，
但是有些机器不方便安装程序，就无法用上这个DDNS的功能了。
如果能实现类似爱快的DDNS功能，就可以只安装一个，就为全网的主机实现的独立的ipv6公网ip更新了

**Comment by jeessy2** [comment]
可通过EUI-64计算出其它机器上的ipv6。https://baike.baidu.com/item/EUI-64
或通过NDP协议来
这个改动较大，欢迎提PR

**Comment by czxinshui** [comment]
> 可通过EUI-64计算出其它机器上的IPv6的。https://baike.baidu.com/item/EUI-64
> 或通过NDP来协议
> 这个改动较大，欢迎提PR

这个是神之功能。如果能成功就好了

**Comment by irrocu** [comment]
如果有这个功能，感觉ddns-go就更完美了

**Comment by xikik** [comment]
支持jeessy2大大，希望大大也能开发出类似的功能。这样可以在局域网一台机器上安装程序，可以方便的访问所有设备了。

**Comment by mjyhj** [comment]
https://www.youtube.com/watch?v=UtbmGJLwJHE
爱快相关IPV6 DDNS功能

**Comment by ahit976** [comment]
衷心希望有这个功能，这样在路由上运行，可以解决所有。
sharealiddns插件有类似功能，但目前还有些bug，我在ac86u上使用sharealiddns效果不好，会断网。
https://github.com/zwmscorm/sharealiddns/issues

**Comment by jeessy2** [comment]
https://github.com/jeessy2/ddns-go/issues/104#issuecomment-919656711

获取局域网其它电脑的IPv6, 主流方案是根据MAC地址获取的IPv6(如爱快系统)
但是有以下问题:
- mac/windows几代前已不支持通过MAC地址生成IPv6(为了保护隐私, 防止网站追踪)
- linux可以通过配置来使用MAC地址获取IPv6

总结如下:
- 支持的系统较少, 不完整
- 隐私问题严重
- 如果有新的方案, 及时讨论

建议:
- 目前建议独立安装DDNS-GO
