### ISSUE TITLE
希望增加点功能，DNS服务商中的callback

### ISSUE THREAD

**Issue by snail2sky** [jeessy2/ddns-go#311]
## 问题描述
    - 由于目前提供的DNS服务商有限，所以未提供的服务商只能通过callback来实现(当然可以提PR，但我比较菜~)
    - 通过callback的功能比较弱，不能修改请求头，因为有的DNS服务商的认证信息放在请求头里，如godaddy，而目前的ddns-go只能修改url和request body，所以目前不能解决这个问题~
- 阐述 记录/问题/事件/... 发生的背景

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [ ] 未搜索

## 环境
- 操作系统: 
- ddns-go版本: 
- 安装方式: docker/服务

**Comment by snail2sky** [comment]
不过感觉这个功能用的人不多，要不回头我提PR搞搞看，估计代码质量不会高~

**Comment by jeessy2** [comment]
这个功能用得有点少，改也改复杂了。可以把godaddy的dns服务器转移支持的服务商

**Comment by gdy666** [comment]
https://github.com/gdy666/lucky
 我在ddns-go基础上有改进,可以自定义callback 请求头,有需要可以试试.

**Comment by jeessy2** [comment]
4.1.0后支持Godaddy
