### ISSUE TITLE
win11开机自启问题

### ISSUE THREAD

**Issue by Yangkuan716** [jeessy2/ddns-go#312]
## 问题描述
Win11系统，安装ddns-go，系统启动未登录微软账号进入桌面状态下，发现无法解析ip到域名。
开机发现日志显示无法连接。
![Screenshot_2022-07-03-10-27-34-830_com microsoft rdc android](https://user-images.githubusercontent.com/28797782/177022337-a336c628-c901-4f6f-9317-004fa1c30594.jpg)

## 是否已搜索同类问题
- [是 ] 已搜索未能解决

## 环境
- 操作系统: win11
- ddns-go版本: 
- 安装方式: docker/服务
#310

**Comment by jeessy2** [comment]
这个和系统有关系，开机没有网络。自行看下win11可以设置不

**Comment by Yangkuan716** [comment]
电脑开机界面，就是输入账号密码的界面，wifi是显示已连接的。
这个大神辛苦看下，我应该从哪个方向去查问题😂😂

**Comment by Yangkuan716** [comment]
这个问题我解决了，先卸载了ddns-go，然后用系统自带的计划任务设置开机自启该程序（注意设置成不用登陆），然后目前完美解决问题
