### ISSUE TITLE
强烈建议, 发布releases的时候, 不要在包名称中带版本号, 最好以后每个版本名称能统一下下

### ISSUE THREAD

**Issue by wutongskype** [jeessy2/ddns-go#314]
因为不带版本号的话,可以用下面这种命令直接下载最新版的
wget https://github.com/jeessy2/ddns-go/releases/latest/download/ddns-go_Linux_arm64.tar.gz

而带版本号的话就得手动复制连接哈.不方便搞一键脚本哈

**Comment by jeessy2** [comment]
一般都带了的。建议网上找下脚本吧
