### ISSUE TITLE
服务不见了

### ISSUE THREAD

**Issue by diaoseo** [jeessy2/ddns-go#316]
## 问题描述
win系统下计划任务启动，在网络有波动情况下(如路由器临时断电，光纤被挖断)服务会丢失。也就是127.1打不开，程序也没有在运行（此情况已出现3次，排除设备问题。重新手动运行程序即可启动。大多数人会陷入死循环。没有ddns就没法远程启动服务。

## 是否已搜索同类问题
- [ ] 未搜索

## 环境
- 操作系统: win10
- ddns-go版本: 3.7.2
- 安装方式: 服务

## 截图
此处没有截图

**Comment by jeessy2** [comment]
程序没运行起来？产生日志没有

**Comment by diaoseo** [comment]
> 程序没运行起来？产生日志没有

不知道日志存放在哪里，目录下并没有。

**Comment by jeessy2** [comment]
需要保证程序能运行，在找下是什么原因引起的

**Comment by diaoseo** [comment]
> 需要保证程序能运行，在找下是什么原因引起的

我也想找原因啊，没找到所有的日志是存哪里的。启动后网页上的日志就和正常启动一样

**Comment by diaoseo** [comment]
经过长时间测试，发现可能是内存不足或者硬盘读取过慢。导致Windows自动重新登陆(看到的现象至少重启了资源管理器)。而我当初的计划任务是每次开机。所以注销后重新登陆并没有启动程序。现尝试修改计划任务让其每次登陆都运行。不过好像每次远程连接都计算重新登陆。所以，最佳解决方案是像流氓软件一样，给我流氓的加自启动。不需要客气，给个设定就行了。暂时关闭ISS吧
