### ISSUE TITLE
请求接口https://alidns.aliyuncs.com/失败! ERROR: Get没看到错误代码 

### ISSUE THREAD

**Issue by qlp3220813** [jeessy2/ddns-go#318]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景

## 是否已搜索同类问题
- [√ ] 已搜索未能解决

## 环境
- 操作系统: docker
- 移动宽带网络
- ddns-go版本: 3.72
- 安装方式: docker/服务
<img width="1078" alt="Snipaste_2022-07-14_10-03-02" src="https://user-images.githubusercontent.com/18310872/178881485-7ca4c699-99cd-4c4f-b142-5db43694a7ed.png">
## 截图
2022/07/14 09:57:59 你的IP 2409:8a04:615:3850:2 没有变化, 域名 www.****.fun
2022/07/14 09:58:09 请求接口https://alidns.aliyuncs.com/失败! ERROR: Get "https://alidns.aliyuncs.com/?AccessKeyId=*****oT****&Action=DescribeSubDomainRecords&DomainName=**d.fun&Format=JSON&Signature=5NebpF4dIYGdoaWHl44JOYiD%2BfY%3D&SignatureMethod=HMAC-SHA1&SignatureNonce=1657763879477773712&SignatureVersion=1.0&SubDomain=%40.**d.fun&Timestamp=2022-07-14T01%3A57%3A59Z&Type=AAAA&Version=2015-01-09": dial tcp: i/o timeout
不知道是哪里的原因了 麻烦大佬看下  非常感谢

**Comment by jeessy2** [comment]
dial tcp: i/o timeout 
请求aliyun超时了，检查下网络

**Comment by qlp3220813** [comment]
我是威联通nas搭建的，，重启了下DOCKER第一条www可以解析,后面的又失败了，请问下大佬怎么检查网络 ...谢谢了🙏

**Comment by jeessy2** [comment]
威联通不熟悉。可以通过curl请求那个网址试试

**Comment by qlp3220813** [comment]
我更新了下威联通系统固件就解决了，具体原因不详  感谢大佬的解答 ，非常感谢。
