### ISSUE TITLE
蜗牛星际B款双网卡，黑群晖，IPv6模式时无法取得物理网卡信息

### ISSUE THREAD

**Issue by hrbagang** [jeessy2/ddns-go#32]
蜗牛星际B款双网卡，黑群晖，IPv6模式时，获取IP方式=通过网卡获取，下拉列表里只有“tun1000”（内网IPv6网址），没有物理网卡信息：ovs_eth0（外网IPv6网址） / ovs_eth1（外网IPv6网址）.

**Comment by jeessy2** [comment]
终端看下ifconfig的输出

**Comment by hrbagang** [comment]
docker0   Link encap:Ethernet  HWaddr 02:42:C1:39:55:DF
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 00:11:32:6A:24:71
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:16 memory 0xd0880000-d08a0000

eth1      Link encap:Ethernet  HWaddr 00:11:32:6A:24:72
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6064 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10480 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1312643 (1.2 MiB)  TX bytes:10445756 (9.9 MiB)
          Interrupt:19 memory 0xd0680000-d06a0000

eth50     Link encap:Ethernet  HWaddr 22:B8:0C:CB:4C:48
          inet addr:192.168.192.220  Bcast:192.168.192.255  Mask:255.255.255.0
          inet6 addr: fe80::20b8:cff:fecb:4c48/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:799 errors:0 dropped:0 overruns:0 frame:0
          TX packets:893 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500
          RX bytes:119565 (116.7 KiB)  TX bytes:155074 (151.4 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:12914 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12914 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2037047 (1.9 MiB)  TX bytes:2037047 (1.9 MiB)

ovs_eth0  Link encap:Ethernet  HWaddr 00:11:32:6A:24:71
          inet addr:192.168.1.21  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::211:32aa:fe6c:2471/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:731 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:64284 (62.7 KiB)

ovs_eth1  Link encap:Ethernet  HWaddr 00:11:32:6A:24:72
          inet addr:192.168.1.22  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::211:32aa:fe6c:2472/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5968 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7497 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1282207 (1.2 MiB)  TX bytes:10249087 (9.7 MiB)

tun1000   Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:169.254.168.139  P-t-P:169.254.168.139  Mask:255.255.240.0
          inet6 addr: fec0:a2b2:3::1889/112 Scope:Site
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1400  Metric:1
          RX packets:1429 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2317 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          RX bytes:94581 (92.3 KiB)  TX bytes:2556711 (2.4 MiB)

**Comment by jeessy2** [comment]
获取的Ipv6是内网的。检查一下你网络环境

**Comment by hrbagang** [comment]
ovs_eth0/ovs_eth1的是外网Ipv6地址啊？fe80开头的。。。

**Comment by jeessy2** [comment]
不是。链路本地地址是使用链路本地前缀FE80::/10的IPv6单播地址(1111 1110 10)。正常的应该是2开头的，如移动2409

**Comment by hrbagang** [comment]
刚百度了一下，是内网地址，我错了

**Comment by hrbagang** [comment]
原来都是公网的V6地址，怎么变成内网v6了，奇怪

**Comment by hrbagang** [comment]
重启了下光猫，好了，有公网v6的IP了
