### ISSUE TITLE
怎么在光猫linux中运行

### ISSUE THREAD

**Issue by buqiang** [jeessy2/ddns-go#320]
我在光猫的telnet里能运行时碰到了这个：

> #./ddns-go
2022/07/16 19:55:05 可使用 sudo ./ddns-go -s install 安装服务运行
2022/07/16 19:55:05 监听 :9876 ...
2022/07/16 19:55:05 第一次运行将等待 20 秒后运行 (等待网络)
2022/07/16 19:55:14 配置文件已保存在: /home/root/.ddns_go_config.yaml
2022/07/16 19:55:14 请求接口https://dnsapi.cn/Record.List失败! ERROR: Post "https://dnsapi.cn/Record.List": x509: certificate signed by unknown authority
2022/07/16 19:55:26 请求接口https://dnsapi.cn/Record.List失败! ERROR: Post "https://dnsapi.cn/Record.List": x509: certificate signed by unknown authority

还有这个
> #./ddns-go -s install
2022/07/16 19:58:12 安装 ddns-go 服务成功! 请打开浏览器并进行配置。
2022/07/16 19:58:12 exit status 2
2022/07/16 19:58:12 exit status 2
#./ddns-go -s uninstall
2022/07/16 19:58:19 exit status 2
2022/07/16 19:58:19 ddns-go 服务卸载成功!

**Comment by jeessy2** [comment]
第一个是本地的证书，太老了。需要升级系统，看能支持否。
第二个也看能升级系统改善不

**Comment by gdy666** [comment]
http_util.go的第63行下加上
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
这行代码忽略证书验证就可以了.

**Comment by jeessy2** [comment]
> http_util.go的第63行下加上
> 
> 			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
> 
> 这行代码忽略证书验证就可以了.

可以是可以，自行编译一个。不过不是很安全

**Comment by SwordRays** [comment]
> > http_util.go的第63行下加上
> > ```
> >   	TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这行代码忽略证书验证就可以了.
> 
> 可以是可以，自行编译一个。不过不是很安全

如果时间允许的话，建议还是加一个配置可选项会好一些，这个需求在大多数路由器官方固件(很老的openwrt)系统里面应该算 是刚需了~

**Comment by gdy666** [comment]
> > http_util.go的第63行下加上
> > ```
> >   	TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这行代码忽略证书验证就可以了.
> 
> 可以是可以，自行编译一个。不过不是很安全

我准备把ddns-go的代码合并进我的一个开源项目https://github.com/gdy666/goports里面,
在ddns-go基础上面改进,同时支持多个ddns任务,提供tls开关,代理服务器等乱七八糟的东东,撸多几天代码应该就可以撸完了...
![QQ截图20220720075201](https://user-images.githubusercontent.com/2849711/179867265-9a6cf4aa-8475-4b68-a90a-4b2022b3d5f4.png)
![QQ截图20220720075309](https://user-images.githubusercontent.com/2849711/179867281-2e68fd85-ade3-45ff-9652-80f79b26e0fd.png)

**Comment by yin1999** [comment]
可以看一下光猫中有没有这个文件：`/etc/ssl/certs/ca-certificates.crt`。有的话，直接从其它的 Linux 发行版拷贝一个过去就行。

**Comment by gdy666** [comment]
> 我在光猫的telnet里能运行时碰到了这个：
> 
> > #./ddns-go
> > 2022/07/16 19:55:05 可使用 sudo ./ddns-go -s install 安装服务运行
> > 2022/07/16 19:55:05 监听 :9876 ...
> > 2022/07/16 19:55:05 第一次运行将等待 20 秒后运行 (等待网络)
> > 2022/07/16 19:55:14 配置文件已保存在: /home/root/.ddns_go_config.yaml
> > 2022/07/16 19:55:14 请求接口[https://dnsapi.cn/Record.List失败](https://dnsapi.cn/Record.List%E5%A4%B1%E8%B4%A5)! ERROR: Post "https://dnsapi.cn/Record.List": x509: certificate signed by unknown authority
> > 2022/07/16 19:55:26 请求接口[https://dnsapi.cn/Record.List失败](https://dnsapi.cn/Record.List%E5%A4%B1%E8%B4%A5)! ERROR: Post "https://dnsapi.cn/Record.List": x509: certificate signed by unknown authority
> 
> 还有这个
> 
> > #./ddns-go -s install
> > 2022/07/16 19:58:12 安装 ddns-go 服务成功! 请打开浏览器并进行配置。
> > 2022/07/16 19:58:12 exit status 2
> > 2022/07/16 19:58:12 exit status 2
> > #./ddns-go -s uninstall
> > 2022/07/16 19:58:19 exit status 2
> > 2022/07/16 19:58:19 ddns-go 服务卸载成功!

可以试试我这个能不能在光猫运行哟. https://github.com/gdy666/lucky,默认禁用了TLS验证.

**Comment by jeessy2** [comment]
fix: https://github.com/jeessy2/ddns-go/releases/tag/v4.4.1
