### ISSUE TITLE
点击查看接口能否返回IPv4地址

### ISSUE THREAD

**Issue by ananqiji** [jeessy2/ddns-go#322]
连接失败! <a target='blank' href='https://myip4.ipip.net'>点击查看接口能否返回IPv4地址

    下午开始就突然这样,下面三个获取ip的地址都能正常访问

![2022-7-21](https://user-images.githubusercontent.com/62270468/180198677-0fc75ad3-6334-43dc-9fd6-cda694b406f9.png)
了

**Comment by jeessy2** [comment]
检查一下自己的网络。在ddns-go主机上通过curl请求看正常不

**Comment by ananqiji** [comment]
邮件已收到！

**Comment by ananqiji** [comment]
是在控制台这样输入吗?  curl https://ip.3322.net  输入以后没法应      才开始用nas不太懂这些命令

**Comment by jeessy2** [comment]
是那么用的

**Comment by ananqiji** [comment]
请求后没输出   虽然这个网站在浏览器里可以打开

**Comment by walkxspace** [comment]
在IP变更后有时我也会出现这种情况，重启一下容器就好了，也可以自己设个定时重启容器

**Comment by jeessy2** [comment]
把你们环境说下，多测试。我这里没遇到这种情况

**Comment by maxage** [comment]
> 把你们环境说下，多测试。我这里没遇到这种情况

unraid docker 运行
2022/07/24 00:44:49 连接失败! [点击查看接口能否返回IPv4地址](https://ddns.oray.com/checkip),
2022/07/24 00:44:59 连接失败! [点击查看接口能否返回IPv4地址](https://ip.3322.net/),
2022/07/24 00:44:59 未能获取IPv4地址, 将不会更新

可是https://myip4.ipip.net, https://ddns.oray.com/checkip, https://ip.3322.net都能正确获取到公网ip

**Comment by jeessy2** [comment]
> > 把你们环境说下，多测试。我这里没遇到这种情况
> 
> 
> 
> unraid docker 运行
> 
> 2022/07/24 00:44:49 连接失败! [点击查看接口能否返回IPv4地址](https://ddns.oray.com/checkip),
> 
> 2022/07/24 00:44:59 连接失败! [点击查看接口能否返回IPv4地址](https://ip.3322.net/),
> 
> 2022/07/24 00:44:59 未能获取IPv4地址, 将不会更新
> 
> 
> 
> 可是https://myip4.ipip.net, https://ddns.oray.com/checkip, https://ip.3322.net都能正确获取到公网ip

能描述清楚一点么？ddns-go版本号，异常持续多久

**Comment by ananqiji** [comment]
版本号显示的是latest,持续了一天多，删掉重新安装一遍就好了

**Comment by jeessy2** [comment]
你们设置的频率都是10s一次的么？那一天请求接口就量大了，大概8640次。接口一般会限制请求量的。要么自建一个获取IP的，或则频率改为默认的5分钟，5分钟完全够用了

**Comment by maxage** [comment]
一直显示连接失败
2022/08/01 17:39:51 配置文件已保存在: /root/.ddns_go_config.yaml
2022/08/01 17:40:01 连接失败! [点击查看接口能否返回IPv4地址](https://myip4.ipip.net/),
2022/08/01 17:40:11 连接失败! [点击查看接口能否返回IPv4地址](https://ddns.oray.com/checkip),
2022/08/01 17:40:21 连接失败! [点击查看接口能否返回IPv4地址](https://ip.3322.net/),
2022/08/01 17:40:21 未能获取IPv4地址, 将不会更新
2022/08/01 17:41:09 连接失败! [点击查看接口能否返回IPv4地址](https://myip4.ipip.net/),
2022/08/01 17:41:19 连接失败! [点击查看接口能否返回IPv4地址](https://ddns.oray.com/checkip),
2022/08/01 17:41:29 连接失败! [点击查看接口能否返回IPv4地址](https://ip.3322.net/),
2022/08/01 17:41:29 未能获取IPv4地址, 将不会更新

网页输入https://myip4.ipip.net, https://ddns.oray.com/checkip, https://ip.3322.net这些网址能获取到IP
比如     当前 IP：1xx.xx.xxx.xxx  来自于：中国 广东 XX  电信   

docker unraid  版本v4.0.0 好多天了一直这样。

**Comment by jeessy2** [comment]
> 一直显示连接失败
> 
> 2022/08/01 17:39:51 配置文件已保存在: /root/.ddns_go_config.yaml
> 
> 2022/08/01 17:40:01 连接失败! [点击查看接口能否返回IPv4地址](https://myip4.ipip.net/),
> 
> 2022/08/01 17:40:11 连接失败! [点击查看接口能否返回IPv4地址](https://ddns.oray.com/checkip),
> 
> 2022/08/01 17:40:21 连接失败! [点击查看接口能否返回IPv4地址](https://ip.3322.net/),
> 
> 2022/08/01 17:40:21 未能获取IPv4地址, 将不会更新
> 
> 2022/08/01 17:41:09 连接失败! [点击查看接口能否返回IPv4地址](https://myip4.ipip.net/),
> 
> 2022/08/01 17:41:19 连接失败! [点击查看接口能否返回IPv4地址](https://ddns.oray.com/checkip),
> 
> 2022/08/01 17:41:29 连接失败! [点击查看接口能否返回IPv4地址](https://ip.3322.net/),
> 
> 2022/08/01 17:41:29 未能获取IPv4地址, 将不会更新
> 
> 
> 
> 网页输入https://myip4.ipip.net, https://ddns.oray.com/checkip, https://ip.3322.net这些网址能获取到IP
> 
> 比如     当前 IP：1xx.xx.xxx.xxx  来自于：中国 广东 XX  电信   
> 
> 
> 
> docker unraid  版本v4.0.0 好多天了一直这样。
> 
> DNS服务商Cloudflare
> 
> 
> 
> 页面截图如下
> 
> https://s1.328888.xyz/2022/08/01/FH0OU.png
> 
> https://s1.328888.xyz/2022/08/01/FH4KB.png

10s频率太高了，上面写了原因的。建议自建接口

**Comment by MirrorCY** [comment]
相同问题，环境为android 12 termux，curl可以获取到IP

**Comment by ananqiji** [comment]
邮件已收到！
