### ISSUE TITLE
openwrt日志时间差了8个小时

### ISSUE THREAD

**Issue by skill7899** [jeessy2/ddns-go#328]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
在openwrt按装了ddns-go，openwrt时间是+8，ddns-go的日志不是+8时区
## 是否已搜索同类问题
- [✓] 已搜索未能解决

## 环境
- 操作系统: openwrt
- ddns-go版本:  v3.7.2
- 安装方式: 服务

## 截图
<img width="381" alt="image" src="https://user-images.githubusercontent.com/13962272/180693046-23a43bb9-1c54-4777-b1e5-9215f840dd08.png">
<img width="314" alt="image" src="https://user-images.githubusercontent.com/13962272/180693060-76dcedfd-dad5-4afa-882b-895785be6beb.png">

**Comment by jeessy2** [comment]
看下是不是没设置对。没复现这个问题

**Comment by DuCun** [comment]
请检查一下你的Docker时区是否为东八区`Asia/Shanghai`

**Comment by skill7899** [comment]
> 请检查一下你的Docker时区是否为东八区`Asia/Shanghai`

我是用服务的方式安装的

**Comment by skill7899** [comment]
> 看下是不是没设置对。没复现这个问题

@jeessy2 我是pve LXC安装的openwrt

**Comment by IDSSC** [comment]
@skill7899 LXC和docker都一样是需要设置时区的

**Comment by skill7899** [comment]
> @skill7899 LXC和docker都一样是需要设置时区的

默认时区没有错的，lxc里面就是正确的时间

**Comment by jeessy2** [comment]
看你op系统时区是多少

**Comment by skill7899** [comment]
> 看你op系统时区是多少

@jeessy2 
<img width="357" alt="image" src="https://user-images.githubusercontent.com/13962272/182120067-305c67eb-4732-4d65-85af-9a843a2919b6.png">

**Comment by jeessy2** [comment]
这个没遇到了，我这里正常的。是不是op挂在pve下面的原因

**Comment by DuCun** [comment]
可参考Go开发文档https://docs.kilvn.com/The-Golang-Standard-Library-by-Example/chapter04/04.2.html

**Comment by DuCun** [comment]
默认 OpenWRT 缺少 zoneinfo 包
需执行`opkg update && opkg install zoneinfo-asia`
然后重启服务`/etc/init.d/system restart`
你可以尝试一下

**Comment by gdy666** [comment]
后台是不是应该增加一个参数,用来自定义时区,这样就不需要zoneinfo 包之类的了.
我原来使用ddns-go的时候也有遇到这个时区的问题,后来我的 https://github.com/gdy666/lucky
用了	var cstZone = time.FixedZone("CST", 8*3600)
	time.Local = cstZone
来强制设置为东八时区,凑合用用.

**Comment by skill7899** [comment]
> 这个没遇到了，我这里正常的。是不是op挂在pve下面的原因

我OP的其它组件输出就正常

**Comment by DuCun** [comment]
> > 这个没遇到了，我这里正常的。是不是op挂在pve下面的原因
> 
> 我OP的其它组件输出就正常

你可以查看我说的方法，其实这个为不同也不影响正常使用，丢在那就不用管

**Comment by skill7899** [comment]
> > > 这个没遇到了，我这里正常的。是不是op挂在pve下面的原因
> > 
> > 
> > 我OP的其它组件输出就正常
> 
> 你可以查看我说的方法，其实这个问题也不影响正常使用，ddns丢在那就基本不用管

是的

**Comment by zsc2010520** [comment]
2023年 07月 22日 星期六 15:32:19 CST

我也复现这个问题了OP时区 时间正确，DDNS-GO时间相差8小时，更新IP解析错误

2023/07/22 07:10:35 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"","Message":"Specified time stamp or date value is expired.","Recommend":"https://api.aliyun.com/troubleshoot?q=InvalidTimeStamp.Expired&product=Alidns","HostId":"alidns.aliyuncs.com","Code":"InvalidTimeStamp.Expired"} ,返回状态码: 400

**Comment by WaterLemons2k** [comment]
> 2023年 07月 22日 星期六 15:32:19 CST
> 
> 我也复现这个问题了OP时区 时间正确，DDNS-GO时间相差8小时，更新IP解析错误
> 
> 2023/07/22 07:10:35 请求接口 [alidns.aliyuncs.com](https://alidns.aliyuncs.com/) 失败! 返回内容: {"RequestId":"","Message":"Specified time stamp or date value is expired.","Recommend":"[https://api.aliyun.com/troubleshoot?q=InvalidTimeStamp.Expired&product=Alidns","HostId":"alidns.aliyuncs.com","Code":"InvalidTimeStamp.Expired"}](https://api.aliyun.com/troubleshoot?q=InvalidTimeStamp.Expired&product=Alidns%22,%22HostId%22:%22alidns.aliyuncs.com%22,%22Code%22:%22InvalidTimeStamp.Expired%22%7D) ,返回状态码: 400

ddns-go 会尝试从 `/etc/localtime` 读取时区，所以请尝试将 `Asia/Shanghai` 软链接到 `/etc/localtime` 后再试：

```sh
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
```

参考：#729

**Comment by zsc2010520** [comment]
> 

这样操作有效 问题已解决
