### ISSUE TITLE
WEB界面可以通过ipv4地址访问，无法通过 ipv6地址访问

### ISSUE THREAD

**Issue by Gyokurin** [jeessy2/ddns-go#329]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
WEB界面可以通过本机ipv4地址访问，无法通过本机 ipv6地址访问
## 是否已搜索同类问题
- [ ] 已搜索未能解决

## 环境
- 操作系统: termux 模拟终端
- ddns-go版本: v3.7.2

## 截图
![image](https://user-images.githubusercontent.com/33086918/180705235-4ff8cb73-63dc-4bd9-b1ce-54515ee34a09.png)
![image](https://user-images.githubusercontent.com/33086918/180705090-df51ff49-fc80-45ca-b6c1-3e728542db92.png)
![image](https://user-images.githubusercontent.com/33086918/180705125-138fac4b-0ed2-4cce-bd68-a1c7e2831db7.png)

**Comment by jeessy2** [comment]
1. 检查系统防火墙
2. 是否打开了`禁止从公网访问`。默认勾选了的

**Comment by Gyokurin** [comment]
> 1. 检查系统防火墙
> 2. 是否打开了。默认勾选了的`禁止从公网访问`

![image](https://user-images.githubusercontent.com/33086918/180707157-6d687ab5-3891-4369-9803-7d78cf0ef143.png)
如图取消勾选一样不能使用ipv6地址访问，ipv4方式9876端口号可以使用，排除防火墙因素。
我在浏览器地址栏 填写 [ipvaddr]:9876 这种方式访问的

**Comment by Gyokurin** [comment]
> 1. 检查系统防火墙
> 2. 是否打开了`禁止从公网访问`。默认勾选了的
windows 平台上运行没有此问题

**Comment by Gyokurin** [comment]
尝试用ipv6地址访问 termux 中的 nginx ssh 服务都正常，ddnsgo无法访问原因未知。

**Comment by jeessy2** [comment]
检查端口是否已监听v6地址，防火墙墙开放端口没有

**Comment by jeessy2** [comment]
正常的。检查自己环境
![截屏2022-07-25 下午6 02 17](https://user-images.githubusercontent.com/6205259/180751904-04867733-25c2-4fb9-9131-d51de90478ce.png)
