### ISSUE TITLE
撸完了,欢迎来尝BUG

### ISSUE THREAD

**Issue by gdy666** [jeessy2/ddns-go#330]
[](url)项目地址:https://github.com/gdy666/lucky
用得上记得点个小星星

集成ddns-go完毕
在ddns-go的基础上主要改进/增加的功能有
1.同时支持接入多个不同的DNS服务商
2.支持http/https/socks5代理设置
3.自定义(Callback)和Webhook支持自定义headers
4.支持BasicAuth
5.DDNS任务列表即可了解全部信息(包含错误信息),无需单独查看日志.
6.调用DNS服务商接口更新域名信息前可以先通过DNS解析域名比较IP,减少对服务商接口调用.
其它细节功能自己慢慢发现...
没有文档,后台各处的提示信息已经足够多.

![列表](https://user-images.githubusercontent.com/2849711/181009413-9607caca-c169-487e-b489-c5ed697ce9ec.png)
![iphi](https://user-images.githubusercontent.com/2849711/181009448-2669b10a-c35d-4cff-80af-d96b84554ef6.png)
![webhook调用记录](https://user-images.githubusercontent.com/2849711/181009453-1b847c70-bbf6-4fbf-92a7-1e3ac90dd358.png)
![域名同步](https://user-images.githubusercontent.com/2849711/181009454-441a2a7b-ede6-46bb-8ca9-8e97d6c5e351.png)

**Comment by jeessy2** [comment]
有空也来改ddns-go

**Comment by gdy666** [comment]
> 有空也来改ddns-go

改着改着改动太大了,不敢对ddns-go下手......
