### ISSUE TITLE
Callback 方式支持自定义变量吗？

### ISSUE THREAD

**Issue by jetsung** [jeessy2/ddns-go#332]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
使用 DNSPod 国际版的 **修改记录** 接口时，[`record_id` 的变量是必填值](https://docs.dnspod.cn/api/modify-records/)。但是若通过 `RequestBody` 输入的内容，只能写死一个值。这样的话，多域名时，则无法修改其它域名的记录。

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [] 未搜索

## 环境
- 操作系统: debian
- ddns-go版本: [DEV]**[9bb457d](https://github.com/jeessy2/ddns-go/commit/9bb457db30aa0857aa34c9b216beb587c1922369)**
- 安装方式: go run main.go 开发模式

## 截图
![image](https://user-images.githubusercontent.com/3362147/181245321-9f9cf2da-953a-4aad-9cb8-994ffb1c90c4.png)

**Comment by jeessy2** [comment]
recordId必填的话，那确实只能修改一个

**Comment by jetsung** [comment]
> recordId必填的话，那确实只能修改一个

好吧。那我自己改一个吧。加在每行域名后面。

**Comment by jeessy2** [comment]
参考这种。看能实现公共的否
test.example.com?Line=oversea
test.example.com?RecordId=123
