### ISSUE TITLE
支持传递自定义参数

### ISSUE THREAD

**Issue by jeessy2** [jeessy2/ddns-go#336]
支持传递自定义参数，目前只实现如下DNS服务商: 

# Aliyun

- 通过[Line参数](https://help.aliyun.com/document_detail/29807.html)修改
```
example.com?Line=telecom
```

- 通过RecordId修改
```
example.com?RecordId=xx
```
- 可搭配更多[参数](https://help.aliyun.com/document_detail/29774.html)
```
example.com?RecordId=xx&Line=oversea&Lang=en
```

# Dnspod

- 通过[record_line参数](https://docs.dnspod.cn/dns/dns-record-line/)修改
```
example.com?record_line=境内
```

- 通过record_id修改
```
example.com?record_id=xx
```
- 可搭配更多[参数](https://docs.dnspod.cn/api/modify-records/)
```
example.com?record_id=xx&record_line=境内&status=disable
```

# Callback

#### URL或RequestBody参考, myid取domains中的myid
```
https://mycallback.com?ip=#{ip}&domain=#{domain}&myid=#{myid}
```
#### domains
```
example.com?myid=xx
```

# Cloudflare

#### proxied (v4.2.2)
```
example.com?proxied=true
```

**Comment by s1240** [comment]
how about porkbun ?

**Comment by jeessy2** [comment]
> how about porkbun ?

Not yet! The PR is welcome

**Comment by s1240** [comment]
不能更新公网IP 到porkbun ,不知道哪里出了问题？
do not update public ip to porkbun ,the log as below :

2022/08/09 00:44:19 配置文件已保存在: /root/.ddns_go_config.yaml
2022/08/09 00:44:19 请求接口https://porkbun.com/api/json/v3/dns/retrieveByNameType/s1240.com/A/@失败! ERROR: Post "https://porkbun.com/api/json/v3/dns/retrieveByNameType/s1240.com/A/@": EOF
2022/08/09 00:45:20 配置文件已保存在: /root/.ddns_go_config.yaml
2022/08/09 00:45:21 请求接口https://porkbun.com/api/json/v3/dns/retrieveByNameType/s1240.com/A/@失败! ERROR: Post "https://porkbun.com/api/json/v3/dns/retrieveByNameType/s1240.com/A/@": EOF
2022/08/09 00:45:22 配置文件已保存在: /root/.ddns_go_config.yaml
2022/08/09 00:45:22 请求接口https://porkbun.com/api/json/v3/dns/retrieveByNameType/s1240.com/A/@失败! ERROR: Post "https://porkbun.com/api/json/v3/dns/retrieveByNameType/s1240.com/A/@": EOF
2022/08/09 00:46:03 请求接口https://porkbun.com/api/json/v3/dns/retrieveByNameType/s1240.com/A/@失败! ERROR: Post "https://porkbun.com/api/json/v3/dns/retrieveByNameType/s1240.com/A/@": EOF
