### ISSUE TITLE
[功能请求]关于登录安全性

### ISSUE THREAD

**Issue by yyxida** [jeessy2/ddns-go#34]
首先非常感谢作者的开发，无论是容器体积还是运行资源都非常轻量，还拥有网页控制台，功能齐全。

提一个小小的建议,希望能够提升一下登陆的安全性（当然我是没有看，也看不懂源码XD，不知道现在的登陆是如何实现的，如果已经有安全措施的话，希望作者能简单讲解一下，让我学习一些知识，感谢！）。
我的使用环境是群晖，使用了IPV6，可以直接用“群晖的V6:端口”访问到控制台，这个功能个人觉得有点还是不安全，希望能加入一些保护措施，比如不允许v4/v6公网访问，或者是使用一些加密方式登录，HTTPS之类的。

最后再次感谢作者的开发！

**Comment by yyxida** [comment]
> 首先非常感谢作者的开发，无论是容器体积还是运行资源都非常轻量，还拥有网页控制台，功能齐全。
> 
> 提一个小小的建议,希望能够提升一下登陆的安全性（当然我是没有看，也看不懂源码XD，不知道现在的登陆是如何实现的，如果已经有安全措施的话，希望作者能简单讲解一下，让我学习一些知识，感谢！）。
> 我的使用环境是群晖，使用了IPV6，可以直接用“群晖的V6:端口”访问到控制台，这个功能个人觉得有点还是不安全，希望能加入一些保护措施，比如不允许v4/v6公网访问，或者是使用一些加密方式登录，HTTPS之类的。
> 
> 最后再次感谢作者的开发！

**Comment by jeessy2** [comment]
可以设置登陆帐号和密码的。

**Comment by jeessy2** [comment]
v2.4.0后支持`禁止从公网访问`
