### ISSUE TITLE
通过网卡获得ipv6怎么编写正则表达式获得不是第一个的ipv6

### ISSUE THREAD

**Issue by zhanghuaiqiang** [jeessy2/ddns-go#341]
您好:
windows10 在使用网卡获取ipv6时默认是第一个全局ipv6地址,请问怎么编写正则表达式指定第二个或者第三个谢谢.

**Comment by jeessy2** [comment]
正则是匹配有规律v6地址。如果要指定第二、三个，还没实现，欢迎PR

**Comment by zhanghuaiqiang** [comment]
> 正则是匹配有规律v6地址。如果要指定第二、三个，还没实现，欢迎PR

谢谢

**Comment by gdy666** [comment]
只需要先判断reg变量是不是纯数字,是纯数字就按IP列表索引取地址,不是纯数字就按照原来的正则匹配,实现起来比较简单.

**Comment by mm2231031** [comment]
IPv6通常会分隐私地址和真实地址，入网只能是真实地址，不一定在网卡第一个，用ip -6 addr show查看，隐私地址标注 scope global dynamic mngtmpaddr noprefixroute，真实地址标注scope global dynamic noprefixroute，如果工具能对这个做出判断就最好了

**Comment by babyvox550** [comment]
我有效的ipv6地址尾号固定是b295,首号为240e,请问能使用正则表达式吗？
能否帮忙编写一下表达式？谢谢

**Comment by jeessy2** [comment]
> 我有效的ipv6地址尾号固定是b295,首号为240e,请问能使用正则表达式吗？
> 
> 能否帮忙编写一下表达式？谢谢

直接输入固定位。b295

**Comment by babyvox550** [comment]
240e:([0-9a-fA-F]{1,4}:){1,6}c666
表示240e开头，c666结尾的ipv6地址。
一般c666是mac地址尾号

**Comment by jeessy2** [comment]
> 240e:([0-9a-fA-F]{1,4}:){1,6}c666
> 
> 表示240e开头，c666结尾的ipv6地址。
> 
> 一般c666是mac地址尾号

直接固定位c666就可以了。搞这么复杂干啥

**Comment by babyvox550** [comment]
> 

有好几个c666
