### ISSUE TITLE
4.0.0 RecordId没用

### ISSUE THREAD

**Issue by whx1024** [jeessy2/ddns-go#343]
## 问题描述
正式版v4.0.0阿里云解析
设置recordId没用，解析时候乱改

## 是否已搜索同类问题
- [✓] 已搜索已能解决
Redstone_dev版本正常
https://github.com/jeessy2/ddns-go/pull/319

## 环境
- 操作系统: Windows
- ddns-go版本: 4.0.0
- 安装方式: 服务

## 截图
自己测试下？就明白了

**Comment by jeessy2** [comment]
4.0.1修复了。以前没考虑只有RecordId的情况
