### ISSUE TITLE
bug: ipv6 获取不稳定

### ISSUE THREAD

**Issue by wangliangliang2** [jeessy2/ddns-go#347]
【问题复现】
ipv4 和ipv6的获取都通过：https://cloudflare.com/cdn-cgi/trace 获取。多次使用即可复现。
原因应该是因为DialContext的network的默认参数应该是"tcp" 导致会随机使用某一协议.

[问题处在这个函数：](https://github.com/jeessy2/ddns-go/blob/11738d6c337eb9914b78020e1e089215fd726302/util/http_client_util.go#L24)
该函数可以添加参数改成类似如下：

func CreateNoProxyHTTPClient(protocol string) *http.Client {
	return &http.Client{
		Timeout: 30 * time.Second,
		Transport: &http.Transport{
			// no proxy
			// from http.DefaultTransport
			DialContext: func(ctx context.Context, network, address string) (net.Conn, error) {
				return dialer.DialContext(ctx, protocol, address)
			},
			ForceAttemptHTTP2:     true,
			MaxIdleConns:          100,
			IdleConnTimeout:       90 * time.Second,
			TLSHandshakeTimeout:   10 * time.Second,
			ExpectContinueTimeout: 1 * time.Second,
		},
	}
}

在这两处使用类似：client := util.CreateNoProxyHTTPClient("tcp4") client := util.CreateNoProxyHTTPClient("tcp6")
[ipv4获取处](https://github.com/jeessy2/ddns-go/blob/11738d6c337eb9914b78020e1e089215fd726302/config/config.go#L150)
[ipv6获取处](https://github.com/jeessy2/ddns-go/blob/11738d6c337eb9914b78020e1e089215fd726302/config/config.go#L210)

**Comment by jeessy2** [comment]
这样指定，似乎也可以。来个PR

**Comment by wangliangliang2** [comment]
我是不想提PR所以才写这么详细的，方便的话，你直接改吧。
