### ISSUE TITLE
有没有发现最近DDNS-GO；运行无反应

### ISSUE THREAD

**Issue by 13155836235** [jeessy2/ddns-go#353]
从周六开始；DDNS-GO 开始不执行获取IP操作；
一直停留在；然后不执行获取IP；
怀疑是不是接口不能再使用了？

单独使用了启用IPv4；
未使用DNS服务商；

2022/08/10 11:18:46 监听 :9876 ...
2022/08/10 11:18:46 第一次运行将等待 20 秒后运行 (等待网络)

**Comment by 13155836235** [comment]
更换了网关，网络环境；甚至更换WIN环境；DOCKER环境皆不能使用

**Comment by jeessy2** [comment]
截个图看下配置

**Comment by 13155836235** [comment]
![image](https://user-images.githubusercontent.com/59426202/183821182-7e5920d1-38a3-443d-8cad-36f393062c91.png)

**Comment by jeessy2** [comment]
你域名都没加，怎么ddns😓

**Comment by 13155836235** [comment]
我需求就是  公网IP变动了，能够发送下通知就行

**Comment by 13155836235** [comment]
如何配置呢？不需要DDNS功能

**Comment by 13155836235** [comment]
我之前设置都是正常的。就周六开始后面就不工作了

**Comment by jeessy2** [comment]
> 我需求就是 公网IP变动了，能够发送下通知就行

不知道你以前怎么成功的，加一个假的域名，使用callback，添一个实际不存在的url
