### ISSUE TITLE
建议添加更改服务运行端口的功能

### ISSUE THREAD

**Issue by PencilNavigator** [jeessy2/ddns-go#354]
rt，因为个人需要，需要在同一台服务器ddns两个域名。但因为这两个域名dns服务分别在Cloudflare和阿里云上，程序也仅提供单选一个服务商的功能。希望可以方便的更改端口号，同时运行多个ddns-go程序实例。
可以在程序目录添加一个config文件，方便调整参数，或者在网页端增加一个端口号设置的选项。

本人编程及其的菜，PR的代码不一定会好。

**Comment by jeessy2** [comment]
可以把域名的dns转到同一个服务商
修改端口和配置文件首页有说明的，参考配置一下
https://github.com/jeessy2/ddns-go

**Comment by PencilNavigator** [comment]
> 可以把域名的dns转到同一个服务商 修改端口和配置文件首页有说明的，参考配置一下 https://github.com/jeessy2/ddns-go

我在阿里云的域名不支持CF的DDNS（因为是Freenom免费域名），CF上的域名开启小黄云不支持RDP（网站需要CF的加速因为服务器为纯公网IPv6服务器）。要是可以我早这么干了。

能否将默认的配置文件存储路径设为程序所在路径文件夹而不是Users路径呢，因为如果运行多实例可能会导致一些问题。例如我这种运行多实例的就会被迷惑到。

**Comment by jeessy2** [comment]
自定义路径随便指定

**Comment by allonmymind** [comment]
请问我开两个ddnsgo容器如何更改监听端口？docker-compose定义不同的端口跑不起来提示9876被占用

**Comment by jeessy2** [comment]
> 请问我开两个ddnsgo容器如何更改监听端口？docker-compose定义不同的端口跑不起来提示9876被占用

首页不是写了？
支持启动带参数 -l监听地址 -f间隔时间(秒)

**Comment by jeessy2** [comment]
5.0.0已支持 https://github.com/jeessy2/ddns-go/releases/tag/v5.0.0
