### ISSUE TITLE
请求作者实现获取地址的“路由功能”

### ISSUE THREAD

**Issue by victorxtx** [jeessy2/ddns-go#355]
## 问题描述
ddns-go 已启动，已通过网页界面 IP:9876 进入管理页面
在 IPv4 - 获取IP方式 部分
  如果选择“通过接口获取”，在多网卡和多线路系统中无法选择特定的网卡获取公网 IP；
  如果选择“通过网卡获取”，则直接获取到了网卡地址，这个地址通常是本地内网地址，而非公网地址；
能不能在第二项“通过网卡获取”界面，实现“选择特定网卡，并通过这块网卡获取公网地址”，就是实现路由选择功能？

## 是否已搜索同类问题
- [ 打钩 ] 已搜遍所有搜索引擎，未能解决

## 环境
- 操作系统: linux, windows10, windows7, docker20.9 都测试过，无法选择路由
- ddns-go版本: 3.6 开始一直到 3.7（4.0未测试）
- 安装方式: docker/服务、仅后台 都试过

## 截图
不用截图了

**Comment by jeessy2** [comment]
`通过网卡获取` 建议在拨号那个路由器上安装才获取得到公网。
如果安装不起的话只能通过接口获取

**Comment by wangzixuan-12335** [comment]
确实那个ipv4接口总是请求出错，我自己写了一个获取接口
http://124.221.143.174/ip/
暂时解决了这个问题，但我不保证什么时候这个接口挂掉（服务器还剩半年呜呜呜）
![image](https://user-images.githubusercontent.com/54347655/184652535-a4ad6fdf-17a0-4e74-b42f-9923fe343579.png)

**Comment by victorxtx** [comment]
> `通过网卡获取` 建议在拨号那个路由器上安装ddns-go才获取得到公网。 如果安装不起的话只能通过接口获取

其实我这边的问题就是选用了低端ROM的硬路由做了网关，主要是图NAT的低延迟。
这个问题已经困扰我两年了，我会继续探索

**Comment by jeessy2** [comment]
可以通过路由器的路由功能实现，要看你路由器支持不

**Comment by victorxtx** [comment]
> 可以通过路由器的路由功能实现，要看你路由器支持不
这不是路由器问题，是ddns-go挂在内网服务器上，服务器有两个网卡，两个网卡分别接了两个路由器，两个路由器拨号出去。
感觉应该在服务器这边做网络虚拟化配置，这个太难实现了

**Comment by jeessy2** [comment]
> > 可以通过路由器的路由功能实现，要看你路由器支持不
> > 这不是路由器问题，是ddns-go挂在内网服务器上，服务器有两个网卡，两个网卡分别接了两个路由器，两个路由器拨号出去。
> > 感觉应该在服务器这边做网络虚拟化配置，这个太难实现了

服务器也可以指定路由，网上可以搜下

**Comment by victorxtx** [comment]
> 

确实是这样，linux3.10 应该可以在内核通过iptables 控制走向。哎，还是我技术不行

**Comment by victorxtx** [comment]
我说的不是这个问题，左边“接口”写的几个地址都可以正常使用，但是右边“网卡”的单选框不能获取公网地址，只能获取内网地址




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月15日(星期一) 晚上10:18
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeessy2/ddns-go] 请求作者实现获取地址的“路由功能” (Issue #355)





 
确实那个ipv4接口总是请求出错，我自己写了一个获取接口
 http://124.221.143.174/ip/
 暂时解决了这个问题，但我不保证什么时候这个接口挂掉（服务器还剩半年呜呜呜）
