### ISSUE TITLE
ipv4地址获取接口故障

### ISSUE THREAD

**Issue by wangzixuan-12335** [jeessy2/ddns-go#356]
## 问题描述
在获取ipv4地址时，
https://api-ipv4.ip.sb/ip
该接口在ddns-go无法获取到返回值(浏览器中可以正常获取到)

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [ ] 未搜索

## 环境
- 操作系统: windows server 2012
- ddns-go版本: 4.0.4
- 安装方式: exe安装包

## 截图
![image](https://user-images.githubusercontent.com/54347655/184654996-26e794c0-65e0-4bc0-acfe-dc4059d023ec.png)

**Comment by jeessy2** [comment]
ip.sb接口有限制的，不用他的就对了
