### ISSUE TITLE
DDNS-GO无法获取到接口返回的IPV6地址，如何解决？

### ISSUE THREAD

**Issue by viewfirst** [jeessy2/ddns-go#358]
test-ipv6.com可以正常获取到ipv6地址；
DDNS-go自带的三个接口网站：
https://myip6.ipip.net
https://speed.neu6.edu.cn/getIP.php
https://v6.ident.me
在手动访问的情况下，也都可以显示IPV6的地址，但是在自动获取的情况下，均提示失败。

“2022/08/20 23:48:57 获取IPv6结果失败! 接口: https://myip6.ipip.net ,返回值:
2022/08/20 23:48:57 连接失败! [点击查看接口能否返回IPv6地址](https://speed.neu6.edu.cn/getIP.php), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/08/20 23:48:57 连接失败! [点击查看接口能否返回IPv6地址](https://v6.ident.me/), 官方说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2022/08/20 23:48:57 未能获取IPv6地址, 将不会更新”

目前路由器为AC86U，最新的官改固件，代理插件已经关闭。
DDNS-GO采用的docker版本，安装在威联通NAS上，通过路由器拨号访问网络。
NAS本身没有设置任何代理。

请问如何解决这一问题？

补充说明：
ddns-go同时启用了ipv4，目前ipv4解析正常。
ipv6与ipv4所解析的域名为同样的域名。
DNS服务商为Dnspod

**Comment by jeessy2** [comment]
通过网卡能获取IPv6地址不？
更新频率多少

**Comment by viewfirst** [comment]
> 通过网卡可以获取IPv6地址不？ 更新频率多少

选择通过网卡会提示“没有找到可用的网卡”，说到这个我突然想起来，难道是因为NAS的docker是走的NAT？
可是这无法解释为什么能获取到IPV4的地址。

更新频率是指？我没有看到这个选项，从日志来看，应该是每五分钟会对比一次IP，五次后与DNS服务商对比？

**Comment by jeessy2** [comment]
用docker host模式

**Comment by viewfirst** [comment]
> 用docker host模式

感谢。修改host模式之后，问题解决了。

**Comment by cl-Rainful** [comment]
@viewfirst 请问你用的docker镜像是哪个版本的 我现在使用4.4.1版本在群晖920和r2s 两个上面即使使用了host模式 在ipv6那一栏里面还是无法找到可用的网卡。ipv4那里倒是可以看见docker和常规网卡

**Comment by viewfirst** [comment]
> @viewfirst 请问你用的docker镜像是哪个版本的 我现在使用4.4.1版本在群晖920和r2s 两个上面即使使用了host模式 在ipv6那一栏里面还是无法找到可用的网卡。ipv4那里倒是可以看见docker和常规网卡

3.7.2

**Comment by z1521183003** [comment]
你好，我也出现了这个问题，image: jeessy/ddns-go:v4.5.9  laster 也是一样的问题
使用的是 host 网络
![image](https://user-images.githubusercontent.com/29905356/224526349-bce97db2-e153-4d89-8d3c-7b66e67c7ec0.png)
宿主机可以获取到IPV6 
![image](https://user-images.githubusercontent.com/29905356/224526396-c2311755-4aa4-4efa-8b07-0c943a4a1505.png)

**Comment by WaterLemons2k** [comment]
> 你好，我也出现了这个问题，image: jeessy/ddns-go:v4.5.9 laster 也是一样的问题
> 使用的是 host 网络
> ![image](https://user-images.githubusercontent.com/29905356/224526349-bce97db2-e153-4d89-8d3c-7b66e67c7ec0.png)
> 宿主机可以获取到IPV6
> ![image](https://user-images.githubusercontent.com/29905356/224526396-c2311755-4aa4-4efa-8b07-0c943a4a1505.png)

可能是这个接口的问题，换一个呢？
