### ISSUE TITLE
关于OpenWrt自启动问题

### ISSUE THREAD

**Issue by sdyby2006** [jeessy2/ddns-go#359]
目前软路由重启的时候会自动删除/tmp/upload下的文件，根据软件err文件记录，启动软件时如果无法找到该目录下的文件会导致启动失败，是否可以在安装过程中把软件复制到/usr/local下的文件夹，然后启动时指定路径为/usr/local/，避免软路由重启时找不到文件的问题？

**Comment by jeessy2** [comment]
这个自行复制后，在安装服务

**Comment by sdyby2006** [comment]
> 这个自己复制后，在安装服务

好的，之前看日志以为是内部写死的，谢谢
