### ISSUE TITLE
关于对路由器插件的支持

### ISSUE THREAD

**Issue by bakeair** [jeessy2/ddns-go#360]
## 环境
- 操作系统:merlin 386.5_2 
- ddns-go版本: 4.0.4
- 安装方式:

**Comment by jeessy2** [comment]
没有专门的插件
通过ssh进入，安装服务能运行不？

**Comment by bakeair** [comment]
> 没有专门的插件 通过ssh进入，安装服务能运行不？

尝试了下，还的确可以，我路由器内核是armv7l的，用ddns-go armv6版的可以正常运行

**Comment by jeessy2** [comment]
ok
