### ISSUE TITLE
在休眠时无法更新映射

### ISSUE THREAD

**Issue by yangchao4** [jeessy2/ddns-go#361]
## 问题描述
-ip改变时计算机处于休眠状态，但无法更新ip地址，导致无法连接
## 是否已搜索同类问题
- [ ] 已搜索未能解决
- 

## 环境
- 操作系统: win11

是否能给予权限，在休眠时每天一次获取ip地址后映射

**Comment by jeessy2** [comment]
看下日志，休眠在请求接口没有
