### ISSUE TITLE
密码忘记了怎么办

### ISSUE THREAD

**Issue by fenghai2ni** [jeessy2/ddns-go#362]
在设置的时候设置了密码 第二次用的时候密码死活都不对 不知道有没有办法重置密码?

**Comment by jeessy2** [comment]
查看配置文件，里面有

**Comment by fenghai2ni** [comment]
> 查看配置文件，里面有

感谢 之前文件属性为只读看不到 改了属性以后查看到了 原来在之前输入密码的时候少输入了一位...
