### ISSUE TITLE
ddns-telegram-bot挂了吗？

### ISSUE THREAD

**Issue by ChenGaber** [jeessy2/ddns-go#365]
ddnsgo的日志提示
2022/08/28 11:15:30 请求接口https://ddns-bot.vercel.app/api/hook/（隐藏）失败! ERROR: Post "https://ddns-bot.vercel.app/api/hook/（隐藏）?": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
RequestBody填写：
{
    "ipv4": {
        "result": "#{ipv4Result}",
        "addr": "#{ipv4Addr}",
        "domains": "#{ipv4Domains}"
    }
}

**Comment by jeessy2** [comment]
vercel应该是被墙了

**Comment by ChenGaber** [comment]
> vercel应该是被墙了

vercel.com能直接访问

**Comment by jeessy2** [comment]
> > vercel应该是被墙了
> 
> vercel.com能直接访问

vercel.app被封，无解

**Comment by allonmymind** [comment]
> > > vercel应该是被墙了
> > 
> > 
> > vercel.com能直接访问
> 
> vercel.app被封，无解

可以自己设置反代api吗

**Comment by jeessy2** [comment]
> > > > vercel应该是被墙了
> > > 
> > > 
> > > vercel.com能直接访问
> > 
> > 
> > vercel.app被封，无解
> 
> 可以自己设置反代api吗

自行研究

**Comment by walkxspace** [comment]
@allonmymind 可以换成同样支持 Telegram 通知的饭碗警告，配置可参见 https://github.com/jeessy2/ddns-go/issues/327#issuecomment-1198824757

**Comment by jeessy2** [comment]
使用telegram，相信拦不到各
