### ISSUE TITLE
Code:98 新增域名解析失败

### ISSUE THREAD

**Issue by cicai1631** [jeessy2/ddns-go#366]
## 问题描述
- 误删dnspod ID 和密码，我重新创建后，无法访问，我升级了docker容器到4.04，目前情况是之前的域名可以正常访问，但是无法新增二级域名？

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [] 未搜索

## 环境
- 操作系统: 群晖7
- ddns-go版本: 4.04
- 安装方式: docker

## 截图
![Screenshot_20220829_081849.jpg](https://user-images.githubusercontent.com/80252289/187101077-44c24c6a-1d8f-43c7-b666-606c3764791c.jpg)

**Comment by jeessy2** [comment]
看说明有可能是你的ip被dnspod封了

**Comment by cicai1631** [comment]
> 看说明有可能是你的ip被dnspod封了

目前访问正常，但是ddns-go还提示无法新增域名，ip非法

**Comment by cicai1631** [comment]
> IP被封，重新拨号换个ip试试

你好，已经重拨
新增域名解析 nas.xxx.top 失败！Code: 98, Message: 您的IP非法，请求被拒绝Code: 98, Message: 您的IP非法，请求被拒绝

**Comment by jeessy2** [comment]
你发一个工单问下dnspod

**Comment by cicai1631** [comment]
> 你发一个工单问下dnspod

已经问了，明天回复我

**Comment by cicai1631** [comment]
> 你发一个工单问下dnspod

已经解决，设置问题
