### ISSUE TITLE
部署后，可以获取ip，但是提示获取失败。无法识别ip

### ISSUE THREAD

**Issue by wingser** [jeessy2/ddns-go#368]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
部署后，Ipv4，使用接口获取ip，提示如下。
2022/08/29 16:00:40 连接失败! [点击查看接口能否返回IPv4地址](https://ip.3322.net/),
2022/08/29 16:00:50 连接失败! [点击查看接口能否返回IPv4地址](https://myip4.ipip.net/),
2022/08/29 16:01:00 连接失败! [点击查看接口能否返回IPv4地址](https://ddns.oray.com/checkip),
2022/08/29 16:01:00 未能获取IPv4地址, 将不会更新

出现以上问题，导致cloudflare挂ddns失败，但是真正点开上述连接时候，发现可以正常获取公网ip

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [] 未搜索

## 环境
- 操作系统: debain
- ddns-go版本: 4.0.4
- 安装方式: 服务

## 截图
![image](https://user-images.githubusercontent.com/13481389/187245384-c3754435-c813-4b32-bb9c-18ef60151f00.png)

**Comment by jeessy2** [comment]
1. 更新频率设置的多少？

2. 需要在Debian系统中执行 curl https://myip4.ipip.net
打开链接是浏览器所在系统在访问，不是安装ddns-go的系统运行的

**Comment by wingser** [comment]
查到问题了，是在pve下的debian问题，我直接把程序放到了pve主机上就可以了。多谢大佬的热心解答。
