### ISSUE TITLE
能否添加关闭 web 服务的功能？

### ISSUE THREAD

**Issue by powersee** [jeessy2/ddns-go#37]
非常感谢大佬开发的 ddns-go，我用的是腾讯云，配置好 域名、id 和 token 就可以自动更新记录了，非常方便。

但是我想，能否添加一个关闭 web 服务的功能？这样只需要第一次使用网页填好配置，以后就让 web 处于关闭状态。这样会不会安全性会更强一点？

当然现在可以通过设置账号密码来提高安全性，但是感觉要是能够选择是否关闭 web，可能会更好一些。

**Comment by jeessy2** [comment]
这个操作性不强吧。可以试下2.1.0版本，可禁止从外网访问

**Comment by powersee** [comment]
好的，多谢。
