### ISSUE TITLE
日志能否存储到一个单独的log文件内？

### ISSUE THREAD

**Issue by yxnwh** [jeessy2/ddns-go#370]
目前的log都是显示在网页上，而且只能显示大概4个小时内的log（默认TTL），能否在网页显示的同时，将全部日志存储到一个单独log文件内，并能映射到主机上打开查看？

**Comment by jeessy2** [comment]
有单独的日志，根据系统不同查看和存放位置也不同

**Comment by yin1999** [comment]
Linux的绝大多数守护进程管理工具均提供了日志功能，目前常用的 `systemd` 会默认记录程序的 `stderr` 和 `stdout`，而 Docker 也会默认记录进程的输出。将日志功能集成到 ddns 中将不得不考虑不同系统、守护进程的差异（例如 Docker，我们应该在检测到执行环境为 docker 时默认不选择记录日志到文件，因为 docker 提供了日志服务，且应该尽量保持其“无状态”的特性）。

我认为仅通过 stderr 或 stdout 输出日志是比较合理的做法。
