### ISSUE TITLE
安装 ddns-go 服务成功! 请打开浏览器并进行配置。

### ISSUE THREAD

**Issue by ardeal** [jeessy2/ddns-go#372]
你好，
在ubuntu安装之后，提示：
·’安装 ddns-go 服务成功! 请打开浏览器并进行配置。·

我应该在这个ubuntu的机器上打开浏览器配置吗？
还是在哪里打开浏览器配置？

如果要配置这个DDNS，例如，输入腾讯的id、key之类的的信息，我应该在浏览器地址栏输入什么？

运行ddns-go的时候，如果使用yaml配置，那么，yaml的格式怎样写？有示例吗？

我是配置这个DDNS软件，还是配置腾讯的账户里面的信息？

**Comment by jeessy2** [comment]
随便在内网的一台电脑打开浏览器，地址栏输入ubuntu的IP:端口

**Comment by ardeal** [comment]
端口是多少呢？

**Comment by jeessy2** [comment]
9876
首页有说明参考一下

**Comment by ardeal** [comment]
看到了，谢谢！

网页打开之后，选择腾讯云，
然后配置IPv4中的选项就可以了，对吗？
IPv4中， ·通过接口获取· 和·通过网卡获取·，是不是指服务器通过哪里获取全局ip地址啊？

我现在的网络配置是，路由器链接公网，有动态全局ip。路由器做了一级子网，我的ubuntu机器（安装ddns-go）就在子网里面。

**Comment by jeessy2** [comment]
IPv4通过接口获取就可以了

**Comment by ardeal** [comment]
对于我来说，这个页面，只需要把ID和Token填写好，就可以了，对吗？

**Comment by jeessy2** [comment]
域名要填写，其他有说明，自己多看多练，试试就知道，很简单的。

**Comment by ardeal** [comment]
哦哦哦，，·通过接口获取·，下面有好几个域名，那是什么呀？
这几个域名下面的 ·Domains·，就是填写我自己的域名，对吧？

**Comment by jeessy2** [comment]
你可以试试填别人的😓

**Comment by ardeal** [comment]
https://myip4.ipip.net, https://ddns.oray.com/checkip, https://ip.3322.net
上面的这几个域名，我需要修改、或增加吗？

**Comment by jeessy2** [comment]
不用

**Comment by jeessy2** [comment]
搞不明白的，就不动
