### ISSUE TITLE
4.1.0 macos x64 下拿不到ip

### ISSUE THREAD

**Issue by gkl1368** [jeessy2/ddns-go#381]
macos 12.6 x86_64 ddns-go 4.1.0 拿不到ip，报如下错误，浏览器打开和终端下curl是可以正常拿到ip的。
<img width="327" alt="image" src="https://user-images.githubusercontent.com/12904884/190460522-b3c5e262-bd0d-41c1-bb36-b546ee1c61cb.png">

**Comment by jeessy2** [comment]
和版本没关系吧，没改网络那块，只是加了打印日志，我的mac都能正常使用

在Mac上通过curl请求正常不？

**Comment by gkl1368** [comment]
curl 可以正常拿到ip 浏览器也可以正常获取ip

**Comment by jeessy2** [comment]
你是不是没允许ddns-go接入网络，mac os要弹出一个框，点击确定没有？
```
您要应用程序“ddns-go”接受传入网络连接吗？
```

**Comment by jeessy2** [comment]
把防火墙关了，在重新登陆测下就知道了

**Comment by gkl1368** [comment]
解决了 果然是防火墙问题。 谢谢
