### ISSUE TITLE
esxi下安装错误

### ISSUE THREAD

**Issue by chindongkainw** [jeessy2/ddns-go#382]
## 问题描述

 安装 ddns-go 服务失败, ERR: readlink /proc/self/exe: no such file or directory

## 是否已搜索同类问题
- [x] 已搜索未能解决

## 环境
- 操作系统: ESXi6.7.0 
- ddns-go版本: v4.1.0
- 安装方式: 二进制文件

**Comment by jeessy2** [comment]
对主流系统支持比较好，esxi可能支持不怎么好，自行研究一下其他方式了
