### ISSUE TITLE
DDNS后如何配置电脑,让其可以通过域名访问到电脑对应端口呢?

### ISSUE THREAD

**Issue by hzhh110** [jeessy2/ddns-go#384]
## 问题描述
- How do I configure the computer to access the corresponding port of the computer through the domain name after DDNS?

## 是否已搜索同类问题
- [ ] 已搜索未能解决
- [x] 未搜索

## 环境
- 操作系统:  MAC 
- ddns-go版本: 4.0.4
- 安装方式: docker/服务

**Comment by jeessy2** [comment]
out of ddns scope! please google
