### ISSUE TITLE
自定义URL ipv4 和 ipv6 参数名不一样 导致 只能更新其一

### ISSUE THREAD

**Issue by aeeq** [jeessy2/ddns-go#387]
## 问题描述

- 比如这家 ddns 服务商 www.dynu.com v4 v6 参数分别是 myip 和 myipv6
https://api.dynu.com/nic/update?username=&password=&hostname=#{domain}&myip=#{ip}&myipv6=#{ip}
更新 v6 时，传到 v4的值不是v4格式，如果 IP 地址未作为请求的一部分发送，API 服务器将使用发起请求的 IP 地址,
但可能是国外的服务器，经过了很多服务器，实际上不是我真正的ipv4。v6 更新正常了，v4又不对了
建议 v6 v4 的 URL 可以分开设置
## 是否已搜索同类问题
- [x] 已搜索未能解决
- [x] 未搜索

## 环境
- 操作系统: 
- ddns-go版本: 
- 安装方式: 服务

**Comment by aeeq** [comment]
找到设置方法，用自定义参数可以实现
URL https://api.dynu.com/nic/update?username=&password=&hostname=#{domain}&myip=#{myip}&myipv6=#{myipv6}

V4 Domains hostname?myipv6=no&myip=#{ip}
V6 Domains aeeq.giize.com?myip=no&myipv6=#{ip}

**Comment by Duke-li** [comment]
> 找到设置方法，用自定义参数可以实现 URL [https://api.dynu.com/nic/update?username=&password=&hostname=#{domain}&myip=#{myip}&myipv6=#{myipv6}](https://api.dynu.com/nic/update?username=&password=&hostname=#%7Bdomain%7D&myip=#%7Bmyip%7D&myipv6=#%7Bmyipv6%7D)
> 
> V4 Domains hostname?myipv6=no&myip=#{ip} V6 Domains hostname?myip=no&myipv6=#{ip}

不好意思，没太看懂这个是是啥意思。
