### ISSUE TITLE
porkbun请求接口失败

### ISSUE THREAD

**Issue by kzlong** [jeessy2/ddns-go#388]
022/09/26 01:30:46 请求接口 https://porkbun.com/api/json/v3/dns/retrieveByNameType/bbki288.dev/A/www 失败! 返回内容: {"status":"ERROR","message":"Invalid API key. (002)"} ,返回状态码: 400
有用porkbun域名的吗，我按照porkbun的API文档说明新创建了密钥，设置里也打开了允许API访问，也还是失败了，看原因还是说API key的问题，不知道哪里出问题了
![搜狗截图20220926013146](https://user-images.githubusercontent.com/43065397/192157165-0195c502-f448-42e9-b16b-e35ef6f5123a.png)

**Comment by jeessy2** [comment]
提示你Invalid API key

重新创建一个。一看你的key就不正确，key和secret长度是相同的

**Comment by kzlong** [comment]
感谢，今天早上重新生成就可以了，昨天重新生成的不知道怎么不行。。
