### ISSUE TITLE
群晖NAS下docker安装设置完成后报错

### ISSUE THREAD

**Issue by wangjie8810** [jeessy2/ddns-go#389]
Cloudflare设置后报错2022/09/27 11:45:18 请求接口 https://api.cloudflare.com/client/v4/zones?name=8810.ga&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400

**Comment by jeessy2** [comment]
查看创建的token是否正确
`创建令牌->编辑区域 DNS(使用模板)`

**Comment by wangjie8810** [comment]
有微信，微信群，QQ群等其他联系方式吗,下面是我设置的一些信息图片地址
https://sm.ms/image/XO5Zhjf6uRdU439   API界面
https://sm.ms/image/mIYxNdbBS7LCnZe  API一部分
https://sm.ms/image/ly5KnMgJofqtQu4    DDNS-go设置界面
https://sm.ms/image/QRqEzOxltvjfcA3      DDNS-go日志报错界面

**Comment by jeessy2** [comment]
创建API令牌， 不要创建Global令牌
