### ISSUE TITLE
Win10运行不了

### ISSUE THREAD

**Issue by irrocu** [jeessy2/ddns-go#39]
![Snipaste_2021-02-23_01-42-57](https://user-images.githubusercontent.com/66506186/108747794-d0878600-7578-11eb-9555-de8ddd89d0ee.jpg)

**Comment by irrocu** [comment]
ddns-go_2.4.2_Windows_x86_64

**Comment by jeessy2** [comment]
我可以运行，要看你系统什么32位还是64位。可以用兼容模式运行或下载ddns-go_2.4.2_Windows_i386.tar.gz试试

**Comment by dataminingstrongly** [comment]
我的win10也运行不了。。。请问怎么解决？

**Comment by jeessy2** [comment]
> 我的win10也运行不了。。。请问怎么解决？

你的报什么错

**Comment by dataminingstrongly** [comment]
您好，我的win10专业版版本是1901，然后打开.exe也是显示这样。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeessy2/ddns-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 上午7:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeessy2/ddns-go] Win10运行不了 (#39)





  
我的win10也运行不了。。。请问怎么解决？
  
你的报什么错

**Comment by jeessy2** [comment]
> 您好，我的win10专业版版本是1901，然后打开.exe也是显示这样。

以管理员身份运行或以兼容模式运行，还有看你win10是32位还是64位的，要单独下载对应文件

**Comment by dataminingstrongly** [comment]
64位的，管理员和兼容模式都试过了，另外我在win7的电脑也尝试了下，发现也是报错

**Comment by jeessy2** [comment]
> 64位的，管理员和兼容模式都试过了，另外我在win7的电脑也尝试了下，发现也是报错

下载的是不是`ddns-go_2.8.3_Windows_x86_64.tar.gz`64版本的。或你重新下一个试试
我本地可以运行的

**Comment by dataminingstrongly** [comment]
> > 64位的，管理员和兼容模式都试过了，另外我在win7的电脑也尝试了下，发现也是报错
> 
> 下载的是不是`ddns-go_2.8.3_Windows_x86_64.tar.gz`64版本的。或你重新下一个试试
> 我本地可以运行的

那里好像只有Windows_x86_64.tar.gz，不知道下载的是`不是64版本的....

**Comment by jeessy2** [comment]
> 那里好像只有Windows_x86_64.tar.gz，不知道下载的是`不是64版本的....

那你重新在github下一个

**Comment by dataminingstrongly** [comment]
你好，尝试了还是不行，我在另外的win10家庭版1909版本的电脑顺利运行，但专业版的运行不了

**Comment by jeessy2** [comment]
> 你好，尝试了还是不行，我在另外的win10家庭版1909版本的电脑顺利运行，但专业版的运行不了

那你检查下运行环境，关一些杀毒的试试吧
或者升级操作系统 / 或使用docker

**Comment by Aerithlon** [comment]
Win10 企业版 LTSC 2019正常运行，CentOS 8 正常运行，ddns-go版本2.9.1，非常好的应用，突然发现了一个宝藏，感谢。
