### ISSUE TITLE
最近更新后不能自动更新ipv6地址

### ISSUE THREAD

**Issue by Depressboy** [jeessy2/ddns-go#393]
## 问题描述
- esxi安装的群晖7系统，使用套件安装ddns-go，使用callback更新ipv6，ddns服务商是he.net。最近几次更新后即使群晖的ipv6发生改变，日志里面还是提示   “你的IPv6未变化, 未触发Callback”，在套件商店里面停用套件后重新启用就能更新一次ipv6，但是下次发生改变后也是不能自动更新。

## 是否已搜索同类问题
- [x ] 已搜索未能解决

## 环境
- 操作系统: 群晖7.1
- ddns-go版本: v4.1.0
- 安装方式: 服务

## 截图
![搜狗截图20220928211640](https://user-images.githubusercontent.com/26180798/192788912-65c49368-43be-41a2-981d-0e5580df2f7f.jpg)
![搜狗截图20220928211845](https://user-images.githubusercontent.com/26180798/192788939-2b594b02-acf1-4839-bb33-0a19eeb4cbcb.jpg)

**Comment by jeessy2** [comment]
什么方式获取IPv6的

**Comment by jeessy2** [comment]
有可能确实是没变化。
你重启后，会清空缓存，就会重新调用callback

**Comment by Depressboy** [comment]
> 

原先是使用网口获取的，后面发现不能更新后改成了网址获取，还是不能更新
