### ISSUE TITLE
对阿里云三级域名修改时会将第三级域名带入到主机记录中导致第二次无法修改

### ISSUE THREAD

**Issue by congzhengmian** [jeessy2/ddns-go#394]
阿里云三级域名修改时会将第三级域名带入到主机记录中导致第二次无法修改
- [ ] 已搜索未能解决

## 环境
- 操作系统: docker 群晖
- ddns-go版本: 最新
- 安装方式: docker
## 截图
![image](https://user-images.githubusercontent.com/48363002/193057081-63c914c0-86f5-45be-af67-f55307aa7969.png)
![image](https://user-images.githubusercontent.com/48363002/193057410-a0d04fea-76ad-40d7-ac0d-9d239f25f8db.png)

**Comment by jeessy2** [comment]
可以使用冒号分割主机记录，Domains下方有说明
