### ISSUE TITLE
请求支持多个不同域名商下多dockers的host同时运行

### ISSUE THREAD

**Issue by naoki66** [jeessy2/ddns-go#396]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
一个阿里域名，一个dnspod域名，两个服务想同时使用但是
host才能方便选择网卡获取IPV6，但是默认  http://主机IP:9876 会冲突
## 是否已搜索同类问题
- [x ] 已搜索未能解决
- [] 未搜索

## 环境
- 操作系统: 群晖docker
- ddns-go版本: v4.1.1
- 安装方式: docker/服务

## 截图
能否添加个参数，指定web管理界面的9876端口，这样可以多个dockers互不干扰

**Comment by jeessy2** [comment]
参考首页docker配置，写了怎么修改监听端口

**Comment by jeessy2** [comment]
[可选] 支持启动带参数 -l监听地址 -f间隔时间(秒)
docker run -d --name ddns-go --restart=always --net=host jeessy/ddns-go -l :9877 -f 600
