### ISSUE TITLE
钉钉机器人无法报警

### ISSUE THREAD

**Issue by xiaonet** [jeessy2/ddns-go#397]
## 问题描述
-  现状：
- （1）点击“模拟测试webhook”时日志提示 2022/10/03 11:43:11 Webhook调用成功, 返回数据: {"errcode":300001,"errmsg":"msgtype is null"}
- （2）以前是可以正常向钉钉机器人发送报警的，近期发现IP地址变更之后钉钉机器人未进行提醒，参数设置未发生任何变化，更新版本之后依然如此
- （3）添加新的子域名发现阿里域名是可以更新子域名的
- （4）Request参数：{"msg_type": "post","content": {"post": {"zh_cn": {"title": "你的公网IP变了","content": [[{"tag": "text","text": "IPV4地址：#{ipv4Addr}"}] , [{"tag": "text","text": "域名更新结果：#{ipv4Result}"}]]}}}}
-  问题：点击模拟测试钉钉机器人未发送报警，IP变化之后也未发送报警

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [ ] 未搜索

## 环境
- 操作系统: rockylinux 9
- ddns-go版本: v4.11
- 安装方式: 服务

## 截图
![image](https://user-images.githubusercontent.com/115051139/193982157-93b50888-7135-4778-9245-21317832c591.png)
![image](https://user-images.githubusercontent.com/115051139/193977845-9039d832-083f-4de9-a30b-6052b26604fe.png)

**Comment by jeessy2** [comment]
你是不是拷贝错了。用的钉钉，拷贝的飞书配置
