### ISSUE TITLE
ddns-go升级版本之后服务无法启动

### ISSUE THREAD

**Issue by xiaonet** [jeessy2/ddns-go#398]
## 问题描述
- 问题
- （1）卸载4.04版本安装新版本4.1.1 之后ddns-go服务未运行
- （2）手动运行./opt/ddns-go正常，直接/opt/ddns-go "-l" ":9876" "-f" "300" "-c" "/root/.ddns_go_config.yaml"也正常
- （3）命令行运行 systemctl start ddns-go服务无法启动

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [ ] 未搜索

## 环境
- 操作系统: Rocky linux9
- ddns-go版本: 4.1.1
- 安装方式: 服务

## 截图
![image](https://user-images.githubusercontent.com/115051139/193984955-d6f002d0-458e-454d-94db-0b5cbbaf512b.png)
![image](https://user-images.githubusercontent.com/115051139/193985102-f61ea31d-1608-41c5-b043-e9b261b0800b.png)

**Comment by jeessy2** [comment]
重启试试

**Comment by xiaonet** [comment]
重启过几次也不行

> 重启试试

**Comment by xiaonet** [comment]
> 重启过几次也不行，我退回了之前的4.0.4版本发现有可以了
> 
> > 重启试试

**Comment by jeessy2** [comment]
看下系统日志，是啥错

**Comment by jeessy2** [comment]
使用journalctl看下日志
