### ISSUE TITLE
feat: 关闭 WEB 服务

### ISSUE THREAD

**Issue by NPCDW** [jeessy2/ddns-go#403]

**Comment by NPCDW** [comment]
能否添加一个启动参数，来控制是否开启 web 服务。

功能请求原因：
1. web 服务使用量很少，一般只有第一次启动以及需要添加域名的时候会用到
2. 持续监听一个端口，会占有一定的资源，即使占用量很小
3. 配置文件并不复杂，直接修改配置文件也能实现添加域名的需求

**Comment by jeessy2** [comment]
监听地址改为`127.0.0.1:9876`也可以实现此功能。

**Comment by yin1999** [comment]
赞同这个提议，如果可以，我愿意提PR，形式：

- 添加运行参数 `--no-web`
- 添加环境变量 `NO_WEB=1`
- 添加到配置文件（目前配置文件仅用于 DDNS 配置，可能并不合适）

我个人比较喜欢第一种。

**Comment by jeessy2** [comment]
可以

**Comment by jeessy2** [comment]
这个用得也少，不如直接监听127.0.0.1来得快
