### ISSUE TITLE
大佬，请问有没有兴趣添加对adguardhome的支持呢？

### ISSUE THREAD

**Issue by tecsar9000** [jeessy2/ddns-go#407]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景

## 是否已搜索同类问题
- [ ] 已搜索未能解决
- [x] 未搜索

## 环境
- 操作系统: 
- ddns-go版本: 
- 安装方式: docker/服务

**Comment by jeessy2** [comment]
？和adguardhome有什么关系

**Comment by tecsar9000** [comment]
不好意思可能我没表述清楚，我意思是能不能添加adguardhome的支持，通过api一类的把最新的ip写入到adguardhome的dns rewrite规则里。这样只有使用自己的dns服务器才能够用域名访问家里的服务，不暴露在公共dns里能增强安全性来着

**Comment by tecsar9000** [comment]
我目前是在公共dns里放一个不用的二级域名用来定位，然后把使用的二级域名rewrite到不用的二级域名上，但这样还是会暴露自己的家宽ip，不够安全，另外网上还有一些还因为dns解析到了家宽然后有web服务被停宽带的例子，直接公共dns解析到家里还是有风险的。因此如果ddnsgo能直接修改adguardhome上的rewrite规则，定时把新ip写进去，那完全可以不使用公共dns，不但安全性更强，而且除非运营商抓包查sni，否则也不可能知道用户有没有wen服务

**Comment by jeessy2** [comment]
dns只是解析域名，用了公共dns也只是说明你解析到那个IP上了。
使用了公共dns不代表能访问内部web服务，担心就不暴露web服务出来，或可以暴露3389远程桌面，通过远程桌面来访问内部服务，或其他方法

**Comment by jeessy2** [comment]
即使运营商想知道你开没开web服务，我猜也是通过扫描端口，看这个IP暴露web服务端口没有，或进行流量识别看是不是http/https流量。和使用公共dns关系不大

**Comment by tecsar9000** [comment]
不开放服务就得用vpn，那样很不方便啊。而用ddns修改adguardhome的重写规则可以做到网页直接访问而不需要连vpn，大佬可以考虑一下。
顺便有说法运营商查web服务是先看有没有域名解析到了家宽ip，然后再看这个域名能不能打开网页，如果不通过公共dns，全程使用adguardhome来提供解析，那可以从源头避免被运营商发现

**Comment by jeessy2** [comment]
你研究通过callback能更新adguardhome配置不？

即使你使用了adguardhome，难道运营商就发现不了你开了web服务？

**Comment by yin1999** [comment]
一般使用非标端口就没事，如果真要查，通过 adguardhome 私密解析 DNS 也没用

**Comment by tecsar9000** [comment]
我看adguardhome api文档里有这段
'/rewrite/add': 'post': 'tags': - 'rewrite' 'operationId': 'rewriteAdd' 'summary': 'Add a new Rewrite rule' 'requestBody': '$ref': '#/components/requestBodies/RewriteEntry' 'responses': '200': 'description': 'OK.' '/rewrite/delete': 'post': 'tags': - 'rewrite' 'operationId': 'rewriteDelete' 'summary': 'Remove a Rewrite rule' 'requestBody': '$ref': '#/components/requestBodies/RewriteEntry' 'responses': '200': 'description': 'OK.'
看起来api是能通过删除新增来更改rewrite的ip的

**Comment by tecsar9000** [comment]
> 一般使用非标端口就没事，如果真要查，通过 adguardhome 私密解析 DNS 也没用

如果用私人dns解析，那应该除非抓包分析sni，否则没有人可以把域名和ip联系起来吧？鉴于连gfw都是只有部分网站是sni封禁，运营商封家宽服务应该没有这么无聊吧？

**Comment by yin1999** [comment]
> 如果用私人dns解析，那应该除非抓包分析sni，否则没有人可以把域名和ip联系起来吧？鉴于连gfw都是只有部分网站是sni封禁，运营商封家宽服务应该没有这么无聊吧？

我了解的是，部分地区的运营商会使用镜像流量分析（并不需要像 gfw 那样实现实时分析和阻断），而且，如果流量比较小，大部分地区的运营商都不会管。如果流量大了，那真需要查的话，也是可以追查到的。我觉得可以先去网上查一下本地运营商的情况。
