### ISSUE TITLE
绝大部分人用不到这个功能，而且实现也有局限性。如果你感兴趣，直接fork自己修改一个版本

### ISSUE THREAD

**Issue by shaojs321** [jeessy2/ddns-go#408]
绝大部分人用不到这个功能，而且实现也有局限性。如果你感兴趣，直接fork自己修改一个版本

_Originally posted by @jeessy2 in https://github.com/jeessy2/ddns-go/discussions/274#discussioncomment-2779872_

其实一直想要这个功能，直接在openwrt上把所有ipv6都ddns，省的每一个都操作。通过pd分发的ipv6应该是有规律的，我看爱快有这个功能，其余的还没找到

**Comment by jeessy2** [comment]
不支持，以前讨论了的，建议搜索一下。
