### ISSUE TITLE
ddns  多个域名解析

### ISSUE THREAD

**Issue by shaojs321** [jeessy2/ddns-go#409]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
- 
- 在ddns  web页面解析同一服务商多个域名，日志显示ok，dnspod页面也ok，tcping显示端口open，但网站只能通过第一个域名访问。我在openwrt和群辉上都试了，都不行。openwrt的dns解析我没动过

## 是否已搜索同类问题
- [ ] 已搜索未能解决

## 环境
- 操作系统: openwrt  群辉
- ddns-go版本: v4.2.0
- 安装方式:   docker

## 截图
<img width="566" alt="Snipaste_2022-10-16_20-15-27" src="https://user-images.githubusercontent.com/56724141/196035734-d7b240e1-525c-4c19-8973-5b0c1f0bcf8f.png">

**Comment by yin1999** [comment]
> dnspod页面也ok

dnspod 上面的域名解析记录都正确是吗？

**Comment by jeessy2** [comment]
检查你网络，和ddns关系不大。我看端口，你用了80端口？强烈不推介80端口，小心运营商找你麻烦

**Comment by shaojs321** [comment]
解决问题，是我电脑上用v2rayn的原因，导致ipv6不能访问，手机登陆就没问题。不过为啥第一个域名能访问也是奇怪
