### ISSUE TITLE
[help wanted] 群晖Ipv6地址可以ping通，但是却无法访问

### ISSUE THREAD

**Issue by luojunyuan** [jeessy2/ddns-go#41]
我在两天前通过ddns-go布置好腾讯dnspod ddns设置，移动网络下外网内网4g网路访问一切正常。今天再次尝试域名访问却遇上这个情况。

解析都是正确的, 解析出来的ipv6可以ping通
```powershell
PS C:\Users\k1mlka> ping  2409:8a6a:ffff:7185:211:32ff:fe12:3456

2409:8a6a:ffff:7185:211:32ff:fe12:3456 に ping を送信しています 32 バイトのデータ:
2409:8a6a:ffff:7185:211:32ff:fe12:3456 からの応答: 時間 =3ms
2409:8a6a:ffff:7185:211:32ff:fe12:3456 からの応答: 時間 =3ms
2409:8a6a:ffff:7185:211:32ff:fe12:3456 からの応答: 時間 =3ms
2409:8a6a:ffff:7185:211:32ff:fe12:3456 からの応答: 時間 =3ms

2409:8a6a:ffff:7185:211:32ff:fe12:3456 の ping 統計:
    パケット数: 送信 = 4、受信 = 4、損失 = 0 (0% の損失)、
ラウンド トリップの概算時間 (ミリ秒):
    最小 = 3ms、最大 = 3ms、平均 = 3ms
```
然后我在浏览器中通过输入`http://[2409:8a6a:ffff:7185:211:32ff:fe12:3456]` 访问页面直接没有回应 (ERR_EMPTY_RESPONSE)，不论我是用电脑还是手机，wifi还是流量效果都相同。直接访问域名更是没效果。ax3pro直接拨号并且之前就关闭了防火墙的，尝试了运维大法重启ax3pro和光猫，结果任然如旧。

这个应该与ddns-go无关，希望能得到作者或者知慧的人的帮助/(ㄒoㄒ)/~~ 两天前刚弄好都还正常现在突然不行了是真的难受😫

**Comment by luojunyuan** [comment]
群晖网络ipv6信息

![image](https://user-images.githubusercontent.com/28323948/108917309-e2e5ea80-7672-11eb-8f68-b937fbd2bd8b.png)

我使用ping访问，或者解析得到的对应都是第一条ipv6

另外我感觉ipv6地址变化的频率有点快，两天前似乎不这样。

**Comment by jeessy2** [comment]
通过内网ip 192.168.3.9能访问不

**Comment by luojunyuan** [comment]
> 通过内网ip 192.168.3.9能访问不

目前就是靠这个ip访问、也只有这个方法

**Comment by czxinshui** [comment]
> > 通过内网ip 192.168.3.9能访问不
> 
> 目前就是靠这个ip访问，也只有这个方法

不要加HTTP访问。用外网访问一下，看看能不能连接成功（域名访问）如果域名能访问的话，就和我一样。只能外网访问，内网用域名没办法访问，好在刚才解决了

**Comment by jeessy2** [comment]
> > 通过内网ip 192.168.3.9能访问不
> 
> 目前就是靠这个ip访问、也只有这个方法

其他还有IPv6地址试下看。通过telnet检查端口是否正常

**Comment by luojunyuan** [comment]
> 不要加HTTP访问。用外网访问一下，看看能不能连接成功（域名访问）如果域名能访问的话，就和我一样。只能外网访问，内网用域名没办法访问，好在刚才解决了

> 其他还有IPv6地址试下看。通过telnet检查端口是否正常`telnet cloud.xxxxxx.cool 5000`

感谢，我也很迷惑。我什么也没做，拿着一些网络测试工具又测试了一番之后(5000 5001端口是打开的)，现在又能正常访问了。

我使用ubuntu服务器上telnet，它的结果没有变化一直是这个，ping 下面解析出来的ipv6没有问题
```shell
root@admin:/home# telnet nas.aaa.xyz 5000
Trying 2409:8a6a:ffff:7265:211:32ff:fe12:3456...
telnet: Unable to connect to remote host: Network is unreachable
```

**Comment by lifeisbut** [comment]
最好配置好域名，通过ipv6环境测试。
如果在ipv4环境下，可通过 https://ipv6proxy.cn 测试你的ipv6网站内容。
