### ISSUE TITLE
ddns解析多个域名

### ISSUE THREAD

**Issue by shaojs321** [jeessy2/ddns-go#410]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
- docker部署ddns，在domain栏解析多个域名，只能识别第一行。日志，dnspod上均显示已解析。tcping显示端口开放，但网页打不开，截图如下。
- 手动在dnspod上解析多个域名不存在这问题

## 是否已搜索同类问题
-已搜索未能解决

## 环境
- 操作系统: openwrt，群辉均试过
- ddns-go版本: v4.2.0
- 安装方式: docker

## 截图
<img width="892" alt="Snipaste_2022-10-17_10-13-04" src="https://user-images.githubusercontent.com/56724141/196074842-d9903b82-ee2b-4529-b7d5-418f976c15a8.png">
<img width="566" alt="Snipaste_2022-10-16_20-15-27" src="https://user-images.githubusercontent.com/56724141/196074846-00b8387a-c82c-46e4-8e5e-f17fa8ad7225.png">

**Comment by shaojs321** [comment]
目前只在dnspod上测试过，别的平台还未测试

**Comment by jeessy2** [comment]
#409
