### ISSUE TITLE
当需要同时更新多个域名的IP时，如何配置？

### ISSUE THREAD

**Issue by conghuang** [jeessy2/ddns-go#411]
比如我需要同时更新顶级域名和二级域名，目前更新单个域名没问题，有多个域名需要更新时如何配置？我看说明中说有支持，没找到方法。谢谢作者。

**Comment by jeessy2** [comment]
配置页面下面有说明。一行一个域名，有多少个域名就多少行

**Comment by conghuang** [comment]
理解了，多谢
