### ISSUE TITLE
有没有dynv6域名的添加教程，第三方域名添加时有token不知道如何添加

### ISSUE THREAD

**Issue by HarryChong** [jeessy2/ddns-go#412]
## 问题描述
有没有dynv6域名的添加教程，第三方域名添加时有token不知道如何添加

## 是否已搜索同类问题
- [x] 已搜索未能解决

## 环境
- 操作系统: nas
- ddns-go版本:4.2.0 
- 安装方式: 套件服务
-

**Comment by jeessy2** [comment]
参考#182
