### ISSUE TITLE
子域名的DDNS设置失败

### ISSUE THREAD

**Issue by XhL6996** [jeessy2/ddns-go#414]
## 问题描述
我有一个域名，暂且称之为xxx.yyy，此域名解析在Cloudflare，通过添加NS记录的方式将子域名的ddns.xxx.yyy交由阿里云解析，设置了阿里api，DDNS域名为zzz.ddns.xxx.yyy，但是API会返回“找不到此域名”，无法更改解析。
此API权限没有问题，因为若将根域名xxx.yyy交由阿里云解析，那么DDNS-GO是可以成功修改zzz.xxx.yyy的解析的。

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [ ] 未搜索

## 环境
- 操作系统: Ubuntu20.04
- ddns-go版本: 1.4.2
- 安装方式: 服务

## 截图
![2022-10-23_09-02](https://user-images.githubusercontent.com/63577165/197368180-265206bf-3baf-4021-b200-7f71a84a42be.png)

**Comment by jeessy2** [comment]
你可以提个工单咨询一下阿里云。看说明就是阿里云需要根域名才能操作

**Comment by XhL6996** [comment]
> 你可以提个工单咨询一下阿里云。看说明就是阿里云需要根域名才能操作

阿里客服回复说可以，但请求的参数应该是DomainName=ddns.xxx.yyy&RP=zzz，而不是DomainName=xxx.yyy&RP=zzz.ddns

**Comment by jeessy2** [comment]
那你用:分割主机记录。输入框下面有说明

**Comment by XhL6996** [comment]
好的，才知道这东西叫分割主机记录
