### ISSUE TITLE
获取地址同一个

### ISSUE THREAD

**Issue by xaiowei7** [jeessy2/ddns-go#415]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
发现获取地址都是网卡地址一模一样

## 是否已搜索同类问题
- [ ] 已搜索未能解决
- [x] 未搜索

## 环境
- 操作系统: 黑群晖
- ddns-go版本: 4.2.0
- 安装方式: docker/服务

## 截图
![image](https://user-images.githubusercontent.com/109535300/197473456-9af0ebb1-8c18-4011-b02a-bec14f680d8f.png)

**Comment by jeessy2** [comment]
能描述清楚一点否

**Comment by xaiowei7** [comment]
3个机器3个域名,在nas上获取都是同一个的ipv6地址

> 能描述清楚一点否

**Comment by jeessy2** [comment]
还是没看明白

**Comment by jeessy2** [comment]
It's taken too long to update. close
