### ISSUE TITLE
创建完保存后怎么都进不了

### ISSUE THREAD

**Issue by 990740150** [jeessy2/ddns-go#416]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景

## 是否已搜索同类问题
- [ ] 已搜索未能解决
- [x] 未搜索

## 环境
- 操作系统: ds918+
- ddns-go版本: 4.2.0 
- 安装方式: docker/服务

**Comment by jeessy2** [comment]
默认开启了禁止公网访问，自行检查
