### ISSUE TITLE
在Armbian安装后无法通过http://127.0.0.1:9876/访问

### ISSUE THREAD

**Issue by tyultra** [jeessy2/ddns-go#417]
## 问题描述
- 通过http://127.0.0.1:9876/无法访问DDNS-go

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [  ] 未搜索

## 环境
- 操作系统: Armbian 22.11.0-trunk Jammy with Linux 5.15.74-flippy-78+o，硬件为HK1 BOX电视盒子
- ddns-go版本: ddns-go_4.2.0_Linux_arm64
- 安装方式: 直接安装，没用使用docker

![image](https://user-images.githubusercontent.com/36122504/197571324-5a151013-5348-4e50-8d91-8794cb97f2ae.png)
![image](https://user-images.githubusercontent.com/36122504/197571394-b76676c9-4f81-4f78-8a81-f693a5718d20.png)

**Comment by jeessy2** [comment]
输入armbian的IP:9876
127.0.0.1是浏览器所在机器的ip

**Comment by jeessy2** [comment]
检查端口起来没有，防火墙开没之类的

**Comment by tyultra** [comment]
> 输入armbian的IP:9876 127.0.0.1是浏览器所在机器的ip

果然是端口没放行，可以了，谢谢！
