### ISSUE TITLE
使用arm无法解析域名

### ISSUE THREAD

**Issue by kk127686** [jeessy2/ddns-go#418]
## 问题描述
- 我使用安卓手机vivoz1安装了termux，在安装了ddns-go的arm版本，配置了ipv6,但是发现ddns-go域名无法解析

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [] 未搜索

## 环境
- 环境：安卓手机vivo z1
- ddns-go版本: 最新版
- 安装方式: 服务

**Comment by jeessy2** [comment]
看说明是你dns没配置好，使用本地的dns了

**Comment by zjy2931** [comment]
> 

你用的哪个包啊 我在termux执行 总是提示unkonw id
