### ISSUE TITLE
需要多ip解析

### ISSUE THREAD

**Issue by qian9008** [jeessy2/ddns-go#420]
多线路  需要多ip 域名的解析

**Comment by jeessy2** [comment]
能描述清楚一些？

**Comment by qian9008** [comment]
> 能描述清楚一些？

只需要 添加多个输入框就可以。路由器可以选择不同接口，其他可以策略分流解析出不同ip。

**Comment by jeessy2** [comment]
路由器上可以通过网卡获取IP。策略分流这个是路由功能吧，不支持

**Comment by qian9008** [comment]
> 路由器上可以通过网卡获取IP。策略分流这个是路由功能吧，不支持

对，只需要支持多个输入框就可以。

**Comment by jeessy2** [comment]
不支持多个输入框，绝大部分人用不到。你启动多个服务也可以实现

**Comment by dnslin** [comment]
> 不支持多个输入框，绝大部分人用不到。你启动多个服务也可以实现

如何安装多个服务 
```
2022/12/25 02:57:07 安装 ddns-go 服务失败, ERR: Init already exists: /etc/init.d/ddns-go
```
