### ISSUE TITLE
Release-v4.2.0没有Windows版本

### ISSUE THREAD

**Issue by fcwys** [jeessy2/ddns-go#422]
## 问题描述
Release-v4.2.0没有Windows版本，是因为不支持Windows平台吗？

**Comment by yin1999** [comment]
有的

![image](https://user-images.githubusercontent.com/15844309/199419253-5475860f-87b2-44c0-bde0-300e9bc3fb61.png)

**Comment by jeessy2** [comment]
![截屏2022-11-02 下午2 52 13](https://user-images.githubusercontent.com/6205259/199420401-af6d47e0-f1d6-4432-81f5-549b4a8f871a.png)
点红框

**Comment by fcwys** [comment]
好吧，尴尬
