### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by unixcs** [jeessy2/ddns-go#424]
## 问题描述
安装： 在armbian设备上 通过docker容器 安装ddns-go . 
解析：使用dnspod解析 IPV6

之前一直正常使用，但是今天突然发现报错！ 截图在最后：

## 是否已搜索同类问题
- [ ] 已搜索未能解决

## 环境

- 操作系统: armbian64
- ddns-go版本: v4.2.0
- 安装方式: docker
- 
## 截图
![image](https://user-images.githubusercontent.com/47837855/200250215-0d26e29f-8609-4430-becb-91ebcfc7e9bd.png)

**Comment by unixcs** [comment]
尝试重启docker后，又能成功获取了。
![image](https://user-images.githubusercontent.com/47837855/200250414-70bcae9e-2bdc-446c-95f0-ff7df9ed4668.png)

**Comment by jeessy2** [comment]
看报错信息是你dns`192.168.0.1`超时了
