### ISSUE TITLE
oom了

### ISSUE THREAD

**Issue by skill7899** [jeessy2/ddns-go#425]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景

## 是否已搜索同类问题
- [ ✓] 已搜索未能解决
- [x] 未搜索

## 环境
- 操作系统: 
x86 openwrt
- ddns-go版本: 
v4.20
- 安装方式: docker/服务
服务
## 截图
![Xnip2022-11-10_11-40-16](https://user-images.githubusercontent.com/13962272/200999333-8b9eae3c-ab6e-4ea7-b090-f16502242180.jpg)

**Comment by jeessy2** [comment]
golang程序在op系统在下是这种“问题”
显示的虚拟内存，实际只有10多MB`cat /proc/26540/status` 中的 `VmRSS`
```
VmPeak:	  720968 kB
VmSize:	  720968 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	   13396 kB
VmRSS:	   11016 kB
```

实际出现OOM了？
