### ISSUE TITLE
ipv6 提示求接口https://dnsapi.cn/Record.List失败! ERROR: Post "https://dnsapi.cn/Record.List": dial tcp 120.232.18.238:443: connect: no route to host

### ISSUE THREAD

**Issue by 5651video** [jeessy2/ddns-go#426]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
![11](https://user-images.githubusercontent.com/71858921/201852469-858b20da-29ca-403e-bdbc-b3708029147f.png)

## 是否已搜索同类问题
- [ ] 已搜索未能解决
- [x] 未搜索

## 环境
- 操作系统: 
- ddns-go版本: 
- 安装方式: docker/服务

**Comment by jeessy2** [comment]
检查自己网络，到dnspod接口没路由

**Comment by 5651video** [comment]
确实是网络设置有问题，已经解决了，谢谢大佬

**Comment by suiyuan21** [comment]
我也遇到相同问题，请指点
