### ISSUE TITLE
我的路由器是armv7l架构的，请问我应该如何在上面使用

### ISSUE THREAD

**Issue by Zmincrix** [jeessy2/ddns-go#427]
## 问题描述
- 没有找到对应我的架构的版本，我尝试了arm6和arm64版本想碰碰运气，但都分别报了不同的错，已附图。

## 是否已搜索同类问题
- [⭕️] 未搜索

## 环境
- 操作系统: # uname -a
Linux RT-AC66U_B1-4C68 2.6.36.4brcmarm #1 SMP PREEMPT Mon Mar 7 11:17:03 CST 2022 armv7l ASUSWRT-Merlin-KoolShare
- ddns-go版本: 4.2.0
- 安装方式: 服务

## 截图
armv6：
<img width="569" alt="截屏2022-11-16 10 03 50" src="https://user-images.githubusercontent.com/35093819/202065852-1a511474-b874-4783-ac96-1cc190313f23.png">

arm64:
<img width="568" alt="截屏2022-11-16 10 07 32" src="https://user-images.githubusercontent.com/35093819/202066199-367e5c2c-2eec-4fb1-8c55-69f6d4b7bbdf.png">

**Comment by jeessy2** [comment]
有可能不支持arm7i. 
golang交叉编译arm只有`CGO_ENABLED=0 GOOS=linux GOARCH=arm  go build` `CGO_ENABLED=0 GOOS=linux GOARCH=arm64  go build` 如果不能运行那也没啥法了

**Comment by lxjxxxxxxxx** [comment]
我也是v7的，现成的包都运行不了，要下载源码项目重新编译，我用的是goland，编译环境设置为`GOARCH=arm;GOARM=5;GOOS=linux`
最关键的就是`GOARM=5`这一项

**Comment by jeessy2** [comment]
> 我也是v7的，现成的包都运行不了，要下载源码项目重新编译，我用的是goland，编译环境设置为`GOARCH=arm;GOARM=5;GOOS=linux` 最关键的就是`GOARM=5`这一项

方便来个PR，用的goreleaser, 参考 https://goreleaser.com/customization/build/
我没arm7的cpu，不好测

**Comment by lxjxxxxxxxx** [comment]
我是用windows的goland交叉编译的，没有接触过pr构建，我只手动设置了三个变量，其余的变量应该都是默认的
`GOARCH=arm`
`GOARM=5`
`GOOS=linux`
以下是我的路由器信息
`
主机名 | OpenWrt
-- | --
型号 | Netgear R6250 V1 (BCM4708)
架构 | ARMv7 Processor rev 0 (v7l)
目标平台 | bcm53xx/generic
固件版本 | OpenWrt 22.03.2 r19803-9a599fee93 / LuCI openwrt-22.03 branch git-22.288.45147-96ec0cd
内核版本 | 5.10.146
`

**Comment by jeessy2** [comment]
fixed. Try with https://github.com/jeessy2/ddns-go/releases/tag/v4.2.1

**Comment by lxjxxxxxxxx** [comment]
> 固定的。尝试使用[https://github.com/jeesy2/ddns-go/releases/tag/v4.2.1](https://github.com/jeessy2/ddns-go/releases/tag/v4.2.1)

经测试，4.2.1 armv5在我的路由器可以运行，没有问题
