### ISSUE TITLE
请问一下ddns内存占用问题

### ISSUE THREAD

**Issue by lxjxxxxxxxx** [jeessy2/ddns-go#428]
我用源码重新编译后在arm的路由器上运行，查看内存占用：
`2658     1 root     S     782m 318%   0% /overlay/ddns-go -l :9876 -f 300 -c /root/.ddns_go_config.yaml`
内存占用高达782m，但是路由器运行正常，而且路由器只有256的内存，请问准确吗

**Comment by jeessy2** [comment]
实际占用只有10MB,显示的是虚拟内存，参考#425
