### ISSUE TITLE
你好，新版本的windows不能使用了吗

### ISSUE THREAD

**Issue by eziojw** [jeessy2/ddns-go#432]
我下载了[ddns-go_4.2.1_Darwin_x86_64.tar.gz](https://github.com/jeessy2/ddns-go/releases/download/v4.2.1/ddns-go_4.2.1_Darwin_x86_64.tar.gz) ，但是ddns-go 这个文件无法打开，他不是exe的
您教程的安装方式我也是没看懂

**Comment by eziojw** [comment]
是我太蠢了，我发现windows版本在下面

**Comment by jeessy2** [comment]
👍Darwin是苹果系统
