### ISSUE TITLE
谷歌ddns更新失败

### ISSUE THREAD

**Issue by auto8624** [jeessy2/ddns-go#433]
谷歌ddns更新失败，ddns-go反馈更新成功，去谷歌域名后台查看实际未更新
主机是windows

**Comment by jeessy2** [comment]
日志详情发下，并请 @yin1999 看下

**Comment by yin1999** [comment]
刚测试是正常的：

![image](https://user-images.githubusercontent.com/15844309/204487933-bc5b2c10-ace1-44fe-b190-1dd542d2c62f.png)

**Comment by auto8624** [comment]
账号密码是填谷歌账号的账号密码吗？

**Comment by auto8624** [comment]
搞错了，原来最下面有个动态 DNS，得在这里填

**Comment by yin1999** [comment]
> 请问怎么添加aaaa记录用ipv6？

直接支持 AAAA 记录添加的，但请使用不同的域名，Google Domain提供的支持并不友好，不同的记录需要使用不同的凭据（需要开两个 ddns-go）

https://support.google.com/domains/answer/6147083

**Comment by auto8624** [comment]
ipv4又失败了
2022/12/01 01:09:29 client.Do失败. Error: Post "https://domains.google.com/nic/update?hostname=a.xxx.xyz&myip=180.114.133.17": dial tcp 172.217.160.110:443: connectex: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2022/12/01 01:09:29 新增域名解析 a.xxx.xyz 失败！
