### ISSUE TITLE
获取到的外网ip有时候是错误的

### ISSUE THREAD

**Issue by chitanda233** [jeessy2/ddns-go#434]
## 问题描述
ddns-go 有时候会获取一个错误的ip地址，并把它更新到dnspod上

详细情况：
家里路由器是AX88U，装了一个自动gfwlist的梯子软件
近期突然发现，ddns-go提交到dnspod上的ip，间歇性的会是一个错误的ip（比如有时候是61.151.164.141，61.151.164.153 这几个ip），过些时间又会更新成正确的，自己测试了很多次网络环境，也没办定位到原因。
访问设置的获取ip的网页，返回的ip地址是正确的自己外网的ip。

看ddns-go的日志，也只是说，你的ip没有变化，等待几次之后更新。
也就是说，这时候，我的拨号外网ip一直没有变化，但是dnspod上的解析地址是错误的，这时候ddns-go并不知道，也不会去更新

所以想一个办法是，是否可以开一个选项，在设定时间检查的时候，先获取一下域名解析的ip，如果和现在的外网ip不一样，那么也更新一次。
如果该选项关闭之后，还是走现在的逻辑

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [] 未搜索

## 环境
- 操作系统: 群晖7.0
- ddns-go版本: 4.2.1
- 安装方式: docker

## 截图
比如这次，全军覆没。。各一半用Linux上服务运行的ddns-go和docker上的，解析了两批
![image](https://user-images.githubusercontent.com/29685669/204323852-9ca88fa2-8a88-4e41-942f-f0ebec5acc5b.png)

发现解析错误之后，访问获取ip地址的网页，是正确的。 https://myip4.ipip.net,https://ddns.oray.com/checkip,https://ip.3322.net 这3个都是对的
![image](https://user-images.githubusercontent.com/29685669/204324401-ca4e0b5b-b559-4cbe-98b3-d0d24b88256b.png)

**Comment by chitanda233** [comment]
还尝试过在路由上关掉梯子，设置对ddns-go的Linux系统ip单独过滤，发现都会有错误的ip解析
这些都是错误的ip地址，不是我的公网ip
![image](https://user-images.githubusercontent.com/29685669/204329214-0eb28b75-0e2b-4f47-a1b6-1c298712db17.png)

**Comment by jeessy2** [comment]
原理也简单：获取IP有变化才去比对dnspod，有变化才更新.
你卡在第一步的获取IP出问题了，是因为自己"网络"问题，这个最好自行解决

**Comment by chitanda233** [comment]
> 步的获取IP出问题了，

但是我通过访问网页查询获取的ip都是正确的，只有ddns提交上去的是失败的。
查ddns的的ip获取日志，也都是正确的，61开头的ip就没有出现过

**Comment by jeessy2** [comment]
第三次算IP变化，有没有日志，发来看下
