### ISSUE TITLE
是否考虑增加域名providers机制

### ISSUE THREAD

**Issue by dezhishen** [jeessy2/ddns-go#436]
# 期望从**外部**主动/被动 获取需要注册的域名列表
## 例如使用traefik做为负载均衡,traefik提供接口`/api/http/routers` 
> 详情参考 https://doc.traefik.io/traefik/operations/api/#endpoints
1. 通过实现类,调用接口和配置,返回统一的`[]config.Domain`
2. 主线程中,调用实现类,获取到domain列表后,统一进入处理流程

**Comment by jeessy2** [comment]
支持多个域名，手工填写也是可以的，还有通配符支持。
你说的要请求traefik的接口获取域名，还要解析json，这个方式不通用，搞复杂了。

**Comment by dezhishen** [comment]
> 支持多个域名，手工填写也是可以的，还有通配符支持。 你说的要请求traefik的接口获取域名，还要解析json，这个方式不通用，搞复杂了。

那做成类似`database/sql`的模式呢?
1. 定义好接口
2. 由各自`providers`自身实现,并且通过`init()`方法注入到`providers`的管理工厂中
3. 对于主流程就是遍历所有的`providers`实现,获取domains,将domains进行ddns操作
4. 当前通过config获取的方式也可以作为一种默认实现

**Comment by jeessy2** [comment]
后面考虑，目前没必要。
