### ISSUE TITLE
功能建议：增加多个服务商 同时解析不同域名

### ISSUE THREAD

**Issue by qian9008** [jeessy2/ddns-go#439]
功能建议：增加多个服务商 同时解析不同域名

**Comment by jeessy2** [comment]
可以修改域名服务器到同一个运营商。
目前暂无计划支持

**Comment by qian9008** [comment]
> 可以修改域名服务器到同一个运营商。 目前暂无计划支持

那只能多开docker里，希望页面内可以改监听端口号。

**Comment by jeessy2** [comment]
1. 转到一个服务商就不用多开docker
2. 也支持多开docker
3. 可以使用cname

**Comment by PencilNavigator** [comment]
这issue我8月份就提过，作者明确说过不支持了。https://github.com/jeessy2/ddns-go/issues/354
可以试下其他项目

**Comment by jeessy2** [comment]
> 这issue我8月份就提过，作者明确说过不支持了。#354 可以试下其他项目

这个实现有点麻烦，要考虑老用户升级，还要简单实用。那位感兴趣可以PR，我暂无兴趣

**Comment by jeessy2** [comment]
5.0.0已支持 https://github.com/jeessy2/ddns-go/releases/tag/v5.0.0
