### ISSUE TITLE
在centos中使用提示open /root/.ddns_go_config.yaml: permission denied

### ISSUE THREAD

**Issue by vistenlee** [jeessy2/ddns-go#45]
启动是以
docker run -d \
  --name ddns-go \
  --restart=always \
  -v /opt/ddns-go:/root/ \
  -p 9876:9876 \
  jeessy/ddns-go

进行启动，打开ip:9876能进入页面，进行保存配置的时候，提示open /root/.ddns_go_config.yaml: permission denied

请问大大怎样解决？

另外还有一个问题，如果以--net=host启动，就无法通过ip:端口进入配置页面了，因为要使用ipv6，请问大大这个怎样解决呀？

**Comment by jeessy2** [comment]
可能是你没有权限访问/opt目录，改一个目录能访问的。
可以通过ip+端口访问的，使用内网ip
