### ISSUE TITLE
获取ip方式, 是否可以增加脚本方式？

### ISSUE THREAD

**Issue by wjz304** [jeessy2/ddns-go#451]
获取ip方式, 是否可以增加脚本方式？

**Comment by jeessy2** [comment]
这个有啥应用场景，能简单介绍一下不

**Comment by wjz304** [comment]
因为一些机器无法安装应用或者其他原因，只能在其他机器上去做解析。
比如：
可以在路由上去给内网的智能摄像头 ddns v6 。
异地组网后，在上海的机器上也能去ddns 广东的机器。

另外，方便管理，当我有十几二十台设备需要ddns时，我可以在一台设备上统一管理。

**Comment by jeessy2** [comment]
通过什么脚本可以获取到其他机器的v6地址，发点脚本来看下

**Comment by wjz304** [comment]
ip -6 neighbor show
可以获取到v6 网邻，之后根据需求 grep 就行了

**Comment by wjz304** [comment]
另外 也能自行解决一部分 接口和网卡 获取不准确的情况

**Comment by jeessy2** [comment]
这个也是一种思路，欢迎PR
`ip -6 neighbor show`这个获取的内网的v6地址？

**Comment by wjz304** [comment]
嗯，内网，相当于arp 吧。有时也不准，
但是脚本开放性就很高了，不局限这一个方法...

**Comment by jeessy2** [comment]
可以可以。欢迎PR

**Comment by wjz304** [comment]
![}UU{J`L17XWNLFAX XQF} P](https://user-images.githubusercontent.com/5615843/206645229-2ce14ad8-abae-482d-81ac-fb80a58d8ca2.gif)
对 go 和 js 都不是很熟悉。看了一下源码，我得先了解下

**Comment by Camusama** [comment]
+1

**Comment by jeessy2** [comment]
@wjz304 @Camusama 已发布，试下4.5.0版本
