### ISSUE TITLE
请求接口 https://api.cloudflare.com/*** 失败! 返回状态码: 400

### ISSUE THREAD

**Issue by adivot** [jeessy2/ddns-go#455]
求助一个问题，ddns-go在Windows下运行，用cloudflare.com登录，IPv4和v6没有同步到cloudflare.com的DNS上，有报错日志，见下。域名是cloudflare.com上购买的，用的Global API Key。

改用阿里云正常，没有报错日志，A、AAAA记录也在更新。

DDNS ipv6探索小白，不知道问题在哪，特来请教，感谢。

## 问题描述
2022/12/14 08:35:28 第一次运行将等待 20 秒后运行 (等待网络)
2022/12/14 08:35:28 监听 :9876 ...
2022/12/14 08:35:49 请求接口 https://api.cloudflare.com/client/v4/zones?name=xxx.com&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400
2022/12/14 08:35:49 请求接口 https://api.cloudflare.com/client/v4/zones?name=xxx.com&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400
2022/12/14 08:38:29 127.0.0.1:49321 请求登陆!
2022/12/14 08:38:42 127.0.0.1:49321 请求登陆!
2022/12/14 08:39:10 配置文件已保存在: C:\Users\Administrator\.ddns_go_config.yaml
2022/12/14 08:39:11 请求接口 https://api.cloudflare.com/client/v4/zones?name=xxx.com&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400
2022/12/14 08:39:12 请求接口 https://api.cloudflare.com/client/v4/zones?name=xxx.com&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400
2022/12/14 08:40:53 IPv4未改变，将等待 5 次后与DNS服务商进行比对
2022/12/14 08:40:53 IPv6未改变，将等待 5 次后与DNS服务商进行比对
2022/12/14 08:42:34 配置文件已保存在: C:\Users\Administrator\.ddns_go_config.yaml
## 是否已搜索同类问题
- [x] 已搜索未能解决
- [ ] 未搜索

## 环境
- 操作系统: 2008R2
- ddns-go版本: 4.3.3
- 安装方式: win服务

**Comment by jeessy2** [comment]
token不对。参考文档说明的操作，以前别人也问了，搜索一下就可以了

**Comment by adivot** [comment]
已解决谢谢。
