### ISSUE TITLE
使用ddns-go的一点小bug

### ISSUE THREAD

**Issue by zzfree2021** [jeessy2/ddns-go#457]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
移动宽带只有ipv6地址，使用ddns-go和cloudflare，在ddns-go添加了ipv6域名和cloudflare的api，cloudflare能新建和更新域名，但是出现一个问题，就是每次更新域名，会把域名的加速那个取消，就是小云朵会掉，因为还必须用cloudflare的加速，这样ipv4的电脑才能访问到域名，这个是什么问题呢？
## 是否已搜索同类问题
- [ ] 已搜索未能解决
- [x] 未搜索

## 环境
- 操作系统: centos7.9
- ddns-go版本: 最新版
- 安装方式: docker

**Comment by jeessy2** [comment]
example.com?proxied=true
