### ISSUE TITLE
 Cloudflare服务，现在每次更新ipv6后都会把代理模式关闭，之前的版本不存在这个问题

### ISSUE THREAD

**Issue by ckcoding** [jeessy2/ddns-go#464]
## 问题描述
- Cloudflare服务，现在每次更新ipv6后都会把代理模式关闭，之前的版本不存在这个问题

## 是否已搜索同类问题
- [ ] 已搜索未能解决
- [x] 未搜索

## 环境
- 操作系统: 
- ddns-go版本: 4.33
- 安装方式: docker

**Comment by jeessy2** [comment]
对。有这个问题

**Comment by jeessy2** [comment]
对。有这个问题

**Comment by jeessy2** [comment]
试下v4.3.4版本
v4.2.2后也可以通过自定义参数控制`example.com?proxied=true`
