### ISSUE TITLE
域名后台手动更新IP地址后，可以刷新成功，但如果重启路由或未在后台配置IP地址时，更新显示失败

### ISSUE THREAD

**Issue by AWSOMEALEX** [jeessy2/ddns-go#468]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景

## 是否已搜索同类问题
- [ ] 已搜索未能解决
- [x] 未搜索

## 环境
- 操作系统: 
- ddns-go版本: 最新版
- 安装方式: docker/服务

## 截图
![Screenshot of DDNS-GO](https://user-images.githubusercontent.com/108708206/208295041-6a8f3c1d-0065-44e7-88e5-9de248dc7e2f.jpg)

**Comment by jeessy2** [comment]
看不明白，信息量太少

**Comment by zzz1041912976** [comment]
同样的问题，动态ip变化，ddns-go无法更新并识别，每次需要手动更改dns

**Comment by jeessy2** [comment]
使用的cloudflare?更新tk域名？

**Comment by zzz1041912976** [comment]
更新到最新版本问题解决

**Comment by AWSOMEALEX** [comment]
> 使用的cloudflare?更新tk域名？
是的，可能是免费域名的原因吗？

**Comment by jeessy2** [comment]
> > 使用的cloudflare?更新tk域名？
> 
> 是的，可能是免费域名的原因吗？

对。有几个免费的在cf被限制了

**Comment by AWSOMEALEX** [comment]
> > > 使用的cloudflare?更新tk域名？
> > 
> > 
> > 是的，可能是免费域名的原因吗？
> 
> 对。有几个免费的在cf被限制了

明白了，谢谢大佬 。
