### ISSUE TITLE
host模式下ipv6解析失败的问题

### ISSUE THREAD

**Issue by pureGavin** [jeessy2/ddns-go#470]
## 问题描述
我用vultr的VPS实验ddns，ipv4可以完美解析，ipv6无法解析
请问该如何排查此类问题？

## 是否已搜索同类问题
- [√] 已搜索未能解决

## 环境
- 操作系统: Ubuntu22.04
- ddns-go版本: 最新的docker版
- 安装方式: docker host模式

**Comment by jeessy2** [comment]
要看什么错？
vps不用ddns,固定IPv4/IPv6

**Comment by pureGavin** [comment]
> 要看什么错？ vps不用ddns,固定IPv4/IPv6

我用vps只是实验我的域名是否能正常解析
奇怪的是网页右边的日志显示ipv6能正常获取，域名也没问题，但是就是无法解析，我换到ipv4就可以正常解析，ufw我也开端口了

**Comment by loryncien** [comment]
> > 要看什么错？ vps不用ddns,固定IPv4/IPv6
> 
> 我用vps只是实验我的域名是否能正常解析 奇怪的是网页右边的日志显示ipv6能正常获取，域名也没问题，但是就是无法解析，我换到ipv4就可以正常解析，ufw我也开端口了

ufw的问题？你关了试试看，好像ufw与docker有些小问题

**Comment by pureGavin** [comment]
> > > 要看什么错？ vps不用ddns,固定IPv4/IPv6
> > 
> > 
> > 我用vps只是实验我的域名是否能正常解析 奇怪的是网页右边的日志显示ipv6能正常获取，域名也没问题，但是就是无法解析，我换到ipv4就可以正常解析，ufw我也开端口了
> 
> ufw的问题？你关了试试看，好像ufw与docker有些小问题

OK，我找机会试试看吧
