### ISSUE TITLE
腾讯云 创建密钥 按钮对应的链接不对

### ISSUE THREAD

**Issue by Huangsam04-github** [jeessy2/ddns-go#472]
应该对应 https://console.dnspod.cn/account/token/token
但是却对应 https://console.dnspod.cn/account/token/ ，打开这个网页默认是腾讯云API密钥，我没注意到。最后花了很长时间才发现不是DNSPOD Token。
`（不是很确定是不是应该在这个地方反馈，第一次用github）`

**Comment by jeessy2** [comment]
反馈正确，等待修改

**Comment by jeessy2** [comment]
4.4.0已修复
