### ISSUE TITLE
BUG：IP改变却提示未变化，另新功能建议，增加强制更新按钮。

### ISSUE THREAD

**Issue by lhbdhr** [jeessy2/ddns-go#477]
## 问题描述

我确定我今天的IPV6地址和昨天的不一样，但是依旧显示
`IPv6未改变，将等待 5 次后与DNS服务商进行比对`

不知道您是把ip地址存在什么位置，但是推荐生成个文件保存吧。这样IP变了一对比肯定能知道。

另外能不能新加入一个功能：
增加个`强制更新按钮`，我确定IP变了，却让我傻等 5x5=25分钟。
上cloudflare手动更新DNS，肯定没有你这个点一个按钮，强制更新来的更方便啊。

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [] 未搜索

## 环境
- 操作系统: Windows
- ddns-go版本: 4.4.0
- 安装方式: 服务

**Comment by jeessy2** [comment]
save按钮就是强制更新。
如果还没更新，说明IPv6没改变

**Comment by cosir888** [comment]
同样的问题，确定变了，但是他提示未变

**Comment by jeessy2** [comment]
把获取ip方式，应该获取的IP地址截图反馈。不然分析不了

**Comment by lhbdhr** [comment]
> 把获取ip方式，应该获取的IP地址截图反馈。不然分析不了

个人觉得没必要搞检测ip是否变化等操作，把事情搞复杂了。

最简单的办法就是每5分钟对比dns解析设置和本地ip，不一样就同步，直接查询一下dns解析也没多大开销啊。

不理解为什么现在设置的是
每5分钟检测ip是否变化，但是不对比dns解析。

尤其检查ip是否变化还不太准，
我提issue时，我确定ipv6地址和昨天不一样，但日志里就是说ip没变化。

我看配置文件里没有保存ip地址，你只是运行时的变量。
今天我电脑关机了，第二天开机，ip地址变化了，但是软件刚打开一直是今天的ip，持续说ip没变化，明明和cloudflare里的不一样。

**Comment by jeessy2** [comment]
没遇到你们说的。最好把配置发来看下，日志相关的，不然无法分析

**Comment by nonepage** [comment]
情况：
cloudflare无法更新ip到主机记录, 在api令牌页面中可以看到令牌被使用了，但是没有进行ip变更的操作
配置：
dns:
    name: cloudflare
    id: ""
    secret: xxxx
ipv4:
    enable: true
    gettype: url
    url: https://myip4.ipip.net, https://ddns.oray.com/checkip, https://ip.3322.net, https://4.ipw.cn
    netinterface: ""
    domains:
        - r1:xxx.cn
        - r2:xxx.cn
        - r3:xxx.cn
        - r4:xxx.cn
日志：
2023/01/29 20:15:53 配置文件已保存在: /root/.ddns_go_config.yaml
2023/01/29 20:17:14 IPv4未改变，将等待 5 次后与DNS服务商进行比对

**Comment by nonepage** [comment]
大佬求求，看看情况

**Comment by cosir888** [comment]
> 大佬求求，看看情况

删除旧的令牌，重新设置生成一个。我今天还正常更新到cloudflare

**Comment by nonepage** [comment]
> > 大佬求求，看看情况
> 
> 删除旧的令牌，重新设置生成一个。我今天还正常更新到cloudflare

您用的版本是最新的吗

**Comment by lhbdhr** [comment]
> 

cloudflare不支持免费域名使用API，比如TK、ML后缀的域名。你域名是正常的com、net域名吗？

**Comment by cosir888** [comment]
> > > 大佬求求，看看情况
> > 
> > 
> > 删除旧的令牌，重新设置生成一个。我今天还正常更新到cloudflare
> 
> 您用的版本是最新的吗

对，最新的。另外如@lhbdhr所说不支持freenom的域名
