### ISSUE TITLE
namesilo支持的问题

### ISSUE THREAD

**Issue by Qwejay** [jeessy2/ddns-go#478]
请问可以支持一下 namesilo 吗？

**Comment by jeessy2** [comment]
暂不支持，欢迎PR

**Comment by Balder1840** [comment]
> 

namesilo 可通过把nameserver配置成cloudflare的来解决
最坑的是freenom

**Comment by Balder1840** [comment]
> 请问可以支持一下 namesilo 吗？

namesilo 可通过把nameserver配置成cloudflare的来解决
最坑的是freenom
