### ISSUE TITLE
希望可以获取当前版本号

### ISSUE THREAD

**Issue by MoontoC** [jeessy2/ddns-go#479]
在使用容器的时候, 很多软件提供了版本号可以查看, 不是那种页面上 , 而是类似配置目录中留下一个version文件, 或是镜像的标签里可以查到, 为了比对更新版本用

比如hass的镜像标签里有一个.Config.Labels "io.hass.version"
vaultwarden的镜像里 .Config.Labels "org.opencontainers.image.version"
nginx proxy manager的镜像里.Config.Env "NPM_BUILD_VERSION"这样

**Comment by jeessy2** [comment]
配置文件和镜像里没必要，要通用，命令行可以加一个，欢迎PR

**Comment by MoontoC** [comment]
sorry 我提了一个别人都有但是没有必要的东西

**Comment by WaterLemons2k** [comment]
@MoontoC 从 #528 开始，可以为镜像自动生成标签，其中 `org.opencontainers.image.version` 是 `ddns-go` 的当前版本号。

自 [v4.5.2](https://github.com/jeessy2/ddns-go/releases/tag/v4.5.2) 起可用。
