### ISSUE TITLE
你好，大佬，请问是否可以实现N个固定IPv4循环解析

### ISSUE THREAD

**Issue by linkala** [jeessy2/ddns-go#48]
最近被bc大佬GFW勒索攻击，想出了这个办法，5分钟进行切换一次IP，看了许多项目，感觉大佬这个项目好牛逼，特地来询问一下，如果可以实现，我会赞助大佬，十分希望得到您的回复谢谢。

**Comment by jeessy2** [comment]
原理上可以实现的，但能不能就解决问题就不清楚了
