### ISSUE TITLE
获取不到ipv4

### ISSUE THREAD

**Issue by ZENG61** [jeessy2/ddns-go#480]
用甲骨文的服务器更换ip后获取不到ipv4
2023/01/06 13:45:26 连接失败! [点击查看接口能否返回IPv4地址](https://myip4.ipip.net/)
2023/01/06 13:45:26 错误信息: Get "https://myip4.ipip.net": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by jeessy2** [comment]
请求 接口超时了吧，自己换个接口试试

**Comment by yin1999** [comment]
可以试试 Cloudflare 在国内的接口，用了 2 个月还是挺稳定的：https://cf-ns.com/cdn-cgi/trace
