### ISSUE TITLE
Godaddy 上更新不正常

### ISSUE THREAD

**Issue by lqsbg26** [jeessy2/ddns-go#482]
## 问题描述

在Godaddy上有一个net域名，近日想通过ddns-go，把IPv6地址注册到Godaddy上。DDNS-go是 v4.4.1 的。一开始是在华硕的AC-66U-B1路由器上运行，用arm64-linux版（好像armv5，armv7也可以）。DDNS-GO配置好godaddy后，可以成功更新AAAA记录，但每30分钟会通过webhook发送一次报警，而不是仅在IPv6地址改变时才发报警，这点与使用其他DNS注册商时的情况不一样。实际上报警内容完全一样，IPv6地址并未改变。

一开始怀疑是 v4.4.1 的问题，换了 v4.4.0 ，问题同样存在；然后怀疑是 arm-linux 版本的问题，于是在一台 Windows 10的计算机上用DDNS-GO v4.4.0 注册到Godaddy，同样是仅IPv6，但问题仍然存在。

再然后排查时，偶然看到我在godaddy上创建的hostname的AAAA记录的IPv6地址保持为初始时的 2::2 ，而出现了另一个同样hostname的AAAA记录，IPv6地址是真实的，这似乎是DDNS-go没有使用我手工创建的AAAA记录，而是在更新AAAA记录时自行创建了另一个同名的。所以我干脆在Godaddy管理界面把华硕路由器和Windows 10的AAAA记录全部删除了，arm-linux和WIndows的DDNS-GO可以自动创建AAAA记录。但这并不有助于解决半个小时webhook报警一次的问题。

最后怀疑是Godaddy的API key类型有问题，本来时production类型，创建了一个OTE类型，发现OTE类型根本不能被DDNS-GO使用，更新时验证不通过。

所有办法都试过后，把注册商改为阿里云，华硕路由器和Windows 10上的这个问题都消失了。

有问题时段得到DDNS-go的日志，内容有些与众不同，举例华硕路由器的日志如下：
----------------------
2023/01/11 20:37:12 IPv6未改变，将等待 3 次后与DNS服务商进行比对
2023/01/11 20:42:13 IPv6未改变，将等待 2 次后与DNS服务商进行比对
2023/01/11 20:47:14 IPv6未改变，将等待 1 次后与DNS服务商进行比对
2023/01/11 20:52:16 向godaddy发送请求，请求地址为https://api.godaddy.com/v1/domains/h***y.net/records/AAAA/r***s
2023/01/11 20:52:17 Webhook调用成功, 返回数据:
2023/01/11 20:57:17 IPv6未改变，将等待 5 次后与DNS服务商进行比对
2023/01/11 21:02:18 IPv6未改变，将等待 4 次后与DNS服务商进行比对
-------------------------
也就是说，在5次DNS对比后，不管IP地址是否改变，都会调用webhook发送报警信息。

## 是否已搜索同类问题
- [x] 已搜索未能解决

## 环境
- 操作系统:  Linux 2.6.36, Windows 10
- ddns-go版本:  4.4.0, 4.4.1
- 安装方式: Linux 脚本， Windows 服务

**Comment by jeessy2** [comment]
有这个问题.

**Comment by jeessy2** [comment]
https://github.com/jeessy2/ddns-go/releases/tag/v4.4.2
