### ISSUE TITLE
不能开始同步

### ISSUE THREAD

**Issue by shakamilo1** [jeessy2/ddns-go#489]
## 问题描述
- 只开IPV4，https://myip4.ipip.net 可以获得正确IP地址，用的阿里云，正确填写了AccessKey，其它是默认设置。在NAS上使用，双网卡，路由开了科学上网，但NAS被设置成不经过代理模式。经长时间等待，程序一直不开始同步。曾经正常工作过。
- 请问各位，我应该怎么开始排查？

## 是否已搜索同类问题
- [x] 已搜索未能解决

## 环境
- 操作系统: 
- ddns-go版本: 4.42
- 安装方式: docker

## 日志
2023/01/13 22:45:54 第一次运行将等待 10 秒后运行 (等待网络)
2023/01/13 22:45:54 监听 :9876 ...
2023/01/13 22:47:02 配置文件已保存在: /root/.ddns_go_config.yaml
2023/01/13 23:00:33 配置文件已保存在: /root/.ddns_go_config.yaml
2023/01/13 23:03:19 配置文件已保存在: /root/.ddns_go_config.yaml
2023/01/13 23:27:00 配置文件已保存在: /root/.ddns_go_config.yaml

**Comment by ItzMiracleOwO** [comment]
可以尝试下在nas上 `curl https://myip4.ipip.net`
