### ISSUE TITLE
请求接口https://alidns.aliyuncs.com/失败! 

### ISSUE THREAD

**Issue by stone2289** [jeessy2/ddns-go#49]
系统是debian10，宽带是移动大内网，有ipv6，可以ping通alidns.aliyuncs.com，用docker版或者直接安装都会出现以下报错，我是小白，麻烦大佬给看看。

请求接口https://alidns.aliyuncs.com/失败! {"RequestId":"CDE6E6E6-F80C-47D3-BB95-C08BA23D4AC3","Message":"Specified time stamp or date value is expired.","Recommend":"https://error-center.aliyun.com/status/search?Keyword=InvalidTimeStamp.Expired&source=PopGw","HostId":"alidns.aliyuncs.com","Code":"InvalidTimeStamp.Expired"}

**Comment by jeessy2** [comment]
检查服务器时间
`
用户时间和服务器时间不在 15 分钟内请检查您的时间戳设置，确认时间戳和服务器时间的差值是否在 15 分钟内。
`

**Comment by stone2289** [comment]
时间戳是系统时间的意思吗？我检查了一下没问题。Asia/Shanghai(CST, +0800)

**Comment by jeessy2** [comment]
看debian系统现在时间和北京标准时间是不是相同的

**Comment by stone2289** [comment]
已解决，系统时区设置正确，但是时间慢了半个小时，感谢作者回复！

**Comment by jeessy2** [comment]
ok。和时区关系不大，用的UTC时间。阿里云要求不能相差15分钟。
