### ISSUE TITLE
使用自定义开启多个服务商同时解析不同域，阿里云国内版DDNS失败，国际版正常，腾讯云正常

### ISSUE THREAD

**Issue by yaleyip** [jeessy2/ddns-go#490]
## 问题描述
- 使用自定义开启多个服务商同时解析不同域，阿里云国内版DDNS失败，国际版正常，腾讯云正常。

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [ ] 未搜索

## 环境
- 操作系统: Ubuntu22.04.01服务器版
- ddns-go版本: 4.4.0/ 4.4.1

## 截图
![阿里云国内版](https://user-images.githubusercontent.com/60421789/212457700-e927e172-4b2f-4cb0-ad59-0616a3891313.jpg)

![阿里云国际版](https://user-images.githubusercontent.com/60421789/212457789-268948f3-391c-460d-b429-c274a9daa141.jpg)

![腾讯云](https://user-images.githubusercontent.com/60421789/212457775-6fdc2378-ea23-4dd8-beb6-8dff8c89a5bd.jpg)

**Comment by jeessy2** [comment]
看说明你的key无权操作

**Comment by yaleyip** [comment]
> 看说明你的key无权操作

说明是说key无权操作，但在ROS可以操作。我比对国内版与国际版，权限是一致的，重新建立key也不行。

**Comment by jeessy2** [comment]
你在检查一下，实在不行你提个工单问下阿里云

**Comment by yaleyip** [comment]
> 你在检查一下，实在不行你提个工单问下阿里云

找到原因了。应用只能使用云账号key，其他第三方应用可以使用RAM用户key。
安全起见，是否考虑兼容RAM用户key。

**Comment by jeessy2** [comment]
授权ram也可以吧。阿里云提供接口都是一样的，不可能单独为ram提供独立的接口
