### ISSUE TITLE
v4.4.2又不能在华硕路由器上运行了

### ISSUE THREAD

**Issue by lqsbg26** [jeessy2/ddns-go#491]
## 问题描述
- 我华硕 RT-AC86u 路由器上，CPU应该是arm-64的，先前几个版本存在godaddy注册异常的问题。

今天升级到了v4.4.2，四个arm版本的执行文件都不能运行，arm v5，v6，arm-64的提示是“Segmentation fault”，arm v7的提示是“runtime: this CPU has no floating point hardware, so it cannot run”。

## 是否已搜索同类问题
- [x] 已搜索未能解决

## 环境
- 操作系统: Linux 4.1.27
- ddns-go版本: 4.4.2
- 安装方式: 脚本执行

**Comment by jeessy2** [comment]
生成的文件都是通过github action自动编译的。可以试下最近那个版本能运行，也可以尝试自行编译

**Comment by lqsbg26** [comment]
不好意思，是我搞错了，我下载了FreeBSD的版本，在Linux上运行。。。。。。

改用了Linux版本的，好了。
