### ISSUE TITLE
可否提供一份yaml

### ISSUE THREAD

**Issue by cosir888** [jeessy2/ddns-go#492]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景

## 是否已搜索同类问题
- [x ] 已搜索未能解决
- [   ] 未搜索

## 环境
- 操作系统: 
- ddns-go版本: 
- 安装方式: docker/服务

## 截图

你好，开发者，我是个新手，正在学习使用github actions编译各个平台不同架构来测试我的一个demo，不得其法，发现这个项目架构很全，但是好像没有编译的yaml文件。希望能发一份编译yml文件，如果不方便在这里发布，请发我邮箱，yahumu228@hotmail.com

**Comment by jeessy2** [comment]
保存后会提示的，直接打开那个文件就行

**Comment by cosir888** [comment]
> 保存后会提示的，直接打开那个文件就行

不懂哎。不过我好像意识到此编译方式是uses了gorelease那个步骤实现的。是吗？

**Comment by cosir888** [comment]
或者能明示一下是哪个文件吗

**Comment by jeessy2** [comment]
下个编译后的文件，在打开网页后点击save后，右边会提示配置文件保存在那里了

**Comment by cosir888** [comment]
![Screenshot_20230115173430.jpg](https://s1.locimg.com/2023/01/15/8d8b135663100.jpg)
![Screenshot_20230115173629.jpg](https://s1.locimg.com/2023/01/15/13963d960a115.jpg)


不是github actions的yml

**Comment by jeessy2** [comment]
.github目录下。这个自己找网上教程。。。

**Comment by cosir888** [comment]
> .github目录下。这个自己找网上教程。。。

好的，非常感谢回复。
