### ISSUE TITLE
能否增加同时解析到阿里云和腾讯云的选项

### ISSUE THREAD

**Issue by Vincenzo155** [jeessy2/ddns-go#493]
配置文件只有一个，需要来回修改配置文件
能否增加同时解析到阿里云和腾讯云的选项
目前这个好像只能同时解析到阿里云或腾讯云，希望这个能变成阿里云和腾讯云，而不是阿里云或腾讯云

**Comment by jeessy2** [comment]
dup: #439

**Comment by Vincenzo155** [comment]
> dup: #439

今天阿里云工程师告诉我说：在阿里云添加腾讯云的解析DNS后，仍旧需要到腾讯云添加解析记录【域名在阿里云注册，解析记录阿里云都设置了，不知为何有些人无法访问，总觉得是DNS原因，所以需要同时解析到阿里云和腾讯云】

**Comment by Vincenzo155** [comment]
> dup: #439

还是渴望作者能够更新下的，譬如：通过for循环来读取多个配置文件什么的。

**Comment by jeessy2** [comment]
欢迎PR
