### ISSUE TITLE
能否支持自定义path，以便nginx反向代理使用。

### ISSUE THREAD

**Issue by zhoufla** [jeessy2/ddns-go#494]
如题。

**Comment by jeessy2** [comment]
自身不支持。nginx可指定path，你参考网上的改下就好了

**Comment by zhoufla** [comment]
好的，已解决，感谢。

**Comment by zhoufla** [comment]
我的解决方案如下：
`    location ~ "^/ddns(/?.*)" {
        proxy_pass http://127.0.0.1:9876$1$is_args$args;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;        
    }`
