### ISSUE TITLE
使用本地域访问管理页面被视为“从公网访问”而被禁止访问

### ISSUE THREAD

**Issue by wordlesswind** [jeessy2/ddns-go#495]
## 问题描述
- `local` 域为 mDNS 使用的域，通过 `http://hostname.local:9876` 访问 ddns-go 管理页面被视为“从公网访问”而被禁止访问。
- 此外还有 `home.arpa`、`intranet`、`internal`、`private`、`corp`、`home` 和 `lan` 等被规定用于私人用途的域。
- [Special-use domain name - Wikipedia](https://en.wikipedia.org/wiki/Special-use_domain_name)

## 是否已搜索同类问题
- [x] 已搜索未能解决

## 环境
- 操作系统: Windows 11
- ddns-go 版本: 4.4.2
- 安装方式: Docker

## 截图
![image](https://user-images.githubusercontent.com/9050713/212625552-0588e57b-df0a-46d5-aec0-4d78ef64bcf6.png)

**Comment by wordlesswind** [comment]
> 这个感觉没啥必要，通过私网IP就可以

内网是通过 IPv6 访问的

**Comment by wordlesswind** [comment]
还有个问题是 Armbian 有个特性是重启即会随机 MAC 地址，所以也无法绑定固定的 IPv4 地址。
能通过主机名访问设备在这种情况下显得十分方便。

**Comment by jeessy2** [comment]
IPv4都不能固定？不可能吧

**Comment by wordlesswind** [comment]
> IPv4都不能固定？不可能吧

因为 MAC 地址是每次启动时随机生成的，所以源头上就不固定了。

![image](https://user-images.githubusercontent.com/9050713/212653992-91426b90-6475-4668-a723-2ab890c41120.png)

我现在路由器里都缓存了大量无用的 MAC 地址，不知道怎么清理

**Comment by jeessy2** [comment]
IPv4又不是根据Mac地址生成的

**Comment by wordlesswind** [comment]
> IPv4又不是根据Mac地址生成的

但是路由器会根据 MAC 地址分配 IP 地址呀，小米/Redmi 路由器，华硕路由器都是这样的。
而且在 TP-LINK 等“先来先得” IP 的路由器上如果想固定 IP 地址，那也得绑定 MAC 地址呀。

**Comment by jeessy2** [comment]
路由器默认设置不用绑定Mac/IP的，如果一来就绑定Mac+IP，谁买他家的路由器。
这个根据你情况修改网络设置，或者你开启公网访问

**Comment by VergilGao** [comment]
```
2023/03/14 20:55:07 172.24.99.1:45138 被禁止从公网访问
2023/03/14 20:55:11 172.24.99.1:45152 被禁止从公网访问
```
172.16.0.0-172.31.255.255 都是内网IP，也被禁止访问了

**Comment by jeessy2** [comment]
> ```
> 2023/03/14 20:55:07 172.24.99.1:45138 被禁止从公网访问
> 2023/03/14 20:55:11 172.24.99.1:45152 被禁止从公网访问
> ```
> 
> 172.16.0.0-172.31.255.255 都是内网IP，也被禁止访问了

你通过域名`xxx.local`访问？

**Comment by VergilGao** [comment]
我还是单独开个 issue 吧，我是 nginx反代访问的
