### ISSUE TITLE
IPV6未改变但被强制更新提示

### ISSUE THREAD

**Issue by naoki66** [jeessy2/ddns-go#496]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
IPV6反复强制更新
## 是否已搜索同类问题
- [x ] 已搜索未能解决
- [] 未搜索

## 环境
- 操作系统: dsm7.1
- ddns-go版本: v4.4.2
- 安装方式: docker

## 截图

2023/01/22 05:56:06 IPv6将使用第 1 个IPv6地址
2023/01/22 05:56:06 IPv6未改变，将等待 5 次后与DNS服务商进行比对
2023/01/22 06:06:06 IPv6将使用第 1 个IPv6地址
2023/01/22 06:06:06 IPv6未改变，将等待 4 次后与DNS服务商进行比对
2023/01/22 06:16:06 IPv6将使用第 1 个IPv6地址
2023/01/22 06:16:06 IPv6未改变，将等待 3 次后与DNS服务商进行比对
2023/01/22 06:26:06 IPv6将使用第 1 个IPv6地址
2023/01/22 06:26:06 IPv6未改变，将等待 2 次后与DNS服务商进行比对
2023/01/22 06:36:06 IPv6将使用第 1 个IPv6地址
2023/01/22 06:36:06 IPv6未改变，将等待 1 次后与DNS服务商进行比对
2023/01/22 06:46:06 IPv6将使用第 1 个IPv6地址
2023/01/22 06:46:07 更新域名解析 IPV6.DOMAN 成功！IP: 240e:332:MACIP
2023/01/22 06:46:07 Webhook调用成功, 返回数据: {"code":200,"msg":"请求成功","data":"5d4d4f78d55b45c7a68364db5de088bf","count":null}
2023/01/22 06:56:07 IPv6将使用第 1 个IPv6地址
2023/01/22 06:56:07 IPv6未改变，将等待 5 次后与DNS服务商进行比对
2023/01/22 07:06:07 IPv6将使用第 1 个IPv6地址
2023/01/22 07:06:07 IPv6未改变，将等待 4 次后与DNS服务商进行比对
2023/01/22 07:16:07 IPv6将使用第 1 个IPv6地址
2023/01/22 07:16:07 IPv6未改变，将等待 3 次后与DNS服务商进行比对
2023/01/22 07:26:07 IPv6将使用第 1 个IPv6地址
2023/01/22 07:26:07 IPv6未改变，将等待 2 次后与DNS服务商进行比对
2023/01/22 07:36:07 IPv6将使用第 1 个IPv6地址
2023/01/22 07:36:07 IPv6未改变，将等待 1 次后与DNS服务商进行比对
2023/01/22 07:46:07 IPv6将使用第 1 个IPv6地址
2023/01/22 07:46:08 更新域名解析 IPV6.DOMAN 成功！IP: 240e:332:MACIP
2023/01/22 07:46:08 Webhook调用成功, 返回数据: {"code":200,"msg":"请求成功","data":"7b48c7b5a04043ee85794431d105355b","count":null}
2023/01/22 07:56:08 IPv6将使用第 1 个IPv6地址
2023/01/22 07:56:08 IPv6未改变，将等待 5 次后与DNS服务商进行比对
2023/01/22 08:06:08 IPv6将使用第 1 个IPv6地址
2023/01/22 08:06:08 IPv6未改变，将等待 4 次后与DNS服务商进行比对
2023/01/22 08:16:08 IPv6将使用第 1 个IPv6地址
2023/01/22 08:16:08 IPv6未改变，将等待 3 次后与DNS服务商进行比对
2023/01/22 08:26:08 IPv6将使用第 1 个IPv6地址
2023/01/22 08:26:08 IPv6未改变，将等待 2 次后与DNS服务商进行比对
2023/01/22 08:36:08 IPv6将使用第 1 个IPv6地址
2023/01/22 08:36:08 IPv6未改变，将等待 1 次后与DNS服务商进行比对
2023/01/22 08:46:08 IPv6将使用第 1 个IPv6地址
2023/01/22 08:46:09 更新域名解析 IPV6.DOMAN 成功！IP: 240e:332:MACIP
2023/01/22 08:46:09 Webhook调用成功, 返回数据: {"code":200,"msg":"请求成功","data":"5ef012b785104681ad4509d12eab3bca","count":null}
2023/01/22 08:56:09 IPv6将使用第 1 个IPv6地址
2023/01/22 08:56:09 IPv6未改变，将等待 5 次后与DNS服务商进行比对
2023/01/22 09:06:09 IPv6将使用第 1 个IPv6地址
2023/01/22 09:06:09 IPv6未改变，将等待 4 次后与DNS服务商进行比对
2023/01/22 09:16:09 IPv6将使用第 1 个IPv6地址
2023/01/22 09:16:09 IPv6未改变，将等待 3 次后与DNS服务商进行比对
2023/01/22 09:26:09 IPv6将使用第 1 个IPv6地址
2023/01/22 09:26:09 IPv6未改变，将等待 2 次后与DNS服务商进行比对
2023/01/22 09:36:04 10.0.0.1:17836 请求登陆!
2023/01/22 09:36:09 IPv6将使用第 1 个IPv6地址
2023/01/22 09:36:09 IPv6未改变，将等待 1 次后与DNS服务商进行比对

--------------------------------------多次复核检查，第 1 个IPv6地址没有任何改变------------------------------

**Comment by jeessy2** [comment]
什么dns服务商

**Comment by jeessy2** [comment]
检查你是不是弄了二个ddns服务

**Comment by jeessy2** [comment]
我是指多个ddns都在使用同一个域名，导致互相修改

**Comment by jeessy2** [comment]
dnspod看下解析日志
