### ISSUE TITLE
时间相差8小时

### ISSUE THREAD

**Issue by lizhiwei8061** [jeessy2/ddns-go#497]
esxi上安装openwrt 然后安装ddns go 插件 ；ddns go 日志时间与openwrt 时间相差8小时，没找到合适的解决方案来问一下
![image](https://user-images.githubusercontent.com/121220591/215097577-9f4a3fd7-7930-4ff6-a3aa-2345a1309ce1.png)

**Comment by lqsbg26** [comment]
我在华硕路由器RT-AC66u-B1上装了v4.4.2版的Linux ARM v5版，也同样的问题，其他功能一切正常。操作系统版本 2.6.36.4brcmarm，CPU是博通的BCM4708。

**Comment by jeessy2** [comment]
op安装zoneinfo包试试

**Comment by jeessy2** [comment]
执行`opkg install zoneinfo-asia`后重启op
