### ISSUE TITLE
保存后无法打开WEB设置 页面

### ISSUE THREAD

**Issue by MilkTeaNo7** [jeessy2/ddns-go#499]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景

## 是否已搜索同类问题
- [x] 已搜索未能解决
- [x] 未搜索

## 环境
- 操作系统: 
- ddns-go版本: 
- 安装方式: docker/服务

## 截图

根据示例进行操作，写入cloudflare的API令牌，监听的域名，保存后就无法打开WEB页面了，Docker日志没有报错

**Comment by jeessy2** [comment]
默认开启了禁止公网访问，手动修改配置后重启

**Comment by MilkTeaNo7** [comment]
> 

是的，但是我用内网IP访问的，我怀疑是否因为API格式的原因导致的这个问题呢

**Comment by MilkTeaNo7** [comment]
> 默认开启了禁止上网访问，手动修改配置后重新开启

是的，但是是我用内网IP访问的，我怀疑是不是因为API格式的原因导致的这个问题呢

**Comment by MilkTeaNo7** [comment]
> > 默认开启了禁止上网访问，手动修改配置后重新开启
> 
> 是的，但是是我用内网IP访问的，我怀疑是不是因为API格式的原因导致的这个问题呢

问题找到了，确实是因为禁止公网访问的原因造成的，及时我用的是VPN连接回家，他依旧提示403访问拒绝

**Comment by jeessy2** [comment]
同时会验证网址栏输入的地址
