### ISSUE TITLE
Docker运行提示`Failed to get ipv6`

### ISSUE THREAD

**Issue by li-xunhuan** [jeessy2/ddns-go#5]
如图所示，配置文件是已经配置好了的
![QQ20200902-102053](https://user-images.githubusercontent.com/10476982/91924748-1835ff00-ed06-11ea-9ff5-504b85cac4fe.png)

**Comment by jeessy2** [comment]
是你docker不支持IPV6，就获取不到IPV6地址。如何开启ipv6看下官方教程

**Comment by li-xunhuan** [comment]
> 是你docker不支持IPV6，就获取不到IPV6地址。如何开启ipv6看下docker官方教程

了解了，查了一圈，挺麻烦的，放弃！

**Comment by jeessy2** [comment]
如果你没用windowns,mac桌面版的docker，可以加一个参数`--net=host`

**Comment by li-xunhuan** [comment]
> 如果你没用windowns,mac桌面版的docker，可以加一个参数`--net=host`试下

我跑起来了，编译的二进制文件可以直接在`OpenWrt X86`上运行，我写了个脚本，好使~~
哈哈哈哈~~

**Comment by jeessy2** [comment]
ok. 不跑docker也可以的，加到开机启动里面也可以

**Comment by li-xunhuan** [comment]
> ok. 不跑docker也可以的，加到主机的开机启动里面也可以

对的，我就这么干的
