### ISSUE TITLE
群晖获取路由器ipv6

### ISSUE THREAD

**Issue by MrVicent** [jeessy2/ddns-go#50]
黑群晖 docker装的 
软路由 lean的openwet
按给的操作设置之后 获取到的不是群晖的ipv6地址 而是路由器的ipv6地址
迷茫。。。。这情况怎么解决啊

**Comment by jeessy2** [comment]
不科学吧，获取到路由器的地址了？
有没有更多信息
可以通过网卡获取地址，试下

**Comment by MrVicent** [comment]
![image](https://user-images.githubusercontent.com/50162258/109883471-6f695c00-7cb6-11eb-9a8d-4065e61f3dc4.png)
![image](https://user-images.githubusercontent.com/50162258/109883585-99bb1980-7cb6-11eb-92b2-b2314cac003b.png)
我也觉得不科学啊
所以更迷茫了

**Comment by jeessy2** [comment]
你获取的IPv6就不正常。检查一下配置
