### ISSUE TITLE
RequestBody返回ip地址异常

### ISSUE THREAD

**Issue by Rockney99** [jeessy2/ddns-go#500]
## 问题描述
- 阐述 记录/问题/事件/... 发生的背景
RequestBody钉钉返回通知ipv4地址127.0.0.1 ipv6显示::1
## 是否已搜索同类问题
- [ ] 已搜索未能解决

## 环境
- 操作系统: windows
- ddns-go版本: 4.4.2
- 安装方式: docker/服务exe

## 截图
![image](https://user-images.githubusercontent.com/42824224/215346549-5b4c99db-99c3-4880-9916-35698f87c133.png)

**Comment by jeessy2** [comment]
模拟测试，点击后有文字说明
