### ISSUE TITLE
不能安装服务

### ISSUE THREAD

**Issue by orangepickson** [jeessy2/ddns-go#501]
## 是否已搜索同类问题
- [x] 已搜索未能解决
- [ ] 未搜索

## 环境
- 操作系统: windows11
- ddns-go版本: 
- 安装方式: Win(以管理员打开cmd): .\ddns-go.exe -s install

## 截图
![屏幕截图 2023-01-30 132951](https://user-images.githubusercontent.com/123923986/215395042-bb84e736-b60a-4d66-b13f-8fb967778182.png)

**Comment by popweiok** [comment]
不用前面 的 ./试一下

**Comment by jeessy2** [comment]
应该是目录下没ddns程序

**Comment by jeessy2** [comment]
`cd ddns-go目录`
