### ISSUE TITLE
希望新增一个dynv6.com的服务商

### ISSUE THREAD

**Issue by gally16** [jeessy2/ddns-go#502]
希望新增一个dynv6.com的服务商
总是错误

**Comment by jeessy2** [comment]
使用callback。搜索下别人怎么操作的

**Comment by jeessy2** [comment]
[ipconfig | findstr IPv6](https://github.com/jeessy2/ddns-go/wiki/Callback%E9%85%8D%E7%BD%AE%E5%8F%82%E8%80%83)

**Comment by jeessy2** [comment]
https://github.com/jeessy2/ddns-go/wiki/Callback配置参考
