### ISSUE TITLE
Webhook中使用的变量内容似乎为默认值

### ISSUE THREAD

**Issue by mustard0207** [jeessy2/ddns-go#504]
## 问题描述
- 使用dnspod.cn，能够正常获取IPv6地址和更新域名记录。但在Webhook中，我使用推送企业微信时，接收到的信息像是默认值。尝试了IPv4和IPv6变量，均不正常。

## 环境
- 操作系统: 群晖6.2
- ddns-go版本: v4.4.2
- 安装方式: docker/服务

## 截图
![584cdf907f5e7a67e1d8862c2caece6](https://user-images.githubusercontent.com/41184957/215728963-6a7ad2ae-b73e-490d-b02c-2825b7a97de8.jpg)
![image](https://user-images.githubusercontent.com/41184957/215729031-5de49217-ad89-40ca-a6be-1bea84dc90b3.png)

**Comment by mustard0207** [comment]
![image](https://user-images.githubusercontent.com/41184957/215729356-6bb5e9e9-738f-46c1-af2d-0389cd7f326d.png)
以上为日志。

**Comment by mustard0207** [comment]
![image](https://user-images.githubusercontent.com/41184957/215729598-0cb91979-0153-499b-bdae-fa83dc06941c.png)
以上为日志。

**Comment by jeessy2** [comment]
模拟测试是这样的，假数据

**Comment by jeessy2** [comment]
点击后有说明的，仔细看下

**Comment by mustard0207** [comment]
> 点击后有说明的，仔细看下

好的，看到了。谢谢~！
