### ISSUE TITLE
提议：使用 GitHub Actions 自动测试

### ISSUE THREAD

**Issue by WaterLemons2k** [jeessy2/ddns-go#505]
当触发推送（push）或拉取请求（pull_request）事件时，使用 GitHub Actions 自动测试。

详见：
- [构建和测试 Go - GitHub Docs](https://docs.github.com/zh/actions/automating-builds-and-tests/building-and-testing-go)
- [github-actions-golang/test.yml at master · mvdan/github-actions-golang](https://github.com/mvdan/github-actions-golang/blob/master/.github/workflows/test.yml)

**Comment by jeessy2** [comment]
欢迎来PR
