### ISSUE TITLE
openwrt ddns-go cloudflare

### ISSUE THREAD

**Issue by Ran-Xing** [jeessy2/ddns-go#507]
XXXXX，我刚准备发issues，结果 叮咚 钉钉提示IP更新

能不能麻烦添加一下 详细日志输出的选项，哭了

![image](https://user-images.githubusercontent.com/73819467/216082152-d35ee015-325b-4592-b4f0-32ad789236f3.png)

但是实际上cloudfalre 上 显示的IP 不是这个

我怀疑是访问失败，但是没有显示错误，而且我直接 curl cloudflare 的接口也能访问

纯粹吐槽一下，谢谢

**Comment by jeessy2** [comment]
看了半天没看明白😓

**Comment by Ran-Xing** [comment]
@jeessy2 就是说一直无法正确的更新dns，我正准备提交issues 结果钉钉弹出通知了，我是想麻烦你添加一个选项，比如说debug，正常情况是info，debug的话是debug，说不定我能从日志中判断原因

我的openwrt 科学了，能正常访问 cloudflare ，但是 一直提示ipv4未改变，我猜测就是没有获取到cloudflare上的dns 设置，所以没有更新

**Comment by jeessy2** [comment]
所有日志都打印了，没分级。看下全部日志分析下
