### ISSUE TITLE
提议：自动关闭不活跃的 issues 和 PRs

### ISSUE THREAD

**Issue by WaterLemons2k** [jeessy2/ddns-go#508]
使用 [actions/stale](https://github.com/actions/stale) 自动关闭不活跃的 issues 和 PRs。

如果需要豁免指定 issues，可以使用选项 `exempt-issue-labels`，示例：
```
exempt-issue-labels: question,bug
```
此时会豁免带 `question,bug` 标签的 issues。

如果需要豁免指定 PRs，可以使用选项 `exempt-pr-labels`，示例：
```
exempt-pr-labels: need-help,WIP
```
此时会豁免带 `need-help,WIP` 标签的 PRs。

参考：
- [关闭不活跃的议题 - GitHub Docs](https://docs.github.com/zh/actions/managing-issues-and-pull-requests/closing-inactive-issues)
- [frp/stale.yml at dev · fatedier/frp](https://github.com/fatedier/frp/blob/dev/.github/workflows/stale.yml)

**Comment by jeessy2** [comment]
可以。来个PR
