### ISSUE TITLE
windows下安装为服务后配置文件保存位置

### ISSUE THREAD

**Issue by leganck** [jeessy2/ddns-go#51]
windows下安装为服务后配置文件保存到了
![image](https://user-images.githubusercontent.com/24834938/110204373-99d13a00-7ead-11eb-8331-3a0c800d9449.png)
并没有保存到用户文件夹或者和执行文件同一个目录

这样不方便找到 我是使用everything 找到的

**Comment by jeessy2** [comment]
使用服务模式，不需要登陆用户也可以使用。所以配置文件不再用户目录下。根据不同系统，存放位置就不同。

**Comment by zhezhe168** [comment]
linux下的配置文件在哪里

**Comment by jeessy2** [comment]
> linux下的配置文件在哪里

搜索一下，具体我也不知道

**Comment by zhezhe168** [comment]
whereis没搜到，可能在哪几个目录下

**Comment by leganck** [comment]
用find搜
