### ISSUE TITLE
提议：自动同步 README.md 到 Docker Hub

### ISSUE THREAD

**Issue by WaterLemons2k** [jeessy2/ddns-go#517]
使用 [peter-evans/dockerhub-description](https://github.com/peter-evans/dockerhub-description) 自动同步 `README.md` 到 Docker Hub。

**Comment by jeessy2** [comment]
可以

**Comment by WaterLemons2k** [comment]
那是在推送镜像时同步，还是在推送 `README.md` 时同步？

**Comment by jeessy2** [comment]
推送`README.md`合适点
