### ISSUE TITLE
无法保存配置，提示出于安全考虑，若通过公网访问，仅允许在服务启动的 10 分钟内完成首次配置文件的保存

### ISSUE THREAD

**Issue by Tatchaxzw** [jeessy2/ddns-go#521]
ddns-go无法保存配置
运行稳定，今晚想要更改webhook配置时，发现提示“出于安全考虑，若通过公网访问，仅允许在服务启动的 10 分钟内完成首次配置文件的保存”。
设置禁止公网访问，无效。
重启套件，无效。
重新安装套件，无效。
重启群晖，无效。

## 是否已搜索同类问题
未搜索到

## 环境
- 操作系统: 群晖
- ddns-go版本: 4.5.0
- 安装方式: 群晖矿神套件

![1](https://user-images.githubusercontent.com/67794844/216769770-9e31aca3-176d-4838-9dbd-069c0d6b815a.png)

**Comment by jeessy2** [comment]
看了代码，这个需要升级，升级到4.5.1，需要旷神来升级，我这没联系方式。

**Comment by Tatchaxzw** [comment]
> 看了代码，这个需要升级，升级到4.5.1，需要旷神来升级，我这没联系方式。

确实是重启10分钟之内也无效，也试了卸载套件，重启群晖，重新安装这种方式。
也是内网访问的！
请问怎么查看配置文件是否加载？
我注意到启动后日志提示：Geting current user failed!

**Comment by Tatchaxzw** [comment]
> 看了代码，这个需要升级，升级到4.5.1，需要矿神来升级，我这没联系方式。 不升级的话，你重启后10分钟之内修改或者使用私网IP+端口访问，也不会提示的。

谢谢，等矿神升级吧，或者我以后用docker安装ddns-go。
以前没遇到这种问题，似乎是今晚套件升级到4.5.0后才出现的，但我不能确定，因为不是经常修改配置。

**Comment by jeessy2** [comment]
> 请问怎么查看配置文件是否加载？

配置在页面上显示出来没有

我这里保存正常，需要截图更多信息分析

**Comment by Tatchaxzw** [comment]
> > 请问怎么查看配置文件是否加载？
> 
> 配置在页面上显示出来没有
> 
> 我这里保存正常，需要截图更多信息分析

![Uploading 1.png…]()

**Comment by Tatchaxzw** [comment]
> > 请问怎么查看配置文件是否加载？
> 
> 配置在页面上显示出来没有
> 
> 我这里保存正常，需要截图更多信息分析

![1](https://user-images.githubusercontent.com/67794844/216772474-3987402a-67c4-416d-9bb1-b66669cbeb4a.png)

**Comment by Tatchaxzw** [comment]
> > 请问怎么查看配置文件是否加载？
> 
> 配置在页面上显示出来没有
> 
> 我这里保存正常，需要截图更多信息分析

![1](https://user-images.githubusercontent.com/67794844/216772500-e4195c5d-f773-4c23-af97-9d2760fc9ec0.png)

**Comment by jeessy2** [comment]
访问地址发来看下？有可能是配置文件没有

**Comment by Tatchaxzw** [comment]
> 访问地址发来看下？有可能是配置文件没有

www.xtatcha.com:19953

**Comment by jeessy2** [comment]
你是公网域名，别发了。要群晖的私网IP+端口

**Comment by Tatchaxzw** [comment]
> 你是公网域名，别发了。要群晖的私网IP+端口

我以为你要看下界面上的日志，我这儿是用内网的

**Comment by Tatchaxzw** [comment]
> 你是公网域名，别发了。要群晖的私网IP+端口

![2](https://user-images.githubusercontent.com/67794844/216772731-7a6ae734-7771-42f4-b1f3-1cac9c14b81f.png)

**Comment by jeessy2** [comment]
1.1.1.4不是私网，只是路由不到你那里

**Comment by Tatchaxzw** [comment]
> 1.1.1.4不是私网，只是路由不到你那里

是因为我家设置的内网网段就是这个，之前更改没问题啊

**Comment by jeessy2** [comment]
v4私网
10.0.0.0 – 10.255.255.255
172.16.0.0 – 172.31.255.255
192.168.0.0 – 192.168.255.255

重启应该是可以的，10分钟内修改

**Comment by Tatchaxzw** [comment]
> v4私网 10.0.0.0 – 10.255.255.255 172.16.0.0 – 172.31.255.255 192.168.0.0 – 192.168.255.255
> 
> 重启应该是可以的，10分钟内修改

谢谢，设置之前没考虑到这些问题，我把家里网段改掉吧

**Comment by Peins** [comment]
我也遇到了，不知道怎么解决，所以到底什么问题

**Comment by jeessy2** [comment]
> 我也遇到了，不知道怎么解决，所以到底什么问题

通过内网地址访问

**Comment by Peins** [comment]
> > 我也遇到了，不知道怎么解决，所以到底什么问题
> 
> 通过内网地址访问

刚刚解决了，学校有59.xxx和180.xx两个公网，用成59.了，用192.168.xx就好了

**Comment by jeessy2** [comment]
需要公网访问升级到[4.5.3](https://github.com/jeessy2/ddns-go/releases/tag/v4.5.3)
