### ISSUE TITLE
[Bug]：旁路由OP无法通过接口获取IPV6

### ISSUE THREAD

**Issue by flywalt** [jeessy2/ddns-go#538]
### 问题描述

主路由ikuai，旁路由OP，在OP里面的ddns-go解析IPV6，通过网卡会出现2-4个地址，顺序还会变，会出现随机的解析失败
通过接口会提示
2023/02/08 21:15:06 连接失败! [点击查看接口能否返回IPv6地址](https://myip6.ipip.net/), 参考说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2023/02/08 21:15:06 错误信息: Get "https://myip6.ipip.net": dial tcp6: lookup myip6.ipip.net on 127.0.0.1:53: no such host
2023/02/08 21:15:06 连接失败! [点击查看接口能否返回IPv6地址](https://speed.neu6.edu.cn/getIP.php), 参考说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2023/02/08 21:15:06 错误信息: Get "https://speed.neu6.edu.cn/getIP.php": dial tcp6: lookup speed.neu6.edu.cn on 127.0.0.1:53: no such host
2023/02/08 21:15:06 连接失败! [点击查看接口能否返回IPv6地址](https://v6.ident.me/), 参考说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2023/02/08 21:15:06 错误信息: Get "https://v6.ident.me": dial tcp6: lookup v6.ident.me on 127.0.0.1:53: no such host
2023/02/08 21:15:06 未能获取IPv6地址, 将不会更新
2023/02/08 21:19:59 连接失败! [点击查看接口能否返回IPv6地址](https://myip6.ipip.net/), 参考说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)

确定IPV6是启用的，也参照文档用了命令启动容器docker run -d --name ddns-go --restart=always --net=host -v /opt/ddns-go:/root jeessy/ddns-go
测试了用op的服务或者是docker都一样

另外一个比较奇怪的问题是，同一个内网下的群晖里ddns-go就能正确通过接口获取，不知道问题在哪，求解

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

latest

### 安装方式

Docker

### 额外信息

无

**Comment by jeessy2** [comment]
看日志，应该是你dns解析不了域名，可以nslookup测试一下

**Comment by flywalt** [comment]
> 

哦大佬说的是对的！
root@DF-NET:~# nslookup https://myip6.ipip.net
Server:         127.0.0.1
Address:        127.0.0.1:53


** server can't find https://myip6.ipip.net: NXDOMAIN

不过OP应该怎么设置我也不太懂……

**Comment by jeessy2** [comment]
nslookup myip6.ipip.net
不要https

**Comment by flywalt** [comment]
root@DF-NET:~# nslookup myip6.ipip.net
Server:         127.0.0.1
Address:        127.0.0.1:53


Name:   myip6.ipip.net
Address: 139.198.30.138

这个好像又是正常的？

**Comment by jeessy2** [comment]
试下这个。nslookup speed.neu6.edu.cn
要解析出v6地址才行

**Comment by flywalt** [comment]
root@DF-NET:~# nslookup speed.neu6.edu.cn
Server:         127.0.0.1
Address:        127.0.0.1:53

不知道为啥解析不出来，通过网卡就能获取V6地址，看了OP自己的接口也能显示三个地址。然后因为是旁路由，不在dhcp段内，主路由ikuai上倒是看不到这个地址

**Comment by jeessy2** [comment]
查看你dns过滤掉了ipv6地址。或则你使用网卡获取ipv6测下

**Comment by flywalt** [comment]
看了下op的设置，并未勾选禁止解析 IPv6 DNS 记录
不知道在lan6的接口高级设置里面有没有啥问题
![image](https://user-images.githubusercontent.com/56569425/217570371-d29677fa-f5cf-48eb-b3b6-ef0504461e89.png)
![image](https://user-images.githubusercontent.com/56569425/217570632-c7022a56-63ec-4e06-ba94-95d01d315c5d.png)

网卡获取是正常的，但是就是因为会获取到很多地址，乱序，不稳定

**Comment by jeessy2** [comment]
网卡用第几个或正则固定。
OP在dns设置的高级设置中是否勾选了`禁止解析 IPv6 DNS 记录`

**Comment by flywalt** [comment]
网卡第几个经常变
正则不太会写，地址大概长这样
![image](https://user-images.githubusercontent.com/56569425/217573812-a2ec37a5-2ac1-4232-9ca9-6b578ba5e9d7.png)
第一个是有效的
也没勾选那个禁止解析

正在看其他文档看是不是OP的设置不对
