### ISSUE TITLE
[功能]：PR 模板

### ISSUE THREAD

**Issue by WaterLemons2k** [jeessy2/ddns-go#539]
### 功能描述

通过添加 `pull_request_template.md` 文件规范 PR 格式。

### 附加信息

[为仓库创建拉取请求模板 - GitHub 文档](https://docs.github.com/zh/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**Comment by jeessy2** [comment]
可以的
