### ISSUE TITLE
[功能]：需要设置定时任务吗?

### ISSUE THREAD

**Issue by TeemoZhang-ice** [jeessy2/ddns-go#541]
### 功能描述

定时检查ipv6是否改变

**Comment by jeessy2** [comment]
没看懂。本身就自带的

**Comment by TeemoZhang-ice** [comment]
> 没看懂。本身就自带的

请问作者：
开机运行后，命令行可以关掉吗？
网页可以关掉吗？

**Comment by WaterLemons2k** [comment]
> > 没看懂。本身就自带的
> 
> 请问作者： 开机运行后，命令行可以关掉吗？ 网页可以关掉吗？

关掉命令行是 #524 吗，关掉网页是添加选项 `-noweb`。

**Comment by jeessy2** [comment]
安装服务，开机后自动运行，不用管
网页可以关，方便你配置的

**Comment by TeemoZhang-ice** [comment]
@WaterLemons2k， @jeessy2 谢谢，我明白了，这个程序非常符合我的需求。现在加上了这个开机自动启动【后台】，可以不用再管它了，太好了
