### ISSUE TITLE
[功能]：自动为 PR 添加标签

### ISSUE THREAD

**Issue by WaterLemons2k** [jeessy2/ddns-go#542]
### 功能描述

使用 [actions/labeler](https://github.com/actions/labeler) 自动为 PR 添加标签。

### 附加信息

默认配置文件路径为 `.github/labeler.yml`，示例：
```YAML
go:
- 'main.go'
```
为修改了 `main.go` 文件的 PR 添加 `go` 标签。

**Comment by jeessy2** [comment]
这个感觉没啥必要
