### ISSUE TITLE
[功能]：创建文档 (docs)

### ISSUE THREAD

**Issue by WaterLemons2k** [jeessy2/ddns-go#543]
### 功能描述

将 `README.md` 的二级标题 `Webhook` 和 `Callback`，带 `documentation` 标签的 issues 复制一份到 `docs` 文件夹。

删除 `README.md` 的二级标题 `Webhook` 和 `Callback`，创建新二级标题 `文档`，链接到 `docs` 文件夹。

### 解决的问题

`README.md` 的二级标题 `Webhook` 部分可能会在未来过于冗长。

### 附加信息

如果创建了 `docs` 文件夹，目录结构可能如下：
```
docs/
├── Callback.md
├── Custom-parameters.md
├── Get-IP-by-commands.md
└── Webhook.md
```

**Comment by jeessy2** [comment]
估计不适合把Webhook放在二级目录下，配置页面中的Webhook链接就是根目录，会影响以前的用户。
Webhook在首页的README.md中就不新增加了，要加也就加一些常用的。

**Comment by WaterLemons2k** [comment]
那在 `Webhook` 结尾处添加 `更多`，链接到 `docs` 和 issue 如何？

**Comment by jeessy2** [comment]
> 那在 `Webhook` 结尾处添加 `更多`，链接到 `docs` 和 issue 如何？

可以
