### ISSUE TITLE
[Bug]：出于安全考虑，若通过公网访问，仅允许在服务启动的 10 分钟内完成首次配置文件的保存

### ISSUE THREAD

**Issue by zs910** [jeessy2/ddns-go#545]
### 问题描述

vps上安装
新建10分钟内 无法通过公网IP+端口   修改为 使用密码公网IP访问。提示出于安全考虑，若通过公网访问，仅允许在服务启动的 10 分钟内完成首次配置文件的保存。
因为基本使用在  代理服务器环境中 VPS方便解析IP到cf，不想搭个环境 反代内网访问。
请问有啥解决方法，感谢

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### ddns-go 版本

4.5.2

### 安装方式

服务

**Comment by jeessy2** [comment]
重启ddns-go，在10分钟之内保存

**Comment by zs910** [comment]
> 重新启动ddns-go，在10分钟之内保存
一样搞不懂为什么。 
以下是我的详细安装方法
------------------------------------------
#!/bin/bash
apt install curl -y
systemctl stop ddns-go
rm /usr/bin/ddns-go
mkdir ./ddns
cd ./ddns
uname -m | grep -qi aarch64 && oarch=linux_arm64 || oarch=linux_x86_64;
wget "$(curl -s https://api.github.com/repos/jeessy2/ddns-go/releases/latest|grep -i "browser_download_url.*${oarch}"|awk -F '"' '{print $(NF-1)}')";
tar -xzvf ./ddns*.tar.gz
chmod +x ./ddns-go
mv ./ddns-go /usr/bin
cd ..
rm -rf ./ddns
ddns-go -s install
systemctl start ddns-go

-------------------------------------------------------------------------
重启服务后还是这样。 在其他VPS 上都复现了
![image](https://user-images.githubusercontent.com/48160567/218120168-2a2974b9-0f70-4611-9210-fc1078ee3c27.png)

**Comment by zs910** [comment]
说实话 能否添加个脚本 ssh里直接设置 允许公网IP访问 并设置密码。
而不是只能内网IP访问，这样VPS 更加友好

**Comment by jeessy2** [comment]
截图截全点，重要信息打个码

**Comment by zs910** [comment]
https://user-images.githubusercontent.com/48160567/218125250-6458e67f-9fff-4e45-b6da-13998207d175.mp4

重启服务后 还是无法保存

**Comment by jeessy2** [comment]
好久重启的？

**Comment by zs910** [comment]
![image](https://user-images.githubusercontent.com/48160567/218127843-7b665243-57b1-457c-aebb-f547e083c17e.png)
我试过重启服务 和直接重启服务器 都这样

**Comment by jeessy2** [comment]
对。是有这个问题。

**Comment by zs910** [comment]
人嘛了，换旧版本

**Comment by zs910** [comment]
nginx反代启用SSL ,对家庭网络或者nas 是安全，但是对VPS 是真不友好，特别是只做代理的VPS服务器。希望大佬修复

**Comment by jeessy2** [comment]
正在打包，等几分钟打包好后测下。没VPS，没注意到这个问题

**Comment by zs910** [comment]
![image](https://user-images.githubusercontent.com/48160567/218132510-4fc654f9-c9bd-4b7b-a083-7c7e17aa0e1e.png)
已经修复，感谢大佬

**Comment by jeessy2** [comment]
感谢反馈。不然都不知道是这个问题 😓
