### ISSUE TITLE
梅林armv7 怎么安装啊

### ISSUE THREAD

**Issue by qian9008** [jeessy2/ddns-go#547]
Illegal instruction
错误

**Comment by jeessy2** [comment]
重新下一个arm版本试试

**Comment by qian9008** [comment]
> 重新下一个arm版本试试

567  64 都不行

**Comment by WaterLemons2k** [comment]
看一下 CPU 型号：
```
cat /proc/cpuinfo
```

**Comment by qian9008** [comment]
> 看一下 CPU 型号：
> 
> ```
> cat /proc/cpuinfo
> ```

Processor       : ARMv7 Processor rev 0 (v7l)
processor       : 0
BogoMIPS        : 1998.84

processor       : 1
BogoMIPS        : 1998.84

Features        : swp half thumb fastmult edsp
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Hardware        : Northstar Prototype
Revision        : 0000
Serial          : 0000000000000000

**Comment by WaterLemons2k** [comment]
https://github.com/WaterLemons2k/Test-ddns-go/releases/download/v0.0.1/ddns-go

使用 Go 1.17 和命令 `CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5 go build -ldflags "-s -w -extldflags -static -extldflags -static"` 构建，看看行不行

另外还找到了 https://github.com/CodeMonk/dd-wrt-go

**Comment by gzxief** [comment]
用docker方便

**Comment by qian9008** [comment]
> 用docker方便

多设备多ip。
