### ISSUE TITLE
[Bug]：无法获取ipv6地址

### ISSUE THREAD

**Issue by xmo566** [jeessy2/ddns-go#549]
### 问题描述

报错Get "https://myip6.ipip.net": dial tcp6 [2402:e7c0:0:200::5]:443: connect: cannot assign requested address

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

armv7

### ddns-go 版本

v4.5.3

### 安装方式

Docker

**Comment by jeessy2** [comment]
可以google搜索`connect: cannot assign requested address` 。或用网卡获取IPv6

**Comment by xmo566** [comment]
> 可以google搜索`connect: cannot assign requested address` 。或用网卡获取IPv6
网卡获取显示没有可用的网卡，但ipv4能显示出网卡

**Comment by xmo566** [comment]
> 可以google搜索`connect: cannot assign requested address` 。或用网卡获取IPv6

网卡获取显示没有可用的网卡，但ipv4能显示出网卡

**Comment by jeessy2** [comment]
查看你是否有IPv6地址，IPv6通不通

**Comment by icstudiochina** [comment]
同求，几个接口都是返回这个，但是服务端curl 能返回正确的ipv6地址

**Comment by jeessy2** [comment]
你们更新频率多少？每次通过接口获取IP都会新建连接的

**Comment by icstudiochina** [comment]
默认的5分钟

**Comment by jeessy2** [comment]
那不得。Google搜索下，查看time_out连接有多少

**Comment by icstudiochina** [comment]
![image](https://user-images.githubusercontent.com/29295169/220319829-313f0383-2cd6-463e-96f5-ffe1b5b76b64.png)

**Comment by jeessy2** [comment]
搜这个Cannot assign requested address
看怎么解决的

**Comment by icstudiochina** [comment]
大致上是由于客户端频繁的连服务器，由于每次连接都在很短的时间内结束，导致很多的TIME_WAIT，以至于用光了可用的端 口号，所以新的连接没办法绑定端口，即“Cannot assign requested address”。是客户端的问题不是服务器端的问题。通过netstat，的确看到很多TIME_WAIT状态的连接。

client端频繁建立连接，而端口释放较慢，导致建立新连接时无可用端口。

**Comment by jeessy2** [comment]
查看啥进程引起的

**Comment by xmo566** [comment]
找到问题了， Docker容器网络没有开启host，那说来也奇怪，之前开了也没显示出来
