### ISSUE TITLE
请问能不能修改/root/.ddns_go_config.yaml为执行文件系统的文件夹

### ISSUE THREAD

**Issue by qingdeng888** [jeessy2/ddns-go#551]
### 功能描述

编译好的可执行文件.ddns_go_config.yaml默认生成/root/.ddns_go_config.yaml 请问可否将其放在可执行文件相同文件夹

**Comment by jeessy2** [comment]
暂不。会影响老用户

**Comment by jeessy2** [comment]
默认当前用户目录，可以参考首页说明修改到指定目录

**Comment by JamaisVuu** [comment]
> 默认当前用户目录，可以参考首页说明修改到指定目录

感觉默认生成在运行目录比较好，今天在/root/ddns-go 运行sudo ./ddns-go -s install，重试了好几次没看到config 文件，原来在/root下😂
