### ISSUE TITLE
[Bug]：无法使用多个域名

### ISSUE THREAD

**Issue by Na3MnO4** [jeessy2/ddns-go#555]
### 问题描述

复现环境
Cloudflare
IPV4
——————————
若Domain中填写：
a.com
b.com
DDNS-GO只会检查填写在前者的a.com，而不会检查b.com

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### ddns-go 版本

v4.5.1

### 安装方式

服务

### 额外信息

<img width="943" alt="image" src="https://user-images.githubusercontent.com/69727714/218770350-b7f7e080-018c-49aa-8d1b-815e2beb33f9.png">

**Comment by jeessy2** [comment]
检查你的B域名是不是写错了。或者此token权限无法操作B域名

**Comment by Na3MnO4** [comment]
感谢，检查了一下。
发现B域名可能因为未知原因，无法由ddns-go检查，在Github寻找了其他的DDNS项目想验证是否是我的域名问题，发现是可以正常解析的没有问题

**Comment by jeessy2** [comment]
B域名什么结尾的？有可能你用的免费域名，cloudflare通过API不支持免费域名

**Comment by Na3MnO4** [comment]
org 正常托管到cloudflare的

**Comment by Na3MnO4** [comment]
请问ddns-go的log在哪里 要不看看有没有报错？

**Comment by jeessy2** [comment]
eu.org? 日志页面上看

**Comment by Na3MnO4** [comment]
是的

**Comment by Na3MnO4** [comment]
两个域名都是eu.org的 挺奇怪的

**Comment by WaterLemons2k** [comment]
> 两个域名都是eu.org的 挺奇怪的

第二个是子域名吗？

**Comment by Na3MnO4** [comment]
不 都是单独申请的

**Comment by WaterLemons2k** [comment]
> 不 都是单独申请的

是不是 [Open domains and policies](https://nic.eu.org/opendomains.html) 列出的 eu.org 的子域名，例如 `cn.eu.org`。

**Comment by Na3MnO4** [comment]
那对的 无效的是.net.eu.org下面的 有效的是eu.org下的

From ENDzZ
________________________________

**Comment by WaterLemons2k** [comment]
> 那对的 无效的是.net.eu.org下面的 有效的是eu.org下的

那是因为 `eu.org` 是写死的，不支持 `eu.org` 的子域名（ c928df0 ）。

**Comment by Na3MnO4** [comment]
好吧

**Comment by jeessy2** [comment]
用冒号分割试下。domains下有备注

**Comment by Na3MnO4** [comment]
似乎没什么用 我把net.eu.org加到domains.go里再自己编译了 感谢帮助

**Comment by Na3MnO4** [comment]
是的 使用了此种填写方法 依旧无效

> 类似这样填写test:net.eu.org

**Comment by jeessy2** [comment]
会golang 那你可以调试. 没那个域名，这些域名也太奇怪了
