### ISSUE TITLE
[功能]：甲骨文外网ipv4

### ISSUE THREAD

**Issue by shaojs321** [jeessy2/ddns-go#557]
### 功能描述

甲骨文的ddns go 目前只能获得内网ipv4，拿不到外网ipv4，作者有时间更新一下吗

**Comment by shaojs321** [comment]
上面说的是通过网卡方式，接口的话，有时候不太准

**Comment by jeessy2** [comment]
网卡获取不到公网IP，只有接口，你找个准的接口
