### ISSUE TITLE
[Bug]：docker Error

### ISSUE THREAD

**Issue by gzxief** [jeessy2/ddns-go#558]
### 问题描述

Digest: sha256:5dd30491a14f21089e6936e2bac84827e806161a470d803a32301449d4322df9
Status: Downloaded newer image for jeessy/ddns-go:latest
ee71cf16d577cfc27cf0e9a00f206176e593982e7aff6aa403136d79a48ece4d
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown.

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### ddns-go 版本

v4.5.3

### 安装方式

Docker

### 额外信息

Digest: sha256:5dd30491a14f21089e6936e2bac84827e806161a470d803a32301449d4322df9
Status: Downloaded newer image for jeessy/ddns-go:latest
ee71cf16d577cfc27cf0e9a00f206176e593982e7aff6aa403136d79a48ece4d
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown.

**Comment by gzxief** [comment]
docker拉取后故障

**Comment by jeessy2** [comment]
试下其他非ddns-go镜像。有可能是docker版本问题

**Comment by gzxief** [comment]
> 试下其他非ddns-go镜像。有可能是Docker版本问题

docker run -d --name ddns-go --restart=always --privileged --net=host -v /ddns-go:/root jeessy/ddns-go
 加上--privilege之后正常运行
