### ISSUE TITLE
windows server 2012 R2运行异常

### ISSUE THREAD

**Issue by yyocean** [jeessy2/ddns-go#56]
在这个系统上，解析DNSPOD，打开后会提示打开端口异常，一分钟后关闭，放在那，过一会之后就开始更新，有时候会提示IPV6查不到地址。多开几次就正常。但是安装服务之后，几乎就没成功过。也就是手动打开可以，安装服务不行。每次打开都是端口异常

**Comment by jeessy2** [comment]
安装服务后，已经占了9876端口了。手动打开就会提示端口异常，无需手动打开，程序自动运行的。

**Comment by yyocean** [comment]
但还是无法自动更新，手动打开倒是可以，而且经常提示IPV6查询不到地址

**Comment by jeessy2** [comment]
把日志贴来看下，去掉个人信息

**Comment by yyocean** [comment]
2021/03/26 23:23:38 你的IP ****** 没有变化, 域名 ****.***.com
2021/03/26 23:23:38 你的IP ****** 没有变化, 域名 ****.***.com
2021/03/26 23:25:10 未能获得IPv6地址! 点击查看接口能否返回IPv6地址, 官方说明:点击访问
2021/03/26 23:30:12 你的IP ****** 没有变化, 域名 ****.***.com
2021/03/26 23:35:22 你的IP ****** 没有变化, 域名 ****.***.com
2021/03/26 23:40:25 更新域名解析 www.****.com 成功！IP: ******
2021/03/26 23:45:36 未能获得IPv6地址! 点击查看接口能否返回IPv6地址, 官方说明:点击访问
2021/03/26 23:50:06 未能获得IPv6地址! 点击查看接口能否返回IPv6地址, 官方说明:点击访问
2021/03/26 23:50:07 你的IP ***.***.***.***. 没有变化, 域名 www.****.com
2021/03/26 23:50:39 读取IPv6结果失败! 查询URL: https://api-ipv6.ip.sb/ip
2021/03/26 23:50:40 你的IP ***.***.***.***. 没有变化, 域名 www.****.com

www.****.com是IP4的解析
****.****.com是IPV6的解析

**Comment by yyocean** [comment]
在网页里保存了设置之后，系统服务是不是就是按照这个网页设置来操作？

**Comment by yyocean** [comment]
怎么样缩短更新时间，这个参数在哪里设置？5分钟太长了

**Comment by jeessy2** [comment]
嗯。有可能是接口/网络不稳定。你可以通过网卡获取ipv6，不用考虑接口稳定不了

**Comment by jeessy2** [comment]
参考文档。先卸载服务。重新安装服务。

Win(以管理员打开cmd): .\ddns-go.exe -s install -f 60
安装服务也支持 -l监听地址 -f同步间隔时间(秒)

**Comment by yyocean** [comment]
可能因为我找你了，程序害怕作者找麻烦，现在测试可以了

**Comment by jeessy2** [comment]
呵呵。不是这个原因哈

**Comment by yyocean** [comment]
不过现在有个问题就是，我另外一个场地的电脑，可能是网络结构的原因，那边通过网卡获取的IPv6地址跟接口获取的不一样。前4段一样，后四段不一样。这两个地址是同一个地址吗？

**Comment by jeessy2** [comment]
网卡获取的是相对固定的，接口获取的是临时的IPv6

**Comment by yyocean** [comment]
****:***:***:****:c0b4:7d91:7617:2网卡
****:***:***:****:f127:9b4a:a75f:27c4接口
这样网卡获取的也可以用吗

**Comment by jeessy2** [comment]
标准的v6都可以用的

**Comment by yyocean** [comment]
恩，试试看。你这个程序是我找过windows下最好用的一个。同时解析2个，省去很多事。
