### ISSUE TITLE
[Bug]：nginx反向代理后无法访问web：9876

### ISSUE THREAD

**Issue by fengyuclub** [jeessy2/ddns-go#562]
### 问题描述

每次访问一闪就没有了，4.5.2和新版4.5.3都是这样，无论主机和docker都是同样问题？因为都是nat后主机和docker使用发生的问题，用出口网关设备做映射到主机或docker端口9876就可以访问，请看看问题在哪里？
x86_64&N1&群晖x86都试了。

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

v4.5.2-4.5.3

### 安装方式

Docker

**Comment by jeessy2** [comment]
能描述清楚一点否？描述清楚详细一点，截个图之类的

**Comment by fengyuclub** [comment]
闪一下，就是浏览器记住了的那个验证密码框,闪过后跳到HTTP ERROR 401
![2023-02-17_18-21-14](https://user-images.githubusercontent.com/18002173/219617831-3cb303c1-c8b4-4b04-9ca3-e65546b4930f.png)
***
![2023-02-17_18-19-43](https://user-images.githubusercontent.com/18002173/219617626-66be6cd5-aac6-4514-b259-e8a699dc7598.png)
***
![2023-02-17_18-22-46](https://user-images.githubusercontent.com/18002173/219618263-e62b238e-efe4-4666-8d60-79bd47af9b4f.png)

**Comment by jeessy2** [comment]
账号密码输对没有，没对的话会返回401

**Comment by fengyuclub** [comment]
应该是我的问题，密码是正确的，使用chrome无痕可以正常，手机流量也正常，唯一不同的是访问端的chrome和npm在同一个子网，这样绕一圈是否会有问题。

**Comment by yin1999** [comment]
有没有正确配置NAT回流，如果你在同一个子网内使用域名访问服务，在没有正确设置NAT回流的情况下，浏览器收到的数据包直接来自子网，请求发送到的IP与响应发回的IP会不一致

**Comment by fengyuclub** [comment]
> 

回流是正确的，我也在单出口家用网络环境下（N1）部署，都测试了，不一定是我的问题，只要记住密码就会闪退401错误，也请开发者或其他朋友测试一下。

**Comment by jeessy2** [comment]
记住的密码是不是有多个，自动填充了其他服务的帐号密码。

**Comment by fengyuclub** [comment]
这点第一次pr已经确认了，不会犯这样的错误。

**Comment by jeessy2** [comment]
那你研究一下，有消息反馈
