### ISSUE TITLE
[Bug]：arm64 pull失败

### ISSUE THREAD

**Issue by lilarcor** [jeessy2/ddns-go#563]
### 问题描述

在arm64上pull 失败 ，提示`error response getting manifests: 404`
尝试x86上使用pull arm64版本，
`docker pull jeessy/ddns-go:arm64
Error response from daemon: manifest for jeessy/ddns-go:arm64 not found: manifest unknown: manifest unknown
`

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### ddns-go 版本

latest

### 安装方式

Docker

### 额外信息

不知道是不是包里少了什么类似标签的东西

**Comment by jeessy2** [comment]
没有`arm64`标签。参考hub.docker.com

**Comment by lilarcor** [comment]
好的。pull最新版导入到arm设备后，提示execve: Exec format error。
` docker pull jeessy/ddns-go:latest@sha256:a3301071edf1e952109b55e3956d2ce3aecb23ea7a6d7a465d8904e0037b6f43`

**Comment by jeessy2** [comment]
直接在arm设备上pull 镜像

**Comment by lilarcor** [comment]
主要是我的设备的docker还是初级版，很多命令不能用，还是谢谢你，那么速度回复

**Comment by gzxief** [comment]
你安装docker-ce时，忘记把arm改为arm64了，你现在卸载docker-ce改为docker.io就没问题了
