### ISSUE TITLE
[Bug]：钉钉通知显示发送成功，日志显示SSL Handshake timeout

### ISSUE THREAD

**Issue by silence9527** [jeessy2/ddns-go#567]
### 问题描述

![mmexport1677162025092](https://user-images.githubusercontent.com/79163325/220934042-9078c24e-4a61-4c7e-b783-650a69c4eeee.png)
![mmexport1677162027778](https://user-images.githubusercontent.com/79163325/220934063-411ccf25-4944-4c8e-8384-f9befc87f87f.png)

这是日志

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

v4.5.3

### 安装方式

Docker

**Comment by jeessy2** [comment]
检查网络，超时了
