### ISSUE TITLE
[Bug]：使用根域名失败，报错400

### ISSUE THREAD

**Issue by guugg** [jeessy2/ddns-go#569]
### 问题描述

使用的是cloudflare
试过：
*.abc.xyz（在cf上直接是*了）
@.abc.xyz（报错）
@abc.xyz（报错）
abc.xyz（在cf上的主机名是abc.xyz；等于是abc.xyz.abc.xyz了）

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### ddns-go 版本

v4.5.3

### 安装方式

Docker

### 额外信息

2023/02/24 20:49:48 配置文件已保存在: /root/.ddns_go_config.yaml
2023/02/24 20:49:49 请求接口 https://api.cloudflare.com/client/v4/zones/3d9c65bb3205dc347559fe94ab4b5d46/dns_records 失败! 返回内容: {"result":null,"success":false,"errors":[{"code":1004,"message":"DNS Validation Error","error_chain":[{"code":9000,"message":"DNS name is invalid."}]}],"messages":[]} ,返回状态码: 400
2023/02/24 20:49:49 新增域名解析 @.abc.xyz 失败！Messages: []

**Comment by guugg** [comment]
`*.abc.xyz（在cf上直接是*了）`

**Comment by jeessy2** [comment]
你怎么输入的

**Comment by guugg** [comment]
> 输入的什么域名，截图看下

[![pSzj4oD.md.png](https://s1.ax1x.com/2023/02/24/pSzj4oD.md.png)](https://imgse.com/i/pSzj4oD)

**Comment by jeessy2** [comment]
前面不加@。直接 abc.xyz
