### ISSUE TITLE
[Bug]：cloudflare出问题了

### ISSUE THREAD

**Issue by zzfree2021** [jeessy2/ddns-go#570]
### 问题描述

2023/02/24 22:57:48 请求接口https://api.cloudflare.com/client/v4/zones?name=xxxx.com&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=xxxx.com&status=active&per_page=50": net/http: TLS handshake timeout

cloudflare的域名无法使用了

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

v4.5.4

### 安装方式

Docker

**Comment by jeessy2** [comment]
TLS handshake timeout
超时了。正常情况
