### ISSUE TITLE
[Bug]： Geting current user failed!

### ISSUE THREAD

**Issue by ItzMiracleOwO** [jeessy2/ddns-go#575]
### 问题描述

服务报错  Geting current user failed! 并且配置文件无法加载

![image](https://user-images.githubusercontent.com/76854136/221362590-0d2daf13-bf1c-4f58-9cd1-1061cd016b86.png)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

4.5.4

### 安装方式

服务

**Comment by ItzMiracleOwO** [comment]
更新：不使用服务可以正常加载

**Comment by jeessy2** [comment]
不管这个报错。运行为服务，找不到HOME目录，所以有这个提示。不影响你使用

**Comment by ItzMiracleOwO** [comment]
配置文件加载不上去了 系统是fedora

**Comment by WaterLemons2k** [comment]
看起来像是服务指定了错误的配置文件（`./.ddns_go_config.yaml`）导致 `Geting current user failed!`，把 ddns-go 服务配置文件（`/etc/systemd/system/ddns-go.service`）`ExecStart` 行的 `-c` 选项去掉看看。

**Comment by jeessy2** [comment]
重新安装服务，重新看下-c目录，或者安装的时候指定-c路径

**Comment by ItzMiracleOwO** [comment]
![image](https://user-images.githubusercontent.com/76854136/221387108-3cba039a-be7a-47a2-b0eb-60883792ce44.png)

**Comment by ItzMiracleOwO** [comment]
使用绝对路径依然报错
![image](https://user-images.githubusercontent.com/76854136/221387145-2edac24f-539b-4a7d-98fa-be5a598d0f7a.png)

**Comment by ItzMiracleOwO** [comment]
> 看起来像是服务指定了错误的配置文件（`./.ddns_go_config.yaml`）导致 `Geting current user failed!`，把 ddns-go 服务配置文件（`/etc/systemd/system/ddns-go.service`）`ExecStart` 行的 `-c` 选项去掉看看。

配置文件的路径看起来并没有问题

**Comment by ItzMiracleOwO** [comment]
> 重新安装服务，重新看下-c目录，或者安装的时候指定-c路径

安装的时候有指定正确 -c 路径:
![image](https://user-images.githubusercontent.com/76854136/221387236-00ddf84b-0e9d-470d-a85f-22ee911fb8fa.png)

**Comment by ItzMiracleOwO** [comment]
> /etc/systemd/system/ddns-go.service

![image](https://user-images.githubusercontent.com/76854136/221387301-f9d4528b-4677-4334-bea5-7a640eaa8904.png)
移除 -c 选项后，故障依旧

**Comment by jeessy2** [comment]
-c 需要指定全路径，都没提示你配置了，说明加载了。报错`Geting current user failed! `是正常的，服务环境找不到用户HOME目录，不是以用户运行的

**Comment by jeessy2** [comment]
https://github.com/jeessy2/ddns-go/blob/master/main.go#L33
服务运行默认初始此段，实际已指定目录了的。感兴趣可看下

**Comment by WaterLemons2k** [comment]
另外，由于 ddns-go 安装为 system service，system service 没有 `$HOME` 变量，所以报错 `Geting current user failed!`，但是 user service 有 `$HOME` 变量。

参考：
- [linux - How to use the `$HOME` environment variable in systemd service files - Server Fault](https://serverfault.com/questions/794922/how-to-use-the-home-environment-variable-in-systemd-service-files)
- [systemd/User - ArchWiki](https://wiki.archlinux.org/title/systemd/User)

**Comment by jeessy2** [comment]
4.5.6不显示了。不过指定的相对路径是不行的，要绝对路径。
