### ISSUE TITLE
端口能获取IPV6，但是网卡却获取不到

### ISSUE THREAD

**Issue by jhbrokey** [jeessy2/ddns-go#58]
我的是Ipv6的公网，没有IPV4公网IP。
使用这个Docker的时候发现，能通过网页获取IPv6地址，但是无法通过网卡获取
没有找到可用的网卡

**Comment by jhbrokey** [comment]
我的IPv4能找到网卡，IPv6就不能找到网卡，没有找到可用的网卡。我的设备是DS918，黑裙，6.24

**Comment by jeessy2** [comment]
群晖里看下ipv6什么开头的

**Comment by mjyhj** [comment]
> 我的是Ipv6的公网，没有IPV4公网IP。
> 使用这个Docker的时候发现，能通过网页获取IPv6地址，但是无法通过网卡获取
> 没有找到可用的网卡

docker用host网络
