### ISSUE TITLE
[Bug]：

### ISSUE THREAD

**Issue by Peooop** [jeessy2/ddns-go#587]
### 问题描述

解析到cloudflare.com失败

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### ddns-go 版本

v4.5.7

### 安装方式

其它

### 额外信息

https://api.cloudflare.com/client/v4/zones?name=#####&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=sooop.tk&status=active&per_page=50": dial tcp: lookup api.cloudflare.com on [::1]:53: read udp [::1]:53751->[::1]:53: read: connection refused

**Comment by WaterLemons2k** [comment]
api.cloudflare.com 被解析到 ::1 了，请尝试更换 DNS。

**Comment by Pandaver** [comment]
armv7安卓10同样报错解析到[::1]，手机浏览器可以正常访问可以正常解析网页
尝试过：
1. 打开Android设置里的“私人DNS”到dns.alidns.com
2. 使用Clash代理
3. 上级路由器IPv6指定阿里DNS 2400:3200::1
错误依然存在
@WaterLemons2k @jeessy2

**Comment by jeessy2** [comment]
因为 Android 不是标准的 Linux 系统，没有 `/etc/resolv.conf` 文件。而 Go 标准库 net 是通过解析 `/etc/resolv.conf` 文件获取 DNS 服务器地址的。由于无法获取，会使用默认值 127.0.0.1:53，而本地又没有开启 DNS 服务所以就报错了。请自行创建 `/etc/resolv.conf` 文件（需要 root），文件内容：

```
nameserver 114.114.114.114
```
或参考 https://github.com/jeessy2/ddns-go/pull/590 自行编译。
