### ISSUE TITLE
ARM平台DNS解析异常

### ISSUE THREAD

**Issue by Pandaver** [jeessy2/ddns-go#589]
armv7安卓10同样报错解析到[::1]，手机浏览器可以正常解析报错网页
尝试过：
1. 打开Android设置里的“私人DNS”功能到dns.alidns.com
2. 使用Clash代理
3. 上级路由器IPv6指定阿里DNS 2400:3200::1 和 2400:3200:baba::1

错误依然存在
@WaterLemons2k @jeessy2

_Originally posted by @Pandaver in https://github.com/jeessy2/ddns-go/issues/587#issuecomment-1454792071_

**Comment by WaterLemons2k** [comment]
https://github.com/jeessy2/ddns-go/issues/587#issuecomment-1454504505 是错误的，真正原因是 Go 使用默认 DNS（127.0.0.1 或 ::1）导致无法解析。

**Comment by jeessy2** [comment]
因为 Android 不是标准的 Linux 系统，没有 `/etc/resolv.conf` 文件。而 Go 标准库 net 是通过解析 `/etc/resolv.conf` 文件获取 DNS 服务器地址的。由于无法获取，会使用默认值 127.0.0.1:53，而本地又没有开启 DNS 服务所以就报错了。请自行创建 `/etc/resolv.conf` 文件（需要 root），文件内容：

```
nameserver 114.114.114.114
```
或参考 https://github.com/jeessy2/ddns-go/pull/590 自行编译。
