### ISSUE TITLE
[Bug]：主路由器ip：202.212.3.1，访问 202.212.3.2:9876 被拒绝。

### ISSUE THREAD

**Issue by RamenRa** [jeessy2/ddns-go#591]
### 在群晖docker安装的，在填写ID、key、域名等必要信息，点击“保存”后就再也无法访问管理员页面（查看日志DDNS正常工作）
**浏览器提示**
--------------------------------------
访问 202.212.3.2被拒绝你没有查看此页面的用户权限。
HTTP ERROR 403
--------------------------------------
1.重建容器，手动映射新的/root目录，网络host，问题依旧存在。
2.重建容器，映射其他端口，网络桥接模式，问题依旧存在。
3.运行“docker image inspect jeessy/ddns-go:latest | grep -i version”，无法获取版本号。

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

v0.0.1

### 安装方式

Docker

**Comment by jeessy2** [comment]
使用内网IP访问，默认勾选了禁止公网访问

**Comment by WensongPan** [comment]
202.212.3.2就是我的内网ip，路由器DHCP就是分配的202.212.3.xxx。

**Comment by WaterLemons2k** [comment]
只有遵守 [RFC 1918](https://www.rfc-editor.org/rfc/rfc1918) 的网络被允许，范围段为：

```
10.0.0.0    - 10.255.255.255
172.16.0.0  - 172.31.255.255
192.168.0.0 - 192.168.255.255
```
