### ISSUE TITLE
[Bug]：Windows下命令获取ip不能执行python脚本

### ISSUE THREAD

**Issue by micturkey** [jeessy2/ddns-go#592]
### 问题描述

通过命令获取IP，自己写了一个去tplink后台拿wan ip的脚本，结果执行都执行不出来
日志：

> 获取IPv4结果失败! 未能成功执行命令：C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command python c:/xx.py，错误："exit status 1" 

尝试使用powershell脚本
`python "c:/Users/xxx/Downloads/ddns-go/getwan.py" | echo `
在自己的powershell终端可以正常执行，但是依旧无法在ddns-go执行，提示

>  获取IPv4结果失败! 命令：C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command C:\getwan.ps1，标准输出："" 

用pyinstaller转exe后问题就可以解决了

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### ddns-go 版本

4.5.7

### 安装方式

服务

**Comment by jeessy2** [comment]
简单模拟了使用python print函数输出IP，获取得了IP。没你的环境不要分析，不过能用pyinstaller转exe可以用就行。

**Comment by micturkey** [comment]
> 简单模拟了使用python print函数输出IP，获取得了IP。没你的环境不好分析，不过能用pyinstaller转exe可以用就行。

我看到了最新的merge请求，等合并后我更新一下版本再看看错误具体是什么
现在就先exe凑合用了😂

**Comment by jeessy2** [comment]
合了。着急的话自己打包一个运行看下什么错误

**Comment by micturkey** [comment]
> 合了。着急的话自己打包一个运行看下什么错误

我重新打包以后找到问题了，ps提示找不到python，估计是我用windows store商店安装的python导致的问题
但是我还是有点疑惑，为啥我直接在powershell里就能运行呢？
是不是因为ddns-go注册为服务后是由SYSTEM用户运行的缘故，而python安装在了当前用户目录里，没有权限访问（我用了完整路径的python也不行）
懒得搞了，直接用exe凑合用了

**Comment by WaterLemons2k** [comment]
可能是 PATH 里没有 Python 吧，用完整 Python 路径呢？

**Comment by micturkey** [comment]
> 可能是 PATH 里没有 Python 吧，用完整 Python 路径呢？

完整路径也不行，错误代码如下

> CategoryInfo : ResourceUnavailable: (:) [], ApplicationFailedException\r\n + FullyQualifiedErrorId : NativeCommandFailed\r\n \r\n

我估摸着可能是权限问题，毕竟python装在了`%USERPROFILE%\AppData\Local\Microsoft\WindowsApps`下面

**Comment by WaterLemons2k** [comment]
用 cmd 运行呢？

```
cmd /c python
```

**Comment by micturkey** [comment]
> 用 cmd 运行呢？
> 
> ```
> cmd /c python
> ```
一样的
完整路径也不行🤣

**Comment by WaterLemons2k** [comment]
经测试，使用 Microsoft Store 安装的 Python 无法在 SYSTEM 账户下运行。请从 https://www.python.org/downloads/ 下载并安装 Python。（安装时可以勾选 `Add python.exe to PATH`）

然后，由于 Microsoft Store 的 Python 优先级极高，运行 `python` 命令可能会跳转到 Microsoft Store 的 Python 下载页面，请使用 Powershell 运行下列命令来删除 Microsoft Store 的 python.exe 占位符：
```PowerShell
Remove-Item $env:USERPROFILE\AppData\Local\Microsoft\WindowsApps\python*.exe
```

最后，将 Python 添加到系统变量 `PATH`。重启 ddns-go，您现在应该可以正常使用 Python！

参考：[Typing “python” on Windows 10 (version 1903) command prompt opens Microsoft store - Super User](https://superuser.com/questions/1437590/typing-python-on-windows-10-version-1903-command-prompt-opens-microsoft-stor)

**Comment by micturkey** [comment]
> 经测试，使用 Microsoft Store 安装的 Python 无法在 SYSTEM 账户下运行。请从 https://www.python.org/downloads/ 下载并安装 Python。（安装时可以勾选 `Add python.exe to PATH`）
> 
> 然后，由于 Microsoft Store 的 Python 优先级极高，运行 `python` 命令可能会跳转到 Microsoft Store 的 Python 下载页面，请使用 Powershell 运行下列命令来删除 Microsoft Store 的 python.exe 占位符：
> 
> ```powershell
> Remove-Item $env:USERPROFILE\AppData\Local\Microsoft\WindowsApps\python*.exe
> ```
> 
> 最后，将 Python 添加到系统变量 `PATH`。重启 ddns-go，您现在应该可以正常使用 Python！
> 
> 参考：[Typing “python” on Windows 10 (version 1903) command prompt opens Microsoft store - Super User](https://superuser.com/questions/1437590/typing-python-on-windows-10-version-1903-command-prompt-opens-microsoft-stor)

谢谢回复！因为是偶尔用python，所以当时才没去官网下载，我自己就现用exe顶着了😂
