### ISSUE TITLE
[功能]：ddns 自动更新

### ISSUE THREAD

**Issue by lishuda** [jeessy2/ddns-go#595]
### 功能描述

系统中使用 ddns-go release版本，没有更新命令，只能./ddns-go -s uninstall卸载以后再运行./ddns-go -s install重新安装。
希望提供update命令提供更新功能

**Comment by jeessy2** [comment]
欢迎PR

**Comment by WuYanQiming** [comment]
电报的Webhook 失效啦？

**Comment by WaterLemons2k** [comment]
> 电报的Webhook 失效啦？

是 [ddns-telegram-bot](https://github.com/WingLim/ddns-telegram-bot) 吗？

**Comment by chenye168** [comment]
同求，希望增加一开机就更新ip的功能

**Comment by jeessy2** [comment]
> 同求，希望增加一开机就更新ip的功能

安装服务不就对了。这个issues是更新程序😓

**Comment by qzj603** [comment]
直接把DDNS-GO程序做成window服务，每次更新停止这个服务，替换DDNS-GO程序，然后重启服务即可为最新版本。

**Comment by qzj603** [comment]
直接把DDNS-GO程序做成window服务，每次更新停止这个服务，替换DDNS-GO程序，然后重启服务即可为最新版本。
