### ISSUE TITLE
[Bug]：docker arm版本无法通过命令方式获取ip地址

### ISSUE THREAD

**Issue by lishuda** [jeessy2/ddns-go#596]
### 问题描述

获取IPv6结果失败! 未能成功执行命令，错误："exec: \"bash\": executable file not found in $PATH"
在网上搜索，发现是容器并没有用bash shell，而是使用的sh。
[csdn](https://blog.csdn.net/cyan20115/article/details/106541009)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

macOS (Darwin)

### 架构

arm64

### ddns-go 版本

v4.5.7

### 安装方式

Docker

**Comment by WaterLemons2k** [comment]
#586 引入忘加到 Docker 里了，#597 修复。
