### ISSUE TITLE
希望增加 dns.he.net的支持

### ISSUE THREAD

**Issue by flynaj** [jeessy2/ddns-go#6]

**Comment by jeessy2** [comment]
欢迎提一个PR

**Comment by jeessy2** [comment]
dns.he.net只能修改，不能通过api新增。每个域名都需要设置一个key。和现在设计不匹配，建议你转到aliyun, dnspod, cloudflare

**Comment by flynaj** [comment]
我自己写个脚本解决了， 谢谢了！ https://www.v2ex.com/t/710134
