### ISSUE TITLE
获取 IP地址 失败后 叮叮没有重新发送 IP

### ISSUE THREAD

**Issue by XRSec** [jeessy2/ddns-go#60]
![image](https://user-images.githubusercontent.com/73819467/115124400-9f658800-9ff4-11eb-85a3-cb9e1f023de2.png)
![image](https://user-images.githubusercontent.com/73819467/115124421-befcb080-9ff4-11eb-94d2-efbb58a519ee.png)

**Comment by zygds** [comment]
用的是server2019 dns exe

**Comment by jeessy2** [comment]
这里故意没调webhook，因为网络问题随时可能出现，导致调用webhook过多，所以此处没处理。

**Comment by zygds** [comment]
可以设置10分钟后重新发送吗？刚好dns刷新缓存

**Comment by jeessy2** [comment]
推迟有什么用吗

**Comment by mangitleung** [comment]
为什么我总是”未能获得IPv4地址! 点击查看接口能否返回IPv4地址“，我点击查看地址也能看到

**Comment by jeessy2** [comment]
> 为什么我总是”未能获得IPv4地址! 点击查看接口能否返回IPv4地址“，我点击查看地址也能看到

换一个接口试试
