### ISSUE TITLE
[功能]：Webhook 中电报推送消息失效啦？

### ISSUE THREAD

**Issue by WuYanQiming** [jeessy2/ddns-go#601]
### 功能描述

Webhook 中电报推送消息失效啦？

**Comment by WaterLemons2k** [comment]
是 [ddns-telegram-bot](https://github.com/WingLim/ddns-telegram-bot) 吗？

**Comment by WuYanQiming** [comment]
> 

对，你可以用吗？一开始好好的，最新不推送了，测试也过不去

**Comment by WuYanQiming** [comment]
DDNSBot

**Comment by WaterLemons2k** [comment]
和 WingLim/ddns-telegram-bot#5 有关吗？

**Comment by WuYanQiming** [comment]
对？以前的不能用了？

**Comment by WuYanQiming** [comment]
好的，谢谢 我试试。
