### ISSUE TITLE
安装服务后启动，会卡在“第一次运行将等待 20 秒后运行 (等待网络)”

### ISSUE THREAD

**Issue by ArcturusYu** [jeessy2/ddns-go#602]
双击运行没有问题

**Comment by jeessy2** [comment]
分别截图看下，重要信息打个码

**Comment by ArcturusYu** [comment]
![image](https://user-images.githubusercontent.com/40350185/224461880-295e9b95-52a9-4c65-859c-fb309220ee0c.png)
用服务启动是这样的
![image](https://user-images.githubusercontent.com/40350185/224461974-0265f35a-2e85-4a8b-9239-a216a0c97e39.png)
手动启动是这样的

**Comment by jeessy2** [comment]
通过网页访问看加载配置没有？你截的图等于没截😓

**Comment by WaterLemons2k** [comment]
你在 `通过命令获取` 栏填入：

```
echo $env:DDNS_CONFIG_FILE_PATH
```

看一下服务和手动使用的是哪个配置文件。

**Comment by ArcturusYu** [comment]
> 通过网页访问看加载配置没有？你截的图等于没截😓

![image](https://user-images.githubusercontent.com/40350185/224465686-ecaedc7f-ae06-48ff-a5e6-74d9911d6c00.png)
应该加载了，ipv6地址也获取到了

**Comment by ArcturusYu** [comment]
> 

没有找到“通过命令获取”

**Comment by WaterLemons2k** [comment]
> 没有找到“通过命令获取”

![GetIPByCommand](https://user-images.githubusercontent.com/62788816/224465924-891dcef8-fef8-487d-b236-1f0c6651b9e6.png)

 这里，保存后看一下标准输出是什么。

**Comment by ArcturusYu** [comment]
> > 没有找到“通过命令获取”
> 
> ![GetIPByCommand](https://user-images.githubusercontent.com/62788816/224465924-891dcef8-fef8-487d-b236-1f0c6651b9e6.png)
> 
> 这里，保存后看一下标准输出是什么。（只用填 1 个）

![image](https://user-images.githubusercontent.com/40350185/224466637-164bf438-cadf-4c7d-9408-acd8ad8f2f8e.png)

**Comment by WaterLemons2k** [comment]
> 回车后只有保存成功的提示

在看一下手动运行什么情况。

**Comment by ArcturusYu** [comment]
> > 回车后只有保存成功的提示
> 
> 在看一下手动运行什么输出。

输出和之前的相同，只有ipv6的输出

**Comment by ArcturusYu** [comment]
> > > 回车后只有保存成功的提示
> > 
> > 
> > 在看一下手动运行什么输出。
> 
> 输出和之前的相同，只有ipv6的输出
打开http://127.0.0.1:9876/后发现设置没有保存

**Comment by ArcturusYu** [comment]
问题已经解决了，谢谢二位的指导
总结一下，是因为通过服务启动的配置文件保存在C:\Windows\System32\config\systemprofile\.ddns_go_config
而直接运行保存的配置文件在C:\Users\用户名\.ddns_go_config
用第二份文件把第一份文件覆盖后就好了

**Comment by jeessy2** [comment]
可能和 #579有关，你试下4.5.6版本，重新安装服务，保存一下，看是保存在那个位置

**Comment by WaterLemons2k** [comment]
自 #579 起，安装服务不再添加 `-c` 选项，默认使用家目录的配置文件。而普通账户和 SYSTEM 账户的家目录不同导致此 issue 出现。

被 #604 修复。

**Comment by ArcturusYu** [comment]
> 而直接运行保存的配置文件在C:\Users\用户名\.ddns_go_config



> 可能和 #579 有关，你试下4.5.6版本，重新安装服务，保存一下，看是保存在那个位置

保存的是这个路径

**Comment by WaterLemons2k** [comment]
> 保存的是这个路径“C:\Users\用户名.ddns_go_config”

[v4.5.9](https://github.com/jeessy2/ddns-go/releases/tag/v4.5.9) 以及以后版本应该都是这个路径了。
