### ISSUE TITLE
树莓派zerow运行/编译问题

### ISSUE THREAD

**Issue by michaelauto** [jeessy2/ddns-go#603]
系统信息
```
cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
Serial          : 0000000009d9e05d
Model           : Raspberry Pi Zero W Rev 1.1
```
--------------------------------------------------------------
首先下载了armv6版本执行提示
`Segmentation fault`
接着下载v7提示
`Illegal instruction`
尝试自行编译
执行make build时提示
`/bin/sh: 1: build: not found
make: *** [Makefile:16: build] Error 127`

**Comment by WaterLemons2k** [comment]
ARMv6 是这个吗：https://github.com/jeessy2/ddns-go/releases/download/v4.5.8/ddns-go_4.5.8_linux_armv6.tar.gz

**Comment by michaelauto** [comment]
> ARMv6 是这个吗：https://github.com/jeessy2/ddns-go/releases/download/v4.5.8/ddns-go_4.5.8_linux_armv6.tar.gz

我可能错用了freebsd那个，回去再试试
