### ISSUE TITLE
群辉docker里面一直显示，未能获得IPv6地址! 

### ISSUE THREAD

**Issue by duwei1483** [jeessy2/ddns-go#61]
2021/04/20 03:30:51 未能获得IPv6地址! 点击查看接口能否返回IPv6地址, 官方说明:点击访问

下面是日志显示内容。

2021/04/20 03: 15: 16 IPv6 <a target='blank' href=https: //api-未能获得IPv6地址!<atarget=blankhref=https:api-bipv6.ip.sb/ip>点击查看接口能否返回IPv6地址<a>,官方说明< target=blank' href=https: //github. com/jeessy2/ddns-go#ipv6'>/a>使用ipv6>点击访问<a>

黑白群辉都一样。

我的IPV6直接在阿里云上手动绑定域名是没有问题的，也能访问。

**Comment by jeessy2** [comment]
核对步骤：

映像 -> 选择jeessy/ddns-go -> 启动 -> 高级设置 -> 网络中勾选使用与 Docker Host 相同的网络，高级设置中勾选启动自动重新启动

**Comment by duwei1483** [comment]
> 核对步骤：
> 
> 映像 -> 选择jeessy/ddns-go -> 启动 -> 高级设置 -> 网络中勾选使用与 Docker Host 相同的网络，高级设置中勾选启动自动重新启动

我已经按大神你的，设置弄好了，现在可以获取IPV6地址了，剩下就等变化的时候看下，能不能修地址成功了。先谢谢了！
