### ISSUE TITLE
[功能]：增加NameCheap的解析功能

### ISSUE THREAD

**Issue by wxh2** [jeessy2/ddns-go#612]
### 功能描述

这功能好馋啊，我翻了一下以前的issues，大佬2022的坑现在没填，所以求加入NameCheap

**Comment by jeessy2** [comment]
fix: #454

**Comment by jeessy2** [comment]
没帐号，到时自行测试下

**Comment by jeessy2** [comment]
5.0.0已支持 https://github.com/jeessy2/ddns-go/releases/tag/v5.0.0
