### ISSUE TITLE
[Bug]：貌似xxx.xxx.xx类型的域名不能正常解析

### ISSUE THREAD

**Issue by Rainsiy** [jeessy2/ddns-go#618]
### 问题描述

例如：域名 cloud.hk.cn ，实际注册下来的域名就是cloud.hk.cn，添加@解析时域名为cloud.hk.cn，www时为www.cloud.hk.cn。

设置IPV4地址时
Domains为：cloud.hk.cn 实际主机记录为@ 
<img width="536" alt="image" src="https://user-images.githubusercontent.com/100349556/224532508-0d3f2d5c-a863-4366-9311-c901bd2b22b2.png">

报错如下：
新增域名解析 cloud.hk.cn 失败！Code: 8, Message: 域名不正确，请输入主域名，如 dnspod.cn

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### ddns-go 版本

v4.5.9

### 安装方式

服务

**Comment by jeessy2** [comment]
www:cloud.hk.cn
用冒号分割，下面有说明
