### ISSUE TITLE
请问大神最近cloudflare出什么问题了还是我设置不对了

### ISSUE THREAD

**Issue by fhne** [jeessy2/ddns-go#62]
各种服务都试了，确定脚本没问题，不知道是我自己的设置还是cloudflare出了问题

获取状态之类的都没问题，只有设置dns失败
2021/05/05 05:36:12 请求接口https://api.cloudflare.com/client/v4/zones?name=myURL&status=active&per_page=50失败! {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null}

**Comment by jeessy2** [comment]
应该是你token设置不对。把你token设置步骤发来看下

**Comment by fhne** [comment]
-------------------------------------------------------------
编辑区域 DNS API 令牌摘要
此 API 令牌将影响以下帐户和区域，以及它们各自的权限

myMailAddress 's Account
myURL- DNS:编辑
-------------------------------------------------------------

上面是【编辑区域 DNS】的设置，只在区域资源选择了自己的域名，其他的都是默认(默认权限是DNS编辑)
用Global API Key可以吗，根据cloudflare的帮助文档，我自己写了用Global API Key的shell工具，也是同样的设置失败

用网上下载的【FlareDDNS-v2.0.0.1】exe执行文件时，设置Global API Key可以查看域名以及解析记录，但是同样不能设置动态解析，返回403错误

**Comment by jeessy2** [comment]
创建API令牌。不用global api![image](https://user-images.githubusercontent.com/6205259/117099863-dd103200-ada4-11eb-95db-7cf73de3841f.png)

**Comment by fhne** [comment]
按照图片提示，把资源设置为所有区域后，出现以下报错
情况依旧，两个id都获取成功了，只在最后的解析出现失败，是我没给什么权限吗

-----------------------------------------------------------------------------------
2021/05/05 22:49:33 请求接口https://api.cloudflare.com/client/v4/zones/xxxxxxxxxxxxxxxxxxxx/dns_records/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx失败! { "result": null, "success": false, "errors": [ { "code": 1038, "message": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard." } ], "messages": [] }
2021/05/05 22:49:33 更新域名解析 myURL失败！Messages: []
-----------------------------------------------------------------------------------

**Comment by jeessy2** [comment]
他说不支持通过api更新你的顶级域名（ .cf, .ga, .gq, .ml, or .tk ）。要在网页上操作。要不你就不用cloudflare，转到其他的服务商

**Comment by fhne** [comment]
原来是真的单纯不支持啊， 不是权限设置问题，是只不支持（ .cf, .ga, .gq, .ml, .tk ）这几个吗
那大家都用什么服务商的域名呢？
都是花钱买的其他服务商域名还是有什么其他免费的域名可用

**Comment by jeessy2** [comment]
一般都是花钱买的，免费的没用过。
花钱一般一年几十元，阿里云、腾讯云选一个都支持的api请求的
