### ISSUE TITLE
[功能]：配置多个DNS服务商

### ISSUE THREAD

**Issue by aarbbs** [jeessy2/ddns-go#621]
### 功能描述

希望能同时配置多个DNS服务商，比如：腾讯+阿里，域名解析也得对应

**Comment by jeessy2** [comment]
正在发布，你就提了😓

**Comment by aarbbs** [comment]
> 正在发布，你就提了😓

哈哈哈哈，刚刚看到了重复问题：#439，准备回复帮忙关闭当前这个。

**Comment by jeessy2** [comment]
5.0.0已支持 https://github.com/jeessy2/ddns-go/releases/tag/v5.0.0
