### ISSUE TITLE
[功能]：请问支持双IP解析吗

### ISSUE THREAD

**Issue by Beginner-tl** [jeessy2/ddns-go#623]
### 功能描述

双ip目前用ddnsgo是2个IP来回识别切换解析，但是域名都访问不了

**Comment by jeessy2** [comment]
能描述详细一点否？
[传递自定义参数](https://github.com/jeessy2/ddns-go/wiki/%E4%BC%A0%E9%80%92%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%82%E6%95%B0) 不知道能满足否，通过RecordId修改

**Comment by Beginner-tl** [comment]
目前我是2个IP，获取到的ip会在2个ip来回切换，导致每分钟同步一下ip，实际2个IP都是，域名就无法访问，有没有就是使他们获取的ip保持一致

**Comment by WaterLemons2k** [comment]
> 目前我是2个IP，获取到的ip会在2个ip来回切换，导致每分钟同步一下ip，实际2个IP都是，域名就无法访问，有没有就是使他们获取的ip保持一致

2 个 IP 的格式有区别吗？

**Comment by jeessy2** [comment]
估计是二条宽带，搞了宽带负载均衡，每次请求接口就来回跳。看路由器支持策略路由不，指定内网ddns-go那台走指定一条宽带出去
其他方式要根据设备情况来选择

**Comment by wangyangaa** [comment]
哈哈哈，我之前还故意这样搞，因为家里也有几条外网线路，天真的以为这样可以实现域名解析的负载均衡，相当于每次访问同一个域名，可以依次使用不同线路。

结果测试了很久发现不行

**Comment by jeessy2** [comment]
> 哈哈哈，我之前还故意这样搞，因为家里也有几条外网线路，天真的以为这样可以实现域名解析的负载均衡，相当于每次访问同一个域名，可以依次使用不同线路。
> 
> 结果测试了很久发现不行

理论上是可以的，自己写一个获取不同宽带的接口，搭配[传递自定义参数](https://github.com/jeessy2/ddns-go/wiki/%E4%BC%A0%E9%80%92%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%82%E6%95%B0)，这个需要自行探索
