### ISSUE TITLE
[Bug]：5.0.1版本下指定网卡失效

### ISSUE THREAD

**Issue by Xielipton** [jeessy2/ddns-go#627]
### 问题描述

当前服务器ens30是pppoe，通过拨号后，ddnsgo中显示为ppp0；另一张网卡是ens31，内网192.168.*.*
更新新版本后，将监听网卡设置为ppp0后，刷新会自动跳回，在ddns记录中也可以发现ip跳成了内网ip

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

v5.0.1

### 安装方式

其它

**Comment by jeessy2** [comment]
刷新会自动跳回，这个能描述清楚点否

**Comment by jeessy2** [comment]
已修复 https://github.com/jeessy2/ddns-go/releases/tag/v5.0.2
