### ISSUE TITLE
[功能]：能不能添加设置不允许新增域名，因为有时候是给别人用的，不允许乱增域名

### ISSUE THREAD

**Issue by Wirili** [jeessy2/ddns-go#634]
### 功能描述

可以在安装服务的时候添加参数，域名原来有的就更新，没有的就不要新增

**Comment by jeessy2** [comment]
设置access key的权限比较好

**Comment by Wirili** [comment]
好的，谢谢

**Comment by Wirili** [comment]
是不是安装路径里面不能有空格

**Comment by jeessy2** [comment]
最好不带

**Comment by Wirili** [comment]
是不是32位的系统不支持，win2008 32位的 运行 i386 提示不是有效的win32程序

**Comment by Wirili** [comment]
功能建议，能否通过域名的备注指定信息来停用ddns-go配置，删除配置 ，删除dns配置 等等

**Comment by jeessy2** [comment]
> 功能建议，能否通过域名的备注指定信息来停用配置，启用配置，删除配置 ，删除dns配置 等等

过于复杂。暂不考录
