### ISSUE TITLE
[Bug]：IPV6接口获取地址失败

### ISSUE THREAD

**Issue by iceyheart** [jeessy2/ddns-go#636]
### 问题描述

部署在NAS上，系统为debian。确认NAS可访问IPV6
docker和直接安装都无法通过接口获取地址，报错信息如下：

2023/03/17 20:51:16 连接失败! [点击查看接口能否返回IPv6地址](https://speed.neu6.edu.cn/getIP.php), 参考说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2023/03/17 20:51:16 错误信息: Get "https://speed.neu6.edu.cn/getIP.php": dial tcp6: lookup speed.neu6.edu.cn on 8.8.8.8:53: no such host
2023/03/17 20:51:16 连接失败! [点击查看接口能否返回IPv6地址](https://v6.ident.me/), 参考说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2023/03/17 20:51:16 错误信息: Get "https://v6.ident.me": dial tcp6: lookup v6.ident.me on 8.8.8.8:53: no such host
2023/03/17 20:51:16 连接失败! [点击查看接口能否返回IPv6地址](https://6.ipw.cn/), 参考说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)
2023/03/17 20:51:16 错误信息: Get "https://6.ipw.cn": dial tcp6: lookup 6.ipw.cn on 8.8.8.8:53: no such host
2023/03/17 20:51:16 未能获取IPv6地址, 将不会更新

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

armv7

### ddns-go 版本

最新

### 安装方式

Docker

**Comment by WaterLemons2k** [comment]
可能是没有 IPv6 DNS 服务器，看一下 `/etc/resolv.conf`：
```sh
cat /etc/resolv.conf
```

**Comment by iceyheart** [comment]
路由器clash的问题，非程序问题，已解决。

**Comment by lyl980918** [comment]
请问我和你是同样的问题 也是软路由开的clash,clash里调整了什么？
