### ISSUE TITLE
[Bug]：使用Value参数报错400

### ISSUE THREAD

**Issue by HalcyonDaysssss** [jeessy2/ddns-go#637]
### 问题描述

xxxx.com?Value=192.168.0.10
报错如下:
2023/03/18 22:36:19 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"69053705-A9ED-5977-A1F7-E95710D20DC3","HostId":"alidns.aliyuncs.com","Code":"InvalidDomainName.Format","Message":"Invalid domain name.","Recommend":"https://next.api.aliyun.com/troubleshoot?q=InvalidDomainName.Format&product=Alidns"} ,返回状态码: 400

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### ddns-go 版本

v1.2.0

### 安装方式

其它

**Comment by WaterLemons2k** [comment]
不用另加 Value 参数吧：
https://github.com/jeessy2/ddns-go/blob/962dee0ba4907058b7e64e6565662d6c4aa939a6/dns/alidns.go#L116

**Comment by wananya** [comment]
刚刚大概看了看，好像仅支持A和AAAA

**Comment by jeessy2** [comment]
参考文档操作。不支持value参数

**Comment by HalcyonDaysssss** [comment]
> 参考文档操作。不支持value参数

请教下，我现在是ipv6内网穿透的，域名访问指定端口，现在只能是xxx.com:1234，我现在想把二级域名绑定指定端口要如何操作呢

**Comment by wananya** [comment]
> > 参考文档操作。不支持值参数
> 
> 请教下，我现在是ipv6内网穿透的，域名访问指定端口，现在只能是xxx.com:1234，我现在想把二级域名绑定指定端口如何操作

群晖的话直接反向代理就行了
