### ISSUE TITLE
关于配置填写

### ISSUE THREAD

**Issue by lalasou** [jeessy2/ddns-go#64]
抱歉有点笨

Domains:支持泛域名嘛

*.abc.com
@.abc.com
b.abc.com
a.b.abc.com
这几种都可以还是怎么样对
谢谢！

**Comment by jeessy2** [comment]
都支持的

**Comment by lalasou** [comment]
这个配置起来很简单
如果支持
dnspod 和阿里同时搞就更好了

**Comment by lalasou** [comment]
> 都支持的

话说 如果用ip  neigh 或者ip -6 neigh
根据mac获取局域网ip（docker host 可以用）
这样不就可以开一个更新局域网内所有设备ipv6 ddns了

我看他的用了这个方法
https://github.com/zwmscorm/sharealiddns

但是他这个应该在加一步pin 判断这个ip可不可以用
因为他显示 STALE FAILED REACHABLE 有时候不太准

**Comment by lalasou** [comment]
> > 都支持的
> 
> 话说 如果用ip  neigh 或者ip -6 neigh
> 根据mac获取局域网ip（docker host 可以用）
> 这样不就可以开一个更新局域网内所有设备ipv6 ddns了
> 
> 我看他的用了这个方法
> https://github.com/zwmscorm/sharealiddns
> 
> 但是他这个应该在加一步pin 判断这个ip可不可以用
> 因为他显示 STALE FAILED REACHABLE 有时候不太准
> 
> 

ping


ip neigh 会显示STALE FAILED REACHABLE但是STALE其实可以ping通

**Comment by jeessy2** [comment]
`ip neigh` 有些环境默认没有ip命令的

**Comment by lalasou** [comment]
> `ip neigh` 有些环境默认没有ip命令的


试了试，好像大部分都支持ip命令
win 没试 不知道....

如果能 支持   
不同 域名 分别ddns ip就更好了
比如 a.xxxx.com  ->   xx.xxx.xx.x
b.xxxx.com ->    xxx.xx.x

**Comment by jeessy2** [comment]
mac系统默认就没有ip命令

ip获取只有一个，以后也不会支持此种特殊需求，你可以fork一个，自行修改
