### ISSUE TITLE
[功能]：将 Docker 镜像推送至 `ghcr.io`

### ISSUE THREAD

**Issue by WaterLemons2k** [jeessy2/ddns-go#641]
### 功能描述

将 ddns-go 的 Docker 镜像推送至 Docker Hub 和 [GitHub Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/) (`ghcr.io`)。

### 解决的问题

仅仅依靠 Docker Hub 不够可靠。[^1]

[^1]:https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/

### 附加信息

- https://github.com/docker/metadata-action#images-input
- https://github.com/docker/login-action#github-container-registry

**Comment by jeessy2** [comment]
可以考虑。
