### ISSUE TITLE
你好大牛  可以说说开机自启是什么原理吗？

### ISSUE THREAD

**Issue by an429075824** [jeessy2/ddns-go#643]
### 功能描述

之前用过别的是在系统里加了任务。

咱们这个开机自启动 和5分钟运行一次   是什么原理 挺好奇的！

**Comment by Curious-r** [comment]
应该是注册成服务吧，在windows上是这样的

**Comment by jeessy2** [comment]
用的第三方库，注册系统服务，定时休眠
