### ISSUE TITLE
[功能]：请问在如何修改IP同步周期

### ISSUE THREAD

**Issue by birdxs** [jeessy2/ddns-go#644]
### 功能描述

默认5分钟有点频繁，想自定义，但是网页端和.ddns_go_config.yaml配置文件均未找到修改入口。

### 解决的问题

自定义IP同步周期

**Comment by WaterLemons2k** [comment]
可以在运行时添加 `-f` 选项修改同步间隔时间(秒)：
```
./ddns-go -f 600
```

**Comment by birdxs** [comment]
> 可以在运行时添加 `-f` 选项修改同步间隔时间(秒)：
> 
> ```
> ./ddns-go -f 600
> ```

这样是不是每次重启主机会自动按照上次设定的周期执行容器吗？希望能增加到配置页面里

**Comment by WaterLemons2k** [comment]
> 这样是不是每次重启主机会自动按照上次设定的周期执行容器吗？希望能增加到配置页面里

安装服务就可以了：
```bash
./ddns-go -s install -f 600
```
