### ISSUE TITLE
[功能]：能不能做成luci插件的形式方便openwrt安装

### ISSUE THREAD

**Issue by threerog** [jeessy2/ddns-go#649]
### 功能描述

如题
可以参考第三方开源的：https://github.com/sirpdboy/luci-app-ddns-go
<img width="796" alt="Snipaste_2023-03-28_03-35-34" src="https://user-images.githubusercontent.com/87128510/228047962-7cfee540-a56f-4c8e-af2c-000e9dd2a8d3.png">
他的目前可以用 但是很少更新 不能及时和官方库同步
所以希望官方库能支持这个是最好的

**Comment by VergilGao** [comment]
luci只是前端，你设置之类的还是去9876端口的网页端去做，那luci要来也没啥用的
