### ISSUE TITLE
可不可以同时登录两个DNS服务商

### ISSUE THREAD

**Issue by mxs365** [jeessy2/ddns-go#65]
可不可以同时登录两个DNS服务商？试了一下不行，改端口也改不了！可有好的方法？

**Comment by jeessy2** [comment]
一个程序只能一个服务商。支持多开程序就支持多个（通过绑定不同端口）。也可以把域名转到一个服务商下

**Comment by hotcoffie** [comment]
> 一个程序只能一个服务商。支持多开程序就支持多个（通过绑定不同端口，使用docker）。也可以把域名转到一个服务商下

还是希望一个服务就能配置多个服务商，docker的方式有点浪费资源，我的服务是跑在树莓派上的，多一个web服务都是沉重的负担啊

**Comment by jeessy2** [comment]
> 还是希望一个服务就能配置多个服务商，docker的方式有点浪费资源，我的服务是跑在树莓派上的，多一个web服务都是沉重的负担啊

页面上不好处理多个服务商(有点麻烦），如果你怕浪费资源的话，可以转到一个域名服务商也很方便的

**Comment by hotcoffie** [comment]
我fork了一份代码，大概看了下web页面只有一个form表单，要处理成多运营商确实有点麻烦
准备参考你的后端代码自己写个前端试试，有大半年没写go了，头昏脑胀

**Comment by jeessy2** [comment]
> 我fork了一份代码，大概看了下web页面只有一个form表单，要处理成多运营商确实有点麻烦
> 
> 准备参考你的后端代码自己写个前端试试，有大半年没写go了，头昏脑胀

欢迎PR

**Comment by wele0612** [comment]
其实用一个固定服务商，其他服务商cname过去会比较好

**Comment by jeessy2** [comment]
5.0.0已支持 https://github.com/jeessy2/ddns-go/releases/tag/v5.0.0
