### ISSUE TITLE
[功能]：希望能增加内网设备扫描以及其他设备动态域名解析

### ISSUE THREAD

**Issue by kylinholmes** [jeessy2/ddns-go#650]
### 功能描述

扫描内网中的设备，识别并记录设备，将其IPV6地址和域名关系发送到服务商。

### 解决的问题

内网中肯定不只一台设备，将ddns-go部署到路由器上，扫描得到所有连接的设备，每个设备的IPV6地址应该也可以获得到，于是可以将全屋的地址绑定到预设的域名上，比如：
```sh
MBP.v6.kylin.com
PC.v6.kylin.com
Srv.v6.kylin.com
```
通过这种方式，就可以做到真正的全屋设备都不需要内网穿透，便可以从公网访问到。
具体来说，设备的绑定关系，可以通过MAC地址，或者不采用DHCP，通过设置静态的IPV4地址解决

----
更进一步，可以直接将设备hostname作为二级域名，比如`kylin的xiaomi`，可以设置域名为：
```
kylin的xiaomi.kylin.cloud
```

**Comment by jeessy2** [comment]
参考[获取其它设备ipv6地址linux](https://github.com/jeessy2/ddns-go/wiki/%E9%80%9A%E8%BF%87%E5%91%BD%E4%BB%A4%E8%8E%B7%E5%8F%96IP%E5%8F%82%E8%80%83#%E8%8E%B7%E5%8F%96%E5%85%B6%E5%AE%83%E8%AE%BE%E5%A4%87ipv6%E5%9C%B0%E5%9D%80linux)

**Comment by jeessy2** [comment]
5.0.0后可以使用`新增一个配置`, 不同的配置设置不同的`通用命令获取`及 `对应的域名`

**Comment by jeessy2** [comment]
参考#664
