### ISSUE TITLE
[功能]：ddns_go_config.yaml 存储目录可以配置

### ISSUE THREAD

**Issue by bruceyan303** [jeessy2/ddns-go#659]
### 功能描述

增加一各启动配置 .ddns_go_config.yaml 存储目录可以配置

### 解决的问题

在小米路由器 配置是提示 open /root/.ddns_go_config.yaml: read-only file system

**Comment by WaterLemons2k** [comment]
`-c` 自定义配置文件路径：

```
./ddns-go -c /Users/name/ddns-go.yaml
```

**Comment by bruceyan303** [comment]
谢谢
