### ISSUE TITLE
希望能增加一个webhook测试按钮，方便配置后测试是否正常工作

### ISSUE THREAD

**Issue by hejialaifen** [jeessy2/ddns-go#66]

**Comment by jeessy2** [comment]
可以考虑，欢迎大家提PR。

**Comment by basncy** [comment]
+1, 跟这个[issue](https://github.com/jeessy2/ddns-go/issues/69)类似, 新增跳过ddns服务商的选项也行.

**Comment by jeessy2** [comment]
v2.9.0已增加
![截屏2021-06-14 下午10 15 47](https://user-images.githubusercontent.com/6205259/121907012-3bdea900-cd5e-11eb-8451-557ba7c40e36.png)
