### ISSUE TITLE
[功能]：能否增加一个IPv6功能，获取运营商分配的动态前缀，然后允许用户用固定的后缀与动态前缀组装成合法的全球地址

### ISSUE THREAD

**Issue by ocoj** [jeessy2/ddns-go#664]
### 功能描述

能否增加一个IPv6功能，获取运营商分配的动态前缀，然后允许用户用固定的后缀与动态前缀组装成合法的全球地址；
例如：电信为客户为配的动态前缀是240e:4b4:50:17ea
           而我网内的A设备固定的后缀是aa:bb:cc:dd
     然后软件自动将动态前缀与用户定义的固定后缀自动组合成240e:4b4:50:17ea:aa:bb:cc:dd这个合法的全球单播地址。然后与域名绑定。这样的话，我就无需要网内每一台主机都安装ddns-go,只需要一台主机安装DDNS-GO 就可能绑定多台设备的IPv6地址。

### 解决的问题

这一功能将会解决有些设备不能，也不允许安装第三方软件的情况下，也可以实现动态IPv6与域名的绑定。如产线上的工控设备，是无法安装第三方软件，但又要满足用户远程监控设备的功能。 以前只能要求电信给一个外网IPv4地址，用NAT映射端口的方法。现在免费的IPv4外网地址已经不再有了。购买固定的也不合算（一般是设备调试用，过了调试期就不用了)。

**Comment by jeessy2** [comment]
https://github.com/jeessy2/ddns-go/wiki/通过命令获取IP参考

获取其它设备IPv6地址（Linux）
需要支持EUI-64（IPv6后半部分包含ff:fe）
```
ip -6 route | awk '{print $1}' | awk '/2409:?/' | awk -F::/ '{print $1 "any suffix of other mac"}'
```

**Comment by ocoj** [comment]
> [https://github.com/jeessy2/ddns-go/wiki/ 通过命令获取IP参考](https://github.com/jeessy2/ddns-go/wiki/%E9%80%9A%E8%BF%87%E5%91%BD%E4%BB%A4%E8%8E%B7%E5%8F%96IP%E5%8F%82%E8%80%83)
> 
> 获取其它设备IPv6地址（Linux） 需要支持EUI-64（IPv6后半部分包含ff：fe）
> 
> ```
> ip -6 route | awk '{print $1}' | awk '/2409:?/' | awk -F::/ '{print $1 "any suffix of other mac"}'
> ```
多谢

**Comment by ocoj** [comment]
> [https://github.com/jeessy2/ddns-go/wiki/通过命令获取IP参考](https://github.com/jeessy2/ddns-go/wiki/%E9%80%9A%E8%BF%87%E5%91%BD%E4%BB%A4%E8%8E%B7%E5%8F%96IP%E5%8F%82%E8%80%83)
> 
> 获取其它设备IPv6地址（Linux） 需要支持EUI-64（IPv6后半部分包含ff:fe）
> 
> ```
> ip -6 route | awk '{print $1}' | awk '/2409:?/' | awk -F::/ '{print $1 "any suffix of other mac"}'
> ```
现在软件上这个功能是单选的，无法为多台设备服务

**Comment by WaterLemons2k** [comment]
> 现在软件上这个功能是单选的，无法为多台设备服务

`配置切换:` -> `添加`

**Comment by ocoj** [comment]
> > 现在软件上这个功能是单选的，无法为多台设备服务
> 
> `配置切换:` -> `添加`
多谢，linux 成功设好，请教一下，有支Windows 版的命令吗？

**Comment by WaterLemons2k** [comment]
> 多谢，linux 成功设好，请教一下，有支Windows 版的命令吗？

```powershell
Get-NetRoute -AddressFamily IPv6 | Where-Object { $_.DestinationPrefix.StartsWith("2409:") } | ForEach-Object { ($_.DestinationPrefix -split '::/')[0] + "any suffix of other mac" }
```

**Comment by ocoj** [comment]
> > 多谢，linux 成功设好，请教一下，有支Windows 版的命令吗？
> 
> ```powershell
> Get-NetRoute -AddressFamily IPv6 | Where-Object { $_.DestinationPrefix.StartsWith("2409:") } | ForEach-Object { ($_.DestinationPrefix -split '::/')[0] + "any suffix of other mac" }
> ```

感谢大神的帮助，我测试过这个powershell 命令，会返回多条IPv6结果。好像不成功
![1680859515911](https://user-images.githubusercontent.com/113037229/230583666-6bb77fe1-b102-46ba-9f36-74de3ce200f2.png)

**Comment by WaterLemons2k** [comment]
> 感谢大神的帮助，我测试过这个powershell 命令，会返回多条IPv6结果。好像不成功 ![1680859515911](https://user-images.githubusercontent.com/113037229/230583666-6bb77fe1-b102-46ba-9f36-74de3ce200f2.png)

最上面那个 Shell 命令好像也会返回多条，另外 ddns-go `仅使用标准输出（stdout）的第一个匹配的 IPv6 地址。`

**Comment by ocoj** [comment]
> > 感谢大神的帮助，我测试过这个powershell 命令，会返回多条IPv6结果。好像不成功 ![1680859515911](https://user-images.githubusercontent.com/113037229/230583666-6bb77fe1-b102-46ba-9f36-74de3ce200f2.png)
> 
> 最上面那个 Shell 命令好像也会返回多条，另外 ddns-go `仅使用标准输出（stdout）的第一个匹配的 IPv6 地址。`

我放在ddns-go测试过，他是用了上图的反回结果中三个IPv6地址的第一个，所以是出错的。

**Comment by WaterLemons2k** [comment]
> 我放在ddns-go测试过，他是用了上图的反回结果中三个IPv6地址的第一个，所以是出错的。

```powershell
 | Select-Object -Skip 2
```

在 PowerShell 命令最后添加此命令以跳过 n 个输出（例如：`2` 代表跳过前 2 个输出）。

参考：
1. https://learn.microsoft.com/powershell/module/microsoft.powershell.utility/select-object?view=powershell-7.3#-skip
2. https://stackoverflow.com/questions/31831470/select-second-or-third-object-element

**Comment by ocoj** [comment]
> ```powershell
> ```powershell
> Get-NetRoute -AddressFamily IPv6 | Where-Object { $_.DestinationPrefix.StartsWith("2409:") } | ForEach-Object { ($_.DestinationPrefix -split '::/')[0] + "any suffix of other mac" }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

q

> > 感谢大神的帮助，我测试过这个powershell 命令，会返回多条IPv6结果。好像不成功 ![1680859515911](https://user-images.githubusercontent.com/113037229/230583666-6bb77fe1-b102-46ba-9f36-74de3ce200f2.png)
> 
> 最上面那个 Shell 命令好像也会返回多条，另外 ddns-go `仅使用标准输出（stdout）的第一个匹配的 IPv6 地址。`



> > 感谢大神的帮助，我测试过这个powershell 命令，会返回多条IPv6结果。好像不成功 ![1680859515911](https://user-images.githubusercontent.com/113037229/230583666-6bb77fe1-b102-46ba-9f36-74de3ce200f2.png)
> 
> 最上面那个 Shell 命令好像也会返回多条，另外 ddns-go `仅使用标准输出（stdout）的第一个匹配的 IPv6 地址。`



> > 我放在ddns-go测试过，他是用了上图的反回结果中三个IPv6地址的第一个，所以是出错的。
> 
> ```powershell
>  | Select-Object -Skip 2
> ```
> 
> 在 PowerShell 命令最后添加此命令以跳过 n 个输出（例如：`2` 代表跳过前 2 个输出）。
> 
> 参考：
> 
> 1. https://learn.microsoft.com/powershell/module/microsoft.powershell.utility/select-object?view=powershell-7.3#-skip
> 2. https://stackoverflow.com/questions/31831470/select-second-or-third-object-element

` Get-NetRoute -AddressFamily IPv6 | Where-Object { $_.DestinationPrefix.StartsWith("240e:") } | Where-Object { $_.DestinationPrefix.endsWith("/64") }|  ForEach-Object { ($_.DestinationPrefix -split '::/')[0] + "any suffix of other mac" }`
我将你的代码改了一下，最后只反回了一个IPv6,但我知道这个代码有点难看，但我不太懂如何简化它

**Comment by WaterLemons2k** [comment]
> 我将你的代码改了一下，最后只反回了一个IPv6,但我知道这个代码有点难看，但我不太懂如何简化它

用 `-and`：
```powershell
Get-NetRoute -AddressFamily IPv6 | Where-Object { $_.DestinationPrefix.StartsWith("240e:") -and $_.DestinationPrefix.endsWith("/64") } | ForEach-Object { ($_.DestinationPrefix -split '::/')[0] + "any suffix of other mac" }
```

参考：https://learn.microsoft.com/powershell/module/microsoft.powershell.core/where-object?view=powershell-7.3#example-6-use-multiple-conditions

**Comment by ocoj** [comment]
> ```powershell
> ```powershell
> Get-NetRoute -AddressFamily IPv6 | Where-Object { $_.DestinationPrefix.StartsWith("240e:") -and $_.DestinationPrefix.endsWith("/64") } | ForEach-Object { ($_.DestinationPrefix -split '::/')[0] + "any suffix of other mac" }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

多谢！！！

**Comment by jeessy2** [comment]
wiki已更新
https://github.com/jeessy2/ddns-go/wiki/通过命令获取IP参考#获取局域网中的其它设备ipv6地址

**Comment by ben272** [comment]
> > [https://github.com/jeessy2/ddns-go/wiki/通过命令获取IP参考](https://github.com/jeessy2/ddns-go/wiki/%E9%80%9A%E8%BF%87%E5%91%BD%E4%BB%A4%E8%8E%B7%E5%8F%96IP%E5%8F%82%E8%80%83)
> > 获取其它设备IPv6地址（Linux） 需要支持EUI-64（IPv6后半部分包含ff:fe）
> > ```
> > ip -6 route | awk '{print $1}' | awk '/2409:?/' | awk -F::/ '{print $1 "any suffix of other mac"}'
> > ```
> 
> 现在软件上这个功能是单选的，无法为多台设备服务

获取局域网中的其它设备IPv6地址，linux有两个IPv6地址，每次都是使用第一个，而第一个无法正常访问，找半天没有找到教程，后面拼凑出来的命令可以用，
获取指定的前缀+后缀组成一个正确的IPv6地址：
ip -6 route | awk -F '[ \t]+|/' '$3 == "::1" { next;} $3 ~ /^fe80::/ { next;} /【替换成你地址】/ ' | awk '/240:?/' | awk -F::/ '{print $1 "【替换成你的需要的后缀】"}'

示例：
ip -6 route | awk -F '[ \t]+|/' '$3 == "::1" { next;} $3 ~ /^fe80::/ { next;} /e0e1/ ' | awk '/240:?/' | awk -F::/ '{print $1 ":2e1:69ff:fe3e:1ab1"}'
结果：
240e:8a55:c24:e0e1:2e1:69ff:fe3e:1ab1

**Comment by raining1123** [comment]
> [https://github.com/jeessy2/ddns-go/wiki/通过命令获取IP参考](https://github.com/jeessy2/ddns-go/wiki/%E9%80%9A%E8%BF%87%E5%91%BD%E4%BB%A4%E8%8E%B7%E5%8F%96IP%E5%8F%82%E8%80%83)
> 
> 获取其它设备IPv6地址（Linux） 需要支持EUI-64（IPv6后半部分包含ff:fe）
> 
> ```
> ip -6 route | awk '{print $1}' | awk '/2409:?/' | awk -F::/ '{print $1 "any suffix of other mac"}'
> ```

请问是要把any suffix of other mac替换成目标设备外网IPv6地址的后四位吗？这不就是手动粘贴？
有没有指定目标设备mac或其他固定标识的办法来一劳永逸？

**Comment by jeessy2** [comment]
> > [https://github.com/jeessy2/ddns-go/wiki/通过命令获取IP参考](https://github.com/jeessy2/ddns-go/wiki/%E9%80%9A%E8%BF%87%E5%91%BD%E4%BB%A4%E8%8E%B7%E5%8F%96IP%E5%8F%82%E8%80%83)
> 
> > 
> 
> > 获取其它设备IPv6地址（Linux） 需要支持EUI-64（IPv6后半部分包含ff:fe）
> 
> > 
> 
> > ```
> 
> > ip -6 route | awk '{print $1}' | awk '/2409:?/' | awk -F::/ '{print $1 "any suffix of other mac"}'
> 
> > ```
> 
> 
> 
> 请问是要把any suffix of other mac替换成目标设备外网IPv6地址的后四位吗？这不就是手动粘贴？
> 
> 有没有指定目标设备mac或其他固定标识的办法来一劳永逸？

手动的。无其他方式

**Comment by Se7enMuting** [comment]
我在debian系统了，ip -6 addr 有时会出现多个前缀地址，有一行是之前的，不过已失效的，另一个才是有效的，但有效的不一定是第一个匹配的 IPv6 地址。
我想这里前缀可不可以通过DNS API的获取某个指定的DNS域名的记录值作为前缀。（这个可能比较麻烦）

**Comment by WaterLemons2k** [comment]
> 我这里debian系统里看，网关重新拨号或者光猫重启后，ip -6 addr 有时会出现多个前缀地址，有一行是之前的，不过已失效的，另一行才是有效的，但有效的不一定是第一个匹配的 IPv6 地址。 我想这里前缀可不可以通过DNS API来获取某个指定的DNS域名的记录值作为前缀，因为我能保证这个记录值一定是当前的Ipv6前缀。（这个实现好像比较麻烦，感觉可以独立做个服务了。。。只是随便讲一下） 或者通过DDNS-GO内部的其他的配置来获取IPv6的前缀。因为通过网卡或者接口获取的IPv6好像总是有效地址。

意思是只输出与指定域名 IP 前缀匹配的 IPv6 地址吗？如果是的话先用 `dig` 找到域名的 IP，然后用 `cut` 提取前四段作为前缀就可以了。

基于 [Linux 仅获取纯公网 IPv6 地址](https://github.com/jeessy2/ddns-go/wiki/%E9%80%9A%E8%BF%87%E5%91%BD%E4%BB%A4%E8%8E%B7%E5%8F%96IP%E5%8F%82%E8%80%83#linux-%E4%BB%85%E8%8E%B7%E5%8F%96%E7%BA%AF%E5%85%AC%E7%BD%91-ipv6-%E5%9C%B0%E5%9D%80) 修改：

```bash
ip -6 addr | grep inet6 | awk -F '[ \t]+|/' '$3 == "::1" { next;} $3 ~ /^fe80::/ { next;} /inet6/ {print $3}' | grep $(dig +short example.com AAAA | cut -d ":" -f -4)
```

将 `example.com` 替换为你的域名。

**Comment by Se7enMuting** [comment]
> > 我这里debian系统里看，网关重新拨号或者光猫重启后，ip -6 addr 有时会出现多个前缀地址，有一行是之前的，不过已失效的，另一行才是有效的，但有效的不一定是第一个匹配的 IPv6 地址。 我想这里前缀可不可以通过DNS API来获取某个指定的DNS域名的记录值作为前缀，因为我能保证这个记录值一定是当前的Ipv6前缀。（这个实现好像比较麻烦，感觉可以独立做个服务了。。。只是随便讲一下） 或者通过DDNS-GO内部的其他的配置来获取IPv6的前缀。因为通过网卡或者接口获取的IPv6好像总是有效地址。
> 
> > 我想这里前缀可不可以通过DNS API来获取某个指定的DNS域名的记录值作为前缀
> 
> 获取指定域名记录的前缀（先用 `dig` 找到域名记录，然后用 `cut` 提取前四段作为前缀）：
> 
> ```shell
> dig +short example.com AAAA | cut -d ":" -f -4
> ```
> 
> 基于 [Linux 仅获取纯公网 IPv6 地址](https://github.com/jeessy2/ddns-go/wiki/%E9%80%9A%E8%BF%87%E5%91%BD%E4%BB%A4%E8%8E%B7%E5%8F%96IP%E5%8F%82%E8%80%83#linux-%E4%BB%85%E8%8E%B7%E5%8F%96%E7%BA%AF%E5%85%AC%E7%BD%91-ipv6-%E5%9C%B0%E5%9D%80) 修改：
> 
> ```shell
> ip -6 addr | grep inet6 | awk -F '[ \t]+|/' '$3 == "::1" { next;} $3 ~ /^fe80::/ { next;} /inet6/ {print $3}' | grep $(dig +short example.com AAAA | cut -d ":" -f -4)
> ```
> 
> 将 `example.com` 替换为你的域名。

对哦，直接找域名记录就可以了，不需要API
ddns-go的环境里可以执行dig吗？

**Comment by WaterLemons2k** [comment]
> 对哦，直接找域名记录就可以了，不需要API `dig +short example.com AAAA | awk -F: '{print $1":"$2":"$3":"$4":suffix of other mac"}'` 问题ddns-go的环境里可以执行dig吗？

`命令：/usr/bin/bash -rc dig +short example.com AAAA | awk -F: '{print $1":"$2":"$3":"$4":suffix of other mac"}'，标准输出："2606:2800:220:1:suffix of other mac\n"`

可以。

**Comment by Se7enMuting** [comment]
> 



> > 对哦，直接找域名记录就可以了，不需要API `dig +short example.com AAAA | awk -F: '{print $1":"$2":"$3":"$4":suffix of other mac"}'` 问题ddns-go的环境里可以执行dig吗？
> 
> `命令：/usr/bin/bash -rc dig +short example.com AAAA | awk -F: '{print $1":"$2":"$3":"$4":suffix of other mac"}'，标准输出："2606:2800:220:1:suffix of other mac\n"`
> 
> 可以。

感谢，不过我前面没讲完整，我是用docker版的ddns-go，运行不了这个，docker环境里没有dig ....

**Comment by WaterLemons2k** [comment]
> 感谢，不过我前面没讲完整，我是用docker版的ddns-go，运行不了这个，docker环境里没有dig ....

```shell
apk add bind-tools
```

参考：
- https://command-not-found.com/dig
- https://til.devjugal.com/linux/alpine/installing-dig-on-alpine.html

**Comment by Se7enMuting** [comment]
> > 感谢，不过我前面没讲完整，我是用docker版的ddns-go，运行不了这个，docker环境里没有dig ....
> 
> ```shell
> apk add bind-tools
> ```
> 
> 参考：
> 
> * https://command-not-found.com/dig
> * https://til.devjugal.com/linux/alpine/installing-dig-on-alpine.html

哈哈，再多补充点：
```
docker exec -it ddns-go-dnspod /bin/bash
apk update
apk add bind-tools
```
