### ISSUE TITLE
[Bug]：cloudfare dns接口是修改了么

### ISSUE THREAD

**Issue by freedom-democracy** [jeessy2/ddns-go#669]
### 问题描述

2023/04/12 09:42:50 请求接口 https://api.cloudflare.com/client/v4/zones?name=XXXXX&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

5.1.0

### 安装方式

服务

### 额外信息

2023/04/12 09:42:50 请求接口 https://api.cloudflare.com/client/v4/zones?name=XXXXX&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400

**Comment by jeessy2** [comment]
没有。是不是你生成token的方式不对，重新生成一个试试

**Comment by idealCJY** [comment]
> 没有。是不是你生成token的方式不对，重新生成一个试试

昨天都是还可以的， 今天早发现配置全被清空，然后再配置就变成这样了

**Comment by idealCJY** [comment]
> 

谢谢，现在正常了。是之前token过期，早上是我配错了。
