### ISSUE TITLE
[Windows] 以 NT Authority\Network Service 身份启动服务

### ISSUE THREAD

**Issue by kenvix** [jeessy2/ddns-go#67]
目前的版本以 Windows 服务运行时，使用的是 SYSTEM (本地系统) 账户，这样的话程序权限太高，可能造成安全风险

可否兼容 `NT Authority\Network Service` 身份启动服务？目前的版本，手动这样修改会导致 ddns-go 不响应服务控制器的请求

**Comment by jeessy2** [comment]
使用的 https://github.com/kardianos/service 帮助创建服务，支持主流平台（win/mac/linux）快速方便创建服务。
但是没有发现参数可以设置以`NT Authority\Network Service`身份启动服务。
没有管理员权限可能确实无法运行ddns-go服务。

**Comment by kenvix** [comment]
@jeessy2 

> 没有管理员权限可能确实无法运行ddns-go服务。
![image](https://user-images.githubusercontent.com/4546175/119360917-afe8dc80-bcdd-11eb-9c63-dc7dcb9d0365.png)

我个人通过使用 winsw 从外部创建了一个 ddns-go 的服务，是可以正常运行的，程序本身应该并不需要管理员权限



大概是 kardianos/service 存在某些问题，无法响应服务控制器的请求？

**Comment by jeessy2** [comment]
ddns-go不需要权限也是可以运行的，通过kardianos/service创建服务就需要管理员权限，创建服务需要管理员权限应该是操作系统必须的吧
