### ISSUE TITLE
[Bug]：v4.5.9之后版本Android无root运行报错

### ISSUE THREAD

**Issue by Pandaver** [jeessy2/ddns-go#672]
### 问题描述

root运行可以，无root运行报错

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### ddns-go 版本

v5.1.0

### 安装方式

其它

### 额外信息

![无root运行](https://user-images.githubusercontent.com/62326552/231677295-44c208e7-1040-49c7-8da7-158e2986cdec.jpg)

**Comment by WaterLemons2k** [comment]
请 @Pandaver 测试一下 #674（可以在 https://github.com/jeessy2/ddns-go/actions/runs/4698466886?pr=674 的 `Artifacts` 处下载）。

**Comment by Pandaver** [comment]
![Screenshot_2023-04-14-19-17-02-515_com termux](https://user-images.githubusercontent.com/62326552/232030032-32407f8d-78cb-4375-bba4-283f07b81021.jpg)
![Screenshot_2023-04-14-19-16-47-352_com termux](https://user-images.githubusercontent.com/62326552/232030042-4445502c-1942-4e57-9784-5f6d77eadd33.jpg)
还是不行

**Comment by Pandaver** [comment]
4.5.9_linux_arm64
![Screenshot_2023-04-14-19-19-56-541_com termux](https://user-images.githubusercontent.com/62326552/232030664-e02159cf-062b-456e-ad2b-691cfb401547.jpg)

**Comment by WaterLemons2k** [comment]
https://github.com/jeessy2/ddns-go/blob/7aa0b1810724c8cb165a5fb4563d67fe04bcc01c/util/open_explorer.go#L18

可能是 `OpenExplorer` 函数运行到这里时导致了 `bad system call`，增加了禁止自动运行此函数的选项：

```sh
./ddns-go -noOpenBrowser
```

https://github.com/jeessy2/ddns-go/actions/runs/4700605723

**Comment by Pandaver** [comment]
> https://github.com/jeessy2/ddns-go/blob/7aa0b1810724c8cb165a5fb4563d67fe04bcc01c/util/open_explorer.go#L18
> 
> 可能是 `OpenExplorer` 函数运行到这里时导致了 `bad system call`，增加了禁止自动运行此函数的选项：
> 
> ```shell
> ./ddns-go -noOpenBrowser
> ```
> 
> https://github.com/jeessy2/ddns-go/actions/runs/4700605723

is work, tks

**Comment by jeessy2** [comment]
@fatinghenji  下载https://github.com/jeessy2/ddns-go/suites/13318707314/artifacts/727556322 测下

**Comment by fatinghenji** [comment]
> @fatinghenji 下载https://github.com/jeessy2/ddns-go/suites/13318707314/artifacts/727556322 测下 @fatinghenji 下载 https://github.com/jeessy2/ddns-go/suites/13318707314/artifacts/727556322 测下

```
➜  ~ ./ddns-go       
zsh: exec format error: ./ddns-go
````
ummmm

**Comment by WaterLemons2k** [comment]
> ```
> ➜  ~ ./ddns-go       
> zsh: exec format error: ./ddns-go
> ```
> 
> ummmm

@fatinghenji 那是给 amd64 用的。下载 https://github.com/jeessy2/ddns-go/suites/13325946027/artifacts/728168801 测下。

**Comment by fatinghenji** [comment]
> > ```
> > ➜  ~ ./ddns-go       
> > zsh: exec format error: ./ddns-go
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ummmm
> 
> @fatinghenji 那是给 amd64 用的。下载 https://github.com/jeessy2/ddns-go/suites/13325946027/artifacts/728168801 测下。 @fatinghenji 那是给 amd64 用的。下载 https://github.com/jeessy2/ddns-go/suites/13325946027/artifacts/728168801 测下。

正常了一部分。
```zsh
➜  ~ ./ddns-go         
2023/06/02 16:24:02 可使用 sudo ./ddns-go -s install 安装服务运行
2023/06/02 16:24:02 第一次运行将等待 20 秒后运行 (等待网络)
2023/06/02 16:24:02 监听 :9876 ...
^C
➜  ~ sudo ./ddns-go -s install
2023/06/02 16:24:51 安装 ddns-go 服务失败, ERR: open /etc/init.d/ddns-go: no such file or directory
```

**Comment by fatinghenji** [comment]
感觉还是有点问题。
```
2023/06/02 16:39:53 IPv6将使用第 1 个IPv6地址
2023/06/02 16:39:53 请求接口http://dynv6.com/api/update?hostname=xia***********my&token=5gsRLE-****************hJMZY&ipv6=2408:82********************9543:ccd4失败! ERROR: Get "http://dynv6.com/api/update?hostname=xiao*************y&token=5********************hedURhJMZY&ipv6=2408:8220********************:ccd4": dial tcp: lookup dynv6.com on [::1]:53: read udp [::1]:40836->[::1]:53: read: connection refused
2023/06/02 16:39:53 Callback调用失败，Err：Get "http://dynv6.com/api/update?hostname=xiao*********my&token=**************&ipv6=2408:8220:****:****:****:****:****:ccd4": dial tcp: lookup dynv6.com on [::1]:53: read udp [::1]:40836->[::1]:53: read: connection refused
```
隐去了部分信息。最开始以为是梯子的问题，然后关闭梯子以后问题依旧存在。在相同局域网环境下的另一台电脑可以正常汇报。

**Comment by fatinghenji** [comment]
> 感觉还是有点问题。
> 
> ```
> 2023/06/02 16:39:53 IPv6将使用第 1 个IPv6地址
> 2023/06/02 16:39:53 请求接口http://dynv6.com/api/update?hostname=xia***********my&token=5gsRLE-****************hJMZY&ipv6=2408:82********************9543:ccd4失败! ERROR: Get "http://dynv6.com/api/update?hostname=xiao*************y&token=5********************hedURhJMZY&ipv6=2408:8220********************:ccd4": dial tcp: lookup dynv6.com on [::1]:53: read udp [::1]:40836->[::1]:53: read: connection refused
> 2023/06/02 16:39:53 Callback调用失败，Err：Get "http://dynv6.com/api/update?hostname=xiao*********my&token=**************&ipv6=2408:8220:****:****:****:****:****:ccd4": dial tcp: lookup dynv6.com on [::1]:53: read udp [::1]:40836->[::1]:53: read: connection refused
> ```
> 
> 隐去了部分信息。最开始以为是梯子的问题，然后关闭梯子以后问题依旧存在。在相同局域网环境下的另一台电脑可以正常汇报。

可能的解决方案：[在Termux中运行Go应用时出现DNS查找问题](https://ask.csdn.net/questions/1010907)
但是在termux中`resolv.conf`的文件路径是`/data/data/com.termux/files/usr/etc/resolv.conf`。我的这个文件中是写有dns解析服务器地址的。

**Comment by WaterLemons2k** [comment]
> ```shell
> ➜  ~ ./ddns-go         
> 2023/06/02 16:24:02 可使用 sudo ./ddns-go -s install 安装服务运行
> 2023/06/02 16:24:02 第一次运行将等待 20 秒后运行 (等待网络)
> 2023/06/02 16:24:02 监听 :9876 ...
> ^C
> ➜  ~ sudo ./ddns-go -s install
> 2023/06/02 16:24:51 安装 ddns-go 服务失败, ERR: open /etc/init.d/ddns-go: no such file or directory
> ```

Termux 可以用 [Termux-services](https://wiki.termux.com/wiki/Termux-services) 安装服务。

参考：https://zbttl-github-io.vercel.app/ma-que-sui-xiao-wu-zang-ju-quan-android-duan-terminal-termux-shang-shou-diao-xiao-zhi-nan/#应用自启
