### ISSUE TITLE
[功能]：在用post方式使用Webhook功能时能够更改Content-Type类型

### ISSUE THREAD

**Issue by 1264038890** [jeessy2/ddns-go#673]
### 功能描述

在使用Webhook功能时能够更改post方式的Content-Type类型

### 解决的问题

在用post方式使用WxPusher微信推送服务时出现错误：Content type ‘application/x-www-form-urlencoded；charset=UTF-8‘ not supported，而使用GET方式则正常。

报错信息如下：
2023/04/14 10:25:56 Webhook调用成功, 返回数据: "{\"code\":1005,\"msg\":\"服务器错误:Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported，这个错误是你传如的Content-Type传入不正确导致的，解决方案请参考：https://blog.csdn.net/jie11447416/article/details/109145869\",\"data\":null,\"success\":false}"

### 附加信息

WxPusher微信推送服务的api文档：https://wxpusher.zjiecode.com/docs/
报错说明以及解决方法：https://blog.csdn.net/jie11447416/article/details/109145869

**Comment by jeessy2** [comment]
如requsetbody中是json格式，会自动设置contentType为application/json

**Comment by WaterLemons2k** [comment]
`RequestBody` 里的 JSON 是什么样的呢？把 `appToken` 或 `UID` 等敏感信息隐藏掉发一下。

**Comment by 1264038890** [comment]
> https://wxpusher.zjiecode.com/docs/

{
  "appToken":"AT_xxx",
  "content":"Wxpusher祝你中秋节快乐!",
  "summary":"消息摘要",//消息摘要，显示在微信聊天页面或者模版消息卡片上，限制长度100，可以不传，不传默认截取content前面的内容。
  "contentType":1,//内容类型 1表示文字  2表示html(只发送body标签内部的数据即可，不包括body标签) 3表示markdown 
  "topicIds":[ //发送目标的topicId，是一个数组！！！，也就是群发，使用uids单发的时候， 可以不传。
      123
  ],
  "uids":[//发送目标的UID，是一个数组。注意uids和topicIds可以同时填写，也可以只填写一个。
      "UID_xxxx"
  ],
  "url":"https://wxpusher.zjiecode.com", //原文链接，可选参数
  "verifyPay":false //是否验证订阅时间，true表示只推送给付费订阅用户，false表示推送的时候，不验证付费，不验证用户订阅到期时间，用户订阅过期了，也能收到。
}
具体可以看这个链接：https://wxpusher.zjiecode.com/docs/#/
里面有详细的具体信息

**Comment by 1264038890** [comment]
> 如requsetbody中是json格式，会自动设置contentType为application/json

我这边测试是没有自动设置，使用的还是application/x-www-form-urlencoded这个格式，不知道是不是我这边配置文件的问题？

**Comment by WaterLemons2k** [comment]
好像 JSON 不允许注释，把注释（`//`）去掉看看？

参考：https://stackoverflow.com/questions/244777/can-comments-be-used-in-json

**Comment by 1264038890** [comment]
> 好像 JSON 不允许注释，把注释（`//`）去掉看看？
> 
> 参考：https://stackoverflow.com/questions/244777/can-comments-be-used-in-json

我将json改为如下内容：

{
  "appToken":"ATxxxxxxxxxxx",
  "content":"已经将ipv4地址#{ipv4Addr}更新到#{ipv4Domains}，更新结果为#{ipv4Result}。ipv6地址#{ipv6Addr}更新到#{ipv6Domains}，更新结果为#{ipv6Result}。",
  "summary":"",
  "contentType":1, 
  "topicIds":[ ],
  "uids":[UID_xxxxx],
  "url":"", 
  "verifyPay":false
}
敏感信息已删除


测试结果为依然报错，错误信息为：
2023/04/14 17:48:32 Webhook调用成功, 返回数据: "{\"code\":1005,\"msg\":\"服务器错误:Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported，这个错误是你传如的Content-Type传入不正确导致的，解决方案请参考：https://blog.csdn.net/jie11447416/article/details/109145869\",\"data\":null,\"success\":false}"

**Comment by WaterLemons2k** [comment]
> {
> "appToken":"ATxxxxxxxxxxx",
> "content":"已经将ipv4地址#{ipv4Addr}更新到#{ipv4Domains}，更新结果为#{ipv4Result}。ipv6地址#{ipv6Addr}更新到#{ipv6Domains}，更新结果为#{ipv6Result}。",
> "summary":"",
> "contentType":1,
> "topicIds":[ ],
> "uids":[UID_xxxxx],
> "url":"",
> "verifyPay":false
> }

`uids` 数组值缺双引号，应该像这样：

```json
{
    "uids":["UID_xxxxx"],
    "url":"",
    "verifyPay":false
}
```

使用前可以先验证一下 JSON 是否有效：https://jsonlint.com/

**Comment by 1264038890** [comment]
> https://jsonlint.com/

感谢！现在可以调用了
