### ISSUE TITLE
[Bug]：

### ISSUE THREAD

**Issue by yueyashe** [jeessy2/ddns-go#675]
### 问题描述

电脑系统是win10，宽带是联通网络，有ipv6，可以ping通alidns.aliyuncs.com，想通过DDNS-go远程控制电脑，但按照教程会出现以下报错，我是纯小白，麻烦大佬给看看。
当获取 IP 方式，通过接口获取会出现：
获取IPv6结果失败! 接口: https://api-ipv6.ip.sb/ip ,返回值:
改为网卡获取，获得ipV6。则出现：
请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"9574019F-5E24-51FD-A6D9-F7E137D331B9","Message":"Specified access key is not found or invalid.","Recommend":"https://next.api.aliyun.com/troubleshoot?q=InvalidAccessKeyId&product=Alidns","HostId":"alidns.aliyuncs.com","Code":"InvalidAccessKeyId"} ,返回状态码: 404

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### ddns-go 版本

ddns-go_5.1.0_windows_x86_64

### 安装方式

其它

**Comment by WaterLemons2k** [comment]
看起来是 `AccessKey` 不可用，试一下再建一个。

参考： #90
