### ISSUE TITLE
[Bug]：无法提交正确的ipv6地址

### ISSUE THREAD

**Issue by panxiuwen** [jeessy2/ddns-go#676]
### 问题描述
Windows_x86没有这个问题，只在Linux_arm上出现过
使用所有的方式，都无法提交获取的正确的ipv6地址
本机ip地址为
```
240c:cf81:1:6bc8::380
240c:cf81:1:6bc8:f4ab:4c23:80bc:b687
```
使用api可以获取到正确的ip地址(浏览器)，但是日志里显示的是第一个ip地址，向DNS服务器提交的也是第一个ip地址
使用网卡+@2的日志里显示的是第二个ip地址，但向DNS服务器提交的也是第一个ip地址(即使我在dynv6里把原来的记录删除)
使用```ip -6 addr list scope global | grep -v " fd" | sed -n 's/.*inet6 \([0-9a-f:]\+\).*/\1/p' | sed -n '2p'```命令
日志里显示的是第二个ip地址，但向DNS服务器提交的也是第一个ip地址(即使我在dynv6里把原来的记录删除)
![1](https://user-images.githubusercontent.com/35104739/232265618-0e5f5a4c-6c87-46c2-8e89-55643202a192.jpg)

![2](https://user-images.githubusercontent.com/35104739/232265624-8a89471a-3d41-4ae7-b150-5c2d3f0e3efe.jpg)

![3](https://user-images.githubusercontent.com/35104739/232265718-1284362d-140f-4730-b6b0-c4272ec03fb2.jpg)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Armbian 23.02.2 Jammy with Linux 5.10.110-rockchip-rk3588

### 架构

arm64

### ddns-go 版本

v5.1.0 v5.0.5

### 安装方式

服务

### 额外信息

设备：香橙派5
自己用本机的go编译器编译了一份也不行

**Comment by jeessy2** [comment]
看回复是更新了。
把URL的内容改成实际的，然后通过浏览器直接更新试下

**Comment by panxiuwen** [comment]
给个联系方式吧，有空的话，我直接跟您联系

**Comment by jeessy2** [comment]
github就是联系方式，自己先测下吧

**Comment by panxiuwen** [comment]
测试了2个多小时了，依然不行，api获得的跟提交的东西都不是一样的

**Comment by WaterLemons2k** [comment]
试过 `通过命令获取` 吗？

```sh
ip -6 addr list scope global | grep -v " fd" | sed -n 's/.*inet6 \([0-9a-f:]\+\).*/\1/p' | head -n 1
```

来自：https://gist.github.com/corny/7a07f5ac901844bd20c9

**Comment by panxiuwen** [comment]
@WaterLemons2k 试了，命令行只能获取第一个ip地址，向DNS服务器提交的也是第一个ip地址
![QQ截图20230416190540](https://user-images.githubusercontent.com/35104739/232304612-aaca6f96-4eaa-44a1-a846-42a93f4c074b.jpg)
使用api可以获取到正确的ip地址(浏览器)，但是日志里显示的是第一个ip地址，向DNS服务器提交的也是第一个ip地址
使用网卡+@2的日志里显示的是第二个ip地址，但向DNS服务器提交的也是第一个ip地址(即使我在dynv6里把原来的记录删除)
使用命令不知道怎么才能只获取到第二个ip地址
很奇怪，在Windows_X86上没发现这个问题，Linux_X86暂时没找到设备所以没法测试，只测试了只有一个ipv6地址的，没什么问题，而且我使用本机的go编译器自己编译了一个，结果还是一样(我不是很懂go，也不懂怎么debug)，实在没办法了才来反馈的

**Comment by WaterLemons2k** [comment]
> @WaterLemons2k 试了，命令行只能获取第一个ip地址，向DNS服务器提交的也是第一个ip地址 ![QQ截图20230416190540](https://user-images.githubusercontent.com/35104739/232304612-aaca6f96-4eaa-44a1-a846-42a93f4c074b.jpg) 使用api可以获取到正确的ip地址(浏览器)，但是日志里显示的是第一个ip地址，向DNS服务器提交的也是第一个ip地址 使用网卡+@2的日志里显示的是第二个ip地址，但向DNS服务器提交的也是第一个ip地址(即使我在dynv6里把原来的记录删除) 使用命令不知道怎么才能只获取到第二个ip地址 很奇怪，在Windows_X86上没发现这个问题，Linux_X86暂时没找到设备所以没法测试，只测试了只有一个ipv6地址的，没什么问题，而且我使用本机的go编译器自己编译了一个，结果还是一样(我不是很懂go，也不懂怎么debug)，实在没办法了才来反馈的

将 `head -n 1` 替换为：

```sh
sed -n '2p'
```

`2p` 代表只打印第二行。

参考：https://stackoverflow.com/questions/13832866/unix-show-the-second-line-of-the-file

**Comment by panxiuwen** [comment]
命令行确实成功了，但结果还是一样，日志里显示的是正确的ip地址，dns服务器里查询到的结果是那个短地址(还是在运行程序之前删除掉dns服务器里的记录)
![QQ截图20230416190540](https://user-images.githubusercontent.com/35104739/232306939-89cdba73-a655-4f80-a498-268bfed65d7c.jpg)
![QQ截图20230416190540](https://user-images.githubusercontent.com/35104739/232306969-e71ee097-516a-4496-9f9d-28ee2ea2ee88.jpg)

**Comment by WaterLemons2k** [comment]
你故意填错 `URL` 的某个字符让 Callback 调用失败看看请求的是哪个 URL，例如：

```diff
- https://dynv6.com
+ https://dynv6.co
```

**Comment by panxiuwen** [comment]
![QQ截图20230416190540](https://user-images.githubusercontent.com/35104739/232307630-c520b3e2-c134-4d54-bb25-a8e94ef2840c.jpg)
![9DBB76BE0A98F5E2922EE3C04EC64156](https://user-images.githubusercontent.com/35104739/232307639-de6a2d34-bf35-4895-904c-f32900406863.png)

**Comment by WaterLemons2k** [comment]
你让它调用失败一次，失败就会输出请求的 URL 了，例如：

```diff
- https://dynv6.com/api/update?zone=#{domain}&token=YOUR_TOKEN&ipv6=#{ip}
+ https://dynv6.com/api/update?zone=#{domain}&token=YOUR_TOKEN&ipv4=#{ip}
```

**Comment by panxiuwen** [comment]
![01](https://user-images.githubusercontent.com/35104739/232309755-3b0cb255-c5c6-4caa-8332-b09c460e33ff.png)
![02](https://user-images.githubusercontent.com/35104739/232309769-aa323d43-aa86-49ca-ab08-8446ace1d581.png)
![03](https://user-images.githubusercontent.com/35104739/232309778-af96cef3-4df3-406a-9025-17c0e4a1c349.png)
不知道怎么调用失败

**Comment by WaterLemons2k** [comment]
```url
https://dynv6.com/api/update?zone=#{domain}&ipv6=#{ip}
```

把这个填进 `URL` 里就可以了。肯定会因为没有 `token` 而调用失败，看看输出的请求 URL 是什么。记得把敏感信息抹掉。

**Comment by panxiuwen** [comment]
![02](https://user-images.githubusercontent.com/35104739/232312308-27dda379-b11c-4060-b4ab-288e068c6b74.png)
写了个错的token，日志里也看不出来什么

**Comment by WaterLemons2k** [comment]
> ![02](https://user-images.githubusercontent.com/35104739/232312308-27dda379-b11c-4060-b4ab-288e068c6b74.png)
> 写了个错的token，日志里也看不出来什么

可以将 `ipv6` 的值更改为 `#{ip}` 吗？看一下会替换为哪个 IPv6 地址。

**Comment by panxiuwen** [comment]
替换成#{ip}就好了，提交的是日志里的ip，应该是ip=auto的锅
![01](https://user-images.githubusercontent.com/35104739/232312799-ccb31a00-8f79-4c96-9f41-7ab9a4efcd84.png)
![02](https://user-images.githubusercontent.com/35104739/232312806-fd2a129a-4c35-48c1-89d3-10d4a84948f3.png)
