### ISSUE TITLE
[功能]：aliyun解析时有解析请求来源（ISP）选择

### ISSUE THREAD

**Issue by jim66707a** [jeessy2/ddns-go#677]
### 功能描述

我添加一个IPV6的默认解析到阿里云时，可用移动宽带或移动网络时可以正常访问主机，就是用电信网无法访问到，后来手动在阿里云上添加了一条解析解析请求来源（ISP）选择中国电信，用电信网也可以访问了，但这个DDNS的默认解析IPV6地址变了后，又要手动去改电信这条解析，能不能自动再添加一个解析 解析请求来源（ISP）为中国电信的

**Comment by WaterLemons2k** [comment]
https://github.com/jeessy2/ddns-go/wiki/传递自定义参数#aliyun

通过[Line参数](https://help.aliyun.com/document_detail/29807.html)修改

**Comment by jim66707a** [comment]
代码是写在DDNS-GO 的Domains里面hossin.work?Line=telecom 这样写代码出错

**Comment by WaterLemons2k** [comment]
> 代码是写在DDNS-GO 的Domains里面hossin.work?Line=telecom 这样写代码出错

报错是什么？

**Comment by jim66707a** [comment]
2023/04/24 20:37:34 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"076F2332-FF8F-5F9C-B8CB-D545DB384573","Message":"Specified signature is not matched with our calculation. server string to sign is:GET&%2F&AccessKeyId%3DLTAI5tPHUDpBwS8dDBgQ6Z7g%26Action%3DDescribeSubDomainRecords%26DomainName%3Dhossin.work%2520Line%253Dtelecom%26Format%3DJSON%26SignatureMethod%3DHMAC-SHA1%26SignatureNonce%3D1682339854703132687%26SignatureVersion%3D1.0%26SubDomain%3D%2540.hossin.work%2520Line%253Dtelecom%26Timestamp%3D2023-04-24T12%253A37%253A34Z%26Type%3DAAAA%26Version%3D2015-01-09","Recommend":"https://next.api.aliyun.com/troubleshoot?q=SignatureDoesNotMatch&product=Alidns","HostId":"alidns.aliyuncs.com","Code":"SignatureDoesNotMatch"} ,返回状态码: 400

**Comment by WaterLemons2k** [comment]
> DomainName%3Dexample.com%2520Line%253Dtelecom

看起来域名和参数 `Line` 中间有一个空格（`%20`），将空格改为问号（`?`）看看。

```diff
- example.com Line=telecom
+ example.com?Line=telecom
```

参考：https://www.w3schools.com/tags/ref_urlencode.ASP

**Comment by jim66707a** [comment]
空格换成了？还是一样
2023/04/25 21:26:04 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"4BB78202-3E8C-5261-A395-CD3EC2974589","HostId":"alidns.aliyuncs.com","Code":"InvalidDomainName.Format","Message":"Invalid domain name.","Recommend":"https://next.api.aliyun.com/troubleshoot?q=InvalidDomainName.Format&product=Alidns"} ,返回状态码: 400

**Comment by WaterLemons2k** [comment]
> 空格换成了？还是一样

`？`是全角，换成半角（`?`）看看。

**Comment by jim66707a** [comment]
哦，我输入的是英文的?

**Comment by WaterLemons2k** [comment]
那截图 `Domains` 看下，敏感信息打码。

**Comment by jim66707a** [comment]
![image](https://user-images.githubusercontent.com/128569644/234302072-86c9fcea-2aee-4c64-a8bd-a44770a08045.png)

**Comment by jeessy2** [comment]
版本不对。你用的版本不支持，升级

**Comment by jim66707a** [comment]
更新了又有新问题了。。。。。。
2023/04/26 00:13:38 连接失败! <a target='blank' href='https://myip6.ipip.net'>点击查看接口能否返回IPv6地址</a>, 参考说明:<a target='blank' href='https://github.com/jeessy2/ddns-go#使用ipv6'>点击访问</a>

**Comment by jeessy2** [comment]
日志贴多点。把https://myip6.ipip.net/移除

**Comment by jim66707a** [comment]
2023/04/26 17:40:39 配置文件已保存在: /root/.ddns_go_config.yaml
2023/04/26 17:40:39 连接失败! <a target='blank' href='https://speed.neu6.edu.cn/getIP.php'>点击查看接口能否返回IPv6地址</a>, 参考说明:<a target='blank' href='https://github.com/jeessy2/ddns-go#使用ipv6'>点击访问</a>
2023/04/26 17:40:39 错误信息: Get "https://speed.neu6.edu.cn/getIP.php": dial tcp6 [2001:da8:9000::66]:443: connect: cannot assign requested address
2023/04/26 17:40:39 连接失败! <a target='blank' href='https://v6.ident.me'>点击查看接口能否返回IPv6地址</a>, 参考说明:<a target='blank' href='https://github.com/jeessy2/ddns-go#使用ipv6'>点击访问</a>
2023/04/26 17:40:39 错误信息: Get "https://v6.ident.me": dial tcp6 [2a01:4f8:c0c:bd0a::1]:443: connect: cannot assign requested address
2023/04/26 17:40:39 未能获取IPv6地址, 将不会更新

**Comment by jim66707a** [comment]
![image](https://user-images.githubusercontent.com/128569644/234537202-7be4e715-5c48-4b88-80e5-9bbc6cc0561f.png)

**Comment by jeessy2** [comment]
测下你IPv6通不通？通过网卡获取有IPv6地址没有

**Comment by jim66707a** [comment]
nas是有ipV6地址的，手动用ipV6解释可以打开，docker没有ipv6
![image](https://user-images.githubusercontent.com/128569644/234575513-9ec310c0-5211-4b69-919c-bd6f04dc933d.png)

**Comment by jim66707a** [comment]
这个新增一个网络ipv6的子网和网关要怎么填的
![image](https://user-images.githubusercontent.com/128569644/234594621-76886b45-0b3d-47a2-b780-a2c009d90bb1.png)
我这样填进去网卡的地址不对。。
![image](https://user-images.githubusercontent.com/128569644/234595034-6686dd9a-1479-4078-9a93-475024b4f02d.png)

**Comment by WaterLemons2k** [comment]
不用新建网络吧，试下 `使用与 Docker Host 相同的网络`。

**Comment by jim66707a** [comment]
![image](https://user-images.githubusercontent.com/128569644/234599724-f25570f8-77bc-490d-ae0a-c49cd59de76e.png)
host是灰色的管理也点不了

**Comment by WaterLemons2k** [comment]
删除现有的容器（备份配置文件），然后点击映像 -> 选择`jeessy/ddns-go` -> 启动 -> 高级设置 -> 网络中勾选`使用与 Docker Host 相同的网络`，高级设置中勾选`启动自动重新启动`。
