### ISSUE TITLE
unraid docker 自动更新后，原本的配置会不见

### ISSUE THREAD

**Issue by justsonghua** [jeessy2/ddns-go#678]
如题，unraid docker自动更新后，再进入webui，原本配置的AccessKey ID/Secret，域名解析和webhook都会不见，需要重新配置一遍。
请问这是什么问题？有什么办法可以解决。

**Comment by WaterLemons2k** [comment]
有将 ddns-go 的配置文件路径映射到主机吗？

**Comment by justsonghua** [comment]
我在配置容器的时候添加了/config路径，但是创建后文件夹里面是空的，在webui界面发现默认配置路径是/root/.ddns_go_config.yaml。

**Comment by WaterLemons2k** [comment]
> 我在配置容器的时候添加了/config路径，但是创建后文件夹里面是空的，在webui界面发现默认配置路径是/root/.ddns_go_config.yaml。

那把容器的 `/root` 路径映射到主机看看。配置文件不在 `/config` 路径。

**Comment by justsonghua** [comment]
> > 我在配置容器的时候添加了/config路径，但是创建后文件夹里面是空的，在webui界面发现默认配置路径是/root/.ddns_go_config.yaml。
> 
> 那把容器的 `/root` 路径映射到主机看看。配置文件不在 `/config` 路径。

从头重新配置了一遍，在容器配置中添加了/root路径，并指向/mnt/user/appdata/ddns-go。现在可以在对应的文件夹下面找到配置文件了。接下来就是看自动更新后配置文件是否还在。

**Comment by justsonghua** [comment]
> > 我在配置容器的时候添加了/config路径，但是创建后文件夹里面是空的，在webui界面发现默认配置路径是/root/.ddns_go_config.yaml。
> 
> 那把容器的 `/root` 路径映射到主机看看。配置文件不在 `/config` 路径。
