### ISSUE TITLE
[功能]：希望增加log日志本地存储

### ISSUE THREAD

**Issue by wuai1024** [jeessy2/ddns-go#679]
### 功能描述

希望能增加配置，能让日志除了在 web 界面输出，还可以在本地存储

**Comment by WaterLemons2k** [comment]
是 Shell 重定向吗？

```sh
./ddns-go > log
```

**Comment by wuai1024** [comment]
> 是 Shell 重定向吗？
> 
> ```shell
> ./ddns-go > log
> ```
> 
> 参考：https://www.runoob.com/linux/linux-shell-io-redirections.html

我是用docker启动的

**Comment by WaterLemons2k** [comment]
> 我是用docker启动的

```sh
docker logs ddns-go >& log
```

将 `ddns-go` 替换为容器名称。

参考：https://stackoverflow.com/questions/41144589/how-to-redirect-docker-container-logs-to-a-single-file

**Comment by wuai1024** [comment]
> > 我是用docker启动的
> 
> ```shell
> docker logs ddns-go >& log
> ```
> 
> 将 `ddns-go` 替换为容器名称。
> 
> 参考：https://stackoverflow.com/questions/41144589/how-to-redirect-docker-container-logs-to-a-single-file

好的，谢谢
