### ISSUE TITLE
[Bug]：clash tun模式下连接失败

### ISSUE THREAD

**Issue by gjluck6** [jeessy2/ddns-go#681]
### 问题描述

未开启clash tun模式可正常获取v6地址；开启clash tun模式日志显示连接失败，但使用浏览器可正常访问网站显示v6地址，有大哥知道怎么解决吗。

日志：
2023/04/19 14:28:44 连接失败! <a target='blank' href='https://speed.neu6.edu.cn/getIP.php'>点击查看接口能否返回IPv6地址</a>, 参考说明:<a target='blank' href='https://github.com/jeessy2/ddns-go#使用ipv6'>点击访问</a>
2023/04/19 14:28:44 错误信息: Get "https://speed.neu6.edu.cn/getIP.php": dial tcp6: lookup speed.neu6.edu.cn: no such host
2023/04/19 14:28:44 连接失败! <a target='blank' href='https://6.ipw.cn'>点击查看接口能否返回IPv6地址</a>, 参考说明:<a target='blank' href='https://github.com/jeessy2/ddns-go#使用ipv6'>点击访问</a>
2023/04/19 14:28:44 错误信息: Get "https://6.ipw.cn": dial tcp6: lookup 6.ipw.cn: no such host
2023/04/19 14:28:44 未能获取IPv6地址, 将不会更新

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### ddns-go 版本

v5.1.0

### 安装方式

服务

### 额外信息

![image](https://user-images.githubusercontent.com/61338638/233009470-5b2f4fa9-b0b2-4958-ac94-5a90727151c8.png)
![image](https://user-images.githubusercontent.com/61338638/233009691-f147f88e-94e9-498c-8090-528a98dd4225.png)

**Comment by jeessy2** [comment]
这个自行研究了。IPv6不通
