### ISSUE TITLE
[功能]：

### ISSUE THREAD

**Issue by a499738316** [jeessy2/ddns-go#683]
### 功能描述

我说在openwrt下装的ddns-go，但是我openwrt安装了证书，https访问情况下，跳转ddns-go的管理端就会报网站不安全，希望作者能加一个配置证书的地方，可以https访问

**Comment by jeessy2** [comment]
可以加一个nginx反代

**Comment by a499738316** [comment]
首先谢谢作者能回复啊，其次可能nginx不行，端口被占用了，nginx只能用其他端口，这样的话openwrt还是点进去还是网页不安全，只能手动改反代后的端口

**Comment by a499738316** [comment]
![image](https://user-images.githubusercontent.com/37020005/233540040-896cf114-3ab5-4306-be7b-7cf7b5d95e3e.png)
