### ISSUE TITLE
[功能]：忘记密码了，登录不了，请添加重置配置或者重置密码功能

### ISSUE THREAD

**Issue by ArchieHurry** [jeessy2/ddns-go#685]
### 功能描述

设置的密码输入错误，忘记了，删除客户端都还在，想找本地配置文件找不到

**Comment by WaterLemons2k** [comment]
https://github.com/jeessy2/ddns-go/wiki/FAQ#忘记用户名或密码

#85 #115 #197 #208 #362 #447 #483 #554

**Comment by ArchieHurry** [comment]
感谢
