### ISSUE TITLE
Namecheap更新域名解析失败

### ISSUE THREAD

**Issue by wxh2** [jeessy2/ddns-go#686]
填入namecheap的密码，然后关闭ipv4更新，打开ipv6更新，日志提示invalid ip

**Comment by jeessy2** [comment]
没看懂，你的这个操作是什么意思

**Comment by wxh2** [comment]
2023/04/28 17:02:15 修改域名解析 * 失败！Status: <?xml version="1.0" encoding="utf-16"?>
<interface-response>
<Command>SETDNSHOST</Command>
<Language>eng</Language>
<ErrCount>1</ErrCount>
<errors>
<Err1>Invalid IP</Err1>
</errors>
<ResponseCount>1</ResponseCount>
<responses>
<response>
<Description>Invalid IP</Description>
<ResponseNumber>304156</ResponseNumber>
<ResponseString>Validation error; invalid ; IP Address</ResponseString>
</response>
</responses>
<Done>true</Done>
<debug><![CDATA[]]></debug>
</interface-response>

**Comment by wxh2** [comment]
![Screenshot_2023-04-28-17-03-54-670-edit_com microsoft emmx](https://user-images.githubusercontent.com/55911222/235105010-d54ea746-0a38-4b83-8711-0c8301f78f4b.jpg)

**Comment by jeessy2** [comment]
配置截图看下

**Comment by wxh2** [comment]
![Uploading IMG_20230428_171241.png…]()

**Comment by wxh2** [comment]
![IMG_20230428_171224](https://user-images.githubusercontent.com/55911222/235107127-82a327db-dc55-44d1-97eb-cf0b09a97d9a.jpg)

**Comment by wxh2** [comment]
![IMG_20230428_171241](https://user-images.githubusercontent.com/55911222/235107230-0e51a024-45e6-4293-b1b1-0ae9beff39f8.png)

**Comment by jeessy2** [comment]
是不是已经存在v4地址了。重新创建一个v6的二级域名

**Comment by WaterLemons2k** [comment]
不支持 IPv6。

> **NOTE**: It is only possible to dynamically update IPv4 addresses (A records) at this time. Currently, IPv6 is not supported by our Dynamic DNS. 

参考：https://www.namecheap.com/support/knowledgebase/article.aspx/29/11/how-to-dynamically-update-the-hosts-ip-with-an-http-request/

**Comment by wxh2** [comment]
那godaddy支不支持ipv6？

**Comment by WaterLemons2k** [comment]
应该可以。看 API 类型里有 AAAA。

参考：https://developer.godaddy.com/doc/endpoint/domains#/v1/recordReplaceTypeName

**Comment by wxh2** [comment]
godaddy支持ipv6，刚才又买了一个域名，解析成功了

**Comment by jeessy2** [comment]
Namecheap的域名不能转name server到其他服务商？
