### ISSUE TITLE
[Bug]：一直提示错误信息: Get "https://myip4.ipip.net": net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by CnSuperYoung** [jeessy2/ddns-go#691]
### 问题描述

![image](https://user-images.githubusercontent.com/6590372/234900784-4fef0f83-7ce9-4099-8af1-3d58c8213451.png)
更换过多个不同运营商的dns也无效，但是仍然无法访问，进入容器的控制台，可以ping通对应的网址

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

i386

### ddns-go 版本

v5.1.1

### 安装方式

Docker

### 额外信息

![image](https://user-images.githubusercontent.com/6590372/234901417-67d7eb98-539a-4194-a47e-8991136f40c9.png)

**Comment by jeessy2** [comment]
进入容器通过wgwt/curl看接口通不通

**Comment by VergilGao** [comment]
把 /etc/localtime 以readonly 方式挂载进容器，然后保证你host的时间是对的
在容器里 curl 一下对应接口的，看看返回了什么。

**Comment by CnSuperYoung** [comment]
> 把/etc/localtime以readonly方式挂载进入容器，然后证明你host的时间是对的 在容器里curl下对应接口的，看回去了怎么了。

curl命令不存在，请问下安装的命令是啥？yum、apt-get install都试了

**Comment by WaterLemons2k** [comment]
> curl命令不存在，请问下安装的命令是啥？yum、apt-get install都试了

```sh
apk add curl
```

**Comment by CnSuperYoung** [comment]
> 

![image](https://user-images.githubusercontent.com/6590372/235040996-df905682-a531-4864-b404-a14e4f327512.png)
一直卡在这，安装源换过中科大，换过阿里

**Comment by WaterLemons2k** [comment]
> ![image](https://user-images.githubusercontent.com/6590372/235040996-df905682-a531-4864-b404-a14e4f327512.png)
> 一直卡在这，安装源换过中科大，换过阿里

清华源：
```bash
sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
```

参考：https://mirrors.tuna.tsinghua.edu.cn/help/alpine/
