### ISSUE TITLE
[Bug]：阿里域名无法在win11上ddns,测试两台win10是可以的

### ISSUE THREAD

**Issue by softwareygr** [jeessy2/ddns-go#693]
### 问题描述

2023/04/29 05:39:59 可使用 .\ddns-go.exe -s install 安装服务运行
2023/04/29 05:39:59 第一次运行将等待 20 秒后运行 (等待网络)
2023/04/29 05:39:59 监听 :9876 ...
2023/04/29 05:40:17 配置文件已保存在: C:\Users\NUC8\.ddns_go_config.yaml
2023/04/29 05:40:17 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"D5210143-AE09-5430-B675-1A19CE16FA95","Message":"Specified time stamp or date value is expired.","Recommend":"https://next.api.aliyun.com/troubleshoot?q=InvalidTimeStamp.Expired&product=Alidns","HostId":"alidns.aliyuncs.com","Code":"InvalidTimeStamp.Expired"} ,返回状态码: 400

2023/04/29 05:40:19 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"EFA06004-C38C-583D-B7F5-D1C879026252","Message":"Specified time stamp or date value is expired.","Recommend":"https://next.api.aliyun.com/troubleshoot?q=InvalidTimeStamp.Expired&product=Alidns","HostId":"alidns.aliyuncs.com","Code":"InvalidTimeStamp.Expired"} ,返回状态码: 400

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### ddns-go 版本

几个版本

### 安装方式

其它

### 额外信息

2023/04/29 05:39:59 可使用 .\ddns-go.exe -s install 安装服务运行
2023/04/29 05:39:59 第一次运行将等待 20 秒后运行 (等待网络)
2023/04/29 05:39:59 监听 :9876 ...
2023/04/29 05:40:17 配置文件已保存在: C:\Users\NUC8\.ddns_go_config.yaml
2023/04/29 05:40:17 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"D5210143-AE09-5430-B675-1A19CE16FA95","Message":"Specified time stamp or date value is expired.","Recommend":"https://next.api.aliyun.com/troubleshoot?q=InvalidTimeStamp.Expired&product=Alidns","HostId":"alidns.aliyuncs.com","Code":"InvalidTimeStamp.Expired"} ,返回状态码: 400

2023/04/29 05:40:19 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"EFA06004-C38C-583D-B7F5-D1C879026252","Message":"Specified time stamp or date value is expired.","Recommend":"https://next.api.aliyun.com/troubleshoot?q=InvalidTimeStamp.Expired&product=Alidns","HostId":"alidns.aliyuncs.com","Code":"InvalidTimeStamp.Expired"} ,返回状态码: 400

**Comment by WaterLemons2k** [comment]
时间不对。

https://github.com/jeessy2/ddns-go/wiki/FAQ#阿里云错误代码-invalidtimestampexpired

**Comment by softwareygr** [comment]
可以了谢谢，我安装了黑苹果双系统，导致时间不对
