### ISSUE TITLE
Webhook 不推送信息

### ISSUE THREAD

**Issue by lizhiwei8061** [jeessy2/ddns-go#696]
### 问题描述

求助：op 上次进行在线更新后，好像试ddns-go 也随之更新了，域名解析成功pushplus收不到消息了，模拟测试Webhook可以收到测试消息，看ddns-go日志没找到有用的信息，请问可以怎么排查下

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

git-24.113.45209-e9b39cd

### 安装方式

其它

**Comment by WaterLemons2k** [comment]
Webhook 配置文件是什么？

**Comment by lizhiwei8061** [comment]
搜到了好几个 ddnsgo-config.yaml 应该看哪个，搞晕了

**Comment by WaterLemons2k** [comment]
> 搜到了好几个 ddnsgo-config.yaml 应该看哪个，搞晕了

看一下 Webhook 的 URL 和 RequestBody 就可以了。

**Comment by lizhiwei8061** [comment]
这个是 ddnsgo-config.yaml 的webhook的部分
![Snipaste_2023-05-08_15-36-22](https://user-images.githubusercontent.com/121220591/236764448-40574ac0-fc3d-4086-bfda-0928d2088dc5.jpg)

**Comment by WaterLemons2k** [comment]
可以把网页的 Webhook 配置也截图一下吗？

**Comment by lizhiwei8061** [comment]
这是网页的webhook配置
![image](https://user-images.githubusercontent.com/121220591/236766754-799585c3-19bb-4670-8110-f013b3ec0ddf.png)

**Comment by WaterLemons2k** [comment]
配置文件的 `webhookdisable` 和网页的 `是否禁用` 都为 true，取消勾选 `是否禁用` 看看。

**Comment by lizhiwei8061** [comment]
啊 打勾是禁用？我一直想着那里是 是否启用

**Comment by WaterLemons2k** [comment]
> 要不移除webhook的`是否禁用` 有点鸡肋，填了就发，没填就不发，弄一个在这，有点费解

`是否禁用` 确实跟别的复选框都不一样，要不要换成选项 `-noWebhook`？不要就算了。

**Comment by lizhiwei8061** [comment]
不影响使用 其他都一切正常 有时候有点强迫症^-^

**Comment by jeessy2** [comment]
> > 要不移除webhook的`是否禁用` 有点鸡肋，填了就发，没填就不发，弄一个在这，有点费解
> 
> `是否禁用` 确实跟别的复选框都不一样，要不要换成选项 `-noWebhook`？不要就算了，全部还原。

选项都不要了，不用的话，把URL剪贴到RequestBody中就完了

**Comment by jeessy2** [comment]
[v5.2.0](https://github.com/jeessy2/ddns-go/releases/tag/v5.2.0) 已移除`是否禁用`
