### ISSUE TITLE
能支持华为云解析吗？

### ISSUE THREAD

**Issue by MeowCold** [jeessy2/ddns-go#7]
阿里云，腾讯云 免费用户TTL 最低10分钟，华为云解析 支持免费用户 TTL 300   最低5分钟

**Comment by jeessy2** [comment]
安排

**Comment by jeessy2** [comment]
1.2.0后开始支持。https://github.com/jeessy2/ddns-go/releases/tag/v1.2.0

**Comment by MeowCold** [comment]
真快 感谢
