### ISSUE TITLE
[功能]：webhook使用代理

### ISSUE THREAD

**Issue by Waitung** [jeessy2/ddns-go#700]
### 功能描述

webhook 使用 telegram bot 的时候，由于国内环境不能直连，虽然能在 ddns-go 之外的地方解决，但如果 webhook 里面能增加使用代理的功能会更加方便。希望发者能考虑一下，大概如下图这样。
![iqdT0A.png](https://i.328888.xyz/2023/05/12/iqdT0A.png)

**Comment by WaterLemons2k** [comment]
`ddns-go` 从变量获取代理，所以只需添加 `HTTPS_PROXY` 变量即可：

```sh
HTTPS_PROXY=http://127.0.0.1:7890 ./ddns-go
```

参考：https://pkg.go.dev/net/http#ProxyFromEnvironment

**Comment by Waitung** [comment]
明白了，我用 systemctl 管理的，不知道为什么 `export https_proxy=http://127.0.0.1:7890` 不生效，在 service 里添加 Environment=https_proxy=http://127.0.0.1:7890 才可以。
