### ISSUE TITLE
[功能]：不进入网页的情况下修改配置文件

### ISSUE THREAD

**Issue by tiandan6666** [jeessy2/ddns-go#701]
### 功能描述

希望可以使用配置文件来允许外网访问

### 解决的问题

无图形界面linux无法使用

**Comment by jeessy2** [comment]
局域网内访问Linux IP:9876就可以访问了

**Comment by tiandan6666** [comment]
> 局域网内访问Linux IP:9876就可以访问了
如果可以我就不问了啊.........

**Comment by tiandan6666** [comment]
> 局域网内访问Linux IP:9876就可以访问了

wc，竟然是防火墙的问题
