### ISSUE TITLE
[Bug]：请求接口https://alidns.aliyuncs.com/失败! dial tcp: lookup alidns.aliyuncs.com on [::1]:53: read udp [::1]:55546->[::1]:53: read: connection refused

### ISSUE THREAD

**Issue by fuping685** [jeessy2/ddns-go#702]
### 问题描述

请求接口https://alidns.aliyuncs.com/失败! ERROR: Get "https://alidns.aliyuncs.com/?AccessKeyId=xxx&Action=DescribeSubDomainRecords&DomainName=xxx.com&Format=JSON&Signature=xxx&SignatureMethod=HMAC-SHA1&SignatureNonce=00000&SignatureVersion=1.0&SubDomain=%40.xxx.com&Timestamp=2023-05-18T03%3A03%3A32Z&Type=AAAA&Version=2015-01-09": dial tcp: lookup alidns.aliyuncs.com on [::1]:53: read udp [::1]:55546->[::1]:53: read: connection refused

在网上搜了很多，没找到类似的错误，求助

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### ddns-go 版本

latest

### 安装方式

服务

**Comment by WaterLemons2k** [comment]
是不是 Android？

参考：#587 #589

**Comment by fuping685** [comment]
> 是不是 Android？
> 
> 参考：#587 #589

成功了，多谢！

通过指定DNS搞定了：
./ddns-go -dns 114.114.114.114
