### ISSUE TITLE
[Bug]：win11阿里云ddns

### ISSUE THREAD

**Issue by 897387171** [jeessy2/ddns-go#703]
### 问题描述

请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"B19999B4-DB94-5D43-B4F6-23CE04662D2F","HostId":"alidns.aliyuncs.com","Code":"InvalidDomainName.Format","Message":"Invalid domain name.","Recommend":"https://next.api.aliyun.com/troubleshoot?q=InvalidDomainName.Format&product=Alidns"} ,返回状态码: 400
一直出现这个

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### ddns-go 版本

v5.2.1

### 安装方式

其它

**Comment by jeessy2** [comment]
截图看下域名怎么填写的，重要内容打码

**Comment by 897387171** [comment]
jacksixth.top;
mc.jacksixth.top;
panel.jacksixth.top;

**Comment by 897387171** [comment]
![image](https://github.com/jeessy2/ddns-go/assets/42532036/73c4ad7c-895c-40f6-a681-e70eae82332a)

**Comment by jeessy2** [comment]
为什么要加分号

**Comment by 897387171** [comment]
奥  不用加啊  我的问题sorry

**Comment by 897387171** [comment]
敲代码敲傻了
