### ISSUE TITLE
[Bug]：无法使用discord推送信息

### ISSUE THREAD

**Issue by justsonghua** [jeessy2/ddns-go#704]
### 问题描述

2023/05/21 22:30:04 Webhook调用失败，Err：请求接口 https://discord.com/api/webhooks/1109871498052784138/jSm… 失败! 返回内容: {"message": "Cannot send an empty message", "code": 50006} ,返回状态码: 400

这个接口是可以正常使用的，unraid的周运行报告每周都可以正常通过Discord推送到手机上。

DDNS-GO在刚配置好Discord的一两个星期也可以正常接收通知，但是之后就一直没有通知了。今天进后台测试了一下，发现这个错误提示。

URL中填的是Discord中生成的api。

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

i386

### ddns-go 版本

v5.2.1

### 安装方式

Docker

### 额外信息

RequestBody：
```
{
	"content":"域名动态解析.",
	"embeds":[{
		"color":15258703,
		"author":{"name":"DDNS-Go"},
		"description":"域名动态解析状态：\n 
			IPv4:#{ipv4Result}.\n 地址: #{ipv4Addr}.\n 
			IPv6:#{ipv6Result}.\n 地址: #{ipv6Addr}.\n\n 
			IPv4域名一览：\n #{ipv4Domains}\n\n 
			IPv6域名一览：\n #{ipv6Domains}",
		"footer":{"text":"DDNS-Go IPv4:#{ipv4Result}. IPv6:#{ipv6Result}."}
	}]
}
```

**Comment by WaterLemons2k** [comment]
看一下 RequestBody。重要信息打码。

**Comment by jeessy2** [comment]
description中的内容应该在一行中，不能手动回车。
把 json内容放在这里校验 https://jsonlint.com/
