### ISSUE TITLE
[功能]：缓存里的重试次数做成可配置,实现秒级更新

### ISSUE THREAD

**Issue by feranwq** [jeessy2/ddns-go#706]
### 功能描述

IPv6 场景 通过灵活配置重复时间和缓存重复次数可以在本地每秒对比 IP,触发更新

**Comment by jeessy2** [comment]
能详细描述下不

**Comment by feranwq** [comment]
> 能详细描述下不

目前只能设置同步间隔时间, 如果我设置为 1 秒, 每 6 秒会请求一次cloudflare 的 API ,为了防止触发限流, 可以把 d.Times 作为可配置项
目前只能拉代码自己编译一下

```
func (d *IpCache) Check(newAddr string) bool {
	if newAddr == "" {
		return true
	}
	// 地址改变 或 达到剩余次数
	if d.Addr != newAddr || d.Times <= 1 {
		d.Addr = newAddr
		d.Times = 6
		return true
	}
	d.Addr = newAddr
	d.Times--
	return false
}
```

**Comment by feranwq** [comment]
提了个 PR 可以看下

**Comment by jeessy2** [comment]
可以系统启动时，判断时间是否小于某个值，如小于程序自动把`Times`调大一点。就不用在增加一个配置参数了

**Comment by feranwq** [comment]
服务商太多了,这个 Times 调整为多少合适不好确定

**Comment by jeessy2** [comment]
和服务商无关，比如同步间隔1s, `Times`为120？ 同步间隔5s, `Times`为24？

**Comment by feranwq** [comment]
如果服务商 A API 限制是每小时 10 次, 服务商 B API 限制 每秒 10 次,这个自动计算的值只能按照每小时 10 次来
 个人认为还是把配置权交给用户, 提供默认值即可, 让使用的人选择合理的轮询间隔和缓存次数

**Comment by jeessy2** [comment]
不用管他限制多少次，设定一个目标值。把配置交给用户，大部分不懂啊。ddns-go目标是简单实用

**Comment by jeessy2** [comment]
打个比方：我设置一个阿里云 / cloudflare，我还得去看接口限制多少次，做为一个新手或老手，在哪里找都不知道，这不很麻烦？程序自动处理了更好，目标值设置3～5分钟（待讨论），我不相信服务商3～5分钟都不让我请求一次

**Comment by feranwq** [comment]
> 默认自动设置，如果输入的话，就手动？

对的,默认值不变, 然后提供配置让用户自定义,这是这个 issue 的初衷, PR 也是这么做的,保持原样(300 秒循环, 6 次重试), 启动时传参自定义这两个参数

**Comment by feranwq** [comment]
以我的场景为例, 我是本地每秒查询一次 IP, 然后每天(86400 次缓存)访问一次 cloudflare 对比一下 API 即可,因为 IPv6 直接在本机, 可以达到即时更新的效果

**Comment by jeessy2** [comment]
也行，这样也简单点，就是要知道这个怎么用的

**Comment by jeessy2** [comment]
那你修改下README的文档说明下就行了
