### ISSUE TITLE
腾讯云问题

### ISSUE THREAD

**Issue by rui3bo2** [jeessy2/ddns-go#71]
为什么群晖上配置好腾讯云的id和token保存并不能解析？日志里没有任何变化？

**Comment by jeessy2** [comment]
可以截图看看不？ 配置Id+token后，还要配置解析的域名，不然不会触发的

**Comment by rui3bo2** [comment]
![3629261C-E174-4A52-98E5-73387769ED5D](https://user-images.githubusercontent.com/6735816/121037037-a9a73580-c79e-11eb-855f-29f6ab40ede9.png)

![121151EF-D0BC-4B36-A132-AD54F9CFDA3A](https://user-images.githubusercontent.com/6735816/121037072-b035ad00-c79e-11eb-8c28-d9d3139d4652.png)

说明中没看见怎么配置域名，哪里有介绍吗？也不知道问题出在哪里？

**Comment by jeessy2** [comment]
域名填写了吗

**Comment by jeessy2** [comment]
![截屏2021-06-07 下午11 53 30](https://user-images.githubusercontent.com/6205259/121051050-b4d48280-c7eb-11eb-8409-cb626db3e968.png)
是否启用根据情况打勾
