### ISSUE TITLE
[功能]：dockerHub上面建议添加github地址

### ISSUE THREAD

**Issue by hjkl950217** [jeessy2/ddns-go#710]
### 功能描述

一直在使用这个ddns做转发，非常方便，点赞！
建议在你的docker hub和github上面添加链接，推广这个项目。
dockerHub添加：https://github.com/jeessy2/ddns-go
github的readme添加：https://hub.docker.com/r/jeessy/ddns-go

**Comment by jeessy2** [comment]
感谢支持。不过github的readme会通过actions自动同步到docker hub的readme，就没必要加了

**Comment by hjkl950217** [comment]
docker hub可以加的，许多玩nas的他们并不一定会玩github，可能是通过一些教程和视频知道了ddns_go，直接去拉镜像，就不会来github这边

**Comment by jeessy2** [comment]
随缘

**Comment by jeessy2** [comment]
里面有链接的，可以跳到github上。主要是通过actions自动同步到docker hub的readme，两边是保持一致的
