### ISSUE TITLE
[Bug]：未能获取IPv4地址, 将不会更新

### ISSUE THREAD

**Issue by XKaguya** [jeessy2/ddns-go#717]
### 问题描述

部署后报错
2023/06/02 10:19:48 可使用 .\ddns-go.exe -s install 安装服务运行
2023/06/02 10:19:48 第一次运行将等待 20 秒后运行 (等待网络)
2023/06/02 10:19:48 监听 :9876 ...
2023/06/02 10:20:08 未能获取IPv4地址, 将不会更新
更换过获取IP的网站，还是报错。
使用浏览器自行访问是都可以获取IP的，但是程序就是报错无法获取

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### ddns-go 版本

v5.3.1

### 安装方式

其它

### 额外信息

2023/06/02 10:19:48 可使用 .\ddns-go.exe -s install 安装服务运行
2023/06/02 10:19:48 第一次运行将等待 20 秒后运行 (等待网络)
2023/06/02 10:19:48 监听 :9876 ...
2023/06/02 10:20:08 未能获取IPv4地址, 将不会更新

**Comment by WaterLemons2k** [comment]
看一下配置文件。

**Comment by XKaguya** [comment]
> 看一下配置文件。

不清楚配置文件在哪，我截图一个web配置
![image](https://github.com/jeessy2/ddns-go/assets/96401952/a618db9b-1622-4c1b-a9e3-cc28e89907d6)
![image](https://github.com/jeessy2/ddns-go/assets/96401952/979d5b29-7487-45b3-b2d9-200e82985b6d)
![image](https://github.com/jeessy2/ddns-go/assets/96401952/b24c019f-8f93-4ff7-ad41-1e572dfde4f6)

**Comment by WaterLemons2k** [comment]
配置文件 默认位于当前用户目录下的 `.ddns_go_config.yaml` 文件中，保存时也会输出 `配置文件已保存在: `。

**Comment by XKaguya** [comment]
> 配置文件 默认位于当前用户目录下的 `.ddns_go_config.yaml` 文件中，保存时也会输出 `配置文件已保存在: `。

谢谢提醒，这是配置文件的内容：
![image](https://github.com/jeessy2/ddns-go/assets/96401952/431cf9c7-4404-4cec-ac7b-1c0a6c4b2034)

**Comment by WaterLemons2k** [comment]
少行 `gettype: url`

```yaml
ipv4:
  enable: true
  gettype: url
```

**Comment by XKaguya** [comment]
> 少行 `gettype: url`
> 
> ```yaml
> ipv4:
>   enable: true
>   gettype: url
> ```

谢谢，问题解决了，但是新问题来了
2023/06/02 12:37:34 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"2E8DDB26-2270-530E-8F0E-0CA18BE2176D","Message":"Specified access key is not found or invalid.","Recommend":"https://api.aliyun.com/troubleshoot?q=InvalidAccessKeyId&product=Alidns","HostId":"alidns.aliyuncs.com","Code":"InvalidAccessKeyId"} ,返回状态码: 404
不知道为什么说我的Access Key无效，我是根据网页的指引申请的

**Comment by XKaguya** [comment]
> 少行 `gettype: url`
> 
> ```yaml
> ipv4:
>   enable: true
>   gettype: url
> ```

解决了，是网页给配置文件的Access Key加了2个空格，删除就可以用了，感谢
