### ISSUE TITLE
[功能]：希望增加对 macOS 上 Homebrew 包管理器安装方式的支持

### ISSUE THREAD

**Issue by Mrered** [jeessy2/ddns-go#721]
### 功能描述

这里有一个国人维护的小小的 [Homebrew](https://brew.sh/) 包管理器安装脚本仓库，我在对方仓库开了 [issue](https://github.com/ivaquero/homebrew-chinese/issues/23) 。

感谢作者！

### 解决的问题

如题

### 附加信息

[Formula Cookbook — Homebrew Documentation](https://docs.brew.sh/Formula-Cookbook) 是 Homebrew 官方提供的 Ruby 脚本编写指南。

**Comment by jeessy2** [comment]
可以直接安装为服务。homebrew需要对方来吧？

**Comment by Mrered** [comment]
感谢@WaterLemons2k 大佬的支持🥹
