### ISSUE TITLE
[Bug]：极空间nas 通过docker没发启动

### ISSUE THREAD

**Issue by YangHaHabiu** [jeessy2/ddns-go#723]
### 问题描述

启动时报
network host is ambiguous (2 matches found on name)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

i386

### ddns-go 版本

latest

### 安装方式

Docker

### 额外信息

**network host is ambiguous (2 matches found on name)**

**Comment by WaterLemons2k** [comment]
删除所有未使用的网络：

```shell
docker network prune
```

参考：https://stackoverflow.com/questions/63776518/error-2-matches-found-based-on-name-network-nameofservice-default-is-ambiguo

**Comment by YangHaHabiu** [comment]
已解决,我重置了一下docker重新部署ok了
