### ISSUE TITLE
[Bug]：域名更新失败

### ISSUE THREAD

**Issue by ncy92** [jeessy2/ddns-go#724]
### 问题描述

![12345](https://github.com/jeessy2/ddns-go/assets/76580423/b922b530-f020-4976-a310-486a417beb2e)
![企业微信截图_16859308542393](https://github.com/jeessy2/ddns-go/assets/76580423/82cef5bc-c3eb-4db6-ad55-1680a39a9237)

我晚上用ddns-go设置访问正常设备没有断电，从晚上1:00一直发这个通知然后外网访问不到页面，威联通myqnapcloud里面看的IP是没有变的还是图里的IP，这是什么问题

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

latest

### 安装方式

Docker

**Comment by jeessy2** [comment]
看日志。有可能是接口请求失败

**Comment by qq289531426** [comment]
同样的，接口请求失败，不知道怎么处理

**Comment by ncy92** [comment]
> 同样的，接口请求失败，不知道怎么处理

也是NAS？

**Comment by qq289531426** [comment]
> > 同样的，接口请求失败，不知道怎么处理
> 
> 也是NAS？

是的，安装在nas下的docker容器内

**Comment by ncy92** [comment]
> > > 同样的，接口请求失败，不知道怎么处理
> > 
> > 
> > 也是NAS？
> 
> 是的，安装在nas下的docker容器内

是威联通还是其他的，是用的ipv6，看一下你网卡接口IP对不对

**Comment by qq289531426** [comment]
> > > > 同样的，接口请求失败，不知道怎么处理
> > > 
> > > 
> > > 也是NAS？
> > 
> > 
> > 是的，安装在nas下的docker容器内
> 
> 是威联通还是其他的，是用的ipv6，看一下你网卡接口IP对不对

群晖，开启ipv4，接口获取，默认有网址，ipv6我都不启用的。
https://cto.jinds918.store:2443/images/2023/06/11/1686463947313.png

**Comment by qq289531426** [comment]
[https://cto.jinds918.store:2443/images/2023/06/11/1686463947313.png](url)

**Comment by ncy92** [comment]
> > > > > 同样的，接口请求失败，不知道怎么处理
> > > > 
> > > > 
> > > > 也是NAS？
> > > 
> > > 
> > > 是的，安装在nas下的docker容器内
> > 
> > 
> > 是威联通还是其他的，是用的ipv6，看一下你网卡接口IP对不对
> 
> 群晖，开启ipv4，接口获取，默认有网址，ipv6我都不启用的。 https://cto.jinds918.store:2443/images/2023/06/11/1686463947313.png

你ddnsgo选的什么网络模式

**Comment by qq289531426** [comment]
> 

bridge,是不是要改成host呢？

**Comment by nixingshiguang** [comment]
我也遇到了同样的问题，环境：黑群晖，docker部署，host模式，获取到的IP没问题的，而且也没变，但是频繁提示以下错误
```
2023/06/20 08:15:21 请求接口https://api.cloudflare.com/client/v4/zones?name=***.eu.org&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=***.eu.org&status=active&per_page=50": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by qq289531426** [comment]
试过使用host网络类型，也是频繁提示错误

**Comment by jeessy2** [comment]
> 我也遇到了同样的问题，环境：黑群晖，docker部署，host模式，获取到的IP没问题的，而且也没变，但是频繁提示以下错误
> 
> ```
> 2023/06/20 08:15:21 请求接口https://api.cloudflare.com/client/v4/zones?name=***.eu.org&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=***.eu.org&status=active&per_page=50": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> ```

cloudflare接口超时，在国内算正常的，可以换到其它服务商

**Comment by magictomagic** [comment]
我也遇到了同样的问题，但是已经开了翻墙了啊
```
"https://api.cloudflare.com/client/v4/zones?name=magictomagic.com&status=active&per_page=50": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024/02/10 20:07:47 查询域名信息发生异常! Get "https://api.cloudflare.com/client/v4/zones?name=magictomagic.com&status=active&per_page=50": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by magictomagic** [comment]
楼上可能是令牌创建错误，点cloudfare上面的创建令牌试试
