### ISSUE TITLE
[Bug]：使用华为云DNS，在需要更新IP的时候，没有成功，日志返回的是新增失败

### ISSUE THREAD

**Issue by solidsnake6023** [jeessy2/ddns-go#727]
### 问题描述

我使用的是威联通的NAS，型号464C，我在ContainerStation里安装了DDNS-GO，连接的是华为云DNS，设置好之后，如果华为云DNS解析里面没有目标域名，日志会提示新增域名成功，实际也成功了。但是，如果华为云DNS解析里面目标域名已经存在的场合，比如发现IP变化了需要更新IP，就没有成功，日志提示的是域名新增发生冲突。请问是不是更新的时候，调用成了新增的接口或者参数呢？

【日志】
2023/06/07 08:41:42 请求接口 https://dns.myhuaweicloud.com/v2/zones/8aace3b9656311c1016584d2b7461446/recordsets 失败! 返回内容: {"code":"DNS.0312","message":"Attribute 'name' conflicts with Record Set 'www.****.com.' type 'A' in line 'default_view'."} ,返回状态码: 400

2023/06/07 08:41:42 新增域名解析 www.****.com 失败！Status: 

【华为云DNS解析的截图】
![image](https://github.com/jeessy2/ddns-go/assets/43085422/8af6a189-bcf5-4aab-8651-4c09b993d41b)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

v5.3.2

### 安装方式

Docker

**Comment by jeessy2** [comment]
经测正常，截图看下你是怎么配置的

**Comment by solidsnake6023** [comment]
你好，谢谢。我刚再试了一下，更新IP成功了。这次我进行了以下2个操作：
1、先手动在华为云DNS解析里，添加上需要的域名（之前是通过DDNS-GO自动添加的）。
2、把DDNS-GO里设置的目标域名，改成全部小写的（之前是大小写混合的，华为云DNS解析里的全是小写）。

感觉是“操作2”起了作用…… 难道华为云DNS解析的接口里，区分了大小写？……

**Comment by jeessy2** [comment]
域名只有小写，没有大写。大写提交到华为云也会自动转为小写
混合大小写会匹配不上

**Comment by solidsnake6023** [comment]
是的，域名是本来只有小写，但平时日常使用时，大小写也不区分的，所以设置的时候，就按域名的单词意思写成了大小写的。
刚又试了一遍，确实就是大小写的原因，就是你说的“混合大小写会匹配不上”。

谢谢哈~~
