### ISSUE TITLE
[Bug]：服务时区问题导致无法获取地址及更新dns

### ISSUE THREAD

**Issue by zzcabc** [jeessy2/ddns-go#729]
### 问题描述

在immortalwrt 2305的版本中，安装`zoneinfo-asia`，打印时间均为Asia/Shanghai的时区，在ddns-go的内部日志是世界标准时，导致无法获取ip地址，及更新ddns

在immortalwrt 2102版本中，与2305版本保持一样的插件运行得到Asia/Shanghai的时区，此时可以正常通过网页获取ip并更新域名ip

在issue查询到的内容均无法有效解决问题

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

5.2.1-1

### 安装方式

服务

### 额外信息

测试时间为2023年6月7日 20点05分

```
2023/06/07 12:05:58 连接失败! <a target='blank' href='https://speed.neu6.edu.cn/getIP.php'>点击查看接口能否返回IPv6地址</a>, 参考说明:<a target='blank' href='https://github.com/jeessy2/ddns-go#使用ipv6'>点击访问</a>
2023/06/07 12:05:58 错误信息: Get "https://speed.neu6.edu.cn/getIP.php": tls: failed to verify certificate: x509: certificate signed by unknown authority
2023/06/07 12:05:59 连接失败! <a target='blank' href='https://v6.ident.me'>点击查看接口能否返回IPv6地址</a>, 参考说明:<a target='blank' href='https://github.com/jeessy2/ddns-go#使用ipv6'>点击访问</a>
2023/06/07 12:05:59 错误信息: Get "https://v6.ident.me": tls: failed to verify certificate: x509: certificate signed by unknown authority
2023/06/07 12:05:59 连接失败! <a target='blank' href='https://6.ipw.cn'>点击查看接口能否返回IPv6地址</a>, 参考说明:<a target='blank' href='https://github.com/jeessy2/ddns-go#使用ipv6'>点击访问</a>
2023/06/07 12:05:59 错误信息: Get "https://6.ipw.cn": tls: failed to verify certificate: x509: certificate signed by unknown authority
2023/06/07 12:05:59 未能获取IPv6地址, 将不会更新
```

**Comment by zzcabc** [comment]
> ```shell
> cat /etc/localtime
> ```

可以看到是CST-8
```
TZif2
     yY^        pӽ|@;>Ӌ{BE"L<fpA|R i ~!I}"g #)_$G %|&'e &^(G (@q~LMTCDTCSTTZif2
                                                                               ~6C)yY^  pӽ|@;>Ӌ{BE"L<fpA|R i ~!I}"g #)_$G %|&'e &^(G (@q~LMTCDTCST
CST-8
```

**Comment by WaterLemons2k** [comment]
> 可以看到是CST-8
> 
> ```
> TZif2
>      yY^        pӽ|@;>Ӌ{BE"L<fpA|R i ~!I}"g #)_$G %|&'e &^(G (@q~LMTCDTCSTTZif2
>                                                                                ~6C)yY^  pӽ|@;>Ӌ{BE"L<fpA|R i ~!I}"g #)_$G %|&'e &^(G (@q~LMTCDTCST
> CST-8
> ```

试一下这个时区文件：

```shell
wget https://github.com/WaterLemons2k/tzdata/raw/main/Asia/Shanghai -O /etc/localtime
```

**Comment by zzcabc** [comment]
导入重启依旧是不正确的时间

**Comment by WaterLemons2k** [comment]
> 导入重启依旧是不正确的时间

看一下系统里有哪些变量：

```shell
env
```

**Comment by zzcabc** [comment]
> ```shell
> env
> ```

```
SHELL=/bin/bash
ENV=/etc/shinit
PWD=/usr/bin
LOGNAME=root
HOME=/root
TERM=xterm-256color
USER=root
SHLVL=1
PS1=\[\e]0;\u@\h: \w\a\]\u@\h:\w\$ 
PATH=/usr/sbin:/usr/bin:/sbin:/bin
OLDPWD=/usr
_=/usr/bin/env
```

**Comment by WaterLemons2k** [comment]
看一下 `/etc/config/system`：

```shell
cat /etc/config/system
```

**Comment by zzcabc** [comment]
```
config system
        option hostname 'ImmortalWrt'
        option ttylogin '0'
        option log_size '2048'
        option urandom_seed '0'
        option timezone 'CST-8'
        option zonename 'Asia/Shanghai'
        option log_proto 'udp'
        option conloglevel '8'
        option cronloglevel '5'

config timeserver 'ntp'
        option enable_server '1'
        list server 'ntp.tencent.com'
        list server 'ntp1.aliyun.com'
        list server 'ntp.ntsc.ac.cn'
        list server 'cn.ntp.org.cn'
```


提一句go可以以参数的形式传入时区吗 `ddns-go TZ=Asia/Shanghai`这样的

**Comment by WaterLemons2k** [comment]
> ```
> config system
>         option hostname 'ImmortalWrt'
>         option ttylogin '0'
>         option log_size '2048'
>         option urandom_seed '0'
>         option timezone 'CST-8'
>         option zonename 'Asia/Shanghai'
>         option log_proto 'udp'
>         option conloglevel '8'
>         option cronloglevel '5'
> 
> config timeserver 'ntp'
>         option enable_server '1'
>         list server 'ntp.tencent.com'
>         list server 'ntp1.aliyun.com'
>         list server 'ntp.ntsc.ac.cn'
>         list server 'cn.ntp.org.cn'
> ```

参考 https://openwrt.org/docs/guide-user/base-system/system_configuration ，`timezone` 是不是应该这么写：

```
option timezone 'Asia/Shanghai'
```

**Comment by jeessy2** [comment]
> > > 提一句go可以以参数的形式传入时区吗 `ddns-go TZ=Asia/Shanghai`这样的
> > 
> > 
> > 可以。 #730
> > ```shell
> > ./ddns-go -tz Asia/Shanghai
> > ```
> 
> 在openwrt中timezone是这样的CST-8 (For London this corresponds to GMT0BST,M3.5.0/1,M10.5.0)
> 
> ```
> 	{ 'Asia/Shanghai', 'CST-8' },
> ```

这样设置能用否，能用就不改代码

**Comment by zzcabc** [comment]
> > > > 提一句go可以以参数的形式传入时区吗 `ddns-go TZ=Asia/Shanghai`这样的
> > > 
> > > 
> > > 可以。 #730
> > > ```shell
> > > ./ddns-go -tz Asia/Shanghai
> > > ```
> > 
> > 
> > 在openwrt中timezone是这样的CST-8 (For London this corresponds to GMT0BST,M3.5.0/1,M10.5.0)
> > ```
> > 	{ 'Asia/Shanghai', 'CST-8' },
> > ```
> 
> 这样设置能用否，能用就不改代码

我尝试在ddns-go.inid.d加入`procd_set_param env TZ="Asia/Shanghai"  # 给进程传递环境变量`,，也并没有成功的设置时区，仅测试通过是使用`TZ=Asia/Shanghai ddns-go` 可以更改时区，不排除是2305版本导致问题，另外值得不能理解的一点是我看了Clash的源码，也并没有设置时区，而它的时区是正确的

**Comment by WaterLemons2k** [comment]
https://github.com/golang/go/blob/b9baf4452fe949a5a159eec4d4a437ad2833ead1/src/time/zoneinfo_unix.go#L29-L44

理想情况下，如果存在变量 `TZ` 则使用 `TZ` 的值，否则使用 `/etc/localtime`，最后使用 `UTC`。

所以先清除变量 `TZ`，再将 `Asia/Shanghai` 软链接到 `/etc/localtime`：

```shell
unset TZ
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
./ddns-go
```

另外如果可以的话，使用 `zdump` 或 `file` 查看 `/etc/localtime` 的内容：

```shell
zdump /etc/localtime
file /etc/localtime
```

参考：
- coolsnowwolf/lede#5700
- AdguardTeam/AdGuardHome#3482
- https://unix.stackexchange.com/questions/85925/how-can-i-examine-the-contents-of-etc-localtime

**Comment by zzcabc** [comment]
直接运行是没有问题的，已luci的形式就无法正常使用，已经转为服务模式，放弃了

**Comment by zzcabc** [comment]
问题提交至immortalwrt/package下

修改 /etc/init.d/ddns-go
在 procd_add_jail_mount_rw 下面加上：
```
procd_add_jail_mount "/etc/localtime"
procd_add_jail_mount "/etc/ssl/"
```

经测试为有效，此方法目前仅适用于immortalwrt版本，其它版本未测试

**Comment by 1715173329** [comment]
TL;DR; 因为 ujail 规则导致 ddns-go 无法访问时区及证书文件

**Comment by qq289531426** [comment]
试过更新到5.3.5的版本，还是一样错误，应该是dns服务商的问题了吧，但是却不知道问题在哪里，只能先关掉提醒了

**Comment by jeessy2** [comment]
fix by: https://github.com/immortalwrt/packages/commit/7ff9e95f9b6c9d555ebe2e6d3f587fd9e1fe08fa

**Comment by xiaohao5812** [comment]
> 问题提交至immortalwrt/package下
> 
> 修改 /etc/init.d/ddns-go 在 procd_add_jail_mount_rw 下面加上：
> 
> ```
> procd_add_jail_mount "/etc/localtime"
> procd_add_jail_mount "/etc/ssl/"
> ```
> 
> 经测试为有效，此方法目前仅适用于immortalwrt版本，其它版本未测试

请问 我找不到 procd_add_jail_mount "/etc/localtime"
> procd_add_jail_mount "/etc/ssl/"
我的ddns-go文件里面没有这两行

**Comment by xiaohao5812** [comment]
> 问题提交至immortalwrt/package下
> 
> 修改 /etc/init.d/ddns-go 在 procd_add_jail_mount_rw 下面加上：
> 
> ```
> procd_add_jail_mount "/etc/localtime"
> procd_add_jail_mount "/etc/ssl/"
> ```
> 
> 经测试为有效，此方法目前仅适用于immortalwrt版本，其它版本未测试

我的ddns-go文件里面是这样的
#!/bin/sh /etc/rc.common
# Copyright (C) 2023 ImmortalWrt.org

START=99
USE_PROCD=1

CONF="ddns-go"
YAML="/etc/$CONF/config.yaml"
PROG="/usr/bin/$CONF"

start_service() {
	config_load "$CONF"

	local enabled
	config_get_bool enabled "config" "enabled" "0"
	[ "$enabled" -eq "1" ] || return 1

	local listen ttl noweb insecure
	config_get listen "config" "listen" "[::]:9876"
	config_get ttl "config" "ttl" "300"
	config_get_bool noweb "config" "noweb" "0"
	config_get_bool insecure "config" "insecure" "0"

	[ -d "${YAML%/*}" ] || mkdir -p "${YAML%/*}"
	touch "$YAML"
	chown ddns-go "$YAML"

	procd_open_instance "$CONF"
	procd_set_param command "$PROG"
	procd_append_param command -c "$YAML"
	procd_append_param command -l "$listen"
	procd_append_param command -f "$ttl"
	[ "$noweb" -eq "0" ] || procd_append_param command -noweb
	[ "$insecure" -eq "0" ] || procd_append_param command -skipVerify

	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param user ddns-go

	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}

**Comment by zzcabc** [comment]
可以直接在`procd_set_param user ddns-go` 下面一行添加
```conf
	procd_add_jail_mount "/etc/localtime"
	procd_add_jail_mount "/etc/TZ"
	procd_add_jail_mount "/etc/ssl/"
```

我看immortalwrt/package的提交日志不知为何移除了这段代码，现在不保证是否有效

**Comment by xiaohao5812** [comment]
> 可以直接在 下面一行添加`procd_set_param user ddns-go`
> 
> ```
> 	procd_add_jail_mount "/etc/localtime"
> 	procd_add_jail_mount "/etc/TZ"
> 	procd_add_jail_mount "/etc/ssl/"
> ```
> 
> 我看immortalwrt/package的提交日志不知为何移除了这段代码，现在不保证是否有效

无效，依然时区不对。。。

**Comment by xiaohao5812** [comment]
> 修复者：[immortalwrt/packages@7ff9e95](https://github.com/immortalwrt/packages/commit/7ff9e95f9b6c9d555ebe2e6d3f587fd9e1fe08fa)

问题依然没有解决，
ImmortalWrt 23.05.3 r27917-81a1f98d5b / LuCI openwrt-23.05 branch git-24.092.44091-d24c2e3
内核版本 |5.15.162

ddns-go版本，6.7.0
![Uploading 屏幕截图 2024-09-08 085817.png…]()

**Comment by xiaohao5812** [comment]
> 可以直接在 下面一行添加`procd_set_param user ddns-go`
> 
> ```
> 	procd_add_jail_mount "/etc/localtime"
> 	procd_add_jail_mount "/etc/TZ"
> 	procd_add_jail_mount "/etc/ssl/"
> ```
> 
> 我看immortalwrt/package的提交日志不知为何移除了这段代码，现在不保证是否有效

已经找到解决方法了，安装zoneinfo-asia 这个软件包，重启路由器就解决了。特地回来告诉你

**Comment by jforce757** [comment]
> > 可以直接在 下面一行添加`procd_set_param user ddns-go`
> > ```
> > 	procd_add_jail_mount "/etc/localtime"
> > 	procd_add_jail_mount "/etc/TZ"
> > 	procd_add_jail_mount "/etc/ssl/"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我看immortalwrt/package的提交日志不知为何移除了这段代码，现在不保证是否有效
> 
> 已经找到解决方法了，安装zoneinfo-asia 这个软件包，重启路由器就解决了。特地回来告诉你

问题解决
