### ISSUE TITLE
需求: 支持自定义网站根目录

### ISSUE THREAD

**Issue by nidbCN** [jeessy2/ddns-go#73]
如图，ddns-go不支持自定义配置网站的根目录
[![27UtR1.png](https://z3.ax1x.com/2021/06/14/27UtR1.png)](https://imgtu.com/i/27UtR1)
希望能够支持

**Comment by jeessy2** [comment]
-l 是监听地址，不符合要求。
目前不支持自定义配置网站的根目录，这个有什么实际用处吗

**Comment by nidbCN** [comment]
我自己modify一个吧，貌似确实没有什么广泛的实际用途（x

**Comment by jeessy2** [comment]
好的，其实没有用处的。
