### ISSUE TITLE
[功能]：希望增加Qnap威联通NAS通过Docker Compose安装的说明

### ISSUE THREAD

**Issue by petercham** [jeessy2/ddns-go#731]
### 功能描述

因为docker hub已经无法连接，但是QNAP提供了Docker Compose编写YAML的方式自己编辑，如果能把具体的配置方式放进Readme，将解决非常多国人的问题

### 解决的问题

Docker hub上的镜像无法连接

### 附加信息

可以通过Docker Compose编写YAML配置来解决

**Comment by jeessy2** [comment]
能用docker hub的镜像，如果有不能连接，用Docker Compose编写YAML配置这个也不能解决吧

**Comment by ccdos** [comment]
version: '3'

services:
  ddns-go:
    image: jeessy/ddns-go
    container_name: ddns-go
    volumes:
      - /volume1/docker/ddns-go/.ddns_go_config.yaml:/root/.ddns_go_config.yaml
    restart: always
    network_mode: "host"
