### ISSUE TITLE
[Bug]：私有地址访问ddsn-go服务时被拒绝

### ISSUE THREAD

**Issue by Crazy-FuQing** [jeessy2/ddns-go#733]
### 问题描述

![image](https://github.com/jeessy2/ddns-go/assets/46838021/b8d3f005-19b6-45b0-9ab6-989f6e360087)
在局域网中的群辉上部署了ddsn-go服务，但是开启“禁止从公网访问“功能时，用局域网中的电脑也无法访问

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

5.2.2

### 安装方式

Docker

**Comment by WaterLemons2k** [comment]
ddns-go 的 域名或 IP 是什么？

不支持通过非 `localhost` 域名访问，详见 https://github.com/jeessy2/ddns-go/wiki/FAQ#开启-禁止公网访问-后无法通过域名访问

参考：#495、#622。

**Comment by Crazy-FuQing** [comment]
可是这样也能被绕过的，限制源IP应该能安全点，当然 最好别放在公网
![image](https://github.com/jeessy2/ddns-go/assets/46838021/6db7d96c-d1be-48d7-839e-af61ef7d803d)

**Comment by jeessy2** [comment]
> 可是这样也能被绕过的，限制源IP应该能安全点，当然 最好别放在公网
> 
> ![image](https://github.com/jeessy2/ddns-go/assets/46838021/6db7d96c-d1be-48d7-839e-af61ef7d803d)
> 
> 

IP和Host都限制了的。多加一个Host限制，考虑到通过nginx转发后，让用户必须设置密码才能访问

**Comment by Crazy-FuQing** [comment]
> > 可是这样也能被绕过的，限制源IP应该能安全点，当然 最好别放在公网
> > ![image](https://user-images.githubusercontent.com/46838021/244441454-6db7d96c-d1be-48d7-839e-af61ef7d803d.png)
> 
> IP和Host都限制了的。多加一个Host限制，考虑到通过nginx转发后，让用户必须设置密码才能访问

IP和Host这些判断都没有用，会被绕过。设置密码可以解决，目前版本还是建议大家设置密码使用
![image-20230609105342036](https://cdn.jsdelivr.net/gh/Crazy-FuQing/image/image-20230609105342036.png)

**Comment by jeessy2** [comment]
访问的IP是内网IP，你内网访问当然没有y用了

**Comment by Crazy-FuQing** [comment]
> 

是的 ，但是有些人的公网映射是通过端口转发实现的，在这种情况下ip限制会失效

**Comment by jeessy2** [comment]
> > 
> 
> 
> 
> 是的 ，但是有些人的公网映射是通过端口转发实现的，在这种情况下ip限制会失效

这种就配置失误了，所以校验Host提示拒绝访问，让配置密码。不然，通过修改Host是可以访问的

**Comment by GuyCui** [comment]
> > > 但是这样也能被绕过的，限制源IP应该能安全点，当然最好别放在公网
> > > ![图像](https://user-images.githubusercontent.com/46838021/244441454-6db7d96c-d1be-48d7-839e-af61ef7d803d.png)
> > 
> > 
> > IP和主机都限制了。多加一个主机限制，考虑到通过nginx转发后，让用户必须设置密码才能访问
> 
> 感谢回复，刚才仔细看了一下，IP和主机这些判断都没有用，都可能被绕过。设置密码可以解决，目前版本还是建议大家设置密码使用 ![图片-20230609105342036](https://camo.githubusercontent.com/195cd02cf0a4bbee74f214b4376d5ee6080547fcfeb88a7c94c3f5824051fc81/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f4372617a792d467551696e672f696d6167652f696d6167652d32303233303630393130353334323033362e706e67)

这个是什么插件

**Comment by Crazy-FuQing** [comment]
> 这个是什么插件

**Comment by Crazy-FuQing** [comment]
> > > > 但是这样也能被绕过的，限制源IP应该能安全点，当然最好别放在公网
> > > > ![图像](https://user-images.githubusercontent.com/46838021/244441454-6db7d96c-d1be-48d7-839e-af61ef7d803d.png)
> > > 
> > > 
> > > IP和主机都限制了。多加一个主机限制，考虑到通过nginx转发后，让用户必须设置密码才能访问
> > 
> > 
> > 感谢回复，刚才仔细看了一下，IP和主机这些判断都没有用，都可能被绕过。设置密码可以解决，目前版本还是建议大家设置密码使用 ![图片-20230609105342036](https://camo.githubusercontent.com/195cd02cf0a4bbee74f214b4376d5ee6080547fcfeb88a7c94c3f5824051fc81/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f4372617a792d467551696e672f696d6167652f696d6167652d32303233303630393130353334323033362e706e67)
> 
> 这个是什么插件

ModHeader
