### ISSUE TITLE
[功能]：使用 `time.Tick` 定时运行

### ISSUE THREAD

**Issue by WaterLemons2k** [jeessy2/ddns-go#734]
### 功能描述

使用 `time.Tick` 运行 `RunTimer`，也就是将 `time.Sleep` 更改为 `time.Tick`：

```go
RunOnce()

for range time.Tick(delay) {
	RunOnce()
}
```

### 解决的问题

`time.Tick` 根据需要调整间隔或跳过：

假设同步间隔时间为 10 秒，执行 `RunOnce` 5 秒：

1. 使用 `time.Sleep`：执行 `RunOnce` 5 秒，等待 10 秒。每 15 秒执行一次。

2. 使用 `time.Tick`：执行 `RunOnce` 5 秒，Ticker 调整为等待 5 秒。每 10 秒执行一次。

### 附加信息

- https://pkg.go.dev/time#Tick
- https://stackoverflow.com/questions/53315716/which-one-of-the-two-is-idiomatic-way-time-sleep-or-ticker

**Comment by jeessy2** [comment]
有些间隔很小的，如1s，用Tick有点忙不过来
