### ISSUE TITLE
[功能]：腾讯云已经升级DNSPod API到3.0版本了，且2.0版本即将下线

### ISSUE THREAD

**Issue by petercham** [jeessy2/ddns-go#735]
### 功能描述

https://docs.dnspod.cn/notices/api-2-upgrade/
本次升级需用户自行检查原云解析 API 2.0 并参照指引和云解析 API 3.0 重新接入。不支持自动升级。
辛苦大佬，能否尽快更新3.0API的版本？

### 解决的问题

腾讯云DNSPod API升级导致projectId参数失效

**Comment by WaterLemons2k** [comment]
已升级，使用 `腾讯云`。

见 #713。
