### ISSUE TITLE
[Bug]：-dns参数没有效果

### ISSUE THREAD

**Issue by windanan** [jeessy2/ddns-go#736]
### 问题描述

这软件很好。不过在使用过程中，遇到点小问题
在`Termux`中启动`ddns-go`后，会报错。见日志。试图使用`-dns`参数，但没有效果。

> 开户手机热点，可临时解决问题。

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### ddns-go 版本

v5.3.3

### 安装方式

其它

### 额外信息

2023/06/13 07:04:43 等待网络连接：Get "https://dnsapi.cn/Record.List": dial tcp: lookup dnsapi.cn on [::1]:53: read udp [::1]:59467->[::1]:53: read: connection refused。5s 后重试...
2023/06/13 07:04:48 等待网络连接：Get "https://domains.google.com/nic/update": dial tcp: lookup domains.google.com on [::1]:53: read udp [::1]:40555->[::1]:53: read: connection refused。5s 后重试...
2023/06/13 07:04:53 等待网络连接：Get "https://dns.myhuaweicloud.com": dial tcp: lookup dns.myhuaweicloud.com on [::1]:53: read udp [::1]:56781->[::1]:53: read: connection refused。5s 后重试...

**Comment by WaterLemons2k** [comment]
https://github.com/jeessy2/ddns-go/blob/8e5ba0a3993f8bc3a32da03dcec12e15197e0858/dns/wait_net.go#L29

定时运行前会检查网络是否连接，但用于测试的 `http.Get` 并不会指定 DNS 解析器。

由 #737 修复。
