### ISSUE TITLE
[功能]：DNS ID Label 为空时隐藏输入框

### ISSUE THREAD

**Issue by WaterLemons2k** [jeessy2/ddns-go#738]
### 功能描述

https://github.com/jeessy2/ddns-go/blob/841031505bedb5e4023d52e5e994d476c49b76d2/web/writing.html#L537-L538

`dnsInfo.idLabel` 为空时可以 **隐藏** `DnsID`，因为此时显示这个输入框是多余的。

### 解决的问题

避免显示对用户无用的输入框。

### 附加信息

[hidden - HTML（超文本标记语言） | MDN](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/hidden)

**Comment by jeessy2** [comment]
可以的
