### ISSUE TITLE
[功能]：自动更新 Homebrew 的 ddns-go

### ISSUE THREAD

**Issue by WaterLemons2k** [jeessy2/ddns-go#740]
### 功能描述

从 #721 起添加了对 Homebrew 的支持，所以现在可以尝试使用 [Bump formulae GitHub Action](https://github.com/Homebrew/actions/tree/master/bump-formulae) 更新 Homebrew 的 ddns-go。

### 解决的问题

让 Homebrew 的 ddns-go 保持最新。

### 附加信息

- https://github.com/Homebrew/actions/tree/master/bump-formulae
- https://github.com/SmartThingsCommunity/smartthings-cli/blob/1fc95b8d18bdcb4ab02438c35527ea3146089ef5/.github/workflows/cd.yaml#L213-L217
- https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/autobump.yml

**Comment by jeessy2** [comment]
可以

**Comment by Mrered** [comment]
感谢 @WaterLemons2k ！因官方库已收录，我将 [ivaquero/homebrew-chinese: 🀄 一个致力于服务国人的 Homebrew 🍺 第三方库](https://github.com/ivaquero/homebrew-chinese) 中的 ddns-go 移除。
