### ISSUE TITLE
[Bug]：Callback返回数据“no chag”，Webhook发送Telegram信息仍显示结果为“成功”

### ISSUE THREAD

**Issue by MononeV** [jeessy2/ddns-go#742]
### 问题描述

对Dynu使用Callback方式更新ipv4，Webhook直接使用Telegram bot API发送消息。每次重启容器或保存配置后会收到消息，显示ipv4更新成功（使用#{ipv4Result}变量），但实际IP并未改变，并且日志显示Callback返回结果为“no chag”。

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

v5.3.5

### 安装方式

Docker

### 额外信息

![Snipaste_2023-06-17_19-22-27](https://github.com/jeessy2/ddns-go/assets/39477101/24c9956c-a10b-4e30-81f6-3ccefa1d7e72)
![Snipaste_2023-06-16_16-50-13](https://github.com/jeessy2/ddns-go/assets/39477101/e8652c85-d856-428b-a744-fae98839e596)
![Snipaste_2023-06-16_16-49-12](https://github.com/jeessy2/ddns-go/assets/39477101/3507b495-d67d-4d5a-b83e-41a85ad49ae4)

**Comment by jeessy2** [comment]
Callback通过返回的http状态码识别成功与否，不是通过返回的内容，callback支持的dns服务商很多，不会去识别内容的

**Comment by MononeV** [comment]
好的，和我预想的差不多，感谢解惑。
