### ISSUE TITLE
[功能]：请求通过socks5代理访问DDNS API

### ISSUE THREAD

**Issue by nzpb** [jeessy2/ddns-go#744]
### 功能描述

请求可以通过一个socks5代理（比如安装在同一台服务器上的翻墙软件）向各种ddns 的API请求。因为被墙是很可能的。

### 解决的问题

目前 api.cloudflare.com 已经被墙，其他外国DDNS API 被墙是时间问题。通过socks5 请求API可以解决这个问题。

**Comment by WaterLemons2k** [comment]
`ddns-go` 从变量获取代理，所以只需添加 `HTTPS_PROXY` 变量即可：

```sh
HTTPS_PROXY=socks5://127.0.0.1:7890 ./ddns-go
```

参考：
- https://pkg.go.dev/net/http#ProxyFromEnvironment
- #700

**Comment by nzpb** [comment]
有个问题啊，你这个全局添加socks5代理，会不会把 IP查询API 的get也代理了？ 这样会更新错误吧？

这里面有两个API，一个是CF的API，用于更新动态IP
另一个是获取本地IP的API，https://myip4.ipip.net 这样的 也走了socks5的话IP会变成梯子的IP。

**Comment by WaterLemons2k** [comment]
> 有个问题啊，你这个全局添加socks5代理，会不会把 IP查询API 的get也代理了？ 这样会更新错误吧？
> 
> 这里面有两个API，一个是CF的API，用于更新动态IP 另一个是获取本地IP的API，[myip4.ipip.net](https://myip4.ipip.net) 这样的 也走了socks5的话IP会变成梯子的IP。

https://github.com/jeessy2/ddns-go/blob/37c567b95786ebd63594d4181206f7a68e770619/config/config.go#L184-L185

https://github.com/jeessy2/ddns-go/blob/37c567b95786ebd63594d4181206f7a68e770619/config/config.go#L317-L318

从 URL 获取 IP 是不会用代理的。

**Comment by nzpb** [comment]
测试成功，感谢。这样就可以通过本地的翻墙软件来请求Cloudflare了。
