### ISSUE TITLE
[Bug]：DDNS-GO获取的是节点 的IP。通过命令获取中建议加入：curl 4.ipw.cn

### ISSUE THREAD

**Issue by loso3000** [jeessy2/ddns-go#745]
### 问题描述

DDNS-GO获取的是节点 的IP。通过命令获取中建议加入：curl 4.ipw.cn ,可以顺利到正确的IPV4 

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

v5.3.5

### 安装方式

Docker

**Comment by jeessy2** [comment]
没你的环境，自行研究

**Comment by WaterLemons2k** [comment]
有尝试过使用其它 API 吗？例如 http://whois.pconline.com.cn/ipJson.jsp
