### ISSUE TITLE
[Bug]：在手机荣耀8上无法正常运行

### ISSUE THREAD

**Issue by woshixiguapi** [jeessy2/ddns-go#746]
### 问题描述

在安卓手机荣耀8上的ddns-go_5.3.5_linux_arm64无法正常运行，日志文件已帖出，而且留意到日志的时间有误。同样的配置文件在win10系统下运行正常.为排除冲突原因，手机和电脑的ddns-go未同时运行。

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### ddns-go 版本

v5.3.5

### 安装方式

其它

### 额外信息

2023/06/21 02:10:24 可使用 sudo ./ddns-go -s install 安装服务运行
2023/06/21 02:10:24 监听 :9876 ...
2023/06/21 02:10:24 等待网络连接：Get "https://alidns.aliyuncs.com/": dial tcp: lookup alidns.aliyuncs.com on [::1]:53: read udp [::1]:44885->[::1]:53: read: connection refused。5s 后重试...
2023/06/21 02:10:29 等待网络连接：Get "https://bcd.baidubce.com": dial tcp: lookup bcd.baidubce.com on [::1]:53: read udp [::1]:59669->[::1]:53: read: connection refused。5s 后重试...
2023/06/21 02:10:34 等待网络连接：Get "https://api.cloudflare.com/client/v4/zones": dial tcp: lookup api.cloudflare.com on [::1]:53: read udp [::1]:40498->[::1]:53: read: connection refused。5s 后重试...
2023/06/21 02:10:39 等待网络连接：Get "https://dnsapi.cn/Record.List": dial tcp: lookup dnsapi.cn on [::1]:53: read udp [::1]:52541->[::1]:53: read: connection refused。5s 后重试...
2023/06/21 02:10:44 等待网络连接：Get "https://domains.google.com/nic/update": dial tcp: lookup domains.google.com on [::1]:53: read udp [::1]:54572->[::1]:53: read: connection refused。5s 后重试...

**Comment by WaterLemons2k** [comment]
缺失 DNS 服务器，添加选项 `-dns`：

```shell
./ddns-go -dns 1.1.1.1
```

参考：
- https://github.com/jeessy2/ddns-go/wiki/FAQ#%E4%BD%BF%E7%94%A8-android-%E8%BF%90%E8%A1%8C%E6%97%B6%E6%8A%A5%E9%94%99-153-read-connection-refused
- https://github.com/jeessy2/ddns-go/issues/672#issuecomment-1574041436
- #587
- #589
- #702

**Comment by woshixiguapi** [comment]
感谢，问题解决
