### ISSUE TITLE
[Bug]：在手机荣耀8上执行ddns-go -s install出错

### ISSUE THREAD

**Issue by woshixiguapi** [jeessy2/ddns-go#747]
### 问题描述

在手机荣耀8上执行ddns-go -s install出错，ERR: open /etc/init.d/ddns-go: no such file or directory，查了一下，手机系统下的确无init.d，有办法让ddns-go在安卓系统下以服务形式运行吗?

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### ddns-go 版本

v5.3.5

### 安装方式

服务

**Comment by WaterLemons2k** [comment]
Termux 可以尝试使用 [Termux-services](https://wiki.termux.com/wiki/Termux-services) 安装服务。

参考：
- https://github.com/jeessy2/ddns-go/issues/672#issuecomment-1574445575
- [https://zbttl-github-io.vercel.app/ma-que-sui-xiao-wu-zang-ju-quan-android-duan-terminal-termux-shang-shou-diao-xiao-zhi-nan/#应用自启](https://zbttl-github-io.vercel.app/ma-que-sui-xiao-wu-zang-ju-quan-android-duan-terminal-termux-shang-shou-diao-xiao-zhi-nan/#%E5%BA%94%E7%94%A8%E8%87%AA%E5%90%AF)

**Comment by woshixiguapi** [comment]
好的，谢谢你
