### ISSUE TITLE
解析出错

### ISSUE THREAD

**Issue by zyu211** [jeessy2/ddns-go#750]
### 问题描述

[Bug]在WIN10安装ddns-go服务，主域名为 xxxx.ha.cn，DDNS-GO配置域名xx.xxxx.ha.cn,阿里云解析添加A记录 xx，更新后aliyun A记录变为 xx.xxxx

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### ddns-go 版本

v5.3.6

### 安装方式

服务

**Comment by jeessy2** [comment]
用冒号分割主机记录

**Comment by zyu211** [comment]
DDNS-GO配置域名xx.xxxx.ha.cn,阿里云解析添加A记录 xx，更新后aliyun A记录变为 xx.xxxx，xx.xxxx.xxxx.ha.cn可以访问，等再次更新DDNS-GO日志显示失败，光猫重启重获取公网IP，无法更新，xx.xxxx.xxxx.ha.cn也无法访问，就是更新域名多了个xxxx

**Comment by WaterLemons2k** [comment]
https://github.com/jeessy2/ddns-go/blob/4d33865890bffebeebb1fe49f079d67c1d8c4625/config/domains.go#L12

除了上面固定的主域名，其余的所有域名都会被当成一级顶级域名。

所以这里处理域名时会把 `ha.cn` 当成主域名，`xx.xxxx` 当成子域名。

参考：https://help.aliyun.com/document_detail/35751.html#section-htk-ycd-b2b

**Comment by jeessy2** [comment]
`xx.xxxx.ha.cn` -> `xx.xxxx:ha.cn`
