### ISSUE TITLE
请问怎么安装？

### ISSUE THREAD

**Issue by wzy105** [jeessy2/ddns-go#754]
设备时openwrt ARMv7 怎么安装 tar.gz 后缀的安装包，小白只会安装ipk的

**Comment by WaterLemons2k** [comment]
连接到 SSH 或 Telnet 后按照 [系统中使用](https://github.com/jeessy2/ddns-go#%E7%B3%BB%E7%BB%9F%E4%B8%AD%E4%BD%BF%E7%94%A8) 安装服务即可：

```bash
wget https://github.com/jeessy2/ddns-go/releases/download/v5.3.6/ddns-go_5.3.6_linux_armv7.tar.gz
tar xvzf ddns-go_5.3.6_linux_armv7.tar.gz ddns-go
./ddns-go -s install
```

参考：https://github.com/jeessy2/ddns-go/discussions/694#discussioncomment-5822011

**Comment by wzy105** [comment]
> 

感谢w老师，这三行是分别输入运行吗

**Comment by WaterLemons2k** [comment]
> 感谢w老师，这三行是分别输入运行吗

全都粘贴到终端里运行就可以了。

**Comment by wzy105** [comment]
> > 感谢w老师，这三行是分别输入运行吗
> 
> 全都粘贴到终端里运行就可以了。

按你方法安装好openwrt里面没有看见界面，是因为没有luci吗

**Comment by WaterLemons2k** [comment]
> 按你方法安装好openwrt里面没有看见界面，是因为没有luci吗

确实没有 luci。默认监听 `:9876` 端口，所以只需要打开 `http://OpenWRT主机IP:9876` 就可以了。

**Comment by woshichenghaibo** [comment]
> > > 感谢w老师，这三行是分别输入运行吗
> > 
> > 
> > 全都粘贴到终端里运行就可以了。
> 
> 按你方法安装好openwrt里面没有看见界面，是因为没有luci吗

网上有现成的luci
