### ISSUE TITLE
[Bug]：等待网络连接：Get "https://alidns.aliyuncs.com/": dial tcp xxx.xxx.xxx.xxx: connect: permission denied

### ISSUE THREAD

**Issue by YKDZ** [jeessy2/ddns-go#755]
### 问题描述

https://pastebin.com/fuSXey15
以服务方式在Centos8中运行出现的报错
网络搜索结果大多是关于Docker的

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

v5.3.6

### 安装方式

服务

**Comment by jeessy2** [comment]
检查系统selinux/防火墙之类的，关闭selinux试试

**Comment by YKDZ** [comment]
关闭selinux后解决 谢谢帮助
