### ISSUE TITLE
密码忘了

### ISSUE THREAD

**Issue by arthurLKD** [jeessy2/ddns-go#756]
佬，在网页设置了密码，怎么重置

**Comment by WaterLemons2k** [comment]
用户名和密码位于 配置文件 中（默认位于当前用户目录下的 .ddns_go_config.yaml 文件中)

参考：
- https://github.com/jeessy2/ddns-go/wiki/FAQ#忘记用户名或密码
- #85 #115 #197 #208 #362 #447 #483 #554 #685
