### ISSUE TITLE
@.mydomain.com 想这样来更新域名, 请问应该怎么填? 

### ISSUE THREAD

**Issue by biggbuddy** [jeessy2/ddns-go#758]
阿里云解析, 定义了一个 @ 主机记录, 然后其它的二级域名, 如 ok.mydomain.com 就使用CNAME记录, 并指向 mydomain.com, 这样避免往后想添加 一个新的域名的时候, 还要改ddns-go里面的配置

但问题是在 Domains 一栏里面应该怎么填呢? 我试了 @.mydomain.com 这种写法, 结果把我的 @ 主机记录删除了, 添加了一条 mydomain.mydomain.com的记录

请问这种需求应该要怎么写? 谢谢

pls, 使用的是ipv6公网, 不过应该没有什么关联吧.....

@jeessy2

**Comment by jeessy2** [comment]
直接填写mydomain.com
不用手动加@，程序会根据不通运营商进行不同处理

**Comment by biggbuddy** [comment]
> 

好像有问题哦， 经常会在阿里云那边生成一个  mydomain.mydomain.com 的 AAAA记录
我配的就是 mydomain.com @jeessy2

**Comment by jeessy2** [comment]
截图看下怎么配置的，文字描述清晰一点，都有点看不懂什么意思呢？
