### ISSUE TITLE
[提问]：请问在华硕路由上使用时如何取消显示<可使用 sudo ./ddns-go -s install 安装服务运行>

### ISSUE THREAD

**Issue by 2TimesMeta** [jeessy2/ddns-go#761]
### 问题描述

华硕路由的服务运行方式特殊，无法正常安装。
因此还有什么办法取消日志中显示 <可使用 sudo ./ddns-go -s install 安装服务运行> 吗？

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### ddns-go 版本

v5.3.6

### 安装方式

其它

### 额外信息

2023/07/06 19:28:17 可使用 sudo ./ddns-go -s install 安装服务运行
2023/07/06 19:28:17 监听 :9876 ...

**Comment by jeessy2** [comment]
只有首次启动并没有安装为服务才提示，安装不了的话，不管这个提示
