### ISSUE TITLE
[功能]：检测同步ip的域名和同步的域名的疑问

### ISSUE THREAD

**Issue by msmkls** [jeessy2/ddns-go#762]
### 功能描述

请问，检测的域名和本地ip是否同步，在多个二级域名需要每个都对比同步，能不能只对比指定的一个域名，同步多个。

这里涉及到cloudflare cdn的一个疑问，例如：同步到cloudflare，再开启cloudflare cdn后，对比的这个域名ip是cloudflare cdn的还是什么，本地ip如果和域名ip不同步的情况下，ddnsgo是否一直去同步修改ip到cloudflare，请指教下，十分感谢

**Comment by jeessy2** [comment]
所有域名都要对比，不能指定
对比的IP始终为cloudflare中设置的IP，不是CDN IP
会一直同步的

**Comment by msmkls** [comment]
> 

好的，感谢解答
