### ISSUE TITLE
请求添加忽略SSL证书安全选项

### ISSUE THREAD

**Issue by ifyz** [jeessy2/ddns-go#764]
### 功能描述

在路由器下运行ddns-go  因为缺少证书报错
由于/etc/ssl 路径被挂载为只读，无法导入证书，需要选项来忽略证书安全检查

WAP(Dopra Linux) # ./ddns
2023/07/10 18:02:00 可使用 sudo ./ddns-go -s install 安装服务运行
2023/07/10 18:02:00 监听 :9876 ...
请手动打开浏览器并访问 http://127.0.0.1:9876 进行配置
2023/07/10 18:02:00 等待网络连接：Get "https://alidns.aliyuncs.com/": tls: failed to verify certificate: x509: certificate signed by unknown authority。5s 后重试...

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by WaterLemons2k** [comment]
使用参数 `-skipVerify` 跳过证书验证。
