### ISSUE TITLE
疑似www和根域名（裸域名）更新冲突

### ISSUE THREAD

**Issue by Bingning** [jeessy2/ddns-go#769]
### 问题描述

我有个Godaddy申请的域名比如johndoe.com，
用本工具解析到家里的动态公网ip用于访问本地的路由器和nas等。本地设置的只解析johndoe.com，运行一切正常。

薅羊毛了一台AWS的机器，有公网ip，搭建了wordpress，在GoDaddy的DNS设置界面添加A记录把www.johndoe.com指向这个机器的ip。

但本地发现动态ip地址变化更新时，会把GoDaddy的www的A记录冲掉。

请问是我设置的问题？
还是本工具在更新时会自动把非根域名的其他记录都冲掉？

谢谢。

### DNS服务商

GoDaddy

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v5.1.1

### 安装方式

Docker

**Comment by WaterLemons2k** [comment]
试一下 `@.example.com` 格式的域名。

**Comment by Bingning** [comment]
感谢回复。
我本地用 @冒号johndoe.com测试通过了。

@:johndoe.com

**Comment by WaterLemons2k** [comment]
看起来 Godaddy Domains API 可能会在没有子域名时更新域名的所有记录。

由 #770 修复。
