### ISSUE TITLE
怎么让程序每分钟运行一次进行更新

### ISSUE THREAD

**Issue by wleelw** [jeessy2/ddns-go#775]
### 功能描述

或者已经有这个功能，而我想让他在电脑启动时自动运行程序更新ip地址

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by wleelw** [comment]
另外我想问可以安装在openwrt吗？我现在测试在mac上没问题，只是不知道如何做到应用自启动运行

**Comment by WaterLemons2k** [comment]
> 怎么让程序每分钟运行一次进行更新

使用参数 `-f` 更改同步间隔时间(秒)。

示例：`./ddns-go -f 60`

> 另外我想问可以安装在openwrt吗？我现在测试在mac上没问题，只是不知道如何做到应用自启动运行

使用 `./ddns-go -s install` 安装服务。
