### ISSUE TITLE
找不到 tag 时使用 HEAD commit 作为版本

### ISSUE THREAD

**Issue by WaterLemons2k** [jeessy2/ddns-go#776]
### 功能描述

目前，在使用 `make build` 构建 ddns-go 时会使用 tag 作为版本。但在找不到 tag 时，也可以使用 HEAD commit 作为版本：

```makefile
VERSION=$(shell git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || git rev-parse --short HEAD)
```

### 解决的问题

使用 GitHub Actions 的 [test.yml](https://github.com/jeessy2/ddns-go/actions/workflows/test.yml?query=branch%3Amaster) 构建 ddns-go 时可能没有 tag，从而导致版本为空。

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
可以来个PR
