### ISSUE TITLE
账号密码必填？

### ISSUE THREAD

**Issue by jeessy2** [jeessy2/ddns-go#778]
### 功能描述

因互联网存在各种扫描，内网也会存在，考虑帐号密码必填，同时验证弱密码

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by WaterLemons2k** [comment]
一些不成熟的想法：

> 因互联网存在各种扫描，内网也会存在

如果要防止扫描默认端口，指引用户监听高端口是否更好些？

> 考虑帐号密码必填

这样是不是破坏性太高？如果用户不依靠 ddns-go 的 basic auth 来保证安全性，账号密码必填是否会带来不好的体验？

如何处理从不使用 Web UI 的用户？

**Comment by jeessy2** [comment]
> 指引用户监听高端口

这个的操作性有点弱

> 破坏性太高
不使用basic auth登录，改其它网页形式的登录？

主要考虑有命令获取IP，如果有弱口令等，容易成肉鸡

**Comment by WaterLemons2k** [comment]
> 不使用basic auth登录，改其它网页形式的登录？

这样就感觉有点复杂了，还得写个登录页。

HTTP 明文传输怎么改也不安全，如果反代为 HTTPS 那都很安全，所以基本的差不多也够了。

> 主要考虑有命令获取IP，如果有弱口令等，容易成肉鸡

确实有必要检测弱口令，可以尝试用 [go-password-validator](https://github.com/wagslane/go-password-validator) 之类的库来检测。

**Comment by jeessy2** [comment]
可以，那就先检测弱口令。有空你来个PR？
