### ISSUE TITLE
端口转发功能

### ISSUE THREAD

**Issue by githubgeekrabbit** [jeessy2/ddns-go#780]
### 功能描述

加一个端口转发功能，转发ipv4和ipv6

### 解决的问题

主要用于解决一个ipv6地址就可以把局域网下所有设备转发到ipv6地址上，而不用每台设备都安装一个ddns软件

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
看名称就不是干端口转发的，建议找其他软件

**Comment by githubgeekrabbit** [comment]
但是可以实现啊，也就对应的转发命令而已

**Comment by githubgeekrabbit** [comment]
这是采用windows作为转发，监听本地ipv6 5000端口的流量，转发至局域网下192.168.1.37:5000的流量
netsh interface portproxy add v6tov4 listenaddress=:: listenport=5000 connectaddress=192.168.1.37 connectport=5000
linux下可以用
ip6tables
