### ISSUE TITLE
调用api更新timeout,此后日志一直显示ipv4未改变

### ISSUE THREAD

**Issue by cnsilvan** [jeessy2/ddns-go#781]
### 问题描述

首次调用api更新失败，感觉可以更快速的再去尝试
如果是我理解错误，先说抱歉

### DNS服务商

Callback

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### 版本

5.3.7

### 安装方式

服务

**Comment by cnsilvan** [comment]
因为api.dynu.com被墙，如果节点失效，就会导致更新timeout

**Comment by jeessy2** [comment]
下次会自动重新请求的，如果需要更快的频率：参考首页说明 `-f 60` 60秒同步一次
