### ISSUE TITLE
[问一下] 请问日志文件在哪里？

### ISSUE THREAD

**Issue by victorxtx** [jeessy2/ddns-go#783]
### 功能描述

请问日志文件在哪里

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by WaterLemons2k** [comment]
并没有日志文件。

**Comment by ItzMiracleOwO** [comment]
![image](https://github.com/jeessy2/ddns-go/assets/76854136/266d41a8-ee2b-45fe-8d97-e0e7cef3b817)

**Comment by violetgits** [comment]
后台运行时，历史日志有本地保存吗？

**Comment by WaterLemons2k** [comment]
> 后台运行时，历史日志有本地保存吗？

不会在本地保存历史日志。

**Comment by jeessy2** [comment]
系统不同，历史日志存放位置不同
