### ISSUE TITLE
webhook无法通知

### ISSUE THREAD

**Issue by testwhite** [jeessy2/ddns-go#785]
### 问题描述

webhook测试正常，但是实际Ip有变动时，无法主动推送webhook通知

### 是否已搜索同类问题

未搜索

### 操作系统

Linux

### 架构

i386

### 版本

5.5.0

### 安装方式

Docker

### 额外信息

![image](https://github.com/jeessy2/ddns-go/assets/31587423/af26cb2f-351b-45fa-8f33-9c0a318246ce)

**Comment by jeessy2** [comment]
实际Ip有变动时，查看打印相关日志没有

**Comment by testwhite** [comment]
没有日志。
2023/07/26 12:54:54 连接失败! <a target='blank' href='https://myip4.ipip.net'>点击查看接口能否返回IPv4地址</a>
2023/07/26 12:54:54 错误信息: Get "https://myip4.ipip.net": net/http: TLS handshake timeout

**Comment by testwhite** [comment]
但是有个错误

**Comment by WaterLemons2k** [comment]
> 没有日志。
> 2023/07/26 12:54:54 连接失败! [点击查看接口能否返回IPv4地址](https://myip4.ipip.net)
> 2023/07/26 12:54:54 错误信息: Get "https://myip4.ipip.net": net/http: TLS handshake timeout

没获取到 IP 不会发送 Webhook 通知，超时了。偶尔是正常情况，长期检查网络

**Comment by testwhite** [comment]
但是域名已经自动解析了。

**Comment by WaterLemons2k** [comment]
> 但是域名已经自动解析了。

如果获取到了 IP 就会添加或更新解析并发送 Webhook 通知。

如果只是偶尔获取不到 IP 可以忽略。

**Comment by testwhite** [comment]
好，我再观察下。

**Comment by jeessy2** [comment]
通过接口获取IP失败超过3次才会通知，防止你收到过多通知
