### ISSUE TITLE
群晖7.2docker改版

### ISSUE THREAD

**Issue by wleelw** [jeessy2/ddns-go#791]
### 功能描述

您好，群晖7.2的docker改版为新的“container manager”，里面的网络配置选项已经更改了，请问怎么设置

### 解决的问题

您好，群晖7.2的docker改版为新的“container manager”，里面的网络配置选项已经更改了，请问怎么设置

### 附加信息

您好，群晖7.2的docker改版为新的“container manager”，里面的网络配置选项已经更改了，请问怎么设置

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by WaterLemons2k** [comment]
使用docker host模式就将 `网络` 设置为 `host`，不使用docker host模式就映射 `9876` 端口。
