### ISSUE TITLE
指定网卡请求接口

### ISSUE THREAD

**Issue by Ran-Xing** [jeessy2/ddns-go#794]
### 功能描述

```bash
curl --interface enp5s0 cip.cc
```

奇奇怪怪的网络环境可以用这种方式 获取到真实ip

### 解决的问题

获取ip地址

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by Ran-Xing** [comment]
顺便问下，能不能同时支持多份配置文件呢

**Comment by jeessy2** [comment]
`curl --interface enp5s0 cip.cc`通过命令获取
支持多份配置文件

**Comment by Ran-Xing** [comment]
@jeessy2 实际测试只有配置文件1生效

**Comment by Ran-Xing** [comment]
我是两个cloudflare的api

**Comment by Ran-Xing** [comment]
每次保存，日志提示都是配置1的提示

**Comment by jeessy2** [comment]
检查你配置，或者截图，重要信息打码
