### ISSUE TITLE
获取的ipv6地址无法访问

### ISSUE THREAD

**Issue by wcn666** [jeessy2/ddns-go#795]
### 问题描述

您好·，我搬家换宽带以后，我的ipv6只能获取到一个短地址，不像以前一样有三个，请问是运营商问题吗？我用的是爱快拨号，搬家之前是正常的。现在的v6地址全是这种短的  2408:826a:e10:9462:1a9d::db9 ，有什么解决办法吗

请问大家都能获取到几个地址，哪个v6地址能访问啊 

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

i386

### 版本

1

### 安装方式

其它

**Comment by WaterLemons2k** [comment]
先测试一下能不能连接到 [IPv6 测试](http://test-ipv6.com/) 的测试域名 https://ipv6.ams2.test-ipv6.com/ip/ ，看返回的是哪个 IP。

**Comment by wcn666** [comment]
> 先测试一下能不能连接到 [IPv6 测试](http://test-ipv6.com/) 的测试域名 https://ipv6.ams2.test-ipv6.com/ip/ ，看返回的是哪个 IP。

callback({"ip":"2408:826a:e10:9462:1a9d::2f1","type":"ipv6","subtype":"","via":"","padding":""})  返回值是这个

**Comment by wcn666** [comment]
> 再运行 `ip -6 addr` 看一下 IPv6 的子网大小（例如 `/64` 或 `/128`）

 2408:826a:e10:9462:1a9d::db9/64   爱快路由设置的64位

**Comment by WaterLemons2k** [comment]
然后再检查一下光猫的 IPv6 防火墙和爱快的 ACL 以及其它设备有没有阻断 IPv6 入站。

**Comment by wcn666** [comment]
> 然后再检查一下路由器的 IPv6 防火墙和爱快的 ACL 以及其它设备有没有阻断 IPv6 入站。

我光猫桥接的，爱快拨号。路由器作为ap，都需要检查吗？  爱快的ACL我没有设置过，是默认的。

**Comment by WaterLemons2k** [comment]
> 我是用爱快运行，还是群晖运行这个命令呢？

要获取哪个设备的 IP，就在哪个设备上运行。

**Comment by wcn666** [comment]
> > 我是用爱快运行，还是群晖运行这个命令呢？
> 
> 
> 
> 要获取哪个设备的 IP，就在哪个设备上运行。

好的，我尝试运行一下试试

**Comment by wcn666** [comment]
> > 接下来尝试通过 EUI-64 获取 IPv6 地址：
> > Linux 运行：
> > ```shell
> > ip -6 addr
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. 找到目前用于连接互联网的网络适配器。
> > 2. 找到一个 IP 地址，它应该类似于 `2408:2002:2003:2004:****:**ff:fe**:****`，它就是该设备的 EUI-64 地址。
> > 3. 记下 `****:**ff:fe**:****` 的部分，下文假设它是 `1:20ff:fe77:2077`。
> > 4. 运行：
> > 
> > ```shell
> > ip -6 route | awk '{print $1}' | awk '/240:?/' | awk -F::/ '{print $1 ":suffix of other mac"}'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 假设 EUI-64 地址是 `1:20ff:fe77:2077`：
> > ```shell
> > ip -6 route | awk '{print $1}' | awk '/240:?/' | awk -F::/ '{print $1 ":1:20ff:fe77:2077"}'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 参考：https://rongrongbq.moe/2021/08/firewall-and-DDNS-settings-for-IPv6/#%E9%80%89%E9%A1%B9%E4%B8%80%EF%BC%9AEUI-64%EF%BC%88%E6%8E%A8%E8%8D%90%EF%BC%89
> 
> 我是用爱快运行，还是群晖运行这个命令呢？

 fe80::b26e:bfff:fece:4416/64    只找到了这个类似格式的，是这个吗

**Comment by WaterLemons2k** [comment]
> 6: ovs_eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UNKNOWN qlen 1 inet6 2408:826a:e10:9462:1a9d::db9/64 scope global valid_lft forever preferred_lft forever inet6 fe80::211:32ff:fe12:3456/64 scope link valid_lft forever preferred_lft forever 7: ovs_eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UNKNOWN qlen 1 inet6 fe80::b26e:bfff:fece:4416/64 scope link valid_lft forever preferred_lft forever
> 
> 都是fe开头的地址

可以都试一下

**Comment by wcn666** [comment]
> > 6: ovs_eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UNKNOWN qlen 1 inet6 2408:826a:e10:9462:1a9d::db9/64 scope global valid_lft forever preferred_lft forever inet6 fe80::211:32ff:fe12:3456/64 scope link valid_lft forever preferred_lft forever 7: ovs_eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UNKNOWN qlen 1 inet6 fe80::b26e:bfff:fece:4416/64 scope link valid_lft forever preferred_lft forever
> > 都是fe开头的地址
> 
> 可以都试一下

运行结果是这样的  
ip -6 route | awk '{print $1}' | awk '/240:?/' | awk -F::/ '{print $1 ":211:32ff:fe12:3456"}'
2408:826a:e10:9462:211:32ff:fe12:3456
 下一步怎么做呢

**Comment by wcn666** [comment]
> > 接下来尝试通过 EUI-64 获取 IPv6 地址：
> 
> > 
> 
> > Linux 运行：
> 
> > 
> 
> > ```shell
> 
> > ip -6 addr
> 
> > ```
> 
> > 
> 
> > 1. 找到目前用于连接互联网的网络适配器。
> 
> > 2. 找到一个 IP 地址，它应该类似于 `2408:2002:2003:2004:****:**ff:fe**:****`，它就是该设备的 EUI-64 地址。
> 
> > 3. 记下 `****:**ff:fe**:****` 的部分，下文假设它是 `1:20ff:fe77:2077`。
> 
> > 4. 运行：
> 
> > 
> 
> > ```shell
> 
> > ip -6 route | awk '{print $1}' | awk '/240:?/' | awk -F::/ '{print $1 ":suffix of other mac"}'
> 
> > ```
> 
> > 
> 
> > 假设 EUI-64 地址是 `1:20ff:fe77:2077`：
> 
> > 
> 
> > ```shell
> 
> > ip -6 route | awk '{print $1}' | awk '/240:?/' | awk -F::/ '{print $1 ":1:20ff:fe77:2077"}'
> 
> > ```
> 
> > 
> 
> > 参考：https://rongrongbq.moe/2021/08/firewall-and-DDNS-settings-for-IPv6/#%E9%80%89%E9%A1%B9%E4%B8%80%EF%BC%9AEUI-64%EF%BC%88%E6%8E%A8%E8%8D%90%EF%BC%89
> 
> 
> 
> 6: ovs_eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UNKNOWN qlen 1
> 
>     inet6 2408:826a:e10:9462:1a9d::db9/64 scope global 
> 
>        valid_lft forever preferred_lft forever
> 
>     inet6 fe80::211:32ff:fe12:3456/64 scope link 
> 
>        valid_lft forever preferred_lft forever
> 
> 7: ovs_eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UNKNOWN qlen 1
> 
>     inet6 fe80::b26e:bfff:fece:4416/64 scope link 
> 
>        valid_lft forever preferred_lft forever
> 
> 
> 
> 都是fe开头的地址

我这个是爱快的问题吗？要不我用硬路由拨号或者刷op试一下。

**Comment by wcn666** [comment]
> > 我这个是爱快的问题吗？要不我用硬路由拨号或者刷op试一下。
> 
> 
> 
> 最后再尝试用 [EUI-64 Calculator](https://eui64-calc.princelle.org/) 根据 MAC 地址计算出 EUI-64 或检查爱快的 [IPv6 设置](https://www.ikuai8.com/zhic/ymgn/lyym/wlsz/ipv6/123.html)，再不行就只能试试其它系统了。

怎么根据这个计算啊，计算出来了又要怎么操作。小白一个不太明白。
