### ISSUE TITLE
链接CloudFlare问题

### ISSUE THREAD

**Issue by PangXitong** [jeessy2/ddns-go#797]
### 问题描述

# 报错
### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

macOS (Darwin)

### 架构

x86_64

### 版本

v5.5.1

### 安装方式

服务

### 额外信息

2023/08/01 13:00:01 请求接口 https://api.cloudflare.com/client/v4/zones?name=//pangxitong.link/&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400
<img width="2048" alt="截屏2023-08-01 13 00 06" src="https://github.com/jeessy2/ddns-go/assets/112756665/8db09b17-addb-461f-81ac-46d54cd919f1">

**Comment by WaterLemons2k** [comment]
域名格式不正确，不需要开头的 `http://` 和结尾的 `/`，只需要 `example.com` 即可。

**Comment by earth712** [comment]
更新了后 , 碰到同样的错误......不知道咋解决了

**Comment by LittleArray** [comment]
一样问题,应该是接口改了

**Comment by jeessy2** [comment]
去cf重新生成一个新token

**Comment by LittleArray** [comment]
新生成了现在解决了这个问题但是好像网路抽风我这边连不上cloudflare

**Comment by LittleArray** [comment]
问题解决,话说我没设置host,DNS也是8.8.8.8为什么cf会被解析成[::1]啊

**Comment by jeessy2** [comment]
搜索DNS污染
