### ISSUE TITLE
关于新增解析SPF记录的请求

### ISSUE THREAD

**Issue by Kx-Y** [jeessy2/ddns-go#801]
### 功能描述

我需要动态解析SPF记录的功能

### 解决的问题

没有SPF记录，自建邮件服务器做邮箱会被标记为垃圾邮件

### 附加信息

由于我不会go语言，所以我在此尽可能地提供有关信息，希望有大佬帮忙实现
SPF记录的本质，是TXT记录
以下是我从cloudflare上截来的图片
![image](https://github.com/jeessy2/ddns-go/assets/86878459/7006bdad-a63d-4f52-a1a7-45c4d68068cc)
只要动态改变txt记录中的ip6 与 ip4 后面对应的IP地址，就可以了，应该
再次感谢各位大佬的无私奉献！

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by Kx-Y** [comment]
其他服务商我没试过，只试过cloud flare

**Comment by jeessy2** [comment]
和目前功能不同，以后估计也不会支持，自行研究了

**Comment by inused** [comment]
这应该不属于DDNS的范畴了吧。
最直接的方案就是自己修改源码后编译。
鉴于你不会，那可以迂回一下，借助Webhook，IP更新后调用你自己的接口，由你的服务调用CF去更新SPF。
既然你是自建邮件服务，那么顺便搞一个接口也是没问题的。
或者直接使用Cloudflare的worker或pages搞一个接口
