### ISSUE TITLE
增加 #{ipType} 功能，方便Callback调用URL时选择

### ISSUE THREAD

**Issue by o2asdv** [jeessy2/ddns-go#802]
### 功能描述

增加 #{ipType} 功能，方便Callback调用URL时选择。

如：https://dynv6.com/api/update?hostname=#{domain}&token=XXXXXXX&ipv#{ipType}=#{ip}

ipType的值为：4或6

### 解决的问题

修改代码：dns/callback.go （108行后，for之前添加）
增加内容
	if recordType == "A" {
		orgPara = strings.ReplaceAll(orgPara, "#{ipType}", "4")
	} else if recordType == "AAAA" {
		orgPara = strings.ReplaceAll(orgPara, "#{ipType}", "6")
	}

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by o2asdv** [comment]
我自己改完测试了下，调用dynv6的接口是正常的

**Comment by jeessy2** [comment]
不用改代码。使用传递自定义参数
https://github.com/jeessy2/ddns-go/wiki/%E4%BC%A0%E9%80%92%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%82%E6%95%B0#callback
