### ISSUE TITLE
token有效的情况下请求Cloudflare的接口失败

### ISSUE THREAD

**Issue by Apelious** [jeessy2/ddns-go#808]
### BUG描述：
使用ipv6的ddns时遇到该bug，日志显示请求接口失败。

### 日志如下所示：
2023/08/05 08:23:37 请求接口https://api.cloudflare.com/client/v4/zones?name=yousuck.icu&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=yousuck.icu&status=active&per_page=50": tls: failed to verify certificate: x509: certificate is valid for intel.yousuck.icu, not api.cloudflare.com

### 事件发生经过
该token已经稳定使用半年多了，解析一切正常，直到今天发现解析失败，查看日志发现在四天前就开始出现请求接口失败的情况了。于是尝试在Cloudflare请求一个新的token并写入配置文件，但是发现问题依旧。在后续对token的测试中并未发现token有问题。

### Token配置及其测试
配置：
![image](https://github.com/jeessy2/ddns-go/assets/57549957/d41357f5-975e-4409-a2af-c145ac5c83e1)

测试：curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
     -H "Authorization: Bearer RrIDowmV**********************************" \
     -H "Content-Type:application/json"
测试结果：{"result":{"id":"3cfdb5fefba82cc921dea6*********","status":"active"},"success":true,"errors":[],"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]}

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v5.3.0

### 安装方式

服务

**Comment by WaterLemons2k** [comment]
```
tls: failed to verify certificate: x509: certificate is valid for intel.yousuck.icu, not api.cloudflare.com
```

使用参数 `-skipVerify` 跳过证书验证。

**Comment by Apelious** [comment]
> ```
> tls: failed to verify certificate: x509: certificate is valid for intel.yousuck.icu, not api.cloudflare.com
> ```
> 
> 使用参数 `-skipVerify` 跳过证书验证。

首先谢谢您耐心看完了我的issue并且做出了解答！！！
我按照您的方法加上了这个参数但是好像接口访问就404了😭
![image](https://github.com/jeessy2/ddns-go/assets/57549957/1f539200-b6e9-48f7-8c3b-77228268f046)
或许我可能没注意到某些细节，希望您能继续耐心解答，再次感谢！

**Comment by jeessy2** [comment]
看下api.cloudflare.com解析到哪去了，有可能解析到127.0.0.1

**Comment by WaterLemons2k** [comment]
> 首先谢谢您耐心看完了我的issue并且做出了解答！！！
> 我按照您的方法加上了这个参数但是好像接口访问就404了😭
> ![image](https://user-images.githubusercontent.com/57549957/258576715-1f539200-b6e9-48f7-8c3b-77228268f046.png)
> 或许我可能没注意到某些细节，希望您能继续耐心解答，再次感谢！

感觉可能是 `api.cloudflare.com` 被劫持到其它域名了，先添加参数 `-dns 1.1.1.1` 用自定义 DNS 服务器解析看下。

**Comment by Apelious** [comment]
啊这，我上当了😭
![截图 2023-08-05 17-57-03](https://github.com/jeessy2/ddns-go/assets/57549957/6c8e4857-38b1-4e25-883d-ca649003a85f)
指定DNS服务器之后就ok了
![image_2023-08-05_18-00-37](https://github.com/jeessy2/ddns-go/assets/57549957/7a277c36-d729-4490-b6cd-e55cdaab0baa)
万分感谢你们的解答！！！
