### ISSUE TITLE
更新域名解析成功，但依旧无法连接

### ISSUE THREAD

**Issue by PangXitong** [jeessy2/ddns-go#809]
### 问题描述

电脑Wi-Fi架设服务器（127.0.0.1能打开）
日志显示2023/08/05 17:22:41 更新域名解析 pangxitong.link 成功！IP: 119.51.23.242
但是手机5G浏览器连接不上
浏览器报错服务器停止响应，而不是找不到服务器

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

macOS (Darwin)

### 架构

x86_64

### 版本

v5.5.1

### 安装方式

服务

### 额外信息

<img width="515" alt="截屏2023-08-05 17 22 53" src="https://github.com/jeessy2/ddns-go/assets/112756665/3877bf0e-ea68-4971-9fa3-943958421e33">
<img width="2048" alt="截屏2023-08-05 17 23 26" src="https://github.com/jeessy2/ddns-go/assets/112756665/0bdd333f-b2c2-4038-aa85-ff785ffd247e">
<img width="2048" alt="截屏2023-08-05 17 24 20" src="https://github.com/jeessy2/ddns-go/assets/112756665/67bec020-227e-427b-8b76-1bd111ecb889">
<img width="2048" alt="截屏2023-08-05 17 24 40" src="https://github.com/jeessy2/ddns-go/assets/112756665/4fecbdaa-0d98-4a57-83f8-bda2b89c93e2">
![IMG_6539](https://github.com/jeessy2/ddns-go/assets/112756665/7b68c658-67f9-4c5d-83db-452768dcdb8b)
![IMG_6539](https://github.com/jeessy2/ddns-go/assets/112756665/a532bdb4-e0b5-4d4a-8daf-092dafd4c323)

**Comment by WaterLemons2k** [comment]
WAN 口的 IP 是什么？

**Comment by PangXitong** [comment]
> WAN 口的 IP 是什么？

192.168.31.203？

**Comment by WaterLemons2k** [comment]
> 192.168.31.203？

不是公网 IP，所以无法连接。

**Comment by PangXitong** [comment]
> 不是公网 IP，所以无法连接。

公网IP是变动的，例如119.51.23.242怎么办啊，我没有终端独立的IPv4，怎么解决啊

**Comment by WaterLemons2k** [comment]
> 公网IP是变动的，例如119.51.23.242怎么办啊，我没有终端独立的IPv4，怎么解决啊

与动态公网 IP 无关。

只有 WAN 口 IP 与公网 IP 一致的情况下才能从公网访问。

**Comment by mrmyn** [comment]
> > 公网IP是变动的，例如119.51.23.242怎么办啊，我没有终端独立的IPv4，怎么解决啊
> 
> 与动态公网 IP 无关。
> 
> 只有 WAN 口 IP 与公网 IP 一致的情况下才能从公网访问。

我现在一致但是通过cloudflare配置好后也打不开，但是可以通过公网ip打开

**Comment by xiaowei56** [comment]
同样的问题，如何解决
