### ISSUE TITLE
cloudflare X509报错

### ISSUE THREAD

**Issue by orzzorzz** [jeessy2/ddns-go#810]
### 问题描述

2023/08/06 13:41:00 请求接口https://api.cloudflare.com/client/v4/zones?name=xxxx.link&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=taoe.link&status=active&per_page=50": tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match api.cloudflare.com

### 是否已搜索同类问题

未搜索

### 操作系统

Linux

### 架构

i386

### 版本

 v5.3.6

### 安装方式

Docker

### 额外信息

2023/08/06 13:41:00 请求接口https://api.cloudflare.com/client/v4/zones?name=xxxx.link&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=taoe.link&status=active&per_page=50": tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match api.cloudflare.com

**Comment by WaterLemons2k** [comment]
先看下 `api.cloudflare.com` 解析的是哪个地址：

```sh
ping api.cloudflare.com
```

**Comment by orzzorzz** [comment]
......127.0.0.1   dns污染了对吗

**Comment by WaterLemons2k** [comment]
> ......127.0.0.1 dns污染了对吗

对的。添加参数 `-dns 1.1.1.1` 使用自定义 DNS 服务器解析。

**Comment by RemKeeper** [comment]
![image](https://github.com/jeessy2/ddns-go/assets/78486275/a4efca2b-df29-43e9-ae21-f2fea1712573)
我这边同样的问题，但是自定义dns也无效
![image](https://github.com/jeessy2/ddns-go/assets/78486275/88637d3b-a226-440b-9efb-bf7f849e73e0)

**Comment by WaterLemons2k** [comment]
> ![image](https://user-images.githubusercontent.com/78486275/258700009-a4efca2b-df29-43e9-ae21-f2fea1712573.png) 我这边同样的问题，但是自定义dns也无效 ![image](https://user-images.githubusercontent.com/78486275/258700176-88637d3b-a226-440b-9efb-bf7f849e73e0.png)

连接不到 `1.1.1.1`。换一个 DNS 服务器，例如 `114.114.114.114`。

**Comment by RemKeeper** [comment]
> > ![image](https://user-images.githubusercontent.com/78486275/258700009-a4efca2b-df29-43e9-ae21-f2fea1712573.png) 我这边同样的问题，但是自定义dns也无效 ![image](https://user-images.githubusercontent.com/78486275/258700176-88637d3b-a226-440b-9efb-bf7f849e73e0.png)
> 
> 连接不到 `1.1.1.1`。换一个 DNS 服务器，例如 `114.114.114.114`。

![image](https://github.com/jeessy2/ddns-go/assets/78486275/3d46fe2a-50b4-4fc6-9d0c-e58c7e247f89)
![image](https://github.com/jeessy2/ddns-go/assets/78486275/cfa649d7-eae4-4b5a-9d3c-6beb306764f3)

先后尝试了114和阿里云,百度的dns，一样无效

**Comment by WaterLemons2k** [comment]
> ![image](https://github.com/jeessy2/ddns-go/assets/78486275/cfa649d7-eae4-4b5a-9d3c-6beb306764f3)
> 
> 
> 
> 先后尝试了114和阿里云,百度的dns，一样无效

使用参数 `-skipVerify` 跳过证书验证。

**Comment by sdyby2006** [comment]
> > ![image](https://user-images.githubusercontent.com/78486275/258708505-cfa649d7-eae4-4b5a-9d3c-6beb306764f3.png)
> > 先后尝试了114和阿里云，百度的DNS，一样无效
> 
> 使用参数 跳过证书验证。`-skipVerify`

请问怎么可以永久设定使用8.8.8.8进行dns解析？

**Comment by WaterLemons2k** [comment]
> 请问怎么可以永久设定使用8.8.8.8进行dns解析？

安装服务：

```sh
sudo ./ddns-go -s install -dns 8.8.8.8
```

**Comment by tmzg0000** [comment]
> > 请问怎么可以永久设定使用8.8.8.8进行dns解析？
> 
> 安装服务：
> 
> ```shell
> sudo ./ddns-go -s install -dns 8.8.8.8
> ```

我是同样的问题 我是在群晖里安装的docker版本 用你上面的命令后提示
/app # sudo ./ddns-go -s install -dns 8.8.8.8                                                                                                                                                               
/bin/sh: sudo: not found                                                                                                                                                                                    
/app # ./ddns-go -s install -dns 8.8.8.8                                                                                                                                                                    
2023/08/09 14:26:53 安装 ddns-go 服务失败, ERR: "rc-update" failed: exec: "rc-update": executable file not found in $PATH                                                                                   
/app # cd ddns-go                                                                                                                                                                                           
/bin/sh: cd: can't cd to ddns-go: Not a directory 

没法安装 问题没解决

**Comment by WaterLemons2k** [comment]
> 我是同样的问题 我是在群晖里安装的docker版本 用你上面的命令后提示 /app # sudo ./ddns-go -s install -dns 8.8.8.8 /bin/sh: sudo: not found /app # ./ddns-go -s install -dns 8.8.8.8 2023/08/09 14:26:53 安装 ddns-go 服务失败, ERR: "rc-update" failed: exec: "rc-update": executable file not found in $PATH
> 
> 没法安装 问题没解决

创建容器时添加参数就可以了：

```sh
docker run -d --name ddns-go --restart=always --net=host -v /opt/ddns-go:/root jeessy/ddns-go -dns 8.8.8.8
```

**Comment by tmzg0000** [comment]
好的,谢谢. 问题解决了

**Comment by orzzorzz** [comment]
我的在路由器设置了smartdns 已经解决了 上游dns用dns 和ali的
