### ISSUE TITLE
请求增加 dns.he.net 的更新功能

### ISSUE THREAD

**Issue by user1121114685** [jeessy2/ddns-go#814]
### 功能描述

更新url如下 使用http.get 请求即可

`https://__HOSTNAME__:__PASSWORD__@dyn.dns.he.net/nic/update?hostname=__HOSTNAME__&myip=__MYIP__`

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by user1121114685** [comment]
IPV4,IPV6同一个接口！

**Comment by jeessy2** [comment]
用callback
