### ISSUE TITLE
子域名无法更新

### ISSUE THREAD

**Issue by yangleiwudi** [jeessy2/ddns-go#815]
### 功能描述

当前情况为cloudflare 解析一级域名 a.com ,添加了一条 b.a.com 的ns 记录 在阿里云
手动设置 查询已经生效 自动更新失败 日志中显示提交域名不存在

### 解决的问题

子域名解析

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
试下使用`:`分割 xx:b.a.com

**Comment by yangleiwudi** [comment]
@jeessy2 谢谢指导 已经成功解析!感谢!
