### ISSUE TITLE
新域名延迟生效

### ISSUE THREAD

**Issue by CCCAUCHY** [jeessy2/ddns-go#816]
### 功能描述

新增延迟更新域名解析功能, 或者保存不重置同步间隔计时.

### 解决的问题

考虑到隐私保护, 为了不留下DNS历史, 当需要同时更新域名和IP时, 如果使用远程操作并开启延迟更新模式, 更改域名并保存后, 延迟30秒生效, 期间可重置网络(有时会重启计算机), 重启后, 读取重启前就保存的配置文件, 由于配置文件里配置了延迟更新模式, 所以在服务启动后也会延迟30秒才为新域名添加DNS记录.
或者保存不重置同步间隔计时, 可以在同步间隔期间保存新域名并重置网络, 重启后可立即为新域名添加DNS记录.

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
啥？

**Comment by CCCAUCHY** [comment]
> 啥？

保存新域名时会立即添加DNS记录, 此时旧域名和新域名都拥有同样的DNS记录, 可以通过IP地址倒查

**Comment by jeessy2** [comment]
那你可以先把旧域名记录删除，不过这样也没有用啊

**Comment by CCCAUCHY** [comment]
> 那你可以先把旧域名记录删除，不过这样也没有用啊

旧域名删了就不能获取新的IP地址了, 防止DNS历史记录只能同时更换两者

**Comment by jeessy2** [comment]
那你手工更新吧。不知道你为何要这样做，不管你怎么折腾，如果想知道你历史记录，怎么都是有法的
