### ISSUE TITLE
之前可以，最近没管，发现总是DNS失败

### ISSUE THREAD

**Issue by murazi** [jeessy2/ddns-go#819]
### 问题描述

用的CF运营商，之前没问题的

最近没怎么用，刚访问时发现错误，以后是不小心动了密钥导致不一致，所以重新下发了密钥，发现还是失败，重新下发了几次的密钥都不行，一直报错

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

1.2.0

### 安装方式

服务

### 额外信息

2023/08/15 07:11:13 请求接口https://api.cloudflare.com/client/v4/zones?name=我的域名&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=我的域名&status=active&per_page=50": read tcp 我的本地IP:端口->104.19.193.29:443: read: connection reset by peer

**Comment by WaterLemons2k** [comment]
收到 TCP RST，可能是 `api.cloudflare.com` 被墙。
