### ISSUE TITLE
希望增加http代理接口，以解决近期Cloudflare无法访问的问题

### ISSUE THREAD

**Issue by nixingshiguang** [jeessy2/ddns-go#820]
### 功能描述

创建docker容器是，可通过添加环境变量例如HTTP_PROXY，把自己的http代理链接填上

### 解决的问题

坐标广东佛山，最近无法访问Cloudflare，官网也打不开，希望增加此功能解决网络问题

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by WaterLemons2k** [comment]
已支持从变量获取代理，只需添加变量即可：

```sh
HTTPS_PROXY=http://127.0.0.1:7890 ./ddns-go
```

参考：
- https://pkg.go.dev/net/http#ProxyFromEnvironment
- #700 #744

**Comment by nixingshiguang** [comment]
> 已支持从变量获取代理，只需添加变量即可：
> 
> ```shell
> HTTPS_PROXY=http://127.0.0.1:7890 ./ddns-go
> ```
> 
> 参考：
> 
> * https://pkg.go.dev/net/http#ProxyFromEnvironment
> * [[功能]：webhook使用代理 #700](https://github.com/jeessy2/ddns-go/issues/700) [[功能]：请求通过socks5代理访问DDNS API #744](https://github.com/jeessy2/ddns-go/issues/744)

谢谢，是我疏忽了，忘了看关了的issue
