### ISSUE TITLE
Windows客户端腾讯云dnspod解析失败

### ISSUE THREAD

**Issue by CleMooling** [jeessy2/ddns-go#824]
### 问题描述

输入了正确的信息，但是程序不进行任何解析
重启程序也没有用

### DNS服务商

腾讯云

### 是否已搜索同类问题

未搜索

### 操作系统

Windows

### 架构

x86_64

### 版本

最新

### 安装方式

其它

**Comment by WaterLemons2k** [comment]
先看一下配置和日志，敏感信息打码
