### ISSUE TITLE
获取ip错误

### ISSUE THREAD

**Issue by rickychaw** [jeessy2/ddns-go#825]
### 问题描述

查阅了历史Issue，有人遇到类似的情况，不过是时区错误。按照相关思路排除了时区问题，本机时间也正确.

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### 版本

5.6.1

### 安装方式

Docker

### 额外信息

2023/08/25 13:33:49 连接失败! <a target='blank' href='https://myip4.ipip.net'>点击查看接口能否返回IPv4地址</a>
2023/08/25 13:33:49 错误信息: Get "https://myip4.ipip.net": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2023-08-25T13:33:49+08:00 is after 2023-08-24T23:59:59Z

**Comment by jeessy2** [comment]
https://myip4.ipip.net/ 的证书过期了。换个接口或等待ipip修复

**Comment by rickychaw** [comment]
好，多谢解答
