### ISSUE TITLE
namesilo api key失败！Deatil: Invalid API Key (Permission denied)

### ISSUE THREAD

**Issue by pot11** [jeessy2/ddns-go#827]
### 问题描述

namesilo 修改失败！Deatil: Invalid API Key (Permission denied)，key是对的还是显示失败

### 是否已搜索同类问题

未搜索

### 操作系统

Windows

### 架构

i386

### 版本

5.6.0

### 安装方式

其它

**Comment by WaterLemons2k** [comment]
生成 API Key 时是不是勾选了 `Generate key for read-only access`？

**Comment by pot11** [comment]
确实是因为勾选了 Generate key for read-only access，导致失败的；重新生成key好使了，已解决，谢谢大佬
