### ISSUE TITLE
ddns-go5.6.1无法解析cloudflare的域名

### ISSUE THREAD

**Issue by zzfree2021** [jeessy2/ddns-go#828]
### 问题描述

2023/08/30 12:41:29 请求接口https://api.cloudflare.com/client/v4/zones?name=xxxx.xyz&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=xxxx.xyz&status=active&per_page=50": net/http: invalid header field value for "Authorization"

群晖6的docker安装的ddns-go v5.6.1无法正确解析，token是对的，产生了新的也是这个错误！

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

5.6.1

### 安装方式

Docker

**Comment by WaterLemons2k** [comment]
看一下配置文件

**Comment by zzfree2021** [comment]
docker加上了映射目录的命令-v /volume1/docker/ddns:/root，看不到配置文件呢

**Comment by WaterLemons2k** [comment]
试一下 `docker cp` 命令：

```sh
docker cp ddns-go:/root/.ddns_go_config.yaml .
```

**Comment by sad-castle** [comment]
m1 macbook macos14 也遇到了这个问题。

**Comment by sad-castle** [comment]
2023/09/01 14:52:55 监听 :9876 ...
2023/09/01 14:52:55 IPv6将使用第 1 个IPv6地址
2023/09/01 14:52:55 请求接口https://api.cloudflare.com/client/v4/zones?name=*******.top&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=******.top&status=active&per_page=50": EOF

**Comment by sad-castle** [comment]
好像跟访问cf的网络环境有关，换了个代理的节点，现在可以了。
