### ISSUE TITLE
ipv6公网ip消失

### ISSUE THREAD

**Issue by zui-lang** [jeessy2/ddns-go#829]
### 问题描述

在unraid的docker中部署ddns-go，host模式，有时候半固定的ipv6公网地址会消失，只会出现临时ip，重启后才能再次获取到半固定v6

### DNS服务商

Cloud flare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v5.6.1

### 安装方式

Docker

### 额外信息

![354F17FC-B878-47DF-92F5-A765A8780F88](https://img.gugu.ovh/i/2023/08/30/lxjw92.webp)

**Comment by jeessy2** [comment]
找下其它原因，ddns-go只是读的网卡IPv6
