### ISSUE TITLE
Webhook通知问题

### ISSUE THREAD

**Issue by zhang-001** [jeessy2/ddns-go#830]
### 问题描述

Webhook点测试可以收到通知  但是ip变动就收不到通知   用的爱语飞飞
![2023-08-31_09-14-45](https://github.com/jeessy2/ddns-go/assets/48820292/ab876cd2-7c87-47f0-bcf8-114b5aa9cf87)

![微信图片_20230831091610](https://github.com/jeessy2/ddns-go/assets/48820292/0e2e2064-0598-453a-b3ad-e5fd717a080f)

### DNS服务商

DnsPod

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

5.6.1

### 安装方式

Docker

**Comment by WaterLemons2k** [comment]
只有域名更新成功或失败、通过接口获取IP失败超过3次才会通知。

没看到域名更新。

**Comment by zhang-001** [comment]
> 只有域名更新成功或失败、通过接口获取IP失败超过3次才会通知。
> 
> 没看到域名更新。

![2023-08-31_09-14-45](https://github.com/jeessy2/ddns-go/assets/48820292/02685edf-98c0-4ef4-b074-380441d66ddc)
日志正常 就是没通知 很奇怪

**Comment by jeessy2** [comment]
你是不是写错了，Requestbody中是URL传参的写法。应该直接写到URL中

**Comment by zhang-001** [comment]
> 你是不是写错了，Requestbody中是URL传参的写法。应该直接写到URL中

可以手动测试是正常的
