### ISSUE TITLE
能否增加一个正式的登入页面，K8S探针报401错误

### ISSUE THREAD

**Issue by SadBoen** [jeessy2/ddns-go#831]
### 功能描述

能否增加一个正式的登入页面，K8S探针报401错误（设置密码登陆的时候）。
用的是Truenas，truechart的包。

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
可以用TCP探针
