### ISSUE TITLE
希望增加代理设置，通过代理去调解析接口。

### ISSUE THREAD

**Issue by goodking-bq** [jeessy2/ddns-go#833]
### 问题描述

同样的KEY ，我在我两个电脑上，一个能成功，一个不能。
```
2023/09/02 22:03:29 请求接口https://api.godaddy.com/v1/domains/golker.xyz/records/AAAA/work-bankup失败! ERROR: Put "https://api.godaddy.com/v1/domains/XXX.xyz/records/AAAA/work-bankup": dial tcp 199.59.148.9:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2023/09/02 22:03:29 更新域名解析 work-bankup.golker.xyz 失败！
```

### DNS服务商

GoDaddy

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v5.6.1

### 安装方式

服务

### 额外信息

2023/09/02 22:03:29 请求接口https://api.godaddy.com/v1/domains/xxx.xyz/records/AAAA/work-bankup失败! ERROR: Put "https://api.godaddy.com/v1/domains/XXX.xyz/records/AAAA/work-bankup": dial tcp 199.59.148.9:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2023/09/02 22:03:29 更新域名解析xxx.xxx.xyz 失败！

![image](https://github.com/jeessy2/ddns-go/assets/7803202/33aa6f8f-f6f5-440e-8caa-5980dc7e9183)

**Comment by WaterLemons2k** [comment]
`ddns-go` 从变量获取代理，所以只需添加 `HTTPS_PROXY` 变量即可：

```sh
HTTPS_PROXY=http://127.0.0.1:7890 ./ddns-go
```

参考：
- https://pkg.go.dev/net/http#ProxyFromEnvironment
- #700
- #744
- #820

**Comment by goodking-bq** [comment]
windows 服务怎么弄呢，不想弄全局代理？

**Comment by WaterLemons2k** [comment]
> windows 服务怎么弄呢，不想弄全局代理？

打开注册表，转至 `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\ddns-go`。

新建数值名称为 `Environment` 的多字符串值（REG_MULTI_SZ），将其数值数据修改为：

```
HTTPS_PROXY=http://127.0.0.1:7890
```

最后重启 `ddns-go` 服务。

参考：https://serverfault.com/a/1103091

**Comment by goodking-bq** [comment]
谢谢 非常有用

**Comment by jeessy2** [comment]
@goodking-bq 问之前先搜索下issues, 都不知道多少人在问了，每次都重复的这个问题
