### ISSUE TITLE
希望添加自动更新DDNS-GO的功能

### ISSUE THREAD

**Issue by simin-in-tw** [jeessy2/ddns-go#834]
### 功能描述

希望添加自动更新DDNS-GO的功能

### 解决的问题

避免忘了更新而一直使用旧版本

### 附加信息

文件下载源建议可选Github官方地址和加速地址，避免中国部分地区无法访问Github出现下载失败的问题。

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
5.6.0后已增加，只能从GitHub下载，无加速地址。
使用方式：
./ddns-go -u
