### ISSUE TITLE
Webhook 5分钟通知一次太频繁了

### ISSUE THREAD

**Issue by zhuhaisto** [jeessy2/ddns-go#839]
### 功能描述

能不能成功更改ip后才通知一下啊 也就是ip有变化才通知啊 没变化不用通知啊 

这个怎么设置

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
有变化或者异常才通知，没变化不会通知的

**Comment by zhuhaisto** [comment]
基本就是五分钟一次 没有改变他也通知了

**Comment by zhuhaisto** [comment]
![image](https://github.com/jeessy2/ddns-go/assets/108032980/99af677f-40c1-4e32-9771-1b1d646cc2a0)
没变化也通知啊 一晚上50多条了 就是五分钟一次

**Comment by jeessy2** [comment]
什么服务商，什么版本
