### ISSUE TITLE
关于虚拟机ipv6无法获取的问题

### ISSUE THREAD

**Issue by Bingaw12** [jeessy2/ddns-go#84]
我试着使用虚拟机搭建docker，并开始设置时发现ipv6无论是用接口获取，还是网卡均无法获取ipv6地址，并且网卡提示没有找到可用的网卡。

**Comment by Bingaw12** [comment]
系统CentOS7

**Comment by jeessy2** [comment]
是的。虚拟机貌似获取不到。文档中有说明

**Comment by Ryker97** [comment]
你试下hosts网络

**Comment by jeessy2** [comment]
> 你试下hosts网络

和host网络关系不大
