### ISSUE TITLE
ipv4变更是5分钟刷新一次会不会慢了点

### ISSUE THREAD

**Issue by zhuhaisto** [jeessy2/ddns-go#841]
### 功能描述

如题，不能变更ip后就直接刷新解析的ip吗？
如果网卡获取获取的是局域网的ipv4，如果是接口获取好像是5分钟一次
有没有啥办法能马上获取ip，然后操作的呢？局域网内

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
可以设置的，具体看文档

**Comment by zhuhaisto** [comment]
设置间隔时间短了 会不会被封ip
