### ISSUE TITLE
CF ddns报错

### ISSUE THREAD

**Issue by YJJ-228** [jeessy2/ddns-go#843]
### 问题描述

 请求接口 https://api.cloudflare.com/client/v4/zones?name=alistofyjj.top&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400
安装在电脑上的，用的是CF的域名和token(.top的)，这个情况怎么解决

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v5.6.1

### 安装方式

其它

**Comment by jeessy2** [comment]
#308
