### ISSUE TITLE
阿里云解析ipv6提示接口失败

### ISSUE THREAD

**Issue by qianzi110** [jeessy2/ddns-go#847]
### 问题描述

![IMG_20230909_153605](https://github.com/jeessy2/ddns-go/assets/103056213/ee985085-4f62-4568-8109-2056c323ef2d)

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

未搜索

### 操作系统

Linux

### 架构

arm64

### 版本

5.6.1

### 安装方式

服务

**Comment by WaterLemons2k** [comment]
检查网络，超时了

**Comment by qianzi110** [comment]
等待网络连接：Get "https://alidns.aliyuncs.com/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)。5s 后重试...,（这是什么问题，服务器能连上网啊，怎么这个就连不上了？不支持ipv6吗）

**Comment by qianzi110** [comment]
> 检查网络，超时了

怎么会这样呢？不支持ipv6吗？同样的阿里云ak，解析ipv4就没问题

**Comment by ryjer** [comment]
有没有可能，你的局域网不支持ipv6，或者你的路由器不解析ipv6 dns请求
