### ISSUE TITLE
如何修改界面UI默认暗黑模式

### ISSUE THREAD

**Issue by lcuwx2016** [jeessy2/ddns-go#848]
### 问题描述

每次启动界面都手动修改UI，比较麻烦

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### 版本

v5.6

### 安装方式

Docker

**Comment by jeessy2** [comment]
跟随系统的，把你系统设置为暗黑模式就可以
