### ISSUE TITLE
CF多IP负载均衡+坏点切换

### ISSUE THREAD

**Issue by Pinkyou1** [jeessy2/ddns-go#849]
### 功能描述

是否可以增加，定期检测 IP 地址的可用性，并在发现故障时自动更新 DNS 记录以切换到其他 IP 地址

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
你可以自己写个脚本试试，可以通过命令行获取IP

**Comment by Pinkyou1** [comment]
ddnsgo是支持 多IP同一域名的下的 负载均衡 坏点切换 吗？

如果都是静态IP的话，是否可以用 -f 10 -cacheTimes 10 来控制ddns的修改速度

**Comment by jeessy2** [comment]
cf不支持多IP，阿里云等可以通过自定义参数实现

可以

**Comment by Pinkyou1** [comment]
A B C 三个DDNS 同一域名下 

如果B机器关机，那么A、C是否可以自动顶替掉B呢

**Comment by jeessy2** [comment]
不可以。这不是DDNS的范畴

**Comment by Pinkyou1** [comment]
好的，谢谢您的回答
