### ISSUE TITLE
无法获取ipv6地址

### ISSUE THREAD

**Issue by SIGHTDEEP** [jeessy2/ddns-go#851]
### 问题描述

- pve 里iStoreOS安装
- ipv4获取没问题
- pve可以获取ipv6地址，没问题
- 虚拟机iStoreOS 通过ip addr 可以看到ipv6 地址（公网），但curl  ipv6地址不通

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v1.2.0

### 安装方式

服务

### 额外信息

日志信息
<img width="424" alt="image" src="https://github.com/jeessy2/ddns-go/assets/20434364/d94aa855-25bd-4c0b-bf64-f54c93d7e9ad">

有ipv6地址
<img width="926" alt="image" src="https://github.com/jeessy2/ddns-go/assets/20434364/969a3126-b8c9-422d-8c28-f8ed58e5ced0">

curl 不通
<img width="450" alt="image" src="https://github.com/jeessy2/ddns-go/assets/20434364/f198bd7a-29ac-45a8-a395-2c6bdf6c02e2">

**Comment by jeessy2** [comment]
虛擬機中使用可能會有IPv6不通, 試下非虛擬機能通不

**Comment by SIGHTDEEP** [comment]
> 虛擬機中使用可能會有IPv6不通, 試下非虛擬機能通不

pve 里面是可以通的

**Comment by SIGHTDEEP** [comment]
> 虛擬機中使用可能會有IPv6不通, 試下非虛擬機能通不

已经重新开了一个虚拟机安装可以了，可能是istoreOs 网络哪里有问题
