### ISSUE TITLE
@3 域名不正确

### ISSUE THREAD

**Issue by caticat** [jeessy2/ddns-go#853]
### 问题描述

使用@1,@2,@3之类的匹配ip的时候会定时报错

类似这种:
2023/09/12 10:43:11 @3 域名不正确
2023/09/12 10:43:11 IPv6将使用第 3 个IPv6地址
2023/09/12 10:43:11 IPv6未改变，将等待 1 次后与DNS服务商进行比对

不确定这种报错通知是否影响使用

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v5.6.1

### 安装方式

服务

**Comment by jeessy2** [comment]
域名填错了吧。

**Comment by caticat** [comment]
实际是可以正确更新Cloudflare的IP地址信息.

咨询一下Domains添法格式,下面哪种是正确的?

- 添法1
```
ddns:a.b.com
:a1.b1.com
:a2.b2.com
```

- 添法2
```
ddns:a.b.com
ddns:a1.b1.com
ddns:a2.b2.com
```

- 添法3
```
a.b.com
:a1.b1.com
:a2.b2.com
```

- 添法4
```
a.b.com
a1.b1.com
a2.b2.com
```

**Comment by caticat** [comment]
> 域名填错了吧。

实际是可以正确更新Cloudflare的IP地址信息.

咨询一下Domains添法格式,下面哪种是正确的?

- 添法1
```
ddns:a.b.com
:a1.b1.com
:a2.b2.com
```

- 添法2
```
ddns:a.b.com
ddns:a1.b1.com
ddns:a2.b2.com
```

- 添法3
```
a.b.com
:a1.b1.com
:a2.b2.com
```

- 添法4
```
a.b.com
a1.b1.com
a2.b2.com
```

**Comment by jeessy2** [comment]
都对d

**Comment by caticat** [comment]
这两天我配好环境再试试吧.3q~
