### ISSUE TITLE
内网最好不要检测弱密码

### ISSUE THREAD

**Issue by canoziia** [jeessy2/ddns-go#860]
### 功能描述

感觉内网检测弱密码不是很必要，而且现在的情况是禁止内网时，可以不进行验证，但是不可以弱密码，有点怪。或者加一个跳过检测弱密码的选项，并且给个警告？

### 解决的问题

内网设置简单密码时不允许保存

### 检查清单

- [x] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
内网也有可能被扫。。你想被扫？

**Comment by canoziia** [comment]
> 内网也有可能被扫。。你想被扫？

如果别人已经在内网扫了，那密码还有意义吗

**Comment by jeessy2** [comment]
有意义，防止被爆破

**Comment by jeessy2** [comment]
亲身经历，其它项目存在漏洞，被上传木马，内网被攻破后，会继续扫内网其它弱口令机器

**Comment by canoziia** [comment]
大概明白了，但是现在内网好像还可以允许空账号密码？如果是这样的话是不是应该考虑内网也必须设置密码

**Comment by jeessy2** [comment]
允许，如果是进行“修改密码”、“设置通过命令获取”，会强制要求启动时间在五分钟内
