### ISSUE TITLE
威联通 docker 版本重启docker后配置会丢失

### ISSUE THREAD

**Issue by xheia** [jeessy2/ddns-go#861]
### 问题描述

忘记从哪个版本开始发生了了，目前版本是5.6.0，威联通 docker 版本重启docker后配置会丢失，不知是否脚本问题？
脚本如下：

version: '3.3'
services:
    ddns-go:
        container_name: ddns-go
        restart: unless-stopped
        ports:
            - '9876:9876'
        volumes:
            - '/opt/ddns-go:/root'
        image: jeessy/ddns-go
        network_mode: host

### 是否已搜索同类问题

未搜索

### 操作系统

Linux

### 架构

i386

### 版本

5.6.0

### 安装方式

Docker

**Comment by jeessy2** [comment]
保存后，查看/opt/ddns-go是否有一个隐藏文件

**Comment by lei-mu** [comment]
我的配置也没了，我以为主机炸了，吓死。在容器控制台 ls -a 只有一个ddns-go 文件。
昨天 通过 docker pull ... 
然后再urnaid docker 可视化控制台 点击更新  今天配置就没了

**Comment by lei-mu** [comment]
> > 我的配置也没了，我以为主机炸了，吓死。在容器控制台 ls -a 只有一个ddns-go 文件。
> > 昨天 通过 docker pull ...
> > 然后再urnaid docker 可视化控制台 点击更新  今天配置就没了
> 
> 检查配置，必须挂载目录，如没正确挂载，更新会丢失配置的

解决了。路径映射没了，加上就好了
