### ISSUE TITLE
ddns-go反代后显示异常

### ISSUE THREAD

**Issue by ilisuo** [jeessy2/ddns-go#862]
### 问题描述

使用Apache进行反代。反代后界面没有元素，只有文字。请问需要做什么操作？
![屏幕快照 2023-09-17 的 20 49 03 下午](https://github.com/jeessy2/ddns-go/assets/108167575/f3062cd8-7d4a-49fc-9622-5c5a16426648)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

macOS (Darwin)

### 架构

arm64

### 版本

v5.6.2

### 安装方式

服务

**Comment by WaterLemons2k** [comment]
看起来像反代后没加载 CSS，看下 Nginx 配置文件和 DevTools。

**Comment by ilisuo** [comment]
> 看起来像反代后没加载 CSS，看下 Nginx 配置文件和 DevTools。
![WeChat9518b173befece21d160e1304a295645](https://github.com/jeessy2/ddns-go/assets/108167575/741979d3-085f-44df-a56a-957e79fa0dc7)

<IfModule mod_proxy.c>
    ProxyRequests Off
    SSLProxyEngine on
    ProxyPass /dns http://192.168.50.10:9876/
    ProxyPassReverse /dns http://192.168.50.10:9876/
    </IfModule>

**Comment by ilisuo** [comment]
关了吧 不用 路径反代了
