### ISSUE TITLE
aliyun解析失败！不知道有没有解决办法？安装的windows版本

### ISSUE THREAD

**Issue by shaoj0013** [jeessy2/ddns-go#864]
### 问题描述

2023/09/20 21:31:25 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"EE33587F-A5A5-5C53-BFCF-E0F5115DB659","Message":"Specified time stamp or date value is expired.","Recommend":"https://api.aliyun.com/troubleshoot?q=InvalidTimeStamp.Expired&product=Alidns","HostId":"alidns.aliyuncs.com","Code":"InvalidTimeStamp.Expired"} ,返回状态码: 400

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v5.6.2

### 安装方式

服务

### 额外信息

2023/09/20 21:31:25 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"EE33587F-A5A5-5C53-BFCF-E0F5115DB659","Message":"Specified time stamp or date value is expired.","Recommend":"https://api.aliyun.com/troubleshoot?q=InvalidTimeStamp.Expired&product=Alidns","HostId":"alidns.aliyuncs.com","Code":"InvalidTimeStamp.Expired"} ,返回状态码: 400

**Comment by WaterLemons2k** [comment]
时间不对。

参考：
- [https://github.com/jeessy2/ddns-go/wiki/FAQ#阿里云错误代码-invalidtimestampexpired](https://github.com/jeessy2/ddns-go/wiki/FAQ#%E9%98%BF%E9%87%8C%E4%BA%91%E9%94%99%E8%AF%AF%E4%BB%A3%E7%A0%81-invalidtimestampexpired)

- #49
- #192
- #194
- #210
- #693

**Comment by shaoj0013** [comment]
谢谢
