### ISSUE TITLE
建议增加name.com域名解析，或Webhook增加自定义方法

### ISSUE THREAD

**Issue by sqguokai** [jeessy2/ddns-go#865]
### 功能描述

name.com修改域名解析使用PUT方法，无法在Webhook更新，建议增加name.com解析，或者在Webhook可以自定义使用post或get,put方法

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
可以把nameserver改到已有的服务商，服务商太多，支持不过来

**Comment by ItzMiracleOwO** [comment]
不会callback就用cloudflare
