### ISSUE TITLE
ipv6获取方式

### ISSUE THREAD

**Issue by z65689880q** [jeessy2/ddns-go#869]
### 功能描述

1：ipv6通过MAC ，DUID 方式获取（参考爱快，萌新选项）
2：通过指令获取（参考lucky这个就是高手倾向了）
3：自带筛选检测功能，因为一台设备长期开机可能很多IPV6 240地址，但是其中只有一个或多个有效。
4：如果3无法实现，那就添加一个筛选指令，最好页面上有一个筛选指令怎么设置的详细教程.........

### 解决的问题

可以ddns指定设备的有效ipv6公网地址，做到一个域名N台设备，不必去记录繁多的端口号。a电脑就a.abc.com：b电脑就是b.abc.com：nas就是nas.abc.com。同时因为大部分地区运营商ipv6有80和443端口，window电脑的远程连接即可以实现域名直连，nas通过改为80端口实现域名访问。

### 附加信息

更多ipv6获取方式，其他ddns都是渣渣

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by z65689880q** [comment]
选项2已经实现了   大家可以无视了  /捂脸

**Comment by wy580477** [comment]
我之前搓了简易脚本，可以设置关键字过滤。

https://github.com/jeessy2/ddns-go/discussions/732

**Comment by z65689880q** [comment]
收到 非常感谢大佬

wy580477 ***@***.***> 于2023年9月30日周六 20:20写道：
