### ISSUE TITLE
希望添加luci面板

### ISSUE THREAD

**Issue by tedcriss** [jeessy2/ddns-go#871]
### 功能描述

希望能够添加一个luci面板，方便添加到openwrt中，应该是要把网页服务那一套用luci的重新搞一下，后端还是现在的，就够了。

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by WaterLemons2k** [comment]
参考：[sirpdboy/luci-app-ddns-go](https://github.com/sirpdboy/luci-app-ddns-go)
