### ISSUE TITLE
希望ipv6地址获取可以根据valid_lft或preferred_lft排序选择

### ISSUE THREAD

**Issue by ryjer** [jeessy2/ddns-go#872]
### 功能描述

根据`ip`命令中的ipv6相关信息
```bash
$ ip -6 addr show ens192
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    altname enp11s0
    inet6 fd00:8214:d450::1234/128 scope global dynamic noprefixroute 
       valid_lft 36214sec preferred_lft 36214sec
    inet6 2408:9e22:6618:8c80::cd9/128 scope global dynamic noprefixroute 
       valid_lft 36214sec preferred_lft 36214sec
    inet6 2408:9e22:6618:8c80:20c:29ff:febb:ca5b/64 scope global dynamic noprefixroute 
       valid_lft 247516sec preferred_lft 161116sec
    inet6 fd00:8214:d450:0:20c:29ff:febb:ca5b/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:febb:ca5b/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```
根据valid_lft (有效使用期限) 和 preferred_lft (首选生存期)信息。可以找出最新分配的ipv6地址，这个最新的ip地址就是最近一次拨号后生成的最新ipv6地址

我希望IPv6功能中`通过网卡获取`后可以添加根据 `valid_lft`或`preferred_lft` 的**剩余时间**排序选择的功能，这样可以通过选择剩余时间最长的ipv6进行准确的ddns

### 解决的问题

家用宽带虽然提供了ipv6公网地址，但是家用宽带会定期进行pppoe重播。
重播会分配不同的ipv6前缀，但局域网内的设备在路由重播后并不会将之前的ipv6前缀删除，而是继续根据新的ipv6前缀生成新的ip。
这样经过几次重播后，局域网设备就会累积大量的ipv6地址，但其中只有1个是可用的。而且这些ipv6地址在ddns-go中的顺序有相当的随意性，无法使用`@数字`的方式准确选择正确地址

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
感觉可以通过命令获取，脚本自行研究

**Comment by yin1999** [comment]
其实可以考虑使用脚本把旧的IPv6地址删掉（如果路由器支持的话，也可以用路由器主动发送弃用报文），如果不去清除或弃用旧IPv6地址，主机也没法使用默认路由访问外网IPv6服务器。我之前写了一个自动删除旧IPv6地址的脚本：https://gist.github.com/yin1999/cfa50d5b9342380f003631a2ac683ea3

**Comment by bingood** [comment]
我是通过命令获取实现如上功能的，你可以试试
`ip addr show|grep -v deprecated|grep -A1 'inet6 [^f:]'|grep -v ^--|sed -nr ':a;N;s#^ +inet6 ([a-f0-9:]+)/.+? scope global .*? valid_lft ([0-9]+sec) .*#\2 \1#p;Ta'|sort -nr|head -n1|cut -d' ' -f2`

**Comment by lialongA** [comment]
window可以用这个命令 (Get-NetIPAddress |     Where-Object {         $_.AddressFamily -eq 23 -and         $_.SuffixOrigin -ne "Deprecated" -and         $_.Type -eq "Unicast" -and         $_.IPAddress -notlike "fe80*" -and         $_.IPAddress -ne "::1"     } |     Sort-Object -Property ValidLifetime -Descending |     Select-Object -First 1).IPAddress
