### ISSUE TITLE
windows端怎么开机自启呢

### ISSUE THREAD

**Issue by SparkCD** [jeessy2/ddns-go#878]
### 功能描述

windows端怎么开机自启呢

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
首页有说明。问之前先看文档。
Win(以管理员打开cmd): .\ddns-go.exe -s install

**Comment by SparkCD** [comment]
> 首页有说明。问之前先看文档。 Win(以管理员打开cmd): .\ddns-go.exe -s install

好的 我尝试过 .\ddns-go.exe -s install   重启后web就进不去了  后台还是掉了 我看看怎么回事

**Comment by jeessy2** [comment]
自己检查下，进入服务查看是否正常
