### ISSUE TITLE
二级地域域名，xx.cn  把xx给解析成主机记录了

### ISSUE THREAD

**Issue by yang799830374** [jeessy2/ddns-go#882]
### 问题描述

二级地域域名，比如我的域名 yw.hk.cn， yw会被识别成主机记录也就是当作二级域名去解析，其实应该是@一级域名的
，这种应该如何正确识别

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

i386

### 版本

v3.7.2

### 安装方式

Docker

**Comment by WaterLemons2k** [comment]
可使用冒号手动分隔主机记录，Domains 下方有说明。

如：`ddns.yw.hk.cn` -> `ddns:yw.hk.cn`

**Comment by yang799830374** [comment]
好的明白了，A类型就是 @:yw.hk.cn 对吧 ，我试试
