### ISSUE TITLE
ddns-go 有安装命令，有重启命令，为啥没有停止命令呢

### ISSUE THREAD

**Issue by gax888** [jeessy2/ddns-go#883]
### 问题描述

ddns-go 有安装命令，有重启命令，为啥没有停止命令呢】
在 linux下如何停止该服务，试了正常的停止命令都不行。
请大佬给出，谢谢。

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

i386

### 版本

5.6.2

### 安装方式

Docker

### 额外信息

ddns-go 有安装命令，有重启命令，为啥没有停止命令呢】
在 linux下如何停止该服务，试了正常的停止命令都不行。
请大佬给出，谢谢。

**Comment by WaterLemons2k** [comment]
试一下 `sudo systemctl stop ddns-go`

**Comment by gax888** [comment]
> 试一下`sudo systemctl stop ddns-go`

感谢，大佬，我试试

**Comment by gax888** [comment]
> 试一下`sudo systemctl stop ddns-go`

停止了，服务又启不了了

**Comment by WaterLemons2k** [comment]
> 停止了，服务又启不了了

启动用 `sudo systemctl start ddns-go`

**Comment by gax888** [comment]
> > 停止了，服务又启不了了
> 
> 启动用 `sudo systemctl start ddns-go`

试过了，好像没用

**Comment by WaterLemons2k** [comment]
> 试过了，好像没用

用 `sudo systemctl status ddns-go` 看下服务状态

**Comment by gax888** [comment]
> > 试过了，好像没用
> 
> 用 `sudo systemctl status ddns-go` 看下服务状态

状态失败。详细如下:
dns-go.service - 
   Loaded: loaded (/etc/systemd/system/ddns-go.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Fri  ; 1min 22s ago
           `- ConditionFileIsExecutable=/home/ddnsgo/ddns-go was not met

**Comment by WaterLemons2k** [comment]
> 状态失败。详细如下: dns-go.service - Loaded: loaded (/etc/systemd/system/ddns-go.service; enabled; vendor preset: enabled) Active: inactive (dead) Condition: start condition failed at Fri ; 1min 22s ago `- ConditionFileIsExecutable=/home/ddnsgo/ddns-go was not met

文件 `/home/ddnsgo/ddns-go` 存在并可以执行吗？

**Comment by gax888** [comment]
> > 状态失败。详细如下: dns-go.service - Loaded: loaded (/etc/systemd/system/ddns-go.service; enabled; vendor preset: enabled) Active: inactive (dead) Condition: start condition failed at Fri ; 1min 22s ago `- ConditionFileIsExecutable=/home/ddnsgo/ddns-go was not met
> 
> 文件 `/home/ddnsgo/ddns-go` 存在并可以执行吗？

感谢大佬，文件下错了，谢谢

**Comment by gax888** [comment]
> > 状态失败。详细如下: dns-go.service - Loaded: loaded (/etc/systemd/system/ddns-go.service; enabled; vendor preset: enabled) Active: inactive (dead) Condition: start condition failed at Fri ; 1min 22s ago `- ConditionFileIsExecutable=/home/ddnsgo/ddns-go was not met
> 
> 文件 `/home/ddnsgo/ddns-go` 存在并可以执行吗？

文件下错了，已经正常了，再次感谢

**Comment by geitwhat** [comment]
sudo systemctl daemon-reload

**Comment by geitwhat** [comment]
sudo systemctl daemon-reload
sudo systemctl restart ddns-go
