### ISSUE TITLE
web监听v4地址

### ISSUE THREAD

**Issue by CCCAUCHY** [jeessy2/ddns-go#885]
### 问题描述

`./ddns-go -l 0.0.0.0:9876 `不会监听v4地址, 无法用v4地址访问, 只能使用私网地址来监听, 但是我想要同时监听v4和v6地址的

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v5.6.3

### 安装方式

服务

**Comment by WaterLemons2k** [comment]
https://pkg.go.dev/net#Listen

> For TCP networks, if the host in the address parameter is empty or a literal unspecified IP address, Listen listens on all available unicast and anycast IP addresses of the local system. 

试一下省略 host：`:9876`

**Comment by CCCAUCHY** [comment]
> https://pkg.go.dev/net#Listen
> 
> > For TCP networks, if the host in the address parameter is empty or a literal unspecified IP address, Listen listens on all available unicast and anycast IP addresses of the local system.
> 
> 试一下省略 host：`:9876`

默认就是这样, 不行

**Comment by WaterLemons2k** [comment]
见过 `被禁止从公网访问!` 之类的日志吗？

**Comment by CCCAUCHY** [comment]
> 见过 `被禁止从公网访问!` 之类的日志吗？

没有, 而且我取消了禁止公网访问, 而且勾选公网访问时通过ipv6也可以访问

**Comment by WaterLemons2k** [comment]
> 没有, 而且我取消了禁止公网访问, 而且勾选公网访问时通过ipv6也可以访问

如果通过公网 IPv4 访问，请确保已取得公网 IP、映射了 ddns-go 端口并开放了防火墙。

**Comment by CCCAUCHY** [comment]
> > 没有, 而且我取消了禁止公网访问, 而且勾选公网访问时通过ipv6也可以访问
> 
> 如果通过公网 IPv4 访问，请确保已取得公网 IP、映射了 ddns-go 端口并开放了防火墙。

我在云上部署的

**Comment by WaterLemons2k** [comment]
> 我在云上部署的

那请确保已在云服务提供商和系统防火墙中开放端口，然后检查端口是否打开。

**Comment by CCCAUCHY** [comment]
> > 我在云上部署的
> 
> 那请确保已在云服务提供商和系统防火墙中开放端口，然后检查端口是否打开。

确保, 非常确保了
