### ISSUE TITLE
Openwrt每次重启都提示DNS回环，但是已经修改过-dns

### ISSUE THREAD

**Issue by Faramitas** [jeessy2/ddns-go#886]
### 问题描述

![Screenshot_20231014_231119_com microsoft emmx](https://github.com/jeessy2/ddns-go/assets/29322214/6dfc41bd-8d1c-4fdb-963c-e536bcba8a17)
必须手动开关服务一次 uninstall  然后install

总之每次重启完路由器，服务自启动是无效的，报上图错误，重启服务之后就正常了

路由器是360T7 刷的ImmortalWrt

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

armv7

### 版本

v6.5.3

### 安装方式

服务

**Comment by Faramitas** [comment]
![Screenshot_20231014_234152](https://github.com/jeessy2/ddns-go/assets/29322214/c41bd59a-af7b-48c6-910a-d194a328333b)
我已经设置了-dns，每次重启openwrt都不生效，还是提示超时

**Comment by WaterLemons2k** [comment]
> 我已经设置了-dns，每次重启openwrt都不生效，还是提示超时 就1.1.1.1不行 我用了主流的一些dns，基本都可以

试一下安装服务时设置 `-dns`：

```sh
./ddns-go -s install -dns 114.114.114.114
```

**Comment by Faramitas** [comment]
> > 我已经设置了-dns，每次重启openwrt都不生效，还是提示超时 就1.1.1.1不行 我用了主流的一些dns，基本都可以
> 
> 试一下安装服务时设置 `-dns`：
> 
> ```shell
> ./ddns-go -s install -dns 114.114.114.114
> ```

试过了，重启还是这样，甚至修改了init.d里的自启动文件，加上了"dns" "114.114.114.114"

**Comment by WaterLemons2k** [comment]
那看一下配置文件和日志：
- `/etc/config/network`
- `/etc/resolv.conf`
- `/etc/init.d/ddns-go`
- `/var/log/ddns-go.log`
- `/var/log/ddns-go.err`

**Comment by Faramitas** [comment]
> 那看一下配置文件和日志：
> 
> * `/etc/config/network`
> * `/etc/resolv.conf`
> * `/etc/init.d/ddns-go`
> * `/var/log/ddns-go.log`
> * `/var/log/ddns-go.err`

[ddns-go_.zip](https://github.com/jeessy2/ddns-go/files/12909091/ddns-go_.zip)

**Comment by jeessy2** [comment]
看日志，用114那个dns可以
