### ISSUE TITLE
使用 wget 命令请求 https 地址，产生巨量 ssl_client 僵尸进程

### ISSUE THREAD

**Issue by wy580477** [jeessy2/ddns-go#889]
### 问题描述

Debian 12 podman rootless 最新容器镜像

运行了一周以后产生了海量 ssl_client 僵尸进程。

![image](https://github.com/jeessy2/ddns-go/assets/98247050/aace2931-074f-4eb1-87c4-0189560daab1)

重启容器后仍然有 ssl_client 僵尸进程产生。

![image](https://github.com/jeessy2/ddns-go/assets/98247050/b300403a-af98-45d7-81ec-f3e412baa211)

我是使用 wget 命令获取 ip 地址的 ( wget -O - https://example.com)，观察结果是每次获取 ip，都会增加一个 ssl_client 僵尸进程，我把 wget 请求的地址从 https 改成 http，就正常了。

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v5.6.3

### 安装方式

Docker

**Comment by jeessy2** [comment]
怎么看出有巨量的
可通过接口获取合适些

**Comment by wy580477** [comment]
> 怎么看出有巨量的 可通过接口获取合适些

htop 命令看到的，翻了十几页都没翻完。每5分钟获取ip产生一个，一周下来就上千个了。

**Comment by jeessy2** [comment]
在Dockerfile中，未明确安装wget
可能自带的版本不同，使用`apk add wget`后未出现zombie

**Comment by wy580477** [comment]
> 在Dockerfile中，未明确安装wget 可能自带的版本不同，使用`apk add wget`后未出现zombie

自带的是 busybox wget，apk add wget 是 GNU wget，不是一回事了。

**Comment by jeessy2** [comment]
说明busybox的有问题吧。要不来PR在Dockerfile中安装

**Comment by wy580477** [comment]
> 说明busybox的有问题吧。要不来PR在Dockerfile中安装

想了一下，感觉没必要，绝大多数人不会这样用，用接口就行了，能在文档里提醒一下就好。

**Comment by jeessy2** [comment]
能简化处理处理就简化处理，不要为了改一个影响不大的问题，引入更多概念

**Comment by wy580477** [comment]
> 能简化处理处理就简化处理，不要为了改一个影响不大的问题，引入更多概念

我是考虑到其它命令说不定也会产生僵尸进程，所以想了一个通用解决方案。

**Comment by jeessy2** [comment]
其他有的情况下，可考虑。现在加tini感觉过早

**Comment by refeccd** [comment]
我这也发现了巨量的ssl_client，全部指向同一个进程，版本是最新的6.16.0
<img width="532" height="342" alt="Image" src="https://github.com/user-attachments/assets/62cad5ba-e054-40f5-850b-6b92a4f5e236" />
<img width="675" height="53" alt="Image" src="https://github.com/user-attachments/assets/110cdbb1-7b86-4304-a112-fe42bec03f0e" />

**Comment by refeccd** [comment]
看了下，一分钟一次，比较符合的就是如下命令了

<img width="945" height="213" alt="Image" src="https://github.com/user-attachments/assets/e302b1a7-1a3e-4dee-ab83-bbf81284ccb4" />

**Comment by refeccd** [comment]
@jeessy2 麻烦作者看一下这个问题吧

**Comment by jeessy2** [comment]
换个命令
