### ISSUE TITLE
不支持解析到DNSPOD的三级域名吗？

### ISSUE THREAD

**Issue by yubanmeiqin9048** [jeessy2/ddns-go#89]

**Comment by jeessy2** [comment]
支持的

**Comment by yubanmeiqin9048** [comment]
> 支持的

dnspod “s.ddns.example.xyz” 提示域名错误

**Comment by jeessy2** [comment]
刚试了. 支持的. 提示的什么错误

**Comment by yubanmeiqin9048** [comment]
> 刚试了. 支持的. 提示的什么错误

新增域名解析 s.ddns.example.xyz 失败！Code: 8, Message: 域名不正确，请输入主域名，如 dnspod.cn

**Comment by jeessy2** [comment]
不是主域名吗? 估计要添加主域名到dnspod

**Comment by yubanmeiqin9048** [comment]
> 不是主域名吗? 估计要添加主域名到dnspod

行吧
