### ISSUE TITLE
无法使用cloudflare的ddns解析API

### ISSUE THREAD

**Issue by 3469134108** [jeessy2/ddns-go#890]
### 问题描述

使用cloudflare的DNS API进行自动ddns解析，API尚未过期，刚开始时的API能正常使用一段时间，两天后便开始报错

`2023/10/21 10:55:28 请求接口 https://api.cloudflare.com/client/v4/zones?name=alistnas.xyz&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":9109,"message":"Invalid access token"}],"messages":[],"result":null} ,返回状态码: 403`
![Screenshot_20231021-110556_Edge](https://github.com/jeessy2/ddns-go/assets/103872353/71d34ee4-3eb6-4c53-a2fa-24d54b1c97c0)

![Screenshot_20231021-110701_Edge](https://github.com/jeessy2/ddns-go/assets/103872353/576300b7-f320-424e-a560-56d900d944db)

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

armv7

### 版本

v5.6.1

### 安装方式

服务

**Comment by jeessy2** [comment]
重新生成一个试试

**Comment by MilkTeaNo7** [comment]
重新生了也不行

**Comment by 3469134108** [comment]
- [ x ] 
已解决，此问题是由于**TTL时间设置过小**导致API频繁请求导致的，将其设置为`自动`或_大于10分钟_即可

**Comment by MilkTeaNo7** [comment]
> 已解决，此问题是由于 **TTL时间设置过小** 导致API频繁请求导致的，将其设置为`自动`或_大于10分钟_即可

并没有解决，TTL本来就是自动

**Comment by 35240** [comment]
我知道，如果是Cloudflare那么token要IPv6加IPv4地址

**Comment by 35240** [comment]
看他输出的日志，如果是查询域名信息发生异常! 返回内容: {"success":false,"errors":[{"code":9109,"message":"Cannot use the access token from location: ipv6"}],"messages":[],"result":null} ,返回状态码: 403 就要在token添加IPv6地址，IPv4填当前设备IP公网IP也行
