### ISSUE TITLE
无法再WEB保存配置，Ubuntu系统，openwrt也是 

### ISSUE THREAD

**Issue by waylin88** [jeessy2/ddns-go#891]
### 问题描述

无法再WEB保存配置，Ubuntu系统，openwrt也是 

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v5.6.3

### 安装方式

服务

**Comment by jeessy2** [comment]
详细描述并截图说明

**Comment by jeessy2** [comment]
换个浏览器试试

**Comment by hengzhao** [comment]
> 换个浏览器试试
确实，更新浏览器就好了
