### ISSUE TITLE
ddns-go 无法卸载

### ISSUE THREAD

**Issue by yhxxm** [jeessy2/ddns-go#892]
### 问题描述

ddns-go ip加9876 无法访问 宝塔里面放行了9876 还是进入不了设置网页 目前想卸载重装 输入命令 root@armbian:~# ./ddns-go -s uninstall-bash: ./ddns-go: No such file or directory 但是ddns-go目前运行中 之前设置的参数还是能用的

### DNS服务商

Cloudflare

### 是否已搜索同类问题

未搜索

### 操作系统

Linux

### 架构

arm64

### 版本

v5.6.3

### 安装方式

服务

**Comment by jeessy2** [comment]
目录下存在ddns-go文件否
