### ISSUE TITLE
配置好没反应

### ISSUE THREAD

**Issue by maomaokeai** [jeessy2/ddns-go#899]
### 问题描述

跳出网页配置后双击打开软件只有这两行字
2023/10/28 21:29:44 可使用 .\ddns-go.exe -s install 安装服务运行
2023/10/28 21:29:44 监听 :9876 ...
重启软件没用，阿里云后台也没有记录，完全没有反应

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

5.6.4

### 安装方式

其它

**Comment by jeessy2** [comment]
配置截图看下，重要信息打码

**Comment by maomaokeai** [comment]
> 配置截图看下，重要信息打码

谢谢，不用了，已经修好了，不好意思我发现忘了填写Domains里的域名而且也没错误提示直接保存成功了（≧﹏ ≦）

**Comment by wzdxy** [comment]
> > 配置截图看下，重要信息打码
> 
> 谢谢，不用了，已经修好了，不好意思我发现忘了填写Domains里的域名而且也没错误提示直接保存成功了（≧﹏ ≦）

谢谢老哥，救了命了，我也是忘了填写域名。
因为直接启动又没问题（忘了配置文件不同），装到docker里和安装成服务就都不行。
