### ISSUE TITLE
显示成功解析但是无法访问

### ISSUE THREAD

**Issue by RikkaLzw** [jeessy2/ddns-go#900]
### 问题描述

2023/10/29 17:42:57 配置文件已保存在: /root/.ddns_go_config.yaml
2023/10/29 17:43:00 你的IP fe80::146b:cc75:f2e4:e4** 没有变化, 域名 web.*****

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v5.6.4

### 安装方式

Docker

### 额外信息

所有配置皆正常，但是外网无法访问。且ipv6外网ping不同，是因为ipv6不是公网吗？怎么判断ipv6是否是内网

**Comment by jeessy2** [comment]
不是公网IP，IPv6公网是2开头的

**Comment by RikkaLzw** [comment]
> 不是公网IP，IPv6公网是2开头的

好的。
