### ISSUE TITLE
<center><h1>502 Bad Gateway</h1></center>

### ISSUE THREAD

**Issue by ilisuo** [jeessy2/ddns-go#902]
### 问题描述

最近ip更换后一直报错，不知道怎么了。

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

macOS (Darwin)

### 架构

arm64

### 版本

5.6.4

### 安装方式

服务

### 额外信息

![IMG_1554](https://github.com/jeessy2/ddns-go/assets/108167575/4f775615-2d63-4493-83cb-62ab6dff718d)

**Comment by jeessy2** [comment]
检查网络

**Comment by Kaiyuan** [comment]
广东电信，走 v2ray 一样报错。

**Comment by Drixn0** [comment]
下午七点四十左右开始的  估计CF抽风了

**Comment by sisikam** [comment]
没错 出现同类问题了 联通/移动都出现了

日志

</html>
 ,返回状态码: 502
2023/11/02 21:35:36 请求接口https://api.cloudflare.com/client/v4/zones?name=xxx.com&status=active&per_page=50失败! ERROR: Get "https://api.cloudflare.com/client/v4/zones?name=xxx.com&status=active&per_page=50": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>cloudflare-lb</center>
</body>
</html>

**Comment by lalasou** [comment]
但是  openwrt cf 更新正常啊

**Comment by ilisuo** [comment]
在 2023年11月3日，06:33，XXG ***@***.***> 写道：﻿
但是  openwrt cf 更新正常啊

**Comment by calfolou** [comment]
我以为是我的出问题了，才发现大家都出问题了，ddns-go，重新设置会更新解析成功，但是仅限于第一次，后面的都不会成功，cloudflare里面也一直报错，API Request Failed: GET /api/v4/accounts/*****************/billing/next-billing (504)；API Request Failed: GET /api/v4/billing/rate_plans/free (504)；
