### ISSUE TITLE
如果是使用docker compose编排的，请问参数 -l监听地址 -f间隔时间(秒)这两个应该如何定义，谢谢

### ISSUE THREAD

**Issue by snakwu** [jeessy2/ddns-go#905]
### 功能描述

[可选] 支持启动带参数 -l监听地址 -f间隔时间(秒)

### 解决的问题

如果是使用docker compose编排的，请问参数 -l监听地址 -f间隔时间(秒)这两个应该如编写，谢谢

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
可以传参的，具体用法自行搜索

**Comment by snakwu** [comment]
已解决
