### ISSUE TITLE
大佬可否增加域名商name.com的支持

### ISSUE THREAD

**Issue by ymting** [jeessy2/ddns-go#907]
### 功能描述

大佬可否增加域名商name.com的支持，api路径：https://www.name.com/zh-cn/account/settings/api

![2023-11-04_105924](https://github.com/jeessy2/ddns-go/assets/108313616/d107e4d8-b27e-4799-a789-ca83e7f88523)

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
可以把nameserver改到已有的服务商，服务商太多，支持不过来
