### ISSUE TITLE
ddns-og自动更新

### ISSUE THREAD

**Issue by syk6666** [jeessy2/ddns-go#908]
### 功能描述

这个插件非常好用 谢谢作者辛苦付出 
请求添加插件自动更新功能  每次版本更新 都要重新配置一回  
谢谢

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
5.6.0后支持./ddns-go -u自动更新到最新版。

**Comment by syk6666** [comment]
谢谢 谢谢 明白了
