### ISSUE TITLE
通过接口检测IPV4地址报错

### ISSUE THREAD

**Issue by Miku-programm** [jeessy2/ddns-go#909]
### 问题描述

机器是动态IP NAT 不能使用指令和通过网卡检测，但是通过接口检测一开始是正常的，但是过不了多久就是这样了
而且我是不理解怎么在检测失败的前提下把域名IP换到104.28.200.15和138.199.60.166这两个IP上的

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v5.6.4

### 安装方式

服务

### 额外信息

2023/11/06 21:00:51 未能获取IPv4地址, 将不会更新
2023/11/06 21:06:00 配置文件已保存在: /root/.ddns_go_config.yaml
2023/11/06 21:06:21 连接失败! <a target='blank' href='https://myip4.ipip.net'>点击查看接口能否返回IPv4地址</a>
2023/11/06 21:06:21 错误信息: Get "https://myip4.ipip.net": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/11/06 21:06:30 连接失败! <a target='blank' href='https://myip4.ipip.net'>点击查看接口能否返回IPv4地址</a>
2023/11/06 21:06:30 错误信息: Get "https://myip4.ipip.net": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/11/06 21:06:39 更新域名解析 *.域名 成功！IP: 104.28.200.15
2023/11/06 21:06:42 更新域名解析 *.zl.域名 成功！IP: 104.28.200.15
2023/11/06 21:06:51 连接失败! <a target='blank' href='https://ddns.oray.com/checkip'>点击查看接口能否返回IPv4地址</a>
2023/11/06 21:06:51 错误信息: Get "https://ddns.oray.com/checkip": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/11/06 21:07:21 连接失败! <a target='blank' href='https://ip.3322.net'>点击查看接口能否返回IPv4地址</a>
2023/11/06 21:07:21 错误信息: Get "https://ip.3322.net": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/11/06 21:07:51 连接失败! <a target='blank' href='https://4.ipw.cn'>点击查看接口能否返回IPv4地址</a>
2023/11/06 21:07:51 错误信息: Get "https://4.ipw.cn": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/11/06 21:07:51 未能获取IPv4地址, 将不会更新
2023/11/06 21:13:21 连接失败! <a target='blank' href='https://myip4.ipip.net'>点击查看接口能否返回IPv4地址</a>
2023/11/06 21:13:21 错误信息: Get "https://myip4.ipip.net": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/11/06 21:13:26 更新域名解析 *.域名 成功！IP: 138.199.60.166
2023/11/06 21:13:29 更新域名解析 *.域名 成功！IP: 138.199.60.166
2023/11/06 21:14:04 配置文件已保存在: /root/.ddns_go_config.yaml
2023/11/06 21:14:34 连接失败! <a target='blank' href='https://cf-ns.com/cdn-cgi/trace'>点击查看接口能否返回IPv4地址</a>
2023/11/06 21:14:34 错误信息: Get "https://cf-ns.com/cdn-cgi/trace": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/11/06 21:14:34 未能获取IPv4地址, 将不会更新
2023/11/06 21:18:59 连接失败! <a target='blank' href='https://cf-ns.com/cdn-cgi/trace'>点击查看接口能否返回IPv4地址</a>
2023/11/06 21:18:59 错误信息: Get "https://cf-ns.com/cdn-cgi/trace": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/11/06 21:18:59 未能获取IPv4地址, 将不会更新
2023/11/06 21:24:29 连接失败! <a target='blank' href='https://cf-ns.com/cdn-cgi/trace'>点击查看接口能否返回IPv4地址</a>
2023/11/06 21:24:29 错误信息: Get "https://cf-ns.com/cdn-cgi/trace": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023/11/06 21:24:29 未能获取IPv4地址, 将不会更新”

**Comment by jeessy2** [comment]
检查你网络，一个接口不通，会找下一个接口，直到成功找到IP
