### ISSUE TITLE
远端通过dynv6网址已经ping的通，但无法访问。

### ISSUE THREAD

**Issue by jamesbondjava** [jeessy2/ddns-go#910]
### 问题描述

![image](https://github.com/jeessy2/ddns-go/assets/57007273/e03a403e-749f-497b-8d64-54f4452b21c6)
远端机器ping安装了ddns-go的服务器（通过dynv6提供的网址），能够看到成功。
![image](https://github.com/jeessy2/ddns-go/assets/57007273/b9885f68-d254-4cbb-8e89-d21c7ef26944)
![image](https://github.com/jeessy2/ddns-go/assets/57007273/fa0010fd-a314-4c62-b1a6-4913f8ca28a9)

Callback调用成功, 域名:*****.*****.army, IP: 2409:*******, 返回数据: addresses updated, 
在ddns-go的网页端，也提示成功。
上述内容都成功了，但是就是无法访问，群晖访问已经打开了http。

### DNS服务商

Callback

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

V5.6.6

### 安装方式

服务

### 额外信息

网页端访问域名，提示503.

**Comment by jeessy2** [comment]
自行检查

HTTP状态码503表示服务不可用。这通常意味着服务器暂时无法处理请求，可能是由于服务器过载、维护或其他临时性问题导致的。
