### ISSUE TITLE
ddns-go无法登入，请问如何重置用户名密码

### ISSUE THREAD

**Issue by IDDisciple** [jeessy2/ddns-go#912]
### 问题描述

需要重新配置ddns-go，打开http://127.0.0.1:9876要求验证身份，试过很多用户名密码都不对

已经试过.\ddns-go.exe -s uninstall再重新.\ddns-go.exe -s install，再打开http://127.0.0.1:9876还是要输入用户名密码

请问如何重置用户名密码？

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

5.6.2

### 安装方式

服务

**Comment by IDDisciple** [comment]
已解决

**Comment by alang521** [comment]
你好，这个问题是如何解决的啊？

**Comment by alang521** [comment]
你好，这个问题是如何解决的啊？搜了好多办法都不管用啊。。。急求

**Comment by jeessy2** [comment]
> 你好，这个问题是如何解决的啊？搜了好多办法都不管用啊。。。急求

在当前用户目录的配置文件下`.ddns_go_config.yaml`，打开就看到帐号密码

**Comment by alang521** [comment]
> > 你好，这个问题是如何解决的啊？搜了好多办法都不管用啊。。。急求
> 
> 在当前用户目录的配置文件下`.ddns_go_config.yaml`，打开就看到帐号密码

感谢大神！确实解决了！（安装了一大堆新服务、设置各种权限都是无用功！）最终登录名就是自己设置的那个——开启公网访问后的用户名和密码，奇怪的是昨天用那个用户名和密码也无法登录，仍然反复提示要求验证，换系统管理员用户名和密码也无效。今天看到你的解决方案后，打开`.ddns_go_config.yaml`这个文件，再点开网页输入，，，就成了😂

**Comment by alang521** [comment]
Windows server 2022开启了网络唤醒功能，但是一旦休眠就只能通过按电源键才能唤醒，大神了解这个问题么？

**Comment by alang521** [comment]
> > > 你好，这个问题是如何解决的啊？搜了好多办法都不管用啊。。。急求
> > 
> > 
> > 在当前用户目录的配置文件下`.ddns_go_config.yaml`，打开就看到帐号密码
> 
> 感谢大神！确实解决了！（安装了一大堆新服务、设置各种权限都是无用功！）最终登录名就是自己设置的那个——开启公网访问后的用户名和密码，奇怪的是昨天用那个用户名和密码也无法登录，仍然反复提示要求验证，换系统管理员用户名和密码也无效。今天看到你的解决方案后，打开`.ddns_go_config.yaml`这个文件，再点开网页输入，，，就成了😂

然后出现新问题：2024/01/13 18:45:41 新增域名解析xxxxx.ink 失败！
2024/01/13 18:50:42 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"CDD3B24B-5408-51FD-ABFF-B8E962D769BF","HostId":"alidns.aliyuncs.com","Code":"DomainRecordConflict","Message":"The \"AAAA\" type record is in conflict the \"CNAME\" type records.","Recommend":"https://api.aliyun.com/troubleshoot?q=DomainRecordConflict&product=Alidns&requestId=CDD3B24B-5408-51FD-ABFF-B8E962D769BF"} ,返回状态码: 400

2024/01/13 18:50:42 新增域名解析 xxxxx.ink 失败！
——之前大神提到修改系统时间和阿里云服务器同步，现在电脑时间和阿里云都是自动网络获取的同步时间，且在同一个时区范围内，不可能不同步呀？

**Comment by alang521** [comment]
> > 你好，这个问题是如何解决的啊？搜了好多办法都不管用啊。。。急求
> 
> 在当前用户目录的配置文件下`.ddns_go_config.yaml`，打开就看到帐号密码

感谢大神，问题确实解决了！然后出现新问题：2024/01/13 18:45:41 新增域名解析xxxxx.ink 失败！
2024/01/13 18:50:42 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"CDD3B24B-5408-51FD-ABFF-B8E962D769BF","HostId":"alidns.aliyuncs.com","Code":"DomainRecordConflict","Message":"The "AAAA" type record is in conflict the "CNAME" type records.","Recommend":"[https://api.aliyun.com/troubleshoot?q=DomainRecordConflict&product=Alidns&requestId=CDD3B24B-5408-51FD-ABFF-B8E962D769BF"}](https://api.aliyun.com/troubleshoot?q=DomainRecordConflict&product=Alidns&requestId=CDD3B24B-5408-51FD-ABFF-B8E962D769BF%22%7D) ,返回状态码: 400

2024/01/13 18:50:42 新增域名解析 xxxxx.ink 失败！
——之前大神提到修改系统时间和阿里云服务器同步，现在电脑时间和阿里云都是自动网络获取的同步时间，且在同一个时区范围内，不可能不同步呀？

**Comment by jeessy2** [comment]
看提示
The "AAAA" type record is in conflict the "CNAME" type records.

**Comment by alang521** [comment]
> 看提示 The "AAAA" type record is in conflict the "CNAME" type records.

感谢感谢！看到状态码400就以为一样的问题，没细看里面内容，，，经过您的指引，删掉了其中一个，问题解决

**Comment by minhongqi** [comment]
> > > 你好，这个问题是如何解决的啊？搜了好多办法都不管用啊。。。急求
> > 
> > 
> > 在当前用户目录的配置文件下`.ddns_go_config.yaml`，打开就看到帐号密码
> 
> 感谢大神！确实解决了！（安装了一大堆新服务、设置各种权限都是无用功！）最终登录名就是自己设置的那个——开启公网访问后的用户名和密码，奇怪的是昨天用那个用户名和密码也无法登录，仍然反复提示要求验证，换系统管理员用户名和密码也无效。今天看到你的解决方案后，打开`.ddns_go_config.yaml`这个文件，再点开网页输入，，，就成了😂

win下找不到这个文件呀？打开隐藏文件也没有？

**Comment by Ericlpl** [comment]
windows11环境打开显示隐藏文件了还是找不到.ddns_go_config.yaml

**Comment by AmberRighd** [comment]
> 看提示
> The "AAAA" type record is in conflict the "CNAME" type records.
> 

我在这个文件内看到的是一长串无规则密码并不是我一开始注册的密码，请问这是正常的吗？

**Comment by jeessy2** [comment]
> > 看提示
> > The "AAAA" type record is in conflict the "CNAME" type records.
> > 
> 
> 我在这个文件内看到的是一长串无规则密码并不是我一开始注册的密码，请问这是正常的吗？

最新版加密了密码，可以直接修改，重启自动重新加密

**Comment by AmberRighd** [comment]
就是说我直接在那个文件内修改好密码然后用修改好的密码直接登录就可以了吗> 加密

**Comment by AmberRighd** [comment]
> > > 看提示
> > > The "AAAA" type record is in conflict the "CNAME" type records.
> > > 
> > 
> > 我在这个文件内看到的是一长串无规则密码并不是我一开始注册的密码，请问这是正常的吗？
> 
> 最新版加密了密码，可以直接修改，重启自动重新加密

就是说我直接在那个文件内修改好密码然后用修改好的密码直接登录就可以了吗

**Comment by jeessy2** [comment]
还要修改后重启才生效

**Comment by AmberRighd** [comment]
> 还要修改后重启才生效

十分感谢，已经解决了

**Comment by wuyue2011** [comment]
他是加密的，Windows怎么解密啊

**Comment by wuyue2011** [comment]
他是加密的，Windows怎么解密啊

**Comment by jeessy2** [comment]
> 他是加密的，Windows怎么解密啊

无法解密，只能重置。参考上面

**Comment by wuyue2011** [comment]
Windows如何重置，我是Windows的

**Comment by aaronfa1r** [comment]
win11可以试下这个
.\ddns-go.exe -resetPassword 新密码
