### ISSUE TITLE
卸载服务重新安装时，如与卸载之前的安装目录不一致，公网/局域网其他设备将无法访问WEB面板

### ISSUE THREAD

**Issue by leic4u** [jeessy2/ddns-go#915]
### 问题描述

Windows 11 环境下：

1. 在 `D:\Programs\DDNS-go\ddns-go` 目录中，按照本项目 [readme.md 在系统中使用](https://github.com/jeessy2/ddns-go#%E7%B3%BB%E7%BB%9F%E4%B8%AD%E4%BD%BF%E7%94%A8) 方法，使用 Powershell 管理员模式，`.\ddns-go.exe -s install` 正常安装任一版本（如我之前安装的是v4.4.2）。

2. 正常通过 `127.0.0.1:9876` 打开面板，配置完成之后，可正常使用 WEB 面板。局域网设备可通过 `192.168.31.xxx:9876` 访问面板。群晖上配置好反向代理，也可以正常用域名 `pc-ddns.xxxx.cn` 访问到 ddns-go 的 WEB 面板。

---

3. 使用 `.\ddns-go.exe -s uninstall` 命令卸载服务。

4. 在 `D:\Programs\DDNS-go`文件路径中，重新使用 `.\ddns-go.exe -s install` 安装任一版本（如最新的v5.6.6）。

5. 此时，WEB 面板只可以通过本机，使用 `127.0.0.1:9876` / `localhost:9876` / `192.168.31.xxx:9876`访问。
局域网设备无论使用 `pc-ddns.xxxx.cn` / `192.168.31.xxx:9876`，均无法访问到 WEB 面板。
通过群晖反代的域名访问，会出现群晖的“找不到该页面”提示。
![image](https://github.com/jeessy2/ddns-go/assets/32786903/be2f4e11-158e-4dde-889f-7682248f47dc)

---

6. 卸载掉服务后，回到最开始的 `D:\Programs\DDNS-go\ddns-go` 目录，重新安装任一版本（如最新的v5.6.6），本机、局域网设备，公网设备又可以正常访问 WEB 面板了。

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v5.6.6

### 安装方式

服务

**Comment by jeessy2** [comment]
检查你windows防火墙

**Comment by leic4u** [comment]
> 检查你windows防火墙

排查了一天，我开始也以为是防火墙问题，排查了很久，各种关闭防火墙、改入站规则等等都试过了，无效。

而且在防火墙没有任何调整的情况下，先后在两个文件目录下安装服务，一个可以访问 WEB 面板，一个访问不了，应该就不是防火墙问题了。

**Comment by jeessy2** [comment]
未遇到这种情况，你先研究一下
为什么要搞二个目录，不晕吗

**Comment by leic4u** [comment]
> 未遇到这种情况，你先研究一下 为什么要搞二个目录，不晕吗

就是觉得之前那个目录有点深，所以把末级文件夹里面的 ddns-go.exe 移出来。结果就发现其他设备访问不了，排查了一天，刚刚想着要不挪回原来的目录试试，结果还真是，挪回去就正常了。😂
