### ISSUE TITLE
Cloudflare 请求失败  “Invalid format for Authorization header”

### ISSUE THREAD

**Issue by dukehug** [jeessy2/ddns-go#916]
### 问题描述

###操作系统版本
Windows 10 LTSC

###DNS服务商
Cloudflare

### 记录地址类型
IPv6

### 错误日志
2023/11/18 16:55:29 请求接口 https://api.cloudflare.com/client/v4/zones?name=xxxxxx.com&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400

### 参考资料

根据日志的回馈，Google搜索得知是缺少了Email 地址的验证

相关文档见此链接：  [https://developers.cloudflare.com/api/#zone-purge-all-files](https://developers.cloudflare.com/api/#zone-purge-all-files)

希望得到修正。再次感谢开发者的工作

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v5.6.6

### 安装方式

服务

### 额外信息

2023/11/18 16:55:29 请求接口 https://api.cloudflare.com/client/v4/zones?name=xxxxxxx.com&status=active&per_page=50 失败! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400

**Comment by jeessy2** [comment]
用的Bearer
检查一下你Token

**Comment by dukehug** [comment]
> 用的Bearer 检查一下你Token

感谢。确实是Token的问题。
