### ISSUE TITLE
NAS两条网线设置链路聚合后得到IPV6。然而DDNSGO的3个方式都无法获取IPV6地址

### ISSUE THREAD

**Issue by pp6451303** [jeessy2/ddns-go#918]
### 问题描述

通过ssh命令行能获取IPV6，只是DDNSGO不行，我该如何设置？
日志如下：
2023/11/19 20:59:49 等待网络连接：Get "https://alidns.aliyuncs.com/": dial tcp: lookup alidns.aliyuncs.com on 8.8.8.8:53: read udp 192.168.0.12:58509->8.8.8.8:53: i/o timeout。5s 后重试...
2023/11/19 21:00:04 等待网络连接：

### DNS服务商

腾讯云

### 是否已搜索同类问题

未搜索

### 操作系统

Linux

### 架构

i386

### 版本

v5.6.6

### 安装方式

Docker

### 额外信息

日志如下：
2023/11/19 20:59:49 等待网络连接：Get "https://alidns.aliyuncs.com/": dial tcp: lookup alidns.aliyuncs.com on 8.8.8.8:53: read udp 192.168.0.12:58509->8.8.8.8:53: i/o timeout。5s 后重试...
2023/11/19 21:00:04 等待网络连接：Get "https://bcd.baidubce.com": dial tcp: lookup bcd.baidubce.com on 8.8.8.8:53: read udp 192.168.0.12:44315->8.8.8.8:53: i/o timeout。5s 后重试...
2023/11/19 21:00:19 等待网络连接：Get "https://api.cloudflare.com/client/v4/zones": dial tcp: lookup api.cloudflare.com on 8.8.8.8:53: read udp 192.168.0.12:41094->8.8.8.8:53: i/o timeout。5s 后重试...
2023/11/19 21:00:34 等待网络连接：Get "https://dnsapi.cn/Record.List": dial tcp: lookup dnsapi.cn on 8.8.8.8:53: read udp 192.168.0.12:42952->8.8.8.8:53: i/o timeout。5s 后重试...
2023/11/19 21:00:49 等待网络连接：Get "https://domains.google.com/nic/update": dial tcp: lookup domains.google.com on 8.8.8.8:53: read udp 192.168.0.12:42392->8.8.8.8:53: i/o timeout。5s 后重试...
2023/11/19 21:01:04 等待网络连接：Get "https://dns.myhuaweicloud.com": dial tcp: lookup dns.myhuaweicloud.com on 8.8.8.8:53: read udp 192.168.0.12:37195->8.8.8.8:53: i/o timeout。5s 后重试...
2023/11/19 21:01:19 等待网络连接：Get "https://dynamicdns.park-your-domain.com/update?host=#%7Bhost%7D&domain=%23%7Bdomain%7D&password=%23%7Bpassword%7D&ip=%23%7Bip%7D": dial tcp: lookup dynamicdns.park-your-domain.com on 8.8.8.8:53: read udp 192.168.0.12:45949->8.8.8.8:53: i/o timeout。5s 后重试...

**Comment by pp6451303** [comment]
单条网线能DDNSGO能正常获取V6地址。2条网线聚合则不行。2条聚合得到的v6可以PING通

**Comment by jeessy2** [comment]
看报错信息是dns问题

**Comment by pp6451303** [comment]
意思是设置好dns就行吗，怎么设置。为啥一条网线时dns就不出问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月19日(周日) 晚上10:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeessy2/ddns-go] NAS两条网线设置链路聚合后得到IPV6。然而DDNSGO的3个方式都无法获取IPV6地址 (Issue #918)




 
看报错信息是dns问题

**Comment by jeessy2** [comment]
这个你自己看了，dns 8.8.8.8查询超时

**Comment by jeessy2** [comment]
换个114.114.114.114试下
