### ISSUE TITLE
有支持花生壳的设置的吗？

### ISSUE THREAD

**Issue by Xingxiwei** [jeessy2/ddns-go#922]
### 功能描述

我有个花生壳企业号想直接用这个号做内网穿透

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by Xingxiwei** [comment]
如何做才可以实现呢请问？

**Comment by jeessy2** [comment]
那你直接可以用花生壳企业号。
DDNS主要针对有公网IP的

**Comment by Xingxiwei** [comment]
> 那你直接可以用花生壳企业号。 DDNS主要针对有公网IP的

好的谢谢
