### ISSUE TITLE
windows2008系统无法打开

### ISSUE THREAD

**Issue by aije** [jeessy2/ddns-go#924]
### 问题描述

Windows2008系统执行程序，提示不是有效的32位应用程序。

![Snipaste_2023-11-29_16-08-05](https://github.com/jeessy2/ddns-go/assets/1253768/61239622-4dc6-4450-9829-f310415378af)
![Snipaste_2023-11-29_16-07-42](https://github.com/jeessy2/ddns-go/assets/1253768/bea0d556-5a06-478e-9a4f-07b606db9c85)

### 是否已搜索同类问题

未搜索

### 操作系统

Windows

### 架构

x86_64

### 版本

V5.6.6

### 安装方式

其它

**Comment by jeessy2** [comment]
下载windows_i386试试
