### ISSUE TITLE
华为云的自定义参数

### ISSUE THREAD

**Issue by mizb** [jeessy2/ddns-go#927]
### 功能描述

增加华为云，区域解析的readme。
华为云，现在有区域解析，能细分到城市。而且ttl还能设定为1s.关键是免费的。但是没有可参考参数。

### 解决的问题

优化功能

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
欢迎PR
