### ISSUE TITLE
windows ip获取问题

### ISSUE THREAD

**Issue by maohaotian** [jeessy2/ddns-go#928]
### 问题描述

windows系统，腾讯云域名。进行了id和token配置，但是获取的ip不正确。
家庭网络配置为天翼网关+路由器，电脑通过无线网连接路由器。获得的ip为一个172开头的ip地址，与https://www.ip138.com/查询到的ip不同。

### DNS服务商

腾讯云

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v1.0.0

### 安装方式

服务

### 额外信息

![问题截图](https://github.com/jeessy2/ddns-go/assets/55353413/d628e42c-6798-48b1-9680-9bc75ff4c4fd)

配置已完成，域名已经填写

**Comment by maohaotian** [comment]
发现问题，是因为开了vpn，关闭之后获取的ip地址相同。

**Comment by maohaotian** [comment]
但是添加的domains没有自动更新，日志没有报错信息出现

**Comment by jeessy2** [comment]
Domains填了？

**Comment by maohaotian** [comment]
确认填写了。可能是下载的版本太低导致？正在尝试新版本。

**Comment by maohaotian** [comment]
问题解决，应该是软件版本的问题。默认的接口api也和目前有效的不一致。更换版本后按照提供的接口填写，有效进行了更新，非常好用，感谢作者！
