### ISSUE TITLE
无法正确获取网卡

### ISSUE THREAD

**Issue by yueyashe** [jeessy2/ddns-go#931]
### 问题描述

作者你好，我遇到的问题是无法正确获取网卡，我电脑安装了双网卡，原先是插网线使用，能正常通过以太网获取ipv6地址，但更换成Wi-Fi后就无法使用了
![28](https://github.com/jeessy2/ddns-go/assets/130819402/f7f8180b-f5aa-4940-b3a2-0da6251481ae)
![29](https://github.com/jeessy2/ddns-go/assets/130819402/36cbae7a-b4f4-4ecf-858e-f05260d44abd)
![31](https://github.com/jeessy2/ddns-go/assets/130819402/12e52946-4032-4872-94be-75084fa42a2c)

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

ddns-go_5.6.6

### 安装方式

其它

**Comment by jeessy2** [comment]
你指定的网卡是以太网，改成Wi-Fi后，所以获取不到
