### ISSUE TITLE
CentOS指令如何安裝DDNS-Go

### ISSUE THREAD

**Issue by Windows1122H2** [jeessy2/ddns-go#933]
### 功能描述

我要如何一鍵安裝DDNS-Go的方法，因爲我無法利用桌面版CentOS 7

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
./ddns-go -s install
