### ISSUE TITLE
请问如何修改密码  登录不上去

### ISSUE THREAD

**Issue by 1261588712** [jeessy2/ddns-go#934]
### 问题描述

找不到配置文件了，删除容器 镜像  重新拉还是没办法重新设置密码

### DNS服务商

腾讯云

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v5.66

### 安装方式

Docker

**Comment by jeessy2** [comment]
在docker的root目录下，是一个隐藏文件

**Comment by 1261588712** [comment]
请问该如何查看修改，或者如何完全删除他，我删除镜像跟容器，重新拉取还是默认配置

**Comment by jeessy2** [comment]
把映射的那个目录一起删除
文档写的/opt/ddns-go

**Comment by 1261588712** [comment]
好的，感谢这么晚还在回复。祝您有个好梦，晚安！！
