### ISSUE TITLE
请问群晖套件版的config文件在哪

### ISSUE THREAD

**Issue by Constanyin** [jeessy2/ddns-go#935]
### 问题描述

卸载重装之后还是之前的端口号和密码，密码错的登不上 /volume1/@appconf 以及@appdata目录下都没找到

### DNS服务商

华为云

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

5.6.6

### 安装方式

其它

**Comment by jeessy2** [comment]
群晖套件不是这边维护的，问下旷神，或者通过命令查找一下文件

**Comment by Constanyin** [comment]
> 群晖套件不是这边维护的，问下旷神，或者通过命令查找一下文件

找到了 在这里 /volume1（数字每个人都不一样）/@appdata/DDNS-GO/ddns-go.yaml
