### ISSUE TITLE
阿里云 DNS API请求时签名不匹配（SignatureDoesNotMatch）

### ISSUE THREAD

**Issue by NolanCN** [jeessy2/ddns-go#936]
### 问题描述

2023/12/12 11:34:23 请求接口 https://alidns.aliyuncs.com/ 失败! 返回内容: {"RequestId":"5589F997-A401-54B2-A2DC-987AFAF132ED","Message":"Specified signature is not matched with our calculation. server string to sign is:GET&%2F&AccessKeyId%3DLTAI5t8quj8RGZHqgjUnXip5%26Action%3DDescribeSubDomainRecords%26DomainName%3Dosnode.cn%26Format%3DJSON%26SignatureMethod%3DHMAC-SHA1%26SignatureNonce%3D1702352063288845221%26SignatureVersion%3D1.0%26SubDomain%3Dpi.osnode.cn%26Timestamp%3D2023-12-12T03%253A34%253A23Z%26Type%3DAAAA%26Version%3D2015-01-09","Recommend":"https://api.aliyun.com/troubleshoot?q=SignatureDoesNotMatch&product=Alidns&requestId=5589F997-A401-54B2-A2DC-987AFAF132ED","HostId":"alidns.aliyuncs.com","Code":"SignatureDoesNotMatch"} ,返回状态码: 400

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### 版本

v5.6.6

### 安装方式

Docker

**Comment by jeessy2** [comment]
重新生成一个key
