### ISSUE TITLE
关闭密码复杂度校验

### ISSUE THREAD

**Issue by NyaMisty** [jeessy2/ddns-go#937]
### 问题描述

我不觉得一个self-hosted的程序应该强制设置最低的密码复杂度。

**Comment by jeessy2** [comment]
有些需要暴露在公网的，还有些内网也不是很安全。
密码复杂度可以降低点，暂时不考虑关

**Comment by NyaMisty** [comment]
用户布在哪里其实是他自己的选择，跟你这个软件没有一丁点的关系。
只能说你这样操作让人感觉很难受。
如果说在这里协商失败那我其实也没啥办法，我会自己fork一份关闭掉它的repo。

**Comment by jeessy2** [comment]
Fork吧。对你来说可能麻烦点，有些人设置123456暴露公网，然后被破解了就完了

**Comment by NyaMisty** [comment]
我仔细看了下，发现核心的问题是这个patch里面提到的known issue并没有被修复。。。。

https://github.com/jeessy2/ddns-go/pull/779

难怪我手动修改配置都没法保存。其实这个弄好我就可以直接改配置文件里面的密码了。

**Comment by jeessy2** [comment]
> 我仔细看了下，发现核心的问题是这个patch里面提到的known issue并没有被修复。。。。
> 
> #779
> 
> 难怪我手动修改配置都没法保存。其实这个弄好我就可以直接改配置文件里面的密码了。

感兴趣的话，欢迎PR

**Comment by jeessy2** [comment]
v6.0.0在未开启公网的条件下，以减低密码复杂度的要求
