### ISSUE TITLE
如果当前IPV6地址没有更新时, 也把当前的IPV6地址通过钉钉发出来

### ISSUE THREAD

**Issue by biggbuddy** [jeessy2/ddns-go#938]
### 功能描述

我使用的是ipv6公网, 现在只有当ipv6地址有变化, 同时往阿里dns中更新成功后才会在钉钉中发送 ipv6Addr 的值, 否则只会有更新结果, 会是类似如下的形式:

```
你的公网IP变了

IPv6地址：
域名更新结果：失败
```

IPV6地址这一栏显示为空.

当域名更新成功的时, IPV6地址是可以成功打印的, 所以webhook的配置应该没有问题

能否即使在认为不需要更新或者更新不成功的时候 , 也把当前获取到的IPV6地址打印出来

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
检查是否获取到IPv6

**Comment by biggbuddy** [comment]
> 检查是否获取到IPv6

你的意思是本来就是默认会输出IPV6地址, 只是没获取到吗? 

我倒没考虑到会是这种原因,  我这边一直是会获得IPV6公网IP的, 并且ddns-go也不是一直提示更新不成功, 所以我一直以为只是因为认为IPV6没有更新所以就没有输出地址.
今天设置了自动任务今天凌晨4点重启OpenWrt路由器, 一般重启后IPV6地址会变, 理论上这个时候会更新dns的IP
查了一下日志, 但只有10点之后的日志, 所以好像没有办法追查了, 钉钉 的提示信息倒是每隔一个小时都会输出, 但都是更新失败的状态, ipv6地址也没有输出

@jeessy2

**Comment by biggbuddy** [comment]
![image](https://github.com/jeessy2/ddns-go/assets/12723408/5259a659-2ca9-4329-ae9d-c6456243807b)
是获取到了地址了的, 但输出的依然是
![image](https://github.com/jeessy2/ddns-go/assets/12723408/beed1c05-8532-4c1b-a4cb-2dcc2d431b20)

**Comment by jeessy2** [comment]
看下你webhook配置对不对

**Comment by biggbuddy** [comment]
下面是我的webhook配置

```
{
    "msgtype": "markdown",
    "markdown": {
        "title": "你的公网IP变了",
        "text": "#### DDNS更新结果 \n - IPv6地址：#{ipv6Addr} \n - 域名更新结果：#{ipv6Result} \n - domain:#{ipv6Domains} \n"
    }
}
```

**Comment by jeessy2** [comment]
那就是未获取到IPv6,然后发送的webhook

**Comment by biggbuddy** [comment]
但是为什么同样的配置, 有时又能正确获取并更新 呢?

**Comment by jeessy2** [comment]
自己检查一下吧

**Comment by biggbuddy** [comment]
但日志中已经提示获取到了IP哦, 但发出来的钉钉信息还是没有地址

**Comment by jeessy2** [comment]
看日志，并没有发送webhook

**Comment by sevensevenmi** [comment]
我的正常 你自己的问题呦！
