### ISSUE TITLE
 二级域名无法进行ddns解析

### ISSUE THREAD

**Issue by zsjsll** [jeessy2/ddns-go#944]
### 问题描述

在 https://nic.ua/ 上申请的二级域名，类似 abc.pp.ua 这样的，无法通过ddns，目前已测试腾讯云和cloudflare ，都不可以。在日志中，腾讯云报错，cloudflare没反应。但是用群晖自带的ddns，是可以通过腾讯云解析的。

### DNS服务商

腾讯云, Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v5.6.7

### 安装方式

服务

**Comment by jeessy2** [comment]
日志呢？

**Comment by jeessy2** [comment]
你腾讯云帐号下，有那个主域名？

**Comment by zsjsll** [comment]
有的
![image](https://github.com/jeessy2/ddns-go/assets/16866928/de63726a-df0a-4b56-9a8d-58299a9274c3)

**Comment by jeessy2** [comment]
用冒号分割`@:xxx.pu.ua`

**Comment by zsjsll** [comment]
> 用冒号分割`@:xxx.pu.ua`

我按照你说的做了，腾讯云和 cloudflare 都可以了，谢谢，不过我想知道，为什么要添加这个 :

**Comment by jeessy2** [comment]
下方有说明，pu.ua不是你的主域名，xxx.pu.ua才是

**Comment by zsjsll** [comment]
好的谢谢了
