### ISSUE TITLE
针对callback场景增加一个触发单次更新的按钮

### ISSUE THREAD

**Issue by jack-yu** [jeessy2/ddns-go#945]
### 功能描述

设置好参数后，能否增加个按钮，单次触发下更新，并可以查看到反馈信息，以便知道配置是否生效

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
不是有？
