### ISSUE TITLE
如何使用Yum指令在CentOS 7系統上使用DDNS Go功能

### ISSUE THREAD

**Issue by Windows1122H2** [jeessy2/ddns-go#946]
### 功能描述

如何使用Yum指令在CentOS 7系統上使用DDNS Go功能

### 检查清单

- [x] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
不支持yum
直接下载后使用
