### ISSUE TITLE
对eu.org的国家域名没有对于的正则，好像会把国家域名当作一级域名处理

### ISSUE THREAD

**Issue by cqash** [jeessy2/ddns-go#947]
### 问题描述

即eu.org是可以注册xxx.cn.eu.org这样的域名的，目前通过观察日志，好像是把cn.eu.org的参数往上传了
参考国家/地区域名列表
https://nic.eu.org/opendomains.html

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

arm64

### 版本

 v5.6.7

### 安装方式

Docker

**Comment by jeessy2** [comment]
用冒号分割

**Comment by cqash** [comment]
> 用冒号分割

比如说我的域名是xxx.cn.eu.org，子域名是xxx.xxx.cn.eu.org，在ddns里面填写成xxx:cn.eu.org和xxx.xxx:cn.eu.org这样吗

**Comment by cqash** [comment]
> 用冒号分割

知道了，谢谢，是写成
:xxx.cn.eu.org
xxx:xxx.cn.eu.org
的形式

**Comment by jeessy2** [comment]
xxx:cn.eu.org

**Comment by cqash** [comment]
> xxx:cn.eu.org

试了下，这种不行，要aaa:bbb.cn.eu.org

**Comment by jeessy2** [comment]
bbb不是你申请的？

**Comment by cqash** [comment]
> bbb不是你申请的？

我申请的域名是bbb.cn.eu.org
目前测试情况是 
 留空:bbb.cn.eu.org  设置bbb.cn.eu.org的ip
aaa.bbb:cn.eu.org  设置aaa.bbb.cn.eu.org的 ip

**Comment by jeessy2** [comment]
以你申请的为准，进行划分

**Comment by jeessy2** [comment]
subdomain:申请的域名
