### ISSUE TITLE
通过接口获取ipv4的新功能请求

### ISSUE THREAD

**Issue by wanglu58** [jeessy2/ddns-go#953]
### 功能描述

通过接口获取ipv4。系统默认是
https://myip4.ipip.net,https://ddns.oray.com/checkip,https://ip.3322.net,https://4.ipw.cn
这4个，我测试发现第一个地址返回包含归属地所以返回时候数据慢，其他请求后返回数据很快。网址每隔5分钟调用一次。会不会被网站拉黑，我想可不可以实现这个功能。第一个根据**顺序**分别调用获取，第二个打乱这4个接口**随机**调取接口请求。这样对网站的请求会好一点。
不知道ddnsgo的逻辑是什么？（如果按顺序请求，那很多人用myip4.ipip.net第一个网站的请求会很大？）有人能解答下吗？写这个go的文件也可以告诉我，我看一下。万分感谢！

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
根据顺序来的，顺序可以自行修改

**Comment by ddnspod** [comment]
http(s)://ip.atomo.cn               IPv4/IPv6 for mainland China only
http(s)://ip.ddnspod.com        IPv4/IPv6 for Global
http(s)://ipv4.ddnspod.com    Only ipv4 for Global
http(s)://ipv6.ddnspod.com    Only ipv6 for Global
国内阿里腾讯华为三大cdn，没有调用频率限制
