### ISSUE TITLE
ipv6 没有找到可用的网卡

### ISSUE THREAD

**Issue by coolmz** [jeessy2/ddns-go#955]
### 问题描述

设备是黑群  可以正常ipv6用网卡获取地址使用 大概十五分钟后就不行了 进去会提示ipv6 没有找到可用的网卡 重启黑群或者在重新安装ddns-go套件 功能又正常了但是还是过一会就不行了 无限循环

### DNS服务商

Cloudflare

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v5.7.0

### 安装方式

其它

### 额外信息

![I5BGV`YL{HZ{{KE3SOX}6_4](https://github.com/jeessy2/ddns-go/assets/34463610/0d72a8c3-a367-4fd4-aba9-7c21a0dfc398)

**Comment by coolmz** [comment]
![V(YWS125YE_O9PUVZ`WAWSD](https://github.com/jeessy2/ddns-go/assets/34463610/43067326-8bce-4443-9254-33535a6f3dfa)

**Comment by jeessy2** [comment]
通过接口获取看有没有

**Comment by coolmz** [comment]
已经解决了 原因是群晖获取ipv6公网后十分钟后会自动变成内网ip 解决方式是重启了光猫 就正常了
