### ISSUE TITLE
大佬，ddns-go可以在安卓termux上面使用吗? 

### ISSUE THREAD

**Issue by wallpass** [jeessy2/ddns-go#957]
### 功能描述

我在termux上尝试了github上面的另外一个ddns项目，（NewFuture大佬的作品），是可以运行的。但是他的项目没办法及时更新ipv6地址，必须设定crond定时任务，我按照他提供的代码在termux上允许失败了，主要是路径不对。
另外，我尝试了酷安老哥制作的magisk模块版本的ddns-go，也允许失败了，日志提示：正在等待网络链接5s之后尝试。

### 解决的问题

想要了解能否在安卓上使用ddns-go，制作成magisk或者在termux上允许

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
指定dns试下

**Comment by wallpass** [comment]
你是说magisk版本的ddns-go可以通过指定dns来解决问题吗?具体应该怎么操作，是设置手机上面的dns还是修改哪里?

**Comment by jeessy2** [comment]
./ddns-go -dns 114.114.114.114

**Comment by Clown8888** [comment]
用-c指定一次配置文件路径启动，就能正常保存配置了，前提是你要现有一份配置模板
