### ISSUE TITLE
ipv4获取

### ISSUE THREAD

**Issue by gzxief** [jeessy2/ddns-go#958]
### 功能描述

本人内网穿透，建立web服务（已备案）本地IPV6有80 443可以直接访问，但ipv4只能内网穿透过来，域名CNAME，如果域名用CNAME,就无法使用AAAA的IPV6，所以只能A+AAAA记录（IPV6使用ddnos-go），但内网穿透的域名经常更换IP， 所以请求DDNS-GO可以ping域名获取到IP，更新到A记录上，谢谢

### 解决的问题

ping域名获取到IP，更新到A记录上

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
通过命令获取
命令就是`ping xxx.xxx`

**Comment by gzxief** [comment]
测试了，DOCKER的ddns-go，不生效

**Comment by jeessy2** [comment]
自行多测多试

**Comment by gzxief** [comment]
![20240110115500](https://github.com/jeessy2/ddns-go/assets/82856050/d9cb5385-32c8-4da7-8186-aa5a5330f7ae)
为啥你都不相信呢

**Comment by jeessy2** [comment]
日志？

**Comment by gzxief** [comment]
都挂着一个星期了，都不行，一直都这样
![20240110122312](https://github.com/jeessy2/ddns-go/assets/82856050/743d9bb6-8366-4203-a858-b417d5d8b507)

**Comment by WaterLemons2k** [comment]
Linux 要加 `-c` 参数，否则会一直 ping：

```shell
ping -c 1 example.com
```

**Comment by gzxief** [comment]
感谢，完美了
