### ISSUE TITLE
请求接口https://dnsapi.cn/Record.List失败

### ISSUE THREAD

**Issue by 404gods** [jeessy2/ddns-go#961]
### 问题描述

请问一下，我使用docker部署在群晖上的，可以解析IP，但是一直报错“请求接口https://dnsapi.cn/Record.List失败! ERROR: Post "https://dnsapi.cn/Record.List": net/http: TLS handshake timeout”

具体如下：
2024/01/05 11:24:42 你的IP x.x.x.x 没有变化, 域名 xxx.xxx.com
2024/01/05 11:29:44 IPv4未改变，将等待 5 次后与DNS服务商进行比对
2024/01/05 11:34:45 IPv4未改变，将等待 4 次后与DNS服务商进行比对
2024/01/05 11:39:48 IPv4未改变，将等待 3 次后与DNS服务商进行比对
2024/01/05 11:44:49 IPv4未改变，将等待 2 次后与DNS服务商进行比对
2024/01/05 11:49:49 IPv4未改变，将等待 1 次后与DNS服务商进行比对
2024/01/05 11:55:01 请求接口https://dnsapi.cn/Record.List失败! ERROR: Post "https://dnsapi.cn/Record.List": net/http: TLS handshake timeout

本地测试如下：
curl https://dnsapi.cn/Record.List
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dnsapi.cn:443 

PS：DDNS-GO禁止公网访问，未启用IPV6

### DNS服务商

DnsPod

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

i386

### 版本

v5.7.0

### 安装方式

Docker

**Comment by jeessy2** [comment]
dnspod问题吧？

**Comment by jeessy2** [comment]
DNS问题，能上网？
