### ISSUE TITLE
建议加个火山引擎的

### ISSUE THREAD

**Issue by mingkksir** [jeessy2/ddns-go#964]
### 功能描述

我在抖音旗下的火山引擎买了个域名，大佬能加个火山引擎的就完美了

### 解决的问题

不需要再转到其他服务商了

### 附加信息

谢谢大佬 ！

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
可以把nameserver改到已有的服务商，服务商太多，支持不过来

**Comment by vpei** [comment]
> ### 功能描述
> 我在抖音旗下的火山引擎买了个域名，大佬能加个火山引擎的就完美了
> 
> ### 解决的问题
> 不需要再转到其他服务商了
> 
> ### 附加信息
> 谢谢大佬 ！
> 
> ### 检查清单
> * [x]  我已搜索同类问题，并确保没有我要提交的功能
> * [x]  我已使用最新版本，并确保该功能仍未在最新版本中实现

cloudflare比较好使：）
