### ISSUE TITLE
v6.0.0 后，在windows 7中运行进程会立即崩溃

### ISSUE THREAD

**Issue by oncx** [jeessy2/ddns-go#976]
### 问题描述

Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x46cbb5
rax     0x0
rbx     0xcf2f00
rcx     0xd47020
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0xd18a98
r11     0x21
r12     0x22fec0
r13     0x1
r14     0xcf2660
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

### 是否已搜索同类问题

未搜索

### 操作系统

Windows

### 架构

x86_64

### 版本

v6.0.1

### 安装方式

服务

**Comment by jeessy2** [comment]
应该是golang 1.21不支持win7了

**Comment by jeessy2** [comment]
fix by: v6.0.2
