### ISSUE TITLE
计时器错误，日志时间错误

### ISSUE THREAD

**Issue by Clown8888** [jeessy2/ddns-go#978]
### 问题描述

日志系统，计时系统

### DNS服务商

腾讯云

### 是否已搜索同类问题

已搜索，未解决

### 操作系统

Linux

### 架构

arm64

### 版本

v6.0.2

### 安装方式

github

### 额外信息

![Screenshot_2024-01-13-13-07-25-772_bin mt plus](https://github.com/jeessy2/ddns-go/assets/156493823/cfa79511-5792-42f5-8c04-5aafc390b04e)
![Screenshot_2024-01-13-13-08-08-984_mark via](https://github.com/jeessy2/ddns-go/assets/156493823/cf956583-0b8b-4518-b445-4221087bde3a)

**Comment by jeessy2** [comment]
启动就要对比，后面才是那个流程。
时间不对，改下系统的时间/时区

**Comment by Clown8888** [comment]
图中日志使用ddns-go -cacheTimes 1 -l :10443 -c .ddns_go_config.yaml启动核心。我设置1次，默认300秒没动，实际得出与dns服务商对比周期为10分钟（300*2/60=10）

**Comment by Clown8888** [comment]
> 启动重点对比，后面才是那个流程。 时间选择，改下系统的时间/时区
那日志时间问题，可能是安卓设备的锅
![Screenshot_2024-01-13-13-26-18-529_com android settings](https://github.com/jeessy2/ddns-go/assets/156493823/572dc9c6-c14a-4ef0-a7e5-d0507d5a757d)

**Comment by lingchenma** [comment]
我现在又遇到了这个同样的问题 ， 版本是 6.7.7 ，

主机名称 | Cudy
型号 | Cudy TR3000 (U-Boot mod)(CpuMark : 8704.324961 Scores)
架构 | ARMv8 Processor x 2 (67.1°C)
 openwrt 版本 | LEDE R24.12.12 / LuCI openwrt-23.05 branch git-24.339.48605-e1135e2


用W11 电脑访问的opwnwrt 网页 

![Image](https://github.com/user-attachments/assets/83672dd8-8313-4c99-9c51-630607932def)

![Image](https://github.com/user-attachments/assets/5200fd0b-392e-4f49-8f82-d21a89e5b2a1)
