### ISSUE TITLE
阿里云解析失败（返回状态码: 400）

### ISSUE THREAD

**Issue by JoyInk** [jeessy2/ddns-go#979]
### 问题描述

阿里云请求失败

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v6.0.2

### 安装方式

Docker

### 额外信息

2024/01/14 00:32:22 查询域名信息发生异常! 返回内容: {"RequestId":"CA434CC3-4F14-595D-99B0-0337C6259DF8","Message":"Specified time stamp or date value is expired.","Recommend":"https://api.aliyun.com/troubleshoot?q=InvalidTimeStamp.Expired&product=Alidns&requestId=CA434CC3-4F14-595D-99B0-0337C6259DF8","HostId":"alidns.aliyuncs.com","Code":"InvalidTimeStamp.Expired"} ,返回状态码: 400

**Comment by jeessy2** [comment]
操作系统时间不对

**Comment by JoyInk** [comment]
是否可以修改ddns-go容器的时区，修改为UTC

**Comment by WaterLemons2k** [comment]
> 是否可以修改ddns-go容器的时区，修改为UTC

修改 `TZ` 变量，默认是 `Asia/Shanghai`。

https://github.com/jeessy2/ddns-go/blob/20f1b2963fa3307bea6d004c57073c0ffaa2aea0/Dockerfile#L19

```sh
docker run -e TZ="UTC" jeessy/ddns-go
```

**Comment by JoyInk** [comment]
时区问题已解决，出现了新的问题：Get "https://alidns.aliyuncs.com/": tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by WaterLemons2k** [comment]
> 时区问题已解决，出现了新的问题：Get "[alidns.aliyuncs.com](https://alidns.aliyuncs.com/)": tls: failed to verify certificate: x509: certificate signed by unknown authority

可能是因为时间不正确导致的证书问题，加 `skipVerify` 参数：

```sh
docker run jeessy/ddns-go -skipVerify
```

**Comment by JoyInk** [comment]
![1705146069757](https://github.com/jeessy2/ddns-go/assets/74496777/4ff14219-59ae-46d4-926c-66eed0ccd3b9)

**Comment by WaterLemons2k** [comment]
时间是对的（UTC+8）但时区是错的（UTC）。

**Comment by WaterLemons2k** [comment]
主机的时间和时区正确吗？

**Comment by JoyInk** [comment]
安装了个zimaos,那个系统是UTC时区的，但时间竟然是正确的，，所以docker里时区调整为UTC时，时间就是正确的，但时区就不对了，没弄明白，觉得不是容器

**Comment by WaterLemons2k** [comment]
在主机上运行 `sudo hwclock --verbose` 看看硬件时钟的时间正确吗？

**Comment by JoyInk** [comment]
这个系统甚至精简掉了命令行，无法对系统做具体操作，暂时没有找到解决办法，已经把此问题提交给了官方。

**Comment by JoyInk** [comment]
首先主机时区显示的是UTC，但时间是正确的中国时间
其次，如果ddns-go容器启动时使用TZ=UTC，那么容器中时区为UTC，时间也为正确时间，
如果不更改TZ，时区为CTS，时间为CTS+8

**Comment by jeessy2** [comment]
时区和具体时间要匹配。UTC时区，时间又是+8小时。说明系统时间快了8小时， 阿里云要30分钟内

**Comment by Iain33** [comment]
@jeessy2 已修改环境变量TZ=UTC-8，系统时间变为
# date
Sun Feb  4 16:20:58 UTC 2024

## 目前的报错日志

2024/02/04 08:25:05 查询域名信息发生异常! 返回内容: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null} ,返回状态码: 400


通过date命令行获取的时间为中国时间，但ddns-go日志的时间不对。报错问题依旧存在

**Comment by jeessy2** [comment]
重新生成token试下

**Comment by wcwckoo** [comment]
指定DNS解析服务器改成ali dns
