### ISSUE TITLE
增加IP变化时访问的url数量

### ISSUE THREAD

**Issue by BA7JCM** [jeessy2/ddns-go#98]
希望可以在IP变化时访问不同的两个url，机子有点老，跑两份程序怕吃不消，目前webhook可以用做一个访问url的地方，但现在我有两个url想在公网IP发送变化时被访问到，一个是通知自己的url，再一个是去腾讯dnspod的公共解析里绑定自己公网IP的url
![image](https://user-images.githubusercontent.com/79561519/131880060-0fee7053-217d-4b32-9a44-8dab088128a0.png)
![image](https://user-images.githubusercontent.com/79561519/131880068-22d06adf-5c9d-4aaa-96c6-75413d05b786.png)
再一个就是密码明文保存在配置文件中，这感觉可能会有点隐患，要不考虑MD5加密一下再保存，感觉这样可能会好一些

**Comment by jeessy2** [comment]
绑定二个webhook页面复杂了，对于绝大部分人用一个也够了，不过你确实需要这样的功能，欢迎提pr或者跑二个程序，占用的CPU和内存也是非常小的。

既然找到配置文件了，不光是密码是重要资料吧，密码加个密，意义不大了
