### ISSUE TITLE
增加在IP发生变化时进行额外的操作的功能

### ISSUE THREAD

**Issue by HotWaterFlask** [jeessy2/ddns-go#984]
### 功能描述

增加在IP发生变化时除更改域名解析的记录值外进行额外的操作，例如执行命令或重启某个服务以支持更多场景自动化。

### 解决的问题

使某些服务在IP改变时自动重启。

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by HotWaterFlask** [comment]
使用webhook能直接执行命令操作？ 
例如
sc stop PrivateServer
sc start PrivateServer
这种命令...

**Comment by jeessy2** [comment]
这种不行，需要自己写接口实现

**Comment by jeessy2** [comment]
应该不会，大部分人用不到此功能。建议fork自行修改，或者自己写个接口

**Comment by devome** [comment]
https://github.com/ncarlier/webhookd 发送webhook到这个工具可以很容易的实现你的需求。
