### ISSUE TITLE
多IP支持

### ISSUE THREAD

**Issue by lcuwx2016** [jeessy2/ddns-go#987]
### 功能描述

希望支持一个配置文件下的IPv4/IPv6的多IP支持，适合多WAN用户

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
不是有？

**Comment by lcuwx2016** [comment]
不行吧，我试着无法绑定2个IPv6地址到一个域名

**Comment by lcuwx2016** [comment]
![image](https://github.com/jeessy2/ddns-go/assets/31233561/c24f326f-11e6-4508-9fcb-051fd736a40a)

**Comment by jeessy2** [comment]
下方不是写得很清楚了吗？

**Comment by lcuwx2016** [comment]
下方的描述@1或者@2只能指定单独一个地址，无法同时指定两个地址

**Comment by jeessy2** [comment]
#980

**Comment by lcuwx2016** [comment]
使用的服务商暂时没找到对应方法

**Comment by jeessy2** [comment]
换到支持的服务商，有些服务商不支持

**Comment by lcuwx2016** [comment]
等有机会自己写个PR吧。感谢PO主

**Comment by lcuwx2016** [comment]
> 换到支持的服务商，有些服务商不支持

huaweicloud是支持的。但我看文档多IP只有cloudflare

**Comment by jeessy2** [comment]
还有阿里云、腾讯都可以

**Comment by lcuwx2016** [comment]
好的，我看一下
