### ISSUE TITLE
使用caddy反向代理启用 https，无法登陆

### ISSUE THREAD

**Issue by Schr0dingerCat** [jeessy2/ddns-go#99]
在没有 .ddns_go_config.yaml 文件时， 是可以登陆的
但是在页面点击保存，无论是否设置 用户名 密码，再次使用反向代理登陆 都会无法登陆
提示HTTP ERROR 403
caddyfile文件：
```
test1.my.com {
        encode gzip
        tls internal
        reverse_proxy ip:9876
}
```
谢谢大大了

**Comment by jeessy2** [comment]
v2.10.0后默认禁止从公网访问
如需要从公网访问. 通过内网ip登陆后, 取消从公网访问即可

**Comment by Schr0dingerCat** [comment]
> v2.10.0后默认禁止从公网访问
> 如需要从公网访问. 通过内网ip登陆后, 取消`禁止公网访问`的勾选即可

谢谢大大了，我没有从公网访问，我是在内网里使用，caddy 和 ddns-go 通过docker 安装，docker的网络是默认的bridge
