### ISSUE TITLE
callback同一域名同时解析IPV4和IPV6

### ISSUE THREAD

**Issue by xushulang** [jeessy2/ddns-go#990]
### 问题描述

一个callback,同时解析IPV4和IPV6到dynv6的同一个域名，无法获取到#ipv4和#IPV6

### DNS服务商

Callback

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### 版本

v6.0.3

### 安装方式

Docker

**Comment by jeessy2** [comment]
在增加一个配置

**Comment by xushulang** [comment]
> 在增加一个配置

刚刚试了一下用自定义参数解决了

**Comment by Chemyou** [comment]
请问如何自定义参数？遇到相同的问题，全网好像都没找到同时callback解析v4和v6的
