### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by UncleLiuYe** [jeessy2/ddns-go#991]
### 问题描述

我关闭IPV4，启用IPV6之后，解析到我的域名。我在本地开了一个nginx，端口8001。但是，域名能ping通，浏览器无法访问8001端口的nginx。

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

未搜索

### 操作系统

Windows

### 架构

x86_64

### 版本

v6.0.3

### 安装方式

服务

### 额外信息

![QQ截图20240122105227](https://github.com/jeessy2/ddns-go/assets/26851631/306a9f78-24e8-4c4e-8443-fe14487925fe)
![QQ截图20240122105238](https://github.com/jeessy2/ddns-go/assets/26851631/cfbf72ee-b413-4549-a771-e97001d4e8f9)
![QQ截图20240122105316](https://github.com/jeessy2/ddns-go/assets/26851631/801f90aa-f814-483f-bba7-c8c7191ce518)

**Comment by UncleLiuYe** [comment]
浏览器的状态码是HTTP 503，但是nginx的asscess.log里没有发现对应的访问记录。

**Comment by jeessy2** [comment]
直接`localhost:8001`测试一下

**Comment by UncleLiuYe** [comment]
@jeessy2 
![QQ截图20240122111141](https://github.com/jeessy2/ddns-go/assets/26851631/063cb8a5-3130-4e4a-9b9b-ac966ec90d4d)

**Comment by jeessy2** [comment]
检查下nginx配置，看监听地址

**Comment by UncleLiuYe** [comment]
@jeessy2 谢谢！
![QQ截图20240122112214](https://github.com/jeessy2/ddns-go/assets/26851631/695fede2-5143-46a3-98e2-b2f257be2c51)

**Comment by UncleLiuYe** [comment]
他已经生效了，感谢您的付出！
