### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by UncleLiuYe** [jeessy2/ddns-go#992]
### 问题描述

NGINX配置了IPV6访问了，我的没有配置路由器，直接光猫连到主机上。现在是局域网可以通过域名+端口访问nginx。但是我把手机的WIFI关闭，使用5G，并且测试了支持IPV6的手机上，无法访问NGINX，请问有什么方法在公网上访问吗？谢谢。

### DNS服务商

Alidns(阿里云)

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Windows

### 架构

x86_64

### 版本

v6.0.3

### 安装方式

服务

### 额外信息

无

**Comment by UncleLiuYe** [comment]
![26ffd17c5c6d8ed953acf96c13e9b795](https://github.com/jeessy2/ddns-go/assets/26851631/caebd498-eeca-420b-925a-b5c4303d483f)

**Comment by jeessy2** [comment]
自行检查，防火墙之类的

**Comment by UncleLiuYe** [comment]
@jeessy2 windows的防火墙已经关闭了，但是这个光猫的我去后台看了看防火墙是没有启用的状态。
