### ISSUE TITLE
有没可能增加免费证书申请，自动续期功能？

### ISSUE THREAD

**Issue by ocoj** [jeessy2/ddns-go#996]
### 功能描述

有没可能增加免费证书申请，自动续期功能？证书申请后自动推送到指定的存方目录

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现

**Comment by jeessy2** [comment]
没有。有其他三方工具，可搭配使用。比如https://github.com/NginxProxyManager/nginx-proxy-manager
